### ISSUE TITLE
Building: makerom: -nocodepading not found

### ISSUE THREAD

**Issue by mariogamer2** [LumaTeam/Luma3DS#10]
Latest makerom...

**Comment by AuroraWright** [comment]
You need it to build it from source. That's why I said "a recent build".

**Comment by mariogamer2** [comment]
build it from source? from 3ds_injector? if makerom,it's already done.

**Comment by AuroraWright** [comment]
Then it works. I meant makerom.

**Comment by mariogamer2** [comment]
?

**Comment by mariogamer2** [comment]
Just re-updated,it's always not working...

makerom -f ncch -rsf ../loader.rsf -nocodepadding -o /home/**/AuReiNand/injector/injector.cxi -elf /home/**_/AuReiNand/injector/injector.elf
[SETTING ERROR] Unrecognised argument '-nocodepadding'
[RESULT] Invalid arguments, see 'makerom -help'
/home/_**/AuReiNand/injector/Makefile:121: recipe for target '/home/**_/AuReiNand/injector/injector.cxi' failed
make[2]: *_\* [/home/_**/AuReiNand/injector/injector.cxi] Error 252
Makefile:103: recipe for target 'build' failed
make[1]: *_\* [build] Error 2
make[1]: Leaving directory '/home/*_**/AuReiNand/injector'
Makefile:74: recipe for target 'build/patches.h' failed
make: *_\* [build/patches.h] Error 2

**Comment by mariogamer2** [comment]
It's strange...

When doing the command by myself,it's work but not the makefile...

**Comment by jixunmoe** [comment]
I made a few lines of modification and build with Msys's gcc, and it works.

Repo: [profi200/Project_CTR](https://github.com/profi200/Project_CTR/tree/master/makerom)

``` patch
--- a/makerom/utils.c
+++ b/makerom/utils.c
@@ -185,7 +185,7 @@ bool AssertFile(char *filename)
 {
        if(filename == NULL)
                return false;
-#ifdef _WIN32
+#ifdef _WIN32_x
        struct _stat64 st;
        return _stat64(filename, &st) == 0;
 #else
@@ -196,7 +196,7 @@ bool AssertFile(char *filename)

 u64 GetFileSize64(char *filename)
 {
-#ifdef _WIN32
+#ifdef _WIN32_x
        struct _stat64 st;
        if( _stat64(filename, &st) != 0)
                return 0;

--- a/makerom/oschar.h
+++ b/makerom/oschar.h
@@ -36,8 +36,8 @@ typedef char oschar_t; // UTF8
 #define os_closedir _wclosedir
 #define os_chdir _wchdir

-#define _osstat _stat64
-#define os_stat _wstat64
+#define _osstat stat
+#define os_stat stat

 #define os_fopen _wfopen
 #define OS_MODE_READ L"rb"
```
