### ISSUE TITLE
Enabling Dev function causes 022-2454 on NNID logging-in and other e-shop related access

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#100]
As topic.
Seemed it had been existed for a long time.
Closing Dev function resolves this problem.

If this is not a bug, I would like to see adding this to Luma Dev's description.

**Comment by rboninsegna** [comment]
Yep, it's "normal", and it was kinda documented last time I checked (as "breaks eshop access" though, while it actually conflicts with **retail NNIDs and Amiibos**) :)

**Comment by TuxSH** [comment]
It's because we set UNITINFO to 2, see [here](https://github.com/AuroraWright/Luma3DS/blob/developer/source/firm.c#L333).

**Comment by urherenow** [comment]
@TuxSH, not to hijack the issue and turn it into a programming lesson, but I thought a number in brackets "[2]" had something to do with an array.

Just a bit confused...

**Comment by TuxSH** [comment]
section[2] is the 3rd FIRM section, for NATIVE_FIRM it's the ARM9 one.

**Comment by RShadowhand** [comment]
@TuxSH Is there a way to get the verbose debug info on error screen without causing NNID issues?

**Comment by TuxSH** [comment]
[Yeah](https://github.com/AuroraWright/Luma3DS/pull/19/commits/6351e5b8c3f04b1d08bb5fb4099fee67a76198a6) but it was decided to modify UNITINFO after some debate because it's needed for other stuff.

**Comment by fincs** [comment]
Why not patch act/mint/eShop/whatever to think UNITINFO is retail?

**Comment by rboninsegna** [comment]
(Kinda OT)

It's pretty funny that Big N put some verbose details in retail Wii U errors though!

**Comment by RShadowhand** [comment]
@TuxSH Could you visit IRC for a moment?

**Comment by TuxSH** [comment]
Fixed in https://github.com/AuroraWright/Luma3DS/commit/2424865fa109610b81cf9babe351addd72f86cd7, I guess.

**Comment by sykhro** [comment]
UNITINFO is sent via post to whatever Nintendo server, i.e. when accessing the e-shop. you could just patch the request header

**Comment by TuxSH** [comment]
I made it multi-choice (no feature, stuff + ErrDisp patch, stuff + UNITINFO patch), that's simpler.
