### ISSUE TITLE
ErrDisp pokemon ultrasun

### ISSUE THREAD

**Issue by Danksi** [LumaTeam/Luma3DS#1001]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39E SysNAND, 11.6.0-39E EmuNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9strap 1.3

**Luma3DS version:**
8.1.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (Yes)

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

With luma 8.1.1 and boot9 1.3 I get the following crash black screen error while playing pokemon ultrasun (the positive thing is that i've got it only twice, today, and yesterday in the morning):

An error occurred (ErrDisp)

Error type: generic
Process ID: 38
Process name: momiji
Process title ID: 0x00040000001b5000

Adress: 0x00346e74
Error code: 0xo96045b

Press any button to reboot

I've started getting it since I used GodMode9 to reset the NNID of my old 3ds with CFW, since I updated ultrasun to 1.1 and since I got Pokemon Bank.

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by sora10pls** [comment]
>Enable game patching: (Yes)

Do you have any CROs from 1.0 on your SD Card being loaded through Luma LayeredFS? What about `code.bin`? If there's a mismatch between 1.0 and 1.1 with either of those, you're guaranteed a crash.

**Comment by Danksi** [comment]
I'm sorry Sora, but I dont understand what you're saying. This happened me  after I updated ultrasun (physycal cartridge) to 1.1 so maybe the error is related to this

I would try what you say though, but I dont know what a CRO or LayeredFS is.

EDIT: I deleted the updated data through data management in system settings. Would redownloading the update solve the crash problems?

**Comment by ghost** [comment]
This is almost always a result of a damaged SD card or running un-updated mods such as the No-Outlines Patch on versions it doesn't support.

**Comment by Mucephie** [comment]
I've got this same error, same error screen information, running Luma 9 and sysnand 11.7.0 , SD card is fine, no mods at all. Anyone have a clue ? Sometimes I get it before I even load the save(example: title screen)
