### ISSUE TITLE
Costum Splash Screens

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1004]
New 2DS XL
Sys 11.6.0-39E
Payload type: SIGHAX
Luma3DS: 9.0-2a840f2
Screen brightness: (4)
Splash: (Before)
PIN lock: (Off)
New 3DS CPU: (Off)

I tired installing a costum splash screen via Anemone but got the error that Splashes are disabled in Luma config. So i rebooted the console, changed the Splash option from Off to Before and saved it.
I tried installing the splash screen again but got the same message again. So i rebooted again, changed it from Before to After and tried again. Still nothing.
I downloaded the theme to my computer, put both splash.bin and splashbottom.bin in the Luma folder and tried it again, and it still didnt work.
I then hacked my Old 3DS and it worked there on my first try.

I hope my gibberish makes sense.
Thanks

**Comment by james-d-elliott** [comment]
https://github.com/astronautlevel2/Anemone3DS/issues

If it's not detected in Anemone it is probably an issue there. To me it not working on one console but on another sounds more like a user specific issue. Either the splashes are in the wrong location or need to update something.

You may want to rename the  luma folder and recreate it with fresh downloads as well as Luma3DS itself on the root, obviously backup everything first. just in case.
