### ISSUE TITLE
compiling error?

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#1005]
collect2.exe: error: ld returned 1 exit status
make[1]: *** [build/rosalina.elf] Error 1
make[1]: Leaving directory `/c/Build_Luma3DS/Luma3DS/sysmodules/rosalina'
make: *** [build/rosalina.cxi] Error 2

what do i need to update?

**Comment by Qyriad** [comment]
You need the latest commit of libctru.
