### ISSUE TITLE
Heap for SKATER Browser ends before it should?

### ISSUE THREAD

**Issue by frozenLake** [LumaTeam/Luma3DS#1008]
Honestly, I'm not sure about if the data is out of bounds or if it stores it in a separate location, but the heap for the browser, when viewed through Rosalina's Ram Viewer does not display any of the html of the page that is currently being viewed. ih8ih8sn0w on the discord reported that the heap was "stopping well before anything relevant exists", but this might be flawed if it stores it in a more obscure memory location. I am not entirely sure.

**Comment by TuxSH** [comment]
Closing, tracker cleanup
