### ISSUE TITLE
Arm11 Exceptions

### ISSUE THREAD

**Issue by vaggelisgol** [LumaTeam/Luma3DS#1014]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

9.2.0-20E SysNAND, 11.6.0-39E EmuNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.1.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: ( 4)

Splash: (off )

PIN lock: ( )

New 3DS CPU: (Clock+L2 )

--

Autoboot EmuNAND: ( x)

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x )

Show NAND or user string in System Settings: ( x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
I've recently migrated from reinand to luma3ds cfw.Now more than half of my cia packages , when booted , give me an arm 11 crash .I've tried many versions of luma3ds but with no luck . i have multiple crash dumps attached

**Steps to reproduce:**

1.boot into emunand's home menu

2.choose a game and launch it

3.wait for the nintendo 3ds splash screen

4.Crash

**Dump file:**
[luma crashdumps.zip](https://github.com/AuroraWright/Luma3DS/files/1649641/luma.crashdumps.zip)

**Comment by ghost** [comment]
`<plutobot> [3DS] Module: FS (17) | Description: NCCH hash-check failed? (fs) (391) | Summary: Wrong argument (8) | Level: Permanent (27)`

Your CIAs were/are corrupted or damaged and thus so are your installs. Not Luma's fault, it just happens to catch a problem that ReiNAND misses.
