### ISSUE TITLE
how to install the LUMA 9.0 files

### ISSUE THREAD

**Issue by jem999** [LumaTeam/Luma3DS#1017]
just wondering how to install the LUMA/arm11 files to the sd card where do the files go in terms of file structure or installation
https://github.com/AuroraWright/Luma3DS
jem999
NEWB

**Comment by piratesephiroth** [comment]
What are yout talking about? You should be looking at the releases

**Comment by Margen67** [comment]
# THIS IS NOT A SUPPORT FORUM! For support go here:
# Nintendo Homebrew: https://discord.gg/MjzatM8
