### ISSUE TITLE
Exception - PrefetchAbort (svcBreak) on out of region game

### ISSUE THREAD

**Issue by Andrevus2** [LumaTeam/Luma3DS#1018]
**System model:**

Old 3DS XL EU

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39E

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

9.0 Stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (X)

Enable game patching: (X)

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

I tried launching the US version of Tomodachi Life on an EU system. During the initial 3DS splash screen it hangs for a few miliseconds before continuing, then the system crashes with an "Exception occured"

Processor : Arm 11 (Core 0) 
Exception type : Prefetch abort (svcBreak) 
Fault status : Debug event 
Current Process: app (000400000008C300)

If i disable Arm 11 exception handlers (which i usually don't do.) the game just boots me back to the OS saying "an error has occured, the system will now reboot" , 

**Steps to reproduce:**

1. Install US game on an EU system with Luma already on.

2. Launch game.

**Dump file:**

[crash_dump_00000016.zip](https://github.com/AuroraWright/Luma3DS/files/1661816/crash_dump_00000016.zip)

**Comment by ghost** [comment]
The game likely requires locale emulation; some out of region games do. Luma supports this; it's detailed in  [the wiki](https://github.com/AuroraWright/Luma3DS/wiki/Optional-features).
