### ISSUE TITLE
[Feature Request] Store Rosalina config in a separate file

### ISSUE THREAD

**Issue by sora10pls** [LumaTeam/Luma3DS#1020]
Currently, any changes made to Rosalina are saved to `sdmc:/luma/config.bin`. While this works, on newer releases where the old `config.bin` is discarded, so are changes made to Rosalina's settings (namely your activation keycombo).

Having to re-enter this on every new release where the old configuration is discarded is annoying, the simple solution would be to store it in a separate file (something like `rosalinaconfig.bin`).

**Comment by ghost** [comment]
#752
