### ISSUE TITLE
HELP! (An exception occurred.  processor:  ARM11 ((core 0)). exception type: prefetch abort .  fault status: Translation selection  menu((000400300008f02))

### ISSUE THREAD

**Issue by jboone321** [LumaTeam/Luma3DS#1022]
I'm trying to load soundhax on my 3ds 9.6,0-10U.   When I boot it, it goes to luma 3ds configuration. 

here are the settings

Autoboot EmuNAND: (x)

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

Afterwards, I go on Nintendo 3ds Sound and go on nedwill. After that I get the error. Please HELP!
[crash_dump_00000000.dmp.zip](https://github.com/Auror
[crash_dump_00000000.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/1691213/crash_dump_00000000.dmp.zip)
aWright/Luma3DS/files/1691210/crash_dump_00000000.dmp.zip)

Theres the crash dump if needed.

**Comment by ghost** [comment]
You can't use soundhax with Luma v8.0 or higher, you must use Rosalina's takeover title method.

**Comment by jboone321** [comment]
Thank you. 









*but who the f--- said you can close this thread*

**Comment by ghost** [comment]
I did.
