### ISSUE TITLE
OK. I've been to a method on how to fix this. its called Rosalinda takeover title method, but I need someone to elaborate on what that is? 

### ISSUE THREAD

**Issue by jboone321** [LumaTeam/Luma3DS#1023]
I'm trying to load soundhax on my 3ds 9.6,0-10U. When I boot it, it goes to luma 3ds configuration.

here are the settings

Autoboot EmuNAND: (x)

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

Afterwards, I go on Nintendo 3ds Sound and go on nedwill. After that I get the error. Please HELP!
[crash_dump_00000000.dmp.zip](https://github.com/Auror
crash_dump_00000000.dmp.zip
aWright/Luma3DS/files/1691210/crash_dump_00000000.dmp.zip)

Theres the crash dump if needed.

**Comment by jboone321** [comment]
FRAP that's supposed to say *told a method.

**Comment by jboone321** [comment]
*crap.

**Comment by ihaveamac** [comment]
you know you can edit your issue title and posts, right? especially given the issue body here is completely unrelated to the title.

**Comment by ghost** [comment]
The issue tracker isn't for tech support. There's even a place exactly for that in the ISSUE_TEMPLATE.md.

**Comment by jboone321** [comment]
Hikari STOP CLOSING SHIT.

**Comment by ihaveamac** [comment]
go somewhere else for tech support.
