### ISSUE TITLE
Once softlocked, if I try to switch the Wi-Fi off, Rosalina will provide an error report:

### ISSUE THREAD

**Issue by Ciromx** [LumaTeam/Luma3DS#1028]
Hey, guys and gals. For a while now my 3DS has been exhibiting some strange behaviour and I suspect there is a problem with my firmware. My system specs:
O3DS XL
11.6 U sys firm
Luma and boot9strap on last patch...
My 3DS can use the eShop, it can use online features of games, and some games can successfully update (Pokémon Moon, for example, will update; Animal Crossing New Leaf would not [finally got it to update after 3 hours of trying different methods of updating]).
And once softlocked, if I try to switch the Wi-Fi off, Rosalina will provide an error report:
Error type: generic
Process ID: 25
Process name: nwm
Process title ID: 0x0004013000002d02
Address: 0x00103218
Error code: 0xf9606c05
How do I solve the problem?
I have a lot of games on my SD CARD and i dont want lose then on downgrade

(I tried downgrade too) but the problem continues...

I appreciate any advice/assistance. I will try my best to provide more information if it is needed.

**Comment by ghost** [comment]
Can't reproduce this, doesn't seem like a Luma issue. Either your system is corrupted in some manner or your wireless hardware is damaged.
