### ISSUE TITLE
Error on Rosalina debbug option!

### ISSUE THREAD

**Issue by Ciromx** [LumaTeam/Luma3DS#1029]
When i put the Debbug option,was fail...

![27836258_533438753715934_1345840084_o](https://user-images.githubusercontent.com/36171807/35890540-5607bb24-0b87-11e8-9746-98c41d4d4f04.jpg)

when i try again,i received that...

![27835500_533437747049368_57935112_o](https://user-images.githubusercontent.com/36171807/35890394-c4af74dc-0b86-11e8-995f-cce950c930a4.jpg)

What i should doo?

**Comment by SmackBro** [comment]
#834 Already known bug,the only thing you can do is check your Wifi settings,this mostly happens,if you enable the debugger when Wifi is disabled or the console wasn't able to connect to wifi,if you go into rosalina too fast.

**Comment by ghost** [comment]
Duplicate of #743 or #834.

**Comment by asfaew** [comment]
i have an ussie where it says failed 0xffffffff

**Comment by asfaew** [comment]
issue not ussie
