### ISSUE TITLE
Rosalina Minor Bug

### ISSUE THREAD

**Issue by aron11195** [LumaTeam/Luma3DS#1031]
**System model:**

New 3ds XL

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap/Sighax

**Luma3DS version:**

9.0-2a840f2

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (3)

Splash: Before(x)

PIN lock: Off(x)

New 3DS CPU: Off(X)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
rosalina options for the New 3ds Menu are reverse. It's a known issue that MGS 3ds always crashes when intro song comes on if you're using overclock so im gonna be using MGS 3ds as my example.

Option 1:
Enable L2 cache
Set Clock Rate to 804MHz
game runs normal (which is kinda slow)

Option 2:
Disable L2 cache
Set Clock Rate to 268MHz
game runs faster

**Steps to reproduce:**

1. Run MGS, stay on the intro screen where it says Press Any Button and roughly 15 secs the game intro comes on. MGS 3ds DOES NOT crash when intro song comes on when im using Option 1.

2. Run MGS, stay on the intro screen where it says Press Any Button and roughly 15 secs the game intro comes on. MGS 3ds DO crash when the intro song comes on when im using Option 2.

**Dump file:**

**Comment by ghost** [comment]
The options are not reversed. That you see "Disable L2 cache, Set clock rate to 268MHz" means that the system is in 804MHz+L2 mode. Additionally, MGS is capped at 20fps on 3DS, the slowness is to be expected.
