### ISSUE TITLE
SD things broken when booting Luma from NAND

### ISSUE THREAD

**Issue by shny-scott** [LumaTeam/Luma3DS#1032]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U, no emu/redNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

9.0

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (3)

Splash: (Before)

PIN lock: (Off)

New 3DS CPU: (Clock+L2 Cache)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (X)

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: (...yes? It's not in the config menu...)

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Splashes and game patches (code.ips and code.bin) don't work when booting Luma off the NAND.

**Steps to reproduce:**
1. Load Luma on to the 3DS with setup_ctrnand_luma3ds.gm9
2. Boot Luma without its boot.firm on the SD card
3. Attempt to look at your splash or use game patches

This was fixed by renaming my Luma boot.firm back to boot.firm.

**Comment by ghost** [comment]
Duplicate of other issues; this is by design, if Luma is loaded from the NAND, it will also look for splashes, game patches, etc. on the NAND instead of the SD card.
