### ISSUE TITLE
LayeredFS game patching not working with USA Tomodachi Life

### ISSUE THREAD

**Issue by 0ICED0** [LumaTeam/Luma3DS#1034]
I have attempted to patch my USA version of Tomodachi Life with a music hack. When I select the option "Enable game patching" with all my files in G:\luma\titles\(Tomodachi Life's title id)\romfs\ nothing happens. All of the files I wish to patch are in the right places but nothing would load. I have attempted this on other regional versions of the game and have only had success on the Korean version of the game. (Attempted on Luma 9.0)

**Comment by 0ICED0** [comment]
The console I am using is a North American New 3ds XL

**Comment by AuroraWright** [comment]
Can you send me the files you modified and tell me when they're meant to be played? I debugged the game and layeredfs works fine... (I even tested that the sound folder is redirected by trying both clone_sound.bcsar and a file in /sound/stream/ ).

**Comment by 0ICED0** [comment]
@AuroraWright What service should I send you the files and info on?

**Comment by AuroraWright** [comment]
You can upload them to transfer.sh or similar

**Comment by 0ICED0** [comment]
(Hopefully I am doing this right) https://transfer.sh/BKksW/Clone_map_day02a.dspadpcm.bcstm replaces the daytime music outside, it goes in \sound\stream. I have tested this by rebuilding the game and it works as intended but rebuilding is icky and slow.

**Comment by 0ICED0** [comment]
This might be useless, but I use a 32gb micro sd card formatted as FAT32.

**Comment by Shadow322** [comment]
Fat32 is all the 3ds can read LOL
