### ISSUE TITLE
Metal Gear Solid: Snake Eater 3D ‒ Crash after Intro with any New 3DS CPU feature enabled

### ISSUE THREAD

**Issue by Dragios** [LumaTeam/Luma3DS#1039]
**System model:** New 3DS XL
**SysNAND version (+emu/redNAND version if applicable):** 11.6.0-39U SysNAND
**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap 1.3
**Luma3DS version:** 9.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)
Screen brightness: (1)
Splash: (After payloads)
PIN lock: (Off)
New 3DS CPU: (Clock + L2 only)

--

Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Enable game patching: (x)

Show NAND or user string in System Settings: (x)
Show GBA boot screen in patched AGB_FIRM: (x)
Patch ARM9 access: ( )
Set developer UNITINFO: ( )
Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Crash when trying to play a video after Metal Gear Solid: Snake Eater 3D intro. Does not happen with New 3DS CPU feature turned off.

**Steps to reproduce:**

1. Open the game and let it run until the intro finish. (Make sure to enable any New 3DS CPU feature 1st)

**Dump file:**
[arm11 crash dump.zip](https://github.com/AuroraWright/Luma3DS/files/1750461/arm11.crash.dump.zip)

**Comment by ghost** [comment]
This is not a Luma issue. Not all games are compatible with New 3DS mode.
