### ISSUE TITLE
Amiibo Reading Issue on o3ds

### ISSUE THREAD

**Issue by CrimsonMaple** [LumaTeam/Luma3DS#104]
I have a pikachu amiibo and attempted to play with it on Smash and the amiibo was unable to be played. The console stated the amiibo was not meant for Smash. The amiibo had just been used on my friend's n3ds so it's not corrupted.

**Comment by DonDalle** [comment]
The o3DS doesn't support amiibo.

**Comment by Shadow322** [comment]
Yes it does with the 3DS NFC Reader/Wrighter for Nintendo 2DS, 3DS and 3DS XL :)

**Comment by CrimsonMaple** [comment]
I have the amiibo reader :P 
Wouldn't have opened other wise.
What kind of noob do you take me for? Kek.

**Comment by TuxSH** [comment]
Did you try the 5.5 release build (not the dev one)?
It's likely an issue with UNITINFO set to the dev. value.

**Comment by CrimsonMaple** [comment]
That was the issue, heh. Well then gonna close this! Thanks everyone taking the time to help my stupid mistake!
