### ISSUE TITLE
[feature request] increase lock to 10 digit pins

### ISSUE THREAD

**Issue by Luro02** [LumaTeam/Luma3DS#1040]
Hey,
I would like to use more than 8 digits for my 3DS pin may it be possible to increase the number ?

Thanks :)

**Comment by RS55** [comment]
Konami Code is that you? xD It would be a good idea

EDIT: What edited?

**Comment by Luro02** [comment]
I expected that nobody would guess it.. 🤣
To be honest I want this feature more because of nostalgia instead of Security.

**Comment by Auvrae** [comment]
I was just thinking about this LOL

**Comment by MarioMasta64** [comment]
same

**Comment by Sayora77** [comment]
I fifth the motion.

**Comment by figgyc** [comment]
should probably just remove the limit altogether
