### ISSUE TITLE
Smash Bros Exception Occurred

### ISSUE THREAD

**Issue by SenseiVin** [LumaTeam/Luma3DS#1044]
-- Please fill in the placeholders.-->
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.6.0-39U SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[. Boot9Strap.]

**Luma3DS version:**

Luma 9.0 Nightly

**Luma3DS configuration/options:**

Default EmuNAND: ( 1)

Screen brightness: (4 )

Splash: (Off )

PIN lock: Off( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (Enabled )

Show NAND or user string in System Settings: (Enabled )

Show GBA boot screen in patched AGB_FIRM: (Disabled )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
When loading up smash with a character retexture (title mods and main menu mods work perfectly fine) without smash selector an exception occurred pops up. The dump is shown at the end of the issue.

**Steps to reproduce:**

1.Install any character retexture or stage retexture on the old 3ds on the latest version of smash

2.Load up game

**Dump file:**
)
[crash_dump_00000000.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/1778559/crash_dump_00000000.dmp.zip)

**Comment by cetertel** [comment]
I had a similar problem when loading mods, but for some reason backing up, deleting, and then restoring my save data fixed it. It seems to be a problem within Super Smash Bros. and not a problem with Luma itself.
