### ISSUE TITLE
Luma updater v2.2 could not obtain update

### ISSUE THREAD

**Issue by jaycollier619** [LumaTeam/Luma3DS#1048]
I am running Luma 3 DS version 9.0 I have boot9strap when I open Luma updater version 2.2 it comes up with an error message that says could not obtain update details check that the console is connected to the internet
My 3 DS is connected to the internet I don't know what to do

**Comment by urherenow** [comment]
Then why not post an issue on the Luma updater page? What you do is download the latest release from here and drop it onto your card, or clone the repository and build the latest nightly yourself, or follow one of the nightly links in the temp forum.

**Comment by Sonlen1414** [comment]
The Luma Updater is made by someone else and was actually updated to work, v2.3, download and install the new version.
