### ISSUE TITLE
Make Nightly for 3DS not working.

### ISSUE THREAD

**Issue by CrafterGamer** [LumaTeam/Luma3DS#1049]
Hey i have a problem.
In the code MyThread Line:43 get srvSetBlockingPolicy(true);
My Devkit have not this function why?

sorry for my bad english, i m a german.

How can i fix this?
thanks

**Comment by TuxSH** [comment]
You need to use ctrulib's lastest commit.

Clone/download the repo, then open the folder in a terminal, and type `cd libctru && make install`.

**Comment by CrafterGamer** [comment]
thanks
