### ISSUE TITLE
Issue in rosalina with last commit (fed6285 and 938cb64)

### ISSUE THREAD

**Issue by RS55** [LumaTeam/Luma3DS#1050]
there is a problem after the implementation of cheats, I do not know if it only happens in Old 3DS but the option "New 3DS menu" is shown and the screenshots option is removed.

**Comment by ValShaped** [comment]
Tested on New 2DS, this seems to be an Old 2/3DS bug.
If I were to guess, "New 3DS Menu" is hidden by omission of the menu item that had its position, and adding "Cheats..." offset the rest of the menu by one.

**Comment by FateForWindows** [comment]
The commit seems to have introduced problems with TWLoader. I'm not sure if this is a Luma problem or a TWLoader problem. Crash dump can be found in the [gbatemp](https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/page-447#post-7890433) thread.
