### ISSUE TITLE
[Bug Report] Console to error while games runs with Rosalina

### ISSUE THREAD

**Issue by ghoul001** [LumaTeam/Luma3DS#1052]
-- Please fill in the placeholders.-->
**System model:**
Old 3DS  Xl

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.6.0-39U SysNAND

**Entrypoint

BootStrap stable

**Luma3DS version:**
Luma 9.0 stable 25/3/2018

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (2 )

Splash: (no)

PIN lock: (no)

Autoboot EmuNAND: (no)

Use EmuNAND FIRM if booting with R: (no)

Enable loading external FIRMs and modules: (no)

Enable game patching: (no)

Show NAND or user string in System Settings: (no)

Show GBA boot screen in patched AGB_FIRM: (no)

Patch ARM9 access: (off)

Set developer UNITINFO: (off)

Disable ARM11 exception handlers: (no)

--

**Explanation of the issue:*
it all started when i was palying hyrule warrios legends in the night i was in the adventure mode on the mission as tingle and suddenly the game freezes and show 
error type: generic

Process Id : 39
Process name: Iron 15
Process title Id: 0x000400000017a800

address:0x0022e79c
Error code:0xd900458b

and after that the 3d image stop working properly, it activates alone when i move the top screen and the 3d switch doesn´t work also other games has been afacted like a patch version of fire emblem fates(just when the game launch) stella glow( this one appears after a few minutes),Beyond the Labyrinth (when i load my save file).I have tried with my other games like ultrasun and my 3ds game cartridge(smash) and
work fine 

**Dump file:**
i dont found any file like that on my sd

**Comment by ghost** [comment]
It's likely your save data is corrupted. It's possible your SD card is damaged.
