### ISSUE TITLE
April Fools joke

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#1057]
the April Fools joke is still in the code please remove

"Luma3DSv9.0-joyconhax-9d507e04"

**Comment by ihaveamac** [comment]
it's just a 9.0 re-upload, and marked as a pre-release.

**Comment by ghost** [comment]
if you build the latest version of luma it shows in the config menu I can confirm this. also the April fools update should get pulled its not April 1st anymore
