### ISSUE TITLE
[suggestion] implement optional use of out of region software keyboards

### ISSUE THREAD

**Issue by prayerie** [LumaTeam/Luma3DS#106]
I've spent quite a while trying to replace the system keyboard with the JP one, as it allows for both alphanumeric and jp input, to no avail. (changed title id, etc etc). As far as I understand, seeing as they have different titleids, different firmwares call for different titles (eu calls 0000D002, jp 0000C002, etc) when the keyboard is needed. Hence, it should be theoretically possible to somehow modify this, so if we installed an out of region keyboard, the system would instead load that title, instead of the default.

For example, when playing Japanese titles, having only alpha-numeric input is going to be an issue. Also, many people are going to want to type in Japanese without changing region.

**Comment by fincs** [comment]
Should be a pretty simple NS sysmodule patch.

**Comment by prayerie** [comment]
@fincs oh, nice. I'd attempt a PR if I knew anything at all about this, but I don't :|

**Comment by urherenow** [comment]
+1

Considering I live in Japan, but use a US, console, I would love this feature! It would be nice to be able to use a Japanese greeting for my streetpasses...

**Comment by prayerie** [comment]
@urherenow For now, I think you can export and modify the extdata on PC to change the greeting. (but still, that's incredibly annoying to do)

**Comment by MaiconErick** [comment]
Besides in game custom built keyboards, I know that USA 3DS doesn't have support for Korean input.
It doesn't even display the title of the game if you make a homebrew with Korean characters. Just a bunch of black squares with "?". It has support for Japanese, though.

**Comment by fincs** [comment]
Korean consoles have a special system font with Korean characters. None of the other versions of the system font have Korean characters.

**Comment by TuxSH** [comment]
Closing, tracker cleanup
