### ISSUE TITLE
Gets an error after reinstalling my NAND back up file

### ISSUE THREAD

**Issue by PsychoOreo** [LumaTeam/Luma3DS#1061]
**System model:**

[New 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[9.0]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (1)

Splash: (OFF)

PIN lock: (OFF)

New 3DS CPU: (OFF)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (X)

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
I tried restoring my NAND back up which is an old one, (I made that back up when boot9strap was relased) when I try to start my device this error pops out. with or without the SD card. I tried using this solution, [https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting](url) I can now start the 3DS if "Enable loading external firms and modules" is enabled but the applications freezes when I start any of them, I can't see my sysNAND version and I can't access the FBI installer coz it freezes. Again, this issue happened when I restored my old sysNAND back up. Thanks for helping out

**Steps to reproduce:**

1.

2.

**Dump file:**

[arm11.zip](https://github.com/AuroraWright/Luma3DS/files/1887677/arm11.zip)

**Comment by ghost** [comment]
Sounds like your NAND backup is damaged in some way.
