### ISSUE TITLE
Rosalina doesn't work whilst running RetroArch (freezes)

### ISSUE THREAD

**Issue by gingerbeardman** [LumaTeam/Luma3DS#1063]
**System model:**

N3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39E

**Entrypoint (How/what you're using to boot Luma3DS):**

B9S

**Luma3DS version:**

9.0

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (2)

Splash: (off)

PIN lock: (off)

New 3DS CPU: (clock+L2)

--

Autoboot EmuNAND: (n)

Use EmuNAND FIRM if booting with R: (n)

Enable loading external FIRMs and modules: (n)

Enable game patching: (y)

Show NAND or user string in System Settings: (y)

Show GBA boot screen in patched AGB_FIRM: (n)

Patch ARM9 access: (n)

Set developer UNITINFO: (n)

Disable ARM11 exception handlers: (n)

--

**Explanation of the issue:**

Rosalina doesn't work whilst running RetroArch

**Steps to reproduce:**

1. Open a RetroArch emulator

2. Press Rosalina combo

3. Freezes

**Dump file:**
n/a

**Comment by ghost** [comment]
This is a known issue with the way certain applications handle graphics. Same issue occurs with 3DSident. Unlikely to a Luma issue.
