### ISSUE TITLE
ARM11 Data Abort Crash with Mario Kart 7 on Old 2DS

### ISSUE THREAD

**Issue by bharadwaj-raju** [LumaTeam/Luma3DS#1064]
**System model:** Old 2DS

**SysNAND version (+emu/redNAND version if applicable):** 11.6.0-39U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** 9.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 )

Screen brightness: ( 4 )

Splash: ( Off )

PIN lock: ( Off )

New 3DS CPU: ( ) 
*Not Applicable (Old 2DS)*

---

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( X )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

---

**Explanation of the issue:**

Mario Kart 7 (with latest update from Nintendo) crashes (ARM11 data abort) on the screen that appears after selecting "Single Player".

**Steps to reproduce:**

1. Launch Mario Kart 7

2. Press "OK" when told to make a Mii character

3. Press "Single Player"

4. Crash

**Dump file:**

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1910034/crash_dump_00000000.zip)

**Comment by bharadwaj-raju** [comment]
DS games using TWLoader work perfect. Homebrew 3DS games like Super-Haxagon work perfect.

It said a "Read Error", so perhaps a problem with the SD card? It's brand new, though...

**Comment by bharadwaj-raju** [comment]
After creating a Mii character (which wasn't strictly necessary for the functioning of the game), it runs and hasn't crashed yet (2 test plays of ~15 mins each).

**Comment by bharadwaj-raju** [comment]
Further crashes have occurred. In order of occurence:

1. When I tried to play online multiplayer: It found players and then crashed.
  "data abort: Permission - Page"
  [crash_dump_00000001.zip](https://github.com/AuroraWright/Luma3DS/files/1910585/crash_dump_00000001.zip)


2. I went to the Mii and enabled sharing, then I started MK7 and it crashed on title/loading screen.
  "prefetch abort: Permission - Section"
  [crash_dump_00000002.zip](https://github.com/AuroraWright/Luma3DS/files/1910586/crash_dump_00000002.zip)


3. I went to online multiplayer again, played a match successfully, but when attempting to play another, it crashed when it had just picked the track.
  "data abort: Translation - Section"
  [crash_dump_00000003.zip](https://github.com/AuroraWright/Luma3DS/files/1910589/crash_dump_00000003.zip)

**Comment by noirscape** [comment]
Have you considered reinstalling MK7 (use Checkpoint to back up your save data)? 

This sounds in part like it could be a broken installation caused by SD corruption.

**Comment by ghost** [comment]
Can't reproduce, likely game data or save file corruption.

**Comment by bharadwaj-raju** [comment]
I redownloaded, reinstalled and reformatted the SD, and haven't encountered a problem yet. Thanks for your help! I was unsure whether an SD card format or game redownload would be needed, since the SD card was new and the game played mostly fine in other parts.

Thanks!

**Comment by Lxxxst** [comment]
Hello i have your same problem, but only when i go to multiplayer i select the kart and then it crashes. What should i do?

**Comment by johanworklance** [comment]
Hi, me too, i have the same problem with mario kart, when i'm in the kart selection screen online
[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/12798024/crash_dump_00000000.zip)

**Comment by johanworklance** [comment]
Online now works for me, I think it was something about the Nintendo servers, anyway there are many hackers.
