### ISSUE TITLE
[Feature Request] Amiibo scanning simulation

### ISSUE THREAD

**Issue by ederenzi78** [LumaTeam/Luma3DS#1066]
I don't know if it's feasible but it would be nice to have a feature to virtually put an Amiibo on the NFC sensor in order to unlock game features without actually using the figurines. In order to do this, Luma could use the ROM inside each Amiibo (which the used should have put inside a specific folder).

**Comment by Shadow322** [comment]
never happening as this would support piracy

**Comment by ederenzi78** [comment]
Disabling the Nintendo signing check on ticket validation is already supporting piracy.

**Comment by Dimensional** [comment]
Not solely, like your suggestion. Disabling Signature checking allows for better homebrew capabilities, and as an unfortunate consequence also allows for piracy. However it does not directly do so. Installing Luma doesn't automatically install some piracy software onto your system. You still have to go and install that yourself.

Likewise, your suggestion is used solely for piracy. For it to work, it requires amiibo data files, and that alone is piracy. You could also purchase of actual amiibos and backing up that data, which renders this feature unnecessary as you could just use your amiibo in the first place. If your suggestion enabled the use other stuff aside from just Copy Protected data, then it wouldn't solely support piracy, and would have a greater chance of being researched. You have an interesting idea, but as it was pointed out, this idea only is viable in a piracy stand point, as it has nothing to do with homebrew at this time. There aren't any home made amiibos nor homebrew that really take advantage of the NFC capabilities with custom home made amiibos.

**Comment by bel3atar** [comment]
+1

**Comment by profi200** [comment]
This is a feature that really only supports piracy as mentioned above. I doubt very much the Luma devs will consider this. There are other ways to archive a similar goal.

**Comment by urherenow** [comment]
Piracy isn’t the sole use case. I have a 5ft long window sill packed with Amiibos. When I deploy on a ship, I can’t possibly take them with me. I use thenaya to back them up and flash them to NFC stickers. With a feature like this, I wouldn’t even need to carry (and worry about losing) the stickers.

**Comment by Nuck-TH** [comment]
Morality discussion can be pretty much endless.
This feature can be used for convenience, because Amiibos are not things you can easily carry around.
Much like signature spoofing this can be used for piracy as well, but decision is always on the user, let's not decide for them.

**Comment by Multimegamander** [comment]
welp, time to wait for a fork with this feature

**Comment by Sayora77** [comment]
Also, this would let Old 3ds users use amiibo without the adapter.

**Comment by ghost** [comment]
It's as @profi200 and @Dimensional say; this won't be implemented by us.
