### ISSUE TITLE
Random freezes on HOME menu when a flashcart is in the cart slot

### ISSUE THREAD

**Issue by s0r00t** [LumaTeam/Luma3DS#1067]
**System model:** New 3DS XL
**SysNAND version:** 11.6.0-39E
**Entrypoint (How/what you're using to boot Luma3DS):** B9S/Sighax
**Luma3DS version:** 9.0
**Luma3DS configuration/options:**
Default EmuNAND: 1
Screen brightness: 2
Splash: Before
PIN lock: Off
New 3DS CPU: Off

Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Enable game patching: (x)
Show NAND or user string in System Settings: (x)
Show GBA boot screen in patched AGB_FIRM: ( )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )
Disable ARM11 exception handlers: ( )

**Explanation of the issue:**

When a flashcart is in the cart slot, the console suffers from random freezes on HOME menu.  
So far, it has happened:  

* when starting up the console (HOME menu never shows up, and the communication LED stays off)
* when going back to the HOME menu from a running 3DS app
* when using the HOME menu regularly (after being awaken from sleep?)

It always occurs in the same way : theme music starts to stutter, then completely stop, and the HOME menu becomes unresponsive seconds after.  
Rosalina menu can still be brought up, but any option will deadlock the console (for example, rebooting).  
No freezes are experienced when actually using the flashcart.
Tested flashcarts are R4i Gold 3DS Plus and CycloDS iEvolution.

**Steps to reproduce:** Unknown, besides having a flashcart inside the console.

**Comment by ghost** [comment]
This has nothing to do with Luma. The 3DS doesn't handle some flashcarts well, and will often freeze entirely if the flashcart has any issues, like say, a bad header or similar. I experienced this with my soft-bricked AK2i, as well, and it was fixed by flashing a clean AK2i flash backup.
