### ISSUE TITLE
"An exception occurred" when playing Dillon's Dead Heat Breakers (Japan Import) crashing

### ISSUE THREAD

**Issue by MarinaRuby** [LumaTeam/Luma3DS#1070]
**System model:**

Old 3ds

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9strap

**Luma3DS version:**

9.0

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: ( 4)

Splash: (off)

PIN lock: (off )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

I recently imported the Japanese version of Dillon's Dead Heat Breakers and got the locale.txt for the game set up and everything. Played it just fine for about an hour and some change until I ran into this right before hiring some Miis for a mission/stage.

![00039](https://user-images.githubusercontent.com/38794888/39444038-5df6d93a-4c84-11e8-82ad-91320265b0fa.png)

**Steps to reproduce:**

1. Not sure how to describe this one, but I just tried to get through this text box...
![00023](https://user-images.githubusercontent.com/38794888/39381778-4d03c534-4a31-11e8-8cf7-cd89d290d73d.png)

 and then right after the screen fades while loading the next part, the crash that happened above appeared moments later. Not sure what to do or what the crash means.

**Dump file:**

[crash_dump_00000003.zip]
(https://github.com/AuroraWright/Luma3DS/files/1956448/crash_dump_00000003.zip)
----
update (4/30/2018)
I was able to continue for some reason, but it crashed again before entering a new mission again. Here's the crash dump file for that part
[crash_dump_00000008.zip](https://github.com/AuroraWright/Luma3DS/files/1961752/crash_dump_00000008.zip)

**Comment by MarinaRuby** [comment]
Well, I'm currently playing the english version after buying it on the eshop and the same thing happened again before the 3rd stage. Crashed right before loading the next part. Here's the crash dump file and please, someone lend some advice or something. Not sure why it's crashing on my main 3ds and doesn't happen on my japanese 3ds.


[crash_dump_00000011.zip](https://github.com/AuroraWright/Luma3DS/files/2038062/crash_dump_00000011.zip)

**Comment by MarinaRuby** [comment]
![image](https://user-images.githubusercontent.com/38794888/40527527-f6369ade-5fba-11e8-9cd5-9cc43835ebd0.png)
here's a screen of the crash as well. Again...0 issues on my japanese 3ds but for both english and japanese versions of this game, I'm having this issue.

**Comment by ghost** [comment]
Given that it's functional on your Japanese 3DS but not the English 3DS and the crashes do not always occur in the same section, it's somewhat likely you've got a damaged SD card or something of that nature.

**Comment by MarinaRuby** [comment]
@Hikari-chin 
I went and bought a new SD card and it still happened. Deleted the game, re downloaded it, still happens.

I'm half tempted to buy either the European or Australian version of the game and want to see if I get the same result because the retail Japanese version gives me the same issue. Any other trouble shooting tips I could possibly try out.

One other thing I need to reiterate : If I clear a stage on my japanese 3ds and bring the retail game back to my main 3ds, I can load the stage that crashed just fine. What's driving me nuts is that the japanese 3ds loaded everything from scratch of the game until the end of the game. But now after I buy the localized version of the game from the eshop it's giving me this issue again.

I don't know if it's any extdata, I don't know if it's because of the Miis or loading the new map or what. I'm half tempted to just remove b9s and luma to see if it still happens or just doesn't launch.

**Comment by ghost** [comment]
If you copied your data from the old SD card to the new, you could've copied over damaged data. Try starting from scratch. 

As a last resort, you could try restoring your last known good NAND backup or clean ctrtransfer image.

**Comment by MarinaRuby** [comment]
Just to be sure, you want me to format my sd card on pc and redownload the game from the eshop?

**Comment by ghost** [comment]
Yes. But be aware that all your save data for every game you own will be lost by formatting.

**Comment by MarinaRuby** [comment]
@Hikari-chin 
Sorry for the wait, had work the night before and yesterday....anyway it crashed again even after formatting the card and downloading it again. This time....before the 2nd stage.
![00091](https://user-images.githubusercontent.com/38794888/40588312-9222e462-61a9-11e8-893e-f52caa9b7a94.png)
I'm seriously lost, this is the only game in last 6+ years with this system  that I've had a problem like this with. The prequels to this game didn't do this, project x zone 2 (english and japanese) didn't do this....it's only this game.

I can't really go back to a nand backup since my last back up was from last year and haven't had much issues nor did I make notes about that last back up. 

I honestly just want to remove b9s and luma just to see if it still happens and if that fails, just restore the custom firmware. Unless there's another method I can try.

[crash_dump_00000015.zip](https://github.com/AuroraWright/Luma3DS/files/2042851/crash_dump_00000015.zip)

edit : btw, why is my issue marked as closed?

**Comment by Dimensional** [comment]
If that is a JAP import and you're running it on a US 3DS, removing CFW on your system will prevent you from playing it all together, as the console is region locked.

**Comment by MarinaRuby** [comment]
@Dimensional 
I absolutely understand that, but the problem is that the US eshop version is giving me the exact same issue as the Japanese version last month. I can't play either version past the beginning stages.

**Comment by piratesephiroth** [comment]
what happens if you disable the ARM11 exception handlers?

**Comment by MarinaRuby** [comment]
@piratesephiroth 
I have tried that and upon trying to load the hotel lobby (where it keeps crashing) the game black screens and reboots to the main menu.

**Comment by ghost** [comment]
Further discussion of this can take place in the NH Discord, linked in the issue template comments.
