### ISSUE TITLE
[Feature Request] Patch Selecter

### ISSUE THREAD

**Issue by Sayora77** [LumaTeam/Luma3DS#1072]
If you have a game that has more than one mod (Pokemon) than it takes a while to switch out your save file and the mod, especially without the computer.
I think there should be a mod selecter where if you hold down a button (select?) while the game is booting, you will get a patch selecter screen and you can choose which patch to use for the game. Booting without opening that menu would boot game as normal. It would also be nice if you could make it so different patches could have their own save file. There could also be an option if you name the patch button_name.ips it would automatically load if you hold down the button while botting the game. Kind of like the firm loading.

**Comment by ghost** [comment]
Bernardo's Lasagna already does this; there's no need for it to be integrated into Luma.
