### ISSUE TITLE
[FEATURE REQUEST]  Save selector?

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1074]
I often use multiple saves for multiple games and switching the saves on some of them is tedious.. Maybe you could add a save selector?

**Comment by RocketRobz** [comment]
You can restore a different save easily, using Checkpoint.

**Comment by ghost** [comment]
I can do that? Maybe I took a break from the 3DS Scene too long :) Closing this now.

**Comment by ghost** [comment]
Hey fuck off @Hikari-chin
