### ISSUE TITLE
[BUG] AGB roms with custom intros makes the system freeze?

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1076]
Yeah, you know how No-Intro sets are named because the person who made the set doesn't add intros to the rom like some people who rip roms do? Well, believe it or not, but whenever I load a rom that has a custom intro like that, hence using Ultimate 3DS VC GBA Injector, it seems to crash? Not sure why the hell this happens, it doesn't even give me a errdisp, all it does is just freeze. Like, the system just stops completely. No error, no nothing.

**Comment by Nuck-TH** [comment]
What does this has to do with luma anyway? AGB_FIRM run roms on hardware, so this means that "intros" are so badly written, that they do not work prooperly on hardware, maybe on emulators they do.

**Comment by piratesephiroth** [comment]
yeah use GBATA to remove the intro and hopefully they will work

**Comment by 6100m** [comment]
Well, what I meant was when I enable AGB logo in the config, but never mind, i can just remove the intros. Closing this now.

**Comment by ihaveamac** [comment]
you're being immature on the issue tracker, stop it.

**Comment by AuroraWright** [comment]
One of the reasons the GBA logo is toggleable is that most of the introed ROMs are improperly made (I think they don't fix a checksum somewhere or something like that) and the GBA BIOS (what runs while you see the logo) won't run them.
