### ISSUE TITLE
Patch to AGB_FIRM for VC color correction?

### ISSUE THREAD

**Issue by teddybuns** [LumaTeam/Luma3DS#108]
According to this thread on GBATemp, https://gbatemp.net/threads/restoring-original-colors-to-gba-vc.427642/, it's theoretically possible to patch the VC footer in AGB_FIRM so the color correction applies to all GBA games instead of having to hex edit each game individually. All of the GBA games look so dimmed and washed out, if the color correction could be done it would be awesome.

**Comment by BlaX722** [comment]
This would be great! Add this if possible... please!

**Comment by piratesephiroth** [comment]
Those are the regular colors, as if we were playing on an emulator. They just look saturated, not corrected.

The games were designed to run on the GBA LCD so the colors in the AGB_FIRM are the closest to the original experience.

**Comment by cheatfreak47** [comment]
@piratesephiroth Not actually true. 
AGS101 GBA SP or especially a DS Lite, or Gameboy Micro, the colors look a lot brighter, more close to the "saturated" look you're referring to.
I'm not saying there's anything wrong with it, I'm just saying it looks like washed out crap compared to the corrected colors. So I'm in favor of this as well. 

Would be awesome as an optional patch in the Luma 3DS config, just like the GBA Intro Patch.

**Comment by teddybuns** [comment]
Let's just say the original GBA screen wasn't a pioneer in LCD technology, so just because the colors in AGB_FIRM right now emulate the "original experience" it doesn't change the fact that most of the games look dimmed and washed out on the 3DS screen. They could look way better.

**Comment by vaguerant** [comment]
Yeah, there are any number of ways to play GBA games that aren't "on the original model GBA". The Game Boy Player, either SP model, the Micro, either DS or DS Lite; to say the dimmed VC graphics are most accurate is to ignore the vast majority of ways that it's possible to play GBA games which say otherwise.

**Comment by joesteve1914** [comment]
This would be great, especially since a lot of people have lost their gba cia files and would need to make a whole new cia to fix the color.

**Comment by Youngsie1997** [comment]
Correct me if i'm wrong but i believe there are a few games that the color fix causes issues with, i believe in the thread there's discussion of a game refusing to save, 

 If it's any conciliation  the process has been made easier via a customized footer generator that somebody has posted that also removes ghosting https://gbatemp.net/threads/restoring-original-colors-to-gba-vc.427642/page-5 (I've tested this and it worked for me on Pokemon fire red and leaf green also didn't flag as a virus or anything). (Of course you could make it a toggle option like the boot screen) but again this is assuming it's even possible to patch the firm.

**Comment by joesteve1914** [comment]
@Youngsie1997 
That's why it should be an option in th configuration menu, like the n3ds clock speed and gba boot screen. 

Of course this might not even be possible. I guess we won't know unless it gets added to Luma3ds.

**Comment by Youngsie1997** [comment]
I've had to remake all my vc anyway so I've just been using the footer generator works fine for me i'm not fussed about having it as a Luma option.
