### ISSUE TITLE
3ds help

### ISSUE THREAD

**Issue by Alexhupp** [LumaTeam/Luma3DS#1081]
**System model
New 2ds
**SysNAND version**
Sysnad 11.6
**Entrypoint**
Boot9strap 1.3
**Luna**
Latest with boot9ctr for custom animations
**Luma3DS configuration/options:**

Default EmuNAND: ( none)
Screen brightness: ( max)
Splash: (yes )
PIN lock: (none )
New 3DS CPU: ( yes)
Autoboot EmuNAND: ( no)
Use EmuNAND FIRM if booting with R: ( no)
Enable loading external FIRMs and modules: (no )

**Comment by Dimensional** [comment]
Whats the matter boy? Timmy fell down the well? Does Flo need change for a dollar (Progressive Insurance Joke)?

Silliness aside, what exactly is the problem? A generic "HELP" message with no details as to exactly what went wrong, only what you have configured and what system, gives nothing for us to help you with.

**Comment by Alexhupp** [comment]
What i get is a black screen with only the blue light on if i try and boot into recovery mode still a black screen but wifi indicator turns on i have uninstalled the cfw many times and reinstalled because i was bored but now its on a black screen either its my N2ds hating me or my dsi forwarders i installed killing me

**Comment by Qyriad** [comment]
This is not a support forum.
