### ISSUE TITLE
Error when playing Starfox 64 3D

### ISSUE THREAD

**Issue by IRStorm** [LumaTeam/Luma3DS#1083]
**System model:**

New 3ds

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9strap

**Luma3DS version:**

9.0

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: (x )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When playing a specific course in Starfox 64 3D

**Steps to reproduce:**

1.initiate game (SF643D)

2.enter the main menu

3.Choose main game

4. Resume last game

5.Proceed to Area 6

6. when accepting the mission, general pepper is about to speak when the error screen below appears with the next digits:

![image](https://user-images.githubusercontent.com/39219441/39958638-366b7416-55cb-11e8-8282-00531dd0f407.png)

**Dump file:**

**Comment by Nuck-TH** [comment]
either game files or save are damaged
if it would be issue of luma - it would be noticed long time ago, because you are not alone, who plays this game.
