### ISSUE TITLE
ErrDisp id: 6 while pressing home button, and ARM11 crashing randomly

### ISSUE THREAD

**Issue by CokeGirl** [LumaTeam/Luma3DS#1091]
**System model:** Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** 11.6.0-39U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):** SIGHAX

**Luma3DS version:** v9.0-1182d3a6

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Hi everybody.
My Old 3DS is crashing with _Errdisp 6_ everytime I press "home" button, at any application/game. I hope someone help me to fix this issue.

Also, It randomly crashes with ARM11 (core 0) error, while lurking at 3DS menu. 

**Steps to reproduce:**

1. If I press home button while at any game or software, I get the following ErrDisp:

_An error ocurred (ErrDisp)

Error type: generic

Process ID: 6
Process name: ns
Process title ID: 0x00040130000008002

Address: 0x00118c10
Error code: 0xd8e007fd

Press any button to reboot._

--

2. Randomly, while at 3DS menu, I also get the following error:

_An exception occurred

Processor: ARM11 (core 0)

Exception type: data abort

Fault status: Translation - Section

Current process: menu (004003000008F02)_

**Dump file:**

[arm11.zip](https://github.com/AuroraWright/Luma3DS/files/2070223/arm11.zip)

**Comment by CokeGirl** [comment]
Looks like I managed to get rid of home button ErrDisp error with "I get a black screen on boot". So far, so good.
But I keep getting that annoying ARM11 (Core 0) error as shown above (current process: menu) while open any game. Sometimes it manages to open the game, sometimes don't... and crash.

**Comment by Shadow322** [comment]
close this as its not a luma3ds problem and this isnt a help get my 3ds working for me place
