### ISSUE TITLE
Majora's Mask 3D Crashing at First Loading Screen

### ISSUE THREAD

**Issue by hbz1** [LumaTeam/Luma3DS#1092]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

9.0-2a840f2

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Once opening Majora's Mask right after the 3DS splash screen, the game loads for half a second then crashes. Running the Japanese version. Tried changing the region using Luma Locale Switcher and no hope. Changing the language on the US version doesn't work either.

**Steps to reproduce:**

1. Download JP Majora's Mask through freeShop.

2. Launch game.
![20180604_195739](https://user-images.githubusercontent.com/39931514/40948311-bfca028c-6835-11e8-9bec-7f5ab1e9dbea.jpg)

**Dump file:**

**Comment by ghost** [comment]
We don't provide support for pirated software here.

**Comment by nioupola** [comment]
Hello,

I get the same with a real EU cartridge with my 2DS LL. But, it's work perfectly on my 3DS LL. I tried with two different 2DS LL with the same issue.

Thanks for Luma3DS ❤️ 

edit : I fix the issue with the ```local.txt``` file. Maybe you can try too and the one to match with your game and game console.
