### ISSUE TITLE
Activating soft-reset combo in DSiWare ver. of WarioWare Touched (or games in nds-bootstrap) causes prefetch abort without game patching

### ISSUE THREAD

**Issue by RocketRobz** [LumaTeam/Luma3DS#1095]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap/Sighax

**Luma3DS version:**

9.0

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Before)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When activating the soft-reset combo in the DSiWare version of WarioWare Touched, or just doing the soft-reset method in TWL mode in general, I get an ARM9 prefetch abort.

Turns out this only occurs if game patching is disabled.

**Steps to reproduce:**

1. Disable game patching.

2. Open DSiWare version of WarioWare Touched, or launch a game on SD through DSiMenu++.

3. Hold L+R+START+SELECT to activate soft-reset.

**Dump file:**
[crash_dump_00000005.zip](https://github.com/AuroraWright/Luma3DS/files/2088574/crash_dump_00000005.zip)
![img_20180610_203326_663 small](https://user-images.githubusercontent.com/16110127/41210593-f445e9d6-6cef-11e8-8e71-e1951b7901a2.png)

**Comment by mariomadproductions** [comment]
Does this happen when nds-bootstrap/twloader is not installed?

**Comment by RocketRobz** [comment]
Yes, though I don't see how nds-bootstrap is the cause of the issue, since that's just a .nds file placed on the SD card.
The version of WW Touched I'm running is downloaded straight from the Nintendo eShop as a My Nintendo reward.

**Comment by ghost** [comment]
This is true for every game that you are trying to play on nds-bootstrap

**Comment by ImmortalScientist** [comment]
Can confirm this affects any game played through nds-bootstrap. Both key combinations (R+L+St+Se and R+L+Down+B) have this effect.

**Comment by RocketRobz** [comment]
One can avoid this issue by using Rei-Six, instead of Luma.
Can confirm this on my side.

**Comment by RocketRobz** [comment]
Oddly, this issue can be fixed by enabling game patching in Luma settings.

**Comment by TuxSH** [comment]
@Robz8 0xc8804465 is "mount point not registered". If this is what I think (a regression (?)), the issue shouldn't occur if luma is booted from nand.

**Comment by piratesephiroth** [comment]
@TuxSH yep that's it.
