### ISSUE TITLE
Aurora Wright I need some help, I hope it is a easy fix.

### ISSUE THREAD

**Issue by RatManz34PLUS2** [LumaTeam/Luma3DS#1096]
NOOBIE DOM

[Doms crash dump.zip](https://github.com/AuroraWright/Luma3DS/files/2129210/Doms.crash.dump.zip)

-- Please fill in the placeholders.-->
 *System model:*

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

In system settings it says / Sys 11.6.0-39E /

**Entrypoint (How/what you're using to boot Luma3DS):**

it says Booted from sd via B9S

**Luma3DS version:**
LUMA version 9.0-2a840f2
**Luma3DS configuration/options:**

Default EmuNAND: ( 1)

Screen brightness: (4 )

Splash: ( off)

PIN lock: (off )

New 3DS CPU: (n/a )

--

Autoboot EmuNAND: (off)

Use EmuNAND FIRM if booting with R: (off )

Enable loading external FIRMs and modules: (just done my 3ds last weekend )

Enable game patching: ( off)

Show NAND or user string in System Settings: (on )

Show GBA boot screen in patched AGB_FIRM: ( off)

Patch ARM9 access: ( ?)

Set developer UNITINFO: (off )

Disable ARM11 exception handlers: (off )

--

**Explanation of the issue:**
when I try to run a 3ds game some will boot of the sd card others will come up with this error
homebrew as well a lot will not work
I have tried checking the sd card for errors no problem there

hey if you can help me out I have messaged you on GBAtemp,
my email as well is -snip-

I need to learn this stuff my self. in my family we have professors and doctors, a few people who are good with computers. my great granddad help make one of the first computers in world war 2 just good people in general.

I shine TBH more than most people in this family
and I only started with this stuff with a wii u about 2 years a go and I am 24 now.

sorry for the English I have a lot of learning disability's, are you Italian if so I am pure from 3 generations a go.

I would like to say hello as well on gbatemp

name=ratmandom
rat=from the pet

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by pbanj** [comment]
Cool "life" story bro

**Comment by RatManz34PLUS2** [comment]
yeah it gets better I am autistic, dyslexic with ADD, schizophrenia and bipolar all 5 at the same time.
to be honest I am not the average person or computer person, like I do kickboxing and listen to trap music and loads of people don't have a clue what I do. I am just waiting for some thing to happen. but far from depressed or violent in the bad ways. why not be this way? you probably know at least some of what I am saying...

**Comment by ghost** [comment]
Not a Luma issue, rather an issue of a corrupted or bad SD card.

**Comment by RatManz34PLUS2** [comment]
thank you yuujieve
I will test out my old 4gb sd card

the card I was using was a 256gb sandisk card and I did test it for errors with h2testw no problems there.
I should look up a recommendation then of good SD cards for the 3ds.

feww it is not my 3ds !
dam sd card is not a micro(not good for my hardware) lol

**Comment by ghost** [comment]
If h2testw reported no problems it may not be a direct hardware issue with the SD card, but rather corrupted data on the card itself.

**Comment by RatManz34PLUS2** [comment]
should I send my sd card back, it is from amazon so I could very easily or could I fix this my self if I can.

**Comment by pbanj** [comment]
the issue might just be the size of the card. bigger sd cards cause a slowdown. lots of people tend to have issues with even 128GB. try reformatting the card but this time use 64kb for the cluster size instead of 32 and see if the issue still happens

**Comment by RatManz34PLUS2** [comment]
I have just tried my old sd card the 4gb that come with the hand held still getting this error. I will try and re-download that game with the wii u usb helper tool.

but it is not just one game it is a lot of games and homebrew...

like could it be something in the nand?
or corrupted data on the card but I formatted the card and extracted a fresh install to the sd.
![3ds error question](https://user-images.githubusercontent.com/37990439/41803766-635e09fa-7684-11e8-8199-a696baa7e0cd.jpg)


leave a message I am off 2 bed its nearly half one in the morning in the uk.

thank you
pbanj
and
yuukieve
from Dominic Wake

**Comment by ratmandom** [comment]
ok I have 3 more dumps if you could just check them, if there is not a fix I need a new 2ds xl.
[Doms dump test 1.zip](https://github.com/AuroraWright/Luma3DS/files/2129910/Doms.dump.test.1.zip)

**Comment by RatManz34PLUS2** [comment]
can you just check these dumps out if they do say the same thing.
I need a new 2ds xl or new 3ds xl.


[Doms dump test 1.zip](https://github.com/AuroraWright/Luma3DS/files/2129912/Doms.dump.test.1.zip)
[Doms dump test 2.zip](https://github.com/AuroraWright/Luma3DS/files/2129913/Doms.dump.test.2.zip)
[Doms dump test 3.zip](https://github.com/AuroraWright/Luma3DS/files/2129914/Doms.dump.test.3.zip)
