### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1097]
If I disable set developer unit will I be able to play CIAs, eshop,amiibo,etc and still have developer software working?

**Comment by ghost** [comment]
Not a support/question forum.

**Comment by ghost** [comment]
.................Thanks.....A.....LOT.

**Comment by ghost** [comment]
@yuukieve can I still have an answer to the question. I really need to know.

**Comment by piratesephiroth** [comment]
yes, it's a requiremnt only for installing developer CIAs

however you could have asked this on many different places

**Comment by ghost** [comment]
Thank you so much. :)
