### ISSUE TITLE
Updating titles not working on >=4.0

### ISSUE THREAD

**Issue by opa334** [LumaTeam/Luma3DS#11]
If you try and update a title (Flipnote Studio 3D in my case) from system menu, it will tell you that your firmware is outdated and it will try to update and find nothing. I have downgraded to 3.14 and performed the update without issues. I think this might be related to some 3ds_injector stuff added.
New 3DS (EUR) 10.7 SysNand using A9LH

**Comment by AuroraWright** [comment]
Interesting:
1) eShop works fine?
2) Can you try one of these builds? http://www51.zippyshare.com/v/G9bZaSLN/file.html
http://www51.zippyshare.com/v/P0Ve4NWs/file.html
I'm pretty sure one of those fixes the issue.

**Comment by AuroraWright** [comment]
Can't reproduce. I updated to 10.7, got into eShop to enable Home Menu updates, rebooted, and updated from Home Menu 3 cartridge games. No error whatsoever. Latest code from repo (nothing should have changed since 4.1).

**Comment by AuroraWright** [comment]
I reproduced it, but it hasn't to do with updates. It has to do with full titles downloads from Home Menu.

**Comment by theAeon** [comment]
Just to further confirm, I attempted to press download now on a full system title and it prompted me to update on aurei 4.2

**Comment by Shadow322** [comment]
This has already been stated as a issue to sole it click open eshop for
update

**Comment by giveup** [comment]
Are you enable "user developer unitinfo"?
This option will cause any Nintendo service error.(eShop/Miiverse)

**Comment by theAeon** [comment]
Nope, I have not.

-Andrew
On Apr 13, 2016, at 11:51 AM, giveup <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you enable "user developer unitinfo"?
This option will cause any Nintendo service error.(eShop/Miiverse)

**Comment by cspencer49519** [comment]
I have one game that will not update, but I suspect maybe a bad CIA, I get a problem where the update stops at 98%. The title is Marvel Pinball, and I believe it is E-Shop only.

**Comment by RShadowhand** [comment]
I need diagnostic information, so everyone who has this problem, please answer these questions:

A9LH?
Patched TWL/AGB Firms? (not by CFW, but by installing CIA)
Patched Home Menu/NS? (by installing patched CIAs, for region-free)
Do you own the CIA? (don't post links)
Did you use PlaiCDN to download the CIA? (don't post titlekeys)

**Comment by cspencer49519** [comment]
I have an N3DSXL, A9LH, no patched TWL/AGB, no patched Home Menu/NS, the cia came from "that iso site", I do not own it, but I can buy it if it will help with diagnostics. I did not use plaicdn to download.

**Comment by theAeon** [comment]
Aurei 4.2, A9LH, no patched cias, title was pushed from my Nintendo.

-Andrew

On Apr 16, 2016, at 11:55 AM, Rhanath Shadowhand <notifications@github.com<mailto:notifications@github.com>> wrote:

I need diagnostic information, so everyone who has this problem, please answer these questions:

A9LH?
Patched TWL/AGB Firms? (not by CFW, but by installing CIA)
Patched Home Menu/NS? (by installing patched CIAs, for region-free)
Do you own the CIA? (don't post links)
Did you use PlaiCDN to download the CIA? (don't post titlekeys)

**Comment by cspencer49519** [comment]
If you need me to do anything diagnostic, including buying the game and testing downloading/updating after that, just let me know, I'm available.

**Comment by RShadowhand** [comment]
@theAeon What do you mean "pushed from My Nintendo", you mean it's legit and you got it from My Nintendo?

**Comment by theAeon** [comment]
I used the send game to device feature off their website. I believe that it tells the device to use download later on the title, and pressing download now from the home menu prompts for a sys update.

On Apr 16, 2016, at 12:43 PM, Rhanath Shadowhand <notifications@github.com<mailto:notifications@github.com>> wrote:

@theAeonhttps://github.com/theAeon What do you mean "pushed from My Nintendo", you mean it's legit and you got it from My Nintendo?

**Comment by RShadowhand** [comment]
@AuroraWright I think it has something to do with firm patching on the fly. I thought I had this issue because I had prepatched TWL/AGB FIRMs and prepatched HomeMenu / NS.

**Comment by cspencer49519** [comment]
It may be worth noting that I had the same issue with this title when AuReiNAND used to create it's own pre-patched firms in the aurei directory, so it might not have anything to do with patching on the fly, but maybe just the way it's being patched in general? I'm pretty clueless but just thought I would throw that out there.

**Comment by theAeon** [comment]
Just updated to 5.1 on vanilla a9lh, still doesn't work with titles that have the download started from Nintendo.com- twilight princess picross in this case

**Comment by theAeon** [comment]
^vanilla aurei a9lh that is

**Comment by RussKay** [comment]
Same here. Pushed from Nintendo to homescreen. On A9LH (latest noscreeninit) and latest ARN. Selecting to download now prompted me to upgrade my system. However, I was able to get it to download by putting my system in sleep mode.

**Comment by RShadowhand** [comment]
I found the issue is caused by eShop check patch, and removing it fixed it. I made a PR (#44), so you'll have to wait a bit.

**Comment by Hartie95** [comment]
AuroraWright already knows about this. Till there is a better patch, simply update full update titles(like Flipnote studio)  from the eshop instead from the home menu.

**Comment by cspencer49519** [comment]
The game I'm trying to update, Marvel Pinball, will not update through any method. It will not download through the home menu, eshop, or while in sleep mode.

**Comment by cspencer49519** [comment]
Also I don't think that PR is going to be accepted, since you rebranded the entire firmware to your own name (ShadowFW?) lol.

**Comment by RShadowhand** [comment]
I made the PR before I renamed it. Doesn't really matter, because it's only like 10~ lines.

**Comment by Hartie95** [comment]
@cspencer49519 does it work without the update patch? Do you have it originally from the eshop, or have you installed it using a cia?
If you installed it via cia it will not update, unless you have a legit ticket.

**Comment by cspencer49519** [comment]
Installed via cia, as I stated in my previous posts. Everything else I have installed from cia updates fine. I'm not sure what version doesn't have the update patch, so unsure how to test that.

**Comment by RShadowhand** [comment]
The problem arises from the "eshop update check" patch. Once disabled, it works fine.

**Comment by cspencer49519** [comment]
Please tell me where I can disable this patch?

**Comment by RShadowhand** [comment]
You can't without a special build. I'll build you one until there's a new release.

**Comment by cspencer49519** [comment]
Awesome, I just have the one title that won't update, it's annoying but causes no problems beyond the annoyance.

**Comment by Hartie95** [comment]
Could it be possible that the other games where games like pokemon that have an  extra update title and not directly update the game files? Because since its not even updating from the eshop I  don't think its the patch.

**Comment by RShadowhand** [comment]
[AuReiNand.zip](https://github.com/AuroraWright/AuReiNand/files/228454/AuReiNand.zip)

No need to rename/remove anything, just replace the arm9loaderhax.bin file.

**Comment by cspencer49519** [comment]
Game still will not update, tried sleep mode, update from home, and update from eshop, I'm just going to chalk this up to a bad cia? I mean it's really not that significant, it's just something I noticed, if I ever decide to play the game I'll just buy it, I'm uninstalling it for now.

**Comment by RShadowhand** [comment]
Yeah it's 100% bad cia. I know that patch works because I used literally the same build to test getting MegaMan from eShop (I own it), and said sleep mode, then simply went to home menu and said "download now", and it downloaded without issues.

**Comment by RShadowhand** [comment]
Made a proper pull request (#46)

**Comment by RShadowhand** [comment]
Fixed in commit d40722af5367c0410477cd7ad26a1dffb0c7d100. Wait for the new release.
