### ISSUE TITLE
Blue light filters!

### ISSUE THREAD

**Issue by j0lol** [LumaTeam/Luma3DS#1101]
Blue light is a problem with most devices where at night the light from screens causes the brain to be tricked into thinking it is daytime, therefore keeping the user of the device awake for much longer. There are programs that aim to fix this problem, such as [f.lux for Windows, Mac, jailbroken iOS devices and Android devices](https://justgetflux.com/) and [redshift for Linux](http://jonls.dk/redshift/). However, there is a 3ds recreation of redshift called [CTR_Redshift by MarcusD.](https://gbatemp.net/threads/ctr_redshift-hardware-based-blue-light-filter-for-old3ds-and-2ds.493736/) The application works quite well (but is quite annoying to set up using the app) and could (i think) be ported easily to the rosalina menu or as an option in luma config. There is also a [pull request adding blue light filters](#1065).

**Comment by RocketRobz** [comment]
There's an unofficial Luma build that has Redshift ported into Rosalina. The build is done by MarcusD.
https://puu.sh/AxWVU/a6635739b3.firm

**Comment by j0lol** [comment]
nice! thanks robz

**Comment by therealbungus** [comment]
Watch what you say about the PR otherwise your comments will get deleted

Thanks AW

**Comment by ghost** [comment]
There's already an open PR for this, as you said.
