### ISSUE TITLE
Wario Ware Gold demo crash on game startup

### ISSUE THREAD

**Issue by HunterAhlquist** [LumaTeam/Luma3DS#1102]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.7.0-40U

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

9.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( 1)

Screen brightness: ( 4)

Splash: ( before)

PIN lock: ( off)

New 3DS CPU: ( off) also tried clock+L2

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
I installed the Wario Ware Gold demo via the  application (cia booted) when I start the game it crashes the 3ds

**Steps to reproduce:**

1. Start Wario Ware Gold (demo)

2. C R A S H

**Dump file:**
[crash_dump_00000027.zip](https://github.com/AuroraWright/Luma3DS/files/2187506/crash_dump_00000027.zip)

fyi, the dump says it is from 2017, but my 3ds clock is just wrong.

**Comment by ghost** [comment]
*That* application just does that sometimes, not likely a Luma issue.
