### ISSUE TITLE
Majora's Mask crashing on launch

### ISSUE THREAD

**Issue by adamagit** [LumaTeam/Luma3DS#1104]
**System model:**
New 3DS XL
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
11.7.0-40E SysNAND
[e.g. 11.6.0-39U SysNAND, 11.6.0-39J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
9.0 stable
[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( x)

Show NAND or user string in System Settings: ( x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Trying to launch an installed cia of Majora's Mask will lead to crashing on launch.
"An exception occurred.
Processor: ARM11 (core 0)
Exception type: data abort
Fault status: Translation - section
Current process: Joker (0004000000125500)

**Steps to reproduce:**

1. Fresh install of CFW, B9S and Luma 9.0, instructions followed to the letter on 3DS.guide (have had the same issue on two systems now, an Old 3DS XL and this New 3DS XL)

2. Attempt to launch the installed Majora's Mask cia
[crash_dump_00000002.zip](https://github.com/AuroraWright/Luma3DS/files/2209949/crash_dump_00000002.zip)

**Dump file:**

**Comment by ghost** [comment]
Can't reproduce. You likely have a bad CIA, bad save data, or something similar.
