### ISSUE TITLE
Add the ability to boot into a selected title on startup

### ISSUE THREAD

**Issue by loudcricketts** [LumaTeam/Luma3DS#1105]
I'm not sure if Luma3DS has the capability to do this, but it would be extremely useful for automatically starting things like [DSiMenu++](https://github.com/Robz8/DSiMenuPlusPlus) which would save a lot of time navigating the slow-to-launch 3DS home screen.

This could be bypassed by a key combo of some sort, or that functionality could be inverted.

**Comment by JoshuaDoes** [comment]
It was done on the Wii with things like Priiloader so I'd really love to see this on the 3DS too

**Comment by fincs** [comment]
Would be nice to have. However, APT is hell.

**Comment by ghost** [comment]
Essentially a duplicate of #779.
