### ISSUE TITLE
Custom Version strings stopped working, along with constant ARM11 errors

### ISSUE THREAD

**Issue by Multimegamander** [LumaTeam/Luma3DS#1113]
**System model:**

New 2DS

**SysNAND version (+emu/redNAND version if applicable):**

11.8.0-41U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Fastboot3DS

**Luma3DS version:**

9.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: (5 sec )

PIN lock: ( )

New 3DS CPU: (Clock+L2 )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )               <-- I fixed a typo here, in the note, lel
 

Enable game patching: (X )

Show NAND or user string in System Settings: (X )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Custom version strings fail to show, however Luma's Sys, Emu, etc. still works, and just about everything causes an ARM 11 crash.

**Steps to reproduce:**

1.Use Bernardo's Custom version tool

2.Nearly everything causes a translation error abort ARM11 crash

**Dump file:**

**Comment by noirscape** [comment]
It would help actually providing information about what is wrong instead of trying to overstuff the issue title.

**Comment by Multimegamander** [comment]
Thx for that halp.

**Comment by TuxSH** [comment]
Closing due to the following:

* Empty issue message (this is just the template), not enough details
* Can't reproduce
