### ISSUE TITLE
ntr cfw broken on luma 9.1

### ISSUE THREAD

**Issue by GamingMaster777** [LumaTeam/Luma3DS#1114]
after updating from 9.0 to 9.1, ntr cfw would crash any game before the 3ds splash screen is finished. after restoring back to 9.0, ntr cfw and cheats work once again. i currently am on 11.7 as well

**Comment by CodyMKW** [comment]
https://github.com/Pablomf6/BootNTR/releases/tag/v2.12 download this version

**Comment by GamingMaster777** [comment]
k thx

**Comment by PatrickB1995** [comment]
I am STILL having problems. I am running Luma 9.1 on Firmware 11.6.39U on the New 3DS XL and am using the latest PabloMK6 NTR as listed above with the latest ntr.bin file Every time I launch NTR CFW, I get this:

#FILEOPEN_FAILURE 
#LOAD_AND_EXECUTE

Press Any Key To Reboot

I have tried uninstalling and reinstalling, checked my SD card for any old NTR files, etc and I am at a loss...

What the hell did I do wrong? I have spent over 3 hours now trying to get NTR to run and its been a MASSIVE headache...

**Comment by PatrickB1995** [comment]
Also, I have tried all the other latest NTR released versions that released a day ago and zero luck there either...

**Comment by PatrickB1995** [comment]
I am simply just trying to ask for any ideas or solutions for fixing this. I dont know where to ask... I would really appreciate some help.

**Comment by Shadow322** [comment]
Like said THIS IS NOT A SUPPORT FORUM

**Comment by PatrickB1995** [comment]
Then instead of BEING A CUCK, you can point me in the right direction of where I can ask for proper help INSTEAD OF USING CAPS LOCK

Thanks!

**Comment by ihaveamac** [comment]
sigh
