### ISSUE TITLE
Switch from Rxtools to Luma3DS

### ISSUE THREAD

**Issue by Radu13** [LumaTeam/Luma3DS#1115]
Hello, i have an old 3DS with firmware 9.2.0-20E and hbl and rxtools 2.0 installed with browserhax.
I want to switch to Luma3DS but i don't know the steps and what i need for it.
I appreciate any help, thanks.

**Comment by ihaveamac** [comment]
Like the issue template said, this is not a support forum.

https://3ds.hacks.guide
