### ISSUE TITLE
Arm11 crash.

### ISSUE THREAD

**Issue by NaturalHarmonia** [LumaTeam/Luma3DS#1119]
I'm on Ver. 11.8.0-41U and Luma3DS v9.1 and I experienced a crash when trying to play Pokemon Ultra Moon. The options I have enabled are Enable game patching and Show GBA boot screen in patched AGB_FIRM. 
[crash_dump_00000001.zip](https://github.com/AuroraWright/Luma3DS/files/2279087/crash_dump_00000001.zip)

**Comment by ghost** [comment]
Played through Ultra Moon without any issues here. CNR.
