### ISSUE TITLE
i have a problem with my nintendo 3DS in luma 9 and Boot9strap 1.3 

### ISSUE THREAD

**Issue by leonskiller** [LumaTeam/Luma3DS#1120]
MY NINTENDO 3DS RUNS AN ERROR ON LUMA 9 AND BOOT9STRAP 1.3 APPEARS DUMP / ARM11 WHEN I TRY TO DOWNLOAD ANY GAME OF FREESHOP plsss help

**Comment by ihaveamac** [comment]
We don't support piracy here.

**Comment by MialTheMimiga** [comment]
That looks like an issue for the free shop creator

**Comment by urherenow** [comment]
No apps like that will ever work again. It will never be fixed. The change is on nintendo server side.
