### ISSUE TITLE
Errors during compiling

### ISSUE THREAD

**Issue by MightyBirdy** [LumaTeam/Luma3DS#1122]
![cmd_2018-08-15_17-59-03](https://user-images.githubusercontent.com/12574149/44213689-89101b80-a12b-11e8-879d-3854137f35f2.png)

**Comment by TuxSH** [comment]
I will fix the warnings later (can't right now), but there isn't any build error. The errors seem to be at "not a git repository" -- you should properly install git and clone the repo to build it.
