### ISSUE TITLE
Arm11 boot abort

### ISSUE THREAD

**Issue by DracoMan671** [LumaTeam/Luma3DS#1123]
**old2ds**

**11.8**

**fastboot3ds 1.1 beta**

**9.1 stable**

**splash: before _ brightness:4 _ game patching: on _ eternal firms and modules: on:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
When i try to boot all i get is a black screen, then i force power off and get an arm11 error saying kernel panic.

**Steps to reproduce:**

1.have cfw

2. I have no freaking idea...
[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/2295080/crash_dump_00000000.zip)

**Dump file:**

**Comment by ghost** [comment]
Can't reproduce.
