### ISSUE TITLE
Need a giude on how to fully install luma for the first time

### ISSUE THREAD

**Issue by Superspy35** [LumaTeam/Luma3DS#1126]
**System model:**

Old 3ds

**SysNAND version (+emu/redNAND version if applicable):**

So I do not need to update I actually am installing luma for the first time so could you give me a giude on how to fully install luma 3ds 9.1 and I also tried downloading the file and all it gave me was one file which I assume to be the application

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS  9.1

[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by urherenow** [comment]
3ds.hacks.guide
