### ISSUE TITLE
Cannot get enable plugins to show up in Rosalina

### ISSUE THREAD

**Issue by stonecutty** [LumaTeam/Luma3DS#1129]
Just as the title says, Cannot get enable plugins to show up in Rosalina, have everything updated to current versions. All my updates were downloaded from here

**Comment by profi200** [comment]
Official Luma3DS/Rosalina does not have plugin support.

**Comment by stonecutty** [comment]
Where do you go about finding an unofficially version that does have plugin support

**Comment by stonecutty** [comment]
Thanks for closing the issue, you sure are a lot of help lol

**Comment by tstambaugh92** [comment]
This is not a homebrew forum it's for issues directly related to Luma. There is a fork tab if you want to go through and find a fork that supports pluggins.
