### ISSUE TITLE
Luma3DS crashing when updating system firmware

### ISSUE THREAD

**Issue by ratquaza** [LumaTeam/Luma3DS#1131]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

SysNAND 11.7.0-40E

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.3

**Luma3DS version:**

9.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
When I try to update my system firmware to 11.8, or whenever I have an active connection to the internet for longer than 6 seconds, Luma crashes and tells me to reboot it. This was happening both on 9.0 and 9.1 out of nowhere. This is the error that I receive when I try to update my O3DS:

An error occurred (ErrDisp)

Error type: generic

Process ID: 19
Process name: am
Process title ID: 0x0004013000001502

Address: 0x001092d2
Error code: 0xc86044d2

Press any button to reboot.

**Steps to reproduce:**

1. Attempt to update O3DS 11.7 system firmware on Luma3DS 9.1

**Comment by ghost** [comment]
Can't reproduce.
