### ISSUE TITLE
Processor: ARM11 (Core 0) Exception type: data abort Fault status: Translation - Section current process: Joker (0004000000125500)

### ISSUE THREAD

**Issue by AgaWaga** [LumaTeam/Luma3DS#1133]
**System model:**

Old 3DS

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

 9.1.xxxxx

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

I tried installing a CIA game and it turns out giving me an error with a long list of error codes at the bottom 

Processor: ARM11 (Core 0)
Exception type: data abort
Fault status: Translation - Section
current process: Joker (0004000000125500)

**Steps to reproduce:**

1. Download CIA game

2. Paste in CIA folder in root of SD card

3. start up FBI

4. Install CIA

5. Launch game.

6. Error shown after several seconds loading of the game. ( i can see the game logo appearing for a few brief seconds )

**Dump file:**
[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/2338319/crash_dump_00000000.zip)

**Comment by Sonlen1414** [comment]
Luma does not support piracy, and no help will be given for it here.
