### ISSUE TITLE
Suggestion: Option to purposely trigger game anti-piracy measures

### ISSUE THREAD

**Issue by mariomadproductions** [LumaTeam/Luma3DS#1134]
I'd like to document anti-piracy measures in games for [The Cutting Room Floor](http://tcrf.net/The_Cutting_Room_Floor). Could Luma3DS have an option that makes it purposely trigger anti-piracy features by making the "mistakes" that anti-piracy code looks out for?

**Comment by AuroraWright** [comment]
As far as I know there are no anti piracy measures in games themselves, but there have been changes in the crypto of the gamecarts to make new games unplayable on 1:1 cart cloners like the Sky3DS (which is a change in the gamecart hardware and in the 3DS OS). Luma has no code to prevent supposed anti-piracy checks in games.

**Comment by piratesephiroth** [comment]
Yeah, anti-piracy measures check for discrepancies in certain functionalities of the system, to detect tampering or emulation.
All the 3DS checks before running a game is whether the contents are valid and, if it's a digital title, whether you have the rights to play it.

**Comment by mariomadproductions** [comment]
I see. Then I wonder what's the "AP" flag that you can see checked on some (all?) games in the 3DS ROM header viewer "Crappy Tiny Reader"?

**Comment by ihaveamac** [comment]
That's something enforced by the 3DS firmware. Some carts had an extra AP check for use with 9.6+, so they couldn't work with older Sky3DS versions.

**Comment by piratesephiroth** [comment]
yeah, it seems that it displays "AP Flag Detected" if a certain value in the rom header isn't 0

**Comment by mariomadproductions** [comment]
I guess old things like gateway didn't emulate anything inaccurately in a way that games could "unofficially" detect? (I think Nintendo has prohibited non-Nintendo anti-piracy measures on recent-consoles)

**Comment by piratesephiroth** [comment]
Gateway didn't have to worry about that because it already controled the system and could patch anything.

That additonal protection was meant to try to stop Sky3DS, which was a true flashcard that ran on unhacked systems.

Anyway once the game is running nothing else is verified.

**Comment by mariomadproductions** [comment]
Okay. I guess this can be closed then. Thanks for the responses.
