### ISSUE TITLE
An exception occurred - Pokémon Versione Rossa

### ISSUE THREAD

**Issue by Jarc1931** [LumaTeam/Luma3DS#1135]
**System model:**

[New 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.8.0-41U SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

 [Boot9Strap]

**Luma3DS version:**

[9.1]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Clock+L2)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

An exception occurred screen pops up when opening Pokémon Versione Rossa.

**Steps to reproduce:**

1. Open Pokémon Versione Rossa.

2. Wait.

**Dump file:**

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/2341765/crash_dump_00000000.zip)

**Comment by ghost** [comment]
Can't reproduce.
