### ISSUE TITLE
An exception occurred

### ISSUE THREAD

**Issue by laser04** [LumaTeam/Luma3DS#1136]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

Sys 11.8.0-35K

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

9.1

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (off)

PIN lock: (off)

New 3DS CPU: (OLD3DS)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (o)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

An exception occurred

Processor : arm11(core1)
Excep. type : data abort
Fault status : Translation - page
Current prpocess : FBI(000400000F800100)

**Steps to reproduce:**
1. Run Titles in FBI

**Dump file:**

[crash_dump_00000003.zip](https://github.com/AuroraWright/Luma3DS/files/2342149/crash_dump_00000003.zip)

**Comment by Shadow322** [comment]
What's an "elp" error?

**Comment by laser04** [comment]
zzz

**Comment by laser04** [comment]
Sorry, I made mistake.

**Comment by ghost** [comment]
I'm completely guessing here, but I don't think this is Luma's issue; it's possible FBI has issues with the different shared font on KOR/CHN devices; when I had a KOR emuNAND, FBI always rendered the text very weirdly.

**Comment by laser04** [comment]
Oh, I tried to run FBI another version, and now it works.
Thanks!

**Comment by LittleCube-hax** [comment]
Could you please post which version you used? I have the same issue but an ARM9 error instead of an ARM11 one.
