### ISSUE TITLE
Sooooooo I have cfw on 11.8 and luma3ds 9.1 and when running fbi or freeshop and try to install a cia it says "an exception occurred" I tried disabling it from the luma menu but instead of the error message it just crashed help 

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1140]
**

**Comment by ghost** [comment]
plz  help

**Comment by piratesephiroth** [comment]
are you smart enough to search on google?

**Comment by ghost** [comment]
I did I could not find anything that why I made the post

**Comment by tstambaugh92** [comment]
It's not related to Luma

**Comment by ghost** [comment]
oooh ok so do you know how to fix it

**Comment by ghost** [comment]
im not saying u do know how but im 
asking if btw

**Comment by tstambaugh92** [comment]
I do know how, and if this was a piracy support forum we'd all be happy to help.

**Comment by ghost** [comment]
im new here and I dont know why you cant help me because its not a piracy fourm

**Comment by ihaveamac** [comment]
If you want help, you need to provide more details. And we don't assist with piracy here (freeshop).

**Comment by ghost** [comment]
ok

**Comment by TuxSH** [comment]
Not a luma bug.
