### ISSUE TITLE
cant find files

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1141]
i have arm9loaderhax installed and the guide i am following says to copy arm9loaderhax.bin from luma3ds but luma3ds doesn't have that file anymore what do i do

**Comment by Dimensional** [comment]
As of either Luma 7.1 or 8, A9LH is no longer the entrypoint. You have to upgrade to B9S. https://3ds.hacks.guide/a9lh-to-b9s

**Comment by ghost** [comment]
thank you i will try that
