### ISSUE TITLE
Suggestion: Feature to log a title's loaded RomFS files

### ISSUE THREAD

**Issue by mariomadproductions** [LumaTeam/Luma3DS#1147]
Suggestion: Feature to log a title's loaded RomFS files to a text file on the sd card, like [CTR Plugin Framework](https://gitlab.com/Nanquitas/Luma3DS-PluginLoader) does. This can be very helpful when trying to debug/datamine a title.

**Comment by TuxSH** [comment]
Closing, tracker cleanup
