### ISSUE TITLE
issues entering menus from Fastboot3ds

### ISSUE THREAD

**Issue by pcs3rd** [LumaTeam/Luma3DS#1148]
I am assuming this is for all devices, especially while chainloading luma from fastboot3ds with a payload keycombo set to select. But, it usually takes a few tries to get luma to load it's own configuration and chainloader menus.
Possible fix would be to have an option to listen for start/select, button presses, etc while splashes are being loaded/displayed. I know this is more of a functionality issue rather than a bug

**Comment by profi200** [comment]
Yeah, this is not a bug. There is no way around this other than using different key combos.

As for the key combo detection on splash: That's something for the Luma devs to decide.

**Comment by Multimegamander** [comment]
Why would you have Luma set to Select, that's like having CakesFW set to L

**Comment by Shadow322** [comment]
:)
