### ISSUE TITLE
Re-enable downgrading from >11.0.0

### ISSUE THREAD

**Issue by Plailect** [LumaTeam/Luma3DS#115]
Either patch the AMPXI:CanInstall function or the minimum versions themselves, the end result is the same.

This will make it so downgrading from 11.0.0 no longer requires booting an older firmware (which is a bad crux to rely on since any new update could prevent using older firmware binaries).

[TuxSH's relevant gist](https://gist.github.com/TuxSH/a2ff24d82bdb00ce2c6a35d9cd3f53bc)

**Comment by ihaveamac** [comment]
wasn't this already done or am I mistaken?

7ea2a0a278042c919e6ede87091da0f1e608a38f

**Comment by TuxSH** [comment]
Yup, this is already implemented (and the 5.5 stable release has this feature).

**Comment by Plailect** [comment]
Well crap, I managed to miss it looking through the commits and didn't see it in the release notes. Sorry for wasting your time :P

**Comment by urherenow** [comment]
Question. Is firm protection disabled when booting 11.0 without a9lh? If not, what good does this do? Wouldn't downgrading with the 11.0 firm staying intact, cause a brick? Or at least prevent svchax from working?
