### ISSUE TITLE
Mode DS doen't work 

### ISSUE THREAD

**Issue by asdereldemon** [LumaTeam/Luma3DS#116]
When we tried to run any game on DS mode, it stays with the black screen.

**Comment by astronautlevel2** [comment]
This is not a support forum. Please post here.
http://gbatemp.net/threads/luma3ds-noob-proof-3ds-custom-firmware.411110/

**Comment by RShadowhand** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#gbads-gamesdsiwaresmash-brosmonster-hunter-4-fail-to-start
