### ISSUE TITLE
[suggestion] A change to "region/language emulation" default behavior

### ISSUE THREAD

**Issue by CouldBeWolf** [LumaTeam/Luma3DS#118]
This is a suggestion that would help me a ton, and hopefully others. 

My suggestion is to make it so that when "region/language emulation" is enabled, it defaults to picking the region of the game, and the language of users choice.
And if an alternative is wanted for a specific game, use specific txt files (like now) for those.

It could solve a lot of cases of problems with out of region games. Especially the few like me who use a Japanese 3DS, but want all games possible in english. Or the ones who maybe have french on their 3DS but want English in all games++
Some times I need the correct setting for the game to even start, some times it's just the wrong language and some times it's even no textures for menues (wtf Tipping Stars). This might be a too small case to warant much attention, but I hope the the explanaition made sense at least.

**Comment by lex3a** [comment]
#48
