### ISSUE TITLE
Question about region free

### ISSUE THREAD

**Issue by b921603** [LumaTeam/Luma3DS#119]
I cannot launch "kid icarus uprising USA" through luma3ds 5.5 on "o3ds jpn" ,while I can launch it through reinand?Is there anything wrong with region-free function.

**Comment by RShadowhand** [comment]
If you're on a9lh, try SaltFW for troubleshooting, see if that one works. If it does, the problem is in Luma.

**Comment by b921603** [comment]
It can be launched by saltfw

**Comment by RShadowhand** [comment]
Alright. What version of Luma are  you using?

**Comment by b921603** [comment]
5.5
And I have one more question want to ask.on both reinand and luma3ds ,I cannot launch "tekken 3d USA" on my o3ds jpn.

**Comment by b921603** [comment]
The problem with "kid icarus uprising USA" seems to disappear on luma3ds after I boot the sysnand through saltfw once.

**Comment by RShadowhand** [comment]
Do you have EmuNAND?

**Comment by b921603** [comment]
No
