### ISSUE TITLE
Error about gsp using Luma on latest fw 11.8

### ISSUE THREAD

**Issue by ShadowOne333** [LumaTeam/Luma3DS#1191]
Good day.

Around Monday or so I updated both the N3DS XL and the Luma firm to the latest available (11.8 for fw and Luma3DS version bd15f51), I'm using B9S sysnand.
Everything went by okay for a day or so, and now today I am getting the following error on boot:

```
An error occurred (ErrDisp)

Error type: generic

Process ID: 20
Process name: gsp
Process title ID: 0x0004013000001c02

Address: 0x00105268
Error code: 0xf8a02bfe

Press any  button to reboot.
```

I tried looking around but haven't found anything yet regarding that issue.

**Comment by james-d-elliott** [comment]
Okay so make sure you've tried the following:

1. https://3ds.hacks.guide/updating-b9s.html
2. Use the build from the official releases https://github.com/AuroraWright/Luma3DS/releases/tag/v9.1
