### ISSUE TITLE
Luma unable to read (micro)sdcard even though other .firm payloads can.

### ISSUE THREAD

**Issue by pcs3rd** [LumaTeam/Luma3DS#1192]
When booting via Fastboot3ds, (don' t think the issue would be effected by switching back to b9s), but when booting via sdcard, The fbi h&s inject won't boot, "swap current title with homebrew title" succeeds in rosalina, but when relaunching the injected app, a arm11 svcbreak error forces a reboot. same result with the h&s inject. If I launch an app and then reenter the home menu, it creates menu data every time. 

3ds hardware is most likely not at fault since luma boots from sd and makes a config in /luma, GM9 reads and writes just fine (I made a dummy file), my pc reads the card just fine, and fastboot3ds loads it's config from the sdcard...
im running a 16gb (micro)sdcard with an adaptor (with writeprotect disabled) on the latest firmware & luma...
EDIT: h&s inject works if i boot from nand, but no sdcard is readable in it...
The error I'm getting for hb launcher is;
Processor: Arm11 (core 1)
Exception Type: prefetch abort (svcBreak)
Fault Status: Debug event
Current process: Loader (000000000000000000)
and for fbi:
Same info listed above.

**Comment by james-d-elliott** [comment]
Why use the inject? It's a very outdated method of getting hbmenu. If you are booting Luma3DS from Fastboot3DS just use Rosalina to launch it. Edit: related issue https://github.com/AuroraWright/Luma3DS/issues/714

Grab this and put boot.3dsx in the root of your SD card: https://github.com/fincs/new-hbmenu/releases/latest
Follow section III of this: https://3ds.hacks.guide/finalizing-setup

**Comment by noirscape** [comment]
A. I'd suggest uploading a crash dump.
B. What version of Luma are you running?
C. What version is your system running?

**Comment by Shadow322** [comment]
This is why we have an issue template

**Comment by pcs3rd** [comment]
@noirscape github wont let me upload .bin files, so i Put the on google drive...
[Dump 1](https://drive.google.com/file/d/1sbFzsraFRza2bOXyuC6Bf5aEiR1FSR_W/view?usp=sharing)
[Dump 2](https://drive.google.com/file/d/1tOM-LJUP-C83Fv_xltceiuzKVGusYwv6/view?usp=sharing)
I am running luma 9.1 with 11.8.0-41u
Also @james-d-elliott I don't use hblauncherloader and inject homebrew into current app is just fine - it was implamented along with rosalina if i recall - and it's only one full version old. But I still use h&s inject because it presists across sd cards. Also, the issue that was referenced was similar, but it  had to do with exiting FBI, not booting it form home menu.

**Comment by james-d-elliott** [comment]
I'm not instructing you to install hblauncherloader. Follow the instructions. App injection is no longer supported.

**Comment by pcs3rd** [comment]
@james-d-elliott sorry for misunderstanding. I'll try tommorow morning.

**Comment by james-d-elliott** [comment]
No worries and once you follow the guide the "Download Play" icon should open homebrew, though you can pick any existing app.

**Comment by profi200** [comment]
That doesn't sound like an issue caused by fastboot3DS at all. It's long gone when the firmware booted successfully.

I dunno what the issue is but if loader calls svcBreak() there is something seriously going wrong on your 3DS. I would recommend backing up your data from the microSD and reformatting it. Then make sure the microSD makes proper contact with the adapter.

**Comment by pcs3rd** [comment]
@profi200 i already tried reformating the card...
might be toast ( the 3ds)

**Comment by pcs3rd** [comment]
@james-d-elliott slight problem, still getting svcbreak after trying to run with ds download software. could it be a formatting issue with the sdcard or could it even be degredation of hardware? I have been formatting with a chromebook instead of windows lately...
I just find it odd that gm9 can (usually) read the sdcard just fine, read and write files, and even launch firms, but luma exits and reboots after calling svcBreak. Also, the home menu thing is still happening. 
Or could it even be caused be rouge code?

**Comment by james-d-elliott** [comment]
Could be. Could also have success with another card, try another if you have it. Might be worth looking for help on the Discord over the weekend or a time you can spend a few hours with someone.

Might also be worth replacing the Luma3DS firm file, it could be corrupt. I've seen issues where files would be corrupt on SD (I believe) and seem to work, but failed in various areas and replacing the firm with the same version fixed it.

**Comment by pcs3rd** [comment]
@james-d-elliot K Thanks. I will try doing another factory reset, redownloading luma, and a new sdcard. I have downgraded to a 16gb sdcard from the 32gb one i was using when this started. If it's ok with everyone, I will keep this issue thread open so I can type out any solution out on here for future users.
Thank you for all of your help. I will definatley look out to the discord.

**Comment by james-d-elliott** [comment]
I think that should be fine, not trying to avoid helping just feel you'll get better help if it's in real time.

**Comment by pcs3rd** [comment]
@james-d-elliott I know. its easier instead of moving a late afternon at a time (In my Eastern/New York  timezone at least)

**Comment by ghost** [comment]
I experienced similar strange/broken behavior when I had a damaged mSD->SD adapter/SD card itself. Unlikely to be a Luma issue.

**Comment by pcs3rd** [comment]
@yuukieve I think that Was the issue
