### ISSUE TITLE
Black Screen on some games when running in a different region to the console's region

### ISSUE THREAD

**Issue by PlatinumLucario** [LumaTeam/Luma3DS#1193]
**System model:** New Nintendo 3DS (White)

[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):** 11.8.0-41E

[e.g. 11.6.0-39U SysNAND, 11.6.0-39J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:** 9.1

[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( x ) - L2+Clock

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( x )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Booting certain brand new games on a different region console to the game won't work. For example, US version of Luigi's Mansion won't boot on European, Japanese, Taiwanese or Korean 3DS consoles, regardless of whenever they are New 3DS or Original 3DS.

The reason why this is the case, is because the game has extra region checking code in which no CFW can detect and bypass. If the region code doesn't match the game, it won't work.

**Steps to reproduce:**

1. Install Luigi's Mansion CIA file or run a cart version of the game

2. A blank screen will occur.

**Dump file:** There is no dump file for this issue, as this doesn't crash Luma3DS, but the entire console itself.

**Comment by urherenow** [comment]
Have you read the directions? Have you created a locale.txt?
https://github.com/AuroraWright/Luma3DS/wiki/Optional-features

https://gbatemp.net/threads/updating-to-b9s-2-0-luma-8-0-has-broken-language-region-on-some-games.473258/#post-7371356
