### ISSUE TITLE
Luma3ds - Error

### ISSUE THREAD

**Issue by sebastopolwzy** [LumaTeam/Luma3DS#1196]
Hey, i've got a problem using Luma3ds (It's my first time)

I've installed it, and everything goes ok, but when i try to launch the homebrew launcher my console keeps on the 3ds logo, this happens after i choose "Switch the hb. title to the current app" option.

![20181018_230123](https://user-images.githubusercontent.com/44280935/47193674-906dc400-d32a-11e8-8c83-47037fd72768.jpg)

I have a 2ds Old, thank's in advance, i hope my problem does have a solution

**Comment by james-d-elliott** [comment]
https://github.com/fincs/new-hbmenu/releases/latest

Grab boot.3dsx and and place it in the root of your SD card. Replace the file if it exists. Make sure when you choose the "Switch the hb. title to the current app" option while you're in an app (download play recommended). Then close the app  (home button, then x) and relaunch it. Should work fine.

**Comment by ghost** [comment]
User error, not a Luma issue.
