### ISSUE TITLE
[ROSALINA] [FEATURE REQUEST] Autostart debugger when a specific app starts

### ISSUE THREAD

**Issue by Rajveer86** [LumaTeam/Luma3DS#1198]
I would like the ability to autostart the debugger when a specific app/process name starts (or if not possible, a setting to enable it by default for all "3dsx_app" processes). This would make the development process flow much better as I would be able to compile, push the binary to the 3DS and attach the debugger all in one step without having to manually open Rosalina, enable the debugger, set it up for my process, then attach e.t.c. This would save seconds, but seconds for every run is a lot of time.

Note: I was unable to post this Rosalina feature request to [#752](https://github.com/AuroraWright/Luma3DS/issues/752) as it's been restricted to collaborators, sorry for any inconvenience.

**Comment by TuxSH** [comment]
Forgot to close, already implemented

**Comment by Rajveer86** [comment]
Awesome, thank you, looking forward to trying it out :) Do you know when you'll do the next release or should I build it myself?

**Comment by Rajveer86** [comment]
Hey @TuxSH, I built the geoshader example and tried running it with this feature enabled in 2 different ways (pushing to Homebrew Launcher with 3dslink, and also manually starting it from the file system), however in both cases the system hangs with black screens. It works if I manually enable debugging after starting it manually.

**Comment by oreo639** [comment]
Did you try connecting gdb after it hangs? (the 3ds will wait for you to connect gdb)

**Comment by Rajveer86** [comment]
Silly me, no I didn't and you're right, the app starts once I connect gdb to the 3DS.

One thing I noticed is that forced debugging of the next app doesn't stay on once you exit the app it's used on i.e. I would like to be able to push my binary to homebrew launcher and automatically enable debugging, then exit the app and repeat, without having to keep on enabling this in Rosalina.
