### ISSUE TITLE
[suggest]Wiimmfi autopatch ds cards

### ISSUE THREAD

**Issue by GabrielCatDev** [LumaTeam/Luma3DS#1200]
CWF of nintendo DS doesn't work but luma can fixit with Wiimmfi using ActionReplay codes!!

**Comment by piratesephiroth** [comment]
wiimmfi doesn't even require https patches anymore

https://www.youtube.com/watch?v=Sh0AZR-tKwM

**Comment by eku** [comment]
> wiimmfi doesn't even require https patches anymore

Yes, but this does not work for networks where any DNS request is redirected to DNS server within this network.
