### ISSUE TITLE
CrashWhenStartingGames

### ISSUE THREAD

**Issue by Izag1** [LumaTeam/Luma3DS#1201]
**System model:**
Old 3DS
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
11.8,0-41E
[e.g. 11.6.0-39U SysNAND, 11.6.0-39J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
9.1 stable
[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (off)

PIN lock: (off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When I try to start my patched Pokémon Y version from the Cartridge this error occurred.

**Steps to reproduce:**

1. Start 3ds.

2. Start game.

3. Don't know if it will help but i used this tutorial to patch my game [https://youtu.be/k-pnqSsJBv0](url)

**Dump file:**
[crash_dump_00000005.zip](https://github.com/AuroraWright/Luma3DS/files/2569031/crash_dump_00000005.zip)

**Comment by james-d-elliott** [comment]
What happens without game patching (turn it off or change the patch folder names to test)? If it works fine then it's probably not an issue with Luma3DS and probably an issue with the patch tutorial or the way you're following it.
