### ISSUE TITLE
internal loader module busted. got an updated cleantitles anyoone?

### ISSUE THREAD

**Issue by DracoMan671** [LumaTeam/Luma3DS#1203]
**System model:**

[O2DS]

**SYS: 11.8.41U, Emu 11.8.41U:**

**B9S:**

**9.1 ctrpf/3dgx**

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: ( 4)

Splash: (before )

PIN lock: ( off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: (off )

Use EmuNAND FIRM if booting with R: (on )

Enable loading external FIRMs and modules: ( off)

Enable game patching: ( on)

Show NAND or user string in System Settings: (on )

Show GBA boot screen in patched AGB_FIRM: (on )

Patch ARM9 access: ( ?)

Set developer UNITINFO: ( off)

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by james-d-elliott** [comment]
Details maybe?

**Comment by oreo639** [comment]
I'm a bit late, however, this is probably a better question for the NH discord. If you know for certain that this is an issue with your loader module, make a nand backup and see if a ctrnand transfer fixes it (assuming you don't have a nand backup).
