### ISSUE TITLE
ARM11 crash with only specific title

### ISSUE THREAD

**Issue by Billnyot** [LumaTeam/Luma3DS#1204]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.8

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v9.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Only this certain title (Being Luigi's Mansion 2) constantly crashes every 30 minutes of game play. The reason ARM11 is giving me: "Translation - Section Error". I even deleted the game, backed up my save file, and started a new save. The game crashes as soon as dialogue begins in Egadd's laboratory. 

**Steps to reproduce:**

1. Starting a new file in Luigi's Mansion 2 produces this error

2. Playing for more than 30 minutes produces an error.
[crash_dump_00000016.zip](https://github.com/AuroraWright/Luma3DS/files/2612559/crash_dump_00000016.zip)

**Dump file:**

**Comment by Billnyot** [comment]
This is happening now with Animal Crossing New Leaf.

**Comment by Billnyot** [comment]
![20181125_165128_hdr](https://user-images.githubusercontent.com/39229088/48988775-1c1e0180-f0dc-11e8-84a9-876b379b5db0.jpg)
Here's the error screen if that helps at all

**Comment by Billnyot** [comment]
[https://youtu.be/f8YXGQ_6nj8](url) here's a video I recorded as an example of where it crashes often.

**Comment by Billnyot** [comment]
Sorry I keep accidentally opening and closing this, I'm unfamiliar with how this kind of thing works still. I tried getting this problem fixed in the Homebrew discord and they refused to help me because they think I pirated the game. Even though I paid for the game.

**Comment by MechanicalDragon0687** [comment]
you bought the game, dumped it, and got rid of the game....regardless, this isnt a luma issue

**Comment by Billnyot** [comment]
That would've been helpful to know

**Comment by Shadow322** [comment]
Can someone ban @CrisperJET ?
