### ISSUE TITLE
Luma3DS not appearing on Homescreen

### ISSUE THREAD

**Issue by ShadowMew718** [LumaTeam/Luma3DS#1207]
Recently I wanted to use PKHeX to get my friend a Pokémon and so I booted up my 2ds which has Luma but when I booted it up No apps like Luma3ds or FBI are there and so im asking for someone to tell me what the problem could be. I haven't touched my 2ds in a while nor have I modified any files on the SD Card.

I hope im asking this question at the place I should be because i really do not know and if im not then could someone tell me where I ask this question :)

**Comment by urherenow** [comment]
gbatemp.net
