### ISSUE TITLE
[Feature Request] Disable 300 title limit

### ISSUE THREAD

**Issue by Multimegamander** [LumaTeam/Luma3DS#1208]
I know Rocket Robz made an app that creates multiple home menus, however, I think it would be nicer to have one home menu with as many games as you want (ofc slowdowns if you have like 700)

**Comment by Margen67** [comment]
Duplicate of #1137 #103

**Comment by Shadow322** [comment]
Never happening so use the app

**Comment by Multimegamander** [comment]
TuxSH coming in with the damage 100
