### ISSUE TITLE
ARM11 exception, type: data abort when boot

### ISSUE THREAD

**Issue by afterdeys** [LumaTeam/Luma3DS#1210]
**System model:**

Old 3Ds

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U SysNAND, 9.2.0-20U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

9.1

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (Yes)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Everytime I boot the console, i get an ARM11 error on CORE 1
prefectch abort (svcBreak)
Fault status : Debug Event
current proces : pm (0000000000000000)

Fisrt issue i can't boot on emuNAND but still work with sysNAND. i tried to move emuNAND to sysNAND (following 3ds.guide) anda get some error with sysNAND boot.
I forgot to backup data in my sd card before moved emuNAND to sysNAND

*sorry for bad english

**Steps to reproduce:**

1. Restored sysNAND  back up the sysNAND data that I got when process moving the emuNAND to sysNAND

2.

**Dump file:**

[crash_dump_00000045.zip](https://github.com/AuroraWright/Luma3DS/files/2673814/crash_dump_00000045.zip)

**Comment by oreo639** [comment]
Uh, can you try asking in the Nintendo Homebrew discord, because this doesn't sound like a luma issue. This sounds like an issue with corrupted system files on the nand.
