### ISSUE TITLE
Cheat Engine not working with most code types

### ISSUE THREAD

**Issue by omarrrio** [LumaTeam/Luma3DS#1212]
**System model:** N3DSXL

**SysNAND version (+emu/redNAND version if applicable):** 11.9.0-42E

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** 9

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 )

Screen brightness: ( 4 )

Splash: ( Off )

PIN lock: ( Off )

New 3DS CPU: ( Clock + L2 )

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( x )

Show NAND or user string in System Settings: ( x )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

**Explanation of the issue:**
Cheat engine, only executes some codes, other don't, even if they are the same type (32bit write for example, i can activate the 999999 gold, and it would work, and when i activate 8000 exp after battle, it won't, basically they are the same thing, freezing a value)

**Steps to reproduce:**

1. Put code in cheats.txt in your title folder in luma
**for example:**
```
[999.999 casino coins]
D3000000 00000000
00581ED0 000F423F

[Gain 1000 Gold After Battle]
D3000000 00000000
0058260C 000003E8
```
2. Above one (Coins) will work, while the gold one won't, switching positions doesn't do a thing.
?. It's random, some will work, some won't, is the types support bad or ?

**Dump file:** No dump since it's not an exception.

**Comment by TuxSH** [comment]
Should be fixed in v10.0
