### ISSUE TITLE
Arm11 Excepition Error                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Arm11-Crash-Kernel-Panic                                                                                                                             

### ISSUE THREAD

**Issue by IceNess1** [LumaTeam/Luma3DS#1216]
[crash_dump_00000006.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/2746281/crash_dump_00000006.dmp.zip)

**System model:**

New 2DS

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.9.0-43U SysNAND, 11.9.0-43U EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

Via Boot9Strap/Sighax,

**Luma3DS version:**
    9.1

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (no)

PIN lock: (no)

New 3DS CPU: (no)

--

Autoboot EmuNAND: (no )

Use EmuNAND FIRM if booting with R: (no)

Enable loading external FIRMs and modules: (no)

Enable game patching: (no )

Show NAND or user string in System Settings: (yes )

Show GBA boot screen in patched AGB_FIRM: (no )

Patch ARM9 access: (no )

Set developer UNITINFO: (no )

Disable ARM11 exception handlers: (no)

--

**Explanation of the issue:**
i cant boot into the home menu the arm11 just pops out when i turn my new 2ds on

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by IceNess1** [comment]
any help
please

**Comment by oreo639** [comment]
Can you explain what you did right before getting the crash?

**Comment by Margen67** [comment]
@IceNess1 @Oreo639 The issue tracker isn't for tech support.
Did you really have to make three issues for this? #1215 #1214

**Comment by IceNess1** [comment]
I don't know why it kept crashing on me and I installed a game in gm9 a title then the  crash happend

**Comment by IceNess1** [comment]
or a game from FBI it was Terraria and animal crossing new leaf welcome amiibo and a ssb dlc

**Comment by IceNess1** [comment]
@Margen67 Can you help me i uninstalled b9s and now my new 2ds wont load anything well because i unstalled b9s but i still cant boot completly

**Comment by Margen67** [comment]
Close this issue and go to the Nintendo Homebrew discord for support: https://discord.gg/MjzatM8
