### ISSUE TITLE
"ErrDisp: card removed" when temperature is very cold

### ISSUE THREAD

**Issue by gingerbeardman** [LumaTeam/Luma3DS#1219]
**System model:**

New 3DS

11.9.0-42E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

B9S

**Luma3DS version:**

9.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: 1(x)

Screen brightness: 3(x)

Splash: Off(x)

PIN lock: Off(x)

New 3DS CPU: Clock+L2(x)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When my PNY brand MicroSD card gets cold the stability of Luma is compromised.

This means I cannot launch anything stored on the MicroSD card.

**Steps to reproduce:**

1. Use N3DS with Luma normally

2. Wait for temperature to drop to ~ 0'

3. ErrDisp appears

**Dump file:**
n/a

**Notes:**
This weekend I plan to return the icroSD card to the store, as it has a 2 year warranty. But before that, let me know if there are any tests you'd like me to run. I suppose that the performance of the card drops in low temperatures and falls outside of the window for Luma/timings to work correctly.

**Comment by Derek1199** [comment]
This isn't a Luma issue. Furthermore, This is caused by temperature. Not luma's fault at all.

**Comment by gingerbeardman** [comment]
The error message is Luma.

Yes, the temperature is not a Luma problem, but I think Luma timings could be relaxed so that SD cards will work in all conditions.

> I suppose that the performance of the card drops in low temperatures and falls outside of the window for Luma/timings to work correctly.

**Comment by ihaveamac** [comment]
It's Nintendo's firmware that raises this error, Luma3DS doesn't influence it in any way.

**Comment by ghost** [comment]
Any and all non-weather-resistant electronics will falter in very frigid or hot temperatures; this is an inevitability of the way they work. Additionally, PNY is a low tier flash storage company and likely has even worse durability than more typical flash storage OEMs. However, it could also be the 3DS itself, of course; for instance, many smartphones shut off and become inoperable in frigid cold when their batteries begin to hit the 10-30% range (that percentage creeping higher and higher as the temps get colder).

Not a Luma issue, and in fact not something even Nintendo could fix.

**Comment by gingerbeardman** [comment]
I have bought a new SanDisk card and that is operating fine in the low temperature with the same N3DS, so it's definitely the PNY card (64GB, UHS-1, MicroSDXC). 

I thought this was an interesting problem, worth investigation.

**Comment by gingerbeardman** [comment]
> It's Nintendo's firmware that raises this error, Luma3DS doesn't influence it in any way.

@ihaveamac this is the error message, I understood it was from Luma?

![38775836-1c609d0c-405a-11e8-832a-aee260c3606d](https://user-images.githubusercontent.com/49612/52172222-09225000-2763-11e9-96f0-ca945d65e483.png)

**Comment by kitlith** [comment]
The *screen* is from luma. The message itself comes from the OS itself if I'm understanding correctly.

**Comment by 823403553** [comment]
maybe cold weather makes your card be thin

Gabriel Wang
+8613285319970

在 2019年2月3日，上午11:23，Matt Sephton <notifications@github.com<mailto:notifications@github.com>> 写道：


It's Nintendo's firmware that raises this error, Luma3DS doesn't influence it in any way.

This is the error message, I understood it was from Luma?

[38775836-1c609d0c-405a-11e8-832a-aee260c3606d]<https://user-images.githubusercontent.com/49612/52172222-09225000-2763-11e9-96f0-ca945d65e483.png>

**Comment by 823403553** [comment]
I don’t understand how you could play 3ds in that cold place? How are your hands?😂😂😂😂😂😂


 Gabriel Wang
+8613285319970

在 2019年2月3日，上午11:23，Matt Sephton <notifications@github.com<mailto:notifications@github.com>> 写道：


It's Nintendo's firmware that raises this error, Luma3DS doesn't influence it in any way.

This is the error message, I understood it was from Luma?

[38775836-1c609d0c-405a-11e8-832a-aee260c3606d]<https://user-images.githubusercontent.com/49612/52172222-09225000-2763-11e9-96f0-ca945d65e483.png>

**Comment by gingerbeardman** [comment]
It's winter here ⛄️
