### ISSUE TITLE
Developer mode

### ISSUE THREAD

**Issue by VegaRoXas** [LumaTeam/Luma3DS#122]
Don't know if this is a bug or if I missed something. My o3ds just freezes when saving the config after enabling the developer options. I tried every dev release there is and none works. Booting Luma without the option works fine.

**Comment by TuxSH** [comment]
Did you try the latest commit? http://astronautlevel2.github.io/Luma3DSDev/builds/Luma-fcb8edff.zip

**Comment by VegaRoXas** [comment]
Thank you very much, this finally worked :+1:
