### ISSUE TITLE
3DS New Black screen after deleting CFW luma with ARM9 exception

### ISSUE THREAD

**Issue by issuer423** [LumaTeam/Luma3DS#1220]
So my Nintendo 3DS New came up with this error after updating it to 11.9:
ARM9 data abort.
I did exactly what this video said hoping that deleting luma and other mods will restore my 3ds back to normal.
Link: https://www.youtube.com/watch?v=xzP3JlCIOA4&t=153s

Now I got black screen forever, never booting to home menu..
Any  h e l p ?

**Comment by oreo639** [comment]
If you uninstalled cfw, then this clearly is an issue with your system, not luma. (Protip: don't uninstall cfw if you don't have a working system and don't know what the risks are)
The issues section is for posting bugs or enhancements. For general help, you can join the NH discord.

**Comment by Nemris** [comment]
There's an [official procedure](https://3ds.hacks.guide/uninstall-cfw) to remove CFW. Random YouTube videos are always a bad idea, when an official method exists. Especially if that random video dates back to 2017.

**Comment by Margen67** [comment]
Removing CFW is never the solution anyways, not that they would know since they clearly can't read or use GitHub properly.

**Comment by MasterGamingYT** [comment]
Don't remove CFW on a device that works, plus video guides aren't a good idea since they can be outdated, use 3ds.hacks.guide

**Comment by ihaveamac** [comment]
This is an old issue.

**Comment by MasterGamingYT** [comment]
Oh I forgot :(
