### ISSUE TITLE
Latest commit "a7100a1" issue

### ISSUE THREAD

**Issue by Sempiternalsharp** [LumaTeam/Luma3DS#1225]
I have an error after compiling the last commit of Luma3DS, when I want to use it from the CTRNand (without SD) it does not let me turn on the console and it does not access the configuration menu of Luma3DS keeping Select before turning on.

**Comment by Shadow322** [comment]
fix your compiling environment because it compiles fine and works as intended

**Comment by Sempiternalsharp** [comment]
> fix your compiling environment because it compiles fine and works as intended

The boot.firm from the microSD/SD memory works without problems, it stops working when you try to run from the CTRNand (without SD).

**Comment by Multimegamander** [comment]
There's no need to compile Luma, get a release from the release tab, or get an hourly from https://github.com/hax0kartik/luma-hourlies/releases

**Comment by Shadow322** [comment]
> 
> 
> There's no need to compile Luma, get a release from the release tab, or get an hourly from https://github.com/hax0kartik/luma-hourlies/releases

not always reliable have many times in the past these people setup a compiling bot and over time something changes in the code or compiling environment changes to where the compilers go dead because of it best to compile yourself

**Comment by Multimegamander** [comment]
Kartik can fix it...

**Comment by 823403553** [comment]
Oh~yeah~ boy next door~

王晓辰 Gabriel Wang
+8613285319970

在 2019年3月9日，下午12:30，Multimegamander <notifications@github.com<mailto:notifications@github.com>> 写道：


Kartik can fix it...

**Comment by Shadow322** [comment]
> 
> 
> Kartik can fix it...

they always say that and it always falls threw

**Comment by TuxSH** [comment]
reverted, should work now
