### ISSUE TITLE
Will it succeed? 

### ISSUE THREAD

**Issue by bleeding4x** [LumaTeam/Luma3DS#1231]
Not a support thing, just curious if 11.9 is compatible with the newest luma update (directly from the luma updater)
![screenshot chrome ](https://user-images.githubusercontent.com/48813598/54795100-d819b400-4c18-11e9-8efc-be0a1ec42813.jpg)

**Comment by Multimegamander** [comment]
Yes... you could have tried before making an issue, the worst that will happen is a print statement...
