### ISSUE TITLE
Crash when holding L+R on Pokemon mand going to HOME

### ISSUE THREAD

**Issue by pokelector** [LumaTeam/Luma3DS#1238]
I am on the most recent release of Luma, 9.1. N3DS.
All my settings are off in Luma config.

This is an oddity. Holding L+R on Pokemon Ultra Sun/Moon and going to HOME menu causes a menu crash.

Arm11
Prefetch abort
Debug event
Menu (0004003000008f02)

Oddly it only does it on the main cutscene when you first boot the game. You know, the part where it says Press Start and then plays a little movie.
It doesnt do it in-game, or even on the part where you click on your trainer profile to begin playing. It only happens in the part before you press START. 

Happens in Alpha Sapphire, X, Sun, Ultra Sun/Moon, all at the same PRESS START movie. Only happens there, and same error.

It does not crash in game, only in the beginning movie where it tellsyou to press start. Happens in all 3ds pokemon gamea it seems.

**Comment by TuxSH** [comment]
Already fixed in 8345f31c2a120a06d35e32bf85b5379613945968
