### ISSUE TITLE
Custom string not showing in system settings

### ISSUE THREAD

**Issue by MasterGamingYT** [LumaTeam/Luma3DS#1239]
This post is obsolete now

**Comment by MasterGamingYT** [comment]
Also the custom string I put was: LUMA3DS 11.9

**Comment by MasterGamingYT** [comment]
24 hours and yet no answer

**Comment by RocketRobz** [comment]
Did you enable showing custom strings in Luma3DS configuration?

**Comment by ghost** [comment]
Believe it or not, no one's getting paid to dev this project or provide "customer service", @MasterGamingYT. 

Custom version text works for me.

**Comment by tstambaugh92** [comment]
Is Luma copied to NAND? You could try copying that file to NAND as well, I did that for my lock screen PIN I believe

**Comment by MasterGamingYT** [comment]
I enabled "Show Nand or user string in system settings" @RocketRobz

**Comment by MasterGamingYT** [comment]
Alright I got it working with the help of the Nintendo Homebrew Discord!

**Comment by tstambaugh92** [comment]
it would be helpful if you posted what was wrong and how you fixed it in case someone comes posting about it again.

**Comment by MasterGamingYT** [comment]
I changed it, because I solved it
