### ISSUE TITLE
[bug] Some titles hanging with black screen when launched on commits 1041d7c and newer

### ISSUE THREAD

**Issue by Searinox** [LumaTeam/Luma3DS#1240]
**System model:**

New 3DS XL

11.9.0-42E

**Entrypoint (How/what you're using to boot Luma3DS):**

B9S v1.3

**Luma3DS version:**

Commit 1041d7c and newer.

**Luma3DS configuration/options:**

Default EmuNAND: N/A

Screen brightness: ( 4 )

Splash: ( 1 )

PIN lock: ( Off )

New 3DS CPU: ( Off )

Autoboot EmuNAND: N/A

Use EmuNAND FIRM if booting with R: N/A

Enable loading external FIRMs and modules: ( False )

Enable game patching: ( True )

Show NAND or user string in System Settings: ( False )

Show GBA boot screen in patched AGB_FIRM: ( True )

Patch ARM9 access: N/A

Set developer UNITINFO: ( False )

Disable ARM11 exception handlers: ( False )

--

**Explanation of the issue:**

Aformentioned build fails to start Super Smash Bros.. Other extended memory titles were tried(Pokemon SM, MH4, Mario Maker) and they work fine. Once game is launched, the initial Nintendo 3DS splash screen is shown then transition to a black screen occurs, where it halts indefinetly. Interestingly enough, pressing A during that black screen will cause the console to restart.

Issue will occur regardless of whether just the title is installed or also update, external data, or save data presence. A clean reinstall of the CIA with delete title + ticket beforehand was attempted. The result did not change.

Issue does NOT occur on commits 74bbfb9 and older.

**Steps to reproduce:**

1. Boot console on latest firmware with Luma3DS commit 1041d7c or newer.

2. Launch Super Smash Bros.

**Dump file:**

N/A

**Comment by BeastSE7** [comment]
I have looked over the entire Webs, I cannot find anything about this issue, now you have nailed exactly what is happening with me as well, on 2 N3dsXL units, Both go black screen on SSB and Detective Pikachu and Sonic Boom both f&i and shattered crystal!

Please can somebody help with this issue?
Both Units are 11.9.0.42E with B9S1.3 latest luma3ds

**Comment by Searinox** [comment]
> I have looked over the entire Webs, I cannot find anything about this issue, now you have nailed exactly what is happening with me as well, on 2 N3dsXL units, Both go black screen on SSB and Detective Pikachu and Sonic Boom both f&i and shattered crystal!
> 
> Please can somebody help with this issue?
> Both Units are 11.9.0.42E with B9S1.3 latest luma3ds

Hello, what version of Luma3DS are you using and if it's also a nightly, does it fix itself when using the commit I mentioned or even way back the official 9.1 release?

**Comment by BeastSE7** [comment]
Ok yes, If I use the 9.1 release the system returns to normal and will play all games without issue.
Originally I used the latest 179-luma3ds-e57b546 because GodMode9 wouldnt show the touchscreen so I couldn't use any menus to finalise the install, I then installed FastBoot1.2 then godmode9 run without issue but the Console wouldn't play any extended memory games by the looks of things (SSB) then flashing 9.1 release into it, godmode9 has no touch screen again BUT I can play everything so I don't care now if GM9 doesn't work

**Comment by MasterGamingYT** [comment]
Try with stable release, also people reported that luma hourlies brick consoles, according to luma updater

**Comment by fireworksordie** [comment]
i can confirm this as well using last night's build for (commit e11cc09). detective pikachu opens and sits at black screen but works again when i revert to release 9.1. if i have some time tomorrow i'll try going back through nightlies to see if i can help pinpoint the start of the issue.

**Comment by Searinox** [comment]
I went through the commits. The last commit that works and is available as binary from Kartik is 74bbfb9 . The next commit - e57abad - is not available as binary for testing. The commit after that - 1041d7c - which is available as binary - is the first in which Smash Bros. breaks. SSB then remains broken in all subsequent commits.

**Comment by TuxSH** [comment]
That's annoying. Which titles break, aide from SSB and Detective Pikachu? Does it happen on old3ds as well?

fastboot shit is totally irrelevant.

**Comment by Searinox** [comment]
I do not have an o3ds to test with so waiting for other people to chime in.

**Comment by Searinox** [comment]
I can now confirm this also happens on an O3DS. Same behaviour - black screen indefinetly, A restarts the console.

**Comment by profi200** [comment]
Any exception dump on the SD card? It sounds like a crash with blackscreen.

**Comment by TuxSH** [comment]
@profi200 or more like an errdisp, but with the screen not being initialized.

I can reproduce

Address:          0x002c5850
Error code:       0xe0a01839

**Comment by Searinox** [comment]
Looked but couldn't find one. No dumps folder created even.

**Comment by TuxSH** [comment]
luma/errdisp.txt (latest commit makes errdisp reimpl always log to a file), it's not a crash dump.

**Comment by TuxSH** [comment]
It's a pm bug causing an error in kernel:

I probably forgot to set reslimit properly, I'll have a more thorough look later.

**Comment by TuxSH** [comment]
Latest commit should have fixed it
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/3087364/boot.zip)

**Comment by fireworksordie** [comment]
can confirm your ZIP works (on my new 3ds). detective pikachu boots when it did not before. thanks for the quick fix!

**Comment by Searinox** [comment]
Confirming SSB is working again with provided binary.

**Comment by andreltrigo** [comment]
I'm having the same issue on the latest release (v10.0.1): black screen after logo and A restarts console. I'm using an O3DSXL on 11.10.0-43U.

Here's the errdisp dump:
> Error type: generic
> Process ID: 40
> Process name: STORYOFS
> Process title ID: 0x0004000000142100
> Address: 0x0011dd80
> Error code: 0xf96047a2

**Comment by grepo11** [comment]
running the latest release on a 2ds, I also want to point out that any button press restarts the console. the game i'm seeing this error for is omega ruby, errdisp:

Error type:       generic
Process ID:       38
Process name:     sango-1
Process title ID: 0x000400000011c400
Address:          0x001181e8
Error code:       0xf96047a2

**Comment by torchicx19** [comment]
> Confirming SSB is working again with provided binary.

How did you did it? I have the same problem, please explain me how to fix it!
