### ISSUE TITLE
Beug 11.9 Luma

### ISSUE THREAD

**Issue by Yaya48** [LumaTeam/Luma3DS#1244]
Hello I hacked my 3ds in 11.9 with b9s 1.3 and luma 9.1 but I have a lot of bugs with hombrew like for example fbi that freezes at launch 1 time out of 5 or hombrew that crashes me there with an error message Like the app had an error the console will restart

That's all I have for a bellow.

**Comment by urherenow** [comment]
Did you install hblauncher_loader or are you launching the homebrew launcher with steelhax every time? Or are you launching it with Rosalina?

**Comment by Yaya48** [comment]
steelhax doesn't work anymore after installing lima and yes I have hbluncher loader on hbl it tells me rosalina so yes I launch with rosalina 
Oh yes and also I launch fbi from the home menu

**Comment by urherenow** [comment]
Punctuation is important. I can’t tell from your comment if you’re using hblauncher_loader, or if you’re using Rosalina. Really, you might be helping other people out if you could do several tests launching hbl via hblauncher_loader, then doing the same using Rosalina, and report if one gives you this issue more than the other (or not...).

**Comment by Yaya48** [comment]
with rosalina I have no problem but with hbluncher loader its freeze once out of 2 times at launch

and fbi that appears when I launch it from the home menu 1 time out of 10 freeze and luma updater that once out of 5 freeze when it is necessary to check the update check it freezes and it leaves and it tells me an error has occurred the console will restart

**Comment by urherenow** [comment]
Those are odd results. Especially loading FBI from the home menu. Have you checked your memory card for errors using H2testw? And is it formatted with 32k or 64k clusters? No fragmented files?

**Comment by Yaya48** [comment]
so h2testw told me that I have no error and my card will be and in fat32 32 cluster and for the content look at the picture
https://imgshare.io/image/ZCw8L
My Sd Card is Good ?

**Comment by TuxSH** [comment]
This is not an assistance channel. Please go to https://discord.gg/C29hYvh
