### ISSUE TITLE
idk what to put here

### ISSUE THREAD

**Issue by Multimegamander** [LumaTeam/Luma3DS#1253]
The loader sysmodule won't compile after this commit 
https://github.com/AuroraWright/Luma3DS/tree/74bbfb95d3a01e815ee19f967018b603d5f365d3
unlike the PR (which still didn't help) it's not a user error as I'm compiling unedited code 

here's a video of trying to compile anything newer: https://www.youtube.com/watch?v=MQusAl7Z7Aw

**Comment by Nuck-TH** [comment]
Mind that anything that not release is WiP, so changes may be unfifnished and break stuff.
Please stop the noise.
