### ISSUE TITLE
The flashcart Stargate3DS can't run DS mode correct. 

### ISSUE THREAD

**Issue by FlameBeam** [LumaTeam/Luma3DS#1263]
**System model:**

new3DS

**SysNAND version:**

11.10.0-43J SysNAND

**Entrypoint:**

Boot9Strap

**Luma3DS version:**

9.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4 )

Splash: (off )

PIN lock: (off )

New 3DS CPU: (off )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( * )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

The flashcart Stargate3DS can't run DS mode correct. 
When this cart run DS mode in a OFW console, it will be in a wood UI like R4i. But when it run DS mode in Luma3DS CFW, it will run like a genuine DS cart (it run the rom in the flashcart what is display on homemenu.

**Steps to reproduce:**

1.Launch the DS icon on home menu with Luma3DS CFW. The Game display on home menu is ALEX RIDER STORMBREAKER, same as the DSTWO.

2.The flashcart run into the game what is display on home menu instead of into the wood menu.

3.In OFW console, the DS mode will be run correct.

**Comment by TuxSH** [comment]
This is probably due to crappy workarounds made by the cards to bypass anti-flashcart checks, checks which Luma3DS removes to enable compatibility with a much larger number of flashcarts.

Try to remove this line, or the ones around it and rebuild: https://github.com/AuroraWright/Luma3DS/blob/master/arm9/source/firm.c#L448
