### ISSUE TITLE
Both screens are black but can hear menu music

### ISSUE THREAD

**Issue by dferrari24** [LumaTeam/Luma3DS#1265]
An error occurred (errdisp)
Error type: generic
Process id: qtm
Process title id: 0x0004013000004202
Address: 0x00103f18
Error code: 0xf96183fe

had this issue originally, but now after restoring my nand, now i dont see both screens

**Comment by TuxSH** [comment]
You broke your head-tracking hardware.

You could uncomment https://github.com/AuroraWright/Luma3DS/blob/master/k11_extension/source/ipc.c#L301 to have a somewhat working device (sleep mode will not work); but the fact remains that you console is damaged

**Comment by dferrari24** [comment]
ah ok, how would i go about doing that, im new to brewing
