### ISSUE TITLE
IR Patch causing SYSCORE slowdown

### ISSUE THREAD

**Issue by PabloMK7** [LumaTeam/Luma3DS#1267]
Apparently, the way irrst is patched causes its thread to consume too much CPU resources. This bug was discovered by @Nanquitas while he was working on the plugin loader. He has been offline for several months and the fix was never pushed to his github repo (as he planned to release everything alltogether). However, this issue is being a pain to all CTRPF devs so I decided to create this issue.

Here is the conversation we had with Nanquitas as he was trying to fix the issue:

> I finally find what causes the slowdown !
> Example in mk7 the fps could go from 60fps to ~43 fps for no obvious reason
> And it's all because of the hid service :thinking:
> Not initializing it makes the fps go back to ~60 fps
> ...
> Ah, it's not hid directly but irrst
> ...
> Yup, I still had a doubt whether it was because of the plugin or not so I timed how much it took for the mini video to be played in it's entirety with and without plugin
> With plugin (but no threads so disabled) it still took from +8s to +10s!
> And since I didn't start any thread it ruled out all ctrpf components and I was left with ctrulib initialization part
> ...
> And it seems to be related to the ir patch made by luma3ds
> Seems logic since the patch remove an svcWaitSync, I assume that it causes the thread to use too much cpu resources
> ...
> Hmm, svcSleepThread seems to be quite inefficient if called multiple times (especially with low sleep value)
> Most likely because it reschedule all threads with same priority (yield thread control)
> ...
> Problem fixed 
> I actually changed my idea, I just restored the original svcWaitSync to use the correct timeout value and I just force the  the input fetch after it

I took a look at the ir patch but I'm not familiarized with it at all, so I created this issue instead of trying to implement the fix and messing things up.

**Comment by Nanquitas** [comment]
Should be fixed with this commit: b17eb66d55fe0df891d50bfb493062cb61a76104
