### ISSUE TITLE
Boot version

### ISSUE THREAD

**Issue by NightScript370** [LumaTeam/Luma3DS#127]
What version can this boot from/What is the minimum firmware version?

**Comment by gnmmarechal** [comment]
Is this really worth opening an issue?

**Comment by NightScript370** [comment]
It's for my guide. I made a 9.2 update page using Luma3DS so I want to know what's the minimum firmware version it can run.

**Comment by ihaveamac** [comment]
if you mean what version can Luma3DS be run from, 7.0 is the minimum. it doesn't take a slot0x25KeyX.bin file or anything.

**Comment by NightScript370** [comment]
Thanks. Would this guide work then: https://github.com/maorninja/Guide/wiki/9.2.0-Update-(Luma3DS-and-Ninjhax)   ?

**Comment by urherenow** [comment]
Github is not a forum. This space is for reporting issues. Close this, because it isn't one.
