### ISSUE TITLE
an exception occured 

### ISSUE THREAD

**Issue by stoonky-g** [LumaTeam/Luma3DS#1274]
after following a guide from 3ds.hacks.guide , and completing the tutorial, my homebrew launcher no longer works. I was using steel diver as an entry point. Now when loading in, an error screen appears. Processor: ARM11 (core 1) Exception type: data abort
Fault status: Translation - Page
I am new to all of this, and don't know what went wrong. Can anybody help?

**Comment by james-d-elliott** [comment]
The guide should instruct you how to enter Homebrew. You need to open an app then do L DOWN SELECT and set the hb app (Miscellaneous options > Switch the hb. title to the current app). If you close it and open again, it will replace that title with sd:/boot.3dsx

You only have to do the L DOWN SELECT part once. :)
