### ISSUE TITLE
Some LayeredFS patches do not work anymore on v10

### ISSUE THREAD

**Issue by GlazedBelmont** [LumaTeam/Luma3DS#1275]
Pokemon Reaper Sun and Nightmare Moon doesn't work (loads to stock title screen). I don't know if I'm allowed to link the patch files because they contain some files that I don't think are in the legal zone. 

Some users also have been suffering from layeredfs patches not working.

GlaZed_Belmont#0177

**Comment by TuxSH** [comment]
some other games affected?

**Comment by jerrwu** [comment]
Can confirm, the English patch for Taiko no Tatsujin is also broken

**Comment by Amapola62** [comment]
Can confirm the Gay Fates patch is broken too.
