### ISSUE TITLE
Exception Error after using MicroSD Management

### ISSUE THREAD

**Issue by Pokemiah** [LumaTeam/Luma3DS#1279]
**System model:**
New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**
11.10.0-43U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**
Sighax

**Luma3DS version:**
v10.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Off)

Splash duration: (1)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Shortly after I updated to Luma v10.0 I went to update some of my homebrew programs. Since I use the New 3DS XL I can't exactly get the microSD card without unscrewing the back so instead I use the microSD management option in the Data management menu in the System Settings. As soon as I exited out of the process the 3DS just crashes giving me an exception error under the pretense of prefetch abort (svcBreak). I didn't have this issue until after the recent update of Luma3DS. I can consistently recreate the issue so I believe it's a flaw in Luma. However, none of the files I transferred seem to have corrupted.

**Steps to reproduce:**

1. Go to System Settings.

2. Select Data Management.

3. Select MicroSD Management.

4. Exit MicroSD Management. (It seems to crash whether or not you do anything in there.)

**Dump file:**

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/3347102/crash_dump_00000000.zip)

**Comment by ghost** [comment]
Yup, same thing happens to me on Luma 10.0. I restored my old Luma version (9.1) for now and on that older version it does not crash.
I have a New 2DS XL, for now i'll stay on Luma 9.1.

**Comment by TuxSH** [comment]
Duplicate. Latest commit fixes it, trying to find layeredfs regression before doing a new hotfix release.

**Comment by AndrewHend** [comment]
Thanks so much for doing this guys, really appreciate all the hard work.  I look forward to this new hotfix.
