### ISSUE TITLE
DS and DSi ware not working 

### ISSUE THREAD

**Issue by iamapie13** [LumaTeam/Luma3DS#128]
Hello, I decided to instal the arm9loaderhax versión of luma and now my DSi and DS games show black screen, I tried to instal a TWL_FIRM patch, but it didn't work

**Comment by ihaveamac** [comment]
if "arm9loaderhax.bin" is not Luma3DS (boot manager, etc), you need to use the pathchanger.
https://github.com/AuroraWright/Luma3DS/wiki/Installation-and-Upgrade#optional-making-luma3ds-work-with-an-external-boot-manager

installing a TWL_FIRM patch doesn't help, instead you should undo that.
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-have-issues-with-gbadsdsiware-games-and-i-have-installed-a-patched-agbtwl-firm-cia-in-the-past

**Comment by TuxSH** [comment]
Please read the wiki before asking (just click on the links @ihaveamac gave you)

**Comment by iamapie13** [comment]
Thank you for the help, I'll try to undo the TWF patch, I only need the ID of the CIA to get it from Nus, but I can try to figure that on my own

**Comment by ihaveamac** [comment]
if you actually read the second wiki page I linked you to, it gives you a link to TWL_FIRM.........

**Comment by iamapie13** [comment]
sorry, my apologies, I forgot to see it, I was rushing in school
