### ISSUE TITLE
Ntr crashes on luma 10.1

### ISSUE THREAD

**Issue by Nor0o** [LumaTeam/Luma3DS#1289]
Last night i updated luma and i was gonna use some cheats on my 3ds and then, crashed.
Im not the only one who have this problem. 
So please fix it.

-Thank you-

**Comment by jonirrings** [comment]
luma 10 disabled the pm patch which used by ntr as the release note.
if you need cheat, maybe you could try [gateshark](https://github.com/FlagBrew/Sharkive) or an early version luma with ntr.

**Comment by Shadow322** [comment]
just chain-load 9.1 if u want to use NTR
