### ISSUE TITLE
Luma version 10.0.0/1 breaks exheader patching via game patching

### ISSUE THREAD

**Issue by DeathChaos25** [LumaTeam/Luma3DS#1290]
As title says, before this version, Luma could load patched exheaders no problem, most commonly this is done because of [Magikoopa](https://github.com/RicBent/Magikoopa) being used to add more custom code and thus expanding the code.bin, needing an exheader edit, but now it is impossible to use patched exheaders as luma is causing a game with a patched exheader (via game patching) to [crash on boot](https://github.com/DeathChaos25/PQ2_MC_Name_Patch/issues/4).  
  
Note that this is not an issue on the previous Luma version, as a custom CIA or on Citra, which is why we know this version of Luma is to blame.

**Comment by leoetlino** [comment]
This has been fixed by https://github.com/AuroraWright/Luma3DS/pull/1287

(here's a build that includes that fix: https://github.com/leoetlino/Luma3DS/releases/tag/v10.0.1-bps.3 -- ignore the BPS stuff, I might submit that to upstream after I reformat the code)
