### ISSUE TITLE
Button configuration is not being saved

### ISSUE THREAD

**Issue by hfc2x** [LumaTeam/Luma3DS#1291]
**System model:**

New 3DS, Old 3DS

**SysNAND version:**

11.6.0-39U SysNAND and 11.10.0-43E SysNAND respectively.

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

10.0.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( x )

Show NAND or user string in System Settings: ( x )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Whenever I try to change the Rosalina Menu button configuration from the default, it's only saved during the current sesion. Turning off the device or launching a NDS game reverts it back to the default setting of L+Down+Select. Tried also on my New 3DS and it also doesn't work. It stopped saving once I updated to 10.0.1.

**Steps to reproduce:**

1. Open Rosalina Menu by holding L+Down+Select.

2. Go into Miscellaneous Options, and Change the Button Configuration.

3. Change it to other than the default of L+Down+Select.

4. Close Rosalina Menu.

5. Power off the console or launch either an NDS game or DSi app.

6. Power on the console or go back to Home Menu and try opening Rosalina Menu.

7. Open it again with the default button config, and see it reverted back to the default.

**Dump file:**
None.

**Comment by david4444** [comment]
User error.
You can save, go to miscellaneous options and press save settings.
