### ISSUE TITLE
[Feature Request] Remove Miiverse from the main menu

### ISSUE THREAD

**Issue by Mark-B97** [LumaTeam/Luma3DS#1292]
**System model:**

Any 3ds

**SysNAND version (+emu/redNAND version if applicable):**

Any FW

**Entrypoint (How/what you're using to boot Luma3DS):**

--

**Luma3DS version:**

--

**Explanation of the issue:**

Please do what nintendon't

Could also maybe make it optional? Put it on rosalina menu, etc.

**Comment by ihaveamac** [comment]
This is harder than it seems since it requires editing the layout of the HOME Menu, which I don’t know if anyone has done that yet. It’s also something that Luma3DS would be unlikely to have built-in.

If anyone wants to attempt, the KOR HOME Menu does not have the Miiverse button.
