### ISSUE TITLE
Heroes Of Ruin (EU/US) crash with luma 10.0.1 

### ISSUE THREAD

**Issue by lkclip** [LumaTeam/Luma3DS#1293]
**System model:** Old 3DS

**SysNAND version (+emu/redNAND version if applicable):** 11.10.0-43E

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** 10.0.1

**Luma3DS configuration/options:**

Screen brightness: (4)

Splash: (Off )

Splash duration: (1x )

PIN lock: (Off )

--

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Digital image of Heroes Of Ruin (US) crashes during the first loading screen, and (EU) crashes after street pass notification request. It seems like the crash happens on autosave, because once save is created on EU version (by loading external Luma3DS 9.1 firm) the game launches fine. Issue confirmed by me and another redditor

**Steps to reproduce:**

1. Launch the title

**Dump file:** Error message doesn't show file path
![Безымянный](https://user-images.githubusercontent.com/50055911/61380299-8b8e6e80-a8c2-11e9-9ae1-b66c68cd7d71.png)

**Comment by brunocar** [comment]
Can confirm that I get the same error on the same game on a New 3DS XL with the same Luma version and similar settings.

**Comment by ghost** [comment]
I too, get the same error on 10.1 on a N3DSXL

**Comment by Captain-Wet-Beard** [comment]
I'm experiencing the same error on an old 2DS and a new 3DS, both running the same version of Luma

**Comment by meepingsnesroms** [comment]
Can someone test this with "Disable ARM11 exception handlers" on, I have crashing in New Super Mario Bros 2 but its not reliable like it is in this game.

**Comment by brunocar** [comment]
> 
> 
> Can someone test this with "Disable ARM11 exception handlers" on, I have crashing in New Super Mario Bros 2 but its not reliable like it is in this game.

already tried it, doesnt change anything

**Comment by brunocar** [comment]
Any updates on this?

**Comment by Captain-Wet-Beard** [comment]
I'm also curious if anyone is actively working on this/ has made any progress yet.
I'm very interested in playing this with my girlfriend, and have had no luck as of yet.

**Comment by brunocar** [comment]
Right now the only workaround is simply downgrading to the previous luma version

EDIT: from what i've seen this bug affects smash bros, NSMB2 and MHG

**Comment by Captain-Wet-Beard** [comment]
I haven't had any issues with Smash Bros, but I haven't tried NSMB2 or MHG yet.

Does anyone have any idea what the cause of the issue might be?

**Comment by brunocar** [comment]
As already stated in another related issue, it seems that someone messed up and mixed up the check calls so that certain positive responses are instead replaced with the errdisp response, which is there to report errors.

**Comment by Captain-Wet-Beard** [comment]
Oooh, ok. Thanks for the information.

**Comment by oreo639** [comment]
> As already stated in another related issue, it seems that someone messed up and mixed up the check calls so that certain positive responses are instead replaced with the errdisp response, which is there to report errors.

The information returned by errdisp on 10.0.1 and 10.0 is incorrect. (the information being incorrect on 10.0 and 10.0.1 is a known bug)
It didn't actually return 'sucess'.
Unless you already knew that.

> Can someone test this with  "Disable ARM11 exception handlers" on, I have crashing in New Super Mario Bros 2 but its not reliable like it is in this game.

 "Disable ARM11 exception handlers" just turns off luma's arm11 exception handlers. It doesn't prevent the crash from happening, it just lets the HOS handle the exception instead of using luma's exception handler which displays info on the crash.

It is also irrelevant since this isn't an arm11 exception and is just an error.

**Comment by Captain-Wet-Beard** [comment]
Ah, thanks for the clarification.

**Comment by oreo639** [comment]
Can someone try reproducing the error and then paste their final entry of `/luma/errdisp.txt`

**Comment by brunocar** [comment]
for sure, i'll edit this comment once i can do it
[errdisp.txt](https://github.com/AuroraWright/Luma3DS/files/3773972/errdisp.txt)

**Comment by brunocar** [comment]
Edited! its quite long after experimenting with it

**Comment by oreo639** [comment]
Tysm.

**Comment by brunocar** [comment]
you are welcome, anything you can tell us from it? i think its plenty obvious that errdisp is the the key to understanding this, but thats as far as my knowledge goes

**Comment by oreo639** [comment]
BOSS sent a logged error.
I don't think logged errors are supposed to be fatal (and trying to create a logged error in a test application when using the patch seemed to allow execution to continue), but since the problem explained here: https://github.com/AuroraWright/Luma3DS/pull/1332
the data in the memory that `info` points to changes during writing `/luma/errdisp.txt`  resulting in`info->type != ERRF_ERRTYPE_LOGGED` returning true causing it to be displayed as a fatal error.

Correct me if I am wrong.

**Comment by Shadow322** [comment]
game works now on latest Luma3DS update as of today

**Comment by brunocar** [comment]
Awesome! thanks for the help

EDIT
Did you mean the latest code? because there is no nightly bot that i know off and the latest release is old.

**Comment by Captain-Wet-Beard** [comment]
> game works now on latest Luma3DS update as of today

I dont see a new release on the updater, which version are you referring to?

**Comment by Shadow322** [comment]
Latest comment get it at

https://github.com/hax0kartik/luma-hourlies/releases/tag/234-luma3ds-dfd50d9

**Comment by Captain-Wet-Beard** [comment]
> Latest comment get it at
> 
> https://github.com/hax0kartik/luma-hourlies/releases/tag/234-luma3ds-dfd50d9

Thank you so much, I've been waiting to play this with my fiance for months <3

**Comment by brunocar** [comment]
I tried it, it works.

🦀Errdisp is GONE🦀

**Comment by Captain-Wet-Beard** [comment]
I can also verify, it's working for me as well
