### ISSUE TITLE
within luma settings  "Enable region/language is gone

### ISSUE THREAD

**Issue by Ember-Rae** [LumaTeam/Luma3DS#1296]
that's pretty much it. I'm trying to get a nintendogs to play on a jap region 2DS xL and I get loading screen of death. I've gone into the file thing and did the .text that was JAP JP and I still get loading screen and  
"Enable region/language emu. and ext code" in Luma settings. just isn't an option in my settings. (luma 10.0.1)

**Comment by TuxSH** [comment]
It's called "Enable game patching" now
