### ISSUE TITLE
Cheats from Boot NTR Selector doesn't work anymore

### ISSUE THREAD

**Issue by Axiskhan** [LumaTeam/Luma3DS#1297]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.9.0-42E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

B9S

**Luma3DS version:**

10.0. but went back to 9.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Cheats from Boot NTR Selector 2.12  don't work

**Steps to reproduce:**

1.Lauching Boot NTR Selector 2.12 is ok.

2.Then launching the game , it does not display the green screen and so cheats don't work

**Dump file:**

**Comment by Shadow322** [comment]
fill out the damn info

**Comment by TuxSH** [comment]
luma 10.x removes support for it

**Comment by ghost** [comment]
> luma 10.x removes support for it

Then you should implement a way to *manually* search/compare/change decimal values in RAM like what Gateway used to offer. Sometimes preloaded cheat codes are not enough (and nonexistant for some games).
