### ISSUE TITLE
[Bug] N3DS Clock Settings don’t persist after power cycle

### ISSUE THREAD

**Issue by EmotionalLove** [LumaTeam/Luma3DS#1299]
(Tested with Pokèmon X battles in 3D mode with a N3DS with Luma 10.0.1 and Rosalina)

In Pokèmon X/Y on any 3DS at the standard clock speed battles with 3D enabled run at a very low frame rate, the same applies to Pokémon Alpha Sapphire/Ruby. 3D battles in Pokémon Sun/Moon and later was removed (probably due to the performance issues). Running an N3DS with the Clock or Clock+L2 setting fixes the lag in 3D battles entirely, however i’ve noticed that the setting doesn’t persist once you turn off the console (although the setting stays ticked when you power on the console with the SELECT button held)

Upon starting the console, and cycling through the Clock settings until Clock+L2 is ticked, and then proceeding with boot with the START button, and then launching Pokémon X and saving the game, and entering a battle, the user should observe the reduction/elimination of the framerate issues whilst the 3D slider is up. When the battle is over you can exit the game without saving (to test the same battle again)

If the user powers off the console entirely and turns it back on, and launches Pokémon X and does the same battle again, the user will notice that the performance issues have returned. However if the user restarts the console again whilst holding SELECT, Clock+L2 is still ticked (but isn’t having any affect until the user cycles through the list again, and presses START)

**Comment by BrandtVanDenBerg** [comment]
Check your SD card. It works for me on the latest luma so the issue is either that (a) the setting doesn't persist because it can't be saved to the SD or (b) the game forces off the N3DS CPU on startup.
