### ISSUE TITLE
Unable to load alternate payloads if default.bin is not present

### ISSUE THREAD

**Issue by 40wattrange** [LumaTeam/Luma3DS#13]
I dont know if this is a bug, or by design, but if there is no default.bin file, the alternate payloads (up/down/left/right) will not trigger at all.

I found this as I dont care so much for using Start as it is odd to do. I just prefer using up/down/left/right as I can trigger that with the left hand, and power on with the right.

Thought I'd throw this out there if it was unexpected behavior.

**Comment by astronautlevel2** [comment]
This is by design.

**Comment by AuroraWright** [comment]
Not a bug.
