### ISSUE TITLE
black screen booting in redNAND on o3DS downgraded with Gateway in the past

### ISSUE THREAD

**Issue by gmipf** [LumaTeam/Luma3DS#130]
The old 3DS (EUR) was downgraded in the past to 4.5.0 with the Gateway Launcher. Now it is on 9.2.0. Booting Luma3DS at v5.5 can only boot until the config menu. I tried about 20 times, always black screen. With v5.3 its working fine. I think the issue is after v5.3.1.

**Comment by cheatfreak47** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-get-a-black-screen-on-boot-with-an-old-3ds-which-has-been-downgraded-from-the-gateway-menu-in-the-past
