### ISSUE TITLE
SSB43DS write crash dump

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1303]
**System model: old 2DS**

[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.6.0-39U SysNAND, 11.6.0-39J EmuNAND]

**Entrypoint: Homebrew Launcher off off frogtool**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version: 11.10.0**

[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( 4)

Splash: ( After)

Splash duration: (7 seconds )

PIN lock: (No )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (Disabled )

Enable game patching: (Enabled )

Show NAND or user string in System Settings: (Enabled )

Show GBA boot screen in patched AGB_FIRM: (Enabled )

Patch ARM9 access: (N/A )

Set developer UNITINFO: (Disabled )

Disable ARM11 exception handlers: ( Disabled)

--

**Explanation of the issue:**

In Super Smash Bros. for Nintendo 3DS, when a textbox pops up, I get a write error

**Steps to reproduce:**

1. Create a new mii fighter, edit streetsmash message, rename existing mii fighter or custom fighter, or change online settings textboxes.
[crash_dump_00000001.zip](https://github.com/AuroraWright/Luma3DS/files/3453244/crash_dump_00000001.zip)

**Dump file:**

**Comment by TuxSH** [comment]
OP acount has been deleted
