### ISSUE TITLE
Possible addition to RO patches

### ISSUE THREAD

**Issue by favna** [LumaTeam/Luma3DS#131]
Some friends and I have been trying to make a custom update `.cia` also work with modified `.cro` files. Creating the modification of the rom as a custom update `.cia` has 2 big perks:
1. The game will be on the latest update so it will be allowed for online play (~~Disregarding the fact that Nintendo reportedly bans users who go online with a romhack Pokemon game but that's a whole different story lel~~)
2. It is very easy to install and use for the end-user as they only need to have a regular copy of the game as cartridge or have the game as a digital title.

Alas, the game always crashes when launching it with the custom update installed. [Whilst this tutorial by Asia8](https://gbatemp.net/threads/tutorial-how-to-rebuild-a-custom-update-for-pokémon-xy-oras.391282/) states that custom update `.cia`'s are only compatible with modified GARC's this was written very much before RO patching by ReiNAND and not much after Luma3DS was a thing. (In fact, it took my Sigma Ruby release for Asia81 to learn about this.. h/she commented on my post first asking about that haha)

That all said, I was wondering if perhaps the issue for custom update `.cia`'s (or updates at all in fact, but they seemingly never officially include new or modified `.cro`'s) to work properly requires further RO patching.

The latest version we used to test if `.cro` included custom updates use can be found [here](https://mega.nz/#!ml8i3bAB!wLG6odX50Ie_JDeHakVQphpm0SVAssPeV-jpWY2CfFQ). This custom update is for Pokemon Omega Ruby but by all means @AuroraWright or @TuxSH you can contact me on Discord any time for testing

**Comment by TuxSH** [comment]
Outdated, closing.
