### ISSUE TITLE
[Request] NTRCFW .plg support?

### ISSUE THREAD

**Issue by ParzivalWolfram** [LumaTeam/Luma3DS#1310]
Someone managed to do it once locally, is it possible to add NTRCFW .plg patch support to Luma? I've found lots of scripts I can't figure out how to port over, and now that NTRCFW is somewhat nonworking with Luma, it'd be handy.

**Comment by lucasaf04** [comment]
Use this.
https://github.com/iSharingan/CTRPF-AR-CHEAT-CODES/blob/master/Luma3DS%209.1%20-%20Plugin%20Loader.7z

**Comment by lucasaf04** [comment]
But if you want luma3ds 10.X with plug-in support it’s not compatible with .plg files, only the new .3gx format. Downloadable here:
https://github.com/mariohackandglitch/Luma3DS/releases/download/v10.0.1/boot.firm

**Comment by ParzivalWolfram** [comment]
'tis why it's a REQUEST.

**Comment by lucasaf04** [comment]
👍

**Comment by moldimolt** [comment]
Superseded: #1743
