### ISSUE TITLE
[Feature request] modules for Rosalina menu

### ISSUE THREAD

**Issue by GlowingUmbreon** [LumaTeam/Luma3DS#1311]
Okay so something i think that could be cool to add to Rosalina is modules, Modules is some file which you put on your SD card and if Rosalina detects files in that directory it adds a menu called Modules inside of that menu it will have all of the modules which can be menus or features. For example you could have a brightness module, you put it inside of the modules folder and open the modules menu inside of Rosalina and then click Brightness and inside of that are options for you to chose from.
This would be useful because people could add features to Luma without needing to download, edit and build the source code and then have people download the firmware.

**Comment by Shadow322** [comment]
Brightness was killed off in like fw 9.4 that's why it's not in BootNTR anymore

**Comment by Dimensional** [comment]
I think he was just using brightness as an example to explain the use of dynamic modules. Sounds something akin to Linux Kernel Modules.

**Comment by ghost** [comment]
So kind of like things to add on to the luma menu? I like your idea though it may be really hard to code.

**Comment by TuxSH** [comment]
No; too difficult
