### ISSUE TITLE
[REQUEST] BPS support?

### ISSUE THREAD

**Issue by Kh4lsior** [LumaTeam/Luma3DS#1313]
Instead of downloading the [10.0.1 version of luma with BPS support](https://github.com/leoetlino/Luma3DS/releases) made by [leoetlino](https://github.com/leoetlino), couldn't you just add that string of code into the normal version of Luma?
It would make things much easier and make people able to patch their titles.

**Comment by FlameKat53** [comment]
I like this idea, and it'd make it so we could stay on official builds, too!

**Comment by markstahler** [comment]
Commenting to follow. Thanks for Luma3DS!

**Comment by TuxSH** [comment]
Merged.
