### ISSUE TITLE
3DS Luma Exception Error

### ISSUE THREAD

**Issue by ffff714** [LumaTeam/Luma3DS#1315]
**System model:**New 3DS

**SysNAND version (+emu/redNAND version if applicable):**11.10.0-43J SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**Boot9Strap

**Luma3DS version:**10.0.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
After I update 3DS from 11.9.0 to 11.10.0 by offline updater, some titles when launch will crash and report this.

![20190906202902](https://user-images.githubusercontent.com/54985869/64427973-1894bd80-d0e5-11e9-8a16-c6347aa1967b.png)

Sorry, this is my fault but if can, help me please!

**Steps to reproduce:**

1.Offline update from 11.9.0 to 11.10.0

2.Launch specific titles (e.g. Monster Hunter Stories) and that will crash before load

**Dump file:**

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/3583893/crash_dump_00000000.zip)

**Comment by Shadow322** [comment]
Update online

**Comment by ffff714** [comment]
> Update online

yea but the result it's same...and I do some may solve this problem methods (reinstall title and try ctrtransfer even format system) but that dosen't work too :(
