### ISSUE TITLE
Luigi Mansion

### ISSUE THREAD

**Issue by Sonicwillsave123** [LumaTeam/Luma3DS#1316]
Luma is working fine and other games are working fine, but today my copy of Luigi Mansion will not start up properly and just hangs after the Nintendo splash screen, with a black screen.  Has anyone else had this issue?  I have done several hard resets and it has made no difference.  Just to be clear, I am not talking about Luigi Mansion 2, I am talking about the GameCube port.

Thank you

**Comment by fincs** [comment]
Do you have a physical gamecart or a digital eShop purchase? If the latter, try checking your SD card for errors, swapping out for a different SD card and redownloading the game from the eShop.

**Comment by Sonicwillsave123** [comment]
eshop

**Comment by MiiJack** [comment]
Maybe it's because of the non matching Regions.
