### ISSUE TITLE
Battery Life Depleted in Sleep Mode when overclocking N3DS

### ISSUE THREAD

**Issue by wolfpacleader1986** [LumaTeam/Luma3DS#132]
I have my N3DS set to "Clock+L2" and I noticed that since then, my battery depletes very quickly, only getting about four hours on a charge, including sleep mode. So, my guess is that there needs to be something written in the code, a fix that corrects the Clock+L2 so that it turns off and goes back to normal in Sleep Mode.

**Comment by Shadow322** [comment]
No just use NTR CFW and turn it off and on when needed

**Comment by TuxSH** [comment]
What do you expect, you're raising the power consumption of your N3DS...

Just turn this option on only when needed.

**Comment by cheatfreak47** [comment]
I know this was closed, but I never actually experienced this sort of battery drain, I've never noticed even a slight difference actually.
