### ISSUE TITLE
Monster Hunter Generation crashes on start up Luma3DS v10

### ISSUE THREAD

**Issue by hoangtrung1999** [LumaTeam/Luma3DS#1322]
**System model:**
New 2DS LL
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
Sorry I'm newbie so I dont know where to find this.
[e.g. 11.6.0-39U SysNAND, 11.6.0-39J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
v10.0.1
[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: (Off )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
I downloaded the legit CIA from ziperto, it's installed successfully but when I start it, it just keep crashing. Here is the image I took when it starts up
![image](https://user-images.githubusercontent.com/12170169/65379011-8519da00-dceb-11e9-9493-b813a1396c54.png)

**Steps to reproduce:**

1.

2.

**Dump file:**

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/3639347/crash_dump_00000000.zip)

**Comment by oreo639** [comment]
> I downloaded the legit CIA from [REDACTED]

Please don't post piracy links here.

You aren't going to recieve help with a pirated game.
Can you see if you can reproduce this on an offically purchased copy of the game?

> Sorry I'm newbie so I dont know where to find this.

It's the system version (you check in system settings) of your sysnand or emunand if you are running it from an emunand.

**Comment by ghost** [comment]
This is on your end, and not a Luma issue.
