### ISSUE TITLE
Using game patch in Pokemon Ultra Sun game crashed

### ISSUE THREAD

**Issue by Dalk2ness** [LumaTeam/Luma3DS#1325]
I try to patching pokemon ultra sun and i have edited some little item in game but i only got this error
in Pokemon ultra sun via CIA install in my New 3ds

[Here this is my error](https://sv1.picz.in.th/images/2019/09/26/cZ4T8W.png)

**Comment by AuroraWright** [comment]
Not enough information

**Comment by Dalk2ness** [comment]
It seem can work with original version of game cant update patch ?
