### ISSUE TITLE
What is star(*) at Cheat list?

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1330]
![20191003_115122](https://user-images.githubusercontent.com/56101469/66095992-74fbd780-e5d4-11e9-9a09-891587392bf0.jpg)

Like this picture, what does the star(*) on the right side of the description mean?

This is the cheat code of Pokemon X, and its update data version is 1.5

**Comment by CatalyticArkun** [comment]
There is additional information with the cheat, press Y to display the usage description.

**Comment by AuditeMarlow** [comment]
I've got a bunch of those cheats but pressing Y does not provide me with extra information unfortunately. Was this feature scrapped or is this a new/recurring bug?

**Comment by hurda** [comment]
> I've got a bunch of those cheats but pressing Y does not provide me with extra information unfortunately. Was this feature scrapped or is this a new/recurring bug?

Cheats with * require a key to be activated, note the descriptions.
