### ISSUE TITLE
ARM9 Crashes on bootup

### ISSUE THREAD

**Issue by daemonspudguy** [LumaTeam/Luma3DS#1333]
**System model:**

New 3DS XL
**SysNAND version (+emu/redNAND version if applicable):**

11.10.43-U

**Entrypoint (How/what you're using to boot Luma3DS):**

Sighax

**Luma3DS version:**

10.0.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (off)

Splash duration: (3)

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Every time I boot, I get an ARM9 crash

**Steps to reproduce:**

1.Boot.

**Dump file:**
[crash_dump_00000006.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/3764997/crash_dump_00000006.dmp.zip)

**Comment by TuxSH** [comment]
Crash dump not parseable
