### ISSUE TITLE
Persona Q2 (Cartridge) crashes on boot.

### ISSUE THREAD

**Issue by SMNFXCN** [LumaTeam/Luma3DS#1336]
**System model:**
New 3DS
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.6.0-39U SysNAND, 11.6.0-39J EmuNAND]
11.10.0-43U SysNAND
**Entrypoint (How/what you're using to boot Luma3DS):**
Sighax
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
10.0.1
[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**
SysNAND
Default EmuNAND: ( )

Screen brightness: (1)

Splash: (Before)

Splash duration: (1)

PIN lock: (Off)

New 3DS CPU: (Clock)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Launching Persona Q2 (on USA cartridge, not sure if the issue exists on digital copy, or any other regions) causes the 3DS to have a prefetch abort with the process being loader. It crashes before the 3DS logo appears.
For some reason, reverting back to the previous version (9.x.x) does not have this issue.

**Steps to reproduce:**

1. Launch Persona Q2 on Luma3DS v10.x.x

**Dump file:**

[crash_dump_00000078.zip](https://github.com/AuroraWright/Luma3DS/files/3780983/crash_dump_00000078.zip)

**Comment by TuxSH** [comment]
People say they can't repro with latest commit, closing.
