### ISSUE TITLE
Time wrong by one hour after using Rosalina NTP

### ISSUE THREAD

**Issue by V10lator** [LumaTeam/Luma3DS#1338]
**System model:** New 2DS XL
**SysNAND version (+emu/redNAND version if applicable):** 11.11.0-43E
**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap
**Luma3DS version:** 10.0.1 stable
**Luma3DS configuration/options:**
Screen brightness: 4
Splash: Off
Splash duration: 1
PIN lock: Off
Enable loading external FIRMs and modules: ( )
Enable game patching: (x)
Show NAND or user string in System Settings: (x)
Show GBA boot screen in patched AGB_FIRM: (x)
Set developer UNITINFO: ( )
Disable ARM11 exception handlers: ( )

**Explanation of the issue:**
If it's i.e. 12 o'clock Rosaline will set the time to 11 o'clock.
Here's a video of it in action: https://public.nbg01.v10lator.de/Rosalina-NTP.mp4
Timezone is setted correctly in the settings.

**Steps to reproduce:**
1. Use Rosalina NTP to set the time
2. Reboot

**Comment by TuxSH** [comment]
Can't repro now. Maybe it's DST. Closing for now

**Comment by Kyhze** [comment]
This issue is still happening on 13.4. 

It is likely due to DST not being accounted for, which should be an easy fix to implement.

**Comment by PabloMK7** [comment]
You have to manually account for DST when confirming the time.

**Comment by Kyhze** [comment]
But why? DST is an universally recurring factor.  
It could, and should be taken into account automatically.  

For countries not taking part in DST, we can always have an option to automatically account for it, or not.  

Maybe some kind of similar mechanism to `tzdata` used in some Linux distributions, where users can pick their timezones, and that will automatically account for DST, when/if applicable.

**Comment by PabloMK7** [comment]
I think having more code, taking more space, for something that can easily be accounted manually by the user is unnecessary.

**Comment by impeeza** [comment]
> But why? DST is an universally recurring factor. It could, and should be taken into account automatically.
> 
> For countries not taking part in DST, we can always have an option to automatically account for it, or not.
> 
> Maybe some kind of similar mechanism to `tzdata` used in some Linux distributions, where users can pick their timezones, and that will automatically account for DST, when/if applicable.

NO! DST IS NOT A UNIVERSALLY recurring factor, there are countries which have different settings on different times of year, some countries have a setting one year AND ANOTHER DIFFERENT THE NEXT YEAR. other DO NOT HAVE IT AT ALL.

United States of America IS NOT THE CENTER OF UNIVERSE and by the way on measurements and standars yours are COMPLETELY DIFFERENT FROM THE REST OF THE WORLD.

**Comment by Kyhze** [comment]
@impeeza Learn to read before commenting.
