### ISSUE TITLE
If TWL_FIRM/AGB_FIRM/SAFE_FIRM doesn't exist and a DS/DSi/GBA software or Recovery Mode is launched, you receive an error about being Unable to mount *CTRNAND*.

### ISSUE THREAD

**Issue by Validusername16** [LumaTeam/Luma3DS#1339]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.12.0-44U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

Stable 10.0.1 (on Stable 9.1 it just powers off the console)

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
This is mostly just a minor text issue, but it is worth noting. Luma3DS will spit out about being unable to mount CTRNAND or load the CTRNAND firm, regardless of whether or not CTRNAND/NATIVE is the firm having issues.

**Steps to reproduce:**

1. Delete TWL_FIRM, AGB_FIRM, or SAFE_FIRM using your method(s) of choice

2. Open either any DS/DSi software, a GBA Virtual Console game, or boot to Recovery/Safe Mode, depending on what you deleted.

3. You would expect an error screen about how it could not load the firm in question, but instead you'll end up with an error about the CTRNAND firm.

**Dump file:**

N/A

**Comment by Validusername16** [comment]
i pushed enter early.

**Comment by Validusername16** [comment]
okay attempt 2

**Comment by TuxSH** [comment]
The errors also mentions **or load the CTRNAND FIRM.". These firms are loaded from CTRNAND, there's no issue.
