### ISSUE TITLE
luma 5.5

### ISSUE THREAD

**Issue by hexyo** [LumaTeam/Luma3DS#134]
im on Part 3 github guide now. When i do 16 (Press Start to boot RedNAND) there's just some colors on screen, and after this console restart and open Homebrew Launcher, not the default console menu.
tried to rerun plaisysupdater and deleting config file of luma3ds, doesnt helped.
what i should do?
Plailect is redirected to u "This is something to do with luma, not my instructions. Make sure you have done everything right then ask @AuroraWright"

**Comment by urherenow** [comment]
You should ask on a forum. This is NOT a forum. @AuroraWright hangs out at gbatemp.
