### ISSUE TITLE
RTC fixing

### ISSUE THREAD

**Issue by Real96** [LumaTeam/Luma3DS#1340]
Can you add an option to open a game with a fixed RTC? this would be great for games Rng

**Comment by Multimegamander** [comment]
wdym? you can just open a game using the home menu

**Comment by Multimegamander** [comment]
or do you mean set a specific RTC, because that's not possible with per game patching, you'll need to manually change your RTC with GodMode9

**Comment by Real96** [comment]
I mean set a specific RTC for the game and fix it. As Citra rtc setting does, you set the date and it won't advance

**Comment by Multimegamander** [comment]
I don't think that's possible on hardware

**Comment by Real96** [comment]
Neither to freeze it just for game boot?

**Comment by TuxSH** [comment]
Nope
