### ISSUE TITLE
It's  possible launch on startup a custom menu?

### ISSUE THREAD

**Issue by GabrielCatDev** [LumaTeam/Luma3DS#1341]
I wonder to develop a menu style switch to launch games,apps and config 3ds but i don't know if it's possible...

The most important is the home menu replace it to the custom...i think it's possible because since v8 can L+Select+(down?) Then home button can be override with the new custom menu no?

[Sorry my bad English]

**Comment by Shadow322** [comment]
This is not a Luma3DS issue take this to gbatemp forums

**Comment by GabrielCatDev** [comment]
:( but Luma is the software necessary to init program on startup and edit home button...no?

**Comment by Multimegamander** [comment]
It's possible, other CFWs have a patch to load a different tid than home menu, the Luma devs said they don't want to add it tho

**Comment by Multimegamander** [comment]
https://github.com/Multimegamander/ProjectAtlas

Me, RocketRobz (creator of TWiLightMenu++) and TheGuy3DS are making a 3DS Home Reimplementation.

**Comment by profi200** [comment]
What the hell is MultiCTR?

**Comment by Multimegamander** [comment]
MultiCTR is a new CFW we're making in C++ that takes features from Corbenik, Luma, and Cakes and adds some unique features.

**Comment by RS55** [comment]
@Multimegamander I hope that, if it becomes a reality, you will do everything Luma3DS left out of annoyance or disinterest (and are logically applicable but have not done so, such as letting you select which screen to take screenshot and assign a combination of buttons or a button to take screenshot).

**Comment by RS55** [comment]
being frank, I hope that, if it becomes a reality, you will do everything Luma3DS left out (and that are logically applicable but have not done so, such as letting you select which screen to take screenshot and assign a combination of buttons or a button to take screenshot ...).
