### ISSUE TITLE
OK I understand now.

### ISSUE THREAD

**Issue by Nashismo** [LumaTeam/Luma3DS#1343]

**Comment by Multimegamander** [comment]
try fixing it through the EShop

**Comment by Nashismo** [comment]
> 
> 
> try fixing it through the EShop

What do you mean? Thank you.

**Comment by RocketRobz** [comment]
> What do you mean? Thank you.

Redownload in the Downloads/Purchases list.

**Comment by Nashismo** [comment]
> 
> 
> > What do you mean? Thank you.
> 
> Redownload in the Downloads/Purchases list.

Oh no you see, this is a CIA that I downloaded from the net, it is an official version, not an injected ROM. But I did NOT downloaded the game from my own Eshop.

Maybe this is a problem because this game has a wireless link feature? Maybe this game is simply impossible to install unless you purchase the game as intended, if that is the case, then I guess I'll buy it. I just want to know what the problem is.

**Comment by fincs** [comment]
> this is a CIA that I downloaded from the net

Or in other words, it's a pirated copy which might or might not be corrupted. Piracy is not supported.

**Comment by Nashismo** [comment]
Piracy is not supported, said the people who hacked the 3DS wide open, mostly for piracy... hahahhhaha fine.

**Comment by fincs** [comment]
We did not hack the 3DS wide open for piracy. We hacked it for homebrew. Pirates took our work and ran away with it.

**Comment by Nashismo** [comment]
Ok, it is fine, I was ignorant of this. I am sorry if I was such an idiot. Thank you for everything.
