### ISSUE TITLE
Can't Download a File on Luma3DS

### ISSUE THREAD

**Issue by light8227** [LumaTeam/Luma3DS#1345]
I was looking in the Luma3DS files, but can only find boot.firm and boot.3dsx in the file. I downloaded the latest version and all 3 assets and it wasn't in any of them. 
If anyone could help me find where to download boot.nds, it would be of great help.

**Comment by oreo639** [comment]
> If anyone could help me find where to download boot.nds

What are you doing that would require a boot.nds file?

**Comment by light8227** [comment]
I'm trying to install Boot9strap

**Comment by oreo639** [comment]
> Copy boot.nds (B9STool) to the root of your SD card

https://3ds.hacks.guide says where to find it.

**Comment by light8227** [comment]
I've been using that guide. When I download the file, it's just not there. 
![Capture](https://user-images.githubusercontent.com/58644191/70382739-3c56e200-1926-11ea-9676-f617e14e12f6.PNG)

**Comment by oreo639** [comment]
boot.nds is from a seperate application from luma, and isn't shipped with luma.

**Comment by light8227** [comment]
Oh, I see now. Just reread it. Thanks.

**Comment by oreo639** [comment]
It would probably be a good idea to close the issue, assuming it is resolved.
