### ISSUE TITLE
Game crashes with ErrDisp error

### ISSUE THREAD

**Issue by spnshguy** [LumaTeam/Luma3DS#1346]
System model: New 3DS XL
Entrypoint (How/what you're using to boot Luma3DS): Boot9Strap
Luma3DS version: 10.0.1 stable

While playing Luigi's Mansion, the game always crashes while playing the game (opening a door to be more specific).

Let me know if more details is needed

```
An error occurred (ErrDisp)
Error type: generic
Process ID: 67115840
Address: 0x00000d0a
Error Code: 0x000000d0
Press any button to reboot.
```

**Comment by Multimegamander** [comment]
Open EShop, and redownload in the Downloads/Purchases list.

If it's a pirated game, we won't help you.

**Comment by spnshguy** [comment]
I tried that but it still crashes :/

**Comment by oreo639** [comment]
Try the latest Luma hourly. Also, it would be helpfull if you would share your /luma/errdisp.txt (the latest release doesn't display the correct information)

**Comment by spnshguy** [comment]
Here is the error log that you asked for

```An error occurred (ErrDisp)
Error type: generic
Process ID: 39
Process Name: LM3DS
Address: 0x0010f9d8
Error Code: 0xd900458b
Press any button to reboot.```

here is also the errdisp.txt

```Error type:       generic

Process ID:       39
Process name:     LM3DS
Process title ID: 0x0004000000055f00

Address:          0x0010f9d8
Error code:       0xd900458b```

**Comment by spnshguy** [comment]
@Oreo639 let me know if you need any more info

**Comment by TurdPooCharger** [comment]
https://github.com/hax0kartik/luma-hourlies/releases

**Comment by DMSalesman** [comment]
I didn't grab a log, but a similar crash out of thin air occurred to me with Fire Emblem Awakening (EUR), on an Old3DS with the latest Luma version.

**Comment by TuxSH** [comment]
Latest commits/oreo's PR should have fixed it. The issue with "0xd900458b" comes from title or savedata corruption

**Comment by jephter9** [comment]
Please how do we solve the savedata or title corruption
