### ISSUE TITLE
Boot NTR CFW SELECTOR app is not working

### ISSUE THREAD

**Issue by GalaxyGold** [LumaTeam/Luma3DS#1347]
https://github.com/44670/BootNTR/releases
This link is NTR CFW downlad link. 

My 3ds is boot9strap CFW. 
recently, Nintendo release 11.13 ver update. 
necessarily, I updated my 3ds today. 'cause I can't using friend add function. 
Everyday I always using NTR CFW app. 
but after the update, NTR CFW not working. :( 
NTR CFW app said 'Loading 3.6...
Load failed !
#firmware unknown
#Delected firm :2.56
Press any key to reboot'

Please help. 
What can I do? 
I want to use NTR CFW app.

**Comment by oreo639** [comment]
That is BootNTR. Not BootNTRSelector.
This is probably what you are thinking of:
https://github.com/Nanquitas/BootNTR

**Comment by GalaxyGold** [comment]
I solved myself. 
I installed 'BootNTRSelector-PabloMK7-Banner.cia'. 
link: https://github.com/Nanquitas/BootNTR/releases

and I clicked 3.6. 

Thank you anyway 'Oreo639'.

**Comment by miiforlong** [comment]
it doesn't work in 2023 .......................
