### ISSUE TITLE
Screenshot is not working

### ISSUE THREAD

**Issue by Doux91** [LumaTeam/Luma3DS#1352]
O3ds
Luma 10.0.1
boot9strap 1.3
Please fix this issue, the screenshot its not working on rosalina menu

**Comment by oreo639** [comment]
I cannot reproduce this. (also did you check `/luma/screenshots`?)
It would be helpful if you could give more info so someone can try to reproduce it.

**Comment by Shadow322** [comment]
works fine here

![mrg_2019-12-23_19-59-39 337](https://user-images.githubusercontent.com/15938645/71389171-ec804800-25c0-11ea-8345-7917facd19e6.jpg)

**Comment by Doux91** [comment]
> I cannot reproduce this. (also did you check `/luma/screenshots`?)
> It would be helpful if you could give more info so someone can try to reproduce it.
Yes I Opened the folder and its empty, when I use the option screenshot (slow) of rosalina it freezes for seconds and it says Operation succeeded but it does not do anything

**Comment by Doux91** [comment]
> I cannot reproduce this. (also did you check `/luma/screenshots`?)
> It would be helpful if you could give more info so someone can try to reproduce it.

Yes I Opened the folder and its empty, when I use the option Take screenshot (slow) of rosalina it freezes for seconds and it says Operation succeeded but it does not do anything

**Comment by Doux91** [comment]
> works fine here
> 
> ![mrg_2019-12-23_19-59-39 337](https://user-images.githubusercontent.com/15938645/71389171-ec804800-25c0-11ea-8345-7917facd19e6.jpg)

Not for me, I mean rosalina screenshot, not 3ds system screenshot

**Comment by Shadow322** [comment]
That is a Rosalina screenshot

**Comment by TurdPooCharger** [comment]
You're probably using CTRNAND Luma3DS.
- **[1:] SYSNAND CTRNAND/rw/luma/screenshots**

**Comment by Doux91** [comment]
> You're probably using CTRNAND Luma3DS.
> 
> * **[1:] SYSNAND CTRNAND/rw/luma/screenshots**

I think you are right but why is rosalina saving the screenshots in the 3ds?
anyway thanks for help me, I must say the issue is fixed but I would like to have the screenshot on SD or at least change where it saves the screenshot

**Comment by Shadow322** [comment]
> > You're probably using CTRNAND Luma3DS.
> > 
> > * **[1:] SYSNAND CTRNAND/rw/luma/screenshots**
> 
> I think you are right but why is rosalina saving the screenshots in the 3ds?
> anyway thanks for help me, I must say the issue is fixed but I would like to have the screenshot on SD or at least change where it saves the screenshot

Because the Luma3DS devs refuse to fix it

**Comment by Doux91** [comment]
> Because the Luma3DS devs refuse to fix it

I copied all the files from ctrnand to the screenshot of sd card, but this is a big issue

**Comment by TurdPooCharger** [comment]
There's nothing wrong with luma. It's your setup. It means your 3DS isn't using Luma3DS found on the SD card.
- **sdmc:/**`boot.firm`
