### ISSUE TITLE
[Feature request] Region emulation for local multiplayer / download play

### ISSUE THREAD

**Issue by elmimmo** [LumaTeam/Luma3DS#1354]
Local multiplayer / download play seems to remains region locked. It'd be nice to be able to mix consoles from different regions per game without having to [hard-change the region of the whole console](https://3ds.hacks.guide/region-changing.html), with all it entails.

#240 was about this issue, but was closed until someone learned “more information about what region-free local multiplayer entails”.

PS: Before anyone suggests [Luma Locale Switcher](https://github.com/ericjwg/LumaLocaleSwitcher/releases) note that it does not work at all around the region lock of Local multiplayer / download play.

**Comment by brunocar** [comment]
exactly, games like mario kart 7 have download play that makes it unusable between consoles of different regions.

**Comment by elmimmo** [comment]
Another example is _The Legend of Zelda: Tri Force Heroes._ It has both local multiplayer (with each console having a copy of the game) and download play (with only one console having the game).

A European console hosting either local multiplayer or download play sessions will remain invisible to a nearby Japanese console, even when the latter has Luma3DS’ “Enable game patching” checked in order to enable out-of-region games.

Similarly, the Japanese console hosting a local multiplayer session of the European game, with its region and language set to the same as the European console’s with Luma Locale Switcher, will remain invisible to the European console, and will outright crash/freeze when attempting to host a download play session, displaying this error message in the bottom screen:

~~~
An error occurred (ErrDisp)

Error type: generic

Process ID: 67115840

Address: 0x00000cea
Error code: 0x000000ce

Press any button to reboot.
~~~

**Comment by profi200** [comment]
This is game dependent and there is a chance this will not work at all with some games.
