### ISSUE TITLE
ErrDisp Type: Generic (Only when Wireless connection is on, the console crashes)

### ISSUE THREAD

**Issue by H4un7** [LumaTeam/Luma3DS#1357]
Error type:       generic

Process ID:       25
Process name:     nwm
Process title ID: 0x0004013000002d02

Address:          0x00109466
Error code:       0xf9606c02

**Comment by ghost** [comment]
Your console's wireless module is damaged or unseated, or nwm sysmodule is corrupted (most likely the former.)

**Comment by H4un7** [comment]
> Your console's wireless module is damaged or unseated, or nwm sysmodule is corrupted (most likely the former.)

So... How can I fix that? And when did it got corrupted anyways? It was working fine a few months ago.

**Comment by TuxSH** [comment]
Will have a look into it

**Comment by TuxSH** [comment]
Latest commits/oreo's PR should have fixed it.

**Comment by Hrozhek** [comment]
I have the same problem. After installing module from old 3ds xl to old 3ds problem dissapeared. So change of wifi module may be possible workaround (but start with updating software and after that try to clean contacts before replacement). Fortunately there are a lot of available lots on ali.
