### ISSUE TITLE
[feature-request] have a volume control system implemented into the luma menu

### ISSUE THREAD

**Issue by scary-tempest** [LumaTeam/Luma3DS#1358]
i have a 2ds xl. i dropped it about a year ago and the volume rocker split in half, so i cant controll the volume, its always off. the developers should make a feature where you can control the volume if the rocker stays still.

**Comment by profi200** [comment]
This may not be possible because the volume is controlled by the MCU and to my knowledge there is no way to disable automatic volume control.
