### ISSUE TITLE
[Feature/Request] Rosalina Menu button combination (L + Down + Select) change?

### ISSUE THREAD

**Issue by OwOItsDanka** [LumaTeam/Luma3DS#1360]
Hey, I'm new here and really just created an account to ask something.
I was in the "finalizing setup" section III of the Homebrew Launcher guide, and I'm having trouble opening the Rosalina menu, because my L button on the 3DS doesn't work. I was wondering if there is anyway to use another button except L? 
Thank you for all your hard work!

**Comment by RaderRMT** [comment]
Hey, in my knowledge, the only way to change the combo to access the Rosalina menu, is by changing it in the Rosalina menu under "Miscellaneous options...". If your L button does not work, you will not be able to change the combo or access the menu.

**Comment by OwOItsDanka** [comment]
Well, that's a shame :/ But still, thanks for answering!

**Comment by profi200** [comment]
Replace the config.bin in /luma with this (rename it to .bin first). This has the key combo set to R+Down+Start. Then set the combo to whatever you like.

Note: If this doesn't download right click it and use "Save as"
[config.txt](https://github.com/AuroraWright/Luma3DS/files/4082545/config.txt)

**Comment by OwOItsDanka** [comment]
I really thought I'd hit a dead end sooo, damn, thank you so much!
