### ISSUE TITLE
Arm11 processor exception on Nintendo 3DS 

### ISSUE THREAD

**Issue by xHula2016** [LumaTeam/Luma3DS#1362]
System model:

Old 3DS XL

SysNAND version (+emu/redNAND version if applicable):

Thanks in advance!

9.2 SysNAND, 11.9.0-42E EmuNAND

Entrypoint (How/what you're using to boot Luma3DS):

Boot9Strap

Luma3DS version: 10.0.1

Luma3DS configuration/options:

Default EmuNAND: ( )

Screen brightness: (4 )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

Explanation of the issue: Sometimes, randomly, mt 3DS will crash. It normally occurs when opening apps or games and it happens the most when I have wireless communication on. The process causing this is "boss"

Steps to reproduce:
I don't really know, it happens randomly.

Dump file:
[crash_dump_00000003.zip](https://github.com/AuroraWright/Luma3DS/files/4082935/crash_dump_00000003.zip)

**Comment by TuxSH** [comment]
It's just some minor change ninty made where stock ignores it but luma crashes. Ignore it.
