### ISSUE TITLE
old 3ds crashes after close some gameboy backup installed

### ISSUE THREAD

**Issue by yggdrassilbcn** [LumaTeam/Luma3DS#1365]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.13.0-45E SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap/Sighax]

**Luma3DS version:**

[Luma3DS 10.0.1]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( X)

Show NAND or user string in System Settings: (X )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: (X )

--

**Explanation of the issue:**
After update my old3ds to 11.13.0-45E, and luma3ds 10.0.1, i have some issues, like errors exceptions, when I close some gameboy backup and try to open for some 3ds backups, or settings.

hope someone can helps. thanks for all, and sorry about my english. Thanks

**Steps to reproduce:**

1. open gameboy backup installed from cia, close the app, open 3ds backup like animal crossing, crash
![IMG_20200130_080151](https://user-images.githubusercontent.com/40324659/73428458-831af400-4339-11ea-9ebe-9233d8ffe931.jpg)

2. open gameboy backup installed from cia, enter settings console, close settings, crashes
![IMG_20200130_080317](https://user-images.githubusercontent.com/40324659/73428520-b067a200-4339-11ea-9925-7288064e1937.jpg)

**Dump file:**

[dumps luma.zip](https://github.com/AuroraWright/Luma3DS/files/4132660/dumps.luma.zip)

**Comment by TuxSH** [comment]
We don't support piracy
