### ISSUE TITLE
ARM11 crash

### ISSUE THREAD

**Issue by Stickman1478963** [LumaTeam/Luma3DS#1366]
**System model:**
New 2ds

**SysNAND version (+emu/redNAND version if applicable):**

11.5.0-38U

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

10.0.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
I got this problem where it doesn't let me open the download mode or any game

**Steps to reproduce:**

**Dump file:**
[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/4137564/crash_dump_00000000.zip)

**Comment by TuxSH** [comment]
Not enough info for me to resolve.
