### ISSUE TITLE
Miitopia crashes when trying to rewatch cutscene 47

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1367]
**System model:New 3DS XL **

**SysNAND version (+emu/redNAND version if applicable): 11.13.0-45U**

**Entrypoint (How/what you're using to boot Luma3DS): Boot9Strap**

**Luma3DS version: v10.0.1 stable**

Luma3DS configuration/options:

Default EmuNAND: ( )

Screen brightness: (1)

Splash: (Before)

Splash duration: (1)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (X)

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Everytime I try to rewatch cutscene 47 in Miitopia, the game crashes. What's weird was that the cutscene was watchable normally as the story progressed, and this happened to no other cutscenes that are rewatchable (or at least from the one's that I tried). 
I tried to reinstall my backup and it still crashed. It's not even a problem with the savefile, since restoring a save from a previous playthrough I had and attempting to watch this cutscene STILL crashed. I even went as far as to try an older luma build (9.1 specifically) to see if it was a v10.0.1 problem, but, like you would of guessed, the game crashed.
At this point I have a feeling that this may be a luma issue, so that's why I'm posting this here. I put my crash dump here, along with my save so you can easily test the problem.

**Steps to reproduce:**
(I added my save to the issue for convenience in reproducing)

1. Open up the game and press start.

2. Go to Menu => Records => Highlights

3. Scroll down to Cutscene 47 and press view.

4. The game _should_ crash.

**Dump file:**

[crash_dump_00000002.zip](https://github.com/AuroraWright/Luma3DS/files/4150917/crash_dump_00000002.zip)
[save.zip](https://github.com/AuroraWright/Luma3DS/files/4150924/save.zip)

**Comment by TuxSH** [comment]
null deref, I don't see why it would be Luma-related

> I tried to reinstall my backup and it still crashed.

We don't support piracy anyway
