### ISSUE TITLE
Ignore ARM11 exception handlers for specific TitleID ?

### ISSUE THREAD

**Issue by TheShadowRunner** [LumaTeam/Luma3DS#1368]
Hi,
I wish to let the ARM11 exception handlers active but blacklist a certain TitleID (so that the handler ignores faults for that TitleID alone).
Is this possible somehow?
If not, could it be implemented, maybe via a blacklist text file containing that TitleID in the /luma/ folder ?
Thank you.

**Comment by oreo639** [comment]
What is crashing and what is the crash?

**Comment by TheShadowRunner** [comment]
Hmm does it matter? I'm just wondering if it can be done. For an app that won't ever be updated and that triggers a benign error. With "ARM11 exception handlers" enables it blackscreens and forces shutdown. With it disabled it works perfectly fine.
So I just wish to blacklist it.
Thanks for considering.

**Comment by piratesephiroth** [comment]
Just disable it altogether then. There's no need for it to be enabled all the time.

**Comment by TheShadowRunner** [comment]
Hmm I read it's not recommended at all, that it can prevent data corruption when it "legitimately" detects a serious fault (contrary to my scenario), hence why I'd rather keep it enabled + blacklist.

**Comment by piratesephiroth** [comment]
In my experience, arm11 exceptions often are minor issues that the 3DS's system doesn't even care about.
The Luma black screen might freeze a game at a very unexpected moment, forcing you to reboot and making you lose progress as well.

**Comment by TheShadowRunner** [comment]
Thanks for these precisions. If such a blacklist isn't possible/ implemented guess it's what I'll do anyway.
I just wish to hear what the developer thinks about it.
Thanks.

**Comment by TuxSH** [comment]
https://github.com/AuroraWright/Luma3DS/blob/master/k11_extension/source/fatalExceptionHandlersMain.c#L57 , KCodeSet structure has a titleId member
