### ISSUE TITLE
Crashing upon pressing Select/Start when Pokemon Bank is running.

### ISSUE THREAD

**Issue by PP-theSLAYER** [LumaTeam/Luma3DS#1369]
**System model:**
2DS

**SysNAND version (+emu/redNAND version if applicable):**
11.13.0-45J

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap

**Luma3DS version:**
v10.0.1

**Luma3DS configuration/options:**
No Emunand.

Screen brightness: ( 4)
Splash: ( off)
Splash duration: ( 1)
PIN lock: ( off)
All options at the bottom parts are unchecked.
--

**Explanation of the issue:**
Need to press Start or Select button in order to change the pointer green, in order to perform mass transfer.
However once it turns green, the 3DS crashes.

**Steps to reproduce:**
1. Load up Pokémon Bank
2. Go into cart
3. Press Select or Start 2 times, to cycle to green.

edit: It appears turning the pointer to green is the issue.
The 2DS doesn't crash when the pointer is blue.

**Dump file:**
(error screen doesn't tell me where to dump file is)

**Error screen
Error type: generic
Process ID: 67115840
Address: 0x00000d1a
Error code: 0x000000d1

**Comment by TuxSH** [comment]
This should be fixed now
