### ISSUE TITLE
Keybinding - bind Decrypt9 to "A" on boot

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#137]
I want to bind the key "A" to Decrypt9WIP.bin
but I cannot find out how to do it. Rename to `a_Decrypt9.bin` does not work.
_But if I name it `x_Decrypt9.bin` it works fine on key `X`!_ How to do it for key `A` ?

**Comment by ihaveamac** [comment]
hold L+A

**Comment by ghost** [comment]
But how can I set it only to "A"? Is there any official documentation about keybinding for Luma3DS or do we need to create this kind of documentation?

**Comment by ihaveamac** [comment]
you can't since Luma3DS uses A normally. applies to select and R too (maybe B, can't remember)

**Comment by JHGitty** [comment]
Okay, what does Luma3DS do with the A key? Can I do something with it? I think there should be any good documentation - no documentation about this yet, right?

**Comment by ghost** [comment]
Thanks. I have found the documentation part: https://github.com/AuroraWright/Luma3DS/wiki/Other-features-and-notes#payload-chainloading
