### ISSUE TITLE
[Feature Request] Backlight Brightness Option

### ISSUE THREAD

**Issue by ElDanteDelAnte** [LumaTeam/Luma3DS#1372]
It's a bit inconvenient to have to suspend game to adjust screen brightness, plus the high contrast of the Rosalina menu would let me see what I'm doing better as I adjust from indoor to outdoor brightness.

(I'm seeing similar issues listed, but between broken links and closed/outdated threads, I can't tell what the status on this feature is anymore.)

**Comment by Shadow322** [comment]
That was killed off via 9.x something as BootNTR has this feature if u downgrade it will show up again via BootNTR

**Comment by ElDanteDelAnte** [comment]
![image](https://user-images.githubusercontent.com/11401222/74502741-5a4f3e80-4ea3-11ea-8a69-3703922a8cff.png)
I'm getting conflicting information and I'm confused (I am very new to this, my apologies).
I should clarify that I'm using Rosalina and not BootNTR, and that this is a request for Rosalina. I was linked to this repo when I asked where to suggest Rosalina features.
