### ISSUE TITLE
Luma crash when opening Super Mario Maker JPN manual

### ISSUE THREAD

**Issue by TheShadowRunner** [LumaTeam/Luma3DS#1373]
Hey all,
I'd like to report a bug:
When attempting to open Super Mario Maker's Manual, Luma crashes with the following message on the bottom screen:
------
An error occured (ErrDisp)
Error type: generic
Process ID: 67115840
Adress: 0x000005ea
Error code: 0x0000005e
Press any button to reboot.
-----
It's the only game for which opening the manual crashes for me.
I tried to reinstall it multiple times, dump from my own cart 'Super Mario Maker" JPN version, no change, the crash always occurs when attempting to open the manual (and the error on the bottom screen always the same).

Is this a known issue?
Thanks for any help.

Edit: My system is JPN N3DS. It wasn't region changed or anything.
Edit2: in errdisp.txt I have "error type: card removed. The card was removed".
I'm on latest 3DS fw and Luma is latest, launched from b9s.

**Comment by oreo639** [comment]
Can you try reproducing this on the latest Luma hourly?

**Comment by TheShadowRunner** [comment]
> Can you try reproducing this on the latest Luma hourly?

Sure, where may that be downloaded? ^^

**Comment by TheShadowRunner** [comment]
Ok, i tested "234-luma3ds-dfd50d9: Merge pull request #9 from Margen67/memes" and the crash still occurs, but this time I have the ErrDisp message as description directly:
![_20200217_021120](https://user-images.githubusercontent.com/1895340/74616993-2c7c2b00-512b-11ea-9d6f-b2369339a410.JPG)
Thanks for your help.
Anything else I can try, let me know.

**Comment by TheShadowRunner** [comment]
Figured it out, corrupted update !
I had no idea updates could affect manuals..
What's strange is only the update to the manual was corrupted, the game patch ver. was displayed on title screen and everything seemed fine.
Anyway, mystery solved :)
