### ISSUE TITLE
Req: Remap ZL / ZR to L / R in Home menu only

### ISSUE THREAD

**Issue by TheShadowRunner** [LumaTeam/Luma3DS#1374]
I'm not sure if this is Luma territory.. 
I'd like to request a feature to remap buttons "ZL and ZR" to "L and R", but within the Home menu only.
Is that technically possible ?

**Comment by TuxSH** [comment]
That's a bit too complicated

- remapping ZL/ZR would imply reworking the InputRedirection codebase
- detecting whether HM is running on the foreground is also bothersome
