### ISSUE TITLE
Cheats on Pokémon Games are really unstable

### ISSUE THREAD

**Issue by felifluid** [LumaTeam/Luma3DS#1376]
Downloading Cheatcodes from Checkpoint and using them with the Rosalina menu are really unstable. I used only one code at a time and almost always the game just freeues entirely.

I don't know if that's only an issue with the newest luma version or if it was like this before.

Tested it with most Codes from Pokémon Y, Moon, and Alpha Saphire. (Yes I was on the right game version). And from researching I don't think the cheat codes are broken.

**Comment by ariscop** [comment]
Having the same trouble, it seems that memory gets remapped with no permissions for some reason, for example 080B5824 from the pokemon y walk through walls code

Using https://github.com/mikewii/Luma3DS/commit/cbc681e1a5e640981a22d5750028b2d268437772 to view mappings shows this, and changing it back to rw- from --- fixes the code

**Comment by ariscop** [comment]
Can confirm the same codes work with an ntr plugin, far as i can tell those plugins run on the arm11 where as rosalina is on the arm9

**Comment by fincs** [comment]
> rosalina is on the arm9

This is false. Rosalina is an ARM11 custom system module.

**Comment by Immersion95** [comment]
Yes I can confirm this behavior. The only solution for now is to use Luma3DS 9.1

**Comment by TuxSH** [comment]
what about now?

**Comment by Theone5000** [comment]
I can confirm this. Installed the **v10.1.3** version last night and various cheats I used let the Pokemon games freeze. Tested it with **Pokemon X** ID: **0004000000055D00** Version: 1.0/1.5 (It does not matter what version you use)

So what kind of codes freeze the game:
- 30/60 FPS
- No outlines
- Max money
- Use PC anywhere
etc. etc.

Most of these codes just work fine via Rosalina on **v9.1**. What I do like however in the new version is that **some** of the v1.0 and v1.5 codes work together so that's a huge plus! :) The downside is that you can't use them at all so why bother. Is there a bypass or fix for this?

EDIT: Tried various codes. All of the codes freeze or crashes the game. 
Sources:
https://github.com/JourneyOver/CTRPF-AR-CHEAT-CODES/blob/master/Cheats/Pok%C3%A9mon%20X%20(GLO)/0004000000055D00.txt
https://gbatemp.net/threads/gateway-cheats.402900/

**Comment by AverageComet250** [comment]
I personally find that it varies by game and installation method. on my alpha sapphire digital copy (e-store download) it crashes a lot. on all of the games that I installed via FBI there are less crashes(e.g. omega ruby, ultra moon and all of my vc games). On my Ultra moon copy I get VERY few crashes.

**Comment by git-you-cat** [comment]
I agree with @AverageComet250 that somehow the installation method seems to matter. My cartridge of ultra sun crashes less than FBI installed .cia (personally made from my cartridges) install of Y.

Regardless the Pokemon cheats are incredibly unstable across X/Y USUM ORAS. I would be willing to offer crash logs if any effort would go into fixing this.

**Comment by CatsLover2006** [comment]
o3DS or n3DS? I do believe that it's possible the o3DS gets very close to filling its RAM during gameplay.

**Comment by AverageComet250** [comment]
I used to play n3ds @CatsLover2006 but that was before I lost my ds because I moved house and put it somewhere.

**Comment by NE1W01F** [comment]
i have a n3DS and can say the problem is still there. i tested it on pokemon X and UM

**Comment by eco9898** [comment]
I'm running the as of now latest version of checkpoint and luma on my 3ds and the cheats all cause the system to crash. Does anyone know of an alternative way to use cheats on Luma specifically for pokemon X

**Comment by NewSammyChan** [comment]
Using a New 3DS and finding crashing on a Pokémon X 

no matter if it’s an all shiny code, instant egg or any other code. Crashes about 10 seconds in

**Comment by Shadow322** [comment]
> Using a New 3DS and finding crashing on a Pokémon X
> 
> no matter if it’s an all shiny code, instant egg or any other code. Crashes about 10 seconds in

Quit cheating and it won't crash its not a luma3ds problem

**Comment by NewSammyChan** [comment]
Sorry that's not a good enough answer. 

If cheats crash and nothing is going to be done about it. It means for me that CFW is useless. 

Also if it's implemented like this then the feature should be removed.

**Comment by Shadow322** [comment]
> Sorry that's not a good enough answer.
> 
> If cheats crash and nothing is going to be done about it. It means for me that CFW is useless.
> 
> Also if it's implemented like this then the feature should be removed.

Well nothing is going to be done about it as it still is not a Luma3DS problem and on that note this should of been posted on gbatemp as this is not a help forum

**Comment by urherenow** [comment]
Maybe you should make your own cheats, or talk to the person who made the cheat that you're trying to use.

**Comment by delilahsrose** [comment]
I've found that, for some reason, activating the 1.0 version of the "no outlines" cheat, deactivating, then activating the 1.5 version seems to stop crashes entirely. not sure why but it works wonders for me!

**Comment by delilahsrose** [comment]
solved it! not sure why it works, but enabling THEN disabling BOTH of the 1.0 & 1.5 no outlines cheat without exiting the luma menu, gives you no outlines without the codes running, so no crashes occur. Hope this helps!

**Comment by moldimolt** [comment]
Closing as a tech support question unrelated to Luma3DS itself; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
