### ISSUE TITLE
Feature suggestion- ram dumper

### ISSUE THREAD

**Issue by bomba1749** [LumaTeam/Luma3DS#1379]
It would be great if rosalina had a ram dumper option, so that people could rip models and stuff and make cheat codes without having to use a flashcart

**Comment by Byebyesky** [comment]
Rosalina can do heap and .text dumps.
To use it: Process list -> select your process -> press select
You can rip models easier by unpacking a rom and taking them from the romfs. That gives you the original file and saves you a bunch of time

**Comment by bomba1749** [comment]
i would but there in a format that doesnt have any tools to open it yet

**Comment by TuxSH** [comment]
Using gdb is the most flexible option. Also, as mentioned, the option to dump heap/code memory is already there.
