### ISSUE TITLE
GDB stub

### ISSUE THREAD

**Issue by henke37** [LumaTeam/Luma3DS#138]
Implement the GDB stub protocol. This would allow for really easy debugging of homebrew and retail titles alike.

NTR already has something similar, but using a nonstandard protocol that nearly no tools understand. GDB on the other hand is well understood by not only gdb itself, but also powerful tools such as IDA Pro.

Oh and "debugging" also means cheating by memory peeks and pokes.

**Comment by mariogamer2** [comment]
What is GDB?

This? : https://www.gnu.org/software/gdb/

**Comment by henke37** [comment]
Yup! That's gdb. It's the debugger that goes with gcc. And gcc is the main compiler for homebrew. As such, it would be very handy to have a gdb stub. It would let you debug homebrew on the console over a TCP connection.

**Comment by dragos240** [comment]
No idea if issues get bumped like threads do but this is a fantastic idea and would be incredibly useful for a homebrew developer.

**Comment by Mrrraou** [comment]
We are developers too. We understand how useful it is.
However, there are limitations on the consoles (especially O3DS consoles) and other things that are preventing this to be developed for now.

**Comment by henke37** [comment]
And what would these limitations be exactly?

**Comment by TuxSH** [comment]
(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ

**Comment by henke37** [comment]
In conclusion, were there any limitations, then the recent boot9strap attack took care of them. Gdb is in since 21db0d45bdffc933491be24abb933929fc91ca96!
