### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by J25Esguerra** [LumaTeam/Luma3DS#1381]
Whenever i play my mhgen on 3ds xl, it crashes and flashes a black screen with err disp type generic 
This is what the display looks like 
![IMG_20200325_041835](https://user-images.githubusercontent.com/62622217/77473848-08f67f80-6e51-11ea-892e-d62fa1bd6b1a.jpg)
Going to another place of the map makes the crashes, the game is on cartridge, the console is 3ds xl new, the console is modded or has cfw please help i want to play my games

**Comment by TuxSH** [comment]
I'll fix it soon enough

**Comment by TuxSH** [comment]
Latest commits/oreo's PR should have fixed it.
