### ISSUE TITLE
Stop 3DS's Built-In Flashcart Blocking

### ISSUE THREAD

**Issue by AkujiTheSniper** [LumaTeam/Luma3DS#139]
So for some DS flashcarts, trying to launch them on your 3DS will go straight to an error screen. However, with a patched TWL_FIRM and the TWL Slot-1 Launcher, you can boot certain flashcarts just fine (you can usually tell if it can work when the error screen was immediate when you tried booting it with the default launcher). However, would it be possible to just cut the Slot-1 Launcher out of the equation, **and instead allow the flashcarts to just boot straight from the default cart launcher?** It would be nice to be able to treat my flashcart just like any other game I own, instead of having to press a separate launcher.

**Comment by urherenow** [comment]
No. Not possible. Those carts don't work because they don't even provide a valid header to the system. Slot-1 launcher is the only way to bypass that.
