### ISSUE TITLE
Arm11 (Core0) crash when launching .3dsx application

### ISSUE THREAD

**Issue by INAAAAAAAAAAA** [LumaTeam/Luma3DS#1393]
Whenever I try to launch CtrQuake from homebrew menu, it crashes and says Arm11(Core0) 
Data abort 
And something with translation section 
Im using a old 3ds XL on the newest firmware and luma 10.0.1.
I've just enabled show NAND or user string in System Settings. 
Please. someone. Help me!

**Comment by INAAAAAAAAAAA** [comment]
Crash dump coming soon

**Comment by INAAAAAAAAAAA** [comment]
[crash_dump_00000024.zip](https://github.com/AuroraWright/Luma3DS/files/4476888/crash_dump_00000024.zip)

**Comment by TuxSH** [comment]
Is this only happening with ctrquake? How are you running it?

**Comment by INAAAAAAAAAAA** [comment]
No it also happens with CtrHexen II

**Comment by INAAAAAAAAAAA** [comment]
What do you mean how am I running it?

**Comment by TuxSH** [comment]
Are you using new-hbmenu (https://github.com/fincs/new-hbmenu/releases) ? What about stuff like ftpd (https://github.com/mtheall/ftpd/releases/download/v2.3.1/ftpd.3dsx)?

**Comment by INAAAAAAAAAAA** [comment]
Yes I'm using new Hbmenu. What is ftpd?

**Comment by INAAAAAAAAAAA** [comment]
Ok. Now I know what ftpd is, but what is it doing?

**Comment by profi200** [comment]
He is asking you to try other homebrews like ftpd to narrow down the problem.

**Comment by INAAAAAAAAAAA** [comment]
Ok

**Comment by INAAAAAAAAAAA** [comment]
Thx for the explanation

**Comment by INAAAAAAAAAAA** [comment]
ftpd works fine. The problem only occurs when I try to launch CtrQuake or CtrHexenII

**Comment by TuxSH** [comment]
The issue is a CtrQuake/CtrHexenII one then. The author(s) should ensure that these apps are build with the latest toolchain version

**Comment by INAAAAAAAAAAA** [comment]
Thx
