### ISSUE TITLE
I can't change my rosalina combo after select and start button stopped working

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1397]
My select and start button stopped working on my 2ds, is there any way to create a combo to do the start and select function? I can't change the rosalina combo without those buttons.

**Comment by TuxSH** [comment]
Change `DEFAULT_MENU_COMBO` in `sysmodules\rosalina\include\menu.h`

Here's a build where I changed the default menu combo to just "R" (GH file upload seems to be irresponsive): https://nopaste.me/#bZ6W_1Ty5O_OxvFQP0Z5OA

**Comment by ghost** [comment]
I'm unable to compile, would you compile one with the combo Left trigger + Dpad Right + A?
Is is possible to implement combos to press start and select with other combos eg: Dpad Right + b for start and Dpad right + b for select?

It seems like luma could add configurable combos for specific buttons like start and select in a near future, people like me that has low defective consoles would love it.

**Comment by ghost** [comment]
I did manage with your custom boot.firm to get to rosalina, thank you! I was in a rush and didn't think right when i was reading, and it was a shame for me because i am a programmer. Sorry for the comment above...

Do you think rosalina could have custom combos to achieve SELECT and START button actions?

The custom boot.firm doesn't also save the new combo I added, and it makes my console to take ages to shutdown.

**Comment by TuxSH** [comment]
> The custom boot.firm doesn't also save the new combo I added

There's an option in the Miscellaneous submenu, "Save settings" that you need to use. Once you use it, it should retain the new combo.

> it makes my console to take ages to shutdown.

working on fixing it

**Comment by TuxSH** [comment]
Apparently this is a thing too: https://3ds.eiphax.tech/config.html
