### ISSUE TITLE
AGB_FIRM and TWL_FIRM patching not working on EU 10.7 A9LH AuReiNand

### ISSUE THREAD

**Issue by internetakias** [LumaTeam/Luma3DS#14]
What the title says. May or may not be related to the fact I installed clean AGB_FIRM and TWL_FIRMs from 3DNUS, but legit GBA and DSiWare games work fine.

**Comment by piratesephiroth** [comment]
??? I thought all regions used the same AGB and TWL firms

**Comment by internetakias** [comment]
I'm aware, but you never know

**Comment by internetakias** [comment]
Turns out I was missing some firms.
