### ISSUE TITLE
I tried to create a Room on my Mario Kart 7 JPN cartriage. and I'm using a English 3DS

### ISSUE THREAD

**Issue by jjdomingo** [LumaTeam/Luma3DS#1403]
Error Type: Generic
Process ID: 38
Process name: DLP
Process title ID: 0x0004013000002802

Address: 0x00100440e
Error Code: 0xc8a11bef

**Comment by TuxSH** [comment]
I think we don't support out-of-region DLP, at least not yet.

**Comment by jjdomingo** [comment]
ok. thanks
