### ISSUE TITLE
Possible to make a toggle for the silent updates?

### ISSUE THREAD

**Issue by Committee** [LumaTeam/Luma3DS#141]
Topic, I would like to know if there is a way to temporarily disable the block on updates to patch the installed games (option Y when online) instead of manually downloading the patch or going through the eshop.

**Comment by RShadowhand** [comment]
That patch shouldn't change game update behaviour. It only prevents silent firmware updates.

**Comment by Committee** [comment]
it does unfortunately, running latest luma and just tried it with hyrule warriors, never got the prompt for the update.

**Comment by TuxSH** [comment]
Why would you want it disabled?
