### ISSUE TITLE
Cia GBA problem

### ISSUE THREAD

**Issue by daniel95000** [LumaTeam/Luma3DS#1414]
I tried to install a Pokemon GBA (Hackrom) on my old 3ds (version 11.13.0-45U) with Luma 10.1.3, it installed perfectly but when I play it the screen turns black and I get a message that there was a error. GB and GBC games work perfectly for me !!

What is the reason why you are failing me?

**Comment by CatsLover2006** [comment]
Luma3DS patches the AGB_FIRM file. That’s probably your issue.
