### ISSUE TITLE
Unable to open PKSM file while Luma3DS is running on Citra for Android

### ISSUE THREAD

**Issue by aecarvalho** [LumaTeam/Luma3DS#1418]
It seems like I can open Luma3DS launcher on Citra for Android but if I try to open PKSM from within Luma3DS then the system just freezes until I exit the app, any solution would be much appreciated. 
![Screenshot_20200508-024646886](https://user-images.githubusercontent.com/60945000/81345917-f2417a80-90d6-11ea-9f00-6b92a24086a3.jpg)

**Comment by Shadow322** [comment]
This does not belong here

**Comment by oreo639** [comment]
The Homebrew Launcher does not support Citra. It is designed for running 3dsx homebrew on hardware. This isn't a bug.
You can load the 3dsx for PKSM directly in Citra.
(Also, I don't believe PKSM supports Citra for non-debugging purposes)

Keep in mind as Shadow said this is for reporting issues with Luma3DS. Yet what you are showing is The Homebrew Launcher running in Citra.

**Comment by aecarvalho** [comment]
Actually it isn't a Citra issue, loading PKSM directly into Citra gives me the following error;
![Screenshot_20200508-032859484](https://user-images.githubusercontent.com/60945000/81348706-3aaf6700-90dc-11ea-9dcf-187b4c8f0ed8.jpg)

The above report is a freeze happening when PKSM is opened within Luma3DS

**Comment by oreo639** [comment]
The Homebrew Launcher and Luma3DS are not the same thing. You cannot run Luma3DS in Citra, it is impossible.
The Homebew Launcher can be run, but it doesn't support Citra and you can't launch apps from it.
PKSM performs a check for the Rosilina sysmodule, that is not a bug in luma, nor is it a bug in PKSM, nor is it a bug in CItra. PKSM only supports running on real hardware with Luma3DS.

**Comment by aecarvalho** [comment]
> Keep in mind as Shadow said this is for reporting issues with Luma3DS. Yet what you are showing is The Homebrew Launcher running in Citra.

Could you show me an instance of you running PKSM from Luma3DS just for reference?

**Comment by aecarvalho** [comment]
> The Homebrew Launcher and Luma3DS are not the same thing. You cannot run Luma3DS in Citra, it is impossible.
> The Homebew Launcher can be run, but it doesn't support Citra and you can't launch apps from it.
> PKSM performs a check for the Rosilina sysmodule, that is not a bug in luma, nor is it a bug in PKSM, nor is it a bug in CItra. PKSM only supports running on real hardware with Luma3DS.

Thanks, much appreciated
