### ISSUE TITLE
GBA games sometimes glitch the screen

### ISSUE THREAD

**Issue by shad00m** [LumaTeam/Luma3DS#142]
theres a topic about this here: http://gbatemp.net/threads/q-gba-cia-on-emunand-not-rendering-screen-correctly.397084/#post-6482252

I've read the closed issues but I haven't seen anyone mention this yet.

Sometimes (only) GBA VC Injected games have the top screen move up by a couple of pixels and it gets mirrored at the bottom. Also sometimes pressing the home button moves it a bit more to the top.
Everything is completely random without changing anything. The game could be started 5 times without any issues but then all of a sudden it gets glitched up. The same with the home button.
Example pic: http://i.imgur.com/dPg7MSq.jpg

I'm not really sure if this is a Luma Issue, like in the thread mentioned an SD issue, or the GBA Rom has been packed wrongly.

**Comment by AuroraWright** [comment]
I recall this being an AGB FIRM issue with cluster size on the SD FAT FS (too small or too large, can't remember). It surely is not a Luma issue.
