### ISSUE TITLE
[Feature Request] Add ZL/ZR Button Compatibility to open Rosalina Menu

### ISSUE THREAD

**Issue by tomasadam3** [LumaTeam/Luma3DS#1421]
Basically what the title says, I'd love if I could utilize the ZL and ZR buttons for making custom Rosalina Menu triggers, given that not too many games use them. Thank you!

**Comment by TuxSH** [comment]
This not really possible, see here: https://www.3dbrew.org/wiki/IR_Services#IR_Services

Basically, implementing support for that would mean causing issues in either Home Menu or games that use it.
