### ISSUE TITLE
Crash while navigating game icons on homescreen "Current process: menu (0004003000008f02)"

### ISSUE THREAD

**Issue by ghostwolfx** [LumaTeam/Luma3DS#1423]
New 3DS XL

Sys 11.13.0-45U

Boot9strap

v10.1.3-3143e7e

--

**Explanation of the issue:**

After I added some games (over 100 games so maybe the quantity has something to do with it?) to my homescreen via the fbi tool installing cia files, I went to browse those games hovering over the various icons and then received a crash. This has repeatedly happened about 5 times now, while hovering over different games just about every time , so it's fairly random, but always when moving from one icon to another. This crash doesn't happen 100% of the time, nor can I pinpoint a specific game as the cause, but it does seem to happen a fair majority of the time assuming I browse the homescreen long enough.

This was the main error feedback, but a more detailed crash dump is provided as well:

Processor: ARM11 (core0)
Exception type: data abort
Fault status: Translation - Section
Current process: menu (0004003000008f02)

**Steps to reproduce:**

1. Power the 3DS on freshly, and let it load up the homescreen.

2. Proceed to just navigate the homescreen, hovering over random games on it with the Dpad until it either crashes or doesn't. (sometimes I get "lucky" and it doesn't crash even after several minutes of browsing so I just use the 3DS as normal and turn it off eventually. Next time I power it on is a roll of the dice if I get lucky again.)

[crash_dump_00000001.dmp.gz](https://github.com/LumaTeam/Luma3DS/files/4645859/crash_dump_00000001.dmp.gz)

**Comment by AuroraWright** [comment]
1) We don't support piracy
2) If home menu crashes, format your SD card as data is probably corrupted.
