### ISSUE TITLE
The machine is totally broken after opening the manu

### ISSUE THREAD

**Issue by JudyLucy** [LumaTeam/Luma3DS#1424]
New 3dsll
Sys: 11.13  jp
Boot9strap
Luma: 10.1.3

I have a new 3dsll and my system is 11.13 and was updated online. My luma is 10.1.3 now. Before updating the system, I can open the Rosalina Menu by pressing L+down+select. At that time, my system was 11.6 and my luma was 8.1 and was also downloaded here. My machine can work well now without opening the menu, but after pressing the L+down+select, it was totally frozen. I want to control my machine with the help of another Xbox joy-con, so it's necessary for me to open it every time I play the games. Is there a way of fixing it?

PS: I have once tried to backroll to the luma 8.1 by downloading the doment here, but I can't even get accessed to the system because the screen was frozen at the luma setting menu at the very beginning. I have to use luma 10.1.3 now.

 Thanks for reading my bug report.

**Comment by TuxSH** [comment]
I think your buttons are stuck and may need repair.

In the meanwhile, can you try this build I haven't released yet? 
[boot.zip](https://github.com/LumaTeam/Luma3DS/files/4665194/boot.zip)

**Comment by JudyLucy** [comment]
Oh, you've reminded me of my broken camare, tough I don't know whether it has anything with that frozen manu. I will send back my feedback as soon as possible. Thanks for replying my letter.

**Comment by JudyLucy** [comment]
Problem settled! I love you my dear sister. Since it is still confidential, I will just keep it for personal use.

**Comment by Shadow322** [comment]
> Problem settled! I love you my dear sister. Since it is still confidential, I will just keep it for personal use.

What is confidential?

**Comment by JudyLucy** [comment]
> > Problem settled! I love you my dear sister. Since it is still confidential, I will just keep it for personal use.
> 
> What is confidential?

The file of course. The file above mentioned hasn't been released officially, so it is confidential and I will keep it just for personal use.

**Comment by Shadow322** [comment]
> 
> 
> > > Problem settled! I love you my dear sister. Since it is still confidential, I will just keep it for personal use.
> > 
> > 
> > What is confidential?
> 
> The file of course. The file above mentioned hasn't been released officially, so it is confidential and I will keep it just for personal use.

myth-busted as anyone that has a proper compiling environment can get that file

**Comment by TuxSH** [comment]
This build ""solving"" the issue can only mean you have stuck buttons, which needs repair.

**Comment by JudyLucy** [comment]
Ok. I see. I will check it when it is convient to me. Thanks for telling me the hardware problem.  I shouldn't have opened it myself so as to let it start directly with the help of the wire and the adaptor.
