### ISSUE TITLE
[Request] Per-Game New 3DS Settings

### ISSUE THREAD

**Issue by CatsLover2006** [LumaTeam/Luma3DS#1429]
I’m not 100% sure what I’m looking for isn’t already in some way implemented, but couldn’t it be possible to override the increased clock and l2 for certain games?
Maybe include a list of prebuilt settings for games which glitch under these circumstances?
**Note:** I’m not including New 3DS enhanced titles, but if it makes life easier, it’s ok if those are added.

**Comment by CatsLover2006** [comment]
**Edit:** this could also have to do with the Rosalina menu, like saving the wanted clock and L2 settings to the game.

**Comment by nayief94** [comment]
hi

**Comment by TuxSH** [comment]
> Maybe include a list of prebuilt settings for games which glitch under these circumstances?

Just disable the corresponding main Luma menu option for it and use the "dynamic" Rosalina option instead.

**Comment by CatsLover2006** [comment]
Where’s the “dynamic” option?

**Comment by RinMaru** [comment]
> > Maybe include a list of prebuilt settings for games which glitch under these circumstances?
> 
> Just disable the corresponding main Luma menu option for it and use the "dynamic" Rosalina option instead.

Whats the Dynamic option?
