### ISSUE TITLE
Denpa Men 2 "Beyond The Waves" crashes

### ISSUE THREAD

**Issue by Toadlover404Git** [LumaTeam/Luma3DS#1436]
I have an original 3DS XL running B9S 10.13. I'm trying to use a save editor to edit my save file to unlock every item in The Denpa Men 2: Beyond The Waves, and it works but whenever I go into the "Commands" menu, the game crashes with [this screen](https://imgur.com/a/FEhAGpn). I restored my original game and it didn't crash. I'd appreciate some help in fixing this issue.

Dump File:
https://drive.google.com/file/d/1HVSNACp0QQBO9YPpJP4miVgBv4koUl1z/view?usp=sharing

**Comment by Shadow322** [comment]
Cheating isn't a Luma3DS problem
