### ISSUE TITLE
[Feature Request] TitleID Spoofing

### ISSUE THREAD

**Issue by BrandtVanDenBerg** [LumaTeam/Luma3DS#1439]
I've thought about this for a while and see no reason why it can't be implemented.
What if we could spoof title information?
For example, send Mario Kart 7's TitleID to Nintendo instead of the Homebrew Launcher's?
While I don't know whether this is possible, the implementation user-wise could be rather simple.
For example, a file labelled 'spoof.cfg' inside the luma folder, with lines like this:

[TitleID of application]:[Spoofed TitleID]

This would also allow the 'show friends what I'm playing' setting to be left on, as it would simply show a legit game instead of a homebrew app, provided the user had configured Luma to do so.

**Comment by Dimensional** [comment]
Interesting idea. It alone wouldn't be used to get around bans, just make it harder for Big N to find invalid Title IDs and subsequently ban people for those. It wouldn't do anything for people who already were banned, such as myself, so they'd have to use other methods that Luma doesn't want to implement, however this method could be used to at least allow homebrew to run from system installation without the risk of banning.

**Comment by oreo639** [comment]
Note, it is possible to use offical applications as an entrypoint for the Homebrew Launcher.
There is an option in Rosilina to switch the current title to HB. Then go to `save settings`.
Your change will persist across reboots.

**Comment by Dimensional** [comment]
That's for the homebrew menu. What about running homebrew from the home screen after they were installed from cia files, like some save editors that require extra access not possible in the homebrew menu, or emulators like RetroArch PSX which only run well if loaded from the home screen? Or even some VC injections?

**Comment by oreo639** [comment]
Installing homebrew as CIAs in order to get custom permissions isn't necessary anymore with Rosilina.

But you are right I wasn't thinking about that.

**Comment by TuxSH** [comment]
This would require NS to be reimplemented, in other words, this is a PITA :)
