### ISSUE TITLE
Wont boot Arm9 :( Crashes after powering 3DS on

### ISSUE THREAD

**Issue by Ravenheart623** [LumaTeam/Luma3DS#1441]
![IMG_8305](https://user-images.githubusercontent.com/67199356/85206237-56667980-b2e6-11ea-8136-ff733fb22356.jpg)

![IMG_8306](https://user-images.githubusercontent.com/67199356/85206334-f6240780-b2e6-11ea-9fef-bbb04fbc66fa.jpg)

My 3DS crashes upon powering it on. Both with and without an SD card. Not sure what the problem is.

**Comment by cooolgamer** [comment]
oof... It's anyting bad on your NAND, have you a backup of your nand? If not, use a ctrtransfert...

**Comment by Ravenheart623** [comment]
I actually did a Crttransfer and it seemed to fix it.
Although it seemed to have uninstalled some things. Just thankful it’s booting up again. 😄 Thanks for the reply.
