### ISSUE TITLE
Screenshot saving in 800px mode

### ISSUE THREAD

**Issue by RocketRobz** [LumaTeam/Luma3DS#1443]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.13.0-45U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap/Sighax

**Luma3DS version:**

v10.1.3 stable

**Luma3DS configuration/options:**

Screen brightness: (1)

Splash: (Before)

Splash duration: (1)

PIN lock: (Off)

New 3DS CPU: (Clock)

--

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: (x)

Patch Arm9 access: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

--

**Explanation of the issue:**

Saving top screenshots while in 800px mode only saves the left half of the screen.

**Steps to reproduce:**

1. Launch an application that runs in 800px mode, such as [this example](https://github.com/citra-emu/citra/files/4802283/wide-console.zip).

2. Open Rosalina menu.

3. Take screenshot.

4. Find the saved image on the SD card.

**Comment by TuxSH** [comment]
I'll implement it later :p
