### ISSUE TITLE
luma v6.2.3 dev link is brocken

### ISSUE THREAD

**Issue by cooolgamer** [LumaTeam/Luma3DS#1444]
hello, I search for luma dev but I find the latest dev version, 6.2.3 but the link is brocken, how to have it now?
thanks.

**Comment by Akurosia** [comment]
link to the mentioned dev version is following: https://github.com/LumaTeam/Luma3DS/releases/download/v6.2.3/Luma3DSv6.2.3-dev.7z

Since 6.3 (copied from the changelog): Merged the regular and dev builds into one.

Hope this helps

**Comment by TuxSH** [comment]
This happened because the repo was hacked once. GH support restored it but not the older releases.

I don't have any intent to support any version that is not the latest.
