### ISSUE TITLE
Random crashes when pressing HOME on Pokemon ORAS

### ISSUE THREAD

**Issue by Despresso99** [LumaTeam/Luma3DS#1446]
**System model**: New 2DS XL
**SysNAND version** (+emu/redNAND version if applicable): 11.13.0-45U
**Entrypoint (How/what you're using to boot Luma3DS)**: Boot9Strap
**Luma3DS version**: 10.0.3 stable
**Luma3DS configuration/options**:
Screen brightness: 1
Splash: Off
Splash duration: N/A
PIN lock: Off
Enable loading external FIRMs and modules: ( )
Enable game patching: (x)
Show NAND or user string in System Settings: (x)
Show GBA boot screen in patched AGB_FIRM: ()
Set developer UNITINFO: ( )
Disable ARM11 exception handlers: ( )

**Explanation of the issue**:
Crashes every now and then when pressing home whilst playing a game.
I seem to encounter this bug and I am not sure what is the cause of it. Essentially, sometimes when I press home whilst in the middle of a game, the 3ds crashes and leads me to that error message. It does not happen all the time, but only sometimes. Attached is the crash dump.

![Crash Screen](https://user-images.githubusercontent.com/67575402/85979633-e1163b00-b9ae-11ea-9dd3-7bfc72b37591.png)

[crash_dump_00000003.zip](https://github.com/LumaTeam/Luma3DS/files/4844118/crash_dump_00000003.zip)

**Comment by Despresso99** [comment]
If any additional information is needed to be provided, I can happily provide. :)

**Comment by Despresso99** [comment]
Edit: Nvm, did not get fixed.
But, it seems to be only relegated to my Alpha Sapphire game when I have enabled game patching turned on, but despite a few of my other games having rom hacks on them as well, they don't have the same issue, so, just confused as to why it's happening. Any help would be much appreciated when possible. :^)

**Comment by moldimolt** [comment]
Closing as a tech support question unrelated to Luma3DS itself; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
