### ISSUE TITLE
Luma3ds payload dont work

### ISSUE THREAD

**Issue by pedroc07** [LumaTeam/Luma3DS#1449]
Luma3ds payloads is not working and so GM9 is not building when i press start while opening it and dont ask if my folder is named right and stuff like that because i checked all it :P

**Comment by TuxSH** [comment]
Do you have more than one payload?

**Comment by pedroc07** [comment]
No

Em Sáb, 11 de jul de 2020 18:25, TuxSH <notifications@github.com> escreveu:

**Comment by TuxSH** [comment]
If you only have one payload it won't show up the payload menu and will instead launch the payload directly

**Comment by pedroc07** [comment]
But it show nothing doesnt show  payload and doesnt show gm9 (boot in
payload folder)


Em dom., 12 de jul. de 2020 às 15:41, TuxSH <notifications@github.com>
escreveu:

**Comment by pedroc07** [comment]
Bro you shouldn't close it, my problem is not solved :/

Em Dom, 12 de jul de 2020 15:41, TuxSH <notifications@github.com> escreveu:

**Comment by TuxSH** [comment]
This is a GM9 bug, https://github.com/d0k3/GodMode9/issues/578, not my issue.

Try to have more than one payload in the payload folder, I guess.
