### ISSUE TITLE
Can you change the "HBL Injector to current.app" in Rosalina Menu so that it can be "Inject any app to current.app"

### ISSUE THREAD

**Issue by TismSpectrum69** [LumaTeam/Luma3DS#1451]
Please and thanks.

Instead of injecting just HBL to current.app it would be cool to have a feature where you can inject any installed app into the currently launched app.

I know that Godmode9-1.2.7 exists, but it only allows for injection to 3 stock apps which is a very limited feature. I want to be able to inject to things like the game-card app (which is entirely possible now using the HBL to current app feature).

**Comment by TuxSH** [comment]
How Rosalina does it is very different from how GodMode9 does it.

Also, I don't see the point to add a feature difficult to add, difficult to maintain and that serves no interesting purpose.
