### ISSUE TITLE
[Feature Request] Boot Directly to DS Mode

### ISSUE THREAD

**Issue by MarioKartFan** [LumaTeam/Luma3DS#1455]
Would it be possible to enable booting directly to DS Mode by holding a button on boot?  Over on GBATemp, someone attempted to use TWL_Firm as a payload, but receives an error message upon boot.

**Comment by MarioKartFan** [comment]
Bummer. @AuroraWright I appreciate all of your hard work...is there a reason this is invalid though?

**Comment by DraconicNEO** [comment]
> 
> 
> Bummer. @AuroraWright I appreciate all of your hard work...is there a reason this is invalid though?

They're probably Just feeling lazy and/or didn't understand/care about it.
