### ISSUE TITLE
Godmode9 1.9.1 does not work with Luma3DS 10.2

### ISSUE THREAD

**Issue by sthetix** [LumaTeam/Luma3DS#1458]
I found that Godmode9 1.9.1 does not work with Luma3DS 10.2, any info on it?

Thanks

**Comment by oreo639** [comment]
Duplicate:
https://github.com/LumaTeam/Luma3DS/issues/1457

**Comment by Shadow322** [comment]
> I found that Godmode9 1.9.1 does not work with Luma3DS 10.2, any info on it?
> 
> Thanks

Works here

**Comment by TheMasterOfMike** [comment]
If you have two payloads, it will work fine (chainloader menu loads up) but if it's only one, and you're using B9S and Luma 10.2, it will not work.

That being said, it's already been reasonably proven it's an issue with GodMode9.

**Comment by Shadow322** [comment]
> If you have two payloads, it will work fine (chainloader menu loads up) but if it's only one, and you're using B9S and Luma 10.2, it will not work.
> 
> That being said, it's already been reasonably proven it's an issue with GodMode9.

Ah I see I do have 2 payloads then
