### ISSUE TITLE
About GodMode9 issues

### ISSUE THREAD

**Issue by TuxSH** [LumaTeam/Luma3DS#1460]
You might have noticed that the latest releases of GodMode9 do not display anything if directly booted (e.g. by having only one payload in the payloads folder). **This is not a Luma3DS bug**.

A **workaround** to the issue is to have more than one payload in the `/luma/payloads` folder and bring up the chainload menu by pressing `START`.

GM9 issues:

* https://github.com/d0k3/GodMode9/issues/578
* https://github.com/d0k3/GodMode9/issues/608

**Comment by moldimolt** [comment]
Per [GM9 issue #578](https://github.com/d0k3/GodMode9/issues/578), this was fixed on their side in pre-release 1.9.2.
