### ISSUE TITLE
[Question] What's this title?

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#147]
Hello. After installing Luma3DS this strange title appeared on my home menu. I'm not sure if it is a title that Luma3DS installed for region free, etc but I was curious because it doesnt show on any of my other CFWs. http://i.imgur.com/nJIp52W.jpg

**Comment by ihaveamac** [comment]
check with FBI 2.x to see if anything unusual was installed to NAND? maybe like something with a title ID that begins with 00040000 (which are usually installed to SD)?

**Comment by ghost** [comment]
A wild 0x0004000000686200 with the product code CTR-HB-LUMA has appeared

**Comment by ghost** [comment]
Seems to be some kind of thing for Luma. Maybe RF as I suggested

**Comment by ihaveamac** [comment]
that's probably not supposed to be installed to NAND.

**Comment by ghost** [comment]
Actually that doesn't seem to match the title shown in the image.

**Comment by ihaveamac** [comment]
things installed to NAND that shouldn't will usually show a black icon with no name. "000400000068620"/"CTR-HB-LUMA" doesn't look like something that should be in NAND so might want to delete it.

**Comment by ghost** [comment]
Actually I misread your comment and was reading that from SD. I don't see anything out of the ordinary in NAND
