### ISSUE TITLE
GodMode9 don't boot after luma3ds update

### ISSUE THREAD

**Issue by davidcc73** [LumaTeam/Luma3DS#1470]
-- Please fill in the placeholders.-->
**System model:**

[New 2DS XL, **New 3DS XL**, New 3DS, Old 2DS, Old 3DS XL, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. **Boot9Strap**/Sighax, etc.]

**Luma3DS version:**

[e.g. **v10.2** stable or if using non-releases specify the commit like this 

**Steps to reproduce:**
After I update my luma3ds to the version v10.2 the godmode9 stopped working when I press the start during the boot, the 3ds only shows a black screen, I have to hold the power button to make it shut down. 
I tried to use de version v1.7.1 of godmod9 and it worked. After that, I tried the more recent version (just to check) and it's back to work.

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( 4)

Splash: ( before)

Splash duration: ( 3s)

PIN lock: (off )

New 3DS CPU: (off )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x )

Show NAND or user string in System Settings: ( x)

Show GBA boot screen in patched AGB_FIRM: ( x)

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

**Comment by toxic9** [comment]
Hi!

This is a known (godmode9) bug. Not Luma's.
The workaround is to have more than one payload on the same folder.
You can even copy godmode9 payload and call it godmode9(1).firm !!

**Comment by Lesking72** [comment]
Just setting a splash to display before payloads is enough to make it work for me

**Comment by Shadow322** [comment]
Just compile latest source as it's been fixed

**Comment by toxic9** [comment]
> Just compile latest source as it's been fixed

Compile Luma3DS or godmode9 ??

**Comment by Shadow322** [comment]
> > Just compile latest source as it's been fixed
> 
> Compile Luma3DS or godmode9 ??

It's a godmode9 side problem

**Comment by mackal** [comment]
Personally I copied both dev and normal firmware over, doing this resulted it bringing up the boot select menu, which has worked 100% of the time booting into GM9 after selecting it.

**Comment by Shadow322** [comment]
> Personally I copied both dev and normal firmware over, doing this resulted it bringing up the boot select menu, which has worked 100% of the time booting into GM9 after selecting it.

Duh having more then one payload is a temp fix but just compile latest source as it's been fixed
