### ISSUE TITLE
Suggested feature: ceserver integration

### ISSUE THREAD

**Issue by dariendark** [LumaTeam/Luma3DS#1474]
Not sure if this should be placed in pull requests instead. Ill move it if so. What I'm perplexed about is the debugger built into the rosalina menu. For those of us who wish to create cheats from scratch. Wouldnt integrating the ceserver function into luma be a better idea. Give us access to the internets best cheating tool instead of mucking around with ida pro and no direct way to search ram data before setting breakpoints. For those who dont know what ceserver is, this is the link to its source
https://github.com/cheat-engine/cheat-engine/tree/master/Cheat%20Engine/ceserver

**Comment by profi200** [comment]
gdb is not intended for cheating and it's there for developers only. It's not a better idea since both serve different purposes.

Cheat searching probably has been requested already in #752.
