### ISSUE TITLE
“Unable to mount CTRNAND or load CTRNAND FIRM” on trying to open TWLMenu++

### ISSUE THREAD

**Issue by milesssx** [LumaTeam/Luma3DS#1478]
I was trying to troubleshoot an issue i was running into when playing a NDS game from the sad card when i got this issue. In the run up to this message coming up i: ran the luma updates and updated to the latest version, tried restoring the version i had before after encountering the issue, reinstalling TWLMenu++ in a million different ways, i accidentally ran the TWLM++ uninstall app which lead to reinstalling it all again. 

System info: o2DS (original firmware 10.3.0-28J), used the region change guide to change it to USA. Running luma and GM9 v1.9.1

Thanks for any help you can offer <3

**Comment by AuroraWright** [comment]
The error means something is seriously wrong with your NATIVE/TWL FIRM files on the CTRNAND, likely caused by the app you described. Nothing to do with Luma itself
