### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#148]
EDIT Read below posts

**Comment by ghost** [comment]
Oh I also have tried renaming it start.bin

**Comment by ihaveamac** [comment]
have you tried something like `start_Decrypt9WIP.bin`? so far it seems you've tried `start_Decrypt9WIP.dat` (.dat is incorrect) and `start.bin` (doesn't have a name).

**Comment by ghost** [comment]
Yeah I realized I accidentally renamed it to dat. I've tried it with the bin in the Decrypt9 release too.

**Comment by ihaveamac** [comment]
tried another button? I use `left_d9.bin` holding left just fine.

**Comment by ghost** [comment]
I just tried with "a" still no dice. Would a video help?

**Comment by ihaveamac** [comment]
are you using `Decrypt9WIP.bin` and not the dat? are you adding a name to it (just "`a.bin`" won't work I think)?

**Comment by ghost** [comment]
Yes I am using Decrypt9.bin

**Comment by ghost** [comment]
The reason I need to do this is because I can't load Decrypt9.3dsx in Luma cfw, it just goes back to the hbl

**Comment by ghost** [comment]
I've tried many more attempts than the ones in this thread. I've tried a_D9.bin a.bin start_Decrypt9.bin

**Comment by pbanj** [comment]
Try this
https://cdn.discordapp.com/attachments/205039685859278848/207038532676485121/start_decrypt9WIP.bin

**Comment by ihaveamac** [comment]
if you're using "A" you need to hold L+A to use the payload. start should work. try another button as well, like left.

**Comment by ghost** [comment]
http://m.imgur.com/9ZXTHBw Strange the file on the left didn't work but the one you sent worked fine. Does it not like NAME to start with a capital?

**Comment by pbanj** [comment]
I think you may have been using the DAT file and not the bin

**Comment by pbanj** [comment]
Or your bin was corrupted somehow

**Comment by ghost** [comment]
As you can see they are the same size. The dat is 223kb cmon guys a simple extension rename mistake...

**Comment by ghost** [comment]
Yeah might've been corrupted. A lot of my files that I put on my SD have randomly been becoming 0bytes

**Comment by pbanj** [comment]
Try giving the one I linked a capital D and see if it still loads, if not we known that was it

**Comment by ghost** [comment]
Currently in the middle of a nand backup :(

**Comment by ghost** [comment]
I'll update you when its done

**Comment by pbanj** [comment]
So did the capital letter work also?

**Comment by ghost** [comment]
Nope. The caps is most likely what's causing it. I wrote another payload like corbenik and I had to not use caps

**Comment by ghost** [comment]
https://github.com/AuroraWright/Luma3DS/blob/af19719e3463dc4adf16438e6473b9401017ea0f/source/fs.c

I haven't done a lot of file system oriented things in C so I don't seem to be able to find where it is ignoring caps...

**Comment by ghost** [comment]
For example a_decrypt9WIP.bin will work but not a_Decrypt9.bin

**Comment by ghost** [comment]
Actually after testing it worked half the time wtf?

**Comment by ghost** [comment]
Weird sometimes the payloads doesn't work but it must not be caps.
