### ISSUE TITLE
NTP client failing

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [LumaTeam/Luma3DS#1481]
**System model:**

N2DS

**SysNAND version (+emu/redNAND version if applicable):**

11.13.0

**Entrypoint (How/what you're using to boot Luma3DS):**

boot9strap

**Luma3DS version:**

10.2 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

Using the NTP client either results in freezing, or `Operation failed. (ffffffff)`

`time.windows.com` is not blocked, and is reachable.

**Steps to reproduce:**

1. Use NTP Client to set to -0500
2. Observe freezing or error message

**Comment by ThatNerdyPikachu** [comment]
It started working all of a sudden? Strange.

Will keep open just in case.

**Comment by TCAtrevor** [comment]
This is happening to me. The time sync menu completely freezes until I cut the network connection, at which point it returns the `Operation failed (ffffffff).` message.

**Comment by therealprocyon** [comment]
For me it currently is occurring. It actually worked in the past but now it freezes and then gives this error.

**Comment by salt86** [comment]
I was having a similar issue. My wireless was switched off. I turned it on and it worked.
