### ISSUE TITLE
help

### ISSUE THREAD

**Issue by crispyi2** [LumaTeam/Luma3DS#1482]
[crash_dump_00000011.zip](https://github.com/LumaTeam/Luma3DS/files/5045328/crash_dump_00000011.zip)
so basically whenever I try to run anything from the homebrew launcher (im mainly trying to get cyannoge3ds working but i still want to use other apps) i get this arm11 (core 0) error plz help (deleting the 00008f folders didnt work for me)

**Comment by AuroraWright** [comment]
Not a support forum
