### ISSUE TITLE
Consistent ARM 11 Exception while on home screen 

### ISSUE THREAD

**Issue by bsil1248** [LumaTeam/Luma3DS#1484]
**System model:**
Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.5.0-38U (Specifically, **11.5.0-38U_ctrtransfer_o3ds.bin** from [this](https://3ds.hacks.guide/ctrtransfer.html) guide)

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9strap

**Luma3DS version:**

Luma3DS v10.2 stable

**Luma3DS configuration/options:**

Default EmuNAND: (N/a)

Screen brightness: (4)

Splash: (Off)

Splash duration: (1)

PIN lock: (Off)

New 3DS CPU: (N/a)

--

Autoboot EmuNAND: ()

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

A bit of background, I bought a "new" o3ds XL on Monday. I followed [this](https://3ds.hacks.guide/) guide to install B9s and Luma3DS and all seemed well. Today I got a random crash while exiting from a NDS game on my R4. After that crash, I've been unable to keep my 3ds on the home menu unless I remove the SD card.

I'll receive an Arm 11 exception followed by a shutdown between 5-10 minutes after I've powered on the device and sat on the home screen. I've attached the dumps from the last few times this has happened.

I've tried formatting my SD card to FAT32 with 32KB clusters (3 times now), 
performed CTRTransfer following [this](https://3ds.hacks.guide/ctrtransfer.html) guide, and deleting the `0000008f` folder from the appropriate directory on my SD card. I followed the guide [here]( https://3ds.hacks.guide/f3-(linux)) to test my SD card using F3 and it looks to be totally fine. [f3.log](https://github.com/LumaTeam/Luma3DS/files/5067133/f3.log)

**Steps to reproduce:**

1. Power on Device with SD inserted

2. Wait for ~ 5-10 minutes.

**Dump file:**
[arm11.zip](https://github.com/LumaTeam/Luma3DS/files/5066957/arm11.zip)

**Comment by AuroraWright** [comment]
https://gbatemp.net/threads/black-screen-at-the-start-of-the-3ds.543980/page-3#post-8763629 follow these instructions, it seems to be a home menu issue sadly. Please reopen the issue if it's not fixed.
