### ISSUE TITLE
Godmode9 1.9.1 don't start pressing power button+start with the lastest version of luma(10.2)

### ISSUE THREAD

**Issue by hamzawarudo** [LumaTeam/Luma3DS#1489]
I don't know the cause why with the god mode9  version 1.9.1 when you pressing the power button+start don't start with luma 10.2
but Godmod9 1.9.1 work with luma 10.1.3
if you have my same problem downgrade the luma version  replace the boot.firm and boot.3dsx with the file of 10.1.3 version

**Comment by Shadow322** [comment]
It's been fixed already in latest gm9

**Comment by AuroraWright** [comment]
Main issue: https://github.com/LumaTeam/Luma3DS/issues/1460
