### ISSUE TITLE
3DS complete wipe?

### ISSUE THREAD

**Issue by Tytylertuck** [LumaTeam/Luma3DS#1490]
I reboot my 3ds to find all my data is wiped, and nothing is there (FBI, Luma, games, HB). Anybody know a fix for this? Thanks in advance! -Edit, forgot to mention i cant launch up e-shop, because it gives me the error "An error occurred (errdisp) generic=36.

**Comment by Shadow322** [comment]
> I reboot my 3ds to find all my data is wiped, and nothing is there (FBI, Luma, games, HB). Anybody know a fix for this? Thanks in advance! -Edit, forgot to mention i cant launch up e-shop, because it gives me the error "An error occurred (errdisp) generic=36.

This is not a help forum use gbatemp kthx

**Comment by ghost** [comment]
If you are going to miserably fail to give him any useful information, then why is this issue still open?

**Comment by ghost** [comment]
To fix this issue, you should first ensure that the "Nintendo 3DS" folder is on the SD Card and can be opened via GodMode9. Then, you should ensure that the "data" and "dbs" folders and the private/movable.sed file are still on the NAND. If any of these files are missing, then restore them from your backup. If you don't have a backup, then this can be a future lesson to you to always make backups.

**Comment by AuroraWright** [comment]
Not a support forum
