### ISSUE TITLE
Luma3DS payload error

### ISSUE THREAD

**Issue by pedroc07** [LumaTeam/Luma3DS#1495]
Hello, Luma payload is not working in my console, i use 10.2 version, my console is a Old 3ds xl. I press start when i power it and it goes to nintendo 3ds home page and its not about that gm9 issue, since i tried with descrypt9 and multiples files and it didn't worked, i also tried to use some cheats like pressing start after opening luma configuration but nothing worked, also my start button is working right in every game so i dont think its that.

**Comment by pedroc07** [comment]
I already solved it with the right support, thanks for the attention.

**Comment by Thetruewatergod** [comment]
HOW
