### ISSUE TITLE
Enable Game Patching [n3ds]

### ISSUE THREAD

**Issue by GamingInfinite** [LumaTeam/Luma3DS#1496]
I'm trying to randomize Pokemon Ultra Sun.  Followed all of the standard "put the right folders in the right patching areas" and all that.  I can't find anything wrong.  All the information I can give you is the path:

luma\titles\00040000001B5100\romfs

and that I've double, triple, and quadruple checked the way everything is laid out within the romfs folder.  I've got enable game patching on, and haven't messed with any other settings.

**Comment by ghost** [comment]
Ultra Sun is 1B50

**Comment by ghost** [comment]
This issue has seemingly been solved, but I have experienced this same issue with all games that have update data installed.

**Comment by AuroraWright** [comment]
Not a support forum
