### ISSUE TITLE
Save screenshots to DCIM folder with JPEG

### ISSUE THREAD

**Issue by CyberRex0** [LumaTeam/Luma3DS#1501]
Take screenshot function is very good, but I want to one more features.
By default, Screenshots are saved in Luma folder with BMP, but I want to get them with JPEG.

It is useful with upload using browser

**Comment by ghost** [comment]
This feature would be very useful.

**Comment by TuxSH** [comment]
Memory is sparse on O3DS and they're is no memory to waste on this.
