### ISSUE TITLE
ARM11 exception svcBreak in process menu

### ISSUE THREAD

**Issue by LateusBetelgeuse** [LumaTeam/Luma3DS#1503]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

I cannot check it anymore, but it's the latest American version.

**Entrypoint (How/what you're using to boot Luma3DS):**

I don't know how can I check it, but I followed the steps in the 3ds.hacks.guide page

**Luma3DS version:**

v10.2 stable

**Luma3DS configuration/options:**

`Screen brightness: 4(x)`

`Splash: Off(x)`

`Splash duration: 1(x) seconds`

`PIN lock: Off(x)`

`Enable loading external FIRMs and modules: ( )`

`Enable game patching: ( )`

`Show NAND or user string in System Settings: (x)`

`Show GBA boot screen in patched AGB_FIRM: ( )`

`Set developer UNITINFO: ( )`

`Disable Arm11 exception handlers: ( )`

---

**Explanation of the issue:**

The exception persists even without SD Card.

```
Processor: ARM11 (Core 0)
Exception type: prefetch abort (svcBreak)
Fault status: Debug event
Current process: menu (0004003000008F02)
```

![photo_2020-09-24_17-46-10](https://user-images.githubusercontent.com/45151224/94205528-797a6980-fe91-11ea-9d91-cf1191c21d3d.jpg)

I've tried a `CTRTransfer (D9)` using the script that comes with `GodMode9`. That was my best shoot. After completed I saw a "loading" dialog _"Preparing Home Menu"_ or something like that. After the loading finished I got the same error.

---

**Steps to reproduce:**

1. Turn on the 3DS

**Dump file:**
[crash_dump_00000000.tar.gz](https://github.com/LumaTeam/Luma3DS/files/5279672/crash_dump_00000000.tar.gz)

**Comment by neoman1918** [comment]
I'm facing the same problem. Above message shows when I try to power on my O3DS XL. If I remove my SD card, the blue LED lights up, then goes off -- but I had already done CTRTransfer to NAND.

**Comment by neoman1918** [comment]
Just managed to solve this problem by following the steps in the link below:

https://gbatemp.net/threads/black-screen-at-the-start-of-the-3ds.543980/page-3#post-8763629

**Comment by Smoreslickgores** [comment]
Yo I have the same same problem so I went to fbi then went to titles then deleted the red things in titles cuz they were taking a lot of space on my 2ds then turned it off to take a break then the (Arm11) (core 0) (SvcBreak)

**Comment by Masamune3210** [comment]
> Yo I have the same same problem so I went to fbi then went to titles then deleted the red things in titles cuz they were taking a lot of space on my 2ds then turned it off to take a break then the (Arm11) (core 0) (SvcBreak)

For the love of gods do not just go through the title list and delete titles you don't know about

**Comment by Zatchhg** [comment]
I'm having the problem with core 1
![Uploading IMG_20220701_152218038.jpg…]()

**Comment by Zatchhg** [comment]
![Uploading IMG_20220701_152218038.jpg…]()

**Comment by Lblk0217** [comment]
![20241011_191217](https://github.com/user-attachments/assets/a69734b0-c239-4326-ad91-8941f022f445)
i dont know how to fix this problem can someone help me

**Comment by 1642128** [comment]
I learned that this error means there is missing code in the NAND (system files). So your best bet would be to use a NAND backup to reinstall the previous NAND using GodMode9 (https://www.cfwaifu.com/3ds-backup-restore/). If you can't do this (you don't have a backup) then you'll probably have to do some sort of factory reset.

**Comment by Masamune3210** [comment]
There are loads of things that can cause this kind of crash, missing system files is only one cause.

**Comment by lateus** [comment]
I'm the original poster of this issue. I just want to say that @Masamune3210 is totally right. This can have very different causes.

That said, I don't think that this issue was really fixed nor I think it should be opened again. There's not objective solution to this problem and, being realistic, people are not going to work on this anymore. I'm just thankful that Luma is as robust as it is, and this is not a common issue.

In my case, I tried a bunch of scripts one after another and eventually it got solved. That was more than four years ago, and in that time spam I've seen this error again under very different circumstances and they all got solved in very different ways, with most of them not being as severe as mine. GodMode9 usually comes with useful scripts, with a description of what they do and when you should use them. You can try those.

**Comment by sterlingsisemore** [comment]
> I'm the original poster of this issue. I just want to say that [@Masamune3210](https://github.com/Masamune3210) is totally right. This can have very different causes.
> 
> That said, I don't think that this issue was really fixed nor I think it should be opened again. There's not objective solution to this problem and, being realistic, people are not going to work on this anymore. I'm just thankful that Luma is as robust as it is, and this is not a common issue.
> 
> In my case, I tried a bunch of scripts one after another and eventually it got solved. That was more than four years ago, and in that time spam I've seen this error again under very different circumstances and they all got solved in very different ways, with most of them not being as severe as mine. GodMode9 usually comes with useful scripts, with a description of what they do and when you should use them. You can try those.

can you elaborate i have the core 1 problem and i wanna fix it how do i find and use the godmod9 scripts
