### ISSUE TITLE
BootNTR Selector Mode 3 semi-working in O3DS in 10.2 and crash in 9.1

### ISSUE THREAD

**Issue by Legarad** [LumaTeam/Luma3DS#1505]
In Luma 3DS 10.2 games that require extended memory do not detect cheat files, but the BootNTR Selector Mode 3 can be seen to be active when pressing the X + Y buttons. While in the Luma3DS 9.1 the game Dragon Quest XI crashes with Debug Event in ARM11

Normal Boot NTR Selector is working correctly.

**Comment by AuroraWright** [comment]
This is not the NTR repo
