### ISSUE TITLE
Patch ssl:C to disable cert verification

### ISSUE THREAD

**Issue by ChlorideCull** [LumaTeam/Luma3DS#151]
Useful for working with data mining applications. I assume patching `CreateContext` to always apply bit 9 ("Disables server cert verification when set." according to 3dbrew) would do the trick?

Should obviously come with huge warning signs for the configuration option, since it would create a security nightmare on untrusted networks, like public WiFi.

**Comment by ghost** [comment]
Perhaps it'd have to be enabled manually, so you cant accidentally do it :stuck_out_tongue:

**Comment by thejsa** [comment]
Bump as this would be absolutely amazing for reverse engineering and the like

**Comment by Margen67** [comment]
https://github.com/SciresM/3DS-SSL-Patch ?

**Comment by ghost** [comment]
Literally only came out 14 minutes ago, but yes that's fine ~~except you have to build an old copy of Luma~~ - this can be closed then.
