### ISSUE TITLE
[Bug] Problem starting the console with the volume lowered to 0 (The minimum)

### ISSUE THREAD

**Issue by wuniversales** [LumaTeam/Luma3DS#1511]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

Sys 11.13.0-45E

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

https://github.com/LumaTeam/Luma3DS/releases/tag/v10.2

**Luma3DS configuration/options:**

Screen brightness: (x)

Splash: (Off)

Splash duration: (1)

PIN lock: (Off)

--

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

--

**Explanation of the issue:**

The console starts up with sound even though the volume is off.

Edit

It seems that the problem also appears on some occasions when closing 3ds and reopening it.
I have been able to observe that the problem appears when the screen stays black for a while.

Edit 2

It seems that now it works well, it is not clear to me what is the pattern to generate the error, but on some occasions it happens.

**Steps to reproduce:**

1. Turn on the console with the volume turned down to minimum.

2. When starting the main menu you can hear the initial music.

**Comment by moldimolt** [comment]
Closing as a tech support question unrelated to Luma3DS itself; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
