### ISSUE TITLE
Luma does not load "R4i gold V1.4.1" card

### ISSUE THREAD

**Issue by wuniversales** [LumaTeam/Luma3DS#1512]
I understand that Luma unlocks all R4i cards, in fact I have three R4 cards, all the cards (even those that are not compatible with 3ds) work for me except one, the one that I indicate in the title.

R4i gold V1.4.1
Website: www.r4i-gold.com (The web does not work)

The card doesn't even appear as detected.
I would like it to work with luma too.
Greetings

**Comment by AuroraWright** [comment]
Luma removes all flashcart checks, so it seems this cart isn't proper enough for the home menu to detect it as an actual DS cart. Nothing we can do about that
