### ISSUE TITLE
BUG - Loop on starting Luma3DS

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1515]
When starting Luma3DS, does a loop asking if I want to update. Is this normal?

![2020-11-02 16 48 36](https://user-images.githubusercontent.com/53082621/97888820-e0f6c500-1d2b-11eb-823e-fb15f830d349.jpg)

**Comment by Nuck-TH** [comment]
"You have the latest stable version" doesn't ring any bells?
Also this repo contains luma itself, not luma updater, which is project of another developer.

**Comment by ghost** [comment]
so then I guess it's normal. I thought for some reason you could do other things with Luma. I guess it wasn't through this
