### ISSUE TITLE
Hurry up with this one plz

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1518]
Hurry up with (this one)[https://github.com/LumaTeam/Luma3DS/issues/1501].

**Comment by ihaveamac** [comment]
You don't need to create duplicate issues like this.

**Comment by profi200** [comment]
@dwain12435 
I guess someone has to say it. You will get nothing done faster with that entitlement and rude tone. If you can't be friendly like 99% of the other people then don't open issues or you will end up blocked everywhere.
