### ISSUE TITLE
Auto-create folder structure the first time Luma3DS loads (or when saving config)

### ISSUE THREAD

**Issue by alvgalrus** [LumaTeam/Luma3DS#152]
Today I forgot to move /luma folder to SD, everytime I launched Luma3DS, the config appeared and I didn't see Emu at Settings afterwards.

I strongly suggest recreating the /luma folder structure automatically the first time it boots, in case the user forgot it, as it's empty by default.

**Comment by TuxSH** [comment]
Afaik recent commits are doing that.

**Comment by alvgalrus** [comment]
I was using 5.5 stable. Since stable builds are usually the first installed and this is awfully outdated I couldn't know. This should've already been updated long time ago.

**Comment by TuxSH** [comment]
I know.
