### ISSUE TITLE
Minecraft 3ds local multiplayer stops working 

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1522]
System model:

New 3DS XL

SysNAND version (+emu/redNAND version if applicable):

Sys 11.13.0-45U

Entrypoint (How/what you're using to boot Luma3DS):

B9S

Luma3DS version:

v10.2.1 Stable

Luma3DS configuration/options:

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Before)

Splash duration: (5)

PIN lock: (Off)

New 3DS CPU: (Clock + L2)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: ( x

Show GBA boot screen in patched AGB_FIRM: (x)

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: (x)

--

Explanation of the issue:

I added Luma3ds and the local multiplayer for Minecraft stopped working.

Steps to reproduce:

Open Minecraft for the 3ds.
Go to multiplayer
Host game
Open new 3ds and follow previous steps except now join
Refresh, and no servers will be found.

Dump file:
None

**Comment by ghost** [comment]
Minecraft for the 3ds does not have download play

**Comment by ghost** [comment]
I meant local multiplayer

**Comment by AuroraWright** [comment]
Could you contact me on Discord at Aurora Wright#9538 ? This is a bit difficult to test because two New 3DSes are required

**Comment by ghost** [comment]
I tried to contact you but I can only do that from discord if I am friended so I sent a friend request. You can delete me right after if you want. @AuroraWright 
<img width="1048" alt="Screen Shot 2020-12-01 at 8 18 21 AM" src="https://user-images.githubusercontent.com/74627744/100752111-c9077500-33ad-11eb-97ed-ecad14a33d9d.png">

**Comment by ghost** [comment]
I tested this on the latest USA Minecraft version (1.9) with Luma3DS v10.2.1-3gxldr on both consoles and multiplayer worked perfectly fine.

**Comment by ghost** [comment]
Hmmmmm, thats weird. Although, your consoles are not on v10.2.1 stable. It also was not working before v10.2.1. I have also had trouble with download play and wireless multiplayer not working on other games.
