### ISSUE TITLE
3ds crash after official update 

### ISSUE THREAD

**Issue by marcs7** [LumaTeam/Luma3DS#1523]
After update my n3ds to 11.14.0-46E when booting it crashes, is there any way to resolve this problem ?

**Comment by Shadow322** [comment]
> After update my n3ds to 11.14.0-46E when booting it crashes, is there any way to resolve this problem ?

U this blind?

**Comment by marcs7** [comment]
> > After update my n3ds to 11.14.0-46E when booting it crashes, is there any way to resolve this problem ?
> 
> U this blind?

why ?
it has installed luma3ds and i update it, i'm asking if is a solution to fix this

**Comment by regulad** [comment]
update to newest luma 10.2.1 
just read the changelogs man

**Comment by marcs7** [comment]
> update to newest luma 10.2.1
> just read the changelogs man

yes i did it, i found the solution in discord homebrew server, update it manually and it worked

**Comment by CatsLover2006** [comment]
could you close this issue?

**Comment by Cota-820** [comment]
I can see this community is really nice.
