### ISSUE TITLE
Region free DLP not working right(?)

### ISSUE THREAD

**Issue by techmuse8** [LumaTeam/Luma3DS#1525]
Decided to try Region Free DLP. My New 3DS XL Sys 11.14.0-46U I’m using as the host console, my Old 3DS Emu 11.14.0-46J, while the Old console can detect the host, it says the client needs to be on 11.14.0-46J which it is. Is it supposed to work by having both consoles being the same region and the host sending foreign content? Thanks in advance. Probably this could be worked around by spoofing firmware stuff?

**Comment by ghost** [comment]
Are you using the newest Luma download? In the features that is one of the fixes.

**Comment by techmuse8** [comment]
Yes, I am.

**Comment by mooseyacky** [comment]
ok

**Comment by mooseyacky** [comment]
thats weird

**Comment by ghost** [comment]
Maybe because you are using an emulator? Try on some unhacked 3ds'. Also, what game is it?

**Comment by mooseyacky** [comment]
Try on some regular 3ds's
