### ISSUE TITLE
Old Issue

### ISSUE THREAD

**Issue by andry6703** [LumaTeam/Luma3DS#1527]
oold

**Comment by hifinerd** [comment]
Try using a fresh boot.firm. The newest Luma3ds is designed with 11.14 in mind.

**Comment by xch25** [comment]
> Try using a fresh boot.firm. The newest Luma3ds is designed with 11.14 in mind.

How can I do this?

**Comment by Shadow322** [comment]
> > Try using a fresh boot.firm. The newest Luma3ds is designed with 11.14 in mind.
> 
> How can I do this?

By replacing it

**Comment by Dimensional** [comment]
I think it's safe to assume this guy is probably using a n3DS and doesn't know how to remove the mSD card from it to connect it to his PC and from there replace the file.

**Comment by SirEnder125** [comment]
I think that you may need to manually install the .firm
with gm9 > [0:] SD Card > .firm file > FIRM options > Install Firm > Both

**Comment by SirEnder125** [comment]
Oh, that is if your mind works enough to
boot into luma chainloader and install gm9.
(Lol jk, who doesn't)

**Comment by GlazedBelmont** [comment]
That's definitely not the best thing to do, also this issue is a month old. (OG comment was removed)
