### ISSUE TITLE
Load alternate CIAs/Home Menus on boot

### ISSUE THREAD

**Issue by hifinerd** [LumaTeam/Luma3DS#1528]
It would be cool to see an option to run a specific app when booting Luma3ds, so you can load an alternate Home Menu alongside the regular one.

**Comment by ghost** [comment]
There is an app for this

**Comment by hifinerd** [comment]
@mooseyacky What is it called?

**Comment by SirEnder125** [comment]
Sounds cool, what IS it called?

**Comment by urherenow** [comment]
Perhaps he's alluding to Sunshell... (or being a smartass and referring to emunand)

**Comment by ghost** [comment]
@hifinerd 3dsbank. To get it here is the link: https://gbatemp.net/threads/release-3dsbank-nintendo-3ds-folder-selector.516996/

**Comment by NightScript370** [comment]
@mooseyacky That's unrelated. He wants to boot into another application on boot, not have separate banks for the home menu.

**Comment by ghost** [comment]
@NightYoshi370 Read the title, "Load Alternate Home Menus on Boot"

**Comment by NightScript370** [comment]
And you should read the actual post: "It would be cool to see an option to run a specific app when booting Luma3ds"

Also, he probably means something like the Homebrew Launcher or TWiLight Menu++ when he says "Alternative Home Menus"

**Comment by ghost** [comment]
@NightYoshi370 Then they can add new startup boot combos to load apps during boot like Homebrew Launcher, 3DSBANK, or TWiLight Menu++ or a custom app so that they don't have to wait.

**Comment by moldimolt** [comment]
Duplicate: #1582
