### ISSUE TITLE
Can't Play DSiWare Games

### ISSUE THREAD

**Issue by Thewanildo** [LumaTeam/Luma3DS#153]
I don't use any kind of bootloader and I still can't play DSiWare games.

**Comment by astronautlevel2** [comment]
Can you provide more details?

Are you on the latest stable? If not, which commit are you on?

Are you on the regular or developer branch?

**Comment by Thewanildo** [comment]
I'm on the latest stable version and I also have a9lh installed.
I can play any Virtual Console game normally and any 3ds game without a single problem.

**Comment by Mrrraou** [comment]
Are you using the arm9loaderhax.bin ? Is the path patched, if it's not on the root on the SD card and called "arm9loaderhax.bin" ?

**Comment by MelonGx** [comment]
Have you read the whole wiki even the troubleshooting page?

You should know Luma conflicts TWL/AGB patches.
It is highly recommended that TWL/AGB patches should be removed if you use Luma.

**Comment by Thewanildo** [comment]
I don't use TWL/AGB patches.
PS: I don't know what I did but instead of getting the error message now I get a black screen.

**Comment by MelonGx** [comment]
Then some simple questions:
1) SysNAND or EmuNAND? TWL/AGB is not supported for unlinked EmuNAND.
2) Same Region? It may be the problem if you play out-of-region TWL/AGB.

**Comment by urherenow** [comment]
Thought TWL region patches were taken care of ages ago. You sure about that @MelonGx?

**Comment by Thewanildo** [comment]
Unlinked RedNand and I thought that Luma was Region Free.

**Comment by Margen67** [comment]
Why are you using Rednand?

**Comment by Thewanildo** [comment]
Because the tutorial I followed told me to :v
Edit: Here's the tutorial [link](https://github.com/Plailect/Guide/wiki/Part-3-%28RedNAND%29)

**Comment by Margen67** [comment]
If you already have A9LH you should switch to updated SysNAND

**Comment by AuroraWright** [comment]
You can't play DSiWare from emuNAND unless you have them on both NANDs
