### ISSUE TITLE
Errdisp

### ISSUE THREAD

**Issue by milotusauto** [LumaTeam/Luma3DS#1530]
System model:

[New 3DS XL]

SysNAND version (+emu/redNAND version if applicable):

[11.14.0-46U SysNAND]

Entrypoint (How/what you're using to boot Luma3DS):

[Boot9Strap]

Luma3DS version:

[v10.2.1 stable]

Luma3DS configuration/options:

Default EmuNAND: ( )

Screen brightness: 4(x)

Splash: Off(x)

Splash duration: 1(x)

PIN lock: Off(x)

New 3DS CPU: Off(x)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

Explanation of the issue:
When playing MHGen, sometimes I get Errdisp on loading screen.

**Steps to reproduce:**

1. Play MHGen

2. Go to new area to trigger loading screen
![IMG_20201120_071020](https://user-images.githubusercontent.com/74740806/99736821-ff1d3d00-2b01-11eb-99a4-7cc01b2688b0.jpg)

Dump file:
Did not provide dump file

**Comment by oreo639** [comment]
The save data for the game is probably corrupted.
https://zoogie.github.io/error/?d900458b

**Comment by milotusauto** [comment]
> The save data for the game is probably corrupted.

That explains why I kept getting error "The archive could not be opened. 0xC8804497" when i try to save data on JKSM. Is there any way to fix this? It is a cartridge game.

**Comment by oreo639** [comment]
MHGen doesn't put it's save data in the "save data" section, it puts it in the "extra data" section. You would probably need to delete the extra data for the game.

**Comment by milotusauto** [comment]
>You would probably need to delete the extra data for the game.


Deleting the extra data worked for a while then the problem returned. I realized the SD card was the one causing the corruption, so I changed it and now it works perfectly. Thanks for the help!

**Comment by milotusauto** [comment]
It came back...

**Comment by milotusauto** [comment]
Turns out the cartridge was defective.
