### ISSUE TITLE
Problem with Smash

### ISSUE THREAD

**Issue by Zetonium** [LumaTeam/Luma3DS#1531]
Model: New 3DS XL 
Region: US
Problem: This might not be very descriptive but every time I launch smash I get this error 
Processor: Arm11 (core 0) 
Exception Type: data abort
Fault Status: Permission - Section
Current process: ctrapp (00040000000EDF00

![20201119_174453](https://user-images.githubusercontent.com/74768219/99788591-8c4e9a80-2ade-11eb-916c-69516255076b.jpg)

Dump I cannot link because I am on mobile but ask me in the comments and I'll post it.

Keep in mind this happened a few weeks ago randomly and also I don't care about my save because I got this game on October 18th so I don't really care if a method deletes my save

**Comment by AuroraWright** [comment]
Does the folder luma\titles\0004000000EDF00 exist on SD and if so what's inside it?

**Comment by Zetonium** [comment]
code.ips

**Comment by ghost** [comment]
Try re-downloading or re-dumping Super Smash Bros. If it still doesn't work, then make sure your SD Card isn't corrupt via h2testw (ask @TurdPooCharger on GBAtemp for a tutorial).

**Comment by AuroraWright** [comment]
@Zetonium Delete the file and try again

**Comment by Zetonium** [comment]
THANKS SO MUCH IT WORKED AND MY SAVE IS STILL INTACT
