### ISSUE TITLE
game cards dont read on testkits

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1533]
game cards dont read on testkits

**Comment by AuroraWright** [comment]
Does it only happen when Luma is run or does it also happen on stock?

**Comment by ghost** [comment]
stock and luma
nds games will read just fine
3ds nope

**Comment by AuroraWright** [comment]
Then why are you reporting it as a Luma bug?

**Comment by ghost** [comment]
luma shuld allow for region free loading so it shuld be able to load games not signed in debug format

**Comment by TuxSH** [comment]
>  region free

It already does

**Comment by VilcsiTH** [comment]
> 
> 
> > region free
> 
> It already does

As far as I can tell, that's why the issue was opened. Luma's region free loading doesn't work in this scenario for some reason.
