### ISSUE TITLE
Problema con spotpass

### ISSUE THREAD

**Issue by Jose123456789007654** [LumaTeam/Luma3DS#1536]
Hola yo tengo otro problema, no tiene que ver con esto pero espero que alguien me pueda ayudar. Esto me pasa en animal crossing, pero creo que es un problema general de spotpass causado al hackeo.
Cuando quiero entrar al pueblo me pone si quiero activar spotpass, le doy que si y me pone: "para usar spotpass debes aceptar la última versión del contrato de uso de los servicios de nintendo 3DS. En la configuración de de la consola, elige Configuración de internet y selecciona información adicional. Una vez allí, toca contrato de uso y acéptalo para poder usar Spotpass"
Todo eso lo hice, pero cuando entro al contrato solo puedo leerlo, no aceptarlo, espero que alguien me ayude.

**Comment by AuroraWright** [comment]
You are using an out of region cartridge or pirated game (hopefully the former as piracy is not supported). Accepting the EULA for the game's region will fix the issue: https://github.com/noirscape/dses/releases/tag/v1.1 . Anyway not Luma's issue.
