### ISSUE TITLE
An exception occurred ARM11 (core 1) / Exception type: undefined instruction / I need help!

### ISSUE THREAD

**Issue by davidgd72k** [LumaTeam/Luma3DS#1537]
Hi, I have a problem with booting my 3DS, I hope somebody can fix this problem.
I have a **Old 3DS (EUR)** with **Luma3DS v10.0.1** (now I can't know the SysNAND version, sorry). The console using Boot9Strap.

About the origin of the error, I don't know very much what could have happened, I only know that after playing a little bit of a game, the next day the error started to occurred the error.

So, every time I power on the console, I get this on the screen:

**An exception ocurred**

Processor: ARM11 (core 1)
Exception type: undefined instruction
Current process: pm (0000000000000000)

Attach a picture with more info (sorry for low light level):

![An exception occurred screen](https://user-images.githubusercontent.com/59517993/100480139-ac8ae480-30f0-11eb-903b-a62910fd9430.jpg)

More interesting info:

**Luma3DS configuration/options:**
Screen brightness: 4(X)
Splash: Off(X)
Splash duration: 1(X)
PIN lock: Off(X)

Enable loading external FIRMs and modules: ( )
Enable game patching: ( )
Show NAND or user string in System Settings: (X)
Show GBA boot screen in patched AGB_FIRM: ( )
Set developer UNITINFO: ( )
Disable Arm11 exception handlers: ( )

**Dump file:**
[crash_dump_file.zip](https://github.com/LumaTeam/Luma3DS/files/5609379/crash_dump_file.zip)

I try with other ways but nothing :(

By beforehand, thanks.

**Comment by davidgd72k** [comment]
P.D.: the error screen appears with the SD card inserted and also without the SD card inserted.
And I don't have a Nintendo 3DS cartridge inserted in the console.

**Comment by profi200** [comment]
Update to the latest Luma version manually (replace boot.firm on the root of the SD card). The newest update broke older versions of Luma.

**Comment by MicrolemurDev** [comment]
I also has this issue and I can confirm that profi200's response does work on the New 2DS XL. Kudos to him/her!

**Comment by davidgd72k** [comment]
I finally solved the problem by doing what say profi200; replace old Luma3DS files for updated Luma3DS files on the root of my SD Card.
For now my 3DS works well, nothing bad I've seen.

Thanks for all.

**Comment by TechManPrieto** [comment]
My friend has experienced this issue and replaced the files, and it seems to work fine now. Well, I am going to archive this as a point of reference in the future.

**Comment by iRon185** [comment]
Replacing the Luma files fixed three New 2DXLs so I copied the files to an Old 3DS as well, for good measure!

**Comment by TechManPrieto** [comment]
> Replacing the Luma files fixed three New 2DXLs so I copied the files to an Old 3DS as well, for good measure!

I replaced them on my old 3DS XL and my friend did as well on his old 3DS. We got them at launch... geez that was long ago.

**Comment by rays** [comment]
Updated the files and rebooted to the same error. If I ask GodMode9 to boot the firmware it loads. Is there a step I'm missing to getting the device to boot

Update: Also tried 'Setup Luma3DS to CTRNAND` to no better effect

**Comment by CringyCraze** [comment]
Well I was told to delete all of my files from my SD card before I saw this, but now I don't know if I will ever be able to update luma and fix the DS

**Comment by Shadow322** [comment]
> Well I was told to delete all of my files from my SD card before I saw this, but now I don't know if I will ever be able to update luma and fix the DS

ROTFLMAO why the hell told u to do that?

**Comment by iRon185** [comment]
> > Well I was told to delete all of my files from my SD card before I saw this, but now I don't know if I will ever be able to update luma and fix the DS
> 
> ROTFLMAO why the hell told u to do that?

I hope no one tells him about the Windows\System32 folder

**Comment by CringyCraze** [comment]
I can still access my Godmode menu is there anything I can do with that?

**Comment by Neo564** [comment]
Hi guys, I have the same problem, but switching the update files didn't do anything.
I formatted my SD Card too, thinking it would help.
Does someone know how to fix this ?

I'm greatful for your ideas :)

**Comment by whiskyfly** [comment]
I have a new 2dsxl and I have the same problem, but switching the update files didn't do anything.
I'm greatful for ideas too!

**Comment by AbhorRend** [comment]
This happened to me after an update on my 3DS. I tried updating Luma, but not too sure if what im doing is right, as my screen never changes

**Comment by oreo639** [comment]
You need to download the zip from https://github.com/LumaTeam/Luma3DS/releases/latest then copy the boot.firm to the root of your sd card. If there is already a boot.firm, delete it.

**Comment by AbhorRend** [comment]
> You need to download the zip from https://github.com/LumaTeam/Luma3DS/releases/latest then copy the boot.firm to the root of your sd card. If there is already a boot.firm, delete it.

Thank you so much. I did this before but must've used the wrong files, cuz it worked with those. Appreciate the help

**Comment by whiskyfly** [comment]
For everyone who is unsuccessful, test with a smaller micro sd. That way it worked.

**Comment by chimpisbadwithcomputers** [comment]
> Update to the latest Luma version manually (replace boot.firm on the root of the SD card). The newest update broke older versions of Luma.

My name is completely correct how the heck do I do that?

**Comment by iansquenet** [comment]
Also have the same problem as Neo564, but I haven't formatted my SD card yet.

**Comment by tcslk** [comment]
> > Update to the latest Luma version manually (replace boot.firm on the root of the SD card). The newest update broke older versions of Luma.
> 
> My name is completely correct how the heck do I do that?

@chimpisbadwithcomputers 

Ok so try downloading this zip: 

https://github.com/LumaTeam/Luma3DS/releases/download/v10.2.1/Luma3DSv10.2.1.zip

And copy the two files (boot.firm and boot.3dsx) from the zip to the root of your SD card (not in any folders in the SD card) and put the SD card back in the 3ds and try that.

**Comment by kylemart** [comment]
Wanted to share my own findings. In addition to updating the boot.firm and boot.3dsx files like other have suggested, I also needed to update GodMode9 to get the [START]+[POWER] combo working again, and re-run the CTRNAND setup script to regain the option of launching my N3DS without an SD card.

**Comment by LursoPolar** [comment]
I did the same with my 3ds, but for some reason it's not updating the luma, it keeps on 10.0.1 and not the actual. even though i did the same process, downloading the last lumavers. and copy and paste on the root of the sd... what can i do?

**Comment by ghost** [comment]
@profi200  at first i was a bit lost but finally it worked! thank you so much!

**Comment by mcradcliffe2490** [comment]
I replaced both files with the new Luma v10.2.1 ones and no dice. System still crashes. Working on an original 3ds. Anyone got any advice?

**Comment by mcradcliffe2490** [comment]
> I replaced both files with the new Luma v10.2.1 ones and no dice. System still crashes. Working on an original 3ds. Anyone got any advice?

Nevermind I'm a goofball. The SD card wasn't formatted properly. The fix in this comment section works.

**Comment by EnderBossGT** [comment]
Im using the latest firm but i still get that error when i launch dragon quest stories. Btw im on a NEW 3ds XL.

**Comment by mcradcliffe2490** [comment]
@EnderBossGT Specifically only dragon quest stories? Have you tried uninstalling the rom after updating luma and trying again?

**Comment by bianca199864** [comment]
I have a Nintendo 2DS that has an exception occurred and I don't know how to get off my screen I need help

**Comment by d8958101** [comment]
thx a lot, problem solved.

**Comment by SepticRedhead** [comment]
Mine says Arm11 core1 exception type undefined instruc process loader 
![Uploading 16335764113783386945249797211146.jpg…]()
0000000000000000

**Comment by SepticRedhead** [comment]
Mine says Arm11 core1 exception type undefined instruc process loader 
![Uploading 16335764113783386945249797211146.jpg…]()
0000000000000000

**Comment by thhreaper72806** [comment]
hey i need help i have this problem to and i cant get it to work i tried updating the file but it wont work pls help i have the new 3d
![20211201_215247](https://user-images.githubusercontent.com/75951232/144349389-7dc0769f-df32-4149-adcf-bb4223da07d8.jpg)
![20211201_215246](https://user-images.githubusercontent.com/75951232/144349396-9cb1cd7c-cecd-40ed-a2b6-a72b65a9737a.jpg)
s

**Comment by mcradcliffe2490** [comment]
@thhreaper72806 did you use the guide specific to the new 3ds when installing luma?

**Comment by thhreaper72806** [comment]
yes

**Comment by thhreaper72806** [comment]
ive had my 3ds for a like a year homebrewed

**Comment by mcradcliffe2490** [comment]
@thhreaper72806 did you recently do a system update on your 3ds?

**Comment by thhreaper72806** [comment]
yes but nothing was wrong after the update i updated the firmware and was fine

**Comment by mcradcliffe2490** [comment]
@thhreaper72806 Did you update luma before you did the system update?

**Comment by thhreaper72806** [comment]
after and it was working btw if you have discord that would make this much easier

**Comment by mcradcliffe2490** [comment]
I'm not an expert but I've been using homebrew for a while, you can hit my disc and we can see if the issue can be sorted out BigPapiKite#2836

**Comment by thhreaper72806** [comment]
ok it is sent accept the friend request and we can vc thx for staying with me this far

**Comment by bryan24G** [comment]
thank you this was an easy fix.

**Comment by WilburNoot69** [comment]
> Update to the latest Luma version manually (replace boot.firm on the root of the SD card). The newest update broke older versions of Luma.

it never worked for me?? i replaced the boot.firm file and the boot.3dsx file. it hasn't worked? I've got the exact same issue :((

**Comment by Liliaimilk** [comment]
> Update to the latest Luma version manually (replace boot.firm on the root of the SD card). The newest update broke older versions of Luma.

wow,I did it😊

**Comment by getapples** [comment]
I'm a little late but I have replaced the boot.firm 3 times and nothing has happened. My 2ds is still stuck on the Arm11 error screen. Anyone know what I should do?

**Comment by urherenow** [comment]
You should jump on Discord or gbatemp. This isn’t really a help forum.

**Comment by Shokamii** [comment]
> Update to the latest Luma version manually (replace boot.firm on the root of the SD card). The newest update broke older versions of Luma.

Godspeed to this unknown hero

**Comment by Dangisuckathomebrew** [comment]
I’m struggling with this also, though my console still functions. I was too excited when hacking it and didn’t eject my sd card even once and after I put it into the console it wouldn’t read it. After putting it back onto my laptop it said I had to format it. Whenever I try to open the homebrew launcher by opening download play I get this error. Is this possible to fix? Thanks

**Comment by Zushikina-kun** [comment]
**The FIX for ARM11 Core 1 Error on 3DS** (While Loading External Storage Firms and Modules is checked or turned on)

If you've tried everything suggested here and you're still getting the ARM11 Core 1 error, here's something else you can try that worked for me:

**Back-Up and Delete Your luma/titles Folder:**

Backup the luma/titles folder on your SD card (just in case).
Delete the luma/titles folder from the SD card.
This folder isn't critical to the system itself, so deleting it won't break anything important. It typically contains custom patches, cheats, mods, or region-free patches for specific games or the system. If you're using any of those, you can easily re-download and set them up again later.
Don't worry—your save data will remain safe.

**Why This Works:**

The error is often caused by a corrupted external storage firm or module in the luma/titles folder (or possibly in luma/modules, though the latter may not exist on all setups). I don’t know the exact cause of the corruption, but removing this folder resolved the issue for me.

**My Experience:**

Initially, unchecking "Enable loading external storage firms and modules" in the Luma3DS settings made my 3DS work again, but I couldn’t access Pretendo servers with that setting off.
After researching online and brainstorming with ChatGPT, I finally found that deleting the luma/titles folder fixed the problem without needing to disable external storage firms and modules.

**Comment by Masamune3210** [comment]
......you know what the problem with using LLM's to do your homework for you is? About half of that is wrong. 

You don't need to use GPT to follow instructions, one of the first troubleshooting steps for almost anything modding related is to back up the sd card, wipe it, and extract fresh copies of needed files

**Comment by Zushikina-kun** [comment]
STFU, It worked for me and this shit has been a problem for me for almost a
year now, there wasn't any guide that WORKED until I FRICKING just did this
one-by-one bullshit where I just move files one by one and just track which
folder is the problem, and NOT everyone knows how to troubleshoot like most
people here FFS, I JUST POSTED WHAT WORKED FOR ME so stop being a high and
mighty loser who thinks he KNOWS IT ALL.

**Comment by Masamune3210** [comment]
No. I don't think I will. 

Still doesn't stop half of that being some variant of incorrect. Turns out a random chat model being abused into doing something it was never designed to do doesn't know shite. Who would have thought.

**Comment by Nemris** [comment]
Masamune is right on the money. It's not like LLMs existing means we can turn off our brains.

@TuxSH Perhaps this issue should be locked at this point? Looks like it got derailed quite a bit over the years.

**Comment by Alkaloon72** [comment]
Having the "and exception occurred" error on my old 3ds, anyone have ideas? 
![Uploading 17325920896156797191630401975698.jpg…]()

**Comment by Alkaloon72** [comment]
It seems updating Luma WITHOUT updating the "luma" folder or the "boot strap" folder fixed this issue
