### ISSUE TITLE
Can't boot into Luma3ds / Rednand

### ISSUE THREAD

**Issue by walshie88** [LumaTeam/Luma3DS#154]
hey guys,

I'm up to step 24 in https://github.com/Plailect/Guide/wiki/Part-3-(RedNAND).

When I try to start Luma3DS, i just get a black screen. It was working before this step.

**Comment by Shadow322** [comment]
This isn't a help place take it to gbatemp forums

**Comment by walshie88** [comment]
sorry mate 
will do
