### ISSUE TITLE
luma wont update

### ISSUE THREAD

**Issue by ki-krpto** [LumaTeam/Luma3DS#1545]
i got the 10.2.1 files but luma wont update and don't know why and im doing it manually
Help?

**Comment by Shazer51** [comment]
im having the same issue

**Comment by ghost** [comment]
You have to copy the "boot.firm" file from the Luma3DS archive to the root of the SD Card and overwrite the already existing one.

**Comment by ki-krpto** [comment]
that did not work but i will take a picture 
here you go
![IMG_20201204_175609](https://user-images.githubusercontent.com/75393241/101230433-21629f00-365a-11eb-8f4d-682f2f810ce2.jpg)
![IMG_20201204_175618](https://user-images.githubusercontent.com/75393241/101230437-258ebc80-365a-11eb-9f87-2c318cf4b3e6.jpg)
sorry if its blurry

just in case


arm 11 (core 1)
exception type undefined instrution
current process pm (0000000000000000)
R0 EOEO1BF5   R1 00000000
R2 00000000   R3 00000000
R4 00001000   R5 00000017
R6 FFFFFFFE R7 00000000
R8 00000000   R9 00000000
R10 00000000 R11 00000000 
LR 00100D2C  PC 00100CB4
CPSR A0000010  FPEXC 00000000
press a to save the crash dump
press any other button to shutdown (does not work)


stack dump:
0FFFFFD8: 00 10 00 6C 0E 10 00
0FFFFFEO : 00 00 00 00 00 00 00 00
0FFFFFE8: FF FF FF FF 50 0E 10 00
OFFFFFF0 00 00 00 00 00 00 00 00
0FFFFFF8: 00 00 00 00 CC 0D 10 00

**Comment by TuxSH** [comment]
Drag and drop boot.firm onto the root of the SD card, replacing the existing file.

When you press Select at boot, does it say it's been booted from SD card (yellow text bottom-left corner bottom screen)
