### ISSUE TITLE
open_agb_firm Issue

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1547]
Luma3DS v10.2.1 can't launch open_agb_firm through the chainloader, but it can be launched via GodMode9.

**Comment by profi200** [comment]
Use the newest alpha build (of oaf). There is a workaround in place. The builds are in the release section.

**Comment by TuxSH** [comment]
I need to rewrite the launcher/baremetal code, but I don't have the time to do that now.

**Comment by profi200** [comment]
Just for the record: This is issue #1396.
