### ISSUE TITLE
luma 3ds won't show open button for games/apps?

### ISSUE THREAD

**Issue by sketchy1** [LumaTeam/Luma3DS#155]
Can someone help me with luma? 
My emunand crashed saying the sdcard has been removed, and when I booted emunand again the open button at the bottom of the screen was gone, so now I cant open any games in emunand running 9.2 sysnand 10.1 emunand . also cant press the a button to open anything and double tapping an app in the touch screen would cause it to freeze

**Comment by james-d-elliott** [comment]
Can attempt moving all of the folders out of the Nintendo DS folder on your SD card, this has fixed similar issues for me before. You should move them back if it doesn't work.

**Comment by dogtopus** [comment]
roxas75/rxTools#475
Well, I don't think your problem was CFW-related. You probably need to ask someone else for help.

**Comment by Margen67** [comment]
> emunand

Well there's your problem
