### ISSUE TITLE
[Rosalina Feature Request] Add option to go into sleep mode from Rosalina menu

### ISSUE THREAD

**Issue by onigari** [LumaTeam/Luma3DS#1551]
I see the 'Power off' and 'Reboot' options in the Rosalina menu but is it possible to add an option to manually put the system to sleep mode?

**Comment by SirEnder125** [comment]
Not to be rude, but, I do not see a point for the developers to add a function that
can be called upon in an VERY easy way by pushing a switch. Oh, wait,
I do not own a 3ds. A 2ds. Do the not have sleep mode? Of course they
do, it is just enabled by folding the 3ds with those (flimsy) hinges.

**Comment by onigari** [comment]
> 
> 
> Not to be rude, but, I do not see a point for the developers to add a function that
> can be called upon in an VERY easy way by pushing a switch. Oh, wait,
> I do not own a 3ds. A 2ds. Do the not have sleep mode? Of course they
> do, it is just enabled by folding the 3ds with those (flimsy) hinges.

I realize what you are saying but unfortunately my 3ds shuts down when folded, it can be kept on only in the right-angle kind of position. And I have seen this happen to a few other people with 3ds too.

**Comment by lividhen** [comment]
You could get a small magnet and place it just to the right and upish from the X button.

**Comment by onigari** [comment]
> 
> 
> You could get a small magnet and place it just to the right and upish from the X button.

Yeah but then it shuts down when lifting the lid
