### ISSUE TITLE
[Rosalina Feature Request] Add Option to Return to HomeScreen or Homebrew Channel

### ISSUE THREAD

**Issue by MarioKartFan** [LumaTeam/Luma3DS#1554]
Sometimes homebrew will hang and the system will no longer respond to the HomeKey. Nevertheless, the Rosalina menu can still be pulled up and used to reset the system. It would be amazing if we could use it to “Quit” the current program and return to either the HomeScreen or the HomeBrew Channel!

**Comment by ghost** [comment]
I agree, that would be very very useful!

**Comment by T0biasCZe** [comment]
also add "reset" button which will reset the game or homebrew would be great =) 
(like the physical reset button on wii, gc, n64, snes and nes but digital)

**Comment by MarioKartFan** [comment]
That would be incredible.

**Comment by DullPointer** [comment]
I did a little bit of experimentation trying to terminate hanging apps (ModMoon and "Portal 3DS") using [NS_TerminateProcessTID](https://libctru.devkitpro.org/ns_8h.html#aa451e546d4aa3cb2692767f0a20c63c3), but I just found that it would either throw an arm11 exception or cause a pop-up that would force you to reboot the console anyway :/.

**Comment by ghost** [comment]
> I did a little bit of experimentation trying to terminate hanging apps (ModMoon and "Portal 3DS") using [NS_TerminateProcessTID](https://libctru.devkitpro.org/ns_8h.html#aa451e546d4aa3cb2692767f0a20c63c3), but I just found that it would either throw an arm11 exception or cause a pop-up that would force you to reboot the console anyway :/.

Try to terminate a non-hb title and see what happens, maybe?

**Comment by moldimolt** [comment]
Duplicate of #1516.
