### ISSUE TITLE
How to get to system update when installing Luma3DS?

### ISSUE THREAD

**Issue by astronaut1234** [LumaTeam/Luma3DS#1557]
I want to install Luma3DS, but there is no way i can get to system update without pressing a certain amount of keys, including my right shoulder button (which is broken.) Is there a way you can change the configuration?
Thanks

**Comment by NightScript370** [comment]
This is not related to Luma3DS. Nintendo would have to change the button combo to SAFE_FIRM.

Try a legacy method, like 3ds.hacks.guide says: https://3ds.hacks.guide/legacy-methods
