### ISSUE TITLE
Load payloads after splash screen

### ISSUE THREAD

**Issue by YodaDaCoda** [LumaTeam/Luma3DS#156]
There's a trend of having the bottom splash screen show which keys will launch which payloads (e.g. start - decrypt9). However, the key must be pressed and held before the splash loads.

Would it be possible to show the splash screen before attempting to load payloads?

**Comment by TuxSH** [comment]
Done (it's now implemented as an option).
3bc966f84e107914d4b29e4f55fec719bc5821bf

**Comment by YodaDaCoda** [comment]
@TuxSH thanks for implementing my suggestion. :)
