### ISSUE TITLE
Problems with frogminer

### ISSUE THREAD

**Issue by kippuro** [LumaTeam/Luma3DS#1562]
i updated the luma, and i got a problem. When i use the download mode in 3ds to enter the Homebrew, i ended in the frogminer menu, and it doesn't appear the button face i need to update, and i can't access to the homebrew menu. What can I do?

**Comment by lividhen** [comment]
Try replacing the boot.3dsx on the sdcard with the one from the luma release.
(if you haven't already figured this out...)
