### ISSUE TITLE
Kirby's Extra Epic Yarn keeps randomly crashing.

### ISSUE THREAD

**Issue by Yola-cola** [LumaTeam/Luma3DS#1565]
**System model:** New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** 11.14.0-46U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** 10.2.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (2)

Splash: (before payloads)

Splash duration: (3 sec)

PIN lock: (off)

New 3DS CPU: (off )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ()

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
When I have active cheats for Kirby's extra epic yarn it randomly crash. Usually on the title screen or after completing a game of hide and seek. it also happen without cheats it's just that it happens more frequency when cheats are enable.

**Steps to reproduce:**
1. Launch Kirby's extra epic yarn

2. Use a gateshark code
 
3. crash 

**Dump file:**
[KEEY CRASH DUMPS.zip](https://github.com/LumaTeam/Luma3DS/files/5776333/KEEY.CRASH.DUMPS.zip)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
