### ISSUE TITLE
Pokemon Gold crashing on boot

### ISSUE THREAD

**Issue by jat666** [LumaTeam/Luma3DS#1569]
**System model:**

Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** 9.4.0-21E

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:** 10.2.1

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4 )

Splash: (off )

Splash duration: (1 )

PIN lock: (off )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x )

Show NAND or user string in System Settings: (x )

Show GBA boot screen in patched AGB_FIRM: (x )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
Crashes on launch after a brief display of 3ds splash screen. Also crashes with GBA boot screen disabled.

**Steps to reproduce:**

1.

2.

**Dump file:** 
[crash_dump_00000006.zip](https://github.com/LumaTeam/Luma3DS/files/5818707/crash_dump_00000006.zip)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
