### ISSUE TITLE
2DS going sleep mode during gameplay

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1572]
I was playing Pokemon Omega Ruby and all of a sudden the game screen went black!
I thought the game crashed but then I saw the on signal blinking which happens while it is on sleep mode. The problem is I never switched it to sleep mode and it happens while playing game.
It might be a SD card malfunction but I hope you take this into account. Thnx.

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
