### ISSUE TITLE
Problem when forcing a connection

### ISSUE THREAD

**Issue by tsClauz** [LumaTeam/Luma3DS#1574]
I have an european old3ds xl on firmware 11.14
When I try to force a connection with Rosalina it doens't work, I need to switch off, and then switch on the wireless communication, and then it works

**Comment by oreo639** [comment]
> When I try to force a connection with Rosalina it doens't work

Wdym? How does it not work? What happens when you enable it? What are you expecting to happen when you enable it?

(Also, in the future, please use the issue template)

**Comment by tsClauz** [comment]
When i try to force the connection it says ''failed to connect'', then if I turn off and then on the wireless connection it says ''successfully connected''

**Comment by X7ox** [comment]
Odd, for me it often takes forever to force one but never fails. May mean that something may be wrong with a connection. I use a Wifi Save Editor that allows me to switch wifi slots on the fly without going to settings and performing a connection test.

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
