### ISSUE TITLE
Luma updater died

### ISSUE THREAD

**Issue by tsClauz** [LumaTeam/Luma3DS#1575]
Luma updater doesn't download the latest luma3ds also if connected to the internet

**Comment by oreo639** [comment]
This is not a Luma3DS issue.
Luma Updater is a separate project and not supported by Luma3DS.

**Comment by ghost** [comment]
> Luma updater doesn't download the latest luma3ds also if connected to the internet

They released a new update for the updater! Just thought you'd like to know
