### ISSUE TITLE
How can i launch Rosalina without my L button?

### ISSUE THREAD

**Issue by Woomy8** [LumaTeam/Luma3DS#1576]
I have an old 2ds and my L button is broken. how can i open the rosalina menu without it?

sorry for my english.

**Comment by oreo639** [comment]
You can change it using `Rosilina Menu > Misc. Options > Change the menu combo` then save the settings.
You can also generate a new config with your chosen combo here:
https://3ds.eiphax.tech/config.html

(The config goes in `/luma/config.bin` on your SD card)
