### ISSUE TITLE
Can't Install more than about 300 games.

### ISSUE THREAD

**Issue by wangdante** [LumaTeam/Luma3DS#1577]
I have 1TB TF card than want to install more games .
when I install more than 300 games ,the new game icon will overwrite oldgame icon

**Comment by Shadow322** [comment]
3DS bank

**Comment by wangdante** [comment]
3DS BANK,what does mean?

**Comment by Shadow322** [comment]
Google it

**Comment by wangdante** [comment]
sorry,I use google to search it,the results are “3D-Secure (3DS) of VISA card” or "pokemon bank".
There is no exact explanation from 3DS Bank.
Would you explain how to solve this problem? thank you

**Comment by Shadow322** [comment]
3ds bank

**Comment by wangdante** [comment]
yes,I search "3ds bank" in google.com,the resultes were all 3D-Secure,No results related to 3DS.
Would you give me a url? thank you.

**Comment by Shadow322** [comment]
It's one word 3dsbank

**Comment by wangdante** [comment]
thank you very much,
