### ISSUE TITLE
New 2Ds XL Crashes when trying load Miiverse / Nintendo eShop

### ISSUE THREAD

**Issue by NintendoPSproGS** [LumaTeam/Luma3DS#1578]
[crash_dump_00000003.zip](https://github.com/LumaTeam/Luma3DS/files/5867471/crash_dump_00000003.zip)

The crash happends when trying to load certain 3ds apps (like the two i said on the title) do you know how to fix it? Because i want to revive Miiverse

**Comment by X7ox** [comment]
Did you region change your device?

**Comment by NintendoPSproGS** [comment]
No, i didn't. The New 2DS Xl it's a EUR region. I think the problem is when it tries to load my Nintendo Network ID (Which i need to use to open miiverse)

**Comment by NintendoPSproGS** [comment]
Hello? I need help, please!

**Comment by urherenow** [comment]
GitHub is not a help forum. This space is for reporting real bugs, or making feature requests.

Nintendo discontinued miiverse nearly 4 years ago, so I don't even know what you expect there. Open a thread on gbatemp, or a discord channel.

**Comment by NintendoPSproGS** [comment]
> GitHub is not a help forum. This space is for reporting real bugs, or making feature requests.
> 
> Nintendo discontinued miiverse nearly 4 years ago, so I don't even know what you expect there. Open a thread on gbatemp, or a discord channel.

I mean that i was gonna use rverse to revive the miiverse services, but if i can't log in, how am i supposed to do it? And it's a real bug
