### ISSUE TITLE
am : u

### ISSUE THREAD

**Issue by Holmes-Agency** [LumaTeam/Luma3DS#158]
Legitimate issue this time. When downgrading to 9.2.0, I keep getting an error line that says

> FAIL
> 
> Can't get am : u service ... try again :x 

Are there fixes?

**Comment by pbanj** [comment]
few questions. why is this a luma issue? sounds like an issue with the downgrader youre using and what fw is your system on?

**Comment by Holmes-Agency** [comment]
@pbandj My bad, wrong thread
