### ISSUE TITLE
Possibility to add all ntr cfw features to luma (even the experimental save state feature) and the ntr streaming feature  so everything is available in one cfw?

### ISSUE THREAD

**Issue by linusrg1** [LumaTeam/Luma3DS#1583]

**Comment by ghost** [comment]
Would that take too much work or could it be an easy-ish cut/paste with a few bits of code (added in)?

**Comment by TuxSH** [comment]
Too much work and too much resources on the 3ds system, so no.

**Comment by linusrg1** [comment]
I completely agree with you, but I am just curious, why would it be heavier on the 3ds than running ntr and luma at the same time. (I don't really understand how things work under the hood tbh)

**Comment by ghost** [comment]
They closed it, LUMA won't respond prolly
Um, I wouldn't know. I'm not knowledgeable on hardware type stuff ig
