### ISSUE TITLE
Crash on start up 

### ISSUE THREAD

**Issue by canx35** [LumaTeam/Luma3DS#1584]
System model:

[New 3DS XL]

SysNAND version (+emu/redNAND version if applicable):

[e.g. 11.14.0-46E SysNAND]

Entrypoint (How/what you're using to boot Luma3DS):

[e.g. Boot9Strap/Sighax, etc.]

Luma3DS version:

[e.g. v10.2.1 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

Luma3DS configuration/options:

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

Explanation of the issue:

After booting my New 3ds XL will crash in this. I have tried anything but I dont know why it make it. ( I have bueyed it a defekt and have fix it)

Steps to reproduce:

Dump file:
![20210128_074433](https://user-images.githubusercontent.com/2721662/106219272-56621c80-61d9-11eb-89c4-4df86dc1fc03.jpg)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
