### ISSUE TITLE
Faint double image on left eye on incandescent filter

### ISSUE THREAD

**Issue by lividhen** [LumaTeam/Luma3DS#1587]
**System model:**

Old 3ds XL

**SysNAND version (+emu/redNAND version if applicable):**

11.14.0-46U

**Entrypoint (How/what you're using to boot Luma3DS):**

B9S

**Luma3DS version:**
v10.2.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (1 )

Splash: (after )

Splash duration: (1 )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X )

Show NAND or user string in System Settings: (X )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

If I change the screen filter to incandescent, there is a faint double image on the left eye for some reason... It doesn't seem to happen on any of the other levels

If it hasn't been noticed by now I could have some kind of minor hardware issue. The right hinge cracked, and epoxy was used to repair it, but that shouldn't affect anything unless the ribbon cable was damaged in some way... But I don't know why it would be that specific color range. 

**Steps to reproduce:**

1. Boot into luma3ds

2. Turn on 3d

3. Turn screen filter level to incandescent

**Comment by moldimolt** [comment]
This doesn't appear to be reproducible, so it may be a hardware issue on your device. If it occurs on another user's device, we will reopen this issue for further investigation.
