### ISSUE TITLE
Luma 6.0+ Dev still displays CtrBootManager's screenshot on first entering configuration

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#159]
This display error makes Luma configuration very difficult to be recognized.
This happens on Luma 6.0+ Dev + Menuhax + CtrBootManager. Don't know about Non-Dev + A9LH + CtrBootManager9.
This doesn't happen on 5.X (Dev).

**Comment by Mrrraou** [comment]
I would probably consider it as an issue with your chainloader, which should clear the screen before chainloading a payload

**Comment by TuxSH** [comment]
This shouldn't happen, Luma3DS clears the screen in all cases https://github.com/AuroraWright/Luma3DS/blob/developer/source/screen.c#L242

**Comment by Margen67** [comment]
> menuhax

Well there's your problem
