### ISSUE TITLE
How do we fix the Arm11 (core 0) (svcBreak)?

### ISSUE THREAD

**Issue by Smoreslickgores** [LumaTeam/Luma3DS#1590]
![IMG_20210205_094159](https://user-images.githubusercontent.com/78554373/107048103-8f306180-6796-11eb-8fdc-aaee69ba51a7.jpg)

I also have the Luma 3ds update as well It's the latest ver to v10 .2. 1

**Comment by TuxSH** [comment]
Are you using a custom theme?
