### ISSUE TITLE
Arm 11 (core 2) error. Exception type: data abort. Fault status: translation-section.

### ISSUE THREAD

**Issue by Cid125** [LumaTeam/Luma3DS#1591]
This error occurs every time I open Minecraft, right after the Mojang screen pops up.
I Have already tried:
Deleting the 0000008f folder.
Replacing the boot.firm file on my SD card
Deleting my save to see if it was corrupted
Reinstalling the .cia
Turning on "disable arm11 exception handlers" it did not solve the problem so I turned it back off
I own a North American New 3ds XL and I also saved the crash dump file if that helps anyone.

**Comment by Shadow322** [comment]
We don't support piracy so take it elsewhere

**Comment by Cid125** [comment]
Would you at least tell me if there are any risks or permanent damage that could be done to my 3DS?
