### ISSUE TITLE
[FEATURE REQUEST] Add fps and time overlays either to rosalina menu or top screen

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1594]
Like how @Nanquitas did it in his NTR CFW plugin (original by @44670 is archived) [https://github.com/Nanquitas/ntr_overlay_samples/](url)
I understand that I can just use the NTRboot app, but sometimes it's buggy, and I'd like the feature to be streamlined into luma cfw somehow, either in rosalina or possibly added onto the top screen, like in the original, it'd be a good quality-of-life addition.

**Comment by TuxSH** [comment]
This is game-dependent and would be too difficult to implement in a general fashion, not to mention opening the Rosalina menu pauses the active application/game.
