### ISSUE TITLE
Exception occurred arm11 core when using certain homebrew applications (NTRBootselector & GYTB)

### ISSUE THREAD

**Issue by Overkill77** [LumaTeam/Luma3DS#1597]
So whenever i select an NTR version i get this error, this also happens after i select a version. 

**Dump ↓**
[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/5991231/crash_dump_00000000.zip)

And with GYTB after it finishes applying the badges it instantly crashes with the same error. 

**And another dump ↓**
[crash_dump_00000001.zip](https://github.com/LumaTeam/Luma3DS/files/5991251/crash_dump_00000001.zip)

**Additional info:**
Im running the latest version of all 3

**Luma Config:**

**Screen brightness**: 4
**Splash**: After
**SplashDuration**: 5
**Pin lock**: Off
**New 3DS CPU**: Off

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
