### ISSUE TITLE
[Feature Request] Is it possible for luma3ds to add support for save states?

### ISSUE THREAD

**Issue by xpirad** [LumaTeam/Luma3DS#1598]
BootNTR CFW has this feature but it's very old and outdated.

Would it be possible for luma3ds to support this feature natively? Thanks!

**Comment by ghost** [comment]
I think they've said it would be hard to implement...but who knows, it may be added sometime!!

**Comment by xpirad** [comment]
> I think they've said it would be hard to implement...but who knows, it may be added sometime!!

I hope so!!

**Comment by TuxSH** [comment]
It's too hard/not worth the bother to add, because you would need to restore the entire OS and hardware state to do it _properly_ which is an insanely complex thing to do.

So, no.
