### ISSUE TITLE
Hello I get this when opening Alpha sapphire randomizer file Arm 11 core 1 SVC break 

### ISSUE THREAD

**Issue by wardy555** [LumaTeam/Luma3DS#1599]
Alpha sapphire randomizer file Arm 11 core 1 SVC break debug event
![IMG_20210221_145659](https://user-images.githubusercontent.com/79413433/108631560-6bda0780-7462-11eb-9ebe-7f2de325f5b0.jpg)

**Comment by wardy555** [comment]
![crash_dump_00000014](https://user-images.githubusercontent.com/79413433/108632879-0b01fd80-7469-11eb-8fa6-7fe90ae852ac.png)

**Comment by TuxSH** [comment]
Not enough details
