### ISSUE TITLE
[Suggestion] Possibility to update payloads

### ISSUE THREAD

**Issue by suzsuzuki** [LumaTeam/Luma3DS#160]
This is not an issue, but a suggestion. I think will be fine if there's a way to update the default payloads (Decrypt9, Hourglass9 and EmuNAND9) used in Plailect guide. Do you think it's possible?

EDIT: I also put this suggestion on LumaUpdater page

**Comment by cheatfreak47** [comment]
Yeah, this is something that'd be good for luma updater or some other updater program, but Luma3DS itself is just a CFW, it doesn't really even update itself, so this really isn't the right place for this issue.

**Comment by suzsuzuki** [comment]
Sorry, closing the issue
