### ISSUE TITLE
An error occurred (ErrDisp)

### ISSUE THREAD

**Issue by ras9256** [LumaTeam/Luma3DS#1601]
At first, the game runs fine, but after about 24 hours, I get this error code.  Is there any way to solve this problem?
![IMG_20210224_233414](https://user-images.githubusercontent.com/79588090/109015776-d4421680-76f8-11eb-8aa6-0bdfc55518b3.jpg)

**Comment by ghost** [comment]
Try reinstalling the CIA, if you downloaded it. Or try a different CIA, especially if you already legally own it.

**Comment by ras9256** [comment]
> CIA를 다운로드 한 경우 다시 설치해보십시오. 또는 특히 이미 합법적으로 소유하고있는 경우 다른 CIA를 사용해보십시오.
Oh I solved the problem.  The problem was just a bad sd card
