### ISSUE TITLE
Dragon Quest 8 Non-Functional

### ISSUE THREAD

**Issue by abrookst** [LumaTeam/Luma3DS#1603]
The feature of removing region locking for physical games is non-functional for Dragon Quest 8 (NTSC console, PAL game). Every single solution for this has not worked. I am on a n3DSXL ver. 11.14.0, Luma ver. 9.1

There is no option to import the seed, Luma Locale Switcher does not work (even with the correct locales directory), and manually making a txt file in Luma > titles did not work. The game boots up before saying "This title cannot be played without extra data." Before trying to create the extra data and failing a few seconds in citing "An error occurred while the SD card was being written to. Please turn off the system and re-insert the SD card."

**Comment by Shadow322** [comment]
> The feature of removing region locking for physical games is non-functional for Dragon Quest 8 (NTSC console, PAL game). Every single solution for this has not worked. I am on a n3DSXL ver. 11.14.0, Luma ver. 9.1
> 
> There is no option to import the seed, Luma Locale Switcher does not work (even with the correct locales directory), and manually making a txt file in Luma > titles did not work. The game boots up before saying "This title cannot be played without extra data." Before trying to create the extra data and failing a few seconds in citing "An error occurred while the SD card was being written to. Please turn off the system and re-insert the SD card."

Update your Luma3DS

**Comment by abrookst** [comment]
> Update your Luma3DS

I did that before all of this, and whenever I click on the updater all I get is "Could not obtain update details." and I'm on the internet

**Comment by Shadow322** [comment]
> > Update your Luma3DS
> 
> I did that before all of this, and whenever I click on the updater all I get is "Could not obtain update details." and I'm on the internet

https://github.com/LumaTeam/Luma3DS/releases/download/v10.2.1/Luma3DSv10.2.1.zip

Download this extract the file place boot.firm on root of SD card then boot your 3ds
