### ISSUE TITLE
Luma3DS won't update at all

### ISSUE THREAD

**Issue by LMFBO** [LumaTeam/Luma3DS#1606]
It's been a couple of years since I haven't touched my old 3DS XL and decided to start replaying some games recently. I have tried manually updating some of the applications I already had on there and it's been giving me issues, especially Luma3DS (tried to drag and replace the files I had with new ones). I'm also a noob at this so please bare with me. 

I have the latest version on my 3DS which is the 11.14.0-46U (I read that it was safe to update).
FBI is also updated and works with the latest version which is 2.6.0.

If I turn off my 3DS and hold select when I turn it back on this is what I get:

![IMG_2522](https://user-images.githubusercontent.com/29415564/110981601-5c4d3080-8335-11eb-8b1d-f35180b79a02.JPG)

When I try to launch Luma3DS this is the error that I get (before my 3DS restarts and takes me back to the home menu)

![IMG_2519](https://user-images.githubusercontent.com/29415564/110981297-f791d600-8334-11eb-8acc-7d250fd29cf2.JPG)

And because I don't have the latest version of Luma3DS, PKSM won't launch too.

![IMG_2521](https://user-images.githubusercontent.com/29415564/110981356-05475b80-8335-11eb-9833-8250ee598f19.JPG)

Homebrew Launcher won't launch too.

![IMG_2520](https://user-images.githubusercontent.com/29415564/110981375-0d070000-8335-11eb-900e-6dd710a716f8.JPG)

Any help would be greatly appreciated, thank you in advance.

**Comment by LMFBO** [comment]
I've tried following this youtube video: https://www.youtube.com/watch?v=FV0Qwr-5CI0&ab_channel=sthetix
Basically it just tells me to drag the .3dsx and .firm files to the root of my SD card but it doesn't update when I launch the Luma3DS configuration screen (still stuck at 7.1)

**Comment by urherenow** [comment]
If you're sure you put the latest files on your card (and the card/files aren't somehow read-only), then you likely used GodMode9 to install it to nand, and you're loading it from there.

Updater has nothing to do with Luma3ds. Luma3ds does not do that.

hblauncher_loader has nothing to do with Luma3ds either.

Your problems are yours and not Luma's, so you should probably close this and ask for help on the gbatemp forums. Or in discord.

**Comment by Jan200101** [comment]
[Luma Updater](https://github.com/KunoichiZ/lumaupdate) is a seperate project from Luma3DS
