### ISSUE TITLE
Stuck on performing preliminary operations when updating Luma3DS

### ISSUE THREAD

**Issue by Ins0rt** [LumaTeam/Luma3DS#1607]
despite i've installed the latest version of Luma it says that it's not the stable version and tries to download 10.2.1 which is already installed. However it does recognises the version i have installed as 10.2.1-c058e3f instead of 10.2.1. 

![image0](https://user-images.githubusercontent.com/80584937/111031906-f27c7600-845d-11eb-90e7-389c83b0c030.jpg)
![image1](https://user-images.githubusercontent.com/80584937/111031915-f90aed80-845d-11eb-9e9c-e9a05266091d.jpg)

and downloading via CTR-NAND just boots Luma to this screen

![image2](https://user-images.githubusercontent.com/80584937/111031942-193aac80-845e-11eb-96b2-c7262bc9b42c.jpg)

and if i try to get the backup it goes back to the first screen image i posted, if i try installing a stable version from here it still doesn't download the files causing an endless loop.

(should have stated this when i edited it, but i changed freezes to not cause any misconceptions)

**Comment by Jan200101** [comment]
[Luma Updater](https://github.com/KunoichiZ/lumaupdate) is a seperate project from Luma3DS
