### ISSUE TITLE
Even after I put boot.firm and boot.3dsx the console still has a crash dump

### ISSUE THREAD

**Issue by Eduacchio** [LumaTeam/Luma3DS#1608]
My 3ds still has a crash dump after I replace the boot.firm and boot.3dsx
![IMG_20210315_152848](https://user-images.githubusercontent.com/80701777/111179150-b2271000-85a3-11eb-96ba-0bf0a39097a7.jpg)

**Comment by TuxSH** [comment]
Press select a boot and read out what the boot source is, in yellow text on the bottom screen, bottom-left corner.

It looks like the 3DS may not be reading your SD card correctly and is using a old copy that's located on CTRNAND. That, or it has not been updated properly.
