### ISSUE TITLE
Input Redirection in DS Mode

### ISSUE THREAD

**Issue by zs2212221** [LumaTeam/Luma3DS#1609]
This is a pretty general question, but what would it take to implement input redirection when launching a game in DS mode? Is this even something at the Luma3DS-level?

**Comment by Shadow322** [comment]
> This is a pretty general question, but what would it take to implement input redirection when launching a game in DS mode? Is this even something at the Luma3DS-level?

Not possible at all

**Comment by zs2212221** [comment]
Is this because Luma3DS CFW and since DS games launch in DS mode, Luma literally can't do anything about that?

**Comment by Shadow322** [comment]
> Is this because Luma3DS CFW and since DS games launch in DS mode, Luma literally can't do anything about that?

Yep

**Comment by profi200** [comment]
I would not say this is impossible but not doable with Luma/Rosalina. A custom TWL_FIRM is needed. And you will run into issues when the game tries to use WiFi.

**Comment by TuxSH** [comment]
It's like profi said, and a ginormous PITA in any case.
