### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by Luma1285** [LumaTeam/Luma3DS#1612]
I cant see any of my configs, here is the dump
[crash_dump_00000005.dmp.zip](https://github.com/LumaTeam/Luma3DS/files/6165469/crash_dump_00000005.dmp.zip)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
