### ISSUE TITLE
BootNTR???

### ISSUE THREAD

**Issue by Myst1c0raL** [LumaTeam/Luma3DS#1613]
I have been waiting for luma to resupport BootNTR since the latest release back in November where support stopped. 
please, can some dev find some way to resupport it? I can’t use any of my USuMo mods w/o it.
Link to BootNTR’s GitHub: https://github.com/Nanquitas/BootNTR/releases 
PLEASE!!

**Comment by urherenow** [comment]
You've got it backwards. It's bootNTR that has to support Luma. Or more to the point, support OFW with the extra syscalls and other advantages afforded to it by b9s/fastboot3ds and Luma3ds. Luma has to support Nintendo's firmware (which was updated since bootNTR was updated last).
