### ISSUE TITLE
[FEATURE REQUEST] Audio volume and style chooser in Rosalina menu

### ISSUE THREAD

**Issue by Mr7011cfw** [LumaTeam/Luma3DS#1616]
You would be able to change volume and the audio from mono to stereo to surround much quicker and easier if you need to or can't.

**Comment by ghost** [comment]
Does the 3DS even have volume (mono/stereo/surround) options?

**Comment by Mr7011cfw** [comment]
Yes, in the settings and or music app you can choose between mono, stereo,
and surround sound. Being able to set the audio volume would be more
helpful but being able to change the style right from the rosalina menu
would also be faster and easier to access.

**Comment by ghost** [comment]
I see! I do think that would be cool. Especially a volume slider...

**Comment by Mr7011cfw** [comment]
Rad😎

**Comment by junpeikun** [comment]
Also, I don't know if I'm the only one experiencing this, but my volume slider is VERY sensitive, to the point where just holding my 3DS can trigger a volume change. A way to completely disable that slider and replace it by a software counterpart is a must.

**Comment by ghost** [comment]
If I remember correctly, there’s a Luma3DS fork that can solve this for you. I forget what it’s called as I don’t have my 3DS on hand, but it’s avaliable on Universal Updater!

**Comment by moldimolt** [comment]
Duplicate: #1485
