### ISSUE TITLE
[FEATURE REQUEST] FPS Counter

### ISSUE THREAD

**Issue by MutatedT7** [LumaTeam/Luma3DS#1617]
Some games have big differences in FPS, comparing the two different clock settings on new 3ds models.

I think that an FPS Counter toggeable in the luma menu would be a good addition as a feature for the next update, insightful and useful, potentially saving battery if using overclock on that game is not worth it.

**Comment by ghost** [comment]
[This is the same as mine](https://github.com/LumaTeam/Luma3DS/issues/1594), I added yours to the feature request thingy. Great minds think alike

**Comment by TuxSH** [comment]
This is game-dependent and would be too difficult to implement in a general fashion, not to mention opening the Rosalina menu pauses the active application/game.
