### ISSUE TITLE
Trying to boot Nintendo eShop crashes my New 2Ds XL

### ISSUE THREAD

**Issue by NintendoPSproGS** [LumaTeam/Luma3DS#1618]
When I open the Nintendo eShop the whole New 2Ds XL crashes. This bug also occures in the Digital Instruction Manual. I'll leave the crash report.
[crash_dump_00000001.zip](https://github.com/LumaTeam/Luma3DS/files/6253505/crash_dump_00000001.zip)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
