### ISSUE TITLE
R3 (gta3  port) return in an ARM11 (core 0) exception at launch

### ISSUE THREAD

**Issue by dixy52-beep** [LumaTeam/Luma3DS#1628]
**System model:**

 New 3DS Xl

**SysNAND version (+emu/redNAND version if applicable):**

Don't know at the moment

**Entrypoint (How/what you're using to boot Luma3DS):**

Don't know at the moment

**Luma3DS version:**
10.2

**Luma3DS configuration/options:**
game patching anabled
Clock + L2

Screen brightness: (highest possible)

New 3DS CPU: ( )
Clock + L2

Enable loading external FIRMs and modules: (true )

Enable game patching: ( true)

Show NAND or user string in System Settings: (false )

Show GBA boot screen in patched AGB_FIRM: (false )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: (true but it doesn't really help, the nintendo says "we encountered a problem and your console needs to reboot )

**Explanation of the issue:**

the game doesn't open. It shows a black screen and then an ARM11 exception

**Steps to reproduce:**

1. Install the game

2. Launch it

Gonna add the dump asap

**Comment by dixy52-beep** [comment]
fixed, not a luma related issue

**Comment by Bestiaz** [comment]
> **System model:**
> 
> New 3DS Xl
> 
> **SysNAND version (+emu/redNAND version if applicable):**
> 
> Don't know at the moment
> 
> **Entrypoint (How/what you're using to boot Luma3DS):**
> 
> Don't know at the moment
> 
> **Luma3DS version:** 10.2
> 
> **Luma3DS configuration/options:** game patching anabled Clock + L2
> 
> Screen brightness: (highest possible)
> 
> New 3DS CPU: ( ) Clock + L2
> 
> Enable loading external FIRMs and modules: (true )
> 
> Enable game patching: ( true)
> 
> Show NAND or user string in System Settings: (false )
> 
> Show GBA boot screen in patched AGB_FIRM: (false )
> 
> Set developer UNITINFO: ( )
> 
> Disable Arm11 exception handlers: (true but it doesn't really help, the nintendo says "we encountered a problem and your console needs to reboot )
> 
> **Explanation of the issue:**
> 
> the game doesn't open. It shows a black screen and then an ARM11 exception
> 
> **Steps to reproduce:**
> 
> 1. Install the game
> 2. Launch it
> 
> Gonna add the dump asap



> fixed, not a luma related issue

How did you fix that error?
