### ISSUE TITLE
How do I fix ErrDisp Error whenever I play a ds game

### ISSUE THREAD

**Issue by Reshiram76** [LumaTeam/Luma3DS#1629]

**Comment by Shadow322** [comment]
Using a ds flashcart?

**Comment by Reshiram76** [comment]
> Using a ds flashcart?

Nope, legit copys

**Comment by Reshiram76** [comment]
here is my error code

Error type:       generic

Process ID:       19
Process name:     am
Process title ID: 0x0004013000001502

Address:          0x001093aa
Error code:       0xc8804478

**Comment by Shadow322** [comment]
> here is my error code
> 
> Error type: generic
> 
> Process ID: 19
> Process name: am
> Process title ID: 0x0004013000001502
> 
> Address: 0x001093aa
> Error code: 0xc8804478

The error code is generic

**Comment by Reshiram76** [comment]
what do I do about that

**Comment by urherenow** [comment]
A good start would be to use the bug template, filling in all of the info, so we at least know where you're coming from. Also, have you ever installed a patched twl_nand (also known as twl_firm)? Whether you have or not, you should try to obtain an unpatched copy and install it, before troubleshooting this issue. Just make sure you grab the correct one (it's different between o3ds and n3ds, for example...)

If you're sure you know the correct title, you could even delete it with FBI, then run a system update, to get an unpatched one installed.

**Comment by Reshiram76** [comment]
So what your saying is that I should find one and install it then do a system update?

EDIT: Can you link one for me?

**Comment by Reshiram76** [comment]
> A good start would be to use the bug template, filling in all of the info, so we at least know where you're coming from. Also, have you ever installed a patched twl_nand (also known as twl_firm)? Whether you have or not, you should try to obtain an unpatched copy and install it, before troubleshooting this issue. Just make sure you grab the correct one (it's different between o3ds and n3ds, for example...)
> 
> If you're sure you know the correct title, you could even delete it with FBI, then run a system update, to get an unpatched one installed.

FIXED, PROBLEM SOLVED THANKS.

**Comment by WICKY419** [comment]
Can someone help me as well?
Error type: generic
Process ID: 15
Process Name: menu
Process Title ID: 0004003000008f02

**Comment by Masamune3210** [comment]
Don't steal closed issues. You made your own, now you just need to wait.
