### ISSUE TITLE
issue when compiling luma3ds from git 

### ISSUE THREAD

**Issue by silverhikari** [LumaTeam/Luma3DS#1630]
i am compiling Luma3ds on manjaro, i have made and installed makerom, i have also install firmtool as stated in the Readme. i also have the latest version of devkit arm(as of the moment) and libctru(version is 2.0.1-1).
here is the error report

https://paste.ee/p/p4oAs

**Comment by oreo639** [comment]
Why do you need to compile Luma3DS from git?

**Comment by Shadow322** [comment]
> Why do you need to compile Luma3DS from git?

He wants the latest compiled code

**Comment by oreo639** [comment]
> He wants the latest compiled code

If that is *all* you want, wouldn't you save yourself some time by using the [latest release](https://github.com/LumaTeam/Luma3DS/releases) or an [hourly](https://github.com/hax0kartik/luma-hourlies/releases)?

(That's not to say there aren't reasons to compile Luma3DS, but unless you intend to add/change something, the former options are probably easier)

**Comment by silverhikari** [comment]
did not know the hourly existed so thanks that looks like what i wanted.

**Comment by urherenow** [comment]
Just as the main page says, you need the latest libctru. In this case, including commits not released yet.

So clone libctru, build it, then "sudo -HE make install"

Just built the latest Luma3ds a few seconds ago with no errors (not that it doesn't have any, but the latest commit disabled errors that weren't important, according to the devs...)

Edit: also, updating the devkitpro files seems wonky. I just had to manually install the latest version of dkp-pacman, and reinstall the groups (eg. dkp-pacman -S 3ds-dev). Seems that running -Syu doesn't automatically add things that may have been added (or separated into different files) into the groups... it only checks that the things you have installed already, are the latest release version...

EDIT2: Actually there IS an error I didn't notice. I have the latest commits of firmtool, makerom, and everything dkp related, and although I end up with a boot.firm, I see this message when I scroll up (and in more than one place):

[EXHEADER WARNING] Parameter Not Found: "AccessControlInfo/ServiceAccessControl"
