### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by FieryMewtwo** [LumaTeam/Luma3DS#1632]
I wanted to install Luma3DS on my launch model O3DS, but I'm kind of worried I might screw up my console. Should I just do it or is there a legitimate reason to not install CFW?

**Comment by FieryMewtwo** [comment]
(like accidental hard-bricking)

**Comment by urherenow** [comment]
Github is not a forum. Please stop creating issues when there is no issue. Use discord or gbatemp forums.
