### ISSUE TITLE
I can't load my homebrew mods because i get a crash from luma: Processor: Arm11 ( core 0 ) Exception type: prefetch abort Fault status: Translation - Section Current process: SKATER ( 0004003000009402 )

### ISSUE THREAD

**Issue by JoystickVR** [LumaTeam/Luma3DS#1635]
I keep on geting this error mesage from luma every time i boot up homebrew.
![WIN_20210606_18_18_31_Pro](https://user-images.githubusercontent.com/85461675/120941976-bf135580-c6f3-11eb-8f0b-07b28c5689a1.jpg)

can you guys help me fix it?

Model: New 3DS XL

**Comment by oreo639** [comment]
You don't need to use browserhax with luma.
You can follow this (specifically section 3) to launch the homebrew launcher with Rosalina:
https://3ds.hacks.guide/finalizing-setup

**Comment by JoystickVR** [comment]
> You don't need to use browserhax with luma.
> You can follow this (specifically section 3) to launch the homebrew launcher with Rosalina:
> https://3ds.hacks.guide/finalizing-setup
-----------------------------------------------------------------------------------------------------------------------------
The menu is in chinese/japanise

**Comment by oreo639** [comment]
> > You don't need to use browserhax with luma.
> > You can follow this (specifically section 3) to launch the homebrew launcher with Rosalina:
> > https://3ds.hacks.guide/finalizing-setup
> 
> The menu is in chinese/japanise

What menu?

**Comment by JoystickVR** [comment]
the Rosalina Menu for download play in step III

**Comment by oreo639** [comment]
That is likely an unofficial version of luma. If you redownload the latest release it should be in english.

**Comment by JoystickVR** [comment]
it works thanks alot

**Comment by justriy** [comment]
I had attempted the same thing as oreo639 had suggested but it still crashed with the same error but this time on core 1. I'm not sure if I deleted important files (i was removing excess files from the 3ds folder that I didn't need before this) or if I have to reinstall but anything that could help would be appreciated. (Image for reference)
![Uploading 20220520_162452.jpg…]()
