### ISSUE TITLE
"An Exception Occurred" BootNTR with a 128GB SD Card

### ISSUE THREAD

**Issue by awes145-neo** [LumaTeam/Luma3DS#1636]
New 2DS Running Luma3DS Here.
On my 128GB Card, I launch (The Nanquitas version) of BootNTR 3.6 And it loads. Sort of,
As soon as it tries to load, It gives the An exception occurred error.
There were barely any tutorials on this on YouTube and Did not work and keeps giving the same error.

**Comment by awes145-neo** [comment]
P.S It works fine on my 16GB Card.

**Comment by Squall-Leonhart** [comment]
64GB and higher sd cards have compatibility concerns with many of the FAT32 libs.

**Comment by awes145-neo** [comment]
Okay, I found a way to fix it tho.

**Comment by xtomasnemec** [comment]
> Okay, I found a way to fix it tho. 

@Awesome-neos145 How?

**Comment by awes145-neo** [comment]
formatting it within gm9 after backing up all the files
