### ISSUE TITLE
Checkpoint isn’t working and I get an error 

### ISSUE THREAD

**Issue by JoystickVR** [LumaTeam/Luma3DS#1640]
I keep on getting a crash when I load checkpoint.cia
![184E240E-D4E5-4B49-A1E8-5628CEFC6B5C](https://user-images.githubusercontent.com/85461675/122555646-8edb8900-d008-11eb-97b3-48abe6f25f47.jpeg)

**Comment by ghost** [comment]
Hello, how are you today?

Let me try to help you on that. Do these steps.

- Power Off console
- Press select button + power button together
- Take a picture of the next screen, it's your Luma configs (don't worry)
- Press START to leave that screen
- Post the picture here

On your Luma Config will have a option called "Arm11 handlers exceptions", try to mark that option and check if the error keep happening.

I'm waiting for your test. See you!

**Comment by eip618** [comment]
> Hello, how are you today?
> 
> Let me try to help you on that. Do these steps.
> 
> * Power Off console
> * Press select button + power button together
> * Take a picture of the next screen, it's your Luma configs (don't worry)
> * Press START to leave that screen
> * Post the picture here
> 
> On your Luma Config will have a option called "Arm11 handlers exceptions", try to mark that option and check if the error keep happening.
> 
> I'm waiting for your test. See you!

1. This is an issue tracker, not a support forum.
2. Disabling arm11 exception handlers is, in 98% of cases, not going to solve the problem and will instead make things more difficult to diagnose.

**Comment by ghost** [comment]
Thats true! Sorry about that. Another guy explained me about this function and really doesn't help. 

Please, ignore my last post. ^^

**Comment by TuxSH** [comment]
Make sure that your Checkpoint version is up to date. Using 3dsx is recommended.

Otherwise this looks like a Checkpoint issue
