### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by MoeTech0** [LumaTeam/Luma3DS#1641]
I have downloaded a splash screen from  https://themeplaza.art/themes and activated  them on luma v10.2.1 and they do not appear any help?

**Comment by TuxSH** [comment]
You're using the correct category, https://themeplaza.art/?category=splashes&query=&sort=newest , right?

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
