### ISSUE TITLE
Arm 11 Core 1

### ISSUE THREAD

**Issue by kiwiiberries** [LumaTeam/Luma3DS#1644]
Arm11 (Core 1) Issues

![100480139-ac8ae480-30f0-11eb-903b-a62910fd9430](https://user-images.githubusercontent.com/86454243/123368146-3eed4c80-d549-11eb-8362-2dfe8a00dbae.jpg)

I updated my 3Ds, thinking nothing of it, and now I'm stuck on this error screen. I have downloaded Luma before, but I did also take the steps to remove it from my 3Ds later on, waaay before this update --- perhaps I did not do it right, and that's why I'm now dealing it with the Arm11 code.

I've seen videos and many people say that you need only update to the boot.firm and boot.3dsx and while I did try that, I figured that without the actual Luma application on my 3Ds, it won't do a thing, and it didn't.

I'm just at a loss of what to do here.

**Comment by ghost** [comment]
Hello, how are you today, buddy?

You can try to follow this guide to make sure that you're doing the update without issues

https://github.com/LumaTeam/Luma3DS/wiki/Installation-and-upgrade

But also I have something to recommend, on luma config (Power On with Select Button pressed) you can mark the option:

- Disable arm11 exceptions handlers

Check if your issues is solved after that and let us know if you need something more. 

See you around.

**Comment by oreo639** [comment]
@sergioinfosec 
As stated in the Luma wiki `ARM11 exception handlers can be turned off, but this is highly not recommended`
It wouldn't fix this issue anyway.

To kiwiiberries:
Updating Luma should fix it. In the future though, please follow the issue template.

**Comment by ghost** [comment]
@Oreo639 Thanks for the information. I noticed that some friends were able to solve certain problems by doing this, so I thought I might be able to help in some way.

Thanks again!

**Comment by ErBlack** [comment]
#1537

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
