### ISSUE TITLE
Yoshi Woolly world crash 

### ISSUE THREAD

**Issue by T0biasCZe** [LumaTeam/Luma3DS#1645]
When you enter the Rosalina menu in 3DS And then exit the menu with Btm, the system crashes
1) load the game
2) Start level
3) load amiibo (optional?)
3) open Rosalina menu
4) Exit with B

https://user-images.githubusercontent.com/44525446/123698675-b8917d00-d85e-11eb-9469-a7f113cdd504.mp4

**Comment by qamichelemassa5859** [comment]
I'm tried all systems, still Playable on N2DSXL??

**Comment by T0biasCZe** [comment]
tried it on latest luma on new 3ds, it still happens, but only when you take screenshot in the luma menu, not when just opening it...

**Comment by qamichelemassa5859** [comment]
merino-c?

**Comment by T0biasCZe** [comment]
> merino-c?

What?

**Comment by qamichelemassa5859** [comment]
#1720

**Comment by T0biasCZe** [comment]
Yeah it still crashes with current process "merino-c"
i also tried it without the amiibo and it also crashes

**Comment by qamichelemassa5859** [comment]
> Yeah it still crashes with current process "merino-c" i also tried it without the amiibo and it also crashes

it gives an errdisp type logged while i try to save the game on a O3DS console system or a N3DS system.

**Comment by T0biasCZe** [comment]
Is it physical or digital game

**Comment by qamichelemassa5859** [comment]
@T0biasCZe i tried disable exception handlers you will be:
```
An error occurred (ErrDisp)

Error type:       invalid

Process ID:       1
Process name:     loader
Process title ID: 0x0000000000000000

Address:          0x0000021a
Error code:       0x00000021


Press any button to reboot.
```

**Comment by qamichelemassa5859** [comment]
Closed #1645.

**Comment by T0biasCZe** [comment]
1) Why, it still wasnt solved
2) you didnt close it

**Comment by impeeza** [comment]
I can confirm I have:

New 3DS
[crash_dump_00000000.dmp.txt](https://github.com/LumaTeam/Luma3DS/files/8354311/crash_dump_00000000.dmp.txt)


Luma 10.3
FW 11.15.0-47U

Poochy & Yoshi's Woolly World Title ID: 00040000001A4200  Version 0 (0.0.0) Code CTR-P-AJNP

When running the game, entering on Rosalina for take a screenshot and press (B) to exit the system crash with the next error:

![image](https://user-images.githubusercontent.com/41979604/160215205-d8cb10bf-6527-4292-8cc6-0e1d26c83abd.png)

the screenshot is take without problem

the attached file is the dump created.

[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8354312/crash_dump_00000000.zip)

**Comment by qamichelemassa5859** [comment]
> I can confirm I have:
> 
> New 3DS [crash_dump_00000000.dmp.txt](https://github.com/LumaTeam/Luma3DS/files/8354311/crash_dump_00000000.dmp.txt)
> 
> Luma 10.3 FW 11.15.0-47U
> 
> Poochy & Yoshi's Woolly World Title ID: 00040000001A4200 Version 0 (0.0.0) Code CTR-P-AJNP
> 
> When running the game, entering on Rosalina for take a screenshot and press (B) to exit the system crash with the next error:
> 
> ![image](https://user-images.githubusercontent.com/41979604/160215205-d8cb10bf-6527-4292-8cc6-0e1d26c83abd.png)
> 
> the screenshot is take without problem
> 
> the attached file is the dump created.
> 
> [crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8354312/crash_dump_00000000.zip)

Now that also it has been verificated the cia file and then it appeared:
```
An error occurred (ErrDisp)

Error type:       invalid

Process ID:       1
Process name:     loader
Process title ID: 0x0000000000000000

Address:          0x00000000
Error code:       0x00000010


Press any button to reboot.
```

**Comment by michelemassa5599** [comment]
> I can confirm I have:
> 
> New 3DS [crash_dump_00000000.dmp.txt](https://github.com/LumaTeam/Luma3DS/files/8354311/crash_dump_00000000.dmp.txt)
> 
> Luma 10.3 FW 11.15.0-47U
> 
> Poochy & Yoshi's Woolly World Title ID: 00040000001A4200 Version 0 (0.0.0) Code CTR-P-AJNP
> 
> When running the game, entering on Rosalina for take a screenshot and press (B) to exit the system crash with the next error:
> 
> ![image](https://user-images.githubusercontent.com/41979604/160215205-d8cb10bf-6527-4292-8cc6-0e1d26c83abd.png)
> 
> the screenshot is take without problem
> 
> the attached file is the dump created.
> 
> [crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8354312/crash_dump_00000000.zip)

I will tried to disable arm11 exception handlers, and now this error screen is different:
```
 An error occurred (ErrDisp)
 
 Error type:       invalid
 
 Process ID:       1
 Process name:     loader
 Process title ID: 0x0000000000000000  
 
 Address:          0x00000000
 Error code:       0x00000010
 
 
 Press any button to reboot.
```

**Comment by subad31155** [comment]
> I can confirm I have:
> 
> New 3DS [crash_dump_00000000.dmp.txt](https://github.com/LumaTeam/Luma3DS/files/8354311/crash_dump_00000000.dmp.txt)
> 
> Luma 10.3 FW 11.15.0-47U
> 
> Poochy & Yoshi's Woolly World Title ID: 00040000001A4200 Version 0 (0.0.0) Code CTR-P-AJNP
> 
> When running the game, entering on Rosalina for take a screenshot and press (B) to exit the system crash with the next error:
> 
> ![image](https://user-images.githubusercontent.com/41979604/160215205-d8cb10bf-6527-4292-8cc6-0e1d26c83abd.png)
> 
> the screenshot is take without problem
> 
> the attached file is the dump created.
> 
> [crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8354312/crash_dump_00000000.zip)

Trying to parse the crash dump in luma exception dump parser?

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).

**Comment by T0biasCZe** [comment]
how is this a tech support question?? this is genuine bug that happens when you do a screenshot in wooly world

**Comment by 2nukes** [comment]
I can confirm that I am experiencing the same, and not just with screenshots. If you open the game, open the Rosalina menu, and then press 'B', the game will crash with the error code reported above, no matter what you are doing in the menu.

I am also something very similar with Poochy & Yoshi's Woolly World. Not when in the Rosaline menu, but often when transitioning between levels. I have tried different SD cards and CIAs and done every troubleshooting process I could find with no luck. The only avenues I haven't investigated fully is it being a bug with Luma or a physical hardware problem. Seeing this issue I wanted to add my 2c to see if this is genuine issue.

![IMG_20220620_205203](https://user-images.githubusercontent.com/21247135/174716416-2ed5b6f0-19ef-41fd-8b4d-0965c6b04ef8.jpg)

'merino-c' is the process having issues.

Luma3DS 11.0 (but it was happening on 10.x as well)
Sys 11.15.0-47U

Crash log:

[crash_dump_00000005.zip](https://github.com/LumaTeam/Luma3DS/files/8945930/crash_dump_00000005.zip)

Thanks a bunch
