### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by zmazenta** [LumaTeam/Luma3DS#1647]
Hi, I already updated the luma to the latest version but I still get the same error, please help me, my console is a new 3ds xl
![63B16826-1D86-4D01-BE0F-60141EEEC593](https://user-images.githubusercontent.com/86636923/123745281-0f5a7f00-d87e-11eb-8976-69880fcb579f.jpeg)
![98580D24-F6AA-42D9-A7F2-76995A2F2206](https://user-images.githubusercontent.com/86636923/123745300-141f3300-d87e-11eb-9876-4ae9eabda3ab.jpeg)

**Comment by Shadow322** [comment]
This is not a help forum take it to gbatemp.net

**Comment by ghost** [comment]
Hey, how are you today, buddy?

Your issues is very insteresting, try to do these steps:

- Power Off your 3DS
- Put the card in computer
- Make a backup from all files
- Format your card (FAT32 is required, if is +64 GB try to use Guiformat.exe)
- Put all the files back in your card
- Power On your 3DS
- Select two options on that screen:

1. Show Nand or User ...
2. Disable arm11 exceptions handlers

- Press Start to save the config.

Post here if this process solved your problem. Be safe!

**Comment by oreo639** [comment]
@sergioinfosec
This issue has nothing to do with luma's exception handler, and there is a 99% chance this is user error. (likely a missing boot.3dsx)

**Comment by ghost** [comment]
@Oreo639 User error in the process of update or something else? I'm very curious about how to solve 3DS issues. lol

Thanks for your answer on the other post, my friend.

**Comment by oreo639** [comment]
> User error in the process of update or something else?

Idk, you'd have to ask the OP. All that I know is that they have a crash due to an "undefined instruction", which can be caused by a variety of things but the reason most regular users would run in to that is usually due to trying to launch the homebrew launcher without boot.3dsx

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
