### ISSUE TITLE
Crashes in Pokemon Rumble World development versions

### ISSUE THREAD

**Issue by mariomadproductions** [LumaTeam/Luma3DS#1649]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.14.0-46E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap (fastboot3ds)

**Luma3DS version:**

v10.2.1

**Luma3DS configuration/options:**

Default EmuNAND: (N/A)

Screen brightness: (4)

Splash: (Off)

Splash duration: (1)

PIN lock: (Off)

New 3DS CPU: (N/A)

--

Autoboot EmuNAND: (N/A)

Use EmuNAND FIRM if booting with R: (N/A)

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: (N/A)

--

**Explanation of the issue:**
In the Pokemon Rumble World "34356M" and "34961M" development versions, opening the menu and closing it crashes the system. The system also sometimes crashes when entering buildings in the hub world of the game. The "branches-TPC20150716, 36474" build crashes on run.

**Steps to reproduce:**

See above

**Dump file:**
[crash_dump_00000002.dmp.zip](https://github.com/LumaTeam/Luma3DS/files/6758339/crash_dump_00000002.dmp.zip)

**Comment by TuxSH** [comment]
Uh, maybe this is just a game crash? A development version is what it is, a development version.

I don't think this is a Luma3ds issue and don't really want to help with leaked content

**Comment by mariomadproductions** [comment]
Good point re. it being a game crash. It should be tested on a development 3DS.

The fact that its leaked content is neither here nor there. The problem isn't related to the source of the content.
