### ISSUE TITLE
Updater return weird strings for current and backup versions

### ISSUE THREAD

**Issue by ThatBenderGuy** [LumaTeam/Luma3DS#165]
I was on 5.5 and then I updated to 6.0.1 but when I went back to the LumaUpdater the version in front of "Current Installed version" and "Current backup version" became this jumbled text and is red since the text doesn't match the latest version from github. Do I need to update my Luma3DS Updater or something? I can't tell what version of it I am running because it says "Luma3DS Updater <Unknown>"

**Comment by james-d-elliott** [comment]
https://github.com/Hamcha/lumaupdate pretty sure this is the repo for this.
