### ISSUE TITLE
Arm11 (core 1) undefined instruction error

### ISSUE THREAD

**Issue by EnderBossGT** [LumaTeam/Luma3DS#1650]
I get this error when i open monster hunter stories and 
im using the latest luma version and im on a NEW 3DS XL pls help
[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/6776738/crash_dump_00000000.zip)

**Comment by oreo639** [comment]
Can you follow and fill out the issue template?

**Comment by EnderBossGT** [comment]
> Can you fill out the issue template?

Sorry i got confused

**Comment by oreo639** [comment]
This crash dump is not from Dragon Quest.
Did you upload the wrong dump? (when Luma writes the dump, it says where the dump is being written to. If you need to, you can try triggering the crash again and re-uploading the correct dump.)

**Comment by EnderBossGT** [comment]
> This crash dump is not from Dragon Quest.
> Did you upload the wrong dump? (when Luma writes the dump, it says where the dump is being written to. If you need to, you can try triggering the crash again and re-uploading the correct dump.)

I did it again as you said, now, i dont know the reason to it NOT being dragon quest stories

**Comment by EnderBossGT** [comment]
Anyone pls help, i really want to play dragon quest stories. (I just found out that this problem occurs with battleminerz too)

**Comment by XenobladePyra** [comment]
fyi this happens with every game on the 3ds/2ds if its the arm11 error it has something to do with the rosalina menu it happens to me as well whenever I like activate some sort of cheat or something in monster hunter generations and after a few quests i get this as well i don't really know why this happens though

**Comment by XenobladePyra** [comment]
someone told me to try to disable the arm11 error with the bootup method while holding select but i can confirm right now that doesn't solve it it'll just freeze the 3ds/2ds

**Comment by EnderBossGT** [comment]
> someone told me to try to disable the arm11 error with the bootup method while holding select but i can confirm right now that doesn't solve it it'll just freeze the 3ds/2ds

I know that it freezes, i tried it too.
Maybe the problem is with my CIA file?

**Comment by EnderBossGT** [comment]
> This crash dump is not from Dragon Quest.
> Did you upload the wrong dump? (when Luma writes the dump, it says where the dump is being written to. If you need to, you can try triggering the crash again and re-uploading the correct dump.)

Hey uhh i just remembered that the name isn't dragon quest stories but its monster hunter stories 🤦🤦

**Comment by EnderBossGT** [comment]
> someone told me to try to disable the arm11 error with the bootup method while holding select but i can confirm right now that doesn't solve it it'll just freeze the 3ds/2ds

Hey uhh i just remembered that the name isn't dragon quest stories but its monster hunter stories 🤦🤦

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
