### ISSUE TITLE
Throws error when attempting a system update

### ISSUE THREAD

**Issue by KrischnaGabriel** [LumaTeam/Luma3DS#1652]
All  Information are in the images
Luma was just freshly updated.  Only firmware-setting i changed was to show the firmware String in the System settings. Everything else is set to  be default.
Weirdly it doesn't gives a crash log or dump that i could give you.
![IMG_20210709_104712](https://user-images.githubusercontent.com/39499729/125054599-b02f1280-e0a6-11eb-85b1-16a521aefc52.jpg)
![IMG_20210709_104739](https://user-images.githubusercontent.com/39499729/125054613-b3c29980-e0a6-11eb-9c68-f8aa6e72c2d7.jpg)
![IMG_20210709_104748](https://user-images.githubusercontent.com/39499729/125054621-b7562080-e0a6-11eb-8476-19cc38104af3.jpg)

**Comment by TuxSH** [comment]
I'm inclined to believe that it would have crashed all the like without Luma. In any case, have you tried booting in safe mode (hold L+R+A+DPad Up at boot)?

Have you modified the CTRNAND partition in any significant way? The error indicates that the partition is full which is clearly not a Luma issue.
