### ISSUE TITLE
Luma 10.2.1 data abort Translation Section

### ISSUE THREAD

**Issue by SomeWhatInterestingLemon** [LumaTeam/Luma3DS#1653]
**System model: Old 3DS XL**

**SysNAND 11.14.0-46(+emu/redNAND version if applicable):**

**Entrypoint Boot9Strap (How/what you're using to boot Luma3DS):**

**Luma3DS version:10.2.1**

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (1x )

Splash: (beforex )

Splash duration: (3x )

PIN lock: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

--

**Explanation of the issue:**
Processor: Arm11 (core 0)
Exception type: data abort
Fault status: Translation - Section
Current process: Boot NTR (00400000EB30000)
Crash Dump https://drive.google.com/file/d/1JwvNITLF58FG3gn2pvkL7_iak0IAk5V8/view?usp=sharing

**Steps to reproduce:**

1. Open Boot NTR (This also happens with a bunch of different games.)
[crash_dump_00000004.zip](https://github.com/LumaTeam/Luma3DS/files/6791610/crash_dump_00000004.zip)

**Dump file:**

**Comment by TuxSH** [comment]
Looks like a BootNTR issue to me
