### ISSUE TITLE
Black screen on Pkmn Omega Ruby

### ISSUE THREAD

**Issue by dynux90** [LumaTeam/Luma3DS#1654]
Model: New 2DS XL
fastboot3ds v1.2
Luma3DS v10.2.1

Content from: errdisp.txt

Error type:       generic

Process ID:       39
Process name:     sango-1
Process title ID: 0x000400000011c400

Address:          0x0012884c
Error code:       0xd900458b

**Comment by fsilletti** [comment]
same problem

**Comment by TuxSH** [comment]
Are you using any kind of patches?

**Comment by dynux90** [comment]
> Are you using any kind of patches?

Nope, also tested on a new sdcard

**Comment by notsunburn** [comment]
mine has been doing the same thing but its not just in the game its when I turn my 3ds on. But it also does do it in game, like 3 secs after trying to use a a cheat from checkpoint. please get back to me with some help on the problem. Thanks

**Comment by dynux90** [comment]
I do not use cheats, i also tried with cheats to walk over wall to avoid the ecounter that makes me crash the game but the cheats also do not work

**Comment by notsunburn** [comment]
and the only way it doesn't show me "An exception occurred" is when i dont have the sd card in the system

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
