### ISSUE TITLE
Arm11 Crash

### ISSUE THREAD

**Issue by XiNaru** [LumaTeam/Luma3DS#1658]
I completely reset my 3ds due to the following problem and redoed the hack. All the latest version.

but when I try to start a game (in this case Monster Hunter Stories) I get an Arm11 crash.

I use the New 3DS XL with firmware 11.15.0-47E and Luma3DS 10.2.1

Crash
https://screen.xinaru.de/001/RUMiRofU93.png

**Comment by oreo639** [comment]
How did you install Monster Hunter Stories? If it is from the eshop, did you try doing a repair install?

**Comment by XiNaru** [comment]
no it was an BACKUP installation through FBI

**Comment by oreo639** [comment]
Then redump it, otherwise, piracy isn't supported.

**Comment by XiNaru** [comment]
not piracy, only BACKUP
that was an backup dump from my modul

**Comment by SpacyJacobson** [comment]
I have the same error but I downloaded it from the Internet

[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/6923403/crash_dump_00000000.zip)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
