### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by kamenradier** [LumaTeam/Luma3DS#1661]
**System model:**

[New 2DS XL, New 3DS XL, New 3DS, Old 2DS, Old 3DS XL, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4 )

Splash: (off )

Splash duration: ( 1)

PIN lock: ( off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (o
[crash_dump.zip](https://github.com/LumaTeam/Luma3DS/files/6942714/crash_dump.zip)
)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
I am Korean. That's why English may not be good enough.
I recently firmwareed 3ds. I am using Luma 10.2.1. And I changed the sd card from 4Gb to 128Gb. I also adjusted it properly using guiformat. But it doesn't work like a dump file. Genuine cartridge chips are also not recognized. However, the 4Gb SD card that I originally had works well. I tried formatting, resetting, and put the file back in, but it failed. What's the problem? Please help me. Thanks.
[crash_dump.zip](https://github.com/LumaTeam/Luma3DS/files/6942746/crash_dump.zip)

 

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by FieryMewtwo** [comment]
Make sure you're following 3ds.guide to hack your console, and make sure you get a "real" SD Card from a physical retailer like Wal-Mart. If you prefer, here is an Amazon link to a reputable card.

[Known Good SD Card Model on amazon.com](https://www.amazon.com/SanDisk-128GB-microSDXC-Memory-Adapter/dp/B073JYC4XM)

Also try asking on the [Nintendo Homebrew Discord](https://discord.gg/C29hYvh)

**Comment by FieryMewtwo** [comment]
Also, please fill out the issue template all the way.
