### ISSUE TITLE
:(

### ISSUE THREAD

**Issue by IgnacioLeonI** [LumaTeam/Luma3DS#1662]

**Comment by oreo639** [comment]
How did you install/run these games? The error codes indicate that either the game files or the save is corrupted.

**Comment by IgnacioLeonI** [comment]
> How did you install/run these games? The error codes indicate that either the game files or the save is corrupted.

Directly from the main menu of the console. I also did the "import seed" with the FBI

**Comment by oreo639** [comment]
Is this installed from the eshop or is this being run from a cartrige is what I meant?

**Comment by IgnacioLeonI** [comment]
> Is this installed from the eshop or is this being run from a cartrige is what I meant?

Downloaded from a webpage and installed through cia

**Comment by Shadow322** [comment]
> > Is this installed from the eshop or is this being run from a cartrige is what I meant?
> 
> Downloaded from a webpage and installed through cia

Luma3ds does not support or Condon piracy

**Comment by Doxerythm** [comment]
> > Is this installed from the eshop or is this being run from a cartrige is what I meant?
> 
> Downloaded from a webpage and installed through cia

Ok, i'm trying to report you to the authorities.

**Comment by IgnacioLeonI** [comment]
Sorry, didn't know how this work. Thanks for your information
