### ISSUE TITLE
Arm 11 Crash Pokémon XY and ORAS

### ISSUE THREAD

**Issue by servalsanz** [LumaTeam/Luma3DS#1666]
Hello, I have been desperate for a long time, I have been with this error since I purchased my new 2ds console.

The console already had CFW installed.

When I had it I updated everything to the latest version. All games seem to be working fine, but when playing Pokémon games, I get an ARM11 error (code 0) and each time I get a different error, as seen in the photos.

I have reinstalled, updated, changed the files ... the same thing always happens to me, an error in a random place (it does not usually occur in the same place) but constant (whatever I do happens)

The weird thing is that it not only happens to me with the backup, it also happens to me with the original game cart.

Does anyone know what the error may be and how to fix it?

![WhatsApp_Image_2021-07-28_at_23 25 32](https://user-images.githubusercontent.com/36898966/130487809-d53eb3ad-cad7-46dd-8b53-7fc36263e862.jpeg)
![20210730_205258](https://user-images.githubusercontent.com/36898966/130487822-6574abd1-d96b-494f-8b08-d335f29315e8.jpg)
![20210730_221412](https://user-images.githubusercontent.com/36898966/130487831-60a82e66-9196-4ae4-a32d-c37c80e988e4.jpg)

**Comment by Squall-Leonhart** [comment]
I don't have this issue with my X and Y carts on O3DS and N3DS

**Comment by WhitetailAni** [comment]
This works fine for me with X and Y carts.
Try reinstalling the CFW? Perhaps it got corrupted.

**Comment by N-rotceh** [comment]
I have everything updated to the latest version and I have the same issue with Pokemon A. Sapphire and Pokemon X as well, I'm using the updated version of both of them.

![IMG_20210901_195334](https://user-images.githubusercontent.com/89993330/131880395-1d0ce47f-6062-45d2-a9d3-1153aff4b88d.jpg)

**Comment by Squall-Leonhart** [comment]
follow the guides to update/migrate from previous cfw to current boot9strap 

https://3ds.hacks.guide/

You are potentially looking at a faulty board though.
https://gbatemp.net/threads/arm11-core-0-crash-error-near-intro-of-games-have-formated-fresh-card-updated-luma.575160/

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
