### ISSUE TITLE
Possibility of animated Splash screens?

### ISSUE THREAD

**Issue by SnazzyYoshi** [LumaTeam/Luma3DS#167]
Wondering if this is a possibility, because when I've tried to use BootAnim9, some apps refused to load.

**Comment by Hartie95** [comment]
You could try BootCTR9, it has support for top screen animations and splashes and more.
But it should also be possible to add it to Luma, but keep in mind, its main functionality is to be a CFW,  everything additionally is just a bonus. ;)
