### ISSUE TITLE
Still getting arm 11 error

### ISSUE THREAD

**Issue by XxDabixX** [LumaTeam/Luma3DS#1670]
After doing all the steps i am still getting the error please help

**Comment by Squall-Leonhart** [comment]
this is not a discussion forum or help channel, refer to the homebrew discords or gbatemp.

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
