### ISSUE TITLE
FE Awakening Arm11 Crash on Boot

### ISSUE THREAD

**Issue by Mintywolf** [LumaTeam/Luma3DS#1672]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.15.0-47U SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[10.2.1]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Off )

Splash duration: (1)

PIN lock: (Off )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

**Steps to reproduce:**

1. Attempt to open Fire Emblem: Awakening from cartridge on the 3DS home screen.

2. After briefly displaying the 3ds title screen, the system crashes and displays an Arm 11 "An exception occurred" error screen.

**Dump file:**
[crash_dump_00000004.zip](https://github.com/LumaTeam/Luma3DS/files/7074080/crash_dump_00000004.zip)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
