### ISSUE TITLE
For people with broken parts using Rosalina Menu (solved im sorry)

### ISSUE THREAD

**Issue by RemittentBow410** [LumaTeam/Luma3DS#1673]
Can you make some type of configurable file so people can choose the configuration to use on Rosalina menu so it is accessable. I have a broken Select button and as it stands I cannot find any way to access Rosalina menu without fixing the broken part (which I understandably don't want to do if at all possible) I would really appreciate it :D 

(edit) there is already a config.bin file that you can do this, sorry lol

**Comment by Weigurde** [comment]
somebody close this?

**Comment by wuniversales** [comment]
> Can you make some type of configurable file so people can choose the configuration to use on Rosalina menu so it is accessable. I have a broken Select button and as it stands I cannot find any way to access Rosalina menu without fixing the broken part (which I understandably don't want to do if at all possible) I would really appreciate it :D
> 
> (edit) there is already a config.bin file that you can do this, sorry lol

Please close the ticket if it has been fixed.
Greetings

**Comment by TuxSH** [comment]
https://3ds.eiphax.tech/config
