### ISSUE TITLE
feature request: auto Sync time

### ISSUE THREAD

**Issue by T0biasCZe** [LumaTeam/Luma3DS#1677]
The 3DS  doesnt have Time battery, So when it runs out of power, the time resets to 1/1/2011 and you need to manually set it
Luma already has function to automatically sync times over internet in the Rosalina menu, but you need to go into it, and notice that the time actually reseted
Would it be possible to add function to automatically sync the time when the time is reseted because of power loss ?

**Comment by TuxSH** [comment]
No, that's not feasible. But you don't need to reboot your console anymore after using the NTP feature
