### ISSUE TITLE
Clock+L2 enabled on Rosalina Menu but disabled in lumaconfig

### ISSUE THREAD

**Issue by Vendicatorealato** [LumaTeam/Luma3DS#1678]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.15.0-47E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v10.2.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (After)

Splash duration: (3)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (On)

Enable game patching: (On)

Show NAND or user string in System Settings: (On)

Show GBA boot screen in patched AGB_FIRM: (On)

Set developer UNITINFO: (Off)

Disable Arm11 exception handlers: (Off)

Enable Rosalina on SAFE_FIRM: (Off)

--

**Explanation of the issue:**

I have Clock+L2 disabled in Luma3DS settings, but every time I boot up the console they are enabled in Rosalina Menu (and I noticed that they are for real beacuse the console heats up). I tried to disable them in Rosalina Menu (saving in Miscellaneous options), enable them in lumaconfig, delete \luma\config.bin, but nothing change. Right now, I have to disable them every time I boot up the New 3DS. For now, I tried only with a microSD card inserted.

**Steps to reproduce:**

1. Set to Off the New 3DS CPU option in lumaconfig

2. Save by clicking Start

3. Open Rosalina Menu on Home, go in New 3DS menu...

4. See that there are "Disable L2 cache" and "Set clock rate to 268MHz

**Dump file:**

**Comment by sugar700** [comment]
This is by design, documentation for "New 3DS CPU" setting clearly says that "This won't apply to New 3DS exclusive/enhanced games". If you boot into a game that is not New 3DS-enhanced (like Mii Maker for instance) then the CPU will be properly clocked at 268MHz.

**Comment by AuroraWright** [comment]
The home menu counts as "N3DS enhanced". As soon as you start any game that's not N3DS enhanced it will downclock/disable the extra L2 cache.
