### ISSUE TITLE
DS games not working on last version

### ISSUE THREAD

**Issue by porky754** [LumaTeam/Luma3DS#168]
DS Games, both original ones and flashcards, doesn't work on emunand 11.0 with luma 6.0.1

**Comment by Shadow322** [comment]
Your shits broken work's fine here

**Comment by NULLx76** [comment]
Has it stopped working or has it never worked for you?

**Comment by pokecrafter1551** [comment]
Where is the bin file? If its not on the root of the sd card and named arm9loaderhax.bin, use the pathchanger.

**Comment by porky754** [comment]
DS games always worked, the problem only shows up on the last version
I have arm9loaderhax.bin in the root of the sd card but still didn't work, I'll try to format the SD card

**Comment by porky754** [comment]
Oh, sorry, the problem was that I haven't overwrited the old arm9loaderhax.bin, apparently.
