### ISSUE TITLE
This Is More A Suggestion

### ISSUE THREAD

**Issue by godreborn** [LumaTeam/Luma3DS#1684]
someone on temp wanted me to post this.  it's his suggestion, not mine: https://gbatemp.net/threads/remove-3ds-system-update-nag-without-safe-mode-rebooting.601412/#post-9629556

**Comment by urherenow** [comment]
Once you have b9s or fasboot3ds installed, there are exactly ZERO reasons to not update. Not worth the time, as this "problem" is 100% your choice and 100% your fault.

You can always delete the update files with FBI anyway.

**Comment by godreborn** [comment]
thanks.  I didn't know about the fbi method.  I'll let him know.
