### ISSUE TITLE
Rosaling menu shows Error code  0xd8606408 when charging

### ISSUE THREAD

**Issue by tumuyan** [LumaTeam/Luma3DS#1685]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[4.2.0-9U SysNAND, 11.15.0-47U EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[10.2.1]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (2 )

Splash: (OFF)

Splash duration: (1 )

PIN lock: ( OFF)

New 3DS CPU: ( )

Autoboot EmuNAND: (Y)

Use EmuNAND FIRM if booting with R: (N)

Enable loading external FIRMs and modules: (Y)

Enable game patching: (Y)

Show NAND or user string in System Settings: (Y)

Show GBA boot screen in patched AGB_FIRM: (N)

Set developer UNITINFO: (Y)

Disable Arm11 exception handlers: (N)

Enable Rosalina on SAFE_FIRM: ( )

**Explanation of the issue:**
Rosaling menu shows Error code  0xd8606408 when charging.

Also I find the same bug
https://gbatemp.net/threads/rosaline-error-during-section-iii-launching-fbi.495842/

**Steps to reproduce:**

1. boot the emu system
2. Plug in the charger
3. Open rosaling menu, wait about 5 second, then it shows Error code  0xd8606408

**Dump file:**

-------------------------------------

Error type:       generic

Process ID:       11
Process name:     mcu
Process title ID: 0x0004013000001f02

Address:          0x0010366c
Error code:       0xd8606408

-------------------------------------

Error type:       generic

Process ID:       11
Process name:     mcu
Process title ID: 0x0004013000001f02

Address:          0x0010366c
Error code:       0xd8606408

**Comment by Shadow322** [comment]
Quit using enunand and the error will go away

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
