### ISSUE TITLE
Keep getting this error how do fix it

### ISSUE THREAD

**Issue by Stinkyisepic** [LumaTeam/Luma3DS#1688]
![image](https://user-images.githubusercontent.com/93695050/140253581-f5a75a4f-157e-4985-8445-5d43e75c10a4.jpg)

**Comment by Stinkyisepic** [comment]
This always happens when I open Homebrew launcher even if I have the Boot.3dsx in the files

**Comment by Squall-Leonhart** [comment]
try reinstalling the launcher
