### ISSUE TITLE
Updated to latest version - EMUNAND not autobooting (works holding L)

### ISSUE THREAD

**Issue by parkesto** [LumaTeam/Luma3DS#1690]
I updated the boot.firm and the boot.3dsx as I had the latest update for my 3ds and now it won't autoboot into emunand, it keeps going into SYSNAND? Not a huge deal as I can hold L but I'd like for it to boot properly so my kids end up in Emunand right away.

I've changed the "Default Emunand" from 1-4 and... nothing? Any insight would be appreciated!

**Comment by Shadow322** [comment]
Why emunand?

**Comment by parkesto** [comment]
> Why emunand?

You know what, I am sorry. I forgot Emunand went the way of the dodo! I unchecked autoboot emunand and I am good to go :P
