### ISSUE TITLE
Suggestion: AGB_FIRM sleep: Simulate buttons on lid close

### ISSUE THREAD

**Issue by joemck** [LumaTeam/Luma3DS#1691]
Is it possible to get AGB_FIRM to simulate a button combination on lid close?

We have sleep patches for GBA games where you push one button combination to put the game to sleep, then push another button combo or open the lid and it wakes up. Is it possible to get AGB_FIRM to send the sleep button combo when you close the lid? Even just a single hardcoded button combination that can be turned on or off on the config menu would be great. The default one seems to be L+R+select, at least in the New Super Ultimate Injector, but we can set it to almost anything.

**Comment by asdolo** [comment]
This is actually possible. AGB_FIRM already does that 🙂 (not sure about OPEN_AGB_FIRM though...)

Check this: https://www.3dbrew.org/wiki/3DS_Virtual_Console#Config

![image](https://user-images.githubusercontent.com/13039008/158048772-4db21110-9a5b-4003-9d51-ba9ce951dc6d.png)

I already tested it and it works!

`0000000001` in binary -> `A button`
`0000000010` in binary -> `B button`
`0000000100` in binary -> `Select button`
`0000001000` in binary -> `Start button`
`0000010000` in binary -> `Right button`
`0000100000` in binary -> `Left button`
`0001000000` in binary -> `Up button`
`0010000000` in binary -> `Down button`
`0100000000` in binary -> `R button`
`1000000000` in binary -> `L button`

So lets say your GBA game goes to sleep when you press L+R+Select. The bitmask for that combination is `1100000100` in binary = `0x0304` in hex. Then, `0x0304` represented in little-endian is `0x04 0x03`, so you should place `04 03` in position `0x00E` of the GBA footer, like this:

![IakvbC8Yt1](https://user-images.githubusercontent.com/13039008/158049183-3e30d666-d6ae-4cb3-9fa2-68d5eaf37463.png)

**Comment by joemck** [comment]
Wth... Nintendo even cited not being able to get sleep mode to work properly as a reason they never released GBA VC games outside of the ambassador program, and added that notice on the bottom screen about sleep not working, and it turns out they had a complete fix that only needs a sleep patch to work on most games? Amazing.

I'm off to manually take apart, hex edit and rebuild my GBA VC injects then. I really wish NSUI set this field when building a GBA inject with the optional sleep patch.

I opened this ticket thinking AGB_FIRM needed patching to do this and that Luma could do it. Now my only issue is with NSUI, so I'm closing my ticket here.

**Comment by asdolo** [comment]
I'll add this feature to NSUI eventually. For now at least it's documented here for anyone 😛.
