### ISSUE TITLE
Nintendo 2ds Arm11 (core 0) Problem

### ISSUE THREAD

**Issue by Slonkuhroni** [LumaTeam/Luma3DS#1692]
So i deleted some red files on fbi which cause the break but i don't know how to fix it and Im panicking Idk if have a custom theme effects it.
![IMG_20211202_165219](https://user-images.githubusercontent.com/90153994/144509054-51c39832-8736-4736-bf67-0bd7be55d0bc.jpg)

**Comment by urherenow** [comment]
GitHub isn't a help forum. Google how to get into recovery mode, and perform a system update. Alternatively, boot into Godmode9, and restore your most recent backup of your nand.

**Comment by Slonkuhroni** [comment]
How?

**Comment by Slonkuhroni** [comment]
ohh

**Comment by Slonkuhroni** [comment]
Umm another way?

**Comment by oreo639** [comment]
@Slonkuhroni Follow the instructions here:
https://www.3dbrew.org/wiki/Recovery_Mode

Then click update. You should get a message saying no updates are available, that's normal. 
(In the future, if you want to uninstall applications, just use the system settings and if you absolutely need to use FBI, the red name indicates it is installed on the system ctrnand partition and not on the SD card)
