### ISSUE TITLE
Crash Monster Hunter Stories

### ISSUE THREAD

**Issue by Moda93** [LumaTeam/Luma3DS#1695]
Hi there,

as the title suggests I am getting a crash everytime I try to start the Game Monster Hunter Stories that I have installed previously as a CIA via FB.

I also tried redumping the Game... but it doesnt seem to make a difference. Neither does importing the Seed.

Does anybody know why this happens ? Other Games start and run just fine as far as I have tested for the ones I already had installed on the SD Card.

Crash Dump attached.

[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/7653983/crash_dump_00000000.zip)
I.

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
