### ISSUE TITLE
SELECT button not working, I think I need a method to adjust the button combo to open the Rosalina menu

### ISSUE THREAD

**Issue by Vagato** [LumaTeam/Luma3DS#1698]
Hi, as mentioned in the title, my SELECT button is not working. 

So I can not complete [the mod guide](https://3ds.hacks.guide/get-started) and therefore mod my 3ds. Is there some ways to change the button configure in order to open the Rosalina menu?

In [the guide](https://3ds.hacks.guide/finalizing-setup#:~:text=Press%20(Left%20Shoulder)%20%2B%20(D%2DPad%20Down)%20%2B%20(Select)%20at%20the%20same%20time%20to%20open%20the%20Rosalina%20menu) it reads:
[Press (Left Shoulder) + (D-Pad Down) + (Select) at the same time to open the Rosalina menu]

Is there a script file that I could edit to change the SELECT button to another button?

Many thanks!

**Comment by TuxSH** [comment]
I'll fix that kind of stuff later, but you can use https://3ds.eiphax.tech/config for now.
