### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by huetrashme0947** [LumaTeam/Luma3DS#1699]
I'm trying to compile Luma3DS from source code. However, I'm getting a couple of errors:
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:89:5: error: unknown type name 'FS_SdMmcSpeedInfo'`
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:110:49: error: passing argument 1 of 'FSUSER_GetSdmcSpeedInfo' from incompatible pointer type [-Werror=incompatible-pointer-types]`
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:112:46: error: request for member 'sdClkCtrl' in something not a structure or union`
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:115:31: error: request for member 'highSpeedModeEnabled' in something not a structure or union`
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:115:54: error: 'SYSCLOCK_SDMMC' undeclared (first use in this function); did you mean 'SYSCLOCK_SOC'?`
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:118:49: error: passing argument 1 of 'FSUSER_GetNandSpeedInfo' from incompatible pointer type [-Werror=incompatible-pointer-types]`
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:120:46: error: request for member 'sdClkCtrl' in something not a structure or union`
`/home/heuhaufen/Luma3DS/sysmodules/rosalina/source/menus.c:123:31: error: request for member 'highSpeedModeEnabled' in something not a structure or union`

**Comment by urherenow** [comment]
When did you install the dkp libraries? Looks like your ctrulib is outdated...

often, you need to compile and install ctrulib from source, instead of relying on dkp-pacman. Same with libnx for switch.

**Comment by huetrashme0947** [comment]
> When did you install the dkp libraries? Looks like your ctrulib is outdated...

Installed it yesterday.

> often, you need to compile and install ctrulib from source, instead of relying on dkp-pacman. Same with libnx for switch.

Thanks, I'll try that later.

**Comment by oreo639** [comment]
> often, you need to compile and install ctrulib from source, instead of relying on dkp-pacman.

This is only the case with luma as new features in luma sometimes require new features to be added to libctru

> Same with libnx for switch.

Generally not.

**Comment by urherenow** [comment]
Don't say "generally not" when you don't know what you're talking about. A new libnx is required with damn near every Atmosphere update, and is hardly ever updated on the dkp repos by that lime.

**Comment by oreo639** [comment]
> A new libnx is required with damn near every Atmosphere update

Sure, I was just trying to clarify for OP that this is a Luma/Atmosphere specific thing and most software do not require pre-release versions of libctru/libnx. That being said, I definitely should have worded it better.

**Comment by TuxSH** [comment]
libctru had a new release, so this is a non-issue
