### ISSUE TITLE
TwlBg broke the DSTWO card

### ISSUE THREAD

**Issue by ITJesse** [LumaTeam/Luma3DS#170]
In version 6.0.1, if I place the TwlBg.cxi in the luma folder, the DSTWO cannot start any game.

In version 6.1, I can't use it anymore.

Maybe you should provide a switcher for this feature.

**Comment by Shadow322** [comment]
No your shits broken because it works here

**Comment by ITJesse** [comment]
It freeze in a black screen when I select a game.

And everything gose well when I switch to 6.0.1 without TwlBg.cxi.

**Comment by VoltageMiner** [comment]
Although unrelated to the issue in a way, Pokemon Heart Gold freezes on a black screen after selecting and loading the save.

**Comment by cheatfreak47** [comment]
Seems to work fine on my end. I have a late model DSTwo, the one that was actually a DSTwo Plus, but has the old DSTwo Label, with no screw on the back, it's held together with glue I think.

@ThunderRemix Your save file is probably the problem, Heartgold is working fine for me.

**Comment by takeshineale128** [comment]
Also white screen on Professor Layton and the Lost Future retail card

**Comment by cheatfreak47** [comment]
@takeshineale128 I can confirm that one, happens for the DSTwo as well for that game, switched back to Luma 6.0 and it worked again.

TwlBg is clearly causing some issues with some games, so it probably should be optional via the Luma 3DS config menu.

If that's possible it's also possible that the original poster only tried games that were broken, or that older versions of the DSTwo break from TwlBg.

**Comment by VoltageMiner** [comment]
@cheatfreak47 Then why does it work for me without TwlBg patches yet work for you with them? I guess the patches aren't perfect.

**Comment by dankzegriefer** [comment]
This is not the correct place to report this. TwlBg is not an official part of Luma.

**Comment by Margen67** [comment]
@dankzegriefer The patches were added to Luma.

**Comment by dankzegriefer** [comment]
@Margen67 Hm? But OP was describing install for unofficial sysmodules? When was this added?
EDIT: Oh it was, well then

**Comment by Mrrraou** [comment]
TwlBg is not a sysmodule.

**Comment by dankzegriefer** [comment]
@Mrrraou It isn't? I thought it was a TWL SysModule.

**Comment by AuroraWright** [comment]
6.1.1 makes it selectable

**Comment by noX1609** [comment]
Hi,

i have the same Problem with Version 6.1 and 6.1.1
Haven't selected the TwlBg in Config so it should be off but the card doesn't work with 6.1.1
If i go back to 6.0.1 it works without a problem but there is the problem with the Settings that sometimes on emuNAND it shows sysNAND and in sysNAND it shows emuNAND. This is fixed in 6.1.1 but as i said the DSTwo Plus doesn't work with 6.1.1 with the patch disabled.

**Comment by irpacynot** [comment]
Having a similar issue regarding DSTWO Plus. The system (O3DS) just shuts off when trying to load the card from the Home menu. I tried installing the two cias as per the trouble-shooting FAQ, but it didn't help. I'm on Luma3DS 6.6.

**Comment by Margen67** [comment]
@irpacynot https://3ds.guide/troubleshooting

**Comment by irpacynot** [comment]
Thanks. Unfortunately, none of those links work. I would otherwise try to install all of those cias.

**Comment by irpacynot** [comment]
Never mind. I didn't realize they were torrent files. But I downloaded all of the files and tried importing them, but each one said "program already exists, import cancelled." Tried to load the flash card, but it still auto-shutdown the system.

**Comment by Margen67** [comment]
What entrypoint are you using? (A9LH, menuhax, etc) Are you using emuNAND?
