### ISSUE TITLE
After updating the device of the 2DS XL with Custom Firmware, the power does not turn on.

### ISSUE THREAD

**Issue by qlife1146** [LumaTeam/Luma3DS#1700]
I have a question. After updating the device of the 2DS XL with Custom Firmware, the power does not turn on.
I thought formatting the SD card would solve this problem. But the blue light still turned on and off immediately.
I found the recovery file and put it in, but it's still the same. Is there a solution?

**Comment by urherenow** [comment]
GitHub isn't for questions. It's for bug reports and collaboration. Ask your question in gbatemp or a discord channel. You've given next to no information, and there's a good chance the answer you need can be found through Google, as there are numerous guides for both getting cfw on a 3ds, and for general troubleshooting. There's probably dozens of cases right here in this GitHub space under closed tickets, if you would just search and read.
