### ISSUE TITLE
(10.2.1) I can't get to the title file directory.

### ISSUE THREAD

**Issue by Freddy3DS** [LumaTeam/Luma3DS#1706]
I know this isn't a help forum but I'm out of ideas. Patching is enabled and I'm using 7-zip, for whatever that's worth. I'm kinda new here, so I might just be stupid, but I really can't get to it. Code.bin and locale.txt do nothing. I do have /luma/titles/TITLE_ID/ but no matter what I put in title_id or what comes after absolutely nothing works. Anything you think I'm doing wrong?

**Comment by Shadow322** [comment]
> I know this isn't a help forum but I'm out of ideas. Patching is enabled and I'm using 7-zip, for whatever that's worth. I'm kinda new here, so I might just be stupid, but I really can't get to it. Code.bin and locale.txt do nothing. I do have /luma/titles/TITLE_ID/ but no matter what I put in title_id or what comes after absolutely nothing works. Anything you think I'm doing wrong?

This isn't a help forum go to gbatemp
