### ISSUE TITLE
Cant get into certian games and apps

### ISSUE THREAD

**Issue by Ineedhelpyo** [LumaTeam/Luma3DS#1708]
an exception occured
arm11 core 1
exception type undefined instruction
loader 00000000000000000000
press a to save crash dump
press any other button to shut down

when i try to get in games i downloaded directly from sd card, this happens

**Comment by Shadow322** [comment]
> an exception occured arm11 core 1 exception type undefined instruction loader 00000000000000000000 press a to save crash dump press any other button to shut down
> 
> when i try to get in games i downloaded directly from sd card, this happens

This is not a help forum go to gbatemp

**Comment by Ineedhelpyo** [comment]
damn bro, u comment so fast
