### ISSUE TITLE
Update `Updating` wiki instruction

### ISSUE THREAD

**Issue by ShockwaveNN** [LumaTeam/Luma3DS#1709]
Just got a notification from this thread:
https://github.com/KunoichiZ/lumaupdate/issues/97#issuecomment-1013226045

That LumaUpdate is not in development anymore and that there is `some other method to update Luma`

I think some corrections should be made on this page:
https://github.com/LumaTeam/Luma3DS/wiki/Installation-and-upgrade#upgrading

Since it mentions deprecated lumaupdate

**Comment by TuxSH** [comment]
Fixed
