### ISSUE TITLE
AGB Boot option ignored.

### ISSUE THREAD

**Issue by Autz64** [LumaTeam/Luma3DS#171]
I'm using the latest version of Luma3DS (No-Dev) and i checked the option **Show GBA boot screen in patched AGB_FIRM**. However, when i boot a GBA game the boot animation doesn't show and loads directly to the game. I erased the config.bin and setted the options again and still doesn't show the animations. 

I don't know if is relevant here, but i have the no-screeninit version of arm9loaderhax.

**Comment by Margen67** [comment]
Have you installed a patched AGB_FIRM cia?

**Comment by Autz64** [comment]
No. I can play GBA VC games normally but i can't see the intro. Should i install a clean AGB_FIRM anyways?

**Comment by cheatfreak47** [comment]
Try reinstalling AGB FIRM. @Autz64

**Comment by Autz64** [comment]
I installed a clean AGB_FIRM and now the boot animation appears. But is pretty odd, i don't remember having installed a patched AGB_FIRM in the past.
