### ISSUE TITLE
BootNTR Crashes When Selecting Version

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1710]
3DS Console:
New Nintendo 3DS XL

SysNand:
11.15-47U

Used To Boot:
Boot9strap

Current Luma3DS Version:
Latest (10.2.1)

And I Have "Show NAND Or User String In System Settings" Enabled

I Do Not Have The Crash Dump At the Moment

And I'm Really Looking Forward To Using The Unofficial Luma3DS (Nanquitas) But Before I Do I Want To See If The Problem Can Be Fixed

**Comment by Shadow322** [comment]
> 3DS Console: New Nintendo 3DS XL
> 
> SysNand: 11.15-47U
> 
> Used To Boot: Boot9strap
> 
> Current Luma3DS Version: Latest (10.2.1)
> 
> And I Have "Show NAND Or User String In System Settings" Enabled
> 
> I Do Not Have The Crash Dump At the Moment
> 
> And I'm Really Looking Forward To Using The Unofficial Luma3DS (Nanquitas) But Before I Do I Want To See If The Problem Can Be Fixed

Not a help forum and not a Luma3DS problem take it to gbatemp
