### ISSUE TITLE
Help with Luma3DS exception error Arm11 core 0

### ISSUE THREAD

**Issue by LordDimentio** [LumaTeam/Luma3DS#1711]
Hi there! I'm trying to install Homebrew on my New 3DS XL, and I've been using the steps on https://3ds.hacks.guide/, and I've gotten to the point on the https://3ds.hacks.guide/installing-boot9strap-(pichaxx) page where it says to "Launch Pokemon Picross". After launching it, I get an error screen that says this:

An exception occurred

Processor:               Arm11 (core 0)
Exception type:       prefetch abort
Fault status:            Debug event
Current Process:    Game  (000400000017C100)

Can anyone help me? Thanks

**Comment by Shadow322** [comment]
> Hi there! I'm trying to install Homebrew on my New 3DS XL, and I've been using the steps on https://3ds.hacks.guide/, and I've gotten to the point on the https://3ds.hacks.guide/installing-boot9strap-(pichaxx) page where it says to "Launch Pokemon Picross". After launching it, I get an error screen that says this:
> 
> An exception occurred
> 
> Processor: Arm11 (core 0) Exception type: prefetch abort Fault status: Debug event Current Process: Game (000400000017C100)
> 
> Can anyone help me? Thanks

No we can't help u this is not a help forum go to gbatemp kthx
