### ISSUE TITLE
ARM11 Error after update to 11.15

### ISSUE THREAD

**Issue by paulipauli130** [LumaTeam/Luma3DS#1712]
I turned on my 3ds again after a long time. My buddy then said he just had to update him. Boom: the "softbrick" was already there. My Luma3ds is on version 10.1.3. Well, in any case, I always get this ARM11 error now. I wanted to update Luma3ds to version 10.2.1 by replacing the boot.fiem and boot.3dsx on the SD card. 
But that didn't work either because I noticed that Luma3ds is loaded from the internal memory of the 3ds. In yellow font, the Luma3ds menu does not say: booted from SD Card but it says: Bootes from CTRNAND via B9S. Does anyone here have a fixed or the same problem?
![1](https://user-images.githubusercontent.com/93503779/150130830-f3b53a2d-9879-469c-99a8-ffd7a6b71748.jpeg)
![2](https://user-images.githubusercontent.com/93503779/150130928-805ecae1-a992-4ca4-8490-adcfd9df57b2.jpeg)

**Comment by TuxSH** [comment]
You haven't properly updated Luma3DS on the SD card, or your SD card is defective.

**Comment by zoracifer** [comment]
i have the same problem and i dont know what to do
