### ISSUE TITLE
mGBA Bug: Svcbreaks when booting Super mario advance 4 and Gradius galaxies and Ace Lightning roms

### ISSUE THREAD

**Issue by qahellokitty5947** [LumaTeam/Luma3DS#1715]
I've got hacked a OLD2DS with Luma3ds. Everytime it crashes after boot up with both games:
> Super mario advance 4: "Saved data is corrupted." error screens when booting.
> Gradius galaxies: After bios, the game will crash.
> Ace Lightning: After BBC logo, the game crashes right away.

**Comment by Shadow322** [comment]
> I've got hacked a OLD2DS with Luma3ds. Everytime it crashes after boot up with both games:
> 
> > Super mario advance 4: "Saved data is corrupted." error screens when booting.
> > Gradius galaxies: After bios, the game will crash.
> > Ace Lightning: After BBC logo, the game crashes right away.

None of that sounds like a Luma3DS problem and this isn't a help forum take it to gbatemp
