### ISSUE TITLE
arm 11 (core 0 error

### ISSUE THREAD

**Issue by CrazyCanadian02** [LumaTeam/Luma3DS#1716]
error happens when trying to open fbi or setings regardless of sd being in or not
![IMG_8269](https://user-images.githubusercontent.com/82821380/153359746-2f280923-a54e-4ab9-b1ea-212273d6cd0f.jpg)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
