### ISSUE TITLE
Data Abort Exception crash in Dillon's Dead-Heat Breakers NA Version

### ISSUE THREAD

**Issue by iceknight84** [LumaTeam/Luma3DS#1719]
**System model:**

Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.15.0-47U

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v10.2.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Off)

Splash duration: (1)

PIN lock: (Off)

--

Enable loading external FIRMs and modules: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

--

**Explanation of the issue:**
While playing the NA version of Dillon's Dead-Heat Breakers that I installed via a .cia file, the game appears fine at first as the intro level plays properly, but upon having to exit into the lobby after the cutscene about your character's village, the game crashes and I see an exception screen saying that its a data abort exception with the fault being a "translation - section". I have checked the SD card with h2test and it has no flaws and I already tried importing the seed with FBI and the game still crashes. I have no idea why this is happening at this point.

**Steps to reproduce:**

1. Install the NA .cia version of Dillon's Dead-Heat Breakers and play the intro level.

2. Upon attempting to go into the lobby after the cutscenes after the intro level, the crash happens.

**Dump file:**

[Dillon's DHB Crash Dump.zip](https://github.com/LumaTeam/Luma3DS/files/8149071/Dillon.s.DHB.Crash.Dump.zip)

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
