### ISSUE TITLE
Arm11 Core 1 Exception When Opening Notifications app

### ISSUE THREAD

**Issue by poorlydrawnproot** [LumaTeam/Luma3DS#1724]
![WIN_20220316_14_26_00_Pro](https://user-images.githubusercontent.com/100108102/158674229-cb220dda-1971-44ad-b2ee-fa7fdf0719d8.jpg)
the notifications app started doing this and its driving me insane, does anyone have a fix other than formatting the system memory?

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
