### ISSUE TITLE
[Feature Request] Make Rosalina blueshift screen filter persistant after reboot 

### ISSUE THREAD

**Issue by ekirchman** [LumaTeam/Luma3DS#1725]
Currently, after a reboot, the screen filter option gets reset back to the default value. It would be convenient if it stayed at the value which the user set it as previously.

**Comment by ghost** [comment]
I'd like to add that it would be nice if user settings could be made persistent in general, such as the power LED toggle.

**Comment by TuxSH** [comment]
Done in latest commit
