### ISSUE TITLE
my last issue was closed but wasn't actually fixed

### ISSUE THREAD

**Issue by TroyTT4** [LumaTeam/Luma3DS#1728]
**System model:**

[New 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.15.0-47U SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[v10.3]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (off)

Splash duration: (1)

PIN lock: (off)

New 3DS CPU: (off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (unchecked)

Enable game patching: (unchecked)

Show NAND or user string in System Settings: (unchecked)

Show GBA boot screen in patched AGB_FIRM: (unchecked)

Set developer UNITINFO: (unchecked)

Disable Arm11 exception handlers: (unchecked)

Enable Rosalina on SAFE_FIRM: (unchecked)

--

**Explanation of the issue:**
this issue started happening last summer(I think) and I haven't found a way to get rid of it. when I play any game on my New3DS, I will get random arm 11 crashes, and I have no idea what's causing it. I was really hoping that v10.3 would fix it and I decided to test by playing Kirby Triple deluxe on it. Three levels in and it crashed. these random crashes have happened on almost any game that I've played on my New3DS. Kirby, Mario kart 7/CTGP7, Miitopia, tomodachi life, mii plaza(it's only crashed on the RC car game though and had some audio bugs on flower town), etc. if the New3DS crashes and I try playing a game again immediately after, it will crash again faster than if I wait until later or the next day to play again. if it crashes too many times in a short amount of time then it will go into a temporary brick state for a few hours. also It's extremely likely to crash if I close the lid and leave it in sleep mode.

**Steps to reproduce:**

1. IDK

2. it's random. the only consistency is closing the lid and leaving it in sleep mode for a few minutes.

**Dump file:**

[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8312053/crash_dump_00000000.zip)

I'm not 100% sure if these are the crash dumps but these were in the dumps folder in the luma folder on the SD card so they probably are. if not then I can type out the crash error I got when testing with Kirby triple deluxe and a few older crash errors that I also took pictures of

**Comment by oreo639** [comment]
This isn't a help fourm. I can't reproduce the issues described. The issue template has a link to the Nintendo Homebrew discord server, I'd recommend you try asking there for help. If you later do find that any of these issues are the result of Luma3DS and not something else, feel free to make a bug report about that.
