### ISSUE TITLE
Forgot PIN, don't have sd card reader

### ISSUE THREAD

**Issue by anseriformas** [LumaTeam/Luma3DS#1731]
New 3DS XL
Luma 10.3
Boot9Strap

**Comment by impeeza** [comment]
hi, this is a issue report space, please give more information about the issue/bug, if you need help, go to discord or GbaTemp or any support site. also on google there are several guides about removing LUMA PIN even on the readme there are instructions.

**Comment by anseriformas** [comment]
Thank you for that reminder but I managed to fix it.
