### ISSUE TITLE
Is there a way to switch the temperature display from Celsius to Fahrenheit?

### ISSUE THREAD

**Issue by ArguaBILL** [LumaTeam/Luma3DS#1732]
If there isn't, would it be possible to add the ability to switch the temperature display from Celsius to Fahrenheit?

**Comment by Masamune3210** [comment]
Celsius is used for 99% of tech stuff when it comes to temperatures, fahrenheit wouldnt be really useful

**Comment by eku** [comment]
Please don't use imperial units. SI rules the world.

**Comment by Shadow322** [comment]
Yes add Fahrenheit

**Comment by ELY3M** [comment]
yes, it is easy to convert C to F   I think it should be based on settings or config.  people should have choice on C or F.   
I would prefer F.

**Comment by TuxSH** [comment]
No, there's is no way to switch units (yet, anyway), and:

1. The MCU itself reports the temperature in Celsius degrees; and Luma doesn't have any kind of internationalization support
2. 
![image](https://user-images.githubusercontent.com/1922548/163460013-1400b791-f6e8-4db8-b262-be10346db94f.png)
