### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by cmarcom** [LumaTeam/Luma3DS#1733]
I'm triyng to update to lastest version, but it fails and throws me an error on "Integrity check [2]": 
"MD5 mismatch between server's and local file
FATAL
Could not get sighax payload..."

I'm sorry if I got wrong posting here. Thanks.
![IMG20220326105047](https://user-images.githubusercontent.com/38864376/160234319-14b143b4-25c6-4847-96bd-4a2d6e070a33.jpg)

**Comment by Shadow322** [comment]
Not a help forum take it to gbatemp

**Comment by urherenow** [comment]
This is the Luma3DS page anyway, not the Luma3DS updater page.

**Comment by cmarcom** [comment]
Yeah case close.

Thank you, I got it now!
