### ISSUE TITLE
After upgrading to Luma 10.3, there is a fatal error in Luma Locale Switcher 

### ISSUE THREAD

**Issue by SofyUchiha** [LumaTeam/Luma3DS#1734]
After updating Luma to the latest version, it is impossible to start Luma Locale Switcher (either via cia or x3ds)
Attached photo of the "fatal error": 

![image](https://user-images.githubusercontent.com/70182567/160269131-a9592322-83b8-4615-834f-410432f76e86.png)

Is there a setting to fix it?

**Comment by Shadow322** [comment]
Your on the wrong github
