### ISSUE TITLE
Outdated info in Wiki section regarding upgrading

### ISSUE THREAD

**Issue by twocows** [LumaTeam/Luma3DS#1735]
https://github.com/LumaTeam/Luma3DS/wiki/Installation-and-upgrade
"You can manually update Luma3DS by repeating "Installation" above, but we recommend using [KunoichiZ's fork of Hamcha's LumaUpdate](https://github.com/KunoichiZ/lumaupdate/releases/latest)."

That repo is no longer maintained and currently doesn't work. Should probably replace with something about universal-updater or whatever solution is preferred currently.

(Also, if U-U doesn't update the NAND version, that might be worth noting too)

**Comment by TuxSH** [comment]
Good point. I need to update the wiki someday.

**Comment by ShockwaveNN** [comment]
This issue is duplicate of my older issue, which has no response 

https://github.com/LumaTeam/Luma3DS/issues/1709

**Comment by Chlorus** [comment]
This is still an issue. It's kind of funny to watch the maintainer grow increasingly frustrated that people keep opening issues on his repo: https://github.com/KunoichiZ/lumaupdate/issues/101#issuecomment-1071992125

**Comment by ShockwaveNN** [comment]
@Chlorus I was ready to contact the maintainer about this, but all issues are blocked so I cannot comment in any way (

**Comment by Shadow322** [comment]
> This is still an issue. It's kind of funny to watch the maintainer grow increasingly frustrated that people keep opening issues on his repo: [KunoichiZ/lumaupdate#101 (comment)](https://github.com/KunoichiZ/lumaupdate/issues/101#issuecomment-1071992125)

Has not been an issue ever since Universal Updater replaced it

**Comment by ShockwaveNN** [comment]
> Has not been an issue ever since Universal Updater replaced it

No, it is an issue since [Luma3DS documentation](https://github.com/LumaTeam/Luma3DS/wiki/Installation-and-upgrade#upgrading) clearly states that you need to use LumaUpdate

**Comment by Shadow322** [comment]
> > Has not been an issue ever since Universal Updater replaced it
> 
> No, it is an issue since [Luma3DS documentation](https://github.com/LumaTeam/Luma3DS/wiki/Installation-and-upgrade#upgrading) clearly states that you need to use LumaUpdate

https://github.com/LumaTeam/Luma3DS/issues/1735#issuecomment-1081054831

**Comment by ShockwaveNN** [comment]
> https://github.com/LumaTeam/Luma3DS/issues/1735#issuecomment-1081054831

Good luck telling some inexperienced users that documentation is wrong but some comment is some-issue-you-need-to-find - contains correct info

**Comment by TuxSH** [comment]
Fixed.
