### ISSUE TITLE
Freeze on entering Sleep Mode with exception handlers disabled

### ISSUE THREAD

**Issue by FunniFlow** [LumaTeam/Luma3DS#1736]
**System model:**

New Nintendo 3DS XL (Galaxy Edition)

**SysNAND version (+emu/redNAND version if applicable):**

11.15.0-47U

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

10.3 stable

**Luma3DS configuration/options:**

Default EmuNAND: (n )

Screen brightness: ( 4)

Splash: ( n)

PIN lock: ( n)

New 3DS CPU: (n )

--

Autoboot EmuNAND: ( n)

Use EmuNAND FIRM if booting with R: (n )

Enable loading external FIRMs and modules: ( n)

Enable game patching: ( y)

Show NAND or user string in System Settings: ( y)

Show GBA boot screen in patched AGB_FIRM: ( n)

Set developer UNITINFO: (n )

Disable Arm11 exception handlers: ( y)

Enable Rosalina on SAFE_FIRM: ( n)

--

**Explanation of the issue:**
I close the system, I open it up and the screen is frozen.

**Steps to reproduce:**

1. Close system with exception handlers disabled

2.Screen frozen

**Dump file:**

It's freezing, so no crash dump.

**Comment by TuxSH** [comment]
> It's freezing, so no crash dump.

> with exception handlers disabled

Yeah, right...

I can't help you if you have those disabled, sorry.
