### ISSUE TITLE
New commit on first startup has yellow screen when i reboot its fine

### ISSUE THREAD

**Issue by SuperTechTrics** [LumaTeam/Luma3DS#1737]
This will require a fix on the latest luma3ds commit
![yellow](https://user-images.githubusercontent.com/68786370/160511696-f82782cd-95a3-45a3-a60b-5c51ebb090cd.png)

**Comment by Shadow322** [comment]
happen on both my New 3DS XL and New 2DS XL always on first boot
![20220328_204024](https://user-images.githubusercontent.com/15938645/160516448-af226125-ab28-4c28-88ad-5a3a4ebc2280.jpg)
