### ISSUE TITLE
Sleep mode download not work

### ISSUE THREAD

**Issue by celula82** [LumaTeam/Luma3DS#174]
In 6.0, 6.0.1 and 6.1, sleep mode download not work, the console ask update, but I have 11.0 arm9. In 5.5 works fine.

![](https://pbs.twimg.com/media/Cqta0H5WIAAWQpz.jpg)

**Comment by thejsa** [comment]
I can confirm this. Trying to use Sleep Mode Download does, in fact, yield a System Update message ("In order to use this function, you must perform a System Update." etc)

**Comment by TuxSH** [comment]
Hm, this is a known bug, try switching the option "use sysnand firm if booting with R"

**Comment by celula82** [comment]
The use sysnand firm if booting with R option dont fix this. Only works in 5.5 with sysNAND is updated option. Why close this if it is not fix?

**Comment by AuroraWright** [comment]
Likely fixed in 6.1.1

**Comment by Margen67** [comment]
Is there a firmware.bin in the luma folder? If so, try deleting it.

**Comment by celula82** [comment]
No firmware.bin in luma folder. Error is in 6.1.1 too, but only en my new normal. I have a XL version and with 6.1.1 its works fine OK.

**Comment by celula82** [comment]
@AuroraWright  Trying to use Sleep Mode Download does, in fact, yield a System Update message ("In order to use this function, you must perform a System Update." etc) in all 6.XX version of luma (6.1.1 incl.) and only works in 5.5 in my normal new 3ds. My new 3ds XL works well with luma 6.1.1 and sleep mode download. I have the same archives in te sd cards! Why? Please, help.
