### ISSUE TITLE
Displaying cheat titles wider than screen

### ISSUE THREAD

**Issue by AuditeMarlow** [LumaTeam/Luma3DS#1740]
Often I come across cheats with titles wider than the screen is capable of displaying. This results in obfuscation of what the cheat is or does. Are there options to apply wrapping or scroll horizontally to get the entire title to display?

**Comment by TuxSH** [comment]
I'll have a look

**Comment by TuxSH** [comment]
Alas it's limited to 37~38 chars by design... you should simplify the cheat's title if it's too long
