### ISSUE TITLE
arm9 data abort for tomodachi life

### ISSUE THREAD

**Issue by septichacker** [LumaTeam/Luma3DS#1742]
it only happens in tomodachi life, is it a bad save or a corrupted cart?
It happens when the 3rd item appears on the loading screen

luma: v10.3-f2e17d30-3gxldr
3dsxl: sys v11.15.0-47
![IMG_20220411_183039](https://user-images.githubusercontent.com/49598503/162798052-90b0c18a-61a2-478e-b833-e1b91ec93375.jpg)
E

**Comment by septichacker** [comment]
i dont think this could be reproducible btw

**Comment by hurda** [comment]
https://github.com/LumaTeam/Luma3DS/issues/1739#issuecomment-1089353996
>ARM9 errors are caused by a faulty or corrupted SD card. You will need to format the SD card to FAT32 again or replace it with another one.

**Comment by septichacker** [comment]
so is it a corrupted save or is my whole sd card corrupted because i never get any other arm9 errors with anything

**Comment by septichacker** [comment]
well, your suspisions were correct, my sd card soon then failed to read and had to be formatted.

**Comment by septichacker** [comment]
issue resolved after a quick format :D
