### ISSUE TITLE
Official 3GX plugin support?

### ISSUE THREAD

**Issue by Yrouel** [LumaTeam/Luma3DS#1743]
I wanted to try CTGP-7 (Mario Kart 7 mod) and it requires a fork of Luma3DS with the support for this type of plugins.

I also saw this closed pull request to add the feature on the main version (#1526 adding 3gx plugin support officially) and I was wondering why it wasn't actually implemented also as a way to focus the development efforts on one version instead of you know multiplying such effort.

So yeah consider this a feature request

**Comment by Querela** [comment]
I found https://github.com/Nanquitas/Luma3DS/releases linked in some forum (https://gbatemp.net/threads/release-luma3ds-v10-1-3-3gx-plugins-edition-unofficial.569002/) when I searched for `3gx` since I did not know what is really is. Seems up-to-date, but not sure how well it works.

**Comment by Dimensional** [comment]
It's pretty good, though they still are working out the kinks for the plugin libraries. Some games will fail to work with their plugins, such as old SDK games like Pokemon Dream Radar, which I've personally tested. However when not using plugins, the number of crashes I've had are pretty much the same with here. There may be a few times where things could break that don't break with this version, but that's more or less a game/app by game/app basis.

**Comment by moldimolt** [comment]
https://github.com/LumaTeam/Luma3DS/pull/1526 adding this feature was not accepted for merging.
