### ISSUE TITLE
3ds crashes on activating cheats 

### ISSUE THREAD

**Issue by Loza76** [LumaTeam/Luma3DS#1744]
I dont think the latest firmware runs the latest version of Luma3ds as it crashes every time I activate a cheat code on any game.

**Comment by Shadow322** [comment]
> I dont think the latest firmware runs the latest version of Luma3ds as it crashes every time I activate a cheat code on any game.

Latest Luma3DS works fine quit using cheats

**Comment by lemaximedu66** [comment]
please upload a log for the creators.

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
