### ISSUE TITLE
Configuration screen opens when it should not

### ISSUE THREAD

**Issue by t33st33r** [LumaTeam/Luma3DS#1745]
Hello,
I use both your original and Nanquitas' mod of Luma3DS.
Configuration screen opens every time I switch on booting from one payload to another. It opens no matter if select key is pressed or not, it ignores the the fact that the configuration file is present. The configuration screen reset all values every single time this happen.

Can you fix it? Please.

**Comment by oreo639** [comment]
> it ignores the the fact that the configuration file is present

Luma checks if the configuration file is compatible with the current version and will create a new one if it is not. If you are switching between two versions of Luma with incompatible configuration files, you will be asked to update your settings.

**Comment by t33st33r** [comment]
> 

Both my payloads are up to date (10.3 base). Why should the config files not be compatible?

**Comment by oreo639** [comment]
Probably because one adds options that don't exist in the other, which causes the size check to fail. (otherwise one may misinterpret the options of the other, due to how it they are stored in the config.bin)

**Comment by t33st33r** [comment]
OK thanks.
Now I need to find a way to contact Nanquitas. The project doesn't have section to post issues.

**Comment by PabloMK7** [comment]
I'm maintaning the plugin loader branch. This issue will no longer happen after the next release, as configuration will be loaded from an ini file.

**Comment by moldimolt** [comment]
No longer an issue as of v11.0.
