### ISSUE TITLE
Prefetch abort svcbreak in process pxi when turning on

### ISSUE THREAD

**Issue by f4arm4** [LumaTeam/Luma3DS#1747]
I get this arm11 exception type prefetch abort svcbreak when turning the 3ds on 
[crash_dump_00000005.zip](https://github.com/LumaTeam/Luma3DS/files/8608184/crash_dump_00000005.zip)

**Comment by TuxSH** [comment]
Can you reproduce this with another 3ds? Is it consistent, and is it just you?

**Comment by moldimolt** [comment]
Closing as a tech support question; the issue tracker is not for tech support, try Nintendo Homebrew's assistance channels (https://discord.gg/C29hYvh).
