### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by HideakiAtsuyo** [LumaTeam/Luma3DS#1750]
Hello I just found an old 3DS XL where Luma is installed and forgot the pin (6 digits) is there any way to get rid of it ?

**Comment by impeeza** [comment]
Yes: reading the documentation on the OP of this github

The pin can be bypassed deleting Luma's config.

simple and plain as that.

**Comment by HideakiAtsuyo** [comment]
> Yes: reading the documentation on the OP of this github
> 
> The pin can be bypassed deleting Luma's config.
> 
> simple and plain as that.

Yeah after crating the issue I tried to overwrite the pin file but instead of using the new code it disabled it, it's perfect ! Thanks anyway :)
