### ISSUE TITLE
Crash when trying to dump memory in AC:NL

### ISSUE THREAD

**Issue by EnbyAce** [LumaTeam/Luma3DS#1751]
**System model:** Old 2DS

**SysNAND version (+emu/redNAND version if applicable):** 11.15-0-47E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** v10.3

**Luma3DS configuration/options:**

Screen brightness: (4)

Splash: (Before)

Splash duration: (3)

PIN lock: (Off)

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

**Explanation of the issue:**
When trying to dump memory in Animal Crossing: New Leaf, my 2DS crashes.

**Steps to reproduce:**

1. Start AC:NL
2. Open Rosalina menu (L+DOWN+SELECT)
3. Go to Process list
4. Select the `GARDEN` process (AC:NL)
5. Press R to switch to code
6. Press SELECT

**Dump file:**
[crash_dump_00000002.zip](https://github.com/LumaTeam/Luma3DS/files/8691039/crash_dump_00000002.zip)

**Comment by moldimolt** [comment]
Duplicate: #1398
