### ISSUE TITLE
An exception occurred; Arm11 (core 0); data abort; Translation - Section

### ISSUE THREAD

**Issue by CaesarYP** [LumaTeam/Luma3DS#1752]
New 3DS LL

**SysNAND version (+emu/redNAND version if applicable):**

[11.15.0-47J SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[10.3]

**Luma3DS configuration/options:**

Enable game patching: ( yes)

Show NAND or user string in System Settings: ( yes)

**Explanation of the issue:**
I'm playing Zelda the Minish Cap, but every time I enter this place, the system crashes after a few seconds.
The cia file of the game is exported by NSUI, using Retroarch Gpsp forwarder.
![IMG_20220518_234620](https://user-images.githubusercontent.com/90097973/169088256-4f698672-b968-4136-9ea5-4ed15637130b.jpg)

https://user-images.githubusercontent.com/90097973/169088294-a71448d3-b829-486b-a303-77cc42c2202e.mp4

**Steps to reproduce:**

1.enter this room

2.wait for a few seconds

**Dump file:**
-- The error message will tell you where the dump is.
-- Zip the dmp file and drag & drop it below.-->
[crash_dump_00000002.zip](https://github.com/LumaTeam/Luma3DS/files/8718025/crash_dump_00000002.zip)

**Comment by impeeza** [comment]
Hello, this is a space for Issues and bug reports, for support please go to gbatemp Discord or similar sites.  saying that, your problem is a bad ROM image, get another from different source.

**Comment by alnnns** [comment]
> New 3DS LL
> 
> **SysNAND version (+emu/redNAND version if applicable):**
> 
> [11.15.0-47J SysNAND]
> 
> **Entrypoint (How/what you're using to boot Luma3DS):**
> 
> [Boot9Strap]
> 
> **Luma3DS version:**
> 
> [10.3]
> 
> **Luma3DS configuration/options:**
> 
> Enable game patching: ( yes)
> 
> Show NAND or user string in System Settings: ( yes)
> 
> **Explanation of the issue:** I'm playing Zelda the Minish Cap, but every time I enter this place, the system crashes after a few seconds. The cia file of the game is exported by NSUI, using Retroarch Gpsp forwarder. ![IMG_20220518_234620](https://user-images.githubusercontent.com/90097973/169088256-4f698672-b968-4136-9ea5-4ed15637130b.jpg)
> 
>  video_20220518_234648.mp4 
> 
> **Steps to reproduce:**
> 
> 1.enter this room
> 
> 2.wait for a few seconds
> 
> **Dump file:** -- The error message will tell you where the dump is. -- Zip the dmp file and drag & drop it below.--> [crash_dump_00000002.zip](https://github.com/LumaTeam/Luma3DS/files/8718025/crash_dump_00000002.zip)

Hey did u find a solution ?

**Comment by CaesarYP** [comment]
I copied the save file to my PC and used retroarch emulator on PC to continue my game 😂
