### ISSUE TITLE
Luma Updater Failure.

### ISSUE THREAD

**Issue by De-Been-Tech-Solutions** [LumaTeam/Luma3DS#1754]
![16534151816519144843830561983190](https://user-images.githubusercontent.com/60248725/170102109-0e8c33cb-656f-4063-85d3-a87cda35e7e7.jpg)

Download failed.

I am requesting a fix please.

**Comment by oreo639** [comment]
Luma Updater is a third party project that has no relation to Luma3DS, and regardless this is the wrong repo to report bugs with it. (The correct repo is stated in the very screenshot you posted)

Also, as per:
https://github.com/KunoichiZ/lumaupdate#luma-updater
Luma Updater will not be receiving any new updates anyway.

**Comment by De-Been-Tech-Solutions** [comment]
Righto, does this mean that you've passed it on?

**Comment by oreo639** [comment]
No. Luma Updater is not maintained anymore and will not receive updates.

The next release of Luma3DS will add a system for copying itself to the nand when it has been updated so hopefully that will help.
https://github.com/LumaTeam/Luma3DS/commit/d798ff0efcac93af068bdfa0e01b056c725899ab
