### ISSUE TITLE
3ds dont start after installing

### ISSUE THREAD

**Issue by DarkNightSwe** [LumaTeam/Luma3DS#1755]
https://user-images.githubusercontent.com/106544109/171020695-67fc4523-90b1-43ee-b7ec-b9135d8079fa.mp4

When i try to start my 3ds it the notification led lights up in the color of white and turns of again. And this started to happen when i tried to download this.

**Comment by impeeza** [comment]
this space is for bugs reports, please go to correct channels for support, on gbatemp there is a thread about this issue, you can search it and get the answer.

regards.

**Comment by DarkNightSwe** [comment]
> this space is for bugs reports, please go to correct channels for support, on gbatemp there is a thread about this issue, you can search it and get the answer.
> 
> regards.

Could You Paste an Link to one that could help me?

**Comment by impeeza** [comment]
Google.com -> discord luma3ds
Google.com -> gbatemp
gbatemp.net  -> search -> luma3ds or 3ds brick

Etc. You get the idea

**Comment by TuxSH** [comment]
https://discord.gg/C29hYvh

Your video is very blurry too. I'm not sure if the LED is red or magenta:
- SD FIRM missing, CTRNAND FIRM corrupt: magenta
- SD FIRM corrupt, CTRNAND FIRM also corrupt: red

You've done something wrong when installing. Make sure boot.firm is properly located on the root of your SD card.

**Comment by rpdistiso** [comment]
> https://discord.gg/C29hYvh
> 
> Your video is very blurry too. I'm not sure if the LED is red or magenta:
> 
> * SD FIRM missing, CTRNAND FIRM corrupt: magenta
> * SD FIRM corrupt, CTRNAND FIRM also corrupt: red
> 
> You've done something wrong when installing. Make sure boot.firm is properly located on the root of your SD card.

He said it was white
