### ISSUE TITLE
3ds crashes on startup

### ISSUE THREAD

**Issue by mikitakahazekura** [LumaTeam/Luma3DS#1758]
System model: New 3DS

SysNAND version: 11.2.0-35E SysNAND

Entrypoint (How/what you're using to boot Luma3DS): Boot9Strao 1.4

Luma3DS version: v11.0 stable

**Luma3DS configuration/options:**

Screen brightness: (1)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

The 3DS crashes on startup with an exception because of the process "boss" (Title ID: 0004013000003402). The network light comes on, so my assumption is that it crashes when most of the operating system is already loaded.

Processor: ARM11
Exception type: data abort
Fault Status: Translation - Section
Current Process: boss (Title ID: 0004013000003402)

I have tried to delete my home menu extdata. Its located in
/Nintendo 3DS/(32 Character ID)/(32 Character ID)/extdata/00000000/, delete the 0000008f folder located there
(i have deleted the 00000098 folder for EU Region 3ds). But the crash persists.

**Steps to reproduce:**

1. Power on the 3DS.

2. Wait 10-ish seconds.

3.  Done!

**Dump file:**
[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8864640/crash_dump_00000000.zip)

**Comment by moldimolt** [comment]
The issue tracker is not for tech support, please try Nintendo Homebrew (https://discord.gg/ZdqEhed).
