### ISSUE TITLE
Unable to make memory pages executable with svcControlProcessMemory

### ISSUE THREAD

**Issue by Hextator** [LumaTeam/Luma3DS#1759]
**Edit: I'm stupid and** didn't check which registers I was loading stack arguments for my `svcControlProcessMemory` wrapper; **it turns out `svcControlProcessMemory` is working fine on my end**. **The part at the end** about suggested features for Rosalina's Gateshark trainer implementation **may still be relevant**. If that should be a separate issue (and properly classified as a feature request rather than an actual issue), I can write something up if requested, or someone else can, **but this issue can be closed**. I'll leave it open (I probably can't close it myself anyway; I didn't check) for the moment in case it helps with getting someone's eyes to glance toward the suggestion in the last paragraph.

For anyone else having issues with `svcControlProcessMemory`, don't forget to call custom svc 0x94 `svcInvalidateEntireInstructionCache` (or the range specific variant svc 0x93 `svcInvalidateInstructionCacheRange`) if you are writing any code to memory from your other code.

`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

Interpret the title as more of a placeholder than an actual description of the issue, as I am not sure which parts of my issue are within the scope of what Luma can achieve. For context, the code described below is being executed in an executable memory page I have found available to write to within a commercial game (Kid Icarus: Uprising (USA); process name `apollo`), and the code, and the hook to it, were written using the Rosalina sysmodule's Gateshark cheat system implementation.

`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

There are 2 cases of things I've tried that are of concern, both having unexpected or undesirable results, so I'll include the results I had as well as what behavior I was expecting in the event of a successful result code.

For case 1:
```cpp
	svcResult = svcControlProcessMemory(
		handleAppProcess,
		RWX_ALLOCATION_ADDRESS, // Multiple of 0x1000
		NULL,
		RWX_ALLOCATION_SIZE, // Multiple of 0x1000
		MemoryOperation(MEMOP_PROTECT), // 6
		MemoryPermission(MEMPERM_RWX) // 7
	);
```
What I expected was for the memory at `RWX_ALLOCATION_ADDRESS` to become simultaneously readable, writable, and executable.
~~What I got instead was error code `0xD9001BF7`, suggesting an invalid handle. However:~~
```cpp
svcResult = svcGetProcessID(&pID, HANDLEALIAS_ACTIVEPROCESS);
// [...]
svcResult = svcOpenProcess(&handleAppProcess, pID);
```
or, in another case:
```cpp
svcResult = svcDuplicateHandle(&handleAppProcess, HANDLEALIAS_ACTIVEPROCESS);
```
In both of these cases, the result code was `0x00000000`, and more importantly
```cpp
svcResult = svcGetProcessID(&pID, handleAppProcess);
```
returned the original process ID (also with result code `0x00000000`) when the "real" handle was used.
As well,
```cpp
svcResult = svcTranslateHandle(&kernelAddress, (char*)(CONTEXT_FUSIONGRID_SAFERWADDRESS + 32), handleAppProcess);
```
returned the same value for `kernelAddress` as had been supplied as the `handleAppProcess` argument, and the resulting `outClassName` printed into the memory was the string "KProcess". The handle being sufficiently useful for acquiring the process ID, as well as being classified as a "KProcess" handle by `svcTranslateHandle`, suggests the handle is indeed valid. ~~However, the error code returned by `svcControlProcessMemory` specifically suggests that it is the `Handle` argument that is erroneous~~.

Now, for the 2nd part of the issue, I attempted to circumvent the need for `svcControlProcessMemory` entirely by making use of the kernel extension `svcControlMemoryEx`.
```cpp

	svcResult = svcControlMemoryEx(
		&outAddr,
		RWX_ALLOCATION_ADDRESS, // Multiple of 0x1000
		NULL,
		RWX_ALLOCATION_SIZE, // Multiple of 0x1000
		MemoryOperation(MEMOP_PROTECT), // 6
		MemoryPermission(MEMPERM_RWX) // 7
	);
```
What I expected was actually what I got, which was the error code `0xE0E01BEE`, which I understand to mean "invalid argument combination". This seems to be in reference to the `MEMPERM_EXECUTE` flag being included in the permissions bits, which is not valid for `svcControlMemory`, and presumably is not valid for `svcControlMemoryEx` either. **As a proposed resolution to this issue, I suggest that `svcControlMemoryEx` be modified to support reprotecting memory with with execution permissions**, though I am not familiar with whether that is possible.

Edit: Since `svcControlProcessMemory` actually works, and this whole post is just here because I made a dumb, perhaps a fork in the svc 0xA2 wrapper, between using svc 0xA2 and svc 0x70, depending on the `MemoryPermission` argument to `svcControlMemoryEx`, could be used to expand the functionality of the 0xA2 custom SVC? We could make the assumption that the current process handle should be used and fetch that, then close the handle afterward, though the assembly code footprint for svc 0xA2 would be a bit bloated as a result. In any case, I think **it would be very nice to have a memory altering svc that supports adding code execution permissions to pages of the current process without needing to manually obtain the handle to the current process**.

~~I do not understand why `svcControlProcessMemory` is rejecting the current process's real handle (remember, I am not using the alias)~~, and I do not believe SVC extension `svcControlMemoryEx` serves all of the purposes it should if it does not support making memory pages executable, at least while having access to `svcControlProcessMemory` from ARM11 userland is ineffective.

`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

I believe that the impacts of this issue (if it's an actual issue and not just a user error (which it was)) are relevant, because of 3 cases:
1. It's very convenient to be able to map executable memory for Gateshark codes and circumvent the need for a ROM patch for otherwise simple modifications.
2. As I understand it, dynamic recompilation for homebrew emulators is impractical without functional use of `svcControlProcessMemory` available to user applications.
3. In the Rosalina source code, an attempt to implement the code type `0xF0F00000`, which is supposedly meant to enable code creators to have the Rosalina trainer jump into their code, located just after the code type designation, was marked with the comment `// I have no clue how to implement this, or if it's even possible. Needs research."` I presumed this may be due to the author of the comment realizing there would be difficulties with making Rosalina trainer data memory pages executable, and such a code type was very powerful and important for NDS Action Replay codes (which seem to be the origin of the Gateshark format).

`~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

I would also like to note that, in addition to the `0xF0F00000` code type implementation for Rosalina's Gateshark themed trainer, another useful code type would be one that sets the data value within the trainer's state to the address of the code creator's code, rather than having the Rosalina trainer jump into it, so that the code creator could use other code types (like the `0XXXXXXX` or `D6000000` code types) to write hooks elsewhere in memory that lead directly into the assembly code included within the trainer data after this hypothetical code type. Such code types would actually solve this issue, at least partially, as having both should suit any need for making memory pages executable that doesn't require the user's code to be executed at a specific location.

It may also be convenient to have a Rosalina code type that makes a page aligned section of memory executable. It seems the trainer already invalidates the instruction cache after execution, ensuring user code loaded by the trainer is executed properly, so there probably won't need to be any extra consideration, beyond having the trainer make the specified memory range executable, with respect to giving users of the trainer the behavior they expect.

**Comment by moldimolt** [comment]
Per requester's edit, closing this. For the feature request, please feel free to open a new feature request issue as you mentioned.
