### ISSUE TITLE
Pokemon Rumble Blast Impossible to Play

### ISSUE THREAD

**Issue by 0reo1** [LumaTeam/Luma3DS#1760]
**System model:**

New 3DS XL (Japanese LL Version)

**SysNAND version (+emu/redNAND version if applicable):**

Sys 11.15.0-47J
**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9strap

**Luma3DS version:**

Tested on v10.3 & v11.0

**Luma3DS configuration/options:**

Default EmuNAND: (N/A)

Screen brightness: ( 4)

Splash: (Before)

Splash duration: (3)

PIN lock: (None)

New 3DS CPU: (None)

--

Autoboot EmuNAND: (N/A)

Use EmuNAND FIRM if booting with R: (N/A)

Enable loading external FIRMs and modules: (Enabled)

Enable game patching: (Tested on & off)

Show NAND or user string in System Settings: (Enabled)

Show GBA boot screen in patched AGB_FIRM: (Disabled)

Set developer UNITINFO: (Disabled)

Disable Arm11 exception handlers: (Tested on & off)

Enable Rosalina on SAFE_FIRM: (Disabled)

--

**Explanation of the issue:**

Anytime I attempt to launch Pokemon Rumble Blast, regardless of whatever format it's installed from it crashes the system upon launching the game 

**Steps to reproduce:**

1. Launch Rumble Blast, and ARM11 error crashes system

2. If Disable Arm11 exception handlers is checked, the system still gives an error and cannot launch the game, regardless of means of installation
**Dump file:[crash_dump_00000003.zip](https://github.com/LumaTeam/Luma3DS/files/8866980/crash_dump_00000003.zip)**
<!--If the issue leads to a crash you must uncheck the "Disable Arm11 exception handlers" option.

**Comment by oreo639** [comment]
I can't reproduce this.
Also, disabling exceptions handlers is rarely the solution and without the crash dump, there's not really anything that can be said.

**Comment by 0reo1** [comment]
> 

Oh I attempted uploading the dump but I guess it didn't go through, will reupload it in a moment
