### ISSUE TITLE
ARM 11 PRE-ABORT (svcBreak) Depuration event

### ISSUE THREAD

**Issue by AlexRedlock** [LumaTeam/Luma3DS#1761]
**System model:**

[New 2DS XL]

**SysNAND version (+emu/redNAND version if applicable):**

[11.15.0-47U SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**

v11.0 stable
**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Off)

Splash duration: (3)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (Off)

Enable game patching: (On)

Show NAND or user string in System Settings: (On)

Show GBA boot screen in patched AGB_FIRM: (Off)

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
After updating the luma version of my nintendo 2ds xl, i could play tomodachi life (for example cuz happens in ports like ddlc) in Eur in ES without a problem, but when i updated the luma version (with LumaUpdater.cia), first of all the screen dont even turn on (well in theory, it was on, but just was the screen in black), just the LED was turn on, without turning off, i was thinking that it was updating the information, but after 1 hour it didn't turn on, so i rebooted the nintendo, and again didn't turn on, the only thing that make something apear in the screen was the luma settings, then i decided to re-make the things that i did when nintendo "banned" Luma, just turning the screen off, but now with the new version, and turn on, then i deleted almost everything in the sd card (maybe something important dunno, but not the boot.firm/3dsx, and re-installed every app i had with HShop, and then the error apeared, i tried with the GodMode Solution, it didn't work, same with the Luma Locale Switcher, it apears to happen with animations or effects in the games/sistem, cuz the same happen with the DDLC port, i tried deleting monika since the start (that makes an alternative ending, so maybe are the variants that make this stuff fail) and after some dialogs crash with the same error, maybe there was a solution but i didn't found it or maybe i just messed up my sistem info, dunno

**Steps to reproduce:**

1.install tomodachi life Eur ES Legit cia/DDLC 3Ds Port from HShop

2.Open the app/apps

3. (If DDLC installed) delete monika chr from settings (the game is planed to do that) and start new game, skip some dialogs and after 7 or maybe more, it will crash

**Dump file:**
[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8880152/crash_dump_00000000.zip)
its the same for both games
**(DDLC-LOV: if its the DDLC Port)**

(Update like 7 minutes before)
Tomodachi life was wrong with the lenguage and now its working, but DDLC-LOV its still crashing

**Comment by oreo639** [comment]
Piracy isn't supported.
