### ISSUE TITLE
[BUG] Remote update failed

### ISSUE THREAD

**Issue by BrandiBlitz** [LumaTeam/Luma3DS#1763]
I have no idea what's going on. I tried to do a remote update for luma3DS v11.0 and it says that the download failed. This started happening as soon as I updated "Luma Updater".

My internet is full bars and FTP installation didn't work.

I had to resort to Manual installation and that worked... I think The Luma Updater needs to be looked into. Maybe part of the code isn't done or optimized correctly. 

[Video Evidence](https://youtu.be/77xpOVJrlVk)

**Comment by Masamune3210** [comment]
LumaUpdater or whatever the homebrew is called is not part of Luma, it is a third party program and no longer works

**Comment by BrandiBlitz** [comment]
> LumaUpdater or whatever the homebrew is called is not part of Luma, it is a third party program and no longer works

Oh I didn't know~ thank you for telling me.
