### ISSUE TITLE
ARM11 bootup screen error still appears even when Luma is updated

### ISSUE THREAD

**Issue by Nick1BunsYT** [LumaTeam/Luma3DS#1765]
I haven't used my 2DS XL in a while so I decided to update luma to get past the arm11 error screen, but when I updated luma, the error screen still appears, same text as always. either Nintendo already patched the new update or my 2ds is bricked. 
can someone explain to me why this is happening?

**Comment by Nick1BunsYT** [comment]
note: the luma configuration screen says that it's on version 10.1.3 even though I updated it to version 11.0

**Comment by Masamune3210** [comment]
1. Nintendo cant patch anything really anymore, bootroms cant be patched once they leave the factory
2. If the Luma config screen says you are on 10.1.3 something is causing it to not use the new version and you are still on the older version

**Comment by Shadow322** [comment]
> note: the luma configuration screen says that it's on version 10.1.3 even though I updated it to version 11.0

What does it say in yellow at the bottom of the bottom screen?

**Comment by Nick1BunsYT** [comment]
> > note: the luma configuration screen says that it's on version 10.1.3 even though I updated it to version 11.0
> 
> What does it say in yellow at the bottom of the bottom screen?

"Booted from CTRNAND via B9S"

**Comment by Shadow322** [comment]
> > > note: the luma configuration screen says that it's on version 10.1.3 even though I updated it to version 11.0
> > 
> > 
> > What does it say in yellow at the bottom of the bottom screen?
> 
> "Booted from CTRNAND via B9S"

Then update your CTRNAND copy

**Comment by Nick1BunsYT** [comment]
> > > > note: the luma configuration screen says that it's on version 10.1.3 even though I updated it to version 11.0
> > > 
> > > 
> > > What does it say in yellow at the bottom of the bottom screen?
> > 
> > 
> > "Booted from CTRNAND via B9S"
> 
> Then update your CTRNAND copy

I haven't done anything to my 3ds in a while so I have no idea where to get the update and how to update it

**Comment by Shadow322** [comment]
> > > > > note: the luma configuration screen says that it's on version 10.1.3 even though I updated it to version 11.0
> > > > 
> > > > 
> > > > What does it say in yellow at the bottom of the bottom screen?
> > > 
> > > 
> > > "Booted from CTRNAND via B9S"
> > 
> > 
> > Then update your CTRNAND copy
> 
> I haven't done anything to my 3ds in a while so I have no idea where to get the update and how to update it

If u re-download from Universal Updater it will automatically update the CTRNAND copy

**Comment by Nick1BunsYT** [comment]
> > > > > > note: the luma configuration screen says that it's on version 10.1.3 even though I updated it to version 11.0
> > > > > 
> > > > > 
> > > > > What does it say in yellow at the bottom of the bottom screen?
> > > > 
> > > > 
> > > > "Booted from CTRNAND via B9S"
> > > 
> > > 
> > > Then update your CTRNAND copy
> > 
> > 
> > I haven't done anything to my 3ds in a while so I have no idea where to get the update and how to update it
> 
> If u re-download from Universal Updater it will automatically update the CTRNAND copy

I redownloaded universal updater onto my 3ds and put it into my CIA folder, but it didn't auto-update the ctrnand copy. does it still auto-update when booted up into the arm11 error/luma config screen?

**Comment by moldimolt** [comment]
The issue tracker is not for tech support, only actual issues with Luma3DS. Try Nintendo Homebrew: https://discord.gg/C29hYvh.
