### ISSUE TITLE
I think it bricked my 2DS! HELP!!!

### ISSUE THREAD

**Issue by Xzz3DSjbluma** [LumaTeam/Luma3DS#1766]
So… I recently jail-braked my Nintendo 2DS and after a while, it started to get this error: 
![A61B4EA6-BAE1-4642-9C34-9F0671CBCA5A](https://user-images.githubusercontent.com/107895634/174691139-d0c39ea2-ad94-41f1-85b9-398ffd6c3cde.jpeg)

This came without warning and I have tried to replace files like boot.firm and stuff but nothing worked. After about a week, I started YouTubing it and NONE of them worked or helped one bit. Now I really need help! Anything would be helpful and thank you!

**Comment by impeeza** [comment]
Please go to the proper site to ask for support, this space if for report bugs.  discord or gbatemp are good support sites.

**Comment by wicorn29** [comment]
(this is my other account) Supper sorry. Might you know who can handle this?

**Comment by wicorn29** [comment]
Oh, and I would also find this as a bug.

**Comment by Shadow322** [comment]
> (this is my other account) Supper sorry. Might you know who can handle this?

U was already told @TuxSH close this please

**Comment by wicorn29** [comment]
It won't let me. And what do you mean by that?

**Comment by moldimolt** [comment]
The issue tracker is not for tech support, only actual issues with Luma3DS. Try Nintendo Homebrew: https://discord.gg/C29hYvh.
