### ISSUE TITLE
Arm11 error when trying to open Super Mario 64 Render 96 3DS Port

### ISSUE THREAD

**Issue by M4ttia2309** [LumaTeam/Luma3DS#1767]
**System model:**

Old 2DS

**SysNAND version (+emu/redNAND version if applicable):**

11.15.0-47E

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v11.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Off)

Splash duration: ( )

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
Whenever I try to open a game (SM64 Render 96 3DS Port) it says:
An exception occurred
Processor: Arm11 (core 0)
Exception type: data abort
Fault status: Translation - Section
Current process: Super Ma (000400000FF3FF00)
**Steps to reproduce:**

1.Open the game

2.Wait a few seconds

**Dump file:**

[crash_dump_00000000.zip](https://github.com/LumaTeam/Luma3DS/files/8948419/crash_dump_00000000.zip)

**Comment by moldimolt** [comment]
The issue tracker is not for tech support, only actual issues with Luma3DS. Try Nintendo Homebrew: https://discord.gg/C29hYvh.
