### ISSUE TITLE
(Request/Enhancement) Remove "Exclusivity" from the Start Button in the Luma Config Menu

### ISSUE THREAD

**Issue by Laxbby** [LumaTeam/Luma3DS#1769]
Hello. When the configuration menu for Luma appears, it forces you to press the START button to exit the menu and save any changes. Notably though, if any other button is being held when you press start, this doesn't work and the menu will not exit. This normally isn't a problem, but if a button is stuck due to hardware issues (in my specific case, my dpad up key), then it's impossible to exit the menu without holding the power button or removing the battery.
This is especially an issue if the console is booting into the configuration menu, which can happen if the config file is lost or the version of Luma is updated.
I've been able to bypass this problem by using a config.ini from another console, but this doesn't seem to be working anymore for whatever reason. I'm not sure if this is due to the recent update, or if it's just a mistake on my part, but regardless, I think it was be less of a hassle if this was implemented, so I wouldn't need a donor file in the first place.

**Comment by PabloMK7** [comment]
https://github.com/LumaTeam/Luma3DS/blob/80aee6fdc175e4191629960f991fad1896d05c34/arm9/source/config.c#L772

That line could be changed to `if(pressed & BUTTON_START) break;` to fix the issue.
