### ISSUE TITLE
Minor Enhancement: SELECT and L+SELECT

### ISSUE THREAD

**Issue by james-d-elliott** [LumaTeam/Luma3DS#177]
Currently, if you have a splash you can only use select SELECT to the splash showing to bring up the Luma conf. It may be useful for people to be able to put a SELECT (without L) payload in this situation.

I may play with this but I've never compiled Luma3DS or any other DS/3DS binaries before. So not sure how my results will be.

**Comment by fox8091** [comment]
Why would a SELECT payload be useful? SELECT is kinda already taken by config..
