### ISSUE TITLE
MD5 mismatch between server's and local file

### ISSUE THREAD

**Issue by SeleDreams** [LumaTeam/Luma3DS#1771]
**System model:** New 3DS XL
**SysNAND version (+emu/redNAND version if applicable):**
Sys 11.14.0-46J
**Entrypoint (How/what you're using to boot Luma3DS):**
b9s
**Luma3DS version:**
10.2.1-c058e3f
**Explanation of the issue:**
It seems like the md5 hash of the latest 11.0 build might be incorrect as the download through the 3ds always results in a hash mismatch during the second check differentiating the local md5 and the server's md5
**Steps to reproduce:**

1. launch luma updater

2. update to the latest version

**Comment by Shadow322** [comment]
Luma updater is dead and not of this team Universal Updater replaces it

**Comment by SeleDreams** [comment]
> Luma updater is dead and not of this team Universal Updater replaces it

Ah I see, I went to this repository because luma updater linked to this one when it comes to bug reports

**Comment by Shadow322** [comment]
> > Luma updater is dead and not of this team Universal Updater replaces it
> 
> Ah I see, I went to this repository because luma updater linked to this one when it comes to bug reports

Yes bug reports dealing with Luma3DS

**Comment by Gumbraise** [comment]
So how did you do to update it ?

**Comment by Shadow322** [comment]
> So how did you do to update it ?

U don't

**Comment by strik3r93** [comment]
Yeah luma updater is broken, just update luma3DS manually

**Comment by DRogueRonin** [comment]
How do I remove the Updater? I installed/updated it manually now but the updater still runs and checks and the only option I have is to quit
