### ISSUE TITLE
Rosalina menu

### ISSUE THREAD

**Issue by ToshaEssential** [LumaTeam/Luma3DS#1774]
On two consoles new 2ds xl and 2ds problem with Rosalina menu. It's in Chinese instead of English. How do I change the language?
Version 10.3
Screenshot https://freeimage.host/i/wMrHDF

**Comment by impeeza** [comment]
Download the files on release section of this page

**Comment by ToshaEssential** [comment]
> Download the files on release section of this page

Thank you! 
That helped and Rosalina works in English!
