### ISSUE TITLE
Bottom or Top screen only mode

### ISSUE THREAD

**Issue by cooolgamer** [LumaTeam/Luma3DS#1775]
Hello, my brother broke his 3ds top screen. It now only have the bottom screen and the top screen is no longer on the console.
The problem is, each time the top screen is initialized, the console instantly power off, making it impossible to boot.
Would it be possible to make a patch to make the console only initialize bottom screen only? (and a top screen only for people not having bottom screen working)

Thanks and have a nice day!

**Comment by impeeza** [comment]
This is a space FOR ISSUE REPORTS not for support, what you are looking is a mod to convert ds to one screen only.  search the net there are plenty of them.

**Comment by moldimolt** [comment]
Is there a practical/feasible use-case for a beheaded 3DS? Much of the 3DS UI and most games rely primarily on the top screen.

**Comment by cooolgamer** [comment]
@impeeza what I want was to make it boot wihout top screen, well I was able to do this by editing luma sourcecode, the code for this is pretty trash and break sleep mode but it works. So editing luma CAN make consoles wihout top screen bootable again

**Comment by Masamune3210** [comment]
Can doesnt mean it should be a standard feature that requires upkeep and maintenance. Besides, bigger point is this is not the place for feature requests, that is what discord or gbatemp is for
