### ISSUE TITLE
[QUESTION] Networking in Rosalina plugins?

### ISSUE THREAD

**Issue by bendevnull** [LumaTeam/Luma3DS#1777]
Hi, just a quick question. Is it possible to use network access in Rosalina plugins as of now? I'm trying to make a Discord RPC plugin for 3DS, and it would also allow RiiTag to use 3DS games from a console instead of just Citra.

Thank you!

**Comment by oreo639** [comment]
What do you mean by "Rosalina plugins"?

**Comment by moldimolt** [comment]
Rosalina does not currently have a plugin system.
