### ISSUE TITLE
Both IPS displays flickering when splashes are enabled.

### ISSUE THREAD

**Issue by StefanoLassandro** [LumaTeam/Luma3DS#1778]
This issue is still present after about two years since it was declared solved, so I simply wanted to remind of the existence of this issue.
Here's a closed thread on the topic.
https://github.com/LumaTeam/Luma3DS/issues/1432
Both IPS displays ficker for some time after booting the console (New Nintendo 3DS XL) with splashes enabled. The flickering is formed by fragments of the splash screen images.

My configuration settings:
  Screen Brightness: 4
  Splash: Before payloads
  PIN lock: Off
  New 3DS CPU: Off
  (x) Enable loading external FIRMs and modules
  (x) Enable game patching
  (x) Show NAND or user string in System Settings
  ( ) Show GBA boot screen in patched AGB_FIRM

I'm using the latest stable Luma version available (v11.0).
I'm using Boot9Strap (latest).
This problem still happens with or without Game Patching being enabled.
Thanks for reading, I'll gladly answer and keep providing information about this issue if needed.

**Comment by moldimolt** [comment]
Per what AW said in #1432, this issue is an example of #1396, which is still open.
