### ISSUE TITLE
Error with cheats 

### ISSUE THREAD

**Issue by JFRR3** [LumaTeam/Luma3DS#1781]
Error with cheats, when I put The cheats And then I play in The game this error happens: arm 11 (core0) 
Type: abortion of imformation/data
State of error: Traduction - section
![IMG_20220725_211452](https://user-images.githubusercontent.com/81179062/180943228-704db123-55ba-4a55-a2ae-15814c6b9c41.jpg)
![IMG_20220725_211443](https://user-images.githubusercontent.com/81179062/180943239-b5479da8-98c3-47dc-8385-15186f0bf6c4.jpg)

**Comment by Shadow322** [comment]
> Error with cheats, when I put The cheats And then I play in The game this error happens: arm 11 (core0) Type: abortion of imformation/data State of error: Traduction - section ![IMG_20220725_211452](https://user-images.githubusercontent.com/81179062/180943228-704db123-55ba-4a55-a2ae-15814c6b9c41.jpg) ![IMG_20220725_211443](https://user-images.githubusercontent.com/81179062/180943239-b5479da8-98c3-47dc-8385-15186f0bf6c4.jpg)

This is not a Luma3DS problem

**Comment by Gtasp1** [comment]
> > Error with cheats, when I put The cheats And then I play in The game this error happens: arm 11 (core0) Type: abortion of imformation/data State of error: Traduction - section ![IMG_20220725_211452](https://user-images.githubusercontent.com/81179062/180943228-704db123-55ba-4a55-a2ae-15814c6b9c41.jpg) ![IMG_20220725_211443](https://user-images.githubusercontent.com/81179062/180943239-b5479da8-98c3-47dc-8385-15186f0bf6c4.jpg)
> 
> This is not a Luma3DS problem

I have the same problem. I think that this is a Luma3DS problem (the part of Rosalina's cheats) because the crash dump saves at  SD:/luma/etc etc etc.

**Comment by Shadow322** [comment]
No this is not something Luma3DS will flx because it's not a Luma3DS problem @TuxSH please close this

**Comment by Gtasp1** [comment]
> No this is not something Luma3DS will flx because it's not a Luma3DS problem @TuxSH please close this

So, if this is not something about Luma3DS, what is it? I would like to solve the same problem.

![Rosalina](https://user-images.githubusercontent.com/109809888/181653377-816e669b-cc02-4754-8583-b202a5c1b989.jpg)

**Comment by Masamune3210** [comment]
Does it happen with every game or just one

**Comment by moldimolt** [comment]
Issues like this are typically issues with the cheats or the installation of the game (often, pirated copies have issues).
