### ISSUE TITLE
Incorrect link to 3ds.hacks.guide page on A9LH to B9S on Luma3DS Wiki

### ISSUE THREAD

**Issue by DarkBrave** [LumaTeam/Luma3DS#1782]
Very simple thing, on the GitHub wiki of Luma3DS there is a link on the page titled "Installation and upgrade" that takes you to the 3ds.hacks.guide page on going from A9LH to B9S.

This link should be the following:
`https://3ds.hacks.guide/a9lh-to-b9s`

But is instead:
`https://3ds.hacks.guide/https:/3ds.guide/a9lh-to-b9s`

**Comment by moldimolt** [comment]
Fixed, thank you.
