### ISSUE TITLE
Cheats in Luma3DS

### ISSUE THREAD

**Issue by Gtasp1** [LumaTeam/Luma3DS#1783]
I know that cheats doesn't work in Luma3DS, at least in version 11.0. Is there a way to solve that? Cheats work on emulators (for example, Citra or similars on Windows), but, why not in Nintendo 3DS? At least, there is another option in order to use cheats on 3DS?

Thank you in advance.

**Comment by oreo639** [comment]
> I know that cheats doesn't work in Luma3DS

It does work.
There is a kernel race condition that can randomly occur on some consoles with some games but it should work fine most of the time.
Cheats on sumo work fine for me.

**Comment by 0megaplus** [comment]
…What? I don't understand. Isn't using Checkpoint (via it's Sharkive database) technically using cheats? Or is there something I'm not understanding?
Sorry, just a question.
