### ISSUE TITLE
An exception occurred?

### ISSUE THREAD

**Issue by ronkarr13** [LumaTeam/Luma3DS#1785]
Hello! I was directed here from Reddit.
I bought a new 3ds XL off eBay, and when I try to play tomodachi life, there’s a black screen with red text that says an error occurred, and a bunch of numbers/letters in white. 
The person I bought it from says it used to be hacked but they said they took all the hacks off before selling it to me. I have no idea what to do. I have a MacBook Pro, not a PC. I have no adapter. I’ve never hacked before and I need help.

**Comment by Shadow322** [comment]
> Hello! I was directed here from Reddit. I bought a new 3ds XL off eBay, and when I try to play tomodachi life, there’s a black screen with red text that says an error occurred, and a bunch of numbers/letters in white. The person I bought it from says it used to be hacked but they said they took all the hacks off before selling it to me. I have no idea what to do. I have a MacBook Pro, not a PC. I have no adapter. I’ve never hacked before and I need help.

Take this to gbatemp kthx
