### ISSUE TITLE
DS Games crashing on O3DS.

### ISSUE THREAD

**Issue by benny1234561** [LumaTeam/Luma3DS#1789]
**System model:**
Old 2DS, Old 3DS XL, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g.9.2.0-20E SysNAND, 11.15.0-47E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap

**Luma3DS version:**

11.0 Stable
**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: ( 4)

Splash: (Before Payloads)

PIN lock: (Off)

Autoboot EmuNAND: (Yes)

Use EmuNAND FIRM if booting with R: (Off)

Enable loading external FIRMs and modules: (On)

Enable game patching: (On)

Show NAND or user string in System Settings: (On)

Show GBA boot screen in patched AGB_FIRM: (On)

**Explanation of the issue:**

DS Games Crashing on OLD 3ds and old 3ds XL

It doesnt give me the Option to make a crash dump.
This didnt happen before i Installed Luma3DS

**Steps to reproduce:**

1. Launch the Game

**Comment by moldimolt** [comment]
Please follow: https://3ds.eiphax.tech/twlfix

If you need help, try the Nintendo Homebrew Discord: https://discord.gg/C29hYvh
