### ISSUE TITLE
Psysical amiibo's not working when having "Game Patching" on

### ISSUE THREAD

**Issue by GamerIsNotEg** [LumaTeam/Luma3DS#1790]
When I'm playing a game that supports psysical amiibo's and when i read it won't read but when I have it off it works just fine I'm not sure if this is a bug but it needs to be fixed well if its just a feature that the creators forgot to add

**Comment by ghost** [comment]
Do you have wumiibo installed (https://github.com/hax0kartik/wumiibo)?

**Comment by GamerIsNotEg** [comment]
yes i do but it still does not work

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/185651701-91e25607-85b7-4a11-a896-078162ef2fab.png)

**Comment by Masamune3210** [comment]
Directly from its readme
