### ISSUE TITLE
Assign the "Press start to save" on another button 

### ISSUE THREAD

**Issue by cybernetkay** [LumaTeam/Luma3DS#1791]
Hi, i'm basically trying to mod my 2ds and when I try to press the start button to save, nothing happens. I realised that the start button was broken. Is there anything i can do? could i remap the start button to some other one and try to fix this?

**Comment by moldimolt** [comment]
The default hotkeys will not be changed, but the Nintendo Homebrew Discord can help you compile a build with them changed for your specific device, as they've done in the past: https://discord.gg/C29hYvh
