### ISSUE TITLE
Luma3DS graphics ghosting when "Game patching" is enabled

### ISSUE THREAD

**Issue by AudioDuplication** [LumaTeam/Luma3DS#1796]
**System model:**
New 3DS XL

**SysNAND version (+emu/redNAND)**
11.15.0-47E SysNAND, 11.15.0-47E EmuNAND

**Entrypoint (How/what you're using to boot Luma3DS):**
Booted from SD via B9S

**Luma3DS version:**
v11.0

**Luma3DS configuration/options:**
Default EmuNAND: (1)
Screen brightness: (4)
Splash: (Off)
Splash duration: (1000)
PIN lock: (Off)
New 3DS CPU: (off)
Autoboot EmuNAND: (x)
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Enable game patching: (x)
Show NAND or user string in System Settings: (x)
Show GBA boot screen in patched AGB_FIRM: ( )
Set developer UNITINFO: ( )
Disable Arm11 exception handlers: ( )
Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
When I set "Enable game patching" to enabled. And open the Luma3DS configuration screen (holding select while booting), or use a splash screen, parts of splash/configscreen stay as a sort of pixel-retention/ghosting on the TOP screen (bottom is unaffected).
It will be visible on the homescreen, and in-game, and will very slowly fade out slightly but never entirely. (see attachment photo)
- If I boot with "Enable game patching" off, then this issue does NOT occur.
- The issue also does NOT occur when I take out my SD card and set "Enable game patching" to enabled.
- I tested this on my New 2DS XL with 2 TN screens, the issue does not occcur, but it also does not have EmuNAND installed on the SD. 

**Steps to reproduce:**
1. Have EmuNAND, and "Enable game patching" ON.
May or may not be necessary: Have New3DSXL with top IPS screen.

2. Hold SELECT while booting, then press start to boot into 3DS
Either EmuNAND or SysNAND doesnt matter.

4. check the edges and corners of the screen for a ghost of what was on the screen during splash or the Luma settings screen.

![photo](https://user-images.githubusercontent.com/108935890/190193799-da1ca59e-a858-4de3-8895-7f8cc0860ea9.jpg)

**Comment by PabloMK7** [comment]
Does this happen with Luma 10.3?

**Comment by moldimolt** [comment]
Duplicate: #1396
