### ISSUE TITLE
There's a crash dump every time that I try to use a cheat

### ISSUE THREAD

**Issue by prglt** [LumaTeam/Luma3DS#1798]
Hello everyone, I wanted to use cheats on Pokemon Omega Ruby but when I try to use a cheat there's a crash dump, I have the current Luma version and I tried to use the last one before that. I don't know where the problem is and I hope that it can be fixed. 
the crash dump says:
an exception occurred
processor: Arm11 (core 0)
Exception type: data abort
Fault status: Translation - Section
Current process: sango-1 (000400000011C400)
Also, the console is upgraded to the last version so I suppose that's not the problem. Thanks for the help!
![IMG_20220920_183434](https://user-images.githubusercontent.com/114013147/191315448-f58106c5-fa3d-4c56-a8cc-a3570ca70567.jpg)

**Comment by Shadow322** [comment]
> Hello everyone, I wanted to use cheats on Pokemon Omega Ruby but when I try to use a cheat there's a crash dump, I have the current Luma version and I tried to use the last one before that. I don't know where the problem is and I hope that it can be fixed. the crash dump says: an exception occurred processor: Arm11 (core 0) Exception type: data abort Fault status: Translation - Section Current process: sango-1 (000400000011C400) Also, the console is upgraded to the last version so I suppose that's not the problem. Thanks for the help! ![IMG_20220920_183434](https://user-images.githubusercontent.com/114013147/191315448-f58106c5-fa3d-4c56-a8cc-a3570ca70567.jpg)

dont cheat and it wont crash

**Comment by prglt** [comment]
Is there a way to cheat and don't make It crash?

> > Hello everyone, I wanted to use cheats on Pokemon Omega Ruby but when I try to use a cheat there's a crash dump, I have the current Luma version and I tried to use the last one before that. I don't know where the problem is and I hope that it can be fixed. the crash dump says: an exception occurred processor: Arm11 (core 0) Exception type: data abort Fault status: Translation - Section Current process: sango-1 (000400000011C400) Also, the console is upgraded to the last version so I suppose that's not the problem. Thanks for the help! ![IMG_20220920_183434](https://user-images.githubusercontent.com/114013147/191315448-f58106c5-fa3d-4c56-a8cc-a3570ca70567.jpg)
> 
> dont cheat and it wont crash

Is there a way to cheat without making the game crash?

**Comment by Shadow322** [comment]
> Is there a way to cheat and don't make It crash?
> 
> > > Hello everyone, I wanted to use cheats on Pokemon Omega Ruby but when I try to use a cheat there's a crash dump, I have the current Luma version and I tried to use the last one before that. I don't know where the problem is and I hope that it can be fixed. the crash dump says: an exception occurred processor: Arm11 (core 0) Exception type: data abort Fault status: Translation - Section Current process: sango-1 (000400000011C400) Also, the console is upgraded to the last version so I suppose that's not the problem. Thanks for the help! ![IMG_20220920_183434](https://user-images.githubusercontent.com/114013147/191315448-f58106c5-fa3d-4c56-a8cc-a3570ca70567.jpg)
> > 
> > 
> > dont cheat and it wont crash
> 
> Is there a way to cheat without making the game crash?

Nope

**Comment by joseowo** [comment]
i think try using a alternative cheat code it can maybe fix your problem.
