### ISSUE TITLE
Missing options in luma3ds menu

### ISSUE THREAD

**Issue by Moepkid** [LumaTeam/Luma3DS#1800]
**System model:**

New 2ds XL

**SysNAND version (+emu/redNAND version if applicable):**

Latest (49E)

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

V11.0

**Explanation of the issue:**

I'm missing the following three options from my menu:

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

Should these not be present? I Had to reinstall my luma because of a factory reset. Im worried I miss essential stuff. 

I also cant create a emunand backup through god9mode. So im worried I messed up the install

**Comment by Shadow322** [comment]
> **System model:**
> 
> New 2ds XL
> 
> **SysNAND version (+emu/redNAND version if applicable):**
> 
> Latest (49E)
> 
> **Entrypoint (How/what you're using to boot Luma3DS):**
> 
> Boot9Strap
> 
> **Luma3DS version:**
> 
> V11.0
> 
> **Explanation of the issue:**
> 
> I'm missing the following three options from my menu:
> 
> Set developer UNITINFO: ( )
> 
> Disable Arm11 exception handlers: ( )
> 
> Enable Rosalina on SAFE_FIRM: ( )
> 
> Should these not be present? I Had to reinstall my luma because of a factory reset. Im worried I miss essential stuff.
> 
> I also cant create a emunand backup through god9mode. So im worried I messed up the install

reading does a body good

![image](https://user-images.githubusercontent.com/15938645/192164997-898236f3-f6a7-4dd6-8497-79885a6ce906.png)

**Comment by Moepkid** [comment]
Im sorry. Im completely new to this :(
