### ISSUE TITLE
Cant boot up the 3ds with and without the sd card.

### ISSUE THREAD

**Issue by Joonusz** [LumaTeam/Luma3DS#1803]
![obraz](https://user-images.githubusercontent.com/114761364/193311217-c4283d65-ab4b-49c1-bde9-cf266f88786a.png)
After i installed some cias onto my micro sd card i put it in my 3ds and when i booted up the system i got this error (see image)
the pc cant read it so it tells me to format it, i didnt do it yet.
Because my pc cant read the sd card i cant upload the crash dump.
Im using the old 3ds.

**Comment by Masamune3210** [comment]
If your computer can't read the sd card and you haven't set up anything like emunand or the ilk, your SD card is corrupted. Format it and try again
