### ISSUE TITLE
I lost the SD Card and i cant boot my console, i need help

### ISSUE THREAD

**Issue by davidsosa2009** [LumaTeam/Luma3DS#1805]
I have an old 3DS EUR, i did have this error a few months ago but i didnt fix it, i was very distracted in other stuff

I had lost the SD card with everything because i used the same card in a boombox, so when i wanted to listen to music i would switch from the boombox to 3ds, so i one day while inserting the card in the bookbox it just inserted completely, maybe i broke some plastic but i couldnt take it out, and now i couldnt use the console.

So heres the error image:

![WhatsApp Image 2022-10-17 at 7 50 38 PM](https://user-images.githubusercontent.com/85592949/196310371-f864be90-a681-4d3a-be4a-ebe4767fbdc0.jpeg)

I have a new sd card, i dont know if i should insert it or not with the new luma, can anyone give me indications? i know i lost all my stuff but i can redownload it again but i first need to fix this

**Comment by Shadow322** [comment]
take this to GBAtemp this isnt a help forum
