### ISSUE TITLE
[Suggestion] revert back changes for advanced users by adding a config option

### ISSUE THREAD

**Issue by cooolgamer** [LumaTeam/Luma3DS#1806]
Hello, I don't really know how to make a good title but the suggestion is to add something on the config.ini like "is_advanced" (that you have to add yourself specified somewhere in the readme) that if is set to 1, show all options like unitinfo, enable rosalina on safe_firm in luma config, doesn't make backups (like before 11.0) and if set 0, leave it like it is now.
This is really good for people that have full nand backups, and use those options in the luma config because it's really annoying to manually edit the config.ini each time I want to enable those options and I don't need the backups as I make full nand backups time to time.

**Comment by Querela** [comment]
Then it's probably easier to just show a "show advanced/hidden options" menu option. You wouldn't need to manually edit the `config.ini` file at all to display the hidden options.
