### ISSUE TITLE
[Suggestion] allow locale emulation on applets

### ISSUE THREAD

**Issue by cooolgamer** [LumaTeam/Luma3DS#1807]
Hello, I noticed that by editing the line that prevent some apps from using game patching allow locale emulation working fine on applets.
Would it be possible to allow applets to use locale emulation? Thanks

**Comment by PabloMK7** [comment]
Can you give examples of applets that would benefit from locale emulation?

**Comment by cooolgamer** [comment]
I first tried with the keyboard and it work just fine, It's useful because russian one have a extra keyboard tab
also instruction manual, friend list, game notes etc. do work too

**Comment by PabloMK7** [comment]
If you would like to contribute by providing a pull request, that would be easier for getting the changes added. (Also, you would appear as having contributed to this project ;) )

**Comment by cooolgamer** [comment]
the problem is I don't really know how to code xD
I only know how to edit some things but I don't know how to make it allow applets to ONLY use locale emulation patch as I enabled all patches for applets for testing

**Comment by cooolgamer** [comment]
done in v12.0
