### ISSUE TITLE
Error expected arm11

### ISSUE THREAD

**Issue by Cadi149** [LumaTeam/Luma3DS#1810]
Hi, and thanks. When i Launchpad FBI an error arm11 core 1 appear .
Same issue with thé lastest versions of luma anemone … Any issue ? Thanks

**Comment by PabloMK7** [comment]
Hello, this is probably related to a currupted SD.

In any case, this page is only to track issues with Luma3DS, and this is not an issue with Luma3DS. Can you please join the Nintendo Homebrew discord server for support? https://discord.gg/C29hYvh
