### ISSUE TITLE
clock speed automatically going to 800mhz on games that dont work well with it

### ISSUE THREAD

**Issue by kamikazilucas** [LumaTeam/Luma3DS#1811]
im trying to play animal crossing but everytime i play the game it goes to 800mhz which makes the game buggy, can there be an option to have it default to 200mhz instead its soo annoying having to to into the menu every time i start the game

**Comment by PabloMK7** [comment]
If you see the game going to 800mhz it's because the game itself is asking the system to go to 800mhz. I doubt that is causing the game to be buggy as that's what the game is designed to.

**Comment by kamikazilucas** [comment]
why is it supposed to go to 800mhz when its an og 3ds game, did it get new 3ds support?

**Comment by PabloMK7** [comment]
Are you sure you are not confusing the UI? What does the new 3ds configuration menu say while you are on the home menu without any games opened? 200mhz or 800mhz?

**Comment by kamikazilucas** [comment]
home menu is 800mhz, but when i open the game its also 800mhz with cache turned on

**Comment by PabloMK7** [comment]
Check that you didn't force 800mhz mode in the Luma configuration menu (hold select on boot)

**Comment by kamikazilucas** [comment]
i have it to set to off on that menu, i think that the problem with the saving bugs is the wireless for some reason is a problem with the game when i turn wifi off it seems to work fine, but i dont really want it on at 800mhz due to it using more battery when it runs fine at 200mhz

**Comment by PabloMK7** [comment]
Which animal crossing game is it?

**Comment by kamikazilucas** [comment]
new leaf

**Comment by PabloMK7** [comment]
Are you using a 3GX plugin/CTRPF?

**Comment by kamikazilucas** [comment]
no i dont think so just using luma

**Comment by profi200** [comment]
Can't reproduce. It says "Set clock to 268 MHz". L2 cache is also off. The game is fully updated.

**Comment by kamikazilucas** [comment]
if it says set to 268 it means its running at 800mhz

**Comment by profi200** [comment]
The game is running as expected. Zero glitches. They probably switched to New 3DS clock with the welcome Amiibo update.

Make sure the game/SD card isn't corrupted.

**Comment by kamikazilucas** [comment]
yes except it uses more power and has problems saving when wireless is an issue

**Comment by PabloMK7** [comment]
I also checked, the game runs at the new 3ds speed because they updated the game to support that, so it's not a bug with Luma.

If you don't like that the game does that, then you should patch the game so that it doesn't change the clock speed.

**Comment by kamikazilucas** [comment]
ok thanks, well ig ill just cope with it then, i wish the wireless wasent so annoying though idk why its doing that
