### ISSUE TITLE
Issue with Game Card Power toggle 

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1813]
I've noticed that there's an issue with the game card slot power toggle that prevents game cards from being read at all. I uninstalled Luma to test my theory and I believe this is correct. Please look into this and address it as needed

Device: Nintendo 2ds running latest firmware
Luma: V.11
Applicable games (that I've tested): Monster Hunter Stories, Tomodachi Life, MarioKart 7, Super Smash Bros. For 3ds, Shin Megami Tensei IV

**Comment by Shadow322** [comment]
um it works as it should i disabled the slot card slot cant be read then enable it again eject game card reinsert works fine

**Comment by ghost** [comment]
It doesn't work for me
Can you kindly tell me what system you're using?

**Comment by profi200** [comment]
Can't reproduce. It works as advertised. Turn gamecard power back on in the Rosalina menu before re-inserting the game.

**Comment by ghost** [comment]
Okay, I will try that. Apologies for wasting your time
