### ISSUE TITLE
can't disable arm11 exception handlers (Option Missing)

### ISSUE THREAD

**Issue by KingDoogan** [LumaTeam/Luma3DS#1814]
![HDlsgeV](https://user-images.githubusercontent.com/29140064/201691094-be1123d7-38d5-4742-8965-eab7e72031fe.jpg)

**Comment by PabloMK7** [comment]
Works as intended.

Do you have any specific reason to disable arm11 exception handlers? Unless you are a developer you shouldn't be disabling them (that's the main reason they were removed from the built-in config editor). If you know what you are doing and still want to disable them, edit the config.ini file in the luma folder in your SD.

**Comment by KingDoogan** [comment]
> Works as intended.
> 
> Do you have any specific reason to disable arm11 exception handlers? Unless you are a developer you shouldn't be disabling them (that's the main reason they were removed from the built-in config editor). If you know what you are doing and still want to disable them, edit the config.ini file in the luma folder in your SD.

Doing some testing with my unity 3ds project. (Only solution i've found, is disabling this option)

Thanks!
