### ISSUE TITLE
Unable to load ultra sun/ ultra moon

### ISSUE THREAD

**Issue by Jmc1922** [LumaTeam/Luma3DS#1815]
I am using the lastest version of luma3ds and my Nintendo switch is up to date . I can play omega ruby fine but when I go to play ultra sun/moon I always get errors 

![image](https://user-images.githubusercontent.com/115006410/202489633-720234ae-0358-4ec6-a52f-cf9f32cedebc.jpg)

Is there any way of helping

**Comment by Masamune3210** [comment]
Cart or digital? If digital, redownload from eshop

**Comment by Jmc1922** [comment]
Hi this is using the cart version , I had tried to create a rom hack using pk3ds if that’s any help

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Masamune3210** [comment]
If the game works without your attempt at modding, I would assume something went wrong with making the mod and it's not valid

**Comment by PabloMK7** [comment]
This is probably unrelated to an issue in Luma3DS (this page is for reporting issues with Luma3DS and not for support). Can you please close this issue and join the Homebrew Discord server and ask for help there? https://discord.gg/C29hYvh
