### ISSUE TITLE
Boot up problems

### ISSUE THREAD

**Issue by norman720** [LumaTeam/Luma3DS#1816]
My 3DS doesn't boot up properly

Sometimes when I try to turn it on, the blue light just blinks each time I press the power button

**Comment by Masamune3210** [comment]
If it's just turning on and then back off again when you push the power, it's having issues finding the file on the SD card. Default behavior with no version on ctrnand is to immediately turn back off if booted and can't find a valid boot file. Is it still on a9lh?
