### ISSUE TITLE
Add support for changing the word Sys/Emu in the System Settings?

### ISSUE THREAD

**Issue by shubshub** [LumaTeam/Luma3DS#182]
Could someone add this feature? I think it'd be really neat :) Sorry if this isn't where I can post suggestions I know its mostly for Issues..

Its kind've an issue for me cause I'd like to be able to change it :)

**Comment by cheatfreak47** [comment]
That's probably not going to be implemented. Luma is about functionality, not so much configuration and customization. If you want something like that, you'd probably have to build it yourself.

**Comment by TuxSH** [comment]
https://github.com/AuroraWright/Luma3DS/blob/master/injector/source/patcher.c#L421

4 letters max.
