### ISSUE TITLE
dsp dump fails when 3ds folder absent 

### ISSUE THREAD

**Issue by AlbertoDiazC** [LumaTeam/Luma3DS#1821]
**System model:**

New 2DS XL

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
DSP fw dumping fails when there isn't any 3ds folder in the sdcard.
Should create it as needed and dump succesfully.

**Steps to reproduce:**

1. Move or delete 3ds folder

2. Try dumping dsp firmware

**Dump file:**

**Comment by TuxSH** [comment]
Thanks for the report, it'll get fixed before the next release.
