### ISSUE TITLE
3ds bricked?

### ISSUE THREAD

**Issue by cheryyB** [LumaTeam/Luma3DS#1824]
I was needing to find a save file and to do so tutorials made me downgrade to version 2.1. when I did what the tutorials told me I got a pop up of the exception arm11 dump. When I tried fixing this it said to download luma again then disable arm11 and I don't get the dump pop anymore but when I boot it will instead show a black screen with the solid blue light and no matter how long I wait it just stays black. I can still open luma and gm9 but not the home menu any help is very appreciated

**Comment by urherenow** [comment]
Github is not a support forum, it’s for collaboration and reporting bugs. There are tutorials on gbatemp for this. You could try to google how to get into recovery and attempt to install firmware that way…

**Comment by cheryyB** [comment]
ok thank you
