### ISSUE TITLE
Suggestion: DSi Boot Animation

### ISSUE THREAD

**Issue by smileyhead** [LumaTeam/Luma3DS#183]
Would it be possible to add the DSi boot animation when launching DSiWare, like with the GBA titles?

**Comment by droped** [comment]
And what would that animation be exactly? Does the ds/dsi even have one for games?

**Comment by RinMaru** [comment]
nope it doesnt thats all bios dude.

**Comment by TuxSH** [comment]
No, it isn't possible.

**Comment by droped** [comment]
If this is what you want: https://gbatemp.net/threads/ntr-launcher-bring-back-that-classic-ds-boot-screen-for-your-ds-games.440110/

**Comment by smileyhead** [comment]
Yes.

**Comment by droped** [comment]
It doesn't launch dsiware, twl titles and many other titles but one day it might.
