### ISSUE TITLE
Can you make a build with this correction please

### ISSUE THREAD

**Issue by MarioHerreraVolioyTrejos** [LumaTeam/Luma3DS#1831]

**Comment by MarioHerreraVolioyTrejos** [comment]
https://github.com/LumaTeam/Luma3DS/commit/80aee6fdc175e4191629960f991fad1896d05c34

**Comment by TuxSH** [comment]
Yes, I will, once I implement one more feature and fix some other bugs.

**Comment by Shadow322** [comment]
Release a new release build perhaps?

**Comment by NightScript370** [comment]
Since 12.0 released, this could be closed.
