### ISSUE TITLE
[request] Option to force audio routing to onboard speakers

### ISSUE THREAD

**Issue by raekuul** [LumaTeam/Luma3DS#1837]
As an extension to #1828, can we also have an option to force audio to route to onboard speakers (ignoring the headphone jack entirely)?  My unit is water damaged in such a way that the headphones report that they're always "in use."  In NDS/3DS Mode this means I need to plug in headphones to get sound.

I know that the onboard speakers themselves still work, though:
1.  The Camera App still correctly plays the "taking a picture" sound through the onboard speakers
2.  The version of OPEN_AGB_FIRM that I have installed doesn't properly detect headphones and so plays through the onboard speakers anyway.

(originally requested in the comments to #752 and I don't know if this was kept since #752 was closed as unmaintainable shortly thereafter)

**Comment by TuxSH** [comment]
Done, here's a build:

[boot.zip](https://github.com/LumaTeam/Luma3DS/files/10702796/boot.zip)

**Comment by raekuul** [comment]
Works for 3DS mode, thank you

**Comment by kuyukurt2923** [comment]
this seems to be not working on my regular 3ds ll. Speaker works on camera as well but when I saved the settings on my luma menu with the force audio X out on the speakers, nothing happens

**Comment by kuyukurt2923** [comment]
Oh and headphones does not work for me as well.  No sound on speakers and headset

**Comment by 123321mario** [comment]
this actually revived my new 3ds speakers but can't launch ctgp anymore
could this be pushed to the main release?

**Comment by ctroche41104** [comment]
This fix almost completely works for me, however I've found that certain applications still do not play from my speakers. Most specifically, it seems to be any applications that can't be minimized, such as DS games or GBA games. If anyone else has had this issue, any help would be greatly appreciated!

**Comment by Masamune3210** [comment]
TWL_FIRM and AGB_FIRM are separate from anything Luma touches. It would take modifying or replacing those firms for this to work for DS or GBA games.

**Comment by JustCoddy** [comment]
> Done, here's a build:
> 
> [boot.zip](https://github.com/LumaTeam/Luma3DS/files/10702796/boot.zip)

hey so i’m kinda new to this and i have the same problem i just don’t know where to put this file or how to boot it i need help
