### ISSUE TITLE
DSiWare titles don't boot anymore after enabling and disabling TwlBg patches

### ISSUE THREAD

**Issue by smileyhead** [LumaTeam/Luma3DS#184]
I wanted to test out this new feature, and after testing and disabling it, DSiWare titles don't boot anymore. (They didn't boot with the setting on, either.)

**Comment by droped** [comment]
Zelda 4 swords anniversary edition boots with either option here.

**Comment by smileyhead** [comment]
It doesn't boot for me. :-/

**Comment by droped** [comment]
Try reinstalling a clean twl firm. https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-have-issues-with-gbadsdsiware-games-and-i-have-installed-a-patched-agbtwl-firm-cia-in-the-past

**Comment by smileyhead** [comment]
I didn't install a modified one in the first place.

**Comment by droped** [comment]
Try reinstalling it either way. It won't do any harm if you properly follow the instructions.

**Comment by TuxSH** [comment]
[out.zip](https://github.com/AuroraWright/Luma3DS/files/441129/out.zip)

**Comment by smileyhead** [comment]
What's this?

**Comment by TuxSH** [comment]
My build of the lastest commit, which should work.
