### ISSUE TITLE
Add color saturation option to "advanced configuration" menu like in fizeau for switch

### ISSUE THREAD

**Issue by pitrako** [LumaTeam/Luma3DS#1840]
I know there is contrast and gamma, but can you add a saturation option?

**Comment by TuxSH** [comment]
Sadly this is not possible. From what I'm seeing the Switch's GPU as a proper color matrix (256x3 ?), whereas the 3DS GPU has 3 256x1 replacement tables (this means anything that a non-diagonal matrix is non-implementable).
