### ISSUE TITLE
2DS doesn't boot

### ISSUE THREAD

**Issue by r4distiso** [LumaTeam/Luma3DS#1843]
I have the boot.firm and boot.3dsx files on the root of my SD card but my 2DS refuses to boot. Help!

**Comment by salvasin** [comment]
im having the same issue .have you found a solution?

**Comment by urherenow** [comment]
This is not a support forum, and neither of you have provided any useful information whatsoever. Ask on Discord or gbatemp.

**Comment by rdistiso** [comment]
> This is not a support forum, and neither of you have provided any useful information whatsoever. Ask on Discord or gbatemp.

I have access to neither as I am underage

**Comment by rdistiso** [comment]
> im having the same issue .have you found a solution?

Does your 2DS give a White light for the top LED and Blue for Power LED?

**Comment by Shadow322** [comment]
@urherenow can u ban them please

**Comment by rpdistiso** [comment]
I have diagnosed the problem just dont know how to fix it, The 2DS can't find the boot.firm

**Comment by Masamune3210** [comment]
Once again, this is not a support forum. Please go to somewhere else to figure this out.
