### ISSUE TITLE
[request] InputRedirection moved to Rosalina Menu

### ISSUE THREAD

**Issue by frogdude66** [LumaTeam/Luma3DS#1844]
In a future update, could you move the 'Start InputRedirection' from 'Miscellaneous options' to the main 'Rosalina menu' so it can be more easily accessed. Thanks in advance

_Originally posted by @frogdude66 in https://github.com/LumaTeam/Luma3DS/issues/752#issuecomment-1444308329_

**Comment by lividhen** [comment]
This would not be ideal for everyone as a lot of people don't use it and it would cause clutter. You can however create a fork and for the most part copy paste the option onto the main menu.

**Comment by frogdude66** [comment]
How would this be possible? I have no coding knowledge whatsoever and this seems too complicated for me. Is there a guide to doing this?

**Comment by lividhen** [comment]
I moved `{ "Start InputRedirection", METHOD, .method = &MiscellaneousMenu_InputRedirection },` from line 71 in `/sysmodules/rosalina/source/menus/miscellaneous.c` to line 48 in `/sysmodules/rosalina/source/menus.c`. Seems to work pretty good.
In summary moved input redirection from misc menu to the top of the main menu.

[boot.firm.zip](https://github.com/LumaTeam/Luma3DS/files/10829109/boot.firm.zip)
[git.diff.txt](https://github.com/LumaTeam/Luma3DS/files/10829125/git.diff.txt)

**Comment by frogdude66** [comment]
Wow Thank you. That is very helpful
