### ISSUE TITLE
closed-lid powering up boots to white screen (v12.0 stable)

### ISSUE THREAD

**Issue by al797** [LumaTeam/Luma3DS#1848]
**Steps to reproduce on a N2DS:**

1. power up the console without opening the lid.

2. wait a couple seconds then open the lid.

this is not an issue on v11.0.

**Comment by al797** [comment]
turned out my n2ds wasnt on latest firmware. solved.

**Comment by Shadow322** [comment]
> turned out my n2ds wasnt on latest firmware. solved.

It happens on latest fw still

**Comment by al797** [comment]
> > turned out my n2ds wasnt on latest firmware. solved.
> 
> It happens on latest fw still

you're right lol. I guess it's not solved then.

**Comment by lifehackerhansol** [comment]
Reproducible on N3DSXL as well.

**Comment by lifehackerhansol** [comment]
After some discussion in a separate Discord server this is also reproducible on O3DS and N3DS, which seems to indicate all devices are affected. Giving the device about 5 seconds (or roughly when the backlight turns on) makes this reproducible quite easily.

There are also reports that waking from sleep mode (regardless of whether system is powered off or not) also causes a white screen, but reproducibility of this is somewhat random.

It should be noted that the screens are just white, but all other functionality are intact. So you can interact with the HOME menu and stuff but the screen just stays white.

Launching any app from this state will launch with the screen remaining white. Rosalina also keeps the screen white. I was, however, able to produce an exception (for unrelated reasons) but the exception handler did show.

**Comment by al797** [comment]
still an issue on 12.0.1

**Comment by kusazh** [comment]
same here

**Comment by TuxSH** [comment]
Fixed on v13.0
