### ISSUE TITLE
Complex PIN combination

### ISSUE THREAD

**Issue by adven142** [LumaTeam/Luma3DS#185]
Use the directional pad, shoulder buttons and face buttons to create a PIN up to 32/or higher characters in length.

**Comment by cheatfreak47** [comment]
wha- why would you want a pin anywhere near that long?

**Comment by astronautlevel2** [comment]
Do the konami code 3 times

**Comment by favna** [comment]
32 seems overkill but I was actually going to ask sort of the same as a future request where we can end the pin length at any time by pressing the Start button and can use Up/Down/Left/Right/ABXY. The reason for ME personally is well... [the single only thing Konami is still good for - Konami code](https://en.wikipedia.org/wiki/Konami_Code)

I seriously want my pin to be up up down down left right left right A B. I got that so memorized.

**Comment by Hartie95** [comment]
If you only need the pin to prevent the usage of other payloads than luma (thinks like decrypt9 and other payloads that could cause damage), you could simply use BootCTR9. 
It supports the usage of more keys and longer combinations.

**Comment by favna** [comment]
> If you only need the pin to prevent the usage of other payloads than luma (thinks like decrypt9 and other payloads that could cause damage), you could simply use BootCTR9. 
> It supports the usage of more keys and longer combinations.

Nah that is not at all why I want a pin. I want it for my device in general.

**Comment by AuroraWright** [comment]
v6.1.2 supports the directional pad and up to 8 digits, which should allow for a very large range of combinations :)
