### ISSUE TITLE
Kirby Planet robobot crashes when plugins are on and something that I had to put in due to no issues section

### ISSUE THREAD

**Issue by MegaloDawn** [LumaTeam/Luma3DS#1854]
**New 3ds XL**

**SYS 11.16.0-49E**
**Boot9Strap**
**VER 12.00**
Screen brightness: (4)
Splash: (Off)
Splash duration: (?)
PIN lock: (Off)
New 3DS CPU: (Off)

--

Enable game patching: (On )

Show NAND or user string in System Settings: (ON)

Show GBA boot screen in patched AGB_FIRM: ( OFF)

Set developer UNITINFO: (? Off)

Disable Arm11 exception handlers: (OFF)

Enable Rosalina on SAFE_FIRM: (??? )

--

1. Have the CTRpluginframeworkfrom [here] (https://github.com/PabloMK7/CTRPluginFramework-BlankTemplate)

2. Enable plugins and launch Kirby planet robo-bot then it crashes (used digital version)

[crash_dump_00000000  (kirby robo).zip](https://github.com/LumaTeam/Luma3DS/files/11011455/crash_dump_00000000.kirby.robo.zip)

Also I need to address one issue with the plugin because there is no issues section for it

Auto load enabled cheats at starts DOESN'T load the cheats. (that's it)

**Comment by PabloMK7** [comment]
Hello, this seems to be an issue with CTRPluginFramework, not with Luma3DS.
