### ISSUE TITLE
An error that can't redirect to the "Nintendo DS Connections" screen?

### ISSUE THREAD

**Issue by Aiyan0117** [LumaTeam/Luma3DS#1863]
When I use "**original resolution mode**" to enter "Nintendo DS Connections" in "Internet Settings", Cannot enter the "Nintendo DS Connections" screen, but enter the "Luma3DS chainloader" and "Luma3DS configuration" screen.
Sorry I don't speak English, this is a machine translation，Request to fix this error，thank you very much!
Luma3DS Version：12.0~12.0.1
Console：New 3DS
System version：11.16.0-49J

**Comment by TheMasterCoders** [comment]
Are you holding down start/select?

**Comment by Aiyan0117** [comment]
That's it!


> Are you holding down start/select?
