### ISSUE TITLE
There are two hidden system titles (black box) at home menu on TWN region O3DS.

### ISSUE THREAD

**Issue by i1itione** [LumaTeam/Luma3DS#1865]
I tried deleting them via FBI by guessing and I found they are:

0004001000028A00: [System Transfer] (CARDBOARD)
0004001000028F00: SAFE_MODE [System Updater]

But I am not sure if it is cause by I had ever did the downgrading to 2.1.0J (region changing for obtain otp.bin) many years ago, and the issue still exists even I change back to TWN region system.

Actually there are other 11 titles (black box) and I found they are system titles of CHN region system.

0004001000026000
0004001000026100
0004001000026200
0004001000026300
0004001000026400
0004001000026500
0004001000026700
0004001000026800
0004001000026D00
0004001000026E00
0004001000026F00

The solution for these 11 black boxes, just delete them via FBI due to they will not be used.

So the problem is "0004001000028A00: [System Transfer] (CARDBOARD)" and "0004001000028F00: SAFE_MODE [System Updater]", because they shouldn't be deleted via FBI.

**Comment by PabloMK7** [comment]
The problem reported here seems to be specific to your situation and not a general issue of Luma3DS. You will get better and more fluent support if you ask in a forum related to 3DS homebrew or in the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh).
