### ISSUE TITLE
[Feature Request] Enable users to exit Luma config screen with another button

### ISSUE THREAD

**Issue by Cybelyrium** [LumaTeam/Luma3DS#1869]
I've seen a lot of users who can't exit Luma config menu due to a broken START button.
The feature to switch which button should be used to exit (such as SELECT or A) would be very appreciated.

**Comment by profi200** [comment]
Instead of adding extra button handling i would add a menu entry like "save and boot".

**Comment by PabloMK7** [comment]
Completed by #1917
