### ISSUE TITLE
Question how update luma3ds when move hacks to internal storage on new 3ds xl.

### ISSUE THREAD

**Issue by Riot20058** [LumaTeam/Luma3DS#1873]
I have question so move my hacks to internal storage so my question how is on new 3ds xl is how update my luma3ds system when a new ver comes out.

**Comment by Riot20058** [comment]
Information do it come for retro game crops video guides on how to hack a 3ds.

**Comment by urherenow** [comment]
Github isn’t a support forum. It’s for reporting bugs and collaboration.

https://3ds.hacks.guide/finalizing-setup.html
Section VI - CTRNAND Luma3DS

**Comment by Riot20058** [comment]
@urherenow did that my question is how update without breaking the whole thing because like do it new ver of luma3ds comes out.

**Comment by Riot20058** [comment]
Like this know so don't put yet outher bugs report of something goes wrong.

**Comment by Riot20058** [comment]
@urherenow think do put luma3ds update files onto sd card and after words go into godmode to copy luma3ds update into the 3ds internal storage is that correct way to do it.

**Comment by Riot20058** [comment]
@urherenow video saying just copy file into internal storage By fbi as way update luma3ds probably best way to do it.

**Comment by korbosoft** [comment]
dont use a video guide
