### ISSUE TITLE
[IDEA] Screen Recording Feature in Rosalina Menu

### ISSUE THREAD

**Issue by Minionguyjpro** [LumaTeam/Luma3DS#1879]
It would be nice to be able to record our screen to a video with the Rosalina menu, like NTR, but instead of streaming we can record it.

**Comment by PabloMK7** [comment]
Hello,
this feature seems to be out of the scope of Luma3DS. It can probably be achieved by other less intrusive means such as a custom system module or homebrew application. Keep in mind that features that are only beneficial to a very small group of people cannot be implemented in a custom firmware designed for everyone, as implementing too many of them could bloat the source code.

BootNTR already does this job pretty well, and the 3DS IO is not fast enough to record directly to the SD.
