### ISSUE TITLE
2 black box in the home menu

### ISSUE THREAD

**Issue by JustForNothing** [LumaTeam/Luma3DS#188]
I have these black box since luma 5.5....
I don't have this problem with Gateway...
![img_20160831_140430524](https://cloud.githubusercontent.com/assets/18685185/18137696/cc7e8c72-6fa9-11e6-8cbc-4aff749e989f.jpg)

That can be hidden in a next update ?

**Comment by TuxSH** [comment]
It's probably titles installed to NAND by error using an old version of FBI.

Install the newest CIA version of FBI (to SD), and you shouldn't worry about having new black boxes like that one. Then, to make the current ones dissapear, provided you rembember what you installed, delete the corresponding titles.

**Comment by fox8091** [comment]
This could also be an issue due to downgrading. If the title was not originally on this firmware, it has a chance to show up on the Home Menu.

**Comment by JustForNothing** [comment]
I have already the lastest version of FBI, and I think the title are from system file, but I don't remember which files

**Comment by AuroraWright** [comment]
Not a Luma problem anyway.
