### ISSUE TITLE
Crash error ( 0xd9004587 ) when i try to boot yo kai watch games ( 2 and 3 )

### ISSUE THREAD

**Issue by Essolll** [LumaTeam/Luma3DS#1880]
When i try to boot a 3ds game ( specifically yo kai watch 2 and 3 because all the other games are working ) on luma 12.0.1, I get an error message

( The both games are up to date on their lastest version )

Here is the complete error message to help me because i'm not good on 3DS hacking : 

*************************************
An error occurred ( ErrDisp )
Error type :          generic

Process ID :         38
Process name :   yw2
Process title ID : 000400000019ac00

Adress :              0x0010bd34
Error code :        0xd9004587

Press any button to reboot
*************************************

Thank you for helping me and sorry for my bad english but i'm not 😅

**Comment by TuxSH** [comment]
The game assets are corrupted, reinstalling the game should fix this (if your SD card is working). If it's a cartridge, then it may be faulty.
