### ISSUE TITLE
Help nintendo 3ds

### ISSUE THREAD

**Issue by KAMPAMENTO** [LumaTeam/Luma3DS#1885]
Hey my nintendo 3ds black was working just finw until this error ocurred now i cant play any game it just crashes and i need to fix it because i need it to play multiplayer this is the error that appears: An error occurred (ErrDisp)

Error type: generic
Process ID: 25
Process name: num
Process title ID: 0x0004012000002d02

Adress: 0x0010941a
Error code: 0xf9606c02

Press any button to reboot

Someone please help tell me how to fix this so i can play again :(

**Comment by Shadow322** [comment]
This is not an help forum take it to gbatemp

**Comment by KAMPAMENTO** [comment]
I know how to fix it now
