### ISSUE TITLE
DSi Ware/DS Games give me a black screen

### ISSUE THREAD

**Issue by fm360** [LumaTeam/Luma3DS#189]
Problem is in the title
Luma 3DS 6.1.1-dev
N3DS 9.2 Sysnand 11.0 REDNand  Menuhax
I have never installed any TWL/AGB patches in the past for anyone that is wondering.

**Comment by Margen67** [comment]
> Menuhax REDNand

Well there's your problem

**Comment by fm360** [comment]
Whats wrong with Menuhax and REDNand? What should be the proper way for me to boot Luma3ds? Im kind of a noob

**Comment by Margen67** [comment]
It's inferior to A9LH.

Waste of SD card space, slow, low boot rates, can't use updated SysNAND, can't boot CFW without an SD card and leaves the system vulnerable to an update, can't unbrick without a hardmod, needs DSiWare/GBA to be installed on both Emu and SysNAND, etc.

**Comment by fm360** [comment]
can you show me a good tutorial for installing A9LH and also where can I find the CIA files for the DSiWare and GBA stuff

**Comment by Margen67** [comment]
https://github.com/Plailect/Guide/wiki

**Comment by TuxSH** [comment]
For the issue itself I lack many details...
