### ISSUE TITLE
Is there a way to update Luma3ds without an SD card?

### ISSUE THREAD

**Issue by Mooshroomdude250** [LumaTeam/Luma3DS#1892]
Hey there LumaTeam. Luma3ds is a pretty good piece of CFW for my Nintendo 2DS but my 2DS's SD card slot can no longer read SD cards so I'm wondering if there's any way to update Luma without one (I'm on v11.0 and Nintendo, please stop nagging me to update my 3ds, it's already stable!)

**Comment by ghost** [comment]
You NEED a SD card to install Luma3DS, let alone **any CFW.**

**Comment by Mooshroomdude250** [comment]
Well I did install Luma3ds onto my NAND back when my SD card slot functioned and now for some reason it doesn't anymore which is why I'm wondering if it's possible to update Luma without one. (But I assume no so.....)
