### ISSUE TITLE
[Question] Is there a way to make the pin longer?

### ISSUE THREAD

**Issue by SteelyxYT** [LumaTeam/Luma3DS#1896]
Is there a file I can edit to make the pin longer. 
I want to have a 10 character pin because I want to use the Konami code.

**Comment by PabloMK7** [comment]
Hello,
This feature seems to be out of the scope of Luma3DS. Keep in mind that features that are only beneficial to a very small group of people cannot be implemented in a custom firmware designed for everyone, as implementing too many of them could bloat the source code.
