### ISSUE TITLE
CPU overclocking and L2 cache always enabled after boot

### ISSUE THREAD

**Issue by drago-sp** [LumaTeam/Luma3DS#1897]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.17.0-50E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v12.0.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (off)

Splash duration: ( )

PIN lock: (off)

New 3DS CPU: (off)

--

Hbmenu autoboot: (off)

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
On New 3DS, CPU overclocking and L2 cache seems to always default to enabled after a reboot, even when disabled in Luma settings.

**Steps to reproduce:**

1. Start console while holding SELECT

2. Set New 3DS CPU to (off)

3. Reboot

4. Open Rosalina, New 3DS menu. It offers the options to disable L2 cache and CPU overclock.

**Dump file:**

**Comment by profi200** [comment]
It's not always enabled. Boot any title that does not request N3DS clocks and it will go down. HOME menu is one of the titles requesting higher clocks.
