### ISSUE TITLE
Some custom applications crash upon exiting

### ISSUE THREAD

**Issue by friendlyanon** [LumaTeam/Luma3DS#190]
![crash](https://cdn.discordapp.com/attachments/187205892989648897/220962226092245002/crash.jpg)

This one in particular happened after exiting from the modified microSD Management application I got from _that site_, which worked just fine on latest v5 before I upgraded to v6.1.1-7fb17ce5

The behaviour previously on v5 was just a message box saying that the application crashed upon exiting into the homemenu.

Attached the crash dump, just do save-as, because github didn't allow me to upload as zip:
[rename_me_to_dmp___crash_dump_00000003](https://cloud.githubusercontent.com/assets/1736896/18178181/a3759666-707d-11e6-85c8-6684e37048c0.png)

**Comment by TuxSH** [comment]
The fact it crashes is not a Luma3DS issue, and that app wasn't meant to be launched from HM directly. I'll take a look soon though
