### ISSUE TITLE
Keep getting "DOWNLOAD FAILED" and I'm not sure what to do

### ISSUE THREAD

**Issue by M0th-gaymer** [LumaTeam/Luma3DS#1901]
I keep getting this message when I try to update and I don't know what to do or what went wrong. Help!
![20230605_215459](https://github.com/LumaTeam/Luma3DS/assets/135679116/af1cafd5-3aaf-4f3b-bcd7-3fcb70b17783)

**Comment by Shadow322** [comment]
> I keep getting this message when I try to update and I don't know what to do or what went wrong. Help! ![20230605_215459](https://user-images.githubusercontent.com/135679116/243524903-af1cafd5-3aaf-4f3b-bcd7-3fcb70b17783.jpg)

Update manually

**Comment by impeeza** [comment]
As stated several times on previous issues, LUMA UPDATER is deprecated, NOT supported by Luma3DS and unrelated to Luma3DS, you must to update manually.

Luma3DS and Luma Updater are completely two separated products.

Please close the issue.
