### ISSUE TITLE
[Feature Request] (Create a tool/option that will) Save/convert screenshots to DCIM for use in 3DS Camera

### ISSUE THREAD

**Issue by skunkmommy** [LumaTeam/Luma3DS#1902]
This is not a full duplicate of #1501 but it is related
It'd be nice if luma3ds screenshots could be saved to DCIM so that they're viewable in 3DS Camera like eg ACNL/Tomodachi captures.
While reading the aforementioned issue, I saw that you said it would not be possible due to memory constraints, at least on the O3DS. Keep in mind that this was said in ~2020 and Luma's almost definitely changed since then.
I propose a workaround, and that is making a dedicated tool. (Ik its out of scope but where else am i gonna ask?)

The homebrew would show every Luma screenshot in pairs,
and allow the user to convert them. Either one by one or in bulk.
There should be an option to pick which screen to convert,
since a lot of the time you only really wanna capture one.

If it would be viable to add the original vision on the N3DS, go for it.
But not everyone has an N3DS. (I don't, for one.)

**Comment by PabloMK7** [comment]
Hello,
this feature seems to be out of the scope of Luma3DS. It can probably be achieved by other less intrusive means such as a custom system module or homebrew application. Keep in mind that features that are only beneficial to a very small group of people cannot be implemented in a custom firmware designed for everyone, as implementing too many of them could bloat the source code.
