### ISSUE TITLE
Can you cfw an emulator?

### ISSUE THREAD

**Issue by SuperMarioYAHOOYAHOO** [LumaTeam/Luma3DS#1907]
I want to install Luma 3DS on CItra. im not sure if you can, as i seee no guides on how to do it. is this possible?

**Comment by Shadow322** [comment]
> I want to install Luma 3DS on CItra. im not sure if you can, as i seee no guides on how to do it. is this possible?

Take this to gbatemp.net this is not a help forum

**Comment by ihaveamac** [comment]
Citra is not a low-level 3DS emulator so it doesn't run ARM9 software like Luma3DS or GodMode9

**Comment by SuperMarioYAHOOYAHOO** [comment]
> > I want to install Luma 3DS on CItra. im not sure if you can, as i seee no guides on how to do it. is this possible?
> 
> Take this to gbatemp.net this is not a help forum

bruh i did

**Comment by SuperMarioYAHOOYAHOO** [comment]
> > I want to install Luma 3DS on CItra. im not sure if you can, as i seee no guides on how to do it. is this possible?
> 
> Take this to gbatemp.net this is not a help forum

https://gbatemp.net/threads/cfw-on-emulator.634648/#post-10183992

**Comment by ghost** [comment]
**This can only be used on actual hardware.**

**Comment by Masamune3210** [comment]
You were given an answer in the thread, yet you persevered and decided to make a issue to ask here as well? Citra cannot run Luma, it is not a low-level emulator.

**Comment by SuperMarioYAHOOYAHOO** [comment]
> You were given an answer in the thread, yet you persevered and decided to make a issue to ask here as well? Citra cannot run Luma, it is not a low-level emulator.

bruh i made this before i got the answer
