### ISSUE TITLE
Boooting everytime with splash-screen, even with disabled option

### ISSUE THREAD

**Issue by nedron92** [LumaTeam/Luma3DS#191]
The new releases of Luma3D 6.x are booting everytime with a splash-screen if the file is located on the sd-card, even if the option is disabled in config. 
In 5.5 the behavior was to boot without splash-screen, if options is disabled (even is file is on the sd-card), which is the right behavior I think ;)

**Comment by james-d-elliott** [comment]
As far as I know the only option regarding splash is to display it prior to the payloads (so that people can see hotkeys).

**Comment by TuxSH** [comment]
Update to the latest commit or delete the config file
