### ISSUE TITLE
Homebrew menu, universal updater, and FBI disappeared?

### ISSUE THREAD

**Issue by Unknxwn837** [LumaTeam/Luma3DS#1912]
I gave my 3DS XL to my little cousin and when I got it back it was stuck on a screen. I didn’t know what it was and the worst thing I did was click A. When I loaded up, all the homebrewed games were gone, universal updater, FBI, and the homebrew app as well. Twilight menu and the DSi games were still there so I got back to the menu after learning how to and clicked what I think I clicked before. I can’t load up anymore and I’m stuck on this screen. I am very anxious and nervous so if anyone knows how to help please do.
![E4468F47-CFC8-46C3-8CA6-C1686BFF2FEF](https://github.com/LumaTeam/Luma3DS/assets/137337805/22762206-0fff-41e3-8109-7be20c5821f7)

**Comment by impeeza** [comment]
this is not a support space, please go to Discord or GBAtemp, hope you have a NAND Backup.
