### ISSUE TITLE
Update 13 broke Twilight menu 

### ISSUE THREAD

**Issue by Witop1** [LumaTeam/Luma3DS#1921]
New 3ds XL with cfw. All the latest update. Updated luma 13, when i open Twilight menu It goes full black and I have to reboot.

**Comment by Shadow322** [comment]
> New 3ds XL with cfw. All the latest update. Updated luma 13, when i open Twilight menu It goes full black and I have to reboot.

Not a Luma3DS problem

**Comment by Witop1** [comment]
When i disable Load external firm it works

Il Ven 21 Lug 2023, 08:33 Shadow322 ***@***.***> ha scritto:

**Comment by RandomMan25XX** [comment]
> When i disable Load external firm it works

Remove twibg.cxi from sd:/luma/sysmodules and you'll be fine

**Comment by Witop1** [comment]
Thanks, I opened an issue to Twilight anyway because this Is a workaround
not a fix

Il Ven 21 Lug 2023, 09:58 Captain_Jerkass96 ***@***.***> ha
scritto:

**Comment by TuxSH** [comment]
Fixed
