### ISSUE TITLE
New Luma 13.01 does not support Vapecord ACNL Plugin

### ISSUE THREAD

**Issue by StikoNiko** [LumaTeam/Luma3DS#1928]
The new Update is cool, and has Pluginsupport. 
Thank you for your Service.

With Old Luma3DS 12.1 
include 3GX Loader Edition 3DS 
i can play ACNL with Vapecord ACNL Plgin.
Version 1.9.6
And i can play MarioKart CTGP7

After this Update:
My ACNL Plugin is not supported and does not start.
My CTGP need Luma 13.01 .

I reinstalled an old backup.
And I hope for a solution to the problem.

**Comment by PabloMK7** [comment]
Hello, this is not a problem with Luma3DS. You should contact the developer of those projects to fix the issues.

In any case, I'm the developer of CTGP7 and I can confirm that the need of Luma3DS v13.0.1 is intentional.
