### ISSUE TITLE
[Suggestion] Could switching speed boost? (About plugin)

### ISSUE THREAD

**Issue by YSYD0315** [LumaTeam/Luma3DS#1930]
So, I'm using [Luma_3GX 12.0.1](https://github.com/PabloMK7/Luma3DS_3GX/releases/tag/v12.0.1) with everything fine, then I changed the luma to the Official 13.0.1. With every setting in same, I launched and played Monster Hunter XX with 1.4.0 update & [.3GX Plugin](https://github.com/mikewii/Luma3DS-plugin/releases/tag/r2.0.0).  However, when I was trying to switch from game to home menu, closing the game, even just pressing the power button, I found that system needs more time to respond my action (multiple tested, nearly 10s avg.). Even system software booted with plugin will cause the issue as well. Rollbacked the luma then, no obvious lag occured. 
  For now, I highly sus it was the ver.13.0.1 that occured the problem. More test may needed.
Thanks for everything you guys have made so far!

**Comment by PabloMK7** [comment]
Hello, this has been fixed in [dd22a0c](https://github.com/LumaTeam/Luma3DS/commit/dd22a0cd93780b0a825507a1c91310c3ed008f0e).
