### ISSUE TITLE
System update required after Luma3ds update.

### ISSUE THREAD

**Issue by metalfoxdev** [LumaTeam/Luma3DS#1934]
A new version (v13.0.1) of luma3ds was released and I updated through Universal Updater like I always do, The update was successful and I ran the "setup luma3ds to ctrnand" script from GM9megascript in godmode9 like I always do. I then rebooted the system and various games and eshop will not start without a "system update" despite the fact I am on the latest version (confirmed by pressing L+Down+Select). I have this issue on two 2DS XLs that I own, both have the latest versions of boot9strap and luma3ds v13.0.1E and have no extra modifications to the cfw. I am not sure what would be causing this. Is this a bug?

**Comment by PabloMK7** [comment]
Hello,

The problem reported here seems to be specific to your situation and not a general issue of Luma3DS. You will get better and more fluent support if you ask in a forum related to 3DS homebrew or in the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh).
