### ISSUE TITLE
Luma 13.0.1 does not work (black screen, but blue LED lights up for a few seconds)

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#1936]
Hi,

I wanted to update my console (I have **Luma 10.2.1** on an (old) 3DS XL with **system version 11.15.0-47E**). As Luma Updater not working, I did the update manually. So I downloaded the latest version 13.0.1 boot.3dsx + boot.firm from the official github page, then I replaced the two files (boot.3dsx and boot.firm) in the root of the SD card. I eject the SD card properly, I put it back in the console and the blue light comes on for about 8 seconds and goes out, the console does not start, yet I have not touched anything else...

I made a backup of my old boot files (10.2.1) and the console restarts, fortunately, but I can't update, so I'm definitely stuck with this old version? What should I do ? There is absolutely no backlighting, the screen remains totally black, there is just the blue LED which lights up for 7 or 8 seconds, then goes out. Should I install a 12.x version instead ?

**Comment by Saimiau** [comment]
Try to ask for help in the [Nintendo Homebrew Discord](https://discord.gg/MWxPgEp) or try following [this part](https://3ds.hacks.guide/troubleshooting#powernotification-light-indicators) of the troubleshooting guide
