### ISSUE TITLE
Error code 0xf9605002

### ISSUE THREAD

**Issue by erikiorai** [LumaTeam/Luma3DS#1937]
I know this error code is a hardware camera problem but what exacly its that camera module is not detected on 3DS or that camera module is connected on 3DS but has issue with the Camera module?

**Comment by PabloMK7** [comment]
Hello,

The problem reported here seems to be specific to your situation and not a general issue of Luma3DS. You will get better and more fluent support if you ask in a forum related to 3DS homebrew or in the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh).
