### ISSUE TITLE
[FEATURE REQUEST] custom luma theme.

### ISSUE THREAD

**Issue by ohhq** [LumaTeam/Luma3DS#1938]
being able to have a custom theme on the luma overlay. or simply being able to change the font, size of the text, color etc i think this would be a great feature!

**Comment by PabloMK7** [comment]
Hello,

Adding theme support to Rosalina would be a waste of resources (CPU and memory), so it's not going to happen, sorry.

**Comment by ohhq** [comment]
its all good! thank you for taking time to look at my request!
