### ISSUE TITLE
after updating to 13.0.2 my internet started going in and out

### ISSUE THREAD

**Issue by Geeksquad130** [LumaTeam/Luma3DS#1939]
so after I've updated to the latest version of luma3ds and now the internet is going in and out I'm on the new 3ds xl. I'm new to having my 3ds homebrewed I just did it yesterday. I didn't have internet issues when on 13.0.1

**Comment by PabloMK7** [comment]
Hello,

There were no changes related to internet stuff in the latest release, it's just a coincidence. If you are still having issues please ask in a forum related to 3DS homebrew or in the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh).
