### ISSUE TITLE
v13.0.2 version incorrect

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#1942]
![image](https://github.com/LumaTeam/Luma3DS/assets/15938645/ec995dca-00cc-471d-b348-723cbdeb28ab)

**Comment by ihaveamac** [comment]
Are you sure you installed the right version? The release has the correct version number

**Comment by PabloMK7** [comment]
Just checked and the version number is good. Make sure you are booting from the SD and you really installed the latest version.
