### ISSUE TITLE
Is it possible to add save state / RTS for 3DS games?

### ISSUE THREAD

**Issue by heptominoes** [LumaTeam/Luma3DS#1944]
Title.
Sorry if wrong section. Just wondering if that's possible to implement?
Like dump the RAM for a specific game and next load the RAM for the same game to continue from the last action?

**Comment by PabloMK7** [comment]
Hello, this is a page for developers to keep track of issues and feature requests, and not for general questions. I recommend asking in a forum related to 3DS homebrew or in the  [Nintendo Homebrew discord server](https://discord.gg/C29hYvh).

In any case, not really possible, but you can check NTR CFW which has an RTS implementation that work in some games within the same play session.
