### ISSUE TITLE
[Feature Request] Allow otp.bin to be loaded from file

### ISSUE THREAD

**Issue by Sayora77** [LumaTeam/Luma3DS#1946]
I have a very niche situation where I want to have the nand from a (now broken) US 3ds motherboard be completely transferred to a JP 3ds and I actually was able to succeed in that even having my NNID working to access the 3ds eshop (or what's left of it anyway) and the few other remaining Nintendo Network features. But, it requires this specific Luma fork https://github.com/truedread/Luma3DS https://gbatemp.net/threads/release-luma3ds-mod-to-unban-a-console-with-022-2812.565173/ in order to truly replicate the old system which allows an otp.bin to be loaded from a file in the luma folder. It's just not updated so it would be nice to be incorporated into regular Luma.

**Comment by PabloMK7** [comment]
Just leaving here the relevant commit in the specified repo: https://github.com/truedread/Luma3DS/commit/aa395a5910113b991e6ad7edc3415152be9bbb03

**Comment by cooolgamer** [comment]
I added this to my updated fork of luma that try to include as much features as I can (while keeping stability) https://github.com/cooolgamer-cuz-github-fork-system-sucks/Luma3DS-but-better
I hope this solves your issue

**Comment by TuxSH** [comment]
Sorry for taking a long time to close the issue, but we're not interested in console impersonation.
