### ISSUE TITLE
An exception occured Arm11 core 0

### ISSUE THREAD

**Issue by Pjaminals** [LumaTeam/Luma3DS#1947]
**System model:**

 New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

[11.17 europe]

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap I think

**Luma3DS version:**

The latest version

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (auto )

Splash: ( idk)

Splash duration: (idk )

PIN lock: (for certain games I have to enter the pin )

New 3DS CPU: ( idk)

--

Autoboot EmuNAND: ( idk)

Use EmuNAND FIRM if booting with R: ( idk)

Enable loading external FIRMs and modules: ( idk)

Enable game patching: (idk )

Show NAND or user string in System Settings: ( idk)

Show GBA boot screen in patched AGB_FIRM: ( idk)

Set developer UNITINFO: ( idk)

Disable Arm11 exception handlers: (idk )

Enable Rosalina on SAFE_FIRM: ( idk)

--

**Explanation of the issue:**
Whenever I boot up my homebrewed new 3ds xl with the sd card in it it shows arm 11 core 0 an exception occurred.without the sd card in the 3ds it boots up normally and acts like a normal 3ds.The issue started when I was playing pokemon moon I saved the game exited it and then I pressed the power button on the 3ds and then the home button to go back to the home menu which is how the error came up.
![1692271235621167199319865482657](https://github.com/LumaTeam/Luma3DS/assets/142499766/87df9d37-d42e-4961-a1ba-551e5b254ffe)

**Steps to reproduce:**

1.put the sd card in the 3ds with mods on it.

2.boot up the 3ds and it happens.

**Dump file:**

**Comment by PabloMK7** [comment]
Hello,

The problem reported here seems to be related to corrupted storage, please follow the next steps:

If your game is a physical copy or a cartridge, take a look at [this post](https://github.com/skawo/GodMode9-with-Cartridge-Fixer). However, if your game is a digital copy, or if you have installed any updates or DLC to the game, your SD card may be corrupted. The following steps may help:

1) Remove the SD card from your 3DS and insert it into your computer. (Or any other device that is able to read SD cards.)

2) Copy all the contents from your SD card and paste them to a folder in your computer. This step is very important to prevent data loss.

3) Use your preferred formatting tool to format your SD card to FAT32 (even if it is already formatted to FAT32). If you need a guide read [this](https://3ds.hacks.guide/formatting-sd-(windows)).

4) Copy all the files you backed up in step 1 to your SD card again. This will rebuild the file system and remove any possible corruption.

5) Try to replicate the steps where SD corruption was causing issues. If you still are having issues, you will have to reinstall the application as the files were damaged (corruption won't damage them again). Make sure to backup the save file with any save manager before doing the reinstall!

6) If after doing the steps listed above you are still having issues, or corruption happens again in a short time, your SD card may be damaged or unreliable and has to be replaced. You can make sure by following [this guide](https://3ds.hacks.guide/h2testw-(windows)).

If the steps listed here don't help, please consider joining the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh) and asking for help there.
