### ISSUE TITLE
[Feature Request] 800px and Antialiasing toggle

### ISSUE THREAD

**Issue by Trickiy** [LumaTeam/Luma3DS#1948]
It would be nice to make things look HD for old and new 3ds's. would have a performance dip but have it be a novelty thing for the old 3ds

**Comment by PabloMK7** [comment]
Hello. That's not possible as it requires non-trivial per game patches.

**Comment by Trickiy** [comment]
could you add it to ctgp-7 then?

**Comment by impeeza** [comment]
You can ask on ctgp-7 support page is not luma related

**Comment by Trickiy** [comment]
thanks but I can't find the support page

**Comment by PabloMK7** [comment]
> thanks but I can't find the support page

No need to, I'm the main developer of CTGP-7 and I'll consider taking a look at this at some point.

**Comment by vengestone-dragoon** [comment]
I have an idea for implimenting this globally from luma, though i dont have the know-how to actualy impliment it.
if you could force the system to stay in 3d mode when the slider was at the bottom and force specific depth settings, overriding/ignoring what the front cammera sees, i think the system could think its rendering sterioscopic 3d, but the result would be the hd 2d image.
Maybe just forcing the depth slider valu to be 0 or negative?

**Comment by profi200** [comment]
That's not how it works. The GPU needs to render the whole 240x800 frame. In 3D mode it's configured to render 2 240x400 frames with different angles and 2 separate frame buffers are used for each eye. This boils down to the same answer given above. This requires per-game patches.

**Comment by vengestone-dragoon** [comment]
Im saying if you could overide the positions, angles, and distances of the 2 240x400 frames, you could get them to line up as the single 2d view with the hd resolution. Make the two veiws face the same direction with a verry small distance(1px) between them.
basically just overriding the depth slider on old3ds to "no depth", and overriding the face tracking on new3ds to remain stationary and not shift with the users face

**Comment by profi200** [comment]
It's the game which is in control of all of these render settings. Again, to change them you need per-game patches. If you override the 3D slider to a fixed off position in software the outcome is also game specific. Some games will switch to rendering 1 240x400 frame and others will keep rendering twice but never show you the second frame.

**Comment by vengestone-dragoon** [comment]
K then,
seems strange to me that nintendo would leave the 3d functionality to developers. Its a feature accrose almost all games and on new3ds its got more features, so i would have thout it would be a system service basicly.
oh well then, patching individual games it is

**Comment by profi200** [comment]
My last response since this is not a forum.
An extra service is not required since all we are doing is rendering twice with different settings and using 2 frame buffers. There is nothing really you can hook into except GPU command list submission. This command list can be huge so it's not possible to scan through it and change render parameters without affecting performance. This is the reason they could not fix the gspwn vulnerability because it would impact performance. Even if we did it anyway the game is in control of everything else like buffer allocation.
