### ISSUE TITLE
Adding custom text when prompted for PIN on boot

### ISSUE THREAD

**Issue by rysian** [LumaTeam/Luma3DS#195]
I feel having the ability to display custom text on the enter PIN screen would be a good enhancement. For example, adding in lost & found info ("If found, please call...") or any other special information would be perfect since it is displayed on boot before anything else shows up. I understand the text can be modified though the pin.c file, but it would be nice to have custom text as an official option, with the text being possibly read though a text/config file. Although it isn't critical, I can see this being a great enhancement, as there isn't a really good way to convey important information/instructions on the console in general.

Thanks!

**Comment by AuroraWright** [comment]
Done.
