### ISSUE TITLE
New 3ds/2ds (Clock + L2 Cache issue)

### ISSUE THREAD

**Issue by DraggieDSlol** [LumaTeam/Luma3DS#1952]
Heya!

Lately I have had the problem that my New 3ds has this option activated in some games, in the Luma menu I have this option deactivated (Clock + L2) but mysteriously in other games it is activated, causing me a lot of slowdowns, in some titles like "Dillon Rolling Western".
When I want to open the Luma menu to disable the options, the game freezes!!! having to reset all my progress, It is quite annoying, because when I make the changes I save the configuration, but when I open the game again or enter sleep mode, it just restarts and activates the Clock + L2 again!!!

I can have some help??? Thanks for your attention!
![20230829_001420](https://github.com/LumaTeam/Luma3DS/assets/78944645/75106e9d-d80d-468d-90d9-224687897923)

**Comment by PabloMK7** [comment]
Hello,

The problem reported here seems to be specific to your situation and not a general issue of Luma3DS. You will get better and more fluent support if you ask in a forum related to 3DS homebrew or in the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh).
