### ISSUE TITLE
Luma3ds without cheats

### ISSUE THREAD

**Issue by Ne0kei** [LumaTeam/Luma3DS#1958]
Can someone plz build me a luma3ds boot.firm without cheats option in rosalina menu? would be very helpful, Thanks in Advance

**Comment by ihaveamac** [comment]
What do you need this build for?

**Comment by Ne0kei** [comment]
> What do you need this build for?

for myself actually

**Comment by ihaveamac** [comment]
What I mean is why you need a build with this option removed.

**Comment by Ne0kei** [comment]
Always having an option for cheats ruins the stock experience for me

**Comment by ihaveamac** [comment]
If you don't enable any cheats then it will do nothing at all.

**Comment by PabloMK7** [comment]
Hello, this is a page for tracking issues and feature requests for Luma3DS, not a page for personal requests. Please ask in a support forum or in the Nintendo homebrew discord server.

**Comment by Ne0kei** [comment]
but still it affects the experience because how easy it is to use them, anyway if no one can help me here then ill ask it on the forum

**Comment by Shadow322** [comment]
> Can someone plz build me a luma3ds boot.firm without cheats option in rosalina menu? would be very helpful, Thanks in Advance

If u really want it removed build it yourself

**Comment by Ne0kei** [comment]
> > Can someone plz build me a luma3ds boot.firm without cheats option in rosalina menu? would be very helpful, Thanks in Advance
> 
> If u really want it removed build it yourself

wish i could but dont know programming

**Comment by ihaveamac** [comment]
> but still it affects the experience because how easy it is to use them, anyway if no one can help me here then ill ask it on the forum

That’s a personal issue that you need to deal with yourself. Don’t use the option if you don’t want to.

Keep in mind that even if you do acquire a build with this option hidden, you will need to keep re-applying it manually for each future update to Luma3DS. The effort is not worth it.

**Comment by Ne0kei** [comment]
reapplying wont be necessary as i dont use rosalina menu anyways, i tried putting older version of luma3ds without cheat release but that gave me an error so
