### ISSUE TITLE
Rosalina menu not displaying on 4.5x

### ISSUE THREAD

**Issue by m4x10187** [LumaTeam/Luma3DS#1959]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

4.5.0-10E (SysNAND) and 6.2.0-12E (EmuNAND+GW)

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap (latest as of writing)

**Luma3DS version:**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

v13.0.2

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: (YES)

Enable loading external FIRMs and modules: (YES)

Enable game patching: (YES)

Show NAND or user string in System Settings: (YES)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
The Rosalina menu will not display if L+Down+Select was pressed on SysNAND. If the system was updated, however to say a higher version like 6.2E, then Rosalina will work as intended.

**Steps to reproduce:**

1. Downgrade a higher system firmware to 4.5.0-10.

2. Hold down L+Down+Select.

**Dump file:**

**Comment by PabloMK7** [comment]
Hello, from the release notes of 13.0.2, custom sys modules (including Rosalina) are no longer available on versions 4.x. This is expected behavior.
