### ISSUE TITLE
Sleep mode download not work in any 6.XX version

### ISSUE THREAD

**Issue by celula82** [LumaTeam/Luma3DS#196]
rying to use Sleep Mode Download does, in fact, yield a System Update message ("In order to use this function, you must perform a System Update." etc) in all 6.XX version of luma (6.1.2 incl.) and only works in 5.5 in my normal new 3ds. My new 3ds XL works well with luma 6.1.2 and sleep mode download. I have the same archives in te sd cards! Why? Please, help.
Look a video:
https://twitter.com/kyosuke82/status/772785052828725252

**Comment by droped** [comment]
Try deselecting "Use sysnand FIRM if booting with R (A9LH)". If you're using this because of ntr, use BootNTR loader from here: https://github.com/SirBeethoven/BootNTR/releases

**Comment by celula82** [comment]
Same with deselecting that option. I dont use ntr.

**Comment by AuroraWright** [comment]
"My new 3ds XL works well with luma 6.1.2 and sleep mode download." Go to system settings and update, I think some title might be out of date...

**Comment by ghost** [comment]
Same issue with me. My n3ds is already up to date (manually updated with 3DSNUS and sysupdater).
New 3DS A9LH 11.0.0-33E SysNand

**Comment by celula82** [comment]
When I try update, the console said it is already updated

**Comment by exegg** [comment]
It's working just fine on my O3DS. 11.0.0-33U with Luma 6.1.2

**Comment by ghost** [comment]
OK, so to be precise, the download works if the 3ds is in sleep mode, but the "Y Complete Download Now" feature doesn't ("you need to perform a system update"...)

**Comment by exegg** [comment]
I did exactly what @celula82 posted in the video. No issues.

**Comment by celula82** [comment]
The download dont work any mode, y button or in sleep mode

**Comment by Committee** [comment]
N3DS XL here on the latest firmware using latest luma3ds release menuhax entrypoint y button update works, have you tried entering the EShop and check if the error persists?

**Comment by celula82** [comment]
Yes, I can donwload games from eshop but not with y button or sleep mode.

**Comment by Margen67** [comment]
@Committee

> menuhax

ew

**Comment by celula82** [comment]
No menuhax, I use arm9 + luma sysnand 11.0 Eur

**Comment by piratesephiroth** [comment]
Sleep mode works. "Download now" with the Y button doesn't.

**Comment by ghost** [comment]
OK, so good news! With me, the problem is fixed with https://github.com/AuroraWright/Luma3DS/commit/b74dda42a2325030b63f9fe93c44ea0d0bc08a51
@piratesephiroth and @celula82 please try to use the latest luma3ds build.

**Comment by piratesephiroth** [comment]
Yep. Seems to be working fine now.
