### ISSUE TITLE
Compile Error：implicit declaration of function

### ISSUE THREAD

**Issue by asypost** [LumaTeam/Luma3DS#1960]
git clone the latest code and compile,the output says:
D:/Luma3DS/sysmodules/rosalina/source/menus/sysconfig.c:268:9: error: implicit declaration of function 'ACI_LoadNetworkSetting' [-Werror=implicit-function-declaration]
  268 |         ACI_LoadNetworkSetting(i);
      |         ^~~~~~~~~~~~~~~~~~~~~~
D:/Luma3DS/sysmodules/rosalina/source/menus/sysconfig.c:269:9: error: implicit declaration of function 'ACI_GetNetworkWirelessEssidSecuritySsid' [-Werror=implicit-function-declaration]
  269 |         ACI_GetNetworkWirelessEssidSecuritySsid(ssids[i]);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1.exe: all warnings being treated as errors

**Comment by ihaveamac** [comment]
Those are newer functions introduced in libctru recently: https://github.com/devkitPro/libctru/commit/5b2a9f6136e5f26b22e8113795732096cb445de8

**Comment by PabloMK7** [comment]
You need to manually compile and install the latest libctru. git clone it then make install
