### ISSUE TITLE
ErrDisp while booting Luma 3ds

### ISSUE THREAD

**Issue by WICKY419** [LumaTeam/Luma3DS#1963]
I was booting Luma and I got An error ocurred (ErrDisp)
Error Type: generic
Process ID: 15
Process Name: menu
Process Title ID: 0004003000008f02
If anyone could help that would be great

**Comment by PabloMK7** [comment]
Hello, this is a place for tracking Luma3DS issues, and not appropriate for giving support. You will get quicker and more fluent support if you ask in a homebrew related forum or in the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh).
