### ISSUE TITLE
How to build a valid .3gx plugin for latest Luma?

### ISSUE THREAD

**Issue by LITTOMA** [LumaTeam/Luma3DS#1968]
Hi, I built a 3gx file using https://github.com/Nanquitas/3gxtool and it produce a plugin file which magic is "3GX$0001". However the latest version of luma requires "3GX$0002". How should I make it?

**Comment by PabloMK7** [comment]
https://gitlab.com/thepixellizeross/3gxtool

**Comment by LITTOMA** [comment]
This one works. Thanks!
