### ISSUE TITLE
Problems Running NTR on 6.1.2

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#197]
Not sure if it's the new BootNTR fault for 11 firm or just luma 6.1.2, but there's a much higher rate of locking up when the nintendo 3ds logo comes up after loading a game. Could be something I'm doing wrong too I suppose

**Comment by poutros** [comment]
This only happens for me if I try to load a game after having loaded and exited a game with a plugin. This is a problem with ntr, not luma.

**Comment by ghost** [comment]
I jumped the gun on this. I should have made sure I had a way to recreate it before actually posting. Anyway it was doing it when the game started, not when I exited and relaunched a game with a plugin
