### ISSUE TITLE
[EXHEADER WARNING] Parameter Not Found: "AccessControlInfo/ServiceAccessControl"

### ISSUE THREAD

**Issue by asypost** [LumaTeam/Luma3DS#1972]
Build the lastest source code and output 
```
[EXHEADER WARNING] Parameter Not Found: "AccessControlInfo/ServiceAccessControl"
```

**Comment by Shadow322** [comment]
> Build the lastest source code and output
> 
> ```
> [EXHEADER WARNING] Parameter Not Found: "AccessControlInfo/ServiceAccessControl"
> ```

ignore it that error has always been there
