### ISSUE TITLE
copying boot.3dsx doesn't work

### ISSUE THREAD

**Issue by daydreamyyZX** [LumaTeam/Luma3DS#1977]
**System model:**

Old 3DS

**Explanation of the issue:**
copying the boot.3dsx file to windows doesn't work at all. is it essential to luma or can it work without?

**Steps to reproduce:**

1. put sdcard in pc

2. try to copy boot.3dsx to desktop for example

**Comment by PabloMK7** [comment]
Hello, this is not a support forum, but a website to report bugs and issues about Luma3DS. Please ask in a forum or in the Nintendo homebrew discord server.
