### ISSUE TITLE
ZL/ZR buttons not working

### ISSUE THREAD

**Issue by B3ts** [LumaTeam/Luma3DS#1978]
In the game IRONFALL Invasion if the option "Enable loading external FIRMs and modules" is enabled on Luma settings cause the ZL/ZR buttons to not work at all in game. With it turned off works as intended.

**Comment by Shadow322** [comment]
> In the game IRONFALL Invasion if the option "Enable loading external FIRMs and modules" is enabled on Luma settings cause the ZL/ZR buttons to not work at all in game. With it turned off works as intended.

Then don't use that setting then the buttons will work

**Comment by CycloKid** [comment]
@Shadow322 i believe they wanted to be able to have it enabled AND be able to use zl/zr. obviously they can disable that but the point of opening the issue was to fix it.

**Comment by PabloMK7** [comment]
> In the game IRONFALL Invasion if the option "Enable loading external FIRMs and modules" is enabled on Luma settings cause the ZL/ZR buttons to not work at all in game. With it turned off works as intended.

I doubt the issue is caused by that option. It's possible it's caused by a loaded plugin. Can you please confirm you weren't using any plugins?

**Comment by B3ts** [comment]
I wasn't using any 3gx/ntr plugin

**Comment by TuxSH** [comment]
Please upgrade rehid if that's what you were using (highly likely considering "if the option "Enable loading external FIRMs and modules" is enabled on Luma settings")

**Comment by alexbatesdev** [comment]
I was facing this problem as well, but upgrading rehid didn't work.
Since this issue is what comes up when you google this symptom I want to add some additional info for anyone else who runs into this.

If updating rehid doesn't work and you just want to remove it, these are the files to remove from your SD card:
```
/luma/sysmodules/0004013000001D02.cxi
/luma/sysmodules/0004013000003302.ips
/luma/sysmodules/rehid.cxi
```
