### ISSUE TITLE
Arm11 core 1, Prefetch Abort (svc break), debug event, NS error

### ISSUE THREAD

**Issue by Nael2504** [LumaTeam/Luma3DS#1979]
I don't know why is happening.. its a old 3ds and now he cant turn on
But it showed this screen for one moment
![065074fa-1084-4dad-952c-0b56984f930f](https://github.com/LumaTeam/Luma3DS/assets/154467174/5d619c30-c126-41be-8cbf-069eaf508295)

**Comment by PabloMK7** [comment]
Hello, this page is for tracking bugs with Luma3DS, and not suitable for support. Please ask in a forum or in the Nintendo homebrew discord: https://discord.gg/C29hYvh
