### ISSUE TITLE
Stuck on AureiNand 5.1.2 Configuration screen

### ISSUE THREAD

**Issue by TheAzure289** [LumaTeam/Luma3DS#198]
Tried to fix an online connectivity error by updating the arm9loaderhax.bin, my 2ds wouldn't boot so I went back to my old bin and now I'm stuck at the config screen. It will not save my choices, just refreshes without moving on.

**Comment by Margen67** [comment]
Try the latest bin from https://github.com/AuroraWright/Luma3DS/releases

**Comment by TheAzure289** [comment]
ok 6.1.2 popped up but froze when i made my choices. my system firmware is updated to the latest. what choices should be on?

**Comment by TheAzure289** [comment]
it is still frozen. i selected, show current nand in system settings and show gba boot screen

**Comment by poutros** [comment]
Select autoboot sysnand.

**Comment by TheAzure289** [comment]
That did the trick! Thank you!!

**Comment by fox8091** [comment]
So..if the issue is fixed, can this be closed? Also, this isn't a forum. Things like this belong somewhere like GBATemp.
