### ISSUE TITLE
HELP WITH MY 3DS URGENTLY!!!

### ISSUE THREAD

**Issue by fsbnadzor** [LumaTeam/Luma3DS#1980]
There was an ARM 9 error on my 3DS. And I decided to fix it, I updated Luma to version 13.2. Copied the files to Sysnand. My 3DS was restored to factory settings, but the game saves remained. I did everything according to these instructions https://3ds.hacks.guide/ctrtransfer.html. BUT ! When I actually used Rosalina’s menu and re-entered the Download play application, I got this error. Nothing helps me, I downloaded and replaced the files boot.3dsx and ctr-no-timeoffset.3dsx,FBI.3dsx, but it didn’t help me, I didn’t find solutions on the Internet. HELP ME PLEASE !!!

here is my dump file: https://drive.google.com/file/d/1qNMf7ToaPN0dFSmr8ZVZUZIf2qk1psjm/view?usp=drive_link 

![IMG_20231227_203402_751](https://github.com/LumaTeam/Luma3DS/assets/154924533/84ff9a0b-d7f0-4037-b688-a41433dcba53)

**Comment by PabloMK7** [comment]
Hello, this page is for tracking issues related to Luma3DS, and is not a support forum. Please ask in a homebrew related forum or in the Nintendo Homebrew discord server: https://discord.gg/C29hYvh
