### ISSUE TITLE
Region change?

### ISSUE THREAD

**Issue by pmcc-notverysmartguy** [LumaTeam/Luma3DS#1982]
**System model:**

2DS

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]
Sys 11.17.0-50E

**Entrypoint (How/what you're using to boot Luma3DS):**

I don't know. I wasn't the one that modded it.

**Luma3DS version:**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

Luma3DS v13.0.1 ESP

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

Autoboot EmuNAND: ( )

I don't know what an EmuNAND is. Sorry.
Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (What?)

Show NAND or user string in System Settings: (What?)

Show GBA boot screen in patched AGB_FIRM: (What?)

Set developer UNITINFO: (What?)

Disable Arm11 exception handlers: (What?)

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
I got a 2DS in Spain. When I got it, it was all in Spanish. Thankfully I can read Spanish, but prefer English. I decided to do a regular factory reset on it.
When I started following the instructions on 3ds.hacks.guide, it stopped me. It asked me to hold select while powering on. Luma3DS configuration happened.
I want to uninstall the CFW on here, but the website said:

If you have done ANY of the following:

[Changed the region](https://3ds.hacks.guide/region-changing) of the console
Installed a custom keyboard
Installed a custom HOME Menu (not a custom theme)
Manually changed the encryption key (movable.sed) of the console
Unbanned the console
then uninstalling CFW WILL BRICK YOUR CONSOLE. If this applies to you, [restore a clean NAND backup](https://3ds.hacks.guide/godmode9-usage#restoring-a-nand-backup) before continuing.

Maybe I don't want to brick my 2DS. How can I uninstall the Spanish CFW and remod it to put in an English CFW?
**Dump file:**

I didn't get a dump file. No error message.

**Comment by PabloMK7** [comment]
Hello, this is a place dedicated to track Luma3DS issues and not a support forum. Please ask in a homebrew related forum or in the Nintendo Homebrew discord server: https://discord.gg/C29hYvh
