### ISSUE TITLE
An Exception Occurred, arm11 core 1 pm undefined instruction

### ISSUE THREAD

**Issue by bwueee** [LumaTeam/Luma3DS#1991]
Hi! In 2020 I was big on my 3ds and modded it. Lost the SD card but I am wanting to try and “unbrick” it. I do not have the old SD card. I cannot do anything beyond this screen and holding select opens a menu as well. What can I do? 
![image](https://github.com/LumaTeam/Luma3DS/assets/157423604/bdc008ee-6382-4390-816b-d76c9ca09837)
![image](https://github.com/LumaTeam/Luma3DS/assets/157423604/a5db3a98-2a25-47bb-aed5-8681a27e0b7f)

**Comment by PabloMK7** [comment]
Hello, this is a page dedicated to track Luma3DS bugs and suggestions, and not appropriate for giving support. Please ask in a homebrew related forum or in the [Nintendo Homebrew discord server](https://discord.gg/C29hYvh)!
