### ISSUE TITLE
[Feature Request] Add LayeredFS support for updates

### ISSUE THREAD

**Issue by CyberYoshi64** [LumaTeam/Luma3DS#1993]
LayeredFS currently only allows patching the base game romfs because it only replaces files for the mountpoint `rom:`.
Because of this update data (using the `ro2:` mountpoint) are left untouched and the game prioritizing the update over the base romfs simply breaks LayeredFS changes. I have eluded to this before but I wasn't great at describing it back then (Issue 1659).
The Mario Kart 7 1.2 update is a recent example. As a result, mods that change the in-game text (or fonts) simply don't work anymore, because the game reads the files from the update and thus not from LayeredFS either.

MK7 uses a folder called `Patch` to replace files for its SZS containers without changing the underlying archive files themselves. However, adding the Patch folder and adding appropriate files in it simply don't work either, because the update's files are left intact. My previous game, SmileBASIC, just replaces files through the update romfs as usual, but it didn't work either. My bypass was to find the mountpoint names in the game's code and swap them, but this is really hacky and very fragile in case another update would release.

It would be appreciated if updates could obtain LayeredFS support. Perhaps by adding a new folder called `update-romfs` or so.
Thank you for your consideration.

**Comment by AuroraWright** [comment]
it’s already supported, but maybe it doesn’t support the mount name in mario kart 7 (?)
see here for already supported mount names https://github.com/LumaTeam/Luma3DS/blob/e2778a45cf379270c3039aab16bb607178561cc1/sysmodules/loader/source/patcher.c#L582

**Comment by CyberYoshi64** [comment]
There is `rom2` but some games use `ro2` instead.
However, MK7 seems to use another name that is a little hard to find. I'll try experimenting with this name list.

Mario Kart 7 mounts it in a somewhat unusual way. I found the string `pat1` in the code, but I have to leave out the colon in that string array, otherwise LayeredFS doesn't apply to the update.

**Comment by PabloMK7** [comment]
> There is `rom2` but some games use `ro2` instead. However, MK7 seems to use another name that is a little hard to find. I'll try experimenting with this name list.
> 
> Mario Kart 7 mounts it in a somewhat unusual way. I found the string `pat1` in the code, but I have to leave out the colon in that string array, otherwise LayeredFS doesn't apply to the update.

If you PR that simple fix can be merged
