### ISSUE TITLE
Rosalina Menu does not display if App has turned off lower screen

### ISSUE THREAD

**Issue by Megaflare448** [LumaTeam/Luma3DS#1996]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

Sys 11.17.0-50E

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v13.0.2

**Luma3DS configuration/options:**

Default EmuNAND: (-)

Screen brightness: (4)

Splash: (Off)

Splash duration: (-)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: (-)

Use EmuNAND FIRM if booting with R: (-)

Enable loading external FIRMs and modules: (No)

Enable game patching: (No)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (No)

Set developer UNITINFO: (-)

Disable Arm11 exception handlers: (-)

Enable Rosalina on SAFE_FIRM: (-)

--

**Explanation of the issue:**
When a HB app lower screen (eg Retroarch), the Rosalina Menu does not show, although appears to function normally as the app will halt until the menu is exited/cancelled. Invoking the Rosalina Menu should check status of lower screen, enable it, then restore to existing state on exit.

**Steps to reproduce:**

1. Launch an App that disables the lower screen (such as Retroarch).
2. Attempt to access Rosalina Menu via hotkey (Left trigger, Select and Dpad Down).
3. Rosalina does not display.
4. As a check, Retroarch can enable the lower screen for menus after touching it--Rosalina Menu will display/function fine if Retroarch has turned the lower screen on.

**Dump file:**
No dump, as it does not crash.

Apologies if this is not the correct spot to put this. Just thought it was best to document it somewhere formally and allow it to be moved/filed as needed. I did see #752 but didn't think this fit with the description of a feature request. Hope this is ok.

**Comment by TuxSH** [comment]
Hi, thanks for the heads up. Unfortunately this is a limitation of the Rosalina Menu and will take lots of work to fix (though I plan to do it eventually).

You should press the Home Menu button to go to the home menu, as a general workaround to this
