### ISSUE TITLE
MVD Service not accessable

### ISSUE THREAD

**Issue by thedevleon** [LumaTeam/Luma3DS#200]
When trying to use the mvd service (with the provided [example](https://github.com/devkitPro/3ds-examples/tree/master/mvd))

 mvdstdInit() returns 0xd8e06406.

As far as I could gather, this means the service is inaccessible.
Would it be possible to add patches to make this accessible from within homebrew apps?

**Comment by fox8091** [comment]
This requires service patches, which are implemented in the dev branch.

**Comment by thedevleon** [comment]
Thanks, but initializing the mvd service on the dev version gives me this:

![Exception](https://i.imgur.com/DtvrQ8z.jpg)

**Comment by Mrrraou** [comment]
Are you sure this is a Luma bug ? This is a crash in the mvd module.
You should use CIAs and add access for the mvd service/port in your CIA exheaders.
