### ISSUE TITLE
[REQUEST] setting to force sound to speakers or headphones at any time.

### ISSUE THREAD

**Issue by netherstef2** [LumaTeam/Luma3DS#2002]
My n3ds xl doesnt send sounds to the speakers and instead the headphones, i saw a earlier release from last year on a issue, i used it and it worked, i was hoping that it could be permanent setting in luma 3ds because many people have this issue and i cant play ctgp 7 on old versions of luma 3ds.

**Comment by TuxSH** [comment]
This is still a setting, just that you have you update config.ini manually
