### ISSUE TITLE
[Feature Request] Support for Injecting Files Over LZ Archives in LayeredFS

### ISSUE THREAD

**Issue by JulyIghor** [LumaTeam/Luma3DS#2004]
Hello Luma3DS Team,

I hope this message finds you well. I am reaching out to request a new feature that I believe could benefit many in the Luma3DS community, especially those involved in localization projects.

As a part of my efforts to make the Nintendo 3DS more accessible to Ukrainian speakers (and many other languages), I have undertaken the task of translating the firmware. This involves placing translated files in the `luma/titles` directory for LayeredFS to override the system's default files. However, I've encountered a significant hurdle: some of the files needed for a comprehensive translation are LZ archives containing copyright-protected images. Due to these restrictions, I am unable to distribute a complete translation package.

To address this and similar challenges faced by others, I propose the addition of a new LayeredFS layer. This layer would specifically support injecting files over existing LZ archives. Such a feature would not only facilitate the easier distribution of language packs but also ensure compliance with copyright laws by allowing translators to modify and distribute translations without including copyrighted materials directly.

Implementing this feature could greatly enhance the utility and versatility of Luma3DS for users worldwide by simplifying the process of creating and sharing translations. It would be a significant step forward in making the 3DS more accessible to non-English speaking communities.

Thank you for considering this request. I am looking forward to your thoughts and am happy to provide further details or clarification as needed.

**Comment by himo45** [comment]
I hope your suggestion is implemented

**Comment by PabloMK7** [comment]
Hello, this feature is not possible because it's game specific, unlike opening files from the romfs which is almost equal in all games.

You will need to manually patch the titles with IPS patches or create 3gx plugins.
