### ISSUE TITLE
luma3ds dosnt  let 3ds boot while  ds cart is inserted

### ISSUE THREAD

**Issue by GweshaDeneb** [LumaTeam/Luma3DS#2006]
System model: New 3DS XL

**SysNAND version  11.17.0-50U

Entrypoint:Boot9Strap

Luma3DS version: 13.0.2

Explanation of the issue:
 n3dsxl(might be the same for other 3ds versions) does not  fully boot up  with physical ds  game inserted into gamecard slot( stays in black screen) blue light stays but no yellow light and screen lighting up indicating it started up properly
booting the select options work  on start up but save/exiting dosnt help either stays in black screen after still 

also if it matters my ds cart is one of the other games (not pokemon ) that have the infrared sensor and i dont have a normal cart to try with it instead.

**Steps to reproduce:**

have ds gamecard inserted on boot up

**Comment by PabloMK7** [comment]
I've seen this happen in the past if the DS card was not properly inserted. I guess you already tried to remove it and insert it again?
Which is the game specifically?

**Comment by GweshaDeneb** [comment]
> I've seen this happen in the past if the DS card was not properly inserted. I guess you already tried to remove it and insert it again? Which is the game specifically?

i tried with a copy of walk with me  for the ir function but i realized after trying to reboot my n3ds it wouldn't boot unless i took out the ds cart  ive tryed it several times so i know it was because of having it inserted not sure why it does it though..

**Comment by rpdistiso** [comment]
Have you tried booting without it inserted and then once booted inserting the game card?

**Comment by GweshaDeneb** [comment]
> Have you tried booting without it inserted and then once booted inserting the game card?
yes the whole console boots like it should without the ds gamecard inserted  ds cart not 3ds cart btw 
 all of  my luma stuff is still on latest update so  i know its a issue with  current luma update  i dont have anything else to really test it fully  so
1 it boots completely without a ds cart  but  not with one inserted  while  booting 
2 3ds carts boot fine
3 it was as i mentioned one of the few ir carts other then the pokemon games cause i dont have any other  carts other then this one  currently on me

edit cause the quote broke  on me
