### ISSUE TITLE
Error trying to update luma

### ISSUE THREAD

**Issue by Kifaf** [LumaTeam/Luma3DS#2007]
Console version: New 3ds XL
Current luma version: 7.1

I get an error when trying to update luma, when I try to update luma to the latest version, it changes absolutely nothing in terms of the luma version, it continues with version 7.1.

**Comment by urherenow** [comment]
Do you have 7.1 installed in nand?

**Comment by Kifaf** [comment]
Yes, Micro SD

**Comment by Kifaf** [comment]
Yes microSD

**Comment by PabloMK7** [comment]
Hello, this is a page dedicated to track Luma3DS bugs and is not suitable for giving assistance. Please ask in a homebrew related forum or in the Nintendo Homebrew discord server: https://discord.gg/C29hYvh
