### ISSUE TITLE
Can not download Capture by Calling API

### ISSUE THREAD

**Issue by Jane-Eyre** [LumaTeam/Luma3DS#2009]
Hi all, 

I just successfully created capture by calling Luma AI API and got it shown in my Google browser, but I do not find any api call can help me with downloading this capture to my local machine, is there any api doc can help with that?

Thanks!

**Comment by PabloMK7** [comment]
Hello, you are probably not in the right repository. This is Luma3DS a custom firmware for the Nintendo 3DS, not an AI tool.
