### ISSUE TITLE
second emunand problem

### ISSUE THREAD

**Issue by srwgin** [LumaTeam/Luma3DS#201]
O3DS A9LH luma 6.1.2
I use emunand9 noemu format sdcard
then use 3ds-multinand_v1.61 format and inject 2 nand
these 2 nand backup by H9 both nand size 943MB
but it can only recognize 1 emunand
for example
I inject nandA in 1，nandB in 2
luma recongnize 1（nandA）
if I inject nandB in1，nandA in 2
luma recongnize 1（nandB）
when turn on Use second EmuNAND as default
always boot 1

**Comment by AuroraWright** [comment]
Works here with a dual emuNAND setup made using dd (maybe that tool you mentioned is buggy?). The code is the same as the other cfws.
