### ISSUE TITLE
[Feature Request] C-Stick emulation for O3DS in InputRedirection

### ISSUE THREAD

**Issue by isa56** [LumaTeam/Luma3DS#2011]
Is it possible to emulate the Circle Pad Pro / C Stick on the Old 3DS using Input Redirection?  That would be a very interesting feature for FPS or camera control on O3DS.

**Comment by TuxSH** [comment]
No, it is not possible to do that, this is far from trivial and requires fully reimplementing the `ir` sysmodule (AFAIK), thus this will not be done in the near future.

**Comment by isa56** [comment]
@TuxSH thank you for your answer. That's a pity, but totally understandable.

**Comment by YoshiCrystal9** [comment]
was searching for something related to circle pad pro around and found this, its a shame

**Comment by Zackeroo** [comment]
Yea me too haha . Them calling it trivial is sad. I wanted to use my Xbox controller for an FPS game on the 3ds. Everything was working fine but I couldn't move the camera around. The game had a circle pad pro option so I was hoping to use the right stick on the Xbox controller for that.

**Comment by jobukkit** [comment]
> Them calling it trivial is sad.

He said it's NOT trivial, to implement it. Not that the feature would be useless.
