### ISSUE TITLE
Excuse me,why can't luma show too many project cheats

### ISSUE THREAD

**Issue by Rendigga** [LumaTeam/Luma3DS#2012]
LUMA13.02   new3dsll   Boot9Strap  11.17 
Explanation of the issue:
Only about 100 items can be displayed,but my monster hunter XX has 300 cheat items.I hope to have it show more cheat items in the next release

**Comment by Rendigga** [comment]
![Uploading_20240403191438.png…]()

**Comment by Rendigga** [comment]
![B9688D36-D4F8-4210-A313-9300F4923B08](https://github.com/LumaTeam/Luma3DS/assets/165901973/6e37f33a-0d7a-48b6-b03a-752fcfebdb47)

**Comment by Rendigga** [comment]
Is there a problem with my luma version or settings, or is it that luma is not implemented at the moment😭😭😭

**Comment by Rendigga** [comment]
[0004000000197100.txt](https://github.com/LumaTeam/Luma3DS/files/14851362/0004000000197100.txt)

Please try it

**Comment by PabloMK7** [comment]
Hello, there is a limit with how many cheats can be loaded at a time due to memory and execution time restrictions.

**Comment by Rendigga** [comment]
Is there a chance to break through this restriction in the next version

**Comment by Rendigga** [comment]
> Hello, there is a limit with how many cheats can be loaded at a time due to memory and execution time restrictions.

Is there a chance to break through this restriction in the next version？🥹 Or can we make luma display more

**Comment by PabloMK7** [comment]
Yes, by downloading more ram to your console.

**Comment by Rendigga** [comment]
> 是的，通过将更多内存下载到您的控制台。

thank！🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷

**Comment by Rendigga** [comment]
> Yes, by downloading more ram to your console.

thank！🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷🌷

**Comment by Masamune3210** [comment]
........

**Comment by Rendigga** [comment]
> 是的，通过将更多内存下载到您的控制台。

Hello, I saw that luma was recently updated. Has the memory limit problem been solved? can more cheats be displayed now?pleases🥺🥺🥺

**Comment by Rendigga** [comment]
@PabloMK7
