### ISSUE TITLE
Luma3DS v13.02 [HID crashes on boot]

### ISSUE THREAD

**Issue by Rodostlyn69** [LumaTeam/Luma3DS#2014]
When booting into 3DS with Luma3DS v13.02, Luma3DS crashes and shows an Arm11 data abort by hid process (0004013000001D02). It does that after enabling both "Enable loading external FIRMs and modules" and "Enable game patching" options. Crash dump file:
[crash_dump_00000025.dmp](https://github.com/LumaTeam/Luma3DS/files/14904149/crash_dump_00000025.dmp)
Enabled settings:
Show NAND or user string in System Settings;
Show GBA boot screen in patched AGB_FIRM;
Enable custom upscaling filters for DSi;
Allow Left+Right / Up+Down combos for DSi.

**Comment by jonahkel** [comment]
I've been having that same issue, though only with "enable loading external FIRMs and modules. I hope it gets fixed so I can use Pretendo.

**Comment by urherenow** [comment]
And do you have the issue with external modules enabled, but with NO external modules to load? If not, then your issue doesn’t belong here. It belongs with that module.

**Comment by Rodostlyn69** [comment]
> And do you have the issue with external modules enabled, but with NO external modules to load? If not, then your issue doesn’t belong here. It belongs with that module.

I have the sysmodules, unlikely, so thats not the problem. Maybe I have the wrong sysmodules? Honestly, I don't know.

**Comment by urherenow** [comment]
I meant, leave the option on, but don’t use those sysmodules. When you add a particular one and get the error, then that module probably needs an update.

**Comment by Rodostlyn69** [comment]
> I meant, leave the option on, but don’t use those sysmodules. When you add a particular one and get the error, then that module probably needs an update.

I tried removing the sysmodules, but that didn't changed anything at all, same error.

**Comment by jonahkel** [comment]
I solved the issue by updating rehid. Try doing that and see if that helps! Just download the latest version of rehid helper and update it through there.

**Comment by Rodostlyn69** [comment]
> I solved the issue by updating rehid. Try doing that and see if that helps! Just download the latest version of rehid helper and update it through there.

Thanks for you help, it worked!

**Comment by jonahkel** [comment]
Glad to have helped!
