### ISSUE TITLE
[Feature Request] Changing brightness of the configuration/chainloader menu using volume slider.

### ISSUE THREAD

**Issue by Komas19-new** [LumaTeam/Luma3DS#2015]
I think it would be nice, for customization, that you can change the brightness of the configuration/chainloader menu using the volume slider, just like in GodMode9.

It would be nice to have in certain environment, where you can't see it.

**Comment by PabloMK7** [comment]
Hello, thanks for the suggestion, but a very small feature like that is not worth the resources to implement or maintain, as the time spent in that menu is very small.
