### ISSUE TITLE
New 3DS XL crashes on Luma 13.0.2 when opening MiiVerse or Link Account.

### ISSUE THREAD

**Issue by apassiou** [LumaTeam/Luma3DS#2017]
**System model:** New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** Both  Sys and Emu on 11.17.0-50U

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** 13.0.2

**Luma3DS configuration/options:** 

Default EmuNAND: (1)

Screen brightness: (2)

Splash: (Before)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: (Yes)

Enable loading external FIRMs and modules: (Yes) - for Pretendo

Enable game patching: (Yes) - For Pretendo

Show NAND or user string in System Settings: (Yes)

Show GBA boot screen in patched AGB_FIRM: (Yes)

--

**Explanation of the issue:**

When I hit MiiVerse icon or try to Link ID through settings the New 3DS XL crashes. I also have a standard 3DS XL and it does NOT crash. Attaching crash dumps and screenshots.

**Steps to reproduce:**

1. Be running Emunand. on New 3DS XL

2. Select Mii Verse icon from the top bar or Link ID via settings.

**Dump file:**
There is no  option to disable Arm 11 handlers in my menu. Is this deprecated info?

[Miiverse.dmp](https://github.com/LumaTeam/Luma3DS/files/15051739/Miiverse.dmp)
[Link ID.dmp](https://github.com/LumaTeam/Luma3DS/files/15051740/Link.ID.dmp)

![Photo Apr 21 2024, 02 45 37](https://github.com/LumaTeam/Luma3DS/assets/24600948/45b7b66a-8097-43c8-bf41-5ffde219e206)
![Photo Apr 21 2024, 04 11 35](https://github.com/LumaTeam/Luma3DS/assets/24600948/b779be07-2056-471e-8a7f-7b9ec719b41f)

**Comment by PabloMK7** [comment]
Hello, this place is designed to track Luma3DS bugs and not for assistance, you will get better support in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh
