### ISSUE TITLE
Having A Small Issue With My Luma.

### ISSUE THREAD

**Issue by grimsgore** [LumaTeam/Luma3DS#2018]
**Luma3DS configuration/options:**

Enable loading external FIRMs and modules: ()  [NOTE: I turned this on, turned off after error and works perfectly fine]

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Disable Arm11 exception handlers: ( )
--
**Explanation of the issue:**
Opens up Luma Menu, clicks on "Enable loading external FIRMs and modules," saves changes, boots up 3ds. Crashes for some reason?

**Reason why I was turning this on**
You may already assume, but I was installing Pretendo onto my 3DS. Already had game patching but not ELEFAM. I boot up my console, and it crashes.

Dump:

Processor: Arm11 (core 1)
Exception type: Prefetch Abort
Fault status: Permission - Page
Current Process: Camera (0004013000001602)

R0    0011F8C4       R1 00000010
R2     00000004      R3 00000000
R4      00000108     R5 0011F8C4
R6      00000010     R7 00000000
R8      00000000     R9 00000000
R10    00000000     R11 00000000
R12    00000000     SP 0FFFFFC0
LR      00113087     PC 0011D000
CPSR 20000010     FPEXC 00000000

Stack Dump:
0FFFFFC0: 00 01 00 00 04 00 00 00
0FFFFFC8: 00 00 00 00 00 01 00 00
0FFFFFD0: 00 00 00 00 79 2D 11 00
0FFFFFD8: 04 00 00 00 00 00 00 00
0FFFFFE0: E8 CE 11 00 F4 CE 11 00
0FFFFFE8: 00 00 00 00 8F FA 10 00
0FFFFFF0: 00 00 00 00 00 00 00 00
0FFFFFF8: 00 00 00 00 14 00 10 00

**Comment by Komas19-new** [comment]
pretendo should work fine.. however i see that the current process is "Camera", does your camera work?

Also, try redownloading the patches https://github.com/PretendoNetwork/Nimbus/releases/latest (make sure to download the combined.zip file)

If you again get issues, i think its better for you to ask for help in the Pretendo Network discord server

**Comment by PabloMK7** [comment]
Hello, this is for tracking luma3DS bugs, and not for assistance. You better ask for support in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh
