### ISSUE TITLE
Tomodachi Life Dutch version crash

### ISSUE THREAD

**Issue by SullyMan71** [LumaTeam/Luma3DS#2020]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.16.0-50E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v13.0.2

**Luma3DS configuration/options:**

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

--

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
During Dutch-exclusive holidays, going to the Supermarket in the European version of Tomodachi Life with the 3DS' region set to Dutch and the language to English crashes the game

**Steps to reproduce:**

1. Use a European 3DS

2. Set the region in profile settings to Dutch and the language to English

3. Set the date to either 5 December or 27 April

4. Boot into Tomodachi Life and go to the Supermarket

**Dump file:**
[crash_dump_00000004.dmp](https://github.com/LumaTeam/Luma3DS/files/15137656/crash_dump_00000004.dmp)

**Comment by PabloMK7** [comment]
Hello, this is probably caused by a corrupted SD and it's not related to a Luma3DS bug. Keep in mind that some games will need locale emulation to work properly. In any case, to get further assistance please ask in a homebrew forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh
