### ISSUE TITLE
Pokemon rumble blast unplayable

### ISSUE THREAD

**Issue by Masono03** [LumaTeam/Luma3DS#2024]
**Explanation of the issue:**
Everytime i try to start Pokemon Rumble blast it crashes. tried to reinstall the game multiple times or other things but doesnt work.

**Steps to reproduce:**

1. have rumble blast as digital version

2. try starting it

**Dump file:**
[crash_dump_00000015.dmp](https://github.com/LumaTeam/Luma3DS/files/15223993/crash_dump_00000015.dmp)

**Comment by takeshineale128** [comment]
i'm in uk its called super pokemon rumble doesn't crash for me, both digital and cart copys both work for me

**Comment by Masono03** [comment]
ah that explains why i couldnt find a european version of it if its diffrent name ima try getting that one instead then
tho its the only US game to ever do that

**Comment by PabloMK7** [comment]
Hello, any kind of piracy is not allowed here.
