### ISSUE TITLE
System clock 

### ISSUE THREAD

**Issue by ZedG95** [LumaTeam/Luma3DS#2029]
Whenever I go to New 3DS Menu and go to set the clock rate to 804mhz and save the settings, it never stays.  When I boot the system back up, it's at the base clock again.  Is there a fix I can do to set the clock at 804mhz upon system startup?  Thanks.

**Comment by PabloMK7** [comment]
Hello, this is intended. Enable the setting from the luma configuration menu. (Press select on boot)

**Comment by profi200** [comment]
To give a little more context the setting changes depending on what is currently active. For example HOME menu will set 804 MHz clock. If you boot a game the setting may flip back.
