### ISSUE TITLE
Finalizing setup from plailect (double confirm is it got anything missing)

### ISSUE THREAD

**Issue by jasontwk85** [LumaTeam/Luma3DS#203]
![20160908_032116](https://cloud.githubusercontent.com/assets/22019893/18326241/6900f81e-7577-11e6-9eea-48a84aff4f19.jpg)

Sorry if i am asking wrong thing or impolite.
1. I wanna ask is it i.m missing something about luma3ds?maybe app or tool? After i finish step from plailect.. cos this is the only thing i got..
1. And i wanna ask how to use rom such as .3ds or .cia? Or can send me a link so i can follow and learn.?

Thanks,
And sorry for inconvenience cause.

**Comment by ihaveamac** [comment]
this is not a Luma3DS issue. you asked this already at https://github.com/Plailect/Guide/issues/477.

the icon that is selected is a Luma3DS updater, unrelated to the actual custom firmware.

**Comment by jasontwk85** [comment]
Sorry bro..i dunno where should i ask to double confirm..
And sorry for being impolite😇
