### ISSUE TITLE
3ds games problem id 15

### ISSUE THREAD

**Issue by alcacsito** [LumaTeam/Luma3DS#2030]
Hello, I would like to receive advice. I have an error when starting my games from my 3ds, but not in all of them, when I try to start them, the following appears.

error: generic

process id: 15

process name: menu

process id: 0004003000009802

address: 0x00229802

error code: 0xd9605c05

Does anyone know how to solve it?

It only happens with games like smahs mario maker mario 3D LAND or luigis mansion 1

However, games like Mariokart 7, Luigis Mansion 2 or Pokemon Y still work without problems.

Thank you in advance for your help

**Comment by PabloMK7** [comment]
Hello, this is a page dedicated to track Luma3DS bugs and is not suitable for giving assistance. Please ask in a homebrew related forum or in the Nintendo Homebrew discord server: https://discord.gg/C29hYvh
