### ISSUE TITLE
An exception occurred. ARM11 - data abort - Translation-section 

### ISSUE THREAD

**Issue by krlv7y** [LumaTeam/Luma3DS#2032]
Explanation of the issue:
Ive had this for almost two years, ever since i modded the DS, basically, it only happens when i play miitopia. Whenever i play for more than like 10 seconds it just randomly crashes. It did that back then too just not as often, and now i cant even continue playing at all.  Also i have miitopia as a cart, not digital, maybe that helps. I tried to change the region of the cart to mine but that did not fix anything. Any type of help is appreciated! Thank you
Heres the dump 

crash_dump_00000008.dmp](https://github.com/LumaTeam/Luma3DS/files/15345651/crash_dump_00000008.dmp)

New 2DS XL (europe)

11.17.0-50E

Boot9Strap

v13.1.1

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

**Comment by Luke1002** [comment]
> Explanation of the issue: Ive had this for almost two years, ever since i modded the DS, basically, it only happens when i play miitopia. Whenever i play for more than like 10 seconds it just randomly crashes. It did that back then too just not as often, and now i cant even continue playing at all. Also i have miitopia as a cart, not digital, maybe that helps. I tried to change the region of the cart to mine but that did not fix anything. Any type of help is appreciated! Thank you Heres the dump
> 
> crash_dump_00000008.dmp](https://github.com/LumaTeam/Luma3DS/files/15345651/crash_dump_00000008.dmp)
> 
> New 2DS XL (europe)
> 
> 11.17.0-50E
> 
> Boot9Strap
> 
> v13.1.1
> 
> Default EmuNAND: ( )
> 
> Screen brightness: ( )
> 
> Splash: ( )
> 
> Splash duration: ( )
> 
> PIN lock: ( )
> 
> New 3DS CPU: ( )
> 
> Autoboot EmuNAND: ( )
> 
> Use EmuNAND FIRM if booting with R: ( )
> 
> Enable loading external FIRMs and modules: ( )
> 
> Enable game patching: (x )
> 
> Show NAND or user string in System Settings: ( )
> 
> Show GBA boot screen in patched AGB_FIRM: ( )
> 
> Set developer UNITINFO: ( )
> 
> Disable Arm11 exception handlers: ( )
> 
> Enable Rosalina on SAFE_FIRM: ( )

I have the same error, can you please write what you did to solve it?

**Comment by urherenow** [comment]
You're commenting on a closed issue. Reading the original post, this person was doing it wrong to begin with. The region changing is for the CONSOLE, not the cart. Whatever language you want the cart to be in, MUST already be on the cart. If a game is Japanese and your system is US, your region.txt for that game would say JPN, JP (or whatever the proper codes are nowadays). Or if the cart actually has english on it, you could use JPN, EN. 

There is an app for doing this properly for you. Been so long, I don't remember off the top of my head. Just google it.
