### ISSUE TITLE
[Feature Request] Better brightness control

### ISSUE THREAD

**Issue by TrixieUA** [LumaTeam/Luma3DS#2036]
Allow lower brightness and more maximum brightness(aka 6 level brightness).

**Comment by profi200** [comment]
Lower brightness is not really an issue but higher increases the risk of hardware damage. We don't know the exact ratings for the backlights and power supplies they use. They already limit the current in the backlight curves.

If you plug in the charger and set the brightness to maximum in HOME menu you will already get a boosted brightness if the current limit allows it. This is something not very well known.

**Comment by TuxSH** [comment]
Current implementation uses gsp which clamps the brightness values and I do not ever intend to add an option to go outside the calibration.
