### ISSUE TITLE
(Question/Request) Luma Handled Streetpass

### ISSUE THREAD

**Issue by RinMaru** [LumaTeam/Luma3DS#2039]
Only so many games can have streetpass active. Would it be possible in the future to activate more and have them handled via Luma when the 3DS bank is full or was there a technical reason why only so ,any could be used?

**Comment by PabloMK7** [comment]
Hello, this kind of features are outside the scope of the CFW, as they can be implemented using module-specific patches.

**Comment by RinMaru** [comment]
> Hello, this kind of features are outside the scope of the CFW, as they can be implemented using module-specific patches.

Is it really feasible for a module patch to make it possible? Or is there a reason the limit is 12?

**Comment by urherenow** [comment]
GitHub isn’t the place for discussions like this, especially when the topic has been closed as not planned. Try a forum or discord. Whether or not the limitation is arbitrary or because of limited resources in hardware, it’s not Luma3ds’ problem.
