### ISSUE TITLE
Power on the 3DS and it automatically opens Luma´s menu. When I press save it gets stuck there.

### ISSUE THREAD

**Issue by notssosa** [LumaTeam/Luma3DS#2042]
**System model: Old 3DS**

[New 2DS XL, New 3DS XL, New 3DS, Old 2DS, Old 3DS XL, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):11.17.0**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS): Power on button**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:13.0**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (x)

Splash: (x)

Splash duration: ( )

PIN lock: (x)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

I get stuck on the Luma´s screen when I power on my 3DS

**Steps to reproduce:**

1. Power on

2.

**Dump file:**

**Comment by PabloMK7** [comment]
Hello, your SD may be corrupted or write protected, preventing luma from writing to it. Make sure it is not write protected and if it isn't, copy everything to your PC, format the SD to FAT32 and then copy everything back. If that still doesn't work please ask for help in a homebrew related forum or in the Nintendo homebrew discord server.
