### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by Golem642** [LumaTeam/Luma3DS#2044]
I cloned this git repo, but when i try to make there's apparently some errors into main.c

![image](https://github.com/LumaTeam/Luma3DS/assets/65229557/e177fe2d-3646-4385-8f36-3f2221da1679)

I have everything installed (git, libctru, makerom and firmtool, althought this doesn't seem to come from any of these), is this normal/ am i missing something or am i not the only one having this problem ?

Thanks

**Comment by PabloMK7** [comment]
Hello, you are using an outdated libctru. Make sure you are using the latest version provided by devkitpro.

**Comment by Golem642** [comment]
Sorry, I'm new to pacman. I thought running `pacman -Syu` would update everything but it seems I was mistaken and after running the command again with libctru at the end, it fixed it. Thanks
