### ISSUE TITLE
Stargate 3DS does not boot into homebrew in DS mode

### ISSUE THREAD

**Issue by lifehackerhansol** [LumaTeam/Luma3DS#2046]
**System model:** New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** 11.16.0-42K

**Entrypoint (How/what you're using to boot Luma3DS):**

boot9strap

**Luma3DS version:** 13.1.1

**Luma3DS configuration/options:**

Default EmuNAND: ()

Screen brightness: (4)

Splash: (Off)

Splash duration: (N/A)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ()

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

The Stargate 3DS is a DS/3DS combination flash cartridge. In 3DS configuration, it behaves similarly to a Sky3DS+, where button scrolling loads an encrypted CXI. In DS configuration, it behaves as any normal DS flash cartridge, showing a modified game that launches a homebrew on the cartridge's SD card. The issue is _specifically_ in the DS configuration; the 3DS configuration works as expected (and is also useless if Luma3DS is installed anyway.)

When booting with Luma3DS, instead of loading homebrew, instead it launches the spoofed game (which is broken, because Stargate firmware only contains a snippet of the SRL, just enough to load the injected overlay to launch the homebrew application.) This makes it impossible to use the Stargate for its intended purpose in DS mode.

When loading NATIVE_FIRM directly from the exefs (see https://github.com/hacks-guide/Guide_3DS/blob/master/gm9_scripts/safety_test.gm9), it behaves as expected.

**Steps to reproduce:**

0. Have a Stargate 3DS
1. Boot Luma3DS with default configuration
2. Press both buttons on the Stargate together until the LED flashes, after a few seconds the spoofed SRL banner will appear
3. Launch the cartridge, and observe that the user's homebrew application (which may be Stargate's provided kernel files or otherwise) does not show up

**Dump file:**

N/A (no crashes)

**Comment by team-orangeBlue** [comment]
The offending function appears to be `patchTwlWhitelistChecks`. When compiling with line 627 of arm9/source/firm.c commented out, stargate loads fine instead of the broken Alex Rider game.

So what that function does wrong - I don't know. It is what it is.

Tested on an N3DS. 
Without whitelist patching:
![image](https://github.com/user-attachments/assets/04339c22-1d00-4bee-aa79-b7ce1e38ff1d)
and with:
![Clipboarder 2024 07 23](https://github.com/user-attachments/assets/ab1c3e5d-dbbe-43d9-ac3d-b36d13f94443)

**Comment by Masamune3210** [comment]
![image](https://github.com/user-attachments/assets/98a55e75-26fe-4335-b36d-fdaeaf0ad877)
All this is doing, as far as I can tell, is disabling the checks. The system, by default, has a whitelist of carts it will allow to be launched as a form of flashcard blocking.

**Comment by profi200** [comment]
Mentioning it here too. The patch Luma applies will make Process9 do less card reads since the whitelist checks are skipped. This card however expects commands in a fixed order as unmodified firmwares would send them. This causes the flashcard to never get out of the game spoofing mode. Still weird that it manages to boot at all with a fraction of the original ROM.

Anyway, not a Luma issue but just a shitty implementation in this flashcard.

**Comment by PabloMK7** [comment]
A workaround for this would be to add an entry in config.ini to disable the whitelist patch. Or change the patch so that it is performed but ignore the result.

**Comment by TuxSH** [comment]
> A workaround for this would be to add an entry in config.ini to disable the whitelist patch. Or change the patch so that it is performed but ignore the result.

Workarounds like these are not desirable because I will eventually reimplement TWL_FIRM process9 without the checks. The solution is either to modify the code for your own use or use another flashcart.

**Comment by metroid-maniac** [comment]
>  The patch Luma applies will make Process9 do less card reads since the whitelist checks are skipped. This card however expects commands in a fixed order as unmodified firmwares would send them. This causes the flashcard to never get out of the game spoofing mode. 

Is it practical to still do the card reads needed, but skip the checks performed on the fetched data?

**Comment by profi200** [comment]
It would require much more patching. I don't think this is going to happen because Luma would be catering specifically for a buggy flashcard. Not a good idea considering how out of control Nintendos legal department is lately.

**Comment by metroid-maniac** [comment]
I'd like to fix the patch in this way but if it's clear the PR wouldn't be accepted due to legal concerns then I'll settle for commenting the patch out locally. Thanks.

**Comment by TuxSH** [comment]
I don't think I would like to accept such a PR; considering Startgate3DS is very niche you should do this change locally.
