### ISSUE TITLE
BUG 3DS wifi connectivity died

### ISSUE THREAD

**Issue by AndryCola** [LumaTeam/Luma3DS#2049]
Hi,

I'm on old 3DS last version of the system 11.17.0-50E and last release of luma3DS.
I can't understand why before installing luma and godmod9 my 3ds was able to use wifi connection and now i can't (like universal updater, update console or simply browser).
Anythings that need internet can't connect, but my 3ds is connected to the router, in fact on left top i see the "internet" icon blue.

I also insert in the root of SD the folder config.

I tried without SD Card and the connectivity works well.
PS: 2 my friends internet connection died with my same case too

**Comment by RinMaru** [comment]
this happened to me today out of the blue i had to force the conection to slot 1 otherwise wifi would be detected as dropping on and off

**Comment by AndryCola** [comment]
> this happened to me today out of the blue i had to force the conection to slot 1 otherwise wifi would be detected as dropping on and off

yes, i have tried and it has worked. i thought the problem was my wifi mesh band, but without SD Card the connection works properly. 
With the sd card, the only connection that works is the first. 
at this point i don't know if could be a sort of bug from luma.

**Comment by RinMaru** [comment]
> yes, i have tried and it has worked. i thought the problem was my wifi mesh band, but without SD Card the connection works properly. With the sd card, the only connection that works is the first. at this point i don't know if could be a sort of bug from luma.

im not sure either i thought maybe it was nimbus or something but idk its weird it happened and just kinda stopped

**Comment by AndryCola** [comment]
> im not sure either i thought maybe it was nimbus or something but idk its weird it happened and just kinda stopped
> 
> 
it could be, but i had nimbus pretendo app installed, but never opened, so in my case i don't think so

**Comment by WuffyTopside** [comment]
I'm having the same issue. I'm on 11.17.0-50U, and even forcing the connection doesn't work for me.

Edit: Solved it on my end. If your SD card is over 32GB, format it with a cluster size of 32k. The info at 3ds hacks.guide is confusingly written.

**Comment by AndryCola** [comment]
> I'm having the same issue. I'm on 11.17.0-50U, and even forcing the connection doesn't work for me.
> 
> 
> 
> Edit: Solved it on my end. If your SD card is over 32GB, format it with a cluster size of 32k. The info at 3ds hacks.guide is confusingly written.

you don't have to force connection by rosalina menu, but you should go to settings and delete all internet connections, the set your wifi to the first one and restart the console. 
i resolved in this way

**Comment by WuffyTopside** [comment]
I was wrong about the format fixing things. 32k was the wrong cluster size after all for a 128GB SD card. 64k seems to be working, so I'm assuming I was wrong about the initial format's cluster size. Will provide updates after testing.

**Comment by WuffyTopside** [comment]
Turns out I was wrong about the SD cluster size. I'm having luck with a static IP and DNS set to 8.8.8.8, but I had to switch to a guest network that is set to only use WPA-PSK and WPA2-PSK. So far, no dropped connections. Further testing is required.

**Comment by SkimMilkFAST** [comment]
I have the same weird issue on both of my hacked New 3DS XL. The internet connection was OK until I updated to the 13.1.2 Version of Luma3DS. Have tried all of methods abovementioned or even use unsafe WEP connection without password, the connection still very lagged and intermittent.

**Comment by SkimMilkFAST** [comment]
> I have the same weird issue on both of my hacked New 3DS XL. The internet connection was OK until I updated to the 13.1.2 Version of Luma3DS. Have tried all of methods abovementioned or even use unsafe WEP connection without password, the connection still very lagged and intermittent.

I just solved this problem (temporally, perhaps) by turning the Connection Type of my 2.4G WIFI Router from WPA2 to WPA/WPA2. And the issue has gone since then. No matter how it worths a try.

**Comment by byeoon** [comment]
I am extremely confused on this because I'm also having this issue. 

It started a few days ago and my Internet sign goes from Internet to Enabled, approximately every 15 seconds or whenever I open a game. It had happened a few weeks after I changed my SD card to 64GB, so I doubt it would happen because of that, but just in case I switched out the card and the connect/disconnect was still happening.

I even switched networks and everything, but to no avail the issue was still there.


Something to note is that this started happening right when I opened Nimbus.

**Comment by WuffyTopside** [comment]
I had gotten everything to work after an update to Luma a while back, but v13.2.1 broke it again. Could there be a regression somewhere?

**Comment by byeoon** [comment]
> I had gotten everything to work after an update to Luma a while back, but v13.2.1 broke it again. Could there be a regression somewhere?

That's also a possibility, because I remember updating before this started to happen.  My original post is really disorganized so I'll re-sort it here.

->update to newest luma (~1.5-2 weeks before the bug)
->change to 64gb sd card (~1 week before the bug)
->open nimbus and switch to pretendo (few hours before the bug happened)
->switch back to nintendo because it showed me as offline (probably when bug started)
->bug started to occurr

**Comment by WuffyTopside** [comment]
Not sure if this is relevant, but GParted reports that there's no partition table on my SD card. I'll try and backup my card and set up a GPT partition table before restoring the files. If that fails, MBR is my next step. It's a 128GB SD, so I'll definitely be following the recommendation to use a 64KiB cluster size for the FAT32 formatting step.

**Comment by urherenow** [comment]
AFAIK, 3DS doesn't work with only GPT. It MUST have an MBR. Doesn't hurt to at least Google before turning GitHub into a forum. That isn't what GitHub is for.

**Comment by WuffyTopside** [comment]
GPT and MBR are both types of partition tables. MBR is useful for legacy devices and has a lower maximum file size, whereas GPT is more modern with much higher maximum file sizes supported. It doesn't hurt to Google things before commenting.

And if you know of a forum dedicated to Luma, please provide a link. I'll happily move my documentation of attempting to find a solution there.

**Comment by urherenow** [comment]
Lol... when trying to be a smartass makes you look like a dumbass. And I'm talking about you. I don't need a lesson in GPT and MBR, I was telling you flat out that GPT doesn't work on a 3DS.

GBAtemp has 3DS forums.

**Comment by PabloMK7** [comment]
Please use other places for offtopic discussion.
Closing as unrelated to luma.
