### ISSUE TITLE
Cannot "copy boot.firm and boot.3dsx from the Luma3DS .zip to the root of [my] SD card"

### ISSUE THREAD

**Issue by holty111** [LumaTeam/Luma3DS#2050]
Just like the title says i cannot copy boot.firm and boot.3dsx from the Luma3DS .zip to the root of my SD card. If i copy and paste the files required they don't move anywhere on my files, if i extract the folder the files i need inside are erased. I can't find any solutions to my problem so i thought i would ask help from the people here.

**Comment by PabloMK7** [comment]
Hello, this website is meant to track Luma3DS issues, if you want to get assistance you can ask in the Nintendo homebrew server: https://discord.gg/C29hYvh
