### ISSUE TITLE
crashes at startup

### ISSUE THREAD

**Issue by ExtraBytez** [LumaTeam/Luma3DS#2052]
it says process loader (00000000) am i bricked?

**Comment by ExtraBytez** [comment]
doing  ctrtransfer

**Comment by ExtraBytez** [comment]
that made it worse

**Comment by ExtraBytez** [comment]
nvm ised the n3ds ctr file instead of the o3ds one so closeing as this should work

**Comment by impeeza** [comment]
RTM  :P

**Comment by ExtraBytez** [comment]
> RTM  :P

RTM?
