### ISSUE TITLE
[Feature request] Add a turbo function to the buttons.

### ISSUE THREAD

**Issue by joaoviss** [LumaTeam/Luma3DS#2053]
Hello, I am physically disabled and have motor coordination problems that prevent me from pressing a button quickly. That's why I always use the turbo function on third-party controllers. Since not every controller works well with all games, could we have the option to put the turbo function on each button individually on the 3DS?

**Comment by PabloMK7** [comment]
Hello, such a feature is outside the scope of Luma3DS. Instead take a look at rehid which has turbo functionality as far as I know.

**Comment by joaoviss** [comment]
Thanks. I was unsure, seeing that It handles input redirection and such. But thanks for the quick response.
