### ISSUE TITLE
[Feature Request] Format Screenshots to .jpg 

### ISSUE THREAD

**Issue by Echo-Beast** [LumaTeam/Luma3DS#2055]
Currently the format is set to .bmp, but with .jpg the screenshots could be saved to Nintendo 3DS Camera so you could edit them on 3DS or just have your experiences in game to be viewed whenever.

**Comment by PabloMK7** [comment]
Hello, encoding in jpg would require a lot of resources, that's why a simple format such as BMP was chosen.

**Comment by profi200** [comment]
Rosalina is already pretty RAM constrained and adding a JPEG encoder would likely push RAM usage to the limit or beyond. Besides that JPEG is not lossless so your screenshots would not look as good as they should.
