### ISSUE TITLE
Clone Event not working. 'Could not find data' error message.

### ISSUE THREAD

**Issue by StephCollis** [LumaTeam/Luma3DS#2057]
**System model:**

[New 2DS XL, New 3DS XL, New 3DS, Old 2DS, Old 3DS XL, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**
I am unable to clone any of my events today. This is a new issue that has happened since last week. When attempting to clone an event, I keep getting a red banner at the bottom saying “Could not find data” (see attached screenshot).
![Screenshot 2024-07-15 at 12 50 34 PM](https://github.com/user-attachments/assets/7ad1b70a-4f2a-41e2-90c9-212667fbeaf7)

**Steps to reproduce:**

1. Manage Event
2. Go to 'More'
3. Click 'Clone Event'
4. Red banner at bottom of page appears

**Dump file:**

![Screenshot 2024-07-15 at 12 50 34 PM](https://github.com/user-attachments/assets/4fe75bc1-fa78-448b-ade5-7afe20533044)

**Comment by PabloMK7** [comment]
Hello, this is Luma3DS, a custom firmware for the Nintendo 3DS console. You have created this issue in a totally unrelated repository. x)
