### ISSUE TITLE
An exeception occurred  Arm 11 (core 0)  prefecth abort (svcbreak) Debug event  Menu (0004003000008F02)

### ISSUE THREAD

**Issue by Its-Andy9** [LumaTeam/Luma3DS#2059]
New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.17.0-50U 

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v13.1.2

**Luma3DS configuration/options:**

Screen brightness: (4)

Splash: ( Off)

PIN lock: ( Off)

New 3DS CPU: (Off )

Hbmenu autoboot: (Off)

Enable loading external FIRMs and modules: (On)

Enable game patching: (On)

Show NAND or user string in System Settings: (On )

Show GBA boot screen in patched AGB_FIRM: (Off )

Redirect app. syscore threads to core2: (Off)

--

**Explanation of the issue:**

Sometimes randomly after a few times off opening and reopening games and apps including the multitask apps: friends list, game notes, internet browser, miiverse and notifications,

Will crash while attempting to load the home menu.

**Steps to reproduce:**

1. Open an app or game

2. Press the Home button ( It may take several presses or prolonged use of the app to reproduce)

**Dump file (if applicable):**
[crash_dump_00000010.dmp](https://github.com/user-attachments/files/16275318/crash_dump_00000010.dmp)

**Comment by PabloMK7** [comment]
Hello, this is a place for reporting luma bugs, and not for assistance. Please ask in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh
