### ISSUE TITLE
An exception occurred: Arm11 (core 1) when trying to enable "Enable loading external FIRMs and modules" and "Enable game patching" at the same time

### ISSUE THREAD

**Issue by GltichyB** [LumaTeam/Luma3DS#2061]
System model: New Nintendo 3DS XL

SysNAND Version: 11.17.0-50U SysNAND

Entrypoint: Boot9Strap

Luma3DS version: v13.1.2 stable

Screen Brightness (4)

Splash (Off)

PIN lock: (Off)

New 3DS CPU (Off)

Hbmenu autoboot (Off)

Enable loading external FIRMs and modules (x)

Enable game patching (x)

Redirect app. syscore threads to core2 ()

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Explanation:

I need to have enable "Enable loading external FIRMs and modules" and "Enable game patching" in the Luma3DS config menu at the same time so that I can use Pretendo, but it gives out an error when I try to do so when I try rebooting my 3DS.  This happens with and without the micro sd card. When I disable "Enable loading external FIRMs and modules" or "Enable game patching", my 3DS reboots normal, but I want to use both of them at the same time.

The error:

An exception occured

Processor: Arm11 (core 1)
Exception type: data abort
Fault status: Translation - Section
Current process: hid (0004013000001D02)

Steps to reproduce:
1. Enable both "Enable loading external FIRMs and modules" and "Enable game patching" at the same time in the Luma3DS config menu

**Comment by PabloMK7** [comment]
Hello, you probably have a broken patch installed on your luma folder. Try to delete the patches from the luma folder in your SD card. For further assistance please ask in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh
