### ISSUE TITLE
[Feature Request] Add function to turn on and off Super-stable 3D in Rosalina 

### ISSUE THREAD

**Issue by KendrickLamar2003** [LumaTeam/Luma3DS#2062]
In certain conditions, the tracking may not be accurate , thereby making the 3D look janky. If there was a way to disable it on-demand instead of having to go into the settings, that would be very cool.

**Comment by KendrickLamar2003** [comment]
![image](https://github.com/user-attachments/assets/b4407f31-6603-45de-8b61-c4b7e7c51344)

**Comment by TuxSH** [comment]
No need to bump; I'm working on this

**Comment by KendrickLamar2003** [comment]
Yoooo, thank you so much @TuxSH
