### ISSUE TITLE
Can't run both M&L Remakes

### ISSUE THREAD

**Issue by StarWizard9** [LumaTeam/Luma3DS#2063]
**System model:**
Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**
10.3.0-28U

**Entrypoint (How/what you're using to boot Luma3DS):**
SoundHax

**Luma3DS version:**
v13.1.2

**Luma3DS configuration/options:**

Default EmuNAND: ( )
Don't Have

Screen brightness: (4)

Splash: (Off)

Splash duration: ( )
Don't Have

PIN lock: (Off)

New 3DS CPU: ( )
Don't Have

Hbmenu autoboot: (Off)

--

Autoboot EmuNAND: ( )
Don't Have

Enable loading external FIRMs and modules: (X)

Enable game patching: ( )

Redirect app. syscore threads to core2: ( )
Don't have

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

**Explanation of the issue:**
Whenever I try to open either of the Mario and Luigi remakes, as the Nintendo 3DS loading screen shows up, it instantly sends me to  the "An exception occurred" screen and I have tried everything I searched for, which was trying to install the games via FBI as CIAs files and via the HShop, importing the seeds via FBI, manually importing the seeds and deleting the tickets for both remakes before giving up and grabbing the crash dump to report here.

**Steps to reproduce:**

1. Install either Mario & Luigi : Superstar Saga + Bowser's Minion or Mario and Luigi : Bowser's Inside Story + Bowser Jr's Journey onto 3DS either via FBI or HShop.

2. Open the game.

**Dump file (if applicable):**

[Crash Dump.zip](https://github.com/user-attachments/files/16398436/Crash.Dump.zip)

**Comment by PabloMK7** [comment]
Hello, we cannot give assistance with piracy, sorry.
