### ISSUE TITLE
Sometimes when screenshots are taken in they are duped

### ISSUE THREAD

**Issue by Trickiy** [LumaTeam/Luma3DS#2068]
In the current version of luma sometimes when I take a screenshot the bottom and top screens will be the same:
![image](https://github.com/user-attachments/assets/2d654b6c-a68f-454d-9f38-5f1ad1c35787)
![image](https://github.com/user-attachments/assets/47765f1d-e5ea-4ab6-97f2-527d36ebca14)
in the game editor the select button is used to swap bottom and top screens. 

Step 1 find a program that is suseptible Thextech works
Step 2 open luma and take a screen shot not 100% garenteed

**Comment by TuxSH** [comment]
Does this happen if you remap luma menu combo to something else that doesn't involve the SELECT button?

**Comment by Trickiy** [comment]
No it dose not happen when I change my button combo, and this is specific to when a game or program has screen swap functionality.

**Comment by TuxSH** [comment]
I've thought about it a bit, but I think I'll close the issue -- what happens is that the game may react to the Rosalina combo. This is very hard to fix properly (requires reimplementing large parts of the system). Workaround is to change the menu combo as mentioned earlier.
