### ISSUE TITLE
hi when i play a game it crashes and gives error code arm11 (core 0) pls fix i put all the error dumps right here. new 3ds xl.And it does the same thing when I exit out of any app sometimes 

### ISSUE THREAD

**Issue by gio46464** [LumaTeam/Luma3DS#2069]
[crash_dump_00000006.dmp](https://github.com/user-attachments/files/16656102/crash_dump_00000006.dmp)
[crash_dump_00000005.dmp](https://github.com/user-attachments/files/16656103/crash_dump_00000005.dmp)
[crash_dump_00000015.dmp](https://github.com/user
[crash_dump_00000009.dmp](https://github.com/user
[crash_dump_00000004.dmp](https://github.com/user-attachments/files/16656123/crash_dump_00000004.dmp)
[crash_dump_00000003.dmp](https://github.com/user
[crash_dump_00000002.dmp](https://github.com/user-attachments/files/16656129/crash_dump_00000002.dmp)
-attachments/files/16656127/crash_dump_00000003.dmp)

[crash_dump_00000000.dmp](https://github.com/user-attachments/files/16656121/crash_dump_00000000.dmp)

[crash_dump_00000001.dmp](https://github.com/user-attachments/files/16656119/crash_dump_00000001.dmp)

[crash_dump_00000008.dmp](https://github.com/user
[crash_dump_00000007.dmp](https://github.com/user-attachments/files/16656118/crash_dump_00000007.dmp)
-attachments/files/16656117/crash_dump_00000008.dmp)
-attachments/files/16656116/crash_dump_00000009.dmp)
-attachments/files/16656104/crash_dump_00000015.dmp)
[crash_dump_00000013.dmp](https://github.com/user-attachments/files/16656114/crash_dump_00000013.dmp)

[crash_dump_00000014.dmp](https://github.com/user-attachments/files/16656105/crash_dump_00000014.dmp)
[crash_dump_00000012.dmp](https://github.com/user
[crash_dump_00000010.dmp](https://github.com/user-attachments/files/16656111/crash_dump_00000010.dmp)
-attachments/files/16656106/crash_dump_00000012.dmp)
[crash_dump_00000011.dmp](https://github.com/user-attachments/files/16656109/crash_dump_00000011.dmp)

**Comment by PabloMK7** [comment]
Hello, this place is for reporting luma 3ds bugs and not for general assistance. Your SD may be corrupted and that's why you get all those issues. Please ask for help in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh

**Comment by gio46464** [comment]
It does the same thing with a new sd card
