### ISSUE TITLE
Hide new3ds config options on old3ds

### ISSUE THREAD

**Issue by henke37** [LumaTeam/Luma3DS#207]
Detect if the console is a new or old 3ds and hide the configuration options exclusive for the new 3ds if running on an old 3ds.

Or at least disable the option.

**Comment by Masamune3210** [comment]
AFAIK, there is no easy way to know what system you are running on when running arm9 payloads due to the firmware being not launched yet

**Comment by TuxSH** [comment]
@deadair3210 There is, actually.

**Comment by poutros** [comment]
Doesn't corbenik do it?

**Comment by AuroraWright** [comment]
Done.
