### ISSUE TITLE
[Feature Request] option to disable sleep mode switch on 2ds / disable sleepmode by closing lid 3ds

### ISSUE THREAD

**Issue by ExtraBytez** [LumaTeam/Luma3DS#2070]
I have a 2ds that has a broken sleep mode switch that keeps toggle ing on and it would be nice if as a temporary fix i could disable that

**Comment by urherenow** [comment]
Turn it off. Soak a Q-tip in IPA and rub it along the switch's groove, and manually toggle the switch on and off real fast. Maybe 20-30 times. Apply more IPA if it dries too quickly. When you're done, wait a good 5-10 minutes for the IPA to evaporate, then turn on your console and try the switch out. You may find that it works much better, if not like new.

**Comment by impeeza** [comment]
Sorry is a hardware interruption, no too much to do, you will need to fix the button.

**Comment by ExtraBytez** [comment]
> Sorry is a hardware interruption, no too much to do, you will need to fix the button.

bummer

**Comment by ExtraBytez** [comment]
> Turn it off. Soak a Q-tip in IPA and rub it along the switch's groove, and manually toggle the switch on and off real fast. Maybe 20-30 times. Apply more IPA if it dries too quickly. When you're done, wait a good 5-10 minutes for the IPA to evaporate, then turn on your console and try the switch out. You may find that it works much better, if not like new.

can i do this isopropyl alcohol?

**Comment by urherenow** [comment]
That's what IPA is...

**Comment by ExtraBytez** [comment]
> That's what IPA is...

😅
