### ISSUE TITLE
After playing New Super Mario Bros 2, every homebrew title that i open will freeze on the start

### ISSUE THREAD

**Issue by Ghegghi** [LumaTeam/Luma3DS#2074]
when I play new super mario bros 2 after I close it, if I try to open a homebrew app it gets stuck on a black screen and i need to force the 3ds to shut down by holding down the power button.

https://github.com/user-attachments/assets/30dc8574-12b5-4abc-ac49-28d5ab8e04c3

System model:

[New 3DS XL]

[11.17.0-50E SysNAND]

Entrypoint (How/what you're using to boot Luma3DS):

[Boot9Strap]

Luma3DS version:

[v13.1.2 stable]

Luma3DS configuration/options:

Screen brightness: ( 4 )

Splash: ( None )

Splash duration: ( None )

PIN lock: ( None )

New 3DS CPU: ( Default )

Hbmenu autoboot: ( )

--

Enable loading external FIRMs and modules: (  )

Enable game patching: (  )

Redirect app. syscore threads to core2: ( )

Show NAND or user string in System Settings: ( X )

Show GBA boot screen in patched AGB_FIRM: ( )

**Comment by TuxSH** [comment]
After some investigation, NSMB2 seems to set GPU in an unexpected state homebrew doesn't support. A workaround for this is to open and then close any other official application.

Cc @fincs .

**Comment by Searinox** [comment]
This issue was reported before and is known to happen with both NSMB2 and Castlevania Mirror of Fate. There is an issue filed for this: https://github.com/LumaTeam/Luma3DS/issues/1559
Would be nice if this was fixed on the Luma side as Nintendo will never fix it now.

**Comment by TuxSH** [comment]
Ideally this is up to libctru to fix it (and homebrew (especially hbmenu)) to be recompiled with it. I don't have much expertise with 3DS GPU programming so it's up to fincs to investigate it, I think.

**Comment by TuxSH** [comment]
Not a luma issue, now fixed by: https://github.com/devkitPro/libctru/pull/554
