### ISSUE TITLE
crash_dump_00000000.dmp

### ISSUE THREAD

**Issue by unknowngirly** [LumaTeam/Luma3DS#2076]
**System model:** 
(Nintendo 3ds LL)
**SysNAND version (+emu/redNAND version if applicable):** 

[e.g. 11.17.0-50U SysNAND, 11.17.0-50E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**

[e.g. v13.1.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/988ec17ebfce513fc4589f7b12e0d6e3894ae542]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

Hbmenu autoboot: ( )

--

Autoboot EmuNAND: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Redirect app. syscore threads to core2: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

--

**Explanation of the issue:**

-> As soon I boot my 3ds it says:
An exception occurred
proccessor: Arm 11 (core 1)
Exception type: prefetch abort (svcBreak)
fault status: debug event
current process: loader (0000000000000000) 

press A to save crash dump 
press any other button to shutdown

stack dump: 

**Steps to reproduce:**

1.

2.

**Dump file (if applicable):**
 

[crash_dump_00000000.zip](https://github.com/user-attachments/files/16901176/crash_dump_00000000.zip)

**Comment by Ghegghi** [comment]
Do you have the latest luma version?

**Comment by PabloMK7** [comment]
Hello, this section is meant to track luma3ds bugs and not suited for general assistance. Please ask in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh
