### ISSUE TITLE
My console 3DS crashes when i try to open one specific game, yet, all the other games i have, do open as it should

### ISSUE THREAD

**Issue by gatitosmiaus** [LumaTeam/Luma3DS#2077]
[crash_dump_00000004.dmp](https://github.com/user-attachments/files/16912215/crash_dump_00000004.dmp)

This happened to me while trying to open my Animal Crossing New Leaf Luxury game for the first time. Any other apps do open without any problem.

**Comment by impeeza** [comment]
sorry this is not a support site, please go to discord or GBATemp,  probably is your game damaged reinstall it, change the cartdrige or get a new copy, so is not a Luma bug or issue.  please close this issue.
