### ISSUE TITLE
Autodetect out of game regions and switch automatically

### ISSUE THREAD

**Issue by henke37** [LumaTeam/Luma3DS#208]
It's a hassle manually setting up region and language overrides. Autodetect the correct region and make an educated guess for the language by default.

**Comment by Mrrraou** [comment]
don't you think it'd have been done if it was that easy or even possible

**Comment by Hartie95** [comment]
Are we able to access the smdh from the loader, if yes it could be possible to implement this.

**Comment by Mrrraou** [comment]
@hartmannaf It's not impossible, it's just complicated, annoying, and would result in dirty code and boot slowdowns, etc. There probably are cleaner ways I haven't thought about, though; I don't know.
