### ISSUE TITLE
Is this usable on Lime3DS or Citra PabloMK7?

### ISSUE THREAD

**Issue by WindowsNinetyTen** [LumaTeam/Luma3DS#2082]
I am just wondering whether this is compatible with those two emulators. If not, then why?

**Comment by Masamune3210** [comment]
Why would you want it to be? It's an emulator, it can already do everything you can do with Luma and more. Citra can't and likely will never work with Luma because it doesn't emulate the whole system, just what's needed to run the games.

**Comment by PabloMK7** [comment]
Hello, as stated, it's not
