### ISSUE TITLE
[Feature Request] 3DS Screen Recording

### ISSUE THREAD

**Issue by AimBlox10** [LumaTeam/Luma3DS#2083]
It would be cool if you could screen record your screen on the 3DS. You can record the upper-screen or bottom-screen or both. If it isn't possible on the old 3DS, make it that it'll be only possible on the New 3DS (If that's also possible).

**Comment by PabloMK7** [comment]
Hello! 
There are already tools available for screen recording. Integrating them to luma is not within the scope of luma3ds.
