### ISSUE TITLE
Rosalina system info incorrectly identifies my screen types as TN. I have can tell I have IPS screens

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#2089]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.17.0-50U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

V13.2.1 stable 

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

Hbmenu autoboot: ( )

--

Autoboot EmuNAND: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X)

Redirect app. syscore threads to core2: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

--

**Explanation of the issue:**
Under system info in the Rosalina menu, it identifies my top screen type and bottom screen type as TN. However, all I have to do to tell it's an IPS screen is look at it at a heavy angle, and I can still clearly see the image. Definitely an IPS screen on both screens, it is worth noting that I used a different system identification Homebrew app, which also says that my shell is red even though it's black. So it's likely that both the shell and the original screens were replaced and it somehow just never got told.

**Steps to reproduce:**

1. Have a system with replaced parts.

2.

**Dump file (if applicable):**

**Comment by TuxSH** [comment]
The IPS/TN status is sourced from the screen's controller itself. You do not have IPS screens.

>  which also says that my shell is red

RED is the codename for the New 3DS XL

**Comment by ghost** [comment]
https://github.com/user-attachments/assets/6611c5e6-8154-4339-ba64-11e3ce421a23

![Screen-Shot-2019-02-18-at-10 08 33-PM-1024x781](https://github.com/user-attachments/assets/776870ec-3c21-4eb7-b3c1-3680b507e970)

I rest my case

**Comment by TuxSH** [comment]
The video shows that your two screens are in fact, TN. IPS screens don't whiten from an angle like yours do, if you had an IPS top screen you should still been able to see the battery icon and "Internet" icon clearly with no discoloration.

Evidently (judging from 0:05 in your video), that is not the case.
