### ISSUE TITLE
3DS Luma menu error

### ISSUE THREAD

**Issue by akmur** [LumaTeam/Luma3DS#2090]
I'm opening this issue hoping somebody who is experienced with Luma might point me in the right direction.

Situation:

- got a 2nd hand 3ds already modded, with games
- the micro sd card in this 3ds is of awful quality and i wanted to use a good Lexar one or a good Sandisk one.
- I tried copying the content from the original micro sd to the lexar and to the sandisk
- when i boot the 3ds, it seems fine, all games are present
- when i boot a game, I get the 3ds luma error in the picture
- i already tried replacing the Luma files, no joy
- I also tried to dump the image of the sd to another sd, no joy
- I even tried to restart the modding process and create a new clean sd card to be used, still no joy

Below is th error I get:

![image](https://github.com/user-attachments/assets/13995fac-2247-490f-ad00-ae2ce573824d)

Now, this 3DS comes with some DS games installed in the internal card, and the only things I have not tried are:

- delete the DS games
- factory reset the 3ds 

If anybody has any idea I would be most grateful

**Comment by PabloMK7** [comment]
Hello! This is a page for tracking Luma3DS specific bugs, and not really suited for assistance. Instead try to re-post your question in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh

If your games got corrupted you can try to fix them from the eShop.
