### ISSUE TITLE
3DS crashing in Homebrew Launcher and in other apps

### ISSUE THREAD

**Issue by skittle0764** [LumaTeam/Luma3DS#2098]
**System model:** Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** Sys 11.17.0-50E

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** v13.2.1

[e.g. v13.2.1 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/988ec17ebfce513fc4589f7b12e0d6e3894ae542]

**Luma3DS configuration/options:**

Screen brightness: (3)

Splash: (OFF)

PIN lock: (OFF)

Hbmenu autoboot: (OFF)

--

Enable loading external FIRMs and modules: (enabled)

Enable game patching: (enabled)

Show NAND or user string in System Settings: (enabled)

Show GBA boot screen in patched AGB_FIRM: ( )

--

**Explanation of the issue:**

My 3DS XL crashes when i try to open the Homebrew Launcher, and many other games, such as Mario Kart 7 and Mario Party: Top 100 (it started when i installed Mario Party: Top 100 as CIA)
I also needed to reinstall GodMode9 because it said it got corrupted randomly

**Steps to reproduce:**

1. Install Mario Party: Top 100 as CIA

2. Launch it (first error accurs)

3. Lauch Homebrew Launcher

4. ur f##### now :)

**Dump file (if applicable):**
[crash_dump_00000011.dmp](https://github.com/user-attachments/files/17923871/crash_dump_00000011.dmp)

**Comment by PabloMK7** [comment]
Hello, this place is for tracking Luma3DS bugs and not for general assistance. Please ask in a homebrew related forum or in the Nintendo homebrew discord server: https://discord.gg/C29hYvh
