### ISSUE TITLE
agb and twl patched not working in 0e9ff44 commit.

### ISSUE THREAD

**Issue by Lumince** [LumaTeam/Luma3DS#21]
They seemed to be fine in the stable build, but this new commit wont allow me to boot gba or dsi games

**Comment by Darky2k1** [comment]
@Biff627 - I'm guessing you are using bootctr, ctrbootmanager, or arm9select to launch Aureinand? If so you need to change the path of your arm9loaderhax.bin using the included file.

**Comment by Lumince** [comment]
I have it setup to boot from /a9lh/AuReinand.bin? Isnt that what it should be?
I even tried to use the patched agb and twl and it doesnt work :(

**Comment by AuroraWright** [comment]
Read the notes... you need to change the path inside the .bin.
