### ISSUE TITLE
A file name suggestion for 3ds Cart image and maybe ds too? (Was told to ask here)

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#2102]
this idea implies .3ci .nci to be filenames, and are non digital cart backups that can be mounted and played like a real one.

**Comment by ghost** [comment]
N is for ds 3 is for 3ds and ci stands for cart image in case needing info about it

**Comment by PabloMK7** [comment]
Hello, not sure who told you to ask here, but this is not the right place.

**Comment by profi200** [comment]
I think what was asked for here is a feature to load gamecard images directly as if you inserted an actual physical game and that's not going to happen. At least i don't expect any of the active maintainers to do this for obvious reasons.
