### ISSUE TITLE
freeze (new/old 11.0U dev a9lh )

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#211]
On dev branch, when svc patch is selected in luma menu, all .3dsx homebrew freezes when launched from the 1.1.x homebrew menu. Multiple hb entry points tested!

**Comment by Mrrraou** [comment]
ctrulib bug, recompile the latest homebrew menu with latest ctrulib

**Comment by ghost** [comment]
Prompt as ever Mr. Black Cat. And that did the trick, thanks. :  )

I'll attach an up-to-date 3ds-hb-menu should anybody have the same problem and find this issue.
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/465818/boot.zip)
