### ISSUE TITLE
New 3DS CPU feature whitelist

### ISSUE THREAD

**Issue by IngeniousDefault** [LumaTeam/Luma3DS#212]
I have a suggestion for a new feature. It would be great if there is a whitelist for the New 3DS CPU feature that just works like the "Enable region/language emulation" option. Some games crashes or have no benefits for the increased performance but always deactivating it when playing those games is really unconvenient.

**Comment by Margen67** [comment]
Duplicate of #209?

**Comment by RinMaru** [comment]
@Margen67 that issue has nothing to do with this.
@IngeniousDefault can't be done sadly many have asked for this feature and its been denied

**Comment by AuroraWright** [comment]
Can't be done with the current patch
