### ISSUE TITLE
question here

### ISSUE THREAD

**Issue by Darius20103104** [LumaTeam/Luma3DS#214]
does it even protect you when you use sysupdater? becuse im having probloms updating with settings?

**Comment by RinMaru** [comment]
you can update normally through system settings if you have a9lh. Luma3ds blocks firm partition updates.

**Comment by Darius20103104** [comment]
what if you use sysupdater? or safesysupdater?

**Comment by RinMaru** [comment]
you dont need sysupdater.

**Comment by Darius20103104** [comment]
the normal updater keeps on failing it shows an error everytime

**Comment by RinMaru** [comment]
are you using a9lh? do you use tubehax dns?

**Comment by Darius20103104** [comment]
a9lh

**Comment by RinMaru** [comment]
ok did you have tubehax dns at any point?

**Comment by Darius20103104** [comment]
no

**Comment by Darius20103104** [comment]
my dns settings are normal

**Comment by Darius20103104** [comment]
on auto

**Comment by RinMaru** [comment]
ok. hmm what guide did you follow to install? is it downloading the update but not finishing? or is it connecting and giving an error?

**Comment by Darius20103104** [comment]
connecting and giving an error

**Comment by RinMaru** [comment]
strange. have you done anything to your router. it sounds like your being blocked from the update server

**Comment by Darius20103104** [comment]
i have tried on my phone i have unlimted data on it

**Comment by RinMaru** [comment]
do you have a wii u?

**Comment by Darius20103104** [comment]
no

**Comment by Darius20103104** [comment]
only 2 3ds

**Comment by Darius20103104** [comment]
both old

**Comment by RinMaru** [comment]
are you using any other 3ds hacks or homebrew apps?

**Comment by Darius20103104** [comment]
i used to use homemenuhax 3.1

**Comment by Darius20103104** [comment]
nevermind i just fixed it by deleting my old internet settings and restarting my router and connecting it again and it works

**Comment by RinMaru** [comment]
lol ok i figured that was the issue. you can close this then.
