### ISSUE TITLE
[REQ] Disable LED flashing when asleep

### ISSUE THREAD

**Issue by bel3atar** [LumaTeam/Luma3DS#218]
Possible?

**Comment by poutros** [comment]
Didn't yellows8 brick when messing with their 3ds' led? And leds don't waste that much either so it would be a pointless feature.

**Comment by TuxSH** [comment]
And which led?

**Comment by bel3atar** [comment]
The annoying blue one that keeps flashing. Gosh it lights the whole room!

**Comment by Shadow322** [comment]
There is 2 that light/flash blue what one again?

**Comment by bel3atar** [comment]
The one that flashes when the device is put to sleep. Front-facing left LED on o3ds.

**Comment by TuxSH** [comment]
https://github.com/Spaqin/bipolar-3ds/

Maybe this could do the trick
