### ISSUE TITLE
Problems with Software Management

### ISSUE THREAD

**Issue by tranaconda** [LumaTeam/Luma3DS#22]
When I go into Settings > Data Management > 3DS > Software, it starts enumerating but stops in the shortly after, showing "Could not access microSD card." next to the microSD card icon on the top screen.

This has been a bug for a while in open source CFWs - the same EmuNAND (back then, now I only use SysNAND) in Gateway Mode did not have this bug. No that I switched to A9LH, I can't easily switch to GW to access Software Management.

I don't think it's the SD card, as I tested it thoroughly with badblocks and used different ones as well. Also, it does not happen on my 2 O3DS.

The NAND was transfered from an O3DS and downgraded once. As stated above, in Gateway Mode before the switch to A9LH this bug did not appear, but at the same time when in rxTools.

Is it possible to make an option to disable all patches and just boot the homemenu clean?  Maybe this way we can find out what's wrong.

**Comment by stayfr0sty141** [comment]
i dont have issue with this one...

mine using a9lh with aureinand 4.2

**Comment by tranaconda** [comment]
Like I said, my 2 O3DS don't have this bug either and it doesn't happen in Gateway Mode. So Gateway does something different (maybe better, maybe worse) than rxTools and AuReiNAND.

**Comment by Hartie95** [comment]
Maybe it an application with a broken header, while experimenting with modifiing the sd cards data I had a similar problem on sysnand, but using gateway it worked.

**Comment by tranaconda** [comment]
Could be, but how do I find out which title is the culprit? And how does Gateway do it?

**Comment by Hartie95** [comment]
Depending on how much titles you have installed, the easiest way could be, to simply backup the nintendo 3ds folder and delete some titles using fbi, and recheck software management.

**Comment by tranaconda** [comment]
A lot! I've used this NAND since I bought my first 3DS when it came out. I just noticed that HANS seems to have a hiccup now, too. I know there's probably a corrupt title to blame, but it would be nice if AuReiNAND would handle it like Gateway, right?

**Comment by tranaconda** [comment]
For the record, I installed the microSD Manager as a cia a long time ago (https://gbatemp.net/threads/microsd-management-on-homecreen-and-working-on-old3dss-too.383892/page-3).

Title ID: CTR-N-HAJP

Just delete it with FBI or whatever. But it would still be nice to have a graceful fail like Gateway has.

**Comment by RShadowhand** [comment]
@tranaconda Is this issue fixed?

**Comment by tranaconda** [comment]
Well, for me personally, yes. But for the long run, it might be nice to handle faulty title gracefully like Gateway does.
