### ISSUE TITLE
Luma menu???

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#224]
When in Luma menu going up and down highlighting other options the bottom description screen text gets piled on-top of previous text and does not refresh with new text only

**Comment by RinMaru** [comment]
doesn't do it to me. using 6.2.3 n3ds

**Comment by cheatfreak47** [comment]
I can't reproduce this either on any of the 4 3DS consoles I have. 
This is just a hunch but... perhaps your A9LH install is out of date or something?

Try updating to the latest version of Arm9LoaderHax.
https://github.com/Plailect/Guide/wiki/Part-3-(arm9loaderhax)

Part 3 here has some good links for downloading what you need to update A9LH to the latest version.

Basically, all you need to do really is place the content of "data input" on the SD card root, drop the two payload files from Arm9LoaderHax (noscreeninit recommended) inside that folder and then run the safea9lhinstaller a9lh payload from luma's chainloader by dropping it into the luma/payloads folder and mapping it to a button. From there just press the button it says to update and you should be all good. 

---

For future reference, when creating issues on trackers it is a good idea to make the title more descriptive than you have here. For an issue like this, "Overlapping Bottom Screen Text on Luma Config" would've been more appropriate, not trying to come off as mean or anything, just making a point.

**Comment by Shadow322** [comment]
Not using A9LH and have no plans to do so anytime soon

**Comment by RinMaru** [comment]
why? its perfectly safe unless you skip around.

**Comment by cheatfreak47** [comment]
@Shadow322 Well then you possibly do have a legitimate problem, and perhaps it _should_ be looked into, but in the meantime, perhaps you should reconsider your thought process, and maybe get some self confidence. If you were good enough to install MenuHax and set up CFW that way, you're more than good enough to install A9LH.

Most people use A9LH for a reason, ya know. All the other options are inferior. That's not an opinion. It's not subjective. A9LH is objectively a better entry point for CFW than anything else, if you want to stick with something that's slowly being deprecated by the community, go right ahead, but don't say I didn't warn ya. :P

**Comment by AuroraWright** [comment]
Fixed
