### ISSUE TITLE
Gracefully handle oversized locale flags rather than ignore them

### ISSUE THREAD

**Issue by dogtopus** [LumaTeam/Luma3DS#226]
On linux, most text editors create files with a trailing line break. Therefore locale flags created by those editors are not 6 bytes long but 7 bytes long, which is really annoying since those flags must be truncated by other programs in order to work with latest Luma.

**Comment by TuxSH** [comment]
It should work with latest luma though.

**Comment by AuroraWright** [comment]
Done.
