### ISSUE TITLE
Streetpass not streetpassing

### ISSUE THREAD

**Issue by bonboncat** [LumaTeam/Luma3DS#227]
I got new3ds with a9lh luma 6.1.2 updated to fw 11.1.0-34U.
My sister's new3ds got updated the same way. 
Problem occurs when we activate streetpass but it's not streetpassing. Even when we stack our new3ds.
I have tried updating luma to 6.2.3 stable but still no luck. Should i downgrade to 11 and re update with luma 6.2.3?
I also tried updating mii plaza and turn on streetpass in it but still our new3ds is not streetpassing each other.
Did i miss something during fw update process? Or did i miss something in system setting? 
Any help is greatly appreciated.
Thanks in advance.

**Comment by AuroraWright** [comment]
This is not a 3DS helpdesk, Luma doesn't touch streetpass **at all**, so ask on the Nintendo forums or something.
