### ISSUE TITLE
System settings crashes with certain custom version strings

### ISSUE THREAD

**Issue by potjesoep** [LumaTeam/Luma3DS#230]
i changed the name to "Stable %d.%d%ls" and settings crashes on startup. luma3ds non-dev 6.2.3 2ds 11.1.0-34E (a9lh) this is reproducable for me. it always crashes if you don't have the full system version (%d.%d.%d-%d%ls) in the string. but if you don't have the version string in there at all it works. so it works woth either the full version string or no version string.

Examples:

Crashes:
- Stable %d.%d%ls
- HaxToTheMax %d.%d

Doesn't Crash:
- Luma %d.%d.%d-%d%ls
- Nintendo pls no sue

**Comment by AuroraWright** [comment]
This is already fixed in nightlies
