### ISSUE TITLE
[SUGGESTION] Online

### ISSUE THREAD

**Issue by Darius20103104** [LumaTeam/Luma3DS#231]
Please add private header genorator or at least you could have a private header on a sd card and load it from there or patch the games everytime you download a game and then restart so people would not have to always extract the game and replace the header just to not get banned

**Comment by FenrirWolf** [comment]
If you're using Luma3DS, what use do you have for private headers? They aren't a thing with CIA games.

**Comment by Darius20103104** [comment]
i use private headers to not get banned

**Comment by FenrirWolf** [comment]
That's not how it works. This ain't Gateway.

**Comment by Darius20103104** [comment]
Isent there a simple way to patch games to play online without getting banned

**Comment by FenrirWolf** [comment]
Yes, there's a simple way to play games without getting banned. It's called turning a game into a CIA. CIAs have no identifying header.

**Comment by MrDarius125** [comment]
Oh thats what i did i thought i had to like extract the game and replace the private header every time i would download a game from madloader.com

**Comment by ghost** [comment]
Remove that damn link @MrDarius125 , it doesn't belong here

**Comment by TuxSH** [comment]
Oh, I almost forgot:
<img src="http://i0.kym-cdn.com/entries/icons/original/000/018/815/794.png"/>
