### ISSUE TITLE
Activity Log entries

### ISSUE THREAD

**Issue by IngeniousDefault** [LumaTeam/Luma3DS#236]
Hi there.

Lately I noticed that games in the Activity Log are missing. They are just not there anymore but sometimes reappear when I launch the specific game. There is also a strange bug when launching a *hax. After that the system randomly raises the play time of the Download Play app.

**Comment by RinMaru** [comment]
i dont think luma even touches the activity log. plus im not having this issue

N3DS A9LH Updated sysNAND
