### ISSUE TITLE
nds games not loading 

### ISSUE THREAD

**Issue by ducky1549** [LumaTeam/Luma3DS#238]
nds games are not loading on this firmware where as they used to now launches with blackscreen and freezes up when launched without cfw it plays nds games fine. (using old 3ds)

**Comment by AuroraWright** [comment]
There's a mythical beast called "Wiki", it is said to wander around in full moon nights...
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#gbads-gamesdsiwaresmash-brosmonster-hunter-4-fail-to-start

**Comment by MelonGx** [comment]
There should be one more answer in the wiki:
Q: GBA/DS games/DSiWare/Smash Bros/Monster Hunter 4 fail to start
A2: For DS games fail to start, it used to be a Luma3DS issue which existed on 6.1 - 6.1.1.
Upgrade your Luma3DS to 6.1.2 or higher and delete /Luma/config.bin.

So I think it's not a RTFW issue, but a wiki issue.
@AuroraWright 

BTW, I can't confirm whether patched TWL_FIRM causes this issue or not.
