### ISSUE TITLE
Does Luma3DS 6.3.1 give up supporting Menuhax boot manager?

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#239]
Tried booting 6.3.1 arm9loaderhax.bin with CTRBootManager -> Weird screen.
Tried booting 6.3.1 mset-spider/Luma3DS.dat with CTRBootManager -> Auto shutdown.

**Comment by MelonGx** [comment]
OK. Never saw that it required BOTH Luma3DS.dat and arm9loaderhax,bin since 6.3.
Now 6.3.1 is successfully booted by CTRBootManager.

**Comment by AuroraWright** [comment]
You can also load arm9loaderhax.bin directly with the boot manager (it should be able to).

**Comment by MelonGx** [comment]
But actually it resulted a weird screen which looked like repeating "retry booting -> unable to boot into it" every 0.5 seconds, when I directly loaded arm9loaderhax.bin with CTRBootManager.
The offset parameter was remaining in 0x12000.

**Comment by Mrrraou** [comment]
Do you even know what it corresponds to
Change the offset to 0x0 and try again (it likely won't work though, because CakeBrah is limited in size)
