### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by louie1105** [LumaTeam/Luma3DS#243]
Cant play mon hun games and super smash bros

**Comment by Committee** [comment]
Can you be more specific? Console details, firmware version, sysnand or emunand, etc, have you also checked the Luma wiki?

**Comment by fox8091** [comment]
RTFW (Read the fucking wiki). There's a section on this.

**Comment by gotolab** [comment]
The same problem to me.
3DS ：Old 3DS LL （HongKong）
Firmware version：11.1.0-34J (Japan）
Run only sysnand
Luma version：6.3.1

**Comment by gotolab** [comment]
![1](https://cloud.githubusercontent.com/assets/22744973/19235473/783bc630-8f24-11e6-9dcd-f45410a19cf2.png)

Run Monster Hunter 4、4G、X、Super smash bros：

![22](https://cloud.githubusercontent.com/assets/22744973/19235479/7d972976-8f24-11e6-940a-58a44f60bddc.png)

**Comment by AuroraWright** [comment]
To @gotolab: do you have a "path.txt" file in /luma? If so, post it.
Also, did you try a different SD card?

**Comment by gotolab** [comment]
the path.txt had been deleted.

try another SD card , get the same result.

**Comment by gotolab** [comment]
i had try direct boot Gateway A9LH (.3DS Game） , it also is black screen
