### ISSUE TITLE
SNES VCs doesn't work

### ISSUE THREAD

**Issue by TwoSideA** [LumaTeam/Luma3DS#245]
Installed a SNES VC through CIA installation. Only part of the icon loads, where the TV is visible but the console and the title is not visible on the top screen. Once the VC is booted up, an error pops up and the 3DS automatically reboots.

**Comment by fox8091** [comment]
That's a CIA issue, not a Luma issue.

**Comment by TwoSideA** [comment]
I've installed 3 SNES VC, all gave me an error and rebooted. :v

**Comment by fox8091** [comment]
Try with another CFW (like Cakes). If it fails there too, it's a CIA issue. If it works, it's a Luma issue.

**Comment by TwoSideA** [comment]
So it's possible to stack firmware? Like having Luma installed then Cakes?

**Comment by cheatfreak47** [comment]
Just to verify, you are aware that SNES VC are NEW 3DS only, correct? I think I've heard of a similar issue happening for people that tried to install SNES VC on an Old 3DS.

**Comment by TwoSideA** [comment]
I'm using a new 3DS XL, with Luma and A9LH installed as per the guide.

**Comment by Committee** [comment]
Official released or custom SNES VC?

**Comment by TwoSideA** [comment]
1 official, 2 custom made.

EDIT: Scratch that, all 3 are custom made. Something else to note, custom GBA VCs work fine on my system.

**Comment by Rust-and-Sunset** [comment]
Sounds like it's 100% just an issue with the shoddily made CIAs you're using- Luma has nothing to do with the banner they display when selected on Home Menu, and what you've described is generally an indicator of a sub-par injection.

Try an official SNES VC title.

**Comment by TwoSideA** [comment]
Tried the official Super Castlevania IV SNES VC. Boots up and works! Haven't tested so far as to save yet. One thing to note is that the banner is incomplete(console and text not shown, only TV is visible) when selected on the Home Menu. I've tried custom made VCs from several users. I guess that means that Luma doesn't recognize them or something?

**Comment by pbanj** [comment]
what region is your system? im guessing jap?

if yes use the language emulation.

**Comment by MasterGamingYT** [comment]
You need seeds for the custom cias (correct me if I'm wrong)

**Comment by ihaveamac** [comment]
Why are you commenting on a really old issue?

**Comment by MasterGamingYT** [comment]
1. To help (obviously)
2. The problem might not be resolved

**Comment by MasterGamingYT** [comment]
How about we not start an argument, ok?

**Comment by ihaveamac** [comment]
If the issue was closed a long time ago, it probably doesn't need any additional comments.

**Comment by MasterGamingYT** [comment]
You might be right

**Comment by ihaveamac** [comment]
I know you're trying to be helpful, but this isn't helping anything. Nearly 2.5 years has passed since the issue was created. It's very unlikely the situation is the same anymore. If you really want to help, consider issues that are open instead.

**Comment by MasterGamingYT** [comment]
Ok
