### ISSUE TITLE
CPU clock for latest 2DS in Japan?

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#246]
From the Chinese hardmodder BZY's report, the latest JPN 2DS (released last month) uses N3DS's CPU.
So I wonder if it supports the CPU clock function?

**Comment by piratesephiroth** [comment]
what??

**Comment by ihaveamac** [comment]
source?

**Comment by piratesephiroth** [comment]
Supposing the O3DS firmware even supported the faster clock, why would they bother adding a faster CPU without adding the additonal RAM?

**Comment by ihaveamac** [comment]
if you really wanted to use the faster clock speed on Old3DS that happened to be using a New3DS CPU, you'd probably need New3DS firmware. which won't really work, for a number of reasons.

**Comment by TuxSH** [comment]
@MelonGx could you test this payload and post a snapshot of your 2DS running it, please?

[left_test.zip](https://github.com/AuroraWright/Luma3DS/files/524121/left_test.zip)

(it's just displaying `1 + (*(vu32*)0x17E00004 & 3)`, ie. the number of cores of the arm11 processor)

**Comment by TuxSH** [comment]
bump

**Comment by AuroraWright** [comment]
The way I read it, he doesn't have such a console himself, he just heard about this from a Chinese hardmodder

**Comment by MelonGx** [comment]
I'm trying to ask the Chinese hardmodder and other hardmodders who suppose to be able to hardmod that latest 2DS to test it.

For my test result, O3DS's ARM11 core = 2, N3DS's ARM11 core = 4.
If the latest 2DS does use N3DS CPU, it should be 4.

**Comment by MelonGx** [comment]
Bad news:
The hardmodders returned back those latest 2DSes to owners and I cannot contact the owners.
That means we should take more time to get a result of this.
Thanks @TuxSH for the test payload to identify the CPU.
Feel free to close this issue if expecting no one can give any result.

**Comment by MelonGx** [comment]
Bad news:
One tester reported that Latest 2DS ARM11 core = 2.
So I close this issue until whom gives another different report.
