### ISSUE TITLE
New 3DS: slow SNES VC when using "Clock" or "L2"

### ISSUE THREAD

**Issue by mcpower** [LumaTeam/Luma3DS#247]
New 3DS XL with A9LH on 11.1. Running Luma3DS v6.3.1-c5eb2e10. Luma settings enabled:
- Autoboot SysNAND
- Use SysNAND FIRM if booting with R
- Enable custom region/language emu. and ext. .code
- Show NAND or user string in System Settings
- Show GBA boot screen in patched AGB_FIRM

Every non-boolean setting is set to the left-most option (1/4/Off/Off/Off/Off).

When "New 3DS CPU" is set to either of the middle options ("Clock" or "L2"), the official The Legend of Zelda: A Link to the Past SNES VC slows down, resulting in around 50% slowdown and sound distortion as a result. Setting it to either "Off" or "Clock+L2" fixes the issue.

**Comment by AuroraWright** [comment]
At the moment this is intended, because SNES VC is Clock + L2 by default and that setting changes things for all booted titles. If it's possible to change this behavior in the future, it will be done.
