### ISSUE TITLE
Battery percentage

### ISSUE THREAD

**Issue by Lapan** [LumaTeam/Luma3DS#254]
Would it be theoretically possible to show the battery percentage in numbers somewhere on the homescreen?

**Comment by ghost** [comment]
You can use Bipolar (https://github.com/Spaqin/bipolar-3ds) to display the battery percentage.... 
(it also permits to disable the power led....)

**Comment by Lapan** [comment]
It only seems to show the percentage when it's launched, I'd be more interested to see that on the home screen, mainly to see if it's already fully charged since the bars aren't really a good representation of that.

**Comment by TuxSH** [comment]
On home-menu? Not really possible.

**Comment by Lapan** [comment]
Oh well
