### ISSUE TITLE
Animated banners 

### ISSUE THREAD

**Issue by Jolty95** [LumaTeam/Luma3DS#255]
Hello everybody.
First of all sorry my english mitakes ^^"
I have a a9lh + luma sysnand in my old 3ds xl and I've noticed that sometimes after installing a CIA or after closing the top screen (I mean closing the console don't know the exact word) sometimes the animated banners doesn't recognise the mic and I have to reboot the console if I want the banners recognise the mic.
I want to know why is this happening because I haven't noticed this before. I'm using latest commit of luma.
Thanks for all :)

**Comment by ghost** [comment]
Are the CIAs' region different than your 3DS' region? (For example CIA is EUR, 3DS is USA)

**Comment by Jolty95** [comment]
No, it's same region.
Thanks :)

**Comment by ghost** [comment]
Are you sure it's a problem with the CIAs and not the microphone? You might wanna get it checked...

**Comment by james-d-elliott** [comment]
By mic I think you mean speakers? Microphones are sound inputs, speakers are sound outputs.

**Comment by ghost** [comment]
"banners doesn't recognise the mic" where does it mention the speakers?

**Comment by Jolty95** [comment]
Sorry if I confuse you. With mic I mean when you are in home menu and you blow on the mic the 3d banners start spining quickly and when you stop blowing the spin speed go more slow. I've tested with different cias and always the same. If I want after installing a cia to have the spin speed after blowing I have to reboot. 
Thanks for all :)

**Comment by Masamune3210** [comment]
I have had this happen once or twice as well with the latest stable of Luna, reboot always fixes it. Maybe a bug snuck through, since most people don't know about this quasi easter egg of a function

**Comment by Jolty95** [comment]
I agree with you. Most of people doesn't know about this "function" and maybe a litle hidden bug is causing this to happend (???)

**Comment by fox8091** [comment]
Nope. :P Luma doesn't touch it. That's an OFW issue.

**Comment by cheatfreak47** [comment]
Thats a function of the official firmware, nothing luma does touches it and it's always behaved that way.
It does this because in loud environments, the icons would be spinning non stop forever and that is really distracting if you happen to be gaming in a loud place.

To remedy this, after a while of spinning, it just starts to ignore the mic.

**Comment by Jolty95** [comment]
I didn't know that...I was only trying to help.
Thanks for all anyway :)
