### ISSUE TITLE
ds/dsi mode broken 

### ISSUE THREAD

**Issue by angeluskun** [LumaTeam/Luma3DS#259]
when i install luma arm9loaderhax on my ctr nand with the new safea9lh installer, ds mode is broken :(

**Comment by Margen67** [comment]
What commit are you using?

**Comment by angeluskun** [comment]
5d868284

**Comment by angeluskun** [comment]
oh my issue is similar to this issue https://github.com/AuroraWright/Luma3DS/issues/258 the answer is here hahah sorry

**Comment by fox8091** [comment]
If your issue is resolved, please close the issue.
