### ISSUE TITLE
Can't boot DS games on emunand

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#262]
Hello.
When i use an emunand, i can't boot DS games -> the 3DS switches itself off. 
But it works on the sysnand.

I have a New3DS, A9LH (sys=11.2, emu=9.2) with Luma3DS (5d868284c69a86413e3f1f019578130ca9d14d3a    fix FIRM 11.2 commit)

Nope, i use the emunand for my flashcard (because of the date, i don't want to be in 2010 on my sysnand)

If you have any ideas...

**Comment by cheatfreak47** [comment]
You should find a custom kernel for your date bombed flashcart, many of them have it. I recommend seeking help on GBATemp.

**Comment by urherenow** [comment]
Install the same game to both. No matter what, agb_firm and twl_firm launch from nand, not SD. You CANNOT fix that.

**Comment by ghost** [comment]
Thanks for your replies.
Nope, the website of the flashcard doesn't exist anymore. And no custom kernel on gbatemp (r4i-gold.com)
Why the 3ds switches  itself off when i launch a ds game on the emunand? 
That was not the case before :-( ...

**Comment by Margen67** [comment]
Have you tried looking for it on archive.org?

**Comment by ghost** [comment]
I already use the latest flashcard kernel...

**Comment by AuroraWright** [comment]
Reinstall a clean TWL FIRM:
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-have-issues-with-gbadsdsiware-games-and-i-have-installed-a-patched-agbtwl-firm-cia-in-the-past

**Comment by ghost** [comment]
OK, i have reinstalled clean twl firm, and now it works! 
The weird thing is just that i have never patched the twl and agb firms on the emunand before... X_X

Thanks all!
