### ISSUE TITLE
Problems after upgrading to 11.2

### ISSUE THREAD

**Issue by juankasv99** [LumaTeam/Luma3DS#269]
Hi, I updated my N3DS to 11.2, and then the EMUNAND doesn't appear. I mean, i tried pushing Select when booting and things like that, but only runs the normal system, without the Luma. I have Luma + Menuhax, some help please? :/

**Comment by cheatfreak47** [comment]
When it runs the normal system, what version is it on?

**Comment by juankasv99** [comment]
Version 11.2.0-35E

**Comment by cheatfreak47** [comment]
Welp, you're boned. You somehow updated your SysNAND.
Rip in Pepperoni

**Comment by juankasv99** [comment]
Yeah, I know, but why? I mean, I updated from the EMUNAND :/

**Comment by cheatfreak47** [comment]
Beats me, but it happened.

@TuxSH @AuroraWright I can confirm this happens sometimes btw, I have no idea how, but I've had a friend experience this himself, I watched him update his EmuNAND myself over Skype.

For him, it happened back when the guide had people using EmuNANDs still.
It happened right after he ran luma on the EmuNAND to update it.

Luckily he had a copy of fieldrunners with it's hax on the SysNAND still so he just redowngraded.

**Comment by juankasv99** [comment]
So... No solución for that right? :(

**Comment by cheatfreak47** [comment]
you wouldn't happen to have fieldrunners with fieldrunner hax installed would you?

**Comment by juankasv99** [comment]
Nope

**Comment by cheatfreak47** [comment]
You plum done for then, mate.
Should've been using Arm9LoaderHax and updated SysNAND.

**Comment by MelonGx** [comment]
Mistaking leads you to the SysNAND upgrade.
To upgrade EmuNAND without any mistake, you MUST always
1) Go System Settings
2) CONFIRM that the version string is Emu X.X.X-XX
3) Go through the Internet upgrade WITHOUT exiting the System Settings

**Comment by juankasv99** [comment]
Yeah, I did all of this '^^

**Comment by MelonGx** [comment]
Mistaking leads you to the SysNAND upgrade.
To upgrade EmuNAND without any mistake, you MUST always ONLY upgrade EmuNAND in System Settings:
1) Go System Settings
2) CONFIRM that the version string is Emu X.X.X-XX
3) Go through the Internet upgrade without exiting the System Settings

**Comment by juankasv99** [comment]
So I have to wait until a fix is released, right? Or is there something I could do?

**Comment by cheatfreak47** [comment]
@LakeTheGray I don't think you understand.

Your 3DS is now running the latest firmware on sysNAND without CFW.
You are basically stuck on stock until a new downgrade method that works for 11.2 is released.

**Comment by juankasv99** [comment]
@cheatfreak47 Yes yes, I understand, i was asking for a downgrade method or something similar. So, I have to wait then '^^. Thx for your help :D

**Comment by TuxSH** [comment]
Somehow System Settings can _reboot_ (as in "mcu reboot") your console for one reason or another. 

When trying to update emuNAND, check the version string then go **directly** to "Other settings" > System update. If something happens inbetween, or if for some reason the screen goes down before the actual update window, cancel and retry.
