### ISSUE TITLE
DS cartridge & flashcart won't boot using ARN v5

### ISSUE THREAD

**Issue by thaikhoa** [LumaTeam/Luma3DS#27]
Black screens with or without twl firm.

**Comment by cheatfreak47** [comment]
I use v5 and have no such issue, probably a user specific issue.

**Comment by Hartie95** [comment]
For me twl is working using the arm9loaderhax.bin, but its not working using the AuReinand.dat(n3ds, bootctr9, a9lh)

**Comment by thaikhoa** [comment]
Solved by changing path for AuReiNand.dat using command line "aurei/"

**Comment by AuroraWright** [comment]
AuReiNand.dat is only supported for *hax users. I say so in the wiki too. If you use A9LH the arm9loaderhax.bin will always take precedence. So not really a bug...

**Comment by thaikhoa** [comment]
I thing is I really don't want to copy, paste & rename many arm9loaderhax.bin(s) for payloads around when updating things... that's why I prefer AuReiNand.dat only to use with bootctr. Sorry for not throughfully understanding. Yes, it's definitely not a bug.

**Comment by Hartie95** [comment]
And I normaly used the AuReinand.dat for testing commits, but now I see why it is failing, the .dat is only the fallback, I thought the main string will be different depending on the version(.bin/.dat).
