### ISSUE TITLE
A suggestion for Luma3DS in CTRNAND and the files that it create.

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#270]
When I load Luma since CTRNAND, and if I have SD inserted, Luma3DS create a "Luma" folder and "config.bin" in SD but I haven't "arm9loaderhax.bin" in SD. I load "arm9loaderhax.bin" by CTRNAND.

Maybe would better if Luma3DS don't create files in SD if this load by CTRNAND. SD would be clean without CFW files, Luma3DS only should read /rw if there aren't files in SD.

**Comment by AuroraWright** [comment]
Not possible to know where it was loaded from, and CTRNAND is only intended for SDless boots.
