### ISSUE TITLE
Support for screenshots?

### ISSUE THREAD

**Issue by sora10pls** [LumaTeam/Luma3DS#28]
While it is possible to use something like NTR CFW on top of AuReiNand for screenshots and the higher CPU clock, I figured that since you added the higher CPU clock on boot, it'd be worth asking if screenshot implementation could work.

Perhaps toggling it in the configuration menu as well as a hotkey for what to take screenshots with? That is if it's possible to begin with.

**Comment by AuroraWright** [comment]
Our resident reverse engineer said this is not feasible within 3ds_injector. So I'm afraid I can't do this for the time being.
