### ISSUE TITLE
Luma3DS.dat doesn't work with CTRBootManager since 6.5

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#280]
If replacing 6.5-6.6's Luma3DS.dat with 6.3.1's, then CTRBootManager -> 6.3.1's Luma3DS.dat -> 6.6's arm9loaderhax.bin can be booted properly.

Need to say that CTRBootManager -> (directly boot) arm9loaderhax.bin is still NG.

**Comment by AuroraWright** [comment]
Fixed with https://github.com/AuroraWright/Luma3DS/commit/f155026d8f7d2a9bee07372c23b58af5acb10f72. arm9loaderhax.bin directly should also work with offset 0, it's just a normal arm9 payload.
