### ISSUE TITLE
Use SDless booting concept to remove .bin from SD card

### ISSUE THREAD

**Issue by rickdgray** [LumaTeam/Luma3DS#281]
Being able to boot to the .bin on CTRNAND is a very cool idea but I think it would be better if it was possible to set that to default in the settings or to even autodetect it. In my opinion, the CFW is needed to keep the system operable so therefore it should be installed to the system by default anyway. Regardless, I think it'd be very useful if the feature was transitioned from SDless-mode to simply onloaded-hack mode. Thoughts?

To be clear, what I'm describing is being able to remove the .bin from the SD card and the system still operate normally by using the .bin on the CTRNAND.

**Comment by rickdgray** [comment]
To be clear, what I'm describing is being able to remove the .bin from the SD card and the system still operate normally by using the .bin on the CTRNAND.

**Comment by Committee** [comment]
Doesn't the latest release already do this?

**Comment by AuroraWright** [comment]
It indeed does...

**Comment by rickdgray** [comment]
When the SD card is inserted, it will still create and use data on the SD card even when the .bin was not on the card itself. What I'm trying to describe is allowing the hack to operate exclusively off of the NAND regardless if the SD card is inserted or not.

**Comment by Mrrraou** [comment]
nintendo already implemented it officially and it's called "removing the sd card"
there's literally no need for this, and that's way too complex to implement.

**Comment by AuroraWright** [comment]
https://github.com/AuroraWright/Luma3DS/issues/282#issuecomment-260692140
