### ISSUE TITLE
[Suggestion] Screenshot feature

### ISSUE THREAD

**Issue by IngeniousDefault** [LumaTeam/Luma3DS#283]
Hi there.

Is it possible to add a screenshot option to Luma? It's great to take gameplay screenshots with NTR CFW with just pressing L + R, however you always have to boot NTR first. Luma could always activate such a feature directly without booting another application first. Screenshots could be saved in /luma/screenshots.

**Comment by walterclozet** [comment]
I would like this feature too.

**Comment by Mrrraou** [comment]
Same as #138 for now.

**Comment by ly0koS** [comment]
I think it will be a very cool feature(which no longer need ntr to do this)!

**Comment by JuneTwooo** [comment]
+1 !

**Comment by RenaKunisaki** [comment]
I'd love a screenshot feature, but instead of it being part of Luma, I'd replace the useless Game Notes applet with a custom applet that lets you take screenshots and doodle on them. Is there any documentation on replacing those applets?

**Comment by Margen67** [comment]
NTR CFW runs in the background but there's no source code

**Comment by fox8091** [comment]
Runs in the background with a network connection on a device with front and rear cameras and a mic..no source code... _looks at Windows 10_ Nah... (jk)

**Comment by JustForNothing** [comment]
Should be possible, I think.
Someone RE'd the screenshot thing from NTR
https://github.com/conanac/REaMscreenshot

**Comment by Mrrraou** [comment]
No need to reverse it to know how to do screenshots.

**Comment by ewormPL** [comment]
One more vote for this. Using NTR is not particularly inconvenient, but with how awesome Luma is, it almost feels wrong to need an alternative for such a "basic" function.

**Comment by TuxSH** [comment]
It's not as basic as you think.

**Comment by wyatt8740** [comment]
So then @TuxSH I take it you're saying you don't plan to implement it?

I understand it's not "basic" at all, but it would be a welcome addition IMO.

NTR apparently has it, so it's not "impossible," at least... Is there no one working on it? I could give it a shot but I am nervous about bricking my only 3DS.

**Comment by urherenow** [comment]
Highly unlikely you could brick, attempting to save a screenshot to SD. Even less if you have a9lh and a nand backup. IMPOSSIBLE with a NAND backup and a hard mod.

**Comment by wyatt8740** [comment]
I am just particularly talented at going in too far when I don't really know what I'm doing. And more worried about deleting save data or corrupting something than a hard brick.

I don't have a decent iron anymore to do the hard mod.

**Comment by AgentScarlet** [comment]
How do you take a screenshot via boot ntr in game and use it on your laptop??

**Comment by Shadow322** [comment]
This is not a help place go ask on gbatemp
