### ISSUE TITLE
FriendCodeSeed_B sig check

### ISSUE THREAD

**Issue by piratesephiroth** [LumaTeam/Luma3DS#285]
After the recent ban wave It seems changing the serial in SecureInfo isn't enough to regain online access and we must have a different FriendCodeSeed as well.

Could you patch that sig check to allow changes to the file?

**Comment by AuroraWright** [comment]
Do you want me to hack into Nintendo's server to patch this check? /s

**Comment by ihaveamac** [comment]
an invalid signature will probably just give you 002-0121 anyway

**Comment by AuroraWright** [comment]
Yes, it seems the check is performed server-side.

**Comment by piratesephiroth** [comment]
So the file is actually sent to Nintendo? 
the absolute mad man
