### ISSUE TITLE
Black screen when I want to launch SafeA9LHInstaller

### ISSUE THREAD

**Issue by Marcos112** [LumaTeam/Luma3DS#289]
Hi there,

Can someone help me to install SafeA9LHInstaller on New 3DS XL ver9.2-20E?

I have follow the steps from : 
https://plailect.github.io/Guide/installing-arm9loaderhax

I reached to "Section II - Installing arm9loaderhax" - New 3DS.
If you can suggest me different methods to install that will be great.

**Comment by cheatfreak47** [comment]
This is the totally wrong place for your problem.

That said, just keep trying, eventually it will work.

Please close this issue thread :P
