### ISSUE TITLE
SafeA9LHInstaller v2.6.4 

### ISSUE THREAD

**Issue by Marcos112** [LumaTeam/Luma3DS#290]
Hi there,

I successfully installed  SafeA9LHInstaller v2.6.4 but then I got this message:

"Thanks to delebile, #cakey and StandardBus

Press SELECT to update A9LH, START to uninstall
Press any other button to shutdown"

when I press any button to shutdown and re-open the N3DS I will still be getting the above mesasge.
Can someone help me?

By the way, I have New 3DS XL ver9.2-20E, and I follow all the steps to "Section II - Installing arm9loaderhax" from:
https://plailect.github.io/Guide/installing-arm9loaderhax

**Comment by cheatfreak47** [comment]
What part of "This is the totally wrong place for your problem." didn't you understand?

This is for reporting actual issues about the Luma 3DS custom firmware only.

This is not the place for getting help following basic instructions that my 14 year old sister can follow without asking half as many questions as you have.

---

Basically, you followed one of the steps wrong if you're seeing that. 
You need to place the correct arm9loaderhax.bin on the root of the SD card.

Any further questions should be directed somewhere else, like GBAtemp or the 3dshacks subreddit.

**Comment by Mrrraou** [comment]
Don't bash 14 year old children

**Comment by james-d-elliott** [comment]
@cheatfreak47 he did not follow any steps wrong. https://github.com/Plailect/Guide/issues/717

@Marcos112 please copy the arm9loaderhax.bin from the Luma3DS.7z onto the root of your SD card. You just need to replace it.

**Comment by Plailect** [comment]
He did follow steps wrong. 2.6.4 did not exhibit the behavior in that issue.

**Comment by cheatfreak47** [comment]
>tfw someone tries to retroactively make a statement you made wrong in light of a change that happened after the fact.

https://u.teknik.io/19k5M.jpg

Nah I'm sure it was an honest mistake, right? 😏

**Comment by james-d-elliott** [comment]
Oh oops! I thought it was implemented earlier.
