### ISSUE TITLE
Latest Luma3DS nightly breaks cia installation

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#291]
From freeshop: wrong title key at 98%-99%.
From FBI: Module: AM (32) Desc: Cert signature or hash check failed.
And it also failed with eShop download (with a free game).

Installing older luma3ds (like 6.5), and then reinstalling 6.6 fix the issue.

Any ideas?

N3DS EUR, 11.2 Sys.

**Comment by urherenow** [comment]
You somehow have a bogus ticket installed, whether it came from a CIA install or from a bad key uploaded to whatever database you're using. I bet if you research the ID of the game/demo/whatever and delete the ticket with FBI, it will install fine from eshop.

**Comment by ghost** [comment]
Nope. 
I have used tiksweep-> doesn't work.
Boot into an emunand ->same issue than the sysnand.

Just by installing the older luma3ds solving the issue on both sysnand and emunand (without remove tickets on emunand).

**Comment by AuroraWright** [comment]
https://github.com/AuroraWright/Luma3DS/releases/tag/v6.6 read carefully.

**Comment by ghost** [comment]
Unfortunately, that was not the case. I haven't checked the UNITINFO by mistake.
Indeed, I was able to access the eShop (to try to download flipnote studio).
edit: I can not reproduce the bug. If i manage to, I will make a video.
I close the issue for now.

edit: it seems using Star updater break Luma3DS. Use Luma updater instead!!
