### ISSUE TITLE
Child Proofing

### ISSUE THREAD

**Issue by JumperGerald** [LumaTeam/Luma3DS#292]
Could we have a separate pin # when trying to launch any of the payloads or luma settings and one another optional one for booting directly into home menu.

**Comment by fox8091** [comment]
This is a CFW, not a babysitter. Instead of childproofing someone else's work, educate your child.

**Comment by JumperGerald** [comment]
Shall I change to the title to idiot proofing? Before casting ignorant judgment on others maybe it would be wise to take into consideration that I may not have children but would like to see a secure platform that a child couldn't easily break.

**Comment by fox8091** [comment]
If you want secure, use the official OS. Not a HOMEBREW software with ADVANCED features.

**Comment by fox8091** [comment]
Also, #252. Learn to read please. :)

**Comment by NexoCube** [comment]
Don't be a prick @fox8091 . This bloated cfw is already unreadable, just add the feature.

**Comment by urherenow** [comment]
Just add the feature? This is open-source, son. Don't nake demands, do it yourself or GTFO.

**Comment by NexoCube** [comment]
I can't. It's unreadable. Only these autistic niggers can make sense of this spaghetti.
