### ISSUE TITLE
Payload error?

### ISSUE THREAD

**Issue by DeKuSkrub** [LumaTeam/Luma3DS#293]
When I boot up Luma from the Homebrew Launcher (via Ocarina Hax), I get an error that reads "An error occurred while loading the payload.
Press any key to continue"
Then when I press something, I get rebooted to the Homebrew Launcher. Can I get some help?

**Comment by urherenow** [comment]
Github is for bugs, not a help forum. You can help yourself be reading the docs and tutorials at gbatemp. Your problem is most likely that you're trying to run Luma from a firmware greater than 9.2. Use the guides to downgrade and get a9lh already.

**Comment by DeKuSkrub** [comment]
OK, geez.

**Comment by DeKuSkrub** [comment]
Sorry, I'm new here. Now why don't you stop being a fucking prick? I thought it was a bug, I didn't know.

**Comment by fox8091** [comment]
Close please?

**Comment by Margen67** [comment]
>Now why don't you stop being a fucking prick?

Okay. I'll be nice.
I'm sorry you're an idiot.

**Comment by pbanj** [comment]
you are missing the arm9loaderhax.bin on the root. it is needed even without arm9loaderhax

**Comment by MaxLempira** [comment]
If you're on a New 3DS and have Clock+L2 Enabled, Disable it and it will work ;) I already made an Issue to report this!

**Comment by Margen67** [comment]
*switch to A9LH
