### ISSUE TITLE
Enable region/language emu. and ext. .code

### ISSUE THREAD

**Issue by simonrule** [LumaTeam/Luma3DS#295]
i had problem with dlc out of region version i couldn't make work with the game there both usa version and my 3ds is europe version so i tried "luma switch local" with enabling "game patching" in my luma 6.6 version but didn't work but when i downgraded to luma 6.3.1 and i did enable this  "**Enable region/language emu. and ext. .code**" the dlc did work and everything is working great so is there anyway you can get this feature back to luma 6.6 or fix the game patching because didn't work for me and i'm sure it's not going to work for others.
and i would like to thank you so much for your hard work :)

**Comment by AuroraWright** [comment]
You forgot to mention the game...

**Comment by simonrule** [comment]
sorry the game is fire emblem awakening i search in the forums i find a member having the same problem
https://gbatemp.net/threads/fire-emblem-awakening-dlc-problems.442574/
he was able to fix the problem with same i did by enabling this **region/language emu. and ext. .code**

**Comment by AuroraWright** [comment]
The issue isn't in Luma, it's in that "locale switcher" app which needs to be updated for the new folder layout in nightlies (/luma/titles/titleID/locale.txt instead of /luma/locales/titleID.txt).
