### ISSUE TITLE
Patched binared are not loaded

### ISSUE THREAD

**Issue by YozenPL** [LumaTeam/Luma3DS#297]
Hi, I was using patched binary for PKM (no outlines) and it was working fine with older releases. With new one it does not work any more.

**Comment by Sky-Lochagos** [comment]
if titleid.bin isn't working make a folder in /luma/ named titles and a folder inside that named the games titleid. code.bin goes inside that.

eg. SDRoot:/luma/titles/0004000000175e00/code.bin
for a code.bin for pokemon moon

**Comment by YozenPL** [comment]
Thanks! It is working now :)

**Comment by fox8091** [comment]
If working, could you close?
