### ISSUE TITLE
Add optional country spoofing to region/language emulation

### ISSUE THREAD

**Issue by ojinoo** [LumaTeam/Luma3DS#298]
The country of residence stays the same, when playing Pokémon™ Sun (and other games) with Japanese language and region emulation.

That means that all Pokemon that I catch will be illegal in PKHeX, because each Pokemon has a field for 3DS Region and Country. One would get e.g. Country: United States, 3DS Region: Japan, which is not possible since a Japanese 3DS can't choose a 'country of residence' outside of the region.

The other problem is that Pokemon Global Link displays your country on the website, so it would be weird and conspicuous, if it showed 'USA' in a Japan only online competition:

![screen shot 2016-12-06 at 21 55 20](https://cloud.githubusercontent.com/assets/24419319/20943191/c5488286-bbfe-11e6-9772-6a55b2f25697.png)

It would be nice and useful, if one could add another option to the locales file to spoof 'country of residence'. 

It's not necessary to make every country selectable, an optional on/off option, with default off, would be enough, so that a representative country for that region is automatically selected, e.g.: Japan for Japan, United States for Americas, Germany for Europe and subregion should be set to blank.

**Comment by srwgin** [comment]
maybe we can change it to
region-language-country of residence-appropriate region
country of residence and appropriate region list maybe we can dump from 3ds
it looks like this
USA-EN-United States-New York
JPN-JP-日本-北海道
EUR-FR-France-Limousin

and if you check select region you will find USA/ESP/JPN come from country of residence
not region

**Comment by 3096** [comment]
This issue deserves more attention!

**Comment by TuxSH** [comment]
Not possible atm
