### ISSUE TITLE
Does this work for oothax3ds

### ISSUE THREAD

**Issue by PyroBurnz** [LumaTeam/Luma3DS#299]
I am new to this so can someone help me out like a video and or step by step instructions for loading up luma cfw and I am running 11. 2. 0-35U and also sorry but can ya tell me which way I can get free shop and cia games installer like fbi

**Comment by ihaveamac** [comment]
wrong place to ask. https://3ds.guide

**Comment by PyroBurnz** [comment]
Question how to post question

**Comment by cheatfreak47** [comment]
The short answer to your question is you can't run it. Not easily. You basically screwed yourself by updating your 3DS regularly.

It is _possible_ to downgrade to an older firmware, but doing so will require jumping through some very difficult hoops. Hoops you probably either won't be able to or will not have the ability for. 

But if you wanna try anyway, follow http://3ds.guide

The appropriate place to ask questions is the 3dshacks subreddit, GBAtemp, or the 3DS Hacking Discord.
GitHub is NOT a support forum.
