### ISSUE TITLE
GBA games not loading?

### ISSUE THREAD

**Issue by fallenlucario** [LumaTeam/Luma3DS#30]
I'm using updated sysnand and my GBA games wont load, on 4.2 it gives me an error message, on 5.0 i just get a black screen. Am i doing something wrong?

**Comment by RShadowhand** [comment]
Do you have a bootloader before ARN? (like ctrbootmanager9, or bootctr9)

**Comment by fallenlucario** [comment]
I'm using arm9select

**Comment by RShadowhand** [comment]
Read the last section of this: https://github.com/AuroraWright/AuReiNand/wiki/Preparing

**Comment by fallenlucario** [comment]
Where do i get that path changer program it mentioned?

**Comment by RShadowhand** [comment]
Download ARN5 from releases page, you'll see the folder there.

**Comment by teconmoon** [comment]
It's in the latest download.
