### ISSUE TITLE
OoTHax + Clock+L2 "Glitch"

### ISSUE THREAD

**Issue by MaxLempira** [LumaTeam/Luma3DS#300]
New 3DS - A9LH SysNAND - 11.2.0-35U
Latest Luma3DS Build Release

Hello! Here to report that, while having Clock+L2, OoTHax is not working, when pressing A to Launch Hombre Launcher, it just return to Home Menu with a Message and then a system reboot.
After Disabling Clock+L2, OoTHax works like normal, hope it can be fixed.
Thanks!

**Comment by AuroraWright** [comment]
Not a Luma issue, use Clock alone

**Comment by Margen67** [comment]
Why are you using OoTHax if you already have A9LH?
Just use this https://github.com/yellows8/hblauncher_loader/releases
