### ISSUE TITLE
002- 0119

### ISSUE THREAD

**Issue by SpaghettiKin** [LumaTeam/Luma3DS#302]
On 6.6-F8984525 Getting error in subject. 3DS updated to 11.2

**Comment by Margen67** [comment]
Try updating Streetpass

**Comment by SpaghettiKin** [comment]
Streetpass completed an update. Issue Remains.

**Comment by Margen67** [comment]
Try the latest nightly https://astronautlevel2.github.io/Luma3DS/

**Comment by SpaghettiKin** [comment]
Have the latest nightly (f8984525). Don't think it would make a difference if I used star updater would it?

**Comment by svanheulen** [comment]
@SpaghettiKin StarUpdater is deprecated and was discontinued by the author. You should use [Luma Updater](https://github.com/Hamcha/lumaupdate) instead. That may not be your issue but StarUpdater has been known to download weird/wrong versions of Luma3DS.

**Comment by Shadow322** [comment]
@SpaghettiKin StarUpdater works fine if u want to continue to use it do so I have never had a problem with it ever

**Comment by SpaghettiKin** [comment]
Honestly what I did was say screw it and create A9lh+luma on my sysnand and it works fine
