### ISSUE TITLE
Mystery machine patch?

### ISSUE THREAD

**Issue by mariogamer2** [LumaTeam/Luma3DS#304]
like corbenik

**Comment by fox8091** [comment]
Nope, that's what code redirection is for. Individual game patches don't belong in a CFW.

**Comment by GrayJack** [comment]
Individual game patches does belong in a CFW, depending what is the propose of the CFW.
But I don't think it is the propose of Luma3DS to add patches for individual games.

**Comment by Mrrraou** [comment]
use ips patches or something...
