### ISSUE TITLE
Luma3ds and payloads won't load when switching from 32 to 128gb sd card

### ISSUE THREAD

**Issue by ismael587** [LumaTeam/Luma3DS#308]
Hello!
I first installed luma 3ds 6.5 on my 32gb sd card and everything works fine. I bought a 128 gb sd card and i formatted it to fat32. I copied every files on the 32 gb card to the new 128gb sd. But now i can't load luma3ds from the sd and i can't get payloads working (hourglass9). However luma3ds still load from the nand when i hold select at startup. It seems that luma 3ds doesn't recognize my 128 gb sd card but everything works fine works fine in the 3ds menu.
I don't know what to do?
i have a old 3ds +luma3ds + a9lh

**Comment by urherenow** [comment]
Were you using emunand before? Simply copying the files doesn't copy emunand/rednand.

If no, try switching your format between 32k and 64k clusters.

**Comment by ismael587** [comment]
i was not using emunand
i tried switching to 64kb clusters but it still does not work

**Comment by ismael587** [comment]
There's no problem for installing cias with FBI the card is recognized

**Comment by ismael587** [comment]
finally i reformatted with 32kb clusters with another tool and i made a direct copy from one card to the other and it works fine now.

**Comment by james-d-elliott** [comment]
You should be able to close this then.

**Comment by weirdal3333** [comment]
This problem usually happens when the card's partition table comes with a GPT partition table. All you need to do is change it to a MBR partition table and format it as a FAT32 partition, and it should work fine.
