### ISSUE TITLE
L2 disables n3DS clock in every game

### ISSUE THREAD

**Issue by Garro** [LumaTeam/Luma3DS#31]
I'm not sure if this is the intended behavior, but enabling only L2 for the new3DS RAM option disables the extra RAM for both o3DS and n3DS games (Making games like Hyrule Warriors Legends lag on new 3DS).

As far as I know, L2 helps loading o3DS game faster right? I was expecting L2 to be active in every game and the extra RAM be active on only n3DS games, but then again, I'm not sure if this is how it's supposed to work.

**Comment by TuxSH** [comment]
The selected clock+L2 setting will be enforced for all games/titles (on N3DS) no matter what. Change or disable the setting according to your needs.
