### ISSUE TITLE
Reboot patches broken on Safehax

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#310]
Extra memory games will not work when launching luma3ds as a payload with Safehax.

**Comment by Margen67** [comment]
Why wouldn't you just install A9LH?

**Comment by ghost** [comment]
> Why wouldn't you just install A9LH?

Because I'm a safehax peasant ;p

Really, I'm asking on the behalf of others who are scared of attempting any risk of bricking.

**Comment by Margen67** [comment]
Tell them to stop being paranoid.
Staying on 11.2 puts you at risk of updating SysNAND without any form of protection.

**Comment by Mrrraou** [comment]
"lol why firmlaunch no work when i use firmlaunchhax" blah blah blah
you need to change the payload's path and stuff. like you'd do on a k9lh setup.

**Comment by ghost** [comment]
> "lol why firmlaunch no work when i use firmlaunchhax" blah blah blah
you need to change the payload's path and stuff. like you'd do on a k9lh setup.

Ok, I've been dressed down by the Black Cat. That's the fat lady singing for my issue. Closed. :-)
