### ISSUE TITLE
Failed to mount CTRNAND

### ISSUE THREAD

**Issue by MrWiik** [LumaTeam/Luma3DS#311]
Well im trying to get a9hl and luma 3ds on 11.2.35E with safehax and when i start the 3ds i get failed to mount ctrnand

**Comment by admiralkikan** [comment]
If you were using Phailects guide during the process it tells you to proceed to the next step if you get that error.

**Comment by travjmaggs** [comment]
What about after everything? I have everything done but need to go back into Luma settings to edit something, will I get the failed to mount CTRLNAND again? Every time? If so, THEN how would i get out of it? Or should it not say the error after? Any advice please!

**Comment by admiralkikan** [comment]
You shouldn't be getting that error at all except that one time. I have no idea what you did.  You could always start over.

**Comment by travjmaggs** [comment]
Thank you, I was just scared to go into those settings again, but it worked fine.

**Comment by admiralkikan** [comment]
No more issues? Ctrnand fail to install doesn't pop up anymore?

**Comment by travjmaggs** [comment]
Nope have used it twice with no problem, thanks.
