### ISSUE TITLE
Config non-save

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#312]
When I change something in the config menu, hit start (save), then immediately go to the payload menu, whatever I changed is not saved after boot to home menu or launching any payload.

**Comment by urherenow** [comment]
Did you save settings to nand at some point and now saving with SD inserted?

**Comment by ghost** [comment]
Never.

**Comment by TuxSH** [comment]
Can't reproduce

**Comment by Mrrraou** [comment]
had the issue when chainloading to another version of luma3ds, so doesn't seem to be related to different luma versions it seems

**Comment by ghost** [comment]
@TuxSH Bug is still present on latest commit.

Exactly how to trigger: Boot 3ds while holding select, change something in config menu, tap Start briefly, then immediately hold Start. This will bring up the payload menu of course. Do whatever you want then come back to the Config menu and all changes will be reverted.

**Comment by IcySon55** [comment]
I can confirm that this is the case. I ran into it a few times while installing A9LH on a few systems.
It's exactly as @idgrepthat described.

I install A9LH then shutdown, boot into Luma settings, tap start, then quickly hold start to launch Hourglass and restore the sysnand backup. Reboot, and I'm greeted with the Luma settings again.

**Comment by AuroraWright** [comment]
Fixed
