### ISSUE TITLE
top Splash screen not loading

### ISSUE THREAD

**Issue by fennectech** [LumaTeam/Luma3DS#318]
the file /luma/splash.bin is not being put on the top screen   only the bottom splash works    top is simply blank

**Comment by Spurned** [comment]
Are you sure the dimensions are correct? For the top screen, it should be 400px horizontal and 240px vertical.

**Comment by fennectech** [comment]
How do i check the dimensions of a .bin file?  i downloaded precreated one

**Comment by fennectech** [comment]
ill upload my bin file 
[splash.zip](https://github.com/AuroraWright/Luma3DS/files/692514/splash.zip)
  This is the mac os7 theme  i want to use   the bottom one works  but top does not

**Comment by fennectech** [comment]
if you could return it to a .png i can fix it myself   but im unsure how :/

**Comment by fennectech** [comment]
Well i cropped the preview and got it to work  :D   will close this
