### ISSUE TITLE
Allow system transfer to and from all 3DS/2DS/New/Old systems

### ISSUE THREAD

**Issue by Margen67** [LumaTeam/Luma3DS#319]
Normally you can't system transfer to an Old/2DS from an N3DS etc but a patch could make it possible.
Alternatively support could be added for O3DS firmware on N3DS.

**Comment by urherenow** [comment]
Transfers can be done manually, if you really wanted to. Only troublesome part is the NNID. That takes a phone call to fix server-side.

No you can't swap firmwares. The hardware is different. This is how people were semi-bricking 2DS models in the first place (no slider to get through the setup). Wouldn't you be crippling the N3DS anyway? O3DS has less memory and no clock boost.
