### ISSUE TITLE
Splash screen too late

### ISSUE THREAD

**Issue by CecilFF4** [LumaTeam/Luma3DS#32]
Re: 5.0: The splash screen occurs after one would need to hit a key to load a payload, instead of before, like BootCTR. It's enough of an annoyance that I'm reverting to the last version of the CFW (I've had numerous payload failures because I didn't hit the key in time). There also doesn't seem to be a way to configure the splash delay.

**Comment by AuroraWright** [comment]
1) I haven't changed the order in 5.0 (and it can be clearly seen in the source).
2) It's by design, because (to me) having the splash screen before a different payload is annoying. There's not to "press the key in time", just hold it pressed before pressing power :)
