### ISSUE TITLE
Change 'select' button to launch config

### ISSUE THREAD

**Issue by weirdal3333** [LumaTeam/Luma3DS#322]
A huge issue for the o3DS is that the select button under the sticker is really hard to press. I've seen people with holes and a toothpick to press the button.

Is there any way that we can customize which button is mapped to the Luma Config screen?

**Comment by weirdal3333** [comment]
I was thinking that it could work like menuhax, where you enter the button combo and tap the screen.

**Comment by weirdal3333** [comment]
Or it could be in /luma/payloads/up_luma3ds.bin

**Comment by BigBrainAFK** [comment]
i had 0 issues pressing select on all of my o3ds systems. (4 in total)

**Comment by weirdal3333** [comment]
I still think it would be a good feature for when they eventually wear out. Or if you don't want to press select, and the up button is easier to hold. I don't think it would be that hard to make the arm9loaderhax reference something in the config file instead.

**Comment by urherenow** [comment]
" don't think it would be that hard to make the arm9loaderhax reference something in the config file instead."

No offence, but why dob't you just do it then? This is open source. You can freely grab the source here and/or fork it and make whatever changes you want.

**Comment by weirdal3333** [comment]
I guess I can try, but I have no clue how this stuff works... AuroraWright implemented big changes that seemed more complicated than this, so I didn't think that it would be too hard for them to do this too. 

I thought that maybe part of the menuhax menu could be used in it, but maybe it has to be written from scratch.

Why is the select button used (and not another button) anyways?

**Comment by Shadow322** [comment]
Because the Select button is the best for this task

**Comment by urherenow** [comment]
You should close this because it's not an issue and github isn't a support forum. You can get help  in thegbatemp forums. Using a config file for what you're asking is not even necesarry. You can simply change the button used by changing a single number in the source, and the change will be permanent for your build.

**Comment by weirdal3333** [comment]
The source actually looks really easy to modify.
All of the code that I would need to use is already in there... I'm going to make a fork that does this!

I'm going to solve this myself. Also, it's going to function the same if you don't do anything.

Closing because it's easy, not because it's solved.
