### ISSUE TITLE
Failed to mount CTRNAND; Can't access hourglass9/decrytp9WIP only shutdown

### ISSUE THREAD

**Issue by huygreat1996** [LumaTeam/Luma3DS#324]
Just like the title, i cant do anything except access luma setting, press start and it happen, try to restore sysNAND through hourglass but i neither can access it nor decrypt9WIP. Help pls!!!
P/s: i've already tried to re-make luma folder and run hourglass9 as armloaderhax... nothing happen. I think for some reason it cant boot the payloads' files

**Comment by weirdal3333** [comment]
So, your directory structure looks like this

/
  luma/
             payloads/
                               x_hourglass9.bin
                               y_decrypt9.bin
  arm9loaderhax.bin
  ..... Everything else 

And you only hold x or y to boot into hourglass9 or decrypt9, respectively.
Also, check out the closed issues.

**Comment by weirdal3333** [comment]
My bad, I thought the spaces would show up

/payloads/x_hourglass9.bin
/payloads/y_decrypt9.bin
/arm9loaderhax.bin

**Comment by huygreat1996** [comment]
Yeah the structure is like that. What do you mean when you said "you only hold" there is another method? Because i tried by pressing X or select or up + power (i named those buttons)

**Comment by weirdal3333** [comment]
maybe download new payloads? Also, I forgot to make it /luma/payloads/x_hou... Etc.

**Comment by piratesephiroth** [comment]
shouldn't it be luma/payloads?

**Comment by weirdal3333** [comment]
Yes, exactly. Also, you should be following the guide at http://3ds.guide/ and asking on gbatemp about your problem...

**Comment by huygreat1996** [comment]
@weirdal3333  Already tried changing payloads yet no help.
@piratesphiroth It wont matter friend, i tried put the payloads folder on root and in luma folder, my n3ds just cant boot those .bin files

**Comment by huygreat1996** [comment]
@weirdal3333 Already done... there are some guys have this problem too
https://gbatemp.net/threads/a9lh-installation-failed-to-mount-ctrnand.452037/page-3

**Comment by weirdal3333** [comment]
You have to configure Luma and press start first. Then you can use the payloads.

**Comment by weirdal3333** [comment]
Also I read that thread, and if you can boot into Luma (and have arm9loaderhax already) you can use safemode and do it over again.

**Comment by huygreat1996** [comment]
@weirdal3333 Done mate, of course i config it then i load the payloads... Config => start => Failed to mount CRTAND / press any button to shutdown => start + power => press any button to shutdown / x +power => same thing. Recovery mode cant access: A + L + R + Up + power and it just show that screen again

**Comment by maki-chan** [comment]
Failed to mount CTRNAND happened on my New 3DS because Luma3DS cannot use the system at version 2.1.0 after ctrtransfer. You have to restore your NANDmin.bin backup or use the 9.2.0 ctrtransfer files to restore your system to a newer version. All of that is mentioned in the guide at https://3ds.guide, though.

**Comment by MelonGx** [comment]
Why asking questions but not reporting Luma issues here?
This is not a place for FAQ.
Go to the GBATEMP thread please.

**Comment by Raiyamanassa** [comment]
heyy huygreat1996! what have you done to go trougth this probleme?(I have the same message, I can't bypass it,the only thing I can do is go on luma6.6.6) because I search on many site and do a lots of things and i'm stuck with this prbleme, I don't know what to do S: are my n3ds xl 's broken?
