### ISSUE TITLE
copying content of original (16GB) card to upgraded (32 or 128 Gb) card black screen

### ISSUE THREAD

**Issue by pcs3rd** [LumaTeam/Luma3DS#325]

**Comment by pcs3rd** [comment]
luma3ds + a9lh (sysnand)
because of current personal issues, I am not able to keep at least 4 GB of space available on my 16GB card, so, I tried copying it to both a 32GB card and a 128GB card, both I tried formatting with godmode9 in both 32k and 64k clusters, and eventually "zeroed the sdcard" using windows and also linux. no matter what, I have not gotten my O3ds to boot from any sdcard other than the original 16GB (anything else, the blue power light just stays on, but there is no sign that the ds is actually booting from a9lh.bin (the screen lcd stays off, and I cannot boot into any of the payloads), and I am just copying the files from the working card to a larger FAT32 ones, but again, all I get is a black screen, not even the wireless status light on the 3ds slider light.)

**Comment by urherenow** [comment]
This isn't a help forum. Ask on irc or gbatemp.

**Comment by weirdal3333** [comment]
It might be because you need the 'arm9loaderhax.bin' and not a 'a9lh.bin'
Do yourself a favor and follow the tutorial on http://3ds.guide/ again.

Basically, you copy the 'arm9loaderhax.bin' (the one that works) to the CTR NAND and it will boot without an SD card.

**Comment by weirdal3333** [comment]
Yea... I think the guide should be pinned at the top or something, so that there are less 'noob panics'

**Comment by pcs3rd** [comment]
`I aready went to gbatemp, for a entire 2 days, everything recomended did NOT work. I am considering this a problem because everyone claims trhat I just format fat32 and copy everythging over, I have checked cluster size, format, partition markings, primary partitions, and I wouldn't be here if gbatemp users help solve the problem.

**Comment by weirdal3333** [comment]
arm9loaderhax.bin has to be from the releases. Maybe it got corrupted while copying? Copy the new one and hold select while booting.

**Comment by pcs3rd** [comment]
could I have a direct download please? using chromium on a raspi is a pain in the a55

**Comment by weirdal3333** [comment]
It has to be a MS-DOS partition table btw, not gpt...

Suggestion to AuroraWright: implement gpt partition table support for the 3DS.
Imagine.... A 2 terrabyte SD card!

**Comment by pcs3rd** [comment]
it is.

**Comment by pcs3rd** [comment]
i am in godmode9 @tm, so I can jkust copy the a9lh bin file to ctr nand?(arm9loaderhax.bin)

**Comment by weirdal3333** [comment]
Umm... https://github.com/AuroraWright/Luma3DS/releases/ 
You can find a release on your phone and copy the URL/link address of the download...

Why isn't this common knowledge?!?!?!

**Comment by pcs3rd** [comment]
but I only have access to a raspi right now, I do not have a non-brewmp phone

**Comment by weirdal3333** [comment]
Come back later after you've formatted the new SD card with a fat32 msdos type partition table and finished with the guide.

**Comment by pcs3rd** [comment]
*I'min western PA*... it is going on 10. I am not exactly able to just boot up a windows laptop atm

**Comment by pcs3rd** [comment]
but again, I am confirming that I can just copy my a9lh.bin file to the root of my ctrl nand

**Comment by weirdal3333** [comment]
Nope, it's the arm9loaderhax.bin file from the Luma 7z file.
 But you should follow the guide first, as it explains why you are doing this.

**Comment by pcs3rd** [comment]
both a9lh files are the same size, I have tried this on 2 different machines on 2 different windows boxes an d2 diferent linux boxes. It isn't just a coincidence that the only card that continues to work no matter the enviroment is the original. when I say a9lh.bin, I am referring to arm9loaderhax.bin!

**Comment by pcs3rd** [comment]
look. I understand how easy it is to make a electronic (cup) coaster/paperwight  from playing with tate. the last thing I need to be doing is explaining why I have bricked a 3ds.

**Comment by pcs3rd** [comment]
*seems to be working booting ctrnand. I will try to update the luma3ds cfw on the 32gb card will be back if need further help, the guys over @ gbatemp haven't helped me as much as I, the lost little idiotic noob am. Thank you? ( for now)
EDIT: I will have to go to gbatemp and close my thread, there was also antother little lost idiotic noob needing help with my same problem, I will make sure to mention this issue thread on github to make sure I am not "cheating" you

**Comment by pcs3rd** [comment]
i am also assuming I can safely run luma3ds updater safley, correct

**Comment by weirdal3333** [comment]
An excerpt from the http://3ds.guide/ front page

> Your SD card should be MBR, not GPT (the SD card that comes with the device will be MBR by default).
If you need to format a brand new SD card, you can use guiformat and set to an Allocation Unit Size of 32K.

So, don't forget about changing the PARTITION TABLE to MBR (or msdos if using gparted). Then format the partition in the MBR partition table as Fat32 with an allocation unit size of 32K.

**Comment by weirdal3333** [comment]
I think that it only works when you have a functional SD card. If the SD card works in the 3ds, then go ahead! The CTR NAND arm9loaderhax is for emergencies only, so fix the SD card. Also, what system menu version are you?

**Comment by urherenow** [comment]
@weirdal3333 um... Fat32 actually can handle 2TB as it is. That's the maximum though.

**Comment by weirdal3333** [comment]
Oh, well... How big can the largest gpt partition hold? Imagine that instead!

Also if gpt partitions were supported... We would have less of these threads.

**Comment by tlhv** [comment]
So I'm new to all the 3ds CFW and I installed everything step by step off that guide. I have everything working perfect but now I want to upgrade my 16gb card to a 64gb card. Can I just format my 64gb to Fat32 and transfer everything over from the original 16gb to the new 64gb or is there a specific back up and restore process I have to follow?

**Comment by Shadow322** [comment]
This isn't a help forum close this and go ask on gbatemp

**Comment by Margen67** [comment]
@Shadow322 This isn't tlhv's issue to close. @pcs3rd or a dev needs to close it.

**Comment by MelonGx** [comment]
To @pcs3rd and all noobs:
1) RTFW = Read the fucking wiki
2) This board is created for reporting Luma issues, but not asking questions.
If you want to ask question, GTTFGT = Go to the fucking GBATEMP thread.
