### ISSUE TITLE
can't download!

### ISSUE THREAD

**Issue by LettuceGoat** [LumaTeam/Luma3DS#326]
when i try to download the v6.6 file, it wont work and it says this 

"This XML file does not appear to have any style information associated with it. The document tree is shown below."

**Comment by Shadow322** [comment]
http://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip

**Comment by gijsgym** [comment]
Im having the same problem

**Comment by LettuceGoat** [comment]
thanks : )
