### ISSUE TITLE
RomFS redirection not working for some games

### ISSUE THREAD

**Issue by will0n** [LumaTeam/Luma3DS#328]
System got stuck in "Nintendo 3DS" loading screen every time. The games I've tried are Fire Emblem: Fates and Persona Q.
I can confirm that HANS works properly with the same romfs files. I've tried some other games like Demon Survivor and Ace Attorney: Spirit of Justice, the redirection work properly as well.
I'm using the nightly build from http://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip

**Comment by z5002800** [comment]
I'm having a similar issue where it crashes attempting to load a redirected romfs. If it helps, here's the crash dumps I got from enabling errdisp.
[dumps.zip](https://github.com/AuroraWright/Luma3DS/files/713552/dumps.zip)
This is Fire Emblem Fates: Birthright, and happens both with the game card and after dumping it to a CIA to try to run it that way instead. The earlier ones are from the cart, the last two are from the cia. Same romfs works with HANS.

**Comment by will0n** [comment]
@configchan oh you remind me of dumping the game to a CIA. CIA doesn't work either. BTW, how to get crash dumps?

**Comment by z5002800** [comment]
Enable errdisp in luma config.
