### ISSUE TITLE
Can't download the .7z file.

### ISSUE THREAD

**Issue by LiamLooper** [LumaTeam/Luma3DS#329]
Comes up with "This XML file does not appear to have any style information associated with it. The document tree is shown below."

**Comment by Shadow322** [comment]
https://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip

**Comment by Diegodam** [comment]
Thats true, and anothers files from the tutorials até offline too!

**Comment by urherenow** [comment]
Impossible. All files that matter from the only tutorial that matters, is in a collection of .torrent files.

**Comment by Diegodam** [comment]
Did you tried? https://github.com/AuroraWright/Luma3DS/releases/tag/v6.6

**Comment by Shadow322** [comment]
https://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip
