### ISSUE TITLE
Child Mode?

### ISSUE THREAD

**Issue by cspencer49519** [LumaTeam/Luma3DS#33]
This is more of a request than an issue. I recently hacked my 9 yr. old's 3ds for homebrew, and I would like to "secure" it as much as possible from her accidentally doing something she should not. I've done the obvious, remove FBI from H&S, removed all payloads etc. But ultimately for child use it would be awesome if the ability to hold anything at boot could be disabled. So maybe it's just a matter of disabling the ability to hold select at boot to reach the AuReiNand config?

**Comment by AuroraWright** [comment]
I'd like to only keep common features. The source is clearly commented, so for rare use cases you can very easily adapt it to your needs.
