### ISSUE TITLE
Luma Updater - Update Failed

### ISSUE THREAD

**Issue by Lesynn** [LumaTeam/Luma3DS#330]
Hi, hope this is the right section.

Was trying to Update Luma through the Luma Updater.
When i try to update to the normal Version im getting an Error.

"Update Failed"
Download Failed

Non-200 status code
Ret code: 404
FATAL
Could not get A9LH payload...

Is the prob on my side or servers side?

**Comment by THEDARKK** [comment]
Hi, this is normal ..

**Comment by donut3226** [comment]
I'm having the same issue.

**Comment by NexoCube** [comment]
I'm sorry for what happened here : https://github.com/AuroraWright/Luma3DS/issues/292#event-922250305

My github got hacked and my account got flagged, i'm so mad right now

**Comment by Masamune3210** [comment]
Server side, github is having issues

**Comment by james-d-elliott** [comment]
There are no new updates since 6.6 - when there are it will be fixed.

**Comment by Shadow322** [comment]
https://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip
