### ISSUE TITLE
Luma3dsv6.6.7z link not working

### ISSUE THREAD

**Issue by Darkhowl** [LumaTeam/Luma3DS#331]
The Luma3dsv6.6.7z isn't working for me, it takes me to a page that says "This XML file does not appear to have any style information associated with it. The document tree is shown below." Here's a picture of the issue. - http://imgur.com/a/sSFEw

**Comment by Darkhowl** [comment]
Really need this link to fix my 3ds with arm9loaderhax.bin, please fix the link asap!

**Comment by Shadow322** [comment]
https://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip

**Comment by Darkhowl** [comment]
Thank you!!

**Comment by zhi1ong** [comment]
https://www.mediafire.com/folder/11qzu54cam51w/Luma

Size = 217kb, same as author's release file.

**Comment by Shadow322** [comment]
https://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip

**Comment by TuxSH** [comment]
Should be fixed.

The problem is due to what happened last Thursday.

**Comment by Darkhowl** [comment]
The link works fine now, thanks everyone.

**Comment by AssisrMatheus** [comment]
past versions links aren't working, want to get 6.5 because 6.6 language emulation is not working

**Comment by Shadow322** [comment]
Does it work in latest nightly?

https://astronautlevel2.github.io/Luma3DS/builds/Luma-1eb18c17.zip

**Comment by AssisrMatheus** [comment]
@Shadow322 the language emulation? it still didn't using jap system with us bravely default using the latest nightly, the game is still in japanese because of the system language, even though it's an us game

**Comment by TuxSH** [comment]
Which game?

**Comment by AssisrMatheus** [comment]
I just said .-. .  American bravely default with language and region set manually to US still show japanese language in japanese 3ds because it has those files. I remember it working in past versions of luma but I updated to play MH online/fix that friend thing and then the language emulation stopped working.
