### ISSUE TITLE
Region/Language emulation and Code.bin patches broken with the latest commits

### ISSUE THREAD

**Issue by Shadowxp13** [LumaTeam/Luma3DS#335]
Hi, after using the hourly builds, me and four other people noticed that issue.
It has something to do with the last commits, because it works with the latest stable version (6.6)
Luma simply ignores it, acting like there was not any file in the locales folder and/or code_sections folder.
Some people also reported on the luma thread in GBATemp, but i think that posting here is better.

**Comment by FateForWindows** [comment]
I'm experiencing the same issue as well. I noticed it when trying to play Smash Neos with Saltysd.

**Comment by ghost** [comment]
Luma3DS nightly changed the Code Sections folder to titles/(titleidofgame)/code.bin

**Comment by Shadowxp13** [comment]
What about region emulation?
It is (or at least was) in luma/locales/TITLEID.txt

**Comment by Shadowxp13** [comment]
Got it, (luma/titles/titleid/locale.txt). anyway this should be added to the wiki

**Comment by ericjwg** [comment]
https://github.com/ericjwg/LumaLocaleSwitcher/releases

support 6.6 nightly
