### ISSUE TITLE
Enable game patching not working

### ISSUE THREAD

**Issue by Mephes** [LumaTeam/Luma3DS#344]
The Enable game patching option won't load code binaries anymore. Everything worked fine on the last version of Luma, so why isn't it working here?

**Comment by sora10pls** [comment]
make sure your directory is updated

example
`luma/titles/<title_id>/code.bin`

**Comment by thunderkai** [comment]
I am having this issue with Smash 3DS too....
Mods are not loading or the language emulation isn't working either

**Comment by sora10pls** [comment]
Smash 4 mods working just fine for me

examples (Smash 3DS USA)
`luma/titles/00040000000EDF00/code.bin`
`luma/titles/00040000000EDF00/locale.txt`

**Comment by thunderkai** [comment]
thank you!

**Comment by sora10pls** [comment]
I think this issue should be closed. We've basically just confirmed that the feature IS working as intended, people just need to update their directories.

**Comment by dothackjhe** [comment]
How does one get the "code.bin" for each game needed for game patching?

**Comment by Auscobe** [comment]
@dothackjhe 1: this isn't a support forum, even i'm still learning that, and GBATemp should be used for that. 2: try the Smash 3DS Hacking Discord

**Comment by dothackjhe** [comment]
@WubTheGame Never mind the question. I just learned that what I was asking for was the old method of making game patching work with Luma3DS. As with the latest release of Luma3DS (B9S), the feature runs with "boot.firm" from the root of the SD/micro-SD Card instead.
