### ISSUE TITLE
Issues Booting Up System With Latest Luma 3DS Commit

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#345]
Having some trouble powering on my system. For some reason, whether it's rebooting from Decrypt9 payload or just powering on, I get a black screen with only the blue LED.

**Comment by Margen67** [comment]
https://github.com/AuroraWright/Luma3DS/commit/ff4517e58337a83a26444905799e532e52d0d36a can boot up but randomly fails after saving config for me.

**Comment by usineur** [comment]
I confirm I encounter the same problem with latest revision. When rebooting from Decrypt9, I get black screen too.

**Comment by DarthVitrial** [comment]
Same issue here, sometimes I'll just get a black screen on booting. Even when I don't, booting seems to take longer than it did on the latest stable build.

**Comment by Shadowxp13** [comment]
Same thing here, when it happens, i have to make up to five reboots for a sucessful boot

**Comment by ghost** [comment]
Works for me just fine on latest commit. If anyone needs proof I can provide it.

Using an old3ds xl on 11.2EUR

**Comment by TuxSH** [comment]
Does 6e5987e3ca219a63e0ff0f897309df0e8c534046 work for you?

**Comment by Shadowxp13** [comment]
@TuxSH [`6e5987e`](https://github.com/AuroraWright/Luma3DS/commit/6e5987e3ca219a63e0ff0f897309df0e8c534046) Has the same issue for me (New 3DS XL A9LH Latest Firmware)
EDIT: It works after redownloading the payload with this commit

**Comment by TuxSH** [comment]
So it works, eh?

What about the latest commit I just pushed, then?

**Comment by Shadowxp13** [comment]
@TuxSH Your latest commit shows my splash screen and can enter the config and the chainloader,this didn't happen on the previous commits. But after the splash screen, chances of sucessfully booting into HOME MENU are random.

**Comment by TuxSH** [comment]
To be sure, 6e5987e3ca219a63e0ff0f897309df0e8c534046 and f03e232b90ed3e2e8545c5abb4c489ca4f1e0b7d work fine, do they?

**Comment by TuxSH** [comment]
And 61ecd9a61781e66005459917b511dc089041fc28 ?

**Comment by ghost** [comment]
yes they all work fine for me.

**Comment by Shadowxp13** [comment]
6e5987e and f03e232 works for me. But 61ecd9a doesn't.
Anything before January 19 works either.
It has something to do with the hide pin option

**Comment by TuxSH** [comment]
Hm, I need to determine the cause of the issue though I'll solve it

**Comment by Shadowxp13** [comment]
I'm making some tests when using a pin with the hide option enabled

**Comment by mshipman** [comment]
I was having this issue with all commits since f03e232 when using the unofficial hourlies at https://astronautlevel2.github.io/Luma3DS/

However, once I compiled Luma myself, I encountered absolutely no more problems on any recent commit. (I have a regular x86_64 Linux box and a Raspberry Pi set up to build automatically for testing, now)

I'm just wondering if this issue is a build environment problem, rather than an issue with a recent commit.

The latest commit **Works for Me (tm)**

**Comment by usineur** [comment]
@mshipman Are you using the devkitpro r46 or a previous one ?

**Comment by mshipman** [comment]
@usineur I'm using r46 on both systems (and the latest commit of libctru).

**Comment by usineur** [comment]
@mshipman ok just like me, I compiled it myself too, and it's not working properly... M'kay

**Comment by mshipman** [comment]
@usineur I'm trying to think of anything else I could've done differently. I did compile the latest makerom and armips from source, as well, rather than using any precompiled binaries for them.

**Comment by mshipman** [comment]
@usineur Update: I've been able to reproduce the failed boot on my N3DS XL on the latest commit. It's very rare, but there's definitely something going on... I feel like I'm in the Twilight Zone! It fails maybe once in dozens of boots (this is with a static splash screen shown before payloads).

Today's build: occasional failed boot ---
[Luma3DS_61ecd9a61781e66005459917b511dc089041fc28.zip](https://github.com/AuroraWright/Luma3DS/files/727556/Luma3DS_61ecd9a61781e66005459917b511dc089041fc28.zip)

Yesterday's build: I couldn't get it to hang on boot ---
[Luma3DS_6f56a9bfe95b2d2b543b51006290c95e04932c37.zip](https://github.com/AuroraWright/Luma3DS/files/727561/Luma3DS_6f56a9bfe95b2d2b543b51006290c95e04932c37.zip)

(I'd be curious to see if anyone else who is having the issue can successfully run my build of 6f56a9b without boot troubles)

**Comment by Shadowxp13** [comment]
The issue is very ramdomic, so it is kinda hard to say that there is no more issues.
I've compiled it myself ang got the same issue

**Comment by usineur** [comment]
@mshipman I also use self-compiled versions of makerom and armips (last revisions or almost). If I have time later that evening, I will give a try to your build of 6f56a9b

**Comment by TuxSH** [comment]
But https://github.com/AuroraWright/Luma3DS/commit/6e5987e3ca219a63e0ff0f897309df0e8c534046 reliabily boot when compiled from source by yourselves, right?

Also don't forget to enable the "ErrDisp" option, please.

**Comment by TuxSH** [comment]
Nvm, please test 6c5f6ac475931579f4f5432af963388b5603a8ee

**Comment by mshipman** [comment]
@TuxSH The new commit 6c5f6ac seems to be booting reliably so far. I will continue to test it for a while and update if I'm able to reproduce the issue from before.

**Comment by ghost** [comment]
No problems for me on any of the commits, but I compile it myself with the latest version of everything. Maybe it's people using prebuilt versions idk

**Comment by TuxSH** [comment]
Does 07101c053a468e0d028b134911383a5dff533bfd work too?

**Comment by usineur** [comment]
@TuxSH 07101c0 is ok for me. Rebooting from "Homebrew Launcher" and "Decrypt9" several times without issues

**Comment by Shadowxp13** [comment]
Rebooting into Windows for testing  07101c0

**Comment by ghost** [comment]
@TuxSH 07101c0 works fine for me, rebooting from Decrypt9 many times and no problems.

**Comment by Shadowxp13** [comment]
@TuxSH 07101c0 Works! 
ef2e008 works too.
