### ISSUE TITLE
black screen when using latest commit

### ISSUE THREAD

**Issue by Cysime** [LumaTeam/Luma3DS#346]
i got a problem that when i use the latest release, then i cannot launch Pokemon Sun(cart & cia)
it will work on the latest commit, but when i reboot my New3DSXL(USA),i will black screen when booting.
i FOLLOWED the FAQ about this issue, but it does't work.(NO "svcBreak" in the "loader",just a black screen)

**Comment by TheBigQuack** [comment]
same problem cannot boot into any menu reverting to .bak does nothing

**Comment by TheBigQuack** [comment]
guess we just have a bricked system lol

**Comment by Cysime** [comment]
@TheBigQuack i can boot my system by reverting the bakup, but cannot launch the Pokemon Sun... pretty strange

**Comment by TheBigQuack** [comment]
well i had a backup copy of the sd card and that fixed it

**Comment by urherenow** [comment]
Special cercumstanses? Region Emulation? I'm imagining a corrupt file caused by an open for reading and failing to close it again

**Comment by TheBigQuack** [comment]
once i recovered i tried update again worked once i manually powered off after update

**Comment by Pitel** [comment]
Duplicate of #345?

**Comment by TuxSH** [comment]
Duplicate
