### ISSUE TITLE
Region free fails with Maido Hanahuda

### ISSUE THREAD

**Issue by gingerbeardman** [LumaTeam/Luma3DS#350]
When launching this game it hangs on the 3DS "red waves" screen.
I have to load it through Hans to play it. 

3 other Japanese eShop games I have run just fine on the same setup.

Game is Japanese eShop only. 
Listed as Maido Hanahuda
I call it Maido Hanafuda (毎度 花札)

https://m.youtube.com/watch?v=T729jUO-4EI (not a video of the bug, just of the game)

**Comment by basvijfwinkel** [comment]
Have you tried adding a Japanese settings file to the 'locales' folder? 
I believe you need to add something like 'JPN JP' and name the file the same as the game id.
Also do check that the region-free option is disabled by default.

**Comment by gingerbeardman** [comment]
Region free works for all my other non-PAL games (only 4 in total).
Region free is enabled in Luma settings.

I've tried 00040000000B6700.txt containing "JPN JP" (without quotes) in the /luma/locales folder ...and it's still not launching.

**Comment by Slashin-it-up** [comment]
use luma locales cia

**Comment by gingerbeardman** [comment]
@HugaShire can you provide a link? Not sure what CIA your referring to? 

I used LumaLocaleSwitcher to setup the locales file but the game still doesn't run.

**Comment by MelonGx** [comment]
/luma/locales/00040000000B6700.txt ONLY WORK FOR 6.6 release and earlier.

If you're using NIGHTLY then please use /luma/titles/00040000000B6700/locale.txt.

Don't trust LumaLocaleSwitcher but do the manual conversion.

Don't forget enabling "Enable game patching".

**Comment by ericjwg** [comment]
https://github.com/ericjwg/LumaLocaleSwitcher/releases

**Comment by Margen67** [comment]
@gingerbeardman Has this issue been solved?

**Comment by gingerbeardman** [comment]
@Margen67 I use the binary available above from @ericjwg 

so, an unofficial solution

**Comment by Margen67** [comment]
ericjwg's fork is but the paths it uses are not. Luma nightly changed the paths so this is no longer a Luma issue, only a LocaleSwitcher one.

**Comment by gingerbeardman** [comment]
@Margen67 then you know more than I do about whether it is fixed or not, sorry

**Comment by gingerbeardman** [comment]
Just got around to testing this again, and the game will still not boot

I am using `/luma/titles/00040000000B6700/locale.txt` with contents `JPN JP`

patching is on in Luma (v8 with boot9strap)

any ideas?

to add to the situation, HANS seems to be have been discontinued?

**Comment by gingerbeardman** [comment]
OK, this game will only run on the latest Luma+B9S setup with the following New 3DS CPU settings:

Off= YES
Clock = YES
L2 = NO
Clock+L2 = NO

Thankful I have found a solution!

I have no idea how HANS was able to launch with CPU speed settings and region free.
