### ISSUE TITLE
[Suggestion] message if no payloads folder 

### ISSUE THREAD

**Issue by quantumcat1** [LumaTeam/Luma3DS#351]
There have been a bunch of people confused why their payloads won't work and it turns out to be because they spelled "payloads" incorrectly. 

Could the config menu have a message that appears if it can't find a payloads folder, or, have it create a payloads folder if it doesn't find one - then people will probably work out that their folder name is spelled incorrectly if another folder keeps appearing.

**Comment by TuxSH** [comment]
It creates it already
