### ISSUE TITLE
New3DS HardBrick? (Black screen/shutdown)

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#354]
3DS Model : New3DS
3DS SysVer : 11.2E
3DS CFW : Luma3DS
3DS CfwVer : latest commit build

Hello , my 3DS won't boot with and without SD Card (i have installed A9LH to CTRNAND using plai's guide) . That's a new problem . I guess the problem come from the SD Card  but i re-formatted my SD Card to MBR/FAT32 and the problem is always here.

(**EDIT** :Tried with another SD Card , same problem)

I tried these A9LH payloads : 

- Luma 3DS 6.6

- Luma 3DS automatic last commit build

- Decrypt9WIP

Black screen in any case .
I can't boot Luma3DS config menu / Ctrboot menu
I can't boot Recovery Mode so i think it's an hard-brick. I will buy/made an hardmod :(

**Comment by Margen67** [comment]
What did you do before it bricked?

**Comment by jcmejia** [comment]
No haven't done it before I only have 2 n3ds one on 9.2 and the other at
latest firmware so yeah I only have one I can mod I just don't want to risk
it

**Comment by jcmejia** [comment]
But I do have another question I was told if my SD card has a certain
partion table it can prevent the random bricks when installing a9lh

**Comment by ghost** [comment]
@Margen67 

Absolutely nothing .
That's pretty weird

**Comment by GizmoTheGreen** [comment]
not sure if it's related but I updated my n3ds's to 11.3 and they worked just fine with multiple reboots then suddenly they stopped booting(with black screen)

removing firm.bin in luma folder fixed it (was left over from when you needed it to run ntr) also worth trying is removing your luma config file?

**Comment by ghost** [comment]
I will try this . thanks

**Comment by Gildedboy** [comment]
try to change the dev features in luma configuration menu from "off" to "errdisp", if is a black screen error it will tell the type of error

**Comment by ghost** [comment]
@Glidedboy

I can't access Luma configuration menu

**Comment by Margen67** [comment]
If you have the SD card inserted but there's no payload (arm9loaderhax.bin) on it does the 3DS turn off?

**Comment by ghost** [comment]
@Margen67 yes
I haven't tried yet the solutions from @GizmoTheGreen

**Comment by ghost** [comment]
I once had the same problem, but I fixed it by removing everything in the "sd://luma" folder and then getting the latest "arm9loaderhax.bin". I then booted into the config menu and everything worked!

**Comment by ghost** [comment]
Solutions from @GizmoTheGreen and @infinity5 . _Je suis dans la merde_

**Comment by AuroraWright** [comment]
Luma can't cause bricks, try another SD card, if it fails it's a hardware failure of some kind

**Comment by ghost** [comment]
Yes , it's not related to Luma3DS but to the SD Card corruption.
I'll send back my 3DS to Nintendo.
Thx
