### ISSUE TITLE
Mods for Smash 3DS have long load times

### ISSUE THREAD

**Issue by paperclip3ds** [LumaTeam/Luma3DS#358]
So, recently, I updated my luma to 6.6, and upon loading up smash, my mods I have on it, (custom music and character skins) take incredibly long to load, so much so that I can't even play online because of it. I uploaded a video of the load times, https://www.youtube.com/watch?v=JBCN8Sxat5c, forgive the background audio, please

**Comment by ghost** [comment]
That's not a Luma problem that's a saltysd problem.
