### ISSUE TITLE
Would anyone please help me with the configurations?

### ISSUE THREAD

**Issue by Rowlet700** [LumaTeam/Luma3DS#359]
The hblauncher_loader works perfectly now after updating Luma3ds to the latest hourly, but after that out-of-region titles do not work at all. What options should I select to take care of the problem?
![kakaotalk_20170211_182030124](https://cloud.githubusercontent.com/assets/25684207/22852832/65ba9c96-f088-11e6-81bb-fccb2f27b9fb.jpg)

**Comment by zeroone1** [comment]
Language emulation is missing in the latest Luma patch.

**Comment by Rowlet700** [comment]
Yes, I just downgraded it and luckily, hblauncher_loader 1.3 was released. Thank you anyway:)
