### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by DeathWizard252** [LumaTeam/Luma3DS#361]
I have just started Luma3DS for the first time on 11.3.0.36 and then I boot it up, it comes to a black screen. I don't know how or why this is, but I followed the instructions.

**Comment by Margen67** [comment]
Do you have A9LH?

**Comment by DeathWizard252** [comment]
Yeah, I do.

**Comment by Margen67** [comment]
Can you get into the options menu by holding select while starting the 3DS?

**Comment by DeathWizard252** [comment]
No, I can't.

**Comment by Margen67** [comment]
Can you boot into recovery mode by holding A+R+L+Up(DPad) while turning on the 3DS?

**Comment by DeathWizard252** [comment]
No.

**Comment by Margen67** [comment]
What if you take out the SD card and cartridge(s)?

**Comment by DeathWizard252** [comment]
Can't access it at all because hombrew is based off of something on my SD card

**Comment by DeathWizard252** [comment]
Wait, nevermind. I thought you had to boot the 3ds, and you had to boot Luma. I'm still having trouble, as it says 'An error has occurred while loading the payload.'

**Comment by Margen67** [comment]
Can you take a picture of the error?
