### ISSUE TITLE
Can't enter configuration menu

### ISSUE THREAD

**Issue by Assaro** [LumaTeam/Luma3DS#363]
Hey, just installed Luma, but the configuration menu didn't show up. Any reasons? I also can't enter it by pushing select.

Edit:
Model: New 3Ds Xl
Firmware: 11.2.0-E35
Used this guide: http://3ds.guide

**Comment by Margen67** [comment]
Can you get into recovery mode by holding A+R+L+Up(DPad) while turning on the 3DS?

**Comment by Assaro** [comment]
Getting this:
[PANIC] Target payload not found:  /luma
Press any key to shutdown

**Comment by Margen67** [comment]
Can you take a picture?

**Comment by Assaro** [comment]
![20170215_174755](https://cloud.githubusercontent.com/assets/13085620/22984955/4f785b90-f3a7-11e6-8255-84b800757f94.jpg)
there you go

**Comment by Margen67** [comment]
Try turning off "use custom path"

**Comment by Assaro** [comment]
?How you do that?

Not considering myself a pro

**Comment by Margen67** [comment]
Hold select while turning on the 3DS.

If that doesn't work take out the SD card and delete the config and path.txt in the luma folder.

**Comment by Assaro** [comment]
![20170215_181400](https://cloud.githubusercontent.com/assets/13085620/22986099/c502c104-f3aa-11e6-8399-bf150a4aaf9b.jpg)
Now I am here
Whats next?

**Comment by Assaro** [comment]
Alright i was able to reset it back to where it started. I'll try again and see whether i will work

**Comment by Margen67** [comment]
Are you using menuhax or A9LH?

**Comment by Assaro** [comment]
Used A9LH. Have made an unknown mistake, old file, etc.
Did it again and it worked just fine. Loving it :)
