### ISSUE TITLE
O3DS/2DS Freezing

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#364]
Before writing this issue, I'd like to say that I am not the one having this issue. It is actually @Droople on GBATemp. He has been having issues with his Home Menu freezing after setting up A9LH and updating to 11.3, and it doesn't seem like there is any issues with his setup...
Here's a video:
https://youtu.be/lzMAIp4MKVw

Please post on this thread if you have any suggestions for him:
http://gbatemp.net/threads/2ds-frozen-when-quiting-from-some-apps-to-home-menu.461175/#post-7101316

Thank you for your time, and have a nice day!
P.S. His setup is:
2DS on 11.3 running Luma w/ A9LH v3
He has a class 10 SD card, and has his payload and files on the root of his SD...

**Comment by Margen67** [comment]
Are any memory mode changes being used?
Are dev patches enabled?
Are there any files like firmware.bin in /luma?

**Comment by droople** [comment]
No (what's this?),
No (what's this?), sorry I'm a noob in CFW.
No, only config.bin
All the steps followed and only followed from 3ds.guide

**Comment by FateForWindows** [comment]
Don't have this issue, try the latest hourly.

**Comment by ghost** [comment]
It seems like he fixed the issue after formatting.... Thanks to everyone who helped @Droople fix his 3DS!
