### ISSUE TITLE
Using Gateway linker

### ISSUE THREAD

**Issue by benoittachet** [LumaTeam/Luma3DS#365]
Hello,

My parents gave me a new 3DS XL last christmas, and I wanted to use my gateway linker on it. As it didn't have the good firmware, I installed Arm9LoaderHax and Luma3DS on it in order to operate a downgrade. Now, my 3DS has the correct firmware, but I get some issues when I want to use my linkers. I added a payload to load Gateway, but I can't get the menu, and I used to be able to use my DS linker, but not anymore...

Are there a way to remove the whole hack while keeping the actual firmware ?

Thank you !

**Comment by cheatfreak47** [comment]
Why would you bother with a Gateway when you already have a fully functional CFW? 
Just install your games as CIAs or use something like freeShop or whatever.

Gateway has a horrible reputation in the 3DS hacking community- so excuse my skepticism, but bear in mind that it's not unwarranted.

**Comment by benoittachet** [comment]
That's exactly what I don't want to do : install all as CIA. I don't want to have dozens of cards for that.
Furthermore, actually, it's more for the DS linker that I ask, as it doesn't work, it stucks on the "loading" screen. I had it a while ago, I solved it by installing TWL and AGB cias, but now, it doesn't work anymore.

**Comment by cheatfreak47** [comment]
First of all, you would only need "dozens of cards" if you are using tiny SD cards or you wanted to catalog every 3DS game ever made. 

and for that matter, wouldn't you _also_ need "dozens of cards" if you are using a Gateway? GW doesn't magically remove the requirement for SD storage space. It's the same stuff being used in a crappier way.

If by "DS linker" you mean the DS flashcart thing, then this guide's page should help fix that.
https://3ds.guide/troubleshooting

You probably just need to cleanly reinstall all the TWL stuff.

**Comment by benoittachet** [comment]
And then, are there a way to : 
1) convert .3ds files to .cia easily ?
2) Use saves obtained from gateway as ones for each game installed ?

If yes, I'll forget gateway. Else, I'll wait a bit.

**Comment by cheatfreak47** [comment]
1. You can do so with decrypt9 right on the 3DS if you want (though that's kind of a waste of time, when most games are avaliable in CIA format anyway)
2. You can do that by getting a 3DS into Gateway mode, and using JKSM to dump the saves from the Gateway one at a time, and then restoring them to the digital version later.
