### ISSUE TITLE
Region free not working on latest hourly

### ISSUE THREAD

**Issue by daothanhduy305** [LumaTeam/Luma3DS#367]
For example, the game I'm having trouble with is Nintendogs and cats: Golden retriever and friends (US).
My system is 11.3 (EUR), with latest luma hourly.
The game works with luma 6.6 stable release (that means I put the right txt file under luma/locales), but doesn't work with the latest hourly (I enabled the option game patching in luma already).

**Comment by Nyquis** [comment]
In the nightlies, the folder structure for patches, locales and romfs has changed. You can take a look at it in this [commit](https://github.com/AuroraWright/Luma3DS/commit/b5336c81cc82b6c5e8115249342beb5b065cdce9).

> "changed structure for game patches: language emulation txts now go to /luma/titles/titleid/locale.txt, code.bins go to /luma/titles/titleid/code.bin, RomFSes go to /luma/titles/titleid/romfs"

You may use the new luma _locale switcher rvn_ which knows the new strucutre. It can be downloaded from _TitleDB_ in FBI.

**Comment by daothanhduy305** [comment]
Confirmed! And thank you very much, and sorry for not looking into the commits/source at first hand
