### ISSUE TITLE
Screen init arm9loaderhax causes shutdown when starting GBA games.

### ISSUE THREAD

**Issue by SirRainbro** [LumaTeam/Luma3DS#368]
When screen init is enabled with arm9loaderhax_si.bin, booting a GBA VC causes the whole system to shutdown. Happens on both latest hourly and stable versions, with clean AGB_Firm installed. Changing the GBA boot screen setting also has no effect. Renaming the .bin back to arm9loaderhax.bin fixes this.

**Comment by Margen67** [comment]
Are you using emuNAND?

**Comment by SirRainbro** [comment]
No, 11.3 sysNAND. And something that I probably should have mentioned, it's a region changed o3DS. Japanese to European.

**Comment by Majickhat55** [comment]
I'm using a screen init version (along with Bootanim9) on Luma hourly and 11.3 and I have no problems playing GBA VC games. They load just fine.
