### ISSUE TITLE
Luma3DS won't compile

### ISSUE THREAD

**Issue by Froej** [LumaTeam/Luma3DS#370]
Hi so I installed devkitpro with devkitARM and a recent version of ctrulib and installed armips and makerom and added them to my path but when I run make, I have this error: http://prntscr.com/edpw54 help please :c

**Comment by potjesoep** [comment]
![image](https://cloud.githubusercontent.com/assets/14105847/23343812/7c947b68-fc71-11e6-890d-932ce29371d6.png)

**Comment by Froej** [comment]
It works now :D bin2c was missing and I had an outdatted version of makerom x)
