### ISSUE TITLE
fw update

### ISSUE THREAD

**Issue by pcs3rd** [LumaTeam/Luma3DS#371]
is it safe to update from 11.2.0 to the newest firmware on emunand

**Comment by Margen67** [comment]
Why are you using EmuNAND?

**Comment by pcs3rd** [comment]
I originally had sysnad on a16gb card and ran out of space and couldn't get it to work after copying to a 32 gb card. so I have one of each, a 16gb sysnand and a 32gb emunand. just normally use the bigger one because it works. pretty much the same configuration, I come most of the config files.

**Comment by pcs3rd** [comment]
* and I can backup all of my games

**Comment by tiduscrying** [comment]
It is safe. Just for future reference, feel free asking questions like this on /r/3DShack's sticky thread or on GBATemp! The issue tracker for Luma isn't really the place to ask, it's for reporting issues!

**Comment by Margen67** [comment]
If you're not already using A9LH you should follow this guide: https://3ds.guide/
