### ISSUE TITLE
Longer boot up on 5081439f

### ISSUE THREAD

**Issue by Nyquis** [LumaTeam/Luma3DS#372]
I currently have the impression that the boot up time on the latest nightly is visibly longer. What could it be linked with?

**Comment by Margen67** [comment]
What entrypoint are you using?

**Comment by Nyquis** [comment]
I am booting directly into sysnand. I have the a9lh + luma 3ds setup.

**Comment by Margen67** [comment]
If you have any firmware.bin on the SD card then delete it.

**Comment by Nyquis** [comment]
I do not have firmware.bin on my SD card.

Last well working firmware was b1b81c8. I'm still on 11.2.  The difference
in speed is of about 5-9 seconds after the splash screen. The splash screen
has been configured to load after payloads.

**Comment by Margen67** [comment]
Splash screens increase boot times.

**Comment by Nyquis** [comment]
I know. However on both b1b81c8 and 5081439f is have a splash screen. The same splash screen was configured to boot after payloads. As in my setup has not changed except for changing luma3ds build.

**Comment by mshipman** [comment]
I too have splash screens enabled, and for any commit newer than b1b81c87f28baa43023ee024358999ce12d170bf rebooting from within an arm9 payload causes the system to hang on a black screen. Even after removing the battery, the system completely refuses to boot (boots up to a black screen) until I remove the SD card and revert to an older stable commit. After a successful boot, I can then re-update to the latest commit of luma and the system works normally until I once again try to chainload something like Hourglass9 and press start to reboot.

When the system is stuck booting to a black screen after triggering this issue, solely deleting luma's config.dat does not resolve it. I thought maybe doing so would at least get me to the luma config screen again. Booting without the SD card inserted always works (luma stable is installed on the nand), but even after a successful boot without the SD, reinserting the SD causes the same black-screen issue (until I successfully boot from SD with an older luma commit).

I'm thinking maybe the boot problem from a month or two ago may have suffered some sort of regression in https://github.com/AuroraWright/Luma3DS/commit/706cd50f25c5a75cac322024c2b74ddc86390908 ? It's just a guess. There's always the possibility that my 3DS is possessed. XD

Lime Green N3DS XL - 11.3.0-36U - Luma + A9LH
(splash enabled before payload / Clock+L2 / booting SysNAND)

**Comment by Nyquis** [comment]
Seems like the 0eab9127 nightly has fixed longer booting times.
