### ISSUE TITLE
Code Sections usage causes game to crash 3DS

### ISSUE THREAD

**Issue by Masamune3210** [LumaTeam/Luma3DS#373]
I have used mystery machine patcher to patch the code.bin of the Pokemon games, but whenever I put the modified <titleid>.bin and enable language emulation and external code, the game tries to launch but gets to about half way through the nintendo animation, then crashes.

Dump files from crash available if needed

Running latest firmware, 6.6 Stable

**Comment by rocknard** [comment]
Try update to hourly build and try (with Luma Updater).

**Comment by Masamune3210** [comment]
Will do when I get a chance, and report back

**Comment by Masamune3210** [comment]
Nightly works like a charm after I figured out the new folder structure. Thanks!

**Comment by Masamune3210** [comment]
There needs to be at least a notice somewhere though that external code is broken in stable though
