### ISSUE TITLE
[Feature suggestion] Number crash dumps using RTC value.

### ISSUE THREAD

**Issue by sirocyl** [LumaTeam/Luma3DS#374]
This provides a sequential, time-based identifier that's easy to avoid collisions on.

It prevents the situation where you have a large number of files, especially dump files, on a low-performing SD, and the `findDumpFile()` loop takes a long time.

**Comment by TuxSH** [comment]
The problem is that IIRC the RTC doesn't contain the current date and time but an offset to what is stored on NAND. Currently there is no other way than using file names to sort the dumps per date of creation.

One could clean up their dump folders if they get too big.

**Comment by sirocyl** [comment]
No, that's the point. It doesn't have to correspond to an actual timestamp, it is only being used to apply a name to the file, in a way that is sequenced roughly based on time.

You don't need to know the actual time and date, since the offset itself is a timebase.

**Comment by TuxSH** [comment]
Meh.
