### ISSUE TITLE
I'm not able to access to SysNAND

### ISSUE THREAD

**Issue by CorJoestar** [LumaTeam/Luma3DS#375]
I tried to boot my New3DS by holding L button during the boot, but the screen remains completely black and nothing happens. I tried to set the autoboot in SysNAND, but when I try to boot my 3DS there is the same problem, but in this case when I boot by holding L button I boot EmuNAND successfully. 
I don't know what I have to do T^T

**Comment by Margen67** [comment]
What entrypoint are you using?

**Comment by CorJoestar** [comment]
Do you mean the Default EmuNAND location setting?
![photo_2017-03-08_19-49-11](https://cloud.githubusercontent.com/assets/26276467/23718609/6c449f6c-0438-11e7-9344-9af6552a0cae.jpg)

**Comment by Margen67** [comment]
Are you using A9LH?

**Comment by CorJoestar** [comment]
I'm not sure 'cause I've installed this CFW a long time ago, but I think so because in the root of my SD there are 2 files (arm9loaderhax.bin and arm9loaderhax.bin.bak)

**Comment by Margen67** [comment]
Luma requires all entrypoints (including menuhax, MSET, etc) to use arm9loaderhax.bin

**Comment by CorJoestar** [comment]
Mmm... so I have to install all of them, right?

**Comment by Margen67** [comment]
Is there an arm9loaderhax.bin on CTRNAND?

If there isn't, then what happens if you boot the 3DS without an SD card inserted?

**Comment by CorJoestar** [comment]
No, there isn't. When I try to Boot my 3DS it goes on SysNAND, but with the SD I can't do it :/

**Comment by Margen67** [comment]
Try reinserting the SD card then setting the home menu theme after turning the 3DS on without the SD card inside.

**Comment by CorJoestar** [comment]
Done. Now?

**Comment by Margen67** [comment]
If that fixed your problem now you should install A9LH by following this guide https://3ds.guide/

**Comment by CorJoestar** [comment]
Okay, thank you very much! O.O
The next step makes me able to boot Luma again? 
So I try ^-^

**Comment by CorJoestar** [comment]
Thank you so much! I solved all the problem! 😍

**Comment by Margen67** [comment]
No problem. Now you can close the issue since it's been solved.
