### ISSUE TITLE
-

### ISSUE THREAD

**Issue by parrotgeek1** [LumaTeam/Luma3DS#376]
###

**Comment by AuroraWright** [comment]
Already happens

**Comment by parrotgeek1** [comment]
oh, sorry, somehow didn't notice that part of the code.
can everything like retail cartridges work?

**Comment by parrotgeek1** [comment]
i thought it was reverted
https://github.com/AuroraWright/Luma3DS/commit/d7fd2f26c1ca6cf4d5b2d8c2076e6468acf80ff0
