### ISSUE TITLE
Mods on games take too long to load

### ISSUE THREAD

**Issue by paperclip3ds** [LumaTeam/Luma3DS#377]
I updated to luma 6.6 when updating my firmware to 11.3, and since then my modded smash 3ds has long load times, so bad that I cant even play online as i get disconnected before the match starts

**Comment by Shadow322** [comment]
6.6 is really old get latest nightly/hourly

**Comment by FateForWindows** [comment]
6.6 is outdated like Shadow322 said. You'll need to move the code.bin when transitioning to the new update.
