### ISSUE TITLE
Clash in new payloads

### ISSUE THREAD

**Issue by habbbe** [LumaTeam/Luma3DS#38]
Hi!
I just checked your latest release. I can't try it out right now, but from looking at the code, it seems that the new pattern used for allowing the old payloads to be recognized will also produce a clash between the payload "r" and "right", as r*.bin will also match right.bin. That's why I had the somewhat hard on the eyes solution in my initial commit that checked both the original name, and also the extended pattern with _NAME.

**Comment by evrardjp** [comment]
Hello. I should take the blame on this one.
Would that be fine if R1 would be loaded by r1 instead of only R? 
Or should we rollback? I'll be happy to send a PR in either way. 
R1 makes more sense to me, but may need more work in the docs.

**Comment by AuroraWright** [comment]
This won't happen because of the order. "right" is checked before "r".

**Comment by habbbe** [comment]
But the right is only checked if the right button is pressed, thus if the user holds down R, it would have already passed the right-condition by failing the (pressed & BUTTON_RIGHT), and it will load the right-payload anyway.

**Comment by AuroraWright** [comment]
OK, reverted back to 5.1. I suppose renaming one or few files won't be much work (I only removed the _ because I thought it was a quick way to also preserve compatibility, but I don't really care).
