### ISSUE TITLE
Luma3DS would not boot via MSET after making a transition from a formerly successful rxTools boot (via MSET)

### ISSUE THREAD

**Issue by dothackjhe** [LumaTeam/Luma3DS#380]
Can anyone show me a screenshot of their memory card's root folder contents after successfully transitioning from rxTools to Luma3DS via the MSET route? 

I need to know which files are meant for Luma3DS and which ones are left for rxTools which likely affects the smooth transition i.e. Luma3DS booting via MSET. 

Attached is a screenshot of my O3DS XL MMC's root folder.

Note: The original files meant for rxTools were placed in the "rxTools Backup" folder as seen on the screenshot and are thus not deleted.

Following on this [guide](https://gbatemp.net/threads/tutorial-updating-from-rxtools-to-luma3ds.427735/), I renamed "Luma3DS.dat" to "launcher.dat." Alternatively, I tried not renaming, but I'm still struggling making Luma3DS boot via MSET.

![o3ds xl mmc_1](https://cloud.githubusercontent.com/assets/18740174/23845467/4f743fd6-0803-11e7-9487-b82943183166.JPG)

**Comment by Margen67** [comment]
Follow this guide: https://3ds.guide/

**Comment by dothackjhe** [comment]
Can someone at least give an answer that does not point to that guide from the start? I know that guide exists. I just chose an easier route by asking for a certain solution here. 

Following the guide I posted, it said about only replacing files to make a transition from rxTools to Luma3DS. That does not seem to be the case here: or, at least, I think I'm doing something wrong hence it would not boot to Luma3DS via MSET. 

I know this method is obsolete but I still prefer this method for now over Menuhax or A9LH.

**Comment by Margen67** [comment]
>but I still prefer this method

Why?

**Comment by dothackjhe** [comment]
I'm taking baby steps towards Luma3DS. A9LH is probably for later. I must boot to Luma3DS and familiarize on it first.

**Comment by Margen67** [comment]
MSET is unsafe. It leaves you vulnerable to updates on sysNAND at boot and not to mention it's very inconvenient. You should immediately switch to A9LH.

**Comment by dothackjhe** [comment]
I can go for Luma3DS and A9LH even on sysnand 8.1.0-19U, right? No updating required?

**Comment by Margen67** [comment]
Yes.

**Comment by dothackjhe** [comment]
I'm leaving this thread open in the meantime while I go through reading and comprehending the steps required in installing Luma3DS as bootable via A9LH. I'm still eager to learn what makes Luma3DS not boot with my unit after going through the transition, following the MSET route.

**Comment by Margen67** [comment]
Luma doesn't support MSET on 4.x.

**Comment by dothackjhe** [comment]
I loaded Luma3DS.nds from my DS Flash Cart and saw two options with the ROP: patch for 4.X and 6.X. Given that my Sysnand is on 8.1.0-19U, I intuitively chose 6.X, yet it still did not fix the issue with Luma3DS not booting via MSET.

**Comment by Margen67** [comment]
You should just do the guide instead of wasting time with that.

**Comment by dothackjhe** [comment]
Noted.

**Comment by trbocode** [comment]
Assuming you didn't do it, try 4.X MSET

**Comment by Margen67** [comment]
>Assuming you didn't do it, try https://3ds.guide/

fixed

**Comment by jarupxx** [comment]
You use the Luma3DS.dat v6.3.1, Luma3DS will boot via the MSET route.

**Comment by dothackjhe** [comment]
@trbocode 

I'll try that again and see how it works from there. Right now I'm still struggling identifying which files must be removed from the micro-SD Card after trying to make a transition from rxTools.

**Comment by Margen67** [comment]
You don't need to remove any files after transitioning from rxTools except maybe any firmware.bin or other similar files. Otherwise it's just wasted SD card space.

**Comment by dothackjhe** [comment]
@Margen67 Yeah, I was actually referring to those files but just do not know yet which to remove specifically.

@Jarupxx Any idea where to get Luma3DS 6.31 when the original GitHub source no longer hosts it?

**Comment by Margen67** [comment]
@dothackjhe You shouldn't need to remove any files. Just follow this guide https://3ds.guide/

**Comment by dothackjhe** [comment]
@Margen67 I tried booting Luma3DS via MSET using a new micro-SD Card, it still would not boot even if I used Luma3DS.nds with my DS Flash Cart and patched the system for 6.X Luma3DS.

**Comment by dothackjhe** [comment]
[Update] I just successfully transitioned from rxTools to Luma3DS via A9LH route. Going through the process, I know better now which part of it risks anyone's handheld of bricking their device. 

This video tutorial saved me from that trouble: https://www.youtube.com/watch?v=DWq6bhSJ7Bo&t=1141s

**Comment by Margen67** [comment]
I'm glad that worked for you but you should just use https://3ds.guide/ video tutorials are outdated and more likely to brick you.
