### ISSUE TITLE
"Enable game patching" is gone from my options

### ISSUE THREAD

**Issue by Salamance73** [LumaTeam/Luma3DS#381]
![image](https://cloud.githubusercontent.com/assets/26430914/23941681/571b5d50-092f-11e7-8aac-fe40ddd3bc28.png)

This is not my first time booting and I'm on o3ds / 11.3 / luma v6.6.

**Comment by Salamance73** [comment]
Should also mention I'm on 11.3

**Comment by Margen67** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/Options-and-usage

**Comment by Salamance73** [comment]
So is it just gone or what?

**Comment by ghost** [comment]
You are using the stable version of luma. they do the same thing.

**Comment by ghost** [comment]
The 5th option is still game patching. Its just a different name.

**Comment by Salamance73** [comment]
I have the titles folder and everything, but my game is not getting patch no matter what I select in the luma menu.

**Comment by sora10pls** [comment]
You're using an older release of Luma3DS. The file structure you have on your SD Card matches those of the nightlies (`SD:/luma/titles/`), whereas the release you're showing off in the pic uses the directory from the latest stable release, v6.6 (`SD:/luma/code_sections`).

Update to latest nightly to fix, this is not an issue.

**Comment by Salamance73** [comment]
Thank you, I had a feeling I wasn't using the right release when I updated. This also may have fixed my problem with homebrew menu accessibility.
