### ISSUE TITLE
Region emulation not working on latest nightly

### ISSUE THREAD

**Issue by dogtopus** [LumaTeam/Luma3DS#382]
Setup: O3DS 11.3.0 RedNAND
Configuration: enabled game patching and exception handler, had flag files correctly set

Same setup (regionemu+errdisp patch+identical flag files) was working on v6.6 but not working on latest nightly (g5081439)

**Comment by svanheulen** [comment]
Not a bug. The location for those files has changed. See this commit:  b5336c81cc82b6c5e8115249342beb5b065cdce9

**Comment by dogtopus** [comment]
Okay, didn't notice that.
