### ISSUE TITLE
[HELP] Need older version of Luma3DS 

### ISSUE THREAD

**Issue by dothackjhe** [LumaTeam/Luma3DS#384]
So I'm having trouble booting my unit to Luma3DS via MSET using its latest build and was thinking that it was patched to be so. Where do I get Luma3DS 6.31 (or any particular version in general) when this repository no longer hosts it?

**Comment by Shadow322** [comment]
Your better off installing soundhax to boot Luma3DS via hbl

**Comment by Margen67** [comment]
https://3ds.guide/

**Comment by khang06** [comment]
just boot it from homebrew launcher, even that's better than mset...

**Comment by dothackjhe** [comment]
My unit is still on 8.1.0-19U. I've no plans of updating the sysnand firmware to 9.2 just to enable menuhax or soundhax with it. I've messed up one O3DS before so I'm quite wary with making significant changes with my existing units. Funny thing was, I was not even aware on which step(s) did I fail to follow properly back then so as to cause it. I just sold the same unit at a low price afterwards.

This is one reason I'm trying to stick to MSET.

@khang06 @Shadow322: I know the convenience with having to boot a CFW via homebrew launcher as what I do by default with ReiNand. However, like the aforementioned, I'm not yet fully given with the idea of having to update my unit to 9.2 just to enable any of those you mentioned.

**Comment by TuxSH** [comment]
Luma3DS should work with mset, you need both the .dat and arm9loaderhax.bin (in spite of the name, as the .dat will launch arm9loaderhax.bin)

**Comment by ghost** [comment]
https://3ds.guide/decrypt9-(browser)# Do this for goodness sake

**Comment by Margen67** [comment]
@pokecraft98 He's already installed A9LH. https://github.com/AuroraWright/Luma3DS/issues/380#issuecomment-287525156

**Comment by dothackjhe** [comment]
@TuxSH Tried that many times, even with a new micro-SD Card, it did not work. I dunno what's causing it not to. Thanks to that persistent error, I was committed to go for Luma3DS via A9LH route. Luckily, the process went very smoothly with me.

@pokecraft98 Going for the A9LH route, I did went with that step. Thanks for pointing that out.

**Comment by TuxSH** [comment]
Weird.

**Comment by dothackjhe** [comment]
@TuxSH True. The reason I even jumped to Luma3DS from rxTools via MSET route was because someone told me that the steps I needed for it only involved replacing files fitted for Luma3DS 6.6: sadly, it did not work with me.
