### ISSUE TITLE
Latest Nightly failed to boot Factory 9.9.0-26J's 1 firmware

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#385]
6.3.1 doesn't have this problem.
Need a fix for this on latest nightly.

**Comment by TuxSH** [comment]
I guess I'll remove the 11.3 patch, it's very likely the cause of the issue

**Comment by cheatfreak47** [comment]
@TuxSH The 11.3 patch does do it's job on 11.3, though, would it be possible to only load that patch if the latest firmware is present?

**Comment by TuxSH** [comment]
That's what is intended to be done but for some reason it doesn't (=> applying only on 11.3)?
