### ISSUE TITLE
[Suggestion] Thread in "Issues", mentioning all new "hourly" version feature

### ISSUE THREAD

**Issue by TLNiles** [LumaTeam/Luma3DS#386]
Might be a dumb thing to ask, but since "hourly" build is ever evolving and gets new version, isn't it would be nice to have pinned thread with new features written down in it?

**Comment by Margen67** [comment]
https://github.com/AuroraWright/Luma3DS/commits/master

**Comment by TLNiles** [comment]
That... doesn't really explains much to regular user.

**Comment by Margen67** [comment]
Regular users should just wait for stable releases and notes.

**Comment by TLNiles** [comment]
Seems... legit. Okay.
