### ISSUE TITLE
2x cpu mode option for new 3ds devices.

### ISSUE THREAD

**Issue by 133794m3r** [LumaTeam/Luma3DS#387]
I realize that this is not a huge thing for most people but enabling this option it could be combined with enable l2 only or something to keep stuff simple but I would like to do tests with it to see the power draw differences and see how it affects the loading of games. At current I can't see how it's writing to the registers to modify the clock multiplier or I'd try it myself.

**Comment by TuxSH** [comment]
Not sure this is worth it, and the patch for it would not be clean at all.

**Comment by MelonGx** [comment]
I just knew that Taiko no Tatsujin Don to Katsu no Jikuu Daibouken will be VERY LAGGED if DISABLE CLOCK+L2.
