### ISSUE TITLE
Romfs not working on nightlies

### ISSUE THREAD

**Issue by Nyquis** [LumaTeam/Luma3DS#388]
I have tested this on two nightlies, the 5081439f and 0eab9127 both do not seem to load even vanilla romfs. I extracted romfs with godmode9 then copied it to titleid/romfs , and deleted extension _.bin_.

Enable game patches is enabled.

Currently the game loads, gets past nintendo splashcreen and _loading data on sd_ only to proceed to a black screen with both blue yellow led turned on. My romfs file is 1.7gb.

Game tested on Fire Emblem Fates.

I have pinpointed that installation of CIAs produces the 331 error when installing software. Reverting to an older nightly solves this issue.

**Comment by CaptainSwag101** [comment]
I haven't experienced a 311 error, but I have been having issues getting external romfs patches working on the latest nightlies, so I can corroborate that part of the issue. I have been trying to load a patch for my cartridge of Pokemon X, as well as for an eShop version of Pokemon Omega Ruby.

**Comment by AuroraWright** [comment]
The buggy RomFS redir was replaced by LayeredFS
