### ISSUE TITLE
Error when Compiling Luma

### ISSUE THREAD

**Issue by Kyousak** [LumaTeam/Luma3DS#389]
When compiling i get this error

math -DREVISION=\"\" -DCOMMIT_HASH="0x"   -c -o build/patches.o source/patches.c
source/patches.c: In function 'implementSvcGetCFWInfo':
<command-line>:0:13: error: invalid suffix "x" on integer constant
source/patches.c:330:23: note: in expansion of macro 'COMMIT_HASH'
   info-> commitHash = COMMIT_HASH;
                       ^~~~~~~~~~~
make: *** [build/patches.o] Error 1

K:\Dev\Luma3DS>

**Comment by TuxSH** [comment]
Outdated makerom. Grab and rename one from https://github.com/Steveice10/buildtools/tree/master/3ds. 

You need git as well (maybe you could use msys to build...). Otherwise just edit the Makefile and replace the part with -DCOMMIT_HASH to -DCOMMIT_HASH="0".
