### ISSUE TITLE
Issue Compiling. 

### ISSUE THREAD

**Issue by Slashin-it-up** [LumaTeam/Luma3DS#390]
![screenshot 13](https://cloud.githubusercontent.com/assets/23299708/24583433/3f398374-16fe-11e7-9798-aa051844145d.png)

I have followed the instructions on the README.md

**Comment by Shadow322** [comment]
If u didn't modify the code just use lumaupdate via 3ds

**Comment by Slashin-it-up** [comment]
I tried that, when ever I use Lumaupdater, out of region games that uses locals, homebrew and more break.

**Comment by Shadow322** [comment]
The path has changed and I don't know what it is

**Comment by urherenow** [comment]
The directory name "Luma3ds-master" leads me to believe that you downloaded the source .zip file instead of cloning. Did you begin with this?

git clone --recursive https://github.com/AuroraWright/Luma3DS

Did you do the same with ctrulib and do a "make install"?

**Comment by Slashin-it-up** [comment]
@urherenow I did that. How can I do that?

**Comment by Slashin-it-up** [comment]
@urherenow I get fatal: unable to access 'https://github.com/AuroraWright/Luma3DS.git/': error setting certificate verify locations:
  CAfile: C:\Users\USER\AppData\Local\GitHub\PortableGit_f02737a78695063deace08e96d5042710d3e32db\mingw32/usr/ssl/certs/ca-bundle.crt
  CApath: none

**Comment by TuxSH** [comment]
That's a git/system configuration problem, not a Luma one (referring to your last msg)

Otherwise just edit the Makefile and replace the part with -DCOMMIT_HASH to -DCOMMIT_HASH="0".

**Comment by Slashin-it-up** [comment]
$(dir_build)/patches.o: CFLAGS += -DREVISION=\"$(revision)\" -DCOMMIT_HASH="0x$(commit)" That's what it has

**Comment by Slashin-it-up** [comment]
<command-line>:0:13: error: invalid suffix "x" on integer constant
source/patches.c:329:24: note: in expansion of macro 'COMMIT_HASH'
     info->commitHash = COMMIT_HASH;
                        ^~~~~~~~~~~
make: *** [build/patches.o] Error 1

C:\Users\Cheryl\Desktop\Luma3DS-master>

**Comment by TuxSH** [comment]
yeah replace "0x$(commit)" by "0" if you don't have a proper git install
