### ISSUE TITLE
Can't boot without SD with Luma in CTRNAND 

### ISSUE THREAD

**Issue by chronoss09** [LumaTeam/Luma3DS#392]
I can't launch Luma without SD card, I have the file "arm9loaderhax.bin" from Luma in SYSNAND CTRNAND but it can't boot :(, i use the last build...

**Comment by Margen67** [comment]
Are you sure you have the latest Luma nightly and newest arm9loaderhax version?

**Comment by chronoss09** [comment]
For Luma yes but i don't know for arm9loaderhax, i will check it...

**Comment by chronoss09** [comment]
Tested with latest Luma (28e6ad3) and latest arm9loaderhax ([4fc9ad8](https://github.com/AuroraWright/arm9loaderhax/commit/4fc9ad8d9a720d174f850f4c9b67d0594c3c280f)) : no boot :(

**Comment by Margen67** [comment]
Are you sure you're pasting arm9loaderhax.bin to the root of CTRNAND?

**Comment by chronoss09** [comment]
Yes, pasting with GodMod9. I used Luma 6.6 and the last in commint....

**Comment by Margen67** [comment]
Can you try using FBI to paste arm9loaderhax.bin?

**Comment by chronoss09** [comment]
Samething......

**Comment by Margen67** [comment]
Are you using a custom path?

**Comment by chronoss09** [comment]
No, I just copy Luma in CTRNAND, nothing else...

**Comment by Margen67** [comment]
Try deleting config.bin from the luma folder on the SD card.

**Comment by chronoss09** [comment]
I want booting without SD card and i think config.bin hasn't a problem because he is on my SD card :(

**Comment by luigoalma** [comment]
did you update a9lh?

**Comment by chronoss09** [comment]
A9lh or Luma ?

and how to update a9lh because i used the last release for [SafeA9LHInstaller ](https://github.com/AuroraWright/SafeA9LHInstaller/releases/latest)and [A9LH](https://github.com/AuroraWright/arm9loaderhax/releases/latest)

I test the same file on N3DS and it work fine, i don't know why it don't work on O3DS :(

**Comment by luigoalma** [comment]
well, if you want to be certain about it
https://3ds.guide/updating-a9lh

**Comment by chronoss09** [comment]
ok but i'm already up date because i have all of these files...

**Comment by MelonGx** [comment]
Both Data Input V3 and V4 support SD/MicroSD-less boot if Luma's arm9loaderhax.bin is in the root of CTRNAND.

Probably OP has not updated his A9LH to Data Input V3 or V4.
