### ISSUE TITLE
arm9loaderhax.bin missing

### ISSUE THREAD

**Issue by Chacolly** [LumaTeam/Luma3DS#393]
I can't find the **arm9loaderhax.bin** from the Luma3DS.7z and I'm stuck;;; Also neither going to the url http://2xrsa.3ds.guide freezes ;____;

**Comment by Margen67** [comment]
It's right there..
![orly](https://cloud.githubusercontent.com/assets/3462541/24830659/36bb5100-1c3f-11e7-8bd2-5607573f9f35.png)

**Comment by Chacolly** [comment]
JUST FOUND IT RIGHT NOOWW--Sorry and thank you so much! It's just my laptop having errors that's why I didn't see it ;; Ughh

**Comment by Margen67** [comment]
If your hard drive is faulty you should have it replaced.

**Comment by Chacolly** [comment]
Okay! Soon!! Thank you so much again ^^
