### ISSUE TITLE
I kinda-bricked my 3ds... PLEASE HELP

### ISSUE THREAD

**Issue by ArkhamK27** [LumaTeam/Luma3DS#394]
Hello 
I tried to follow the forum to repair my nds files on my 3ds
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting
But after choosing to initiate in "Enable loading external FIRMs and modules option" my 3ds gets a black screen
I tried several times and my 3ds still could boot without choosing the external firms option, but now, any way trying to start will give a black screen
If anyone has a solution, please

**Comment by sora10pls** [comment]
This isn't a support forum.
