### ISSUE TITLE
Luma3DS with MenuHax v3.2 wont boot after update

### ISSUE THREAD

**Issue by bliblablub231** [LumaTeam/Luma3DS#395]
Is this a known issue?

**Comment by guiscaranse** [comment]
Is it 11.4?

**Comment by Margen67** [comment]
https://3ds.guide/

**Comment by bliblablub231** [comment]
Got it. In case you update your Luma3DS you need to download the arm9loaderhax.bin and put it in the ROOT directory.

Step by Step tutorial:

https://github.com/AuroraWright/Luma3DS/wiki/Installation-and-upgrade
