### ISSUE TITLE
TWL and AGB not working on 11.4

### ISSUE THREAD

**Issue by noahc3** [LumaTeam/Luma3DS#396]
Launching DS titles or GBA VC titles causes the system to get stuck on a black screen on ~~both O3DS and~~ N3DS on 11.4. ~~Extended memory mode games work fine on O3DS, it's not the reboot causing the issue.~~

Update: AGB and TWL works on my O3DS, not mine and some others' N3DS'.

**Comment by Margen67** [comment]
Does this happen with the latest nightly or just v6.6?

**Comment by andot** [comment]
I have the same problem with luma3DS latest nightly version in N3DS on 11.4.

**Comment by Margen67** [comment]
Should be fixed by https://github.com/AuroraWright/Luma3DS/commit/71f49180c3a06a722b669895974ca87b478c01e2 (or newer)

**Comment by TuxSH** [comment]
Yeah, multiple people has reported this commit addresses the issue.
