### ISSUE TITLE
DS/DSi games still fail to load on 11.4 even after updating to the latest hourly build of luma 3ds

### ISSUE THREAD

**Issue by dissant** [LumaTeam/Luma3DS#399]
Even after updating to the latest hourly build(ad1dc51e) I still can't launch any DS/DSi games,because it gives me a black screen

**Comment by Margen67** [comment]
Did you try https://3ds.guide/troubleshooting

**Comment by dissant** [comment]
Yes,I did,forgot to say that

**Comment by Margen67** [comment]
What entrypoint are you using? Are you using an emuNAND?

**Comment by dissant** [comment]
No,I don't. I'm just trying to launch a game from the home menu

**Comment by dissant** [comment]
Fixed by updating to luma 7.0,thanks Aurora!
