### ISSUE TITLE
Possible to make LayeredFS load times any faster?

### ISSUE THREAD

**Issue by sora10pls** [LumaTeam/Luma3DS#402]
I only ask this because compared to SaltySD load times on a New 3DS, the new LayeredFS implementation makes loading games (mainly been trying Pokemon Sun/Moon) extremely slow, almost the same as, if not worse than an Old 3DS.

**Comment by AuroraWright** [comment]
No, the current approach is limited

**Comment by sora10pls** [comment]
Damn that's a shame. Thanks anyway, load times aren't THAT bad, and the implementation is awesome :)

**Comment by RinMaru** [comment]
> I only ask this because compared to SaltySD load times on a New 3DS, the new LayeredFS implementation makes loading games (mainly been trying Pokemon Sun/Moon) extremely slow, almost the same as, if not worse than an Old 3DS.

worse than old 3ds this is nds level slow. the more files you have the longer it takes
