### ISSUE TITLE
[REQUEST] Update issues layout

### ISSUE THREAD

**Issue by Jolty95** [LumaTeam/Luma3DS#404]
Just a reminder to update it :P

**Comment by Margen67** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-get-an-auto-shutdown-with-gbadsdsiware-games also needs to be updated

**Comment by ihaveamac** [comment]
@Margen67 what needs updating in this section?

**Comment by Margen67** [comment]
@ihaveamac This still needs to be fixed https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-get-an-auto-shutdown-with-gbadsdsiware-games

It should just be changed to https://3ds.guide/troubleshooting

**Comment by ihaveamac** [comment]
I'm not sure what in it needs fixing. 3DS Guide's Troubleshooting page doesn't cover agbfirm.

**Comment by Margen67** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-get-an-auto-shutdown-with-gbadsdsiware-games only covers TWL_FIRM.
Not TWL Version Data, DS Internet, DS Download Play, or Nintendo DS Cart Whitelist which also help solve TWL problems.

**Comment by ihaveamac** [comment]
a link could probably be added but it won't be entirely replaced with it

**Comment by Jolty95** [comment]
Now it's updated :P

Thansk @ihaveamac  :)
