### ISSUE TITLE
SMILE BASIC Crashes Loader

### ISSUE THREAD

**Issue by gudenau** [LumaTeam/Luma3DS#405]
When I launch SMILE BASIC v3.3.1 on FW 11.4.0-37U Loader calls svcBreak.

An exception occurred

Processor: ARM11 (core 1)
Exception type: prefetch abort (svcBreak)
Current process: loader

R0 00000001 R1 FFF9180C
R2 FFF90F70 R3 FFF9CF1C
R4 D9004587 R5 0FFFFF78
R6 140058C8 R7 00000001
R8 0FFFFEE8 R9 14005470
R10 00000D54 R11 00000001
R12 00000000 SP 0FFFFE20
LR 18001BC8 PC 140034E8
CPSR A0000010 FPEXC 00000000
You can find a dump in the following file:
dump/arm11/crash_dump00000020.dmp

Press an button to shutdown

**Comment by Slashin-it-up** [comment]
That is because 11.4 breaks Homebrew (if you have not updated payloads). This is a homebrew error not Luma3DS

**Comment by gudenau** [comment]
How is it a homebrew error? I am not attempting to use homebrew.

**Comment by Margen67** [comment]
What version of Luma are you using?

**Comment by gudenau** [comment]
7.0

**Comment by AuroraWright** [comment]
Do you have any game patching feature enabled for the title? LayeredFS, or locale.txt, or code.ips...?

**Comment by AuroraWright** [comment]
Can't reproduce, game works fine even with LayeredFS redirection and language emulation. You are probably running it on an old NAND/FIRM.
