### ISSUE TITLE
[Feature suggestion] Ctr-httpwn intergration

### ISSUE THREAD

**Issue by ZenithRogue** [LumaTeam/Luma3DS#406]
Would you be able to make it so you don't have to update for use with online, similar to that of Ctr-httpwn?

**Comment by phtom** [comment]
Agreed, it could have CTR-Httpwn integration!

**Comment by ZenithRogue** [comment]
Especially since some users are unable to get ctr-httpwn to funtion properly

**Comment by TuxSH** [comment]
For games it's already possible anyways, use 7.0

For eShop... oh well...
