### ISSUE TITLE
Booting Luma v7 through homebrew launcher

### ISSUE THREAD

**Issue by arubar0** [LumaTeam/Luma3DS#407]
Using the files provided inside the "hax" folder to boot Luma through menuhax/homebrew launcher leads to a black screen (you cannot even boot the config screen).

Using the files provided on v6.6 instead solves the problem though (boots luma v7 successfully).

More info about my setup:
o3ds EUR
Using menuhax ->homebrew launcher -> luma v7
Gateway emunand type on 11.4 (I think, the one emunand9 made by default in very old versions)
Sysnand on 9.2
Using 2.8 homebrew payload

**Comment by andamirorulez** [comment]
I have the same problem
N3ds, sysnand 9.2, menuhax
I use the 3dsx luma to direct boot
Black screen with luma 7
Works perfect if back to 6.6

**Comment by arubar0** [comment]
@andamirorulez Try using all the files you need from v6.6 and then replace only the arm9loaderhax.bin with the one provided on v7 and tell us if you're able to boot Luma v7

**Comment by Margen67** [comment]
https://3ds.guide/

**Comment by andamirorulez** [comment]
@arubar0 i gonna try that, copying only the arm9loaderhax.bin from v7
I think boot.3dsx from v7 is corrupt

@Margen67 can you tell me exactly where to read?

**Comment by AuroraWright** [comment]
[out.zip](https://github.com/AuroraWright/Luma3DS/files/924296/out.zip)
Does this work?
And no, not corrupted, but updating ctrulib leads to random cakebrah breakages

**Comment by Margen67** [comment]
@andamirorulez Click "Get Started"

**Comment by andamirorulez** [comment]
@Margen67 i use menuhax, not arm9
So that guide its not for me
That why i asked you where tu read in the guide

@AuroraWright i gonna try that later and feedback thanks!

**Comment by Margen67** [comment]
>i use menuhax, not arm9

Why?

**Comment by MelonGx** [comment]
@Margen67 For professional usages.

BTW, Luma3DS.dat after 6.3.1 is always unable to re-direct to arm9loaderhax.bin.
If anyone needs to use (1) Boot Managers for Menuhax or (2) MSET or (3) Spider, he/she should use 6.3.1's Luma3DS.dat instead of any later version's.

**Comment by SkittleDash** [comment]
I'm having the exact same problem. This really needs to be fixed. I was looking forward to its new features. ;-;

**Comment by Margen67** [comment]
@SkittleDash If you want to use the newest Luma without waiting for a fix for menuhax (which you shouldn't be using anyway) you can install A9LH https://3ds.guide/

**Comment by AuroraWright** [comment]
Could anyone test the files I posted?

**Comment by SkittleDash** [comment]
@AuroraWright Just tested. Still got a black screen.

**Comment by arubar0** [comment]
@AuroraWright Not working for me either

**Comment by SkittleDash** [comment]
@Margen67 I refuse to use A9LH because I just cannot be bothered to install it. I don't even care about boot time anyway. And I leave my sysNAND and emuNAND unlinked so my sysNAND will remain untouched.

**Comment by NightScript370** [comment]
@Margen67 No.

A9LH isn't the answer to their problem. That's a **workaround**. I don't care if it's a good workaround. Besides, if everyone here automatically made the jump to A9LH, then there won't be any testers for MenuHax, and Luma is trying to be "not limited to A9LH, AKA being available to multiple entrypoints". Also, I do like A9LH; Don't get me wrong. Except it isn't the answer to everything...

First, let's solve their problem, so we can have an official working release of 7.0 on HBL, and then you can suggest the A9LH route.

**Comment by MelonGx** [comment]
As what I said, Luma3DS.dat after 6.3.1 are all broken so everyone using CBM/Spider/MSET should use 6.3.1's Luma3DS.dat instead.
So how about trying old version's boot.3dsx?

**Comment by SkittleDash** [comment]
@MelonGx I can confirm that this worked. Thanks! ^_^

Using 6.6 boot.3dsx fixed the black screen.

**Comment by MelonGx** [comment]
@SkittleDash Good to hear that.

I still wonder what @AuroraWright has updated on boot.3dsx since 6.6 & Luma3DS.dat since 6.3.1 which cause those files nonfunctional.

**Comment by EightyVI** [comment]
@AuroraWright Not work for me. Black screen in emunand.

**Comment by pbanj** [comment]
@SkittleDash it should be noted that just because you have your nands unlinked doesn't mean your sysnand is safe. I've fixed a handful of systems that were using menuhax and an Emunand but somehow their sysnand ended up bricked. They were not in sysnand at the time, all of them were playing a game.

Not trying to scare you, just letting you know you're not as safe as you think.

**Comment by AuroraWright** [comment]
It is fixed in the latest nightlies

**Comment by andamirorulez** [comment]
@AuroraWright where can i download de nightlies? Are you talking about the releases?
Do you update the 7z file of v7??

**Comment by pbanj** [comment]
http://astronautlevel2.github.io/Luma3DS/
