### ISSUE TITLE
[REQUEST] LayeredFS support for System Titles

### ISSUE THREAD

**Issue by lex3a** [LumaTeam/Luma3DS#410]
Unfortunately,  LayeredFS does not work with system titles.  If it will work it can help with Home Menu modding,  for example.

**Comment by AuroraWright** [comment]
Some needed symbols can't be found with applets (like Home Menu) so it's not possible. Regular system apps are already supported

**Comment by Delphox** [comment]
Is NVer a regular system app? Cuz I tried redirecting its version.bin to a -37 one and it didn't seem to work...
