### ISSUE TITLE
Luma 7.0 can't enable region/language emulation

### ISSUE THREAD

**Issue by iKimz** [LumaTeam/Luma3DS#411]
I use N3DS LL and updated Luma3DS to v7.0. After finishing update I all of game that use language emulation don't work (It work correctly in v6.6).

**Comment by iKimz** [comment]
I found the problem

Language Emulation text files go in a different location now.
/luma/titles/<titleid>/locale.txt

still contains the same info.

**Comment by MelonGx** [comment]
@AuroraWright A Wiki update is required.
