### ISSUE TITLE
Can't find arm9loaderhax.bin

### ISSUE THREAD

**Issue by Anchony** [LumaTeam/Luma3DS#413]
I downloaded the Luma3DSv7.0.7z file but can't find arm9loaderhax.bin anywhere in it. Is it somewhere else or am I not looking close enough?

**Comment by Margen67** [comment]
![wut](https://cloud.githubusercontent.com/assets/3462541/25102947/71b5acec-236f-11e7-9a4f-2b0eb5b8092f.PNG)
