### ISSUE TITLE
Enabling Game Patching or Patching SVC Break Homebrew Launcher Apps

### ISSUE THREAD

**Issue by Piefactor** [LumaTeam/Luma3DS#414]
I am on Luma v7.0 on a N3DS 11.3U

If either of these options are enabled in the Luma Configuration menu, launching the homebrew launcher and selecting a homebrew application causes the system to hang and not load.  I can still relaunch the homebrew launcher by pressing L,R, down, and B, so it is not a hard freeze.

**Comment by AuroraWright** [comment]
you need to update your boot.3dsx
