### ISSUE TITLE
Outdated Wiki - Region/Language Emulation Path

### ISSUE THREAD

**Issue by evandixon** [LumaTeam/Luma3DS#417]
The [Options & Usage](https://github.com/AuroraWright/Luma3DS/wiki/Options-and-usage) page of the wiki currently does not detail how to use the region/language emulation on the latest stable release. In the past, the path for the locale file was `/luma/locales/<titleID>.txt`, but now it's `/luma/titles/<titleID>/locale.txt`. (It took me a bit to find out what the new path was, since I don't see it documented anywhere outside of [the code](https://github.com/AuroraWright/Luma3DS/blob/108e8a0cd408221d496ac47501338abd5c5327a4/injector/source/patcher.c#L458).)

It looks like there's other things on that page that might not apply to the latest version, but I can offer no specifics beyond the locale path.

**Comment by Margen67** [comment]
The issue template also needs to be updated.

**Comment by AceTrainer2712** [comment]
Does the emulation work with nothing else applied after the appropriate path change? Or is there anything else that needs to be changed?

**Comment by evandixon** [comment]
Game patching needs to be enabled (like before, but the option was renamed IIRC).

**Comment by AceTrainer2712** [comment]
Right, so I take it the archive patch referred to is the locale file?

**Comment by sora10pls** [comment]
@AceTrainer2712 No. "Enable game patching" applies to LayeredFS, Code Replacement, Locales, etc.

**Comment by dogtopus** [comment]
Few other things need to be updated on wiki too (e.g. the new chainloader)

**Comment by AceTrainer2712** [comment]
@sora10pls yeah, I figured, but Luma says that to make game patching work, you need to apply an "archive patch", and I'm not sure what that means.

**Comment by Margen67** [comment]
@TuxSH @AuroraWright

**Comment by Margen67** [comment]
#404

**Comment by yichof** [comment]
Hey guys, I think thre's still a problem even with the appropriate path change applied. I've followed the procedures described above and also enabled the game patching in Luma, and so far I've tried three different games (all US regions) on my JPN machine (N 3DSLL), and all of them stuck at the 3DS title loading screen permanently.

Could someone give me hand here? Thanks a lot!

**Comment by urherenow** [comment]
Are you sure you have the seeds for thise games?

**Comment by urherenow** [comment]
*those

**Comment by ihaveamac** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/Options-and-usage
