### ISSUE TITLE
layerfs problem

### ISSUE THREAD

**Issue by M-1-RLG** [LumaTeam/Luma3DS#418]
Does layerfs work with updates? if it does then acnl have problems

**Comment by AuroraWright** [comment]
The files in the update aren't redirected?

**Comment by M-1-RLG** [comment]
Nope

**Comment by AuroraWright** [comment]
What about the files not included in the update?

**Comment by M-1-RLG** [comment]
Yeah they load

**Comment by AuroraWright** [comment]
7.0.1 should work... the update ROMFS is mounted as patch:/
