### ISSUE TITLE
Region free download play won't work on luma v7.0 and v7.0.1

### ISSUE THREAD

**Issue by TheAmiiboCollector** [LumaTeam/Luma3DS#419]
I have a 3dsxl and an n3ds both US and a European 2ds, all CFW with a9lh and the latest luma nightly with system firmware 11.2 (lol was afraid to update to 11.3) anyways as the title says I can't use the region free download play with mk7 what do I do? Also, how do I switch from the nightly build of luma to the stable release?

**Comment by AdivonL** [comment]
You need an emunand to be brave. LOL
Just replace the arm9loaderhax.bin or use the updater to update luma.

**Comment by Nucca187** [comment]
so theres absolutely no way I can get Luma if I updated to 11.4 37 u
grr this is aggravating swapdoodle is set but have no one to send me doodlebomb just want Homebrew back my precious my precious homebrew.. jk just got off work was hoping for some good news on HBL


________________________________

**Comment by Masamune3210** [comment]
If you have a9lh, just take a backup of your NAND and update to 11.4, won't hurt anything to my knowledge and if it does you can just restore your backup.
You can just download the latest version of Luma from the releases on this website and replace the files when prompted, or you can use something like Luma Updater.

EmuNAND is not required to be brave, as anything that can hurt you on a9lh SysNAND enough to brick will do the same on EmuNAND

**Comment by AdivonL** [comment]
Fair enough, but restoring SysNAND isn't that easy and it's more risky.

**Comment by Margen67** [comment]
@adivonglong How is it "not that easy"? You literally just choose a different option in D9 to restore sysNAND. Stop spreading misinformation.

**Comment by Nucca187** [comment]
what if I didn't have a9lh all I was using was soundhax and updated without thinking like a nite like this after work....



________________________________

**Comment by Margen67** [comment]
@Nucca187 If you updated to 11.4 on sysNAND without A9LH without any sort of NAND backup there is no possible way you can downgrade. Also this is irrelevant to the issue so go to /r/3dshacks or something.

**Comment by Nucca187** [comment]
just making sure.. had to ask because no one is sending me doodlebomb. ty for taking the time to reply back though [😊]


________________________________

**Comment by AdivonL** [comment]
@Margen67 Please relate to the context, you wouldn't have D9 then.

**Comment by urherenow** [comment]
Wut? Wasn't D9 around BEFORE a9lh? Either way, there has always been a .3dsx version.

**Comment by AuroraWright** [comment]
This feature makes it possible to use Download Play with foreign games, it doesn't allow it between games or consoles from different regions from what I could see
