### ISSUE TITLE
I can't boot on EMUnand (Old 3DS)

### ISSUE THREAD

**Issue by CorJoestar** [LumaTeam/Luma3DS#420]
I followed step by step the guide in this page ( https://3ds.guide/ ) but in the end I can't boot the Old3DS on EMUnand... 
I've installed Luma, but if I boot the device while I'm holding L button (with SysNand autoboot enabled) or otherwise (with SysNand autoboot disabled), it goes Sysnand at the same.

**Comment by Margen67** [comment]
The guide has you transfer your emuNAND to your sysNAND.

**Comment by pbanj** [comment]
Did the system ever even have an Emunand? If there is no Emunand on the SD card luma will boot sysnand every time as there is nothing else to boot

**Comment by GabrielRRussell** [comment]
If you're asking how to boot an EmuNand, just format it using D9 or something else. Then copy your files back. Run an emunand then.
