### ISSUE TITLE
Why does homebrew freeze when i try to luanch stuff i have the 11.4 payload

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#422]
Like I have all the files but my homebrew just crashes on a green bottom screen and a black top screen and after 30 secinds my N3ds xl on 11.4 just turns off? is there a way to fix this or alternatively downgrade back to 11.3 by like useing the sysnand or whatever the hell its named

**Comment by MelonGx** [comment]
Why do you think that your problem is caused by Luma?

**Comment by ghost** [comment]
Cus if it dosent crash it says luma3ds payload error

**Comment by Zelec** [comment]
Are you using a9lh for your entry-point? if not you may want to see if your using Luma 7.0.1.
![image](https://cloud.githubusercontent.com/assets/13732124/25186535/73727012-24ee-11e7-8f94-3cd30425de98.png)

**Comment by ghost** [comment]
I updated to luma 7.0.1 and it still happens i even downgraded from 11.4 to 11.3 due to my SysNand from installing al9h

**Comment by ghost** [comment]
Or whatever its called

**Comment by TuxSH** [comment]
Use the 11.2 *hax payloads even on 11.3/11.4.
