### ISSUE TITLE
luma v7.x minimum system requirement changed, region free dependency

### ISSUE THREAD

**Issue by d386538** [LumaTeam/Luma3DS#425]
update:
Apparently,  luma v7.x Region free patch can not be applied on a 9.5 emunand. The patch can be applied after I update the emunand to 11.3.

I'm not sure what the minimum system requirement is needed for luma v7.x to work, **but it has nothing to do with A9LH, period.**

**Thanks for the useless arrogant down votes and replies.** 

-----------------------------------------------------------------------------------------
New 3ds US, 9.2 sysnand, 9.5 emunand.
Region free patch works on luma v6.6, but mset is broken.
Region free patch failed to apply on luma v7.0.1, but mset worked.
Tried /luma/titles/<titleID>/locale.txt already.
**I even deleted the luma folder (so it can't be the path issue: https://github.com/AuroraWright/Luma3DS/issues/417 or patch txt issue).**
Anything I shall try?

**Comment by jonirrings** [comment]
the locale path changed,
[code comment](https://github.com/AuroraWright/Luma3DS/blob/108e8a0cd408221d496ac47501338abd5c5327a4/injector/source/patcher.c#L458)

**Comment by Margen67** [comment]
https://3ds.guide/

**Comment by d386538** [comment]
> the locale path changed,

I deleted the entire luma folder, how would locale path matter at all?

> https://3ds.guide/

I have a working CFW, just the region free patch failed to apply.

**Comment by sora10pls** [comment]
>9.5 emunand

c r i n g e

**Comment by d386538** [comment]
> c r i n g e

I finished the 1 game I installed in 2015 just last month....
And 11.4 wasn't goodly supported during 7x nightly...

**Comment by Margen67** [comment]
You shouldn't be using menuhax, mset, or soundhax. They're unsafe. You should install B9S. @p1617762

**Comment by d386538** [comment]
Still, I would like to get the region free patch working first. @Margen67

**Comment by MelonGx** [comment]
1. @AuroraWright Wiki update seems to be the most important issue because there are more and more noobs asking for the latest region patch's path.

2. @p1617762 Read the fucking commit instead of the fucking wiki.
https://github.com/AuroraWright/Luma3DS/commit/b5336c81cc82b6c5e8115249342beb5b065cdce9

**Comment by MelonGx** [comment]
How can a region free patch work if you ignored what #417 required?

**Comment by d386538** [comment]
I used this:
> G:\luma\titles\0004000000166A00\locale.txt

with 

> JPN JP

but failed, that's why I removed the whole folder.
(Wait, so I can't pre-enable the region free option ahead of time?) @MelonGx
