### ISSUE TITLE
NSMB2 LayeredFS not loading mods

### ISSUE THREAD

**Issue by Gimzie** [LumaTeam/Luma3DS#426]
The game New Super Mario Bros 2. does not load the modified romfs with Luma's built in LayeredFS, and it's probably due to a different structure.

Multiple people have also reported this issue, and it would be way easier to load mods if the bug was fixed.

Thanks in advance!

**Comment by AuroraWright** [comment]
Latest nightly fixes it, please test

**Comment by Gimzie** [comment]
Tested on latest hourly, seems to work! Thanks a bunch for your hard work! 'w'

**Comment by NightScript370** [comment]
@Gimzie has a Github? Did you just make it?

But anyways, @AuroraWright, why did those issues even occur to start with? (If I offended you and your work with this post, I'm sorry, K? I just don't know how to phrase stuff nicely....)

**Comment by AuroraWright** [comment]
Because layeredFS works by patching the game's code and while I can test it with a limited amount of games there is a possibility the patch doesn't play nice with the code of *all games*.

**Comment by shinra358** [comment]
not working luma 9.1
