### ISSUE TITLE
Luma3DS 7.0.1 Download Play unavailable

### ISSUE THREAD

**Issue by Pixelw** [LumaTeam/Luma3DS#427]
I have a US New 3DS XL and a JP New 3DS. I wanted play mk7 local multiplayer for a long time. 7.0 came out which really excite me. But I tryed,on my us 3ds with jpn mk7.  Although I could create a group without error now. But jp 3ds could not detect my us 3ds. The same thing happens when it reverse.

"Download Play is now region free. " What does this new function mean. Is there anything I should do for this?

**Comment by Margen67** [comment]
#419
