### ISSUE TITLE
LayeredFS causes active theme to be disabled when exiting to home menu

### ISSUE THREAD

**Issue by jupitteer** [LumaTeam/Luma3DS#428]
I've tried with multiple games and mods, and every time, exiting to the home menu causes the theme to be reset to default as if the theme extdata wasn't available. The themes can be re-enabled.

**Comment by Margen67** [comment]
What entrypoint are you using?

**Comment by jupitteer** [comment]
arm9loaderhax. It is the latest version of luma and arm9loaderhax.

**Comment by AuroraWright** [comment]
https://github.com/AuroraWright/Luma3DS/issues/441

**Comment by AuroraWright** [comment]
Quoting myself: "I tried with an official theme (not via CHMM or other homebrew apps, but I don't think it should change anything and **if it does, it's not Luma's problem**), launched Pokemon Moon (both 1.0 and 1.1) with this romhack: https://projectpokemon.org/forums/forums/topic/40238-pok%C3%A9mon-nova-sun-umbra-moon-fully-featured-challenging-sunmoon-romhacks/ (which worked as expected) and home had no crashes or anything. **The theme also kept working as expected.**"

**Comment by jupitteer** [comment]
Trying with an official theme, it is not set back to no theme. Something with custom themes.

**Comment by GabrielRRussell** [comment]
I'm using a custom theme, with game patching for a Japanese Game (FE:Echoes Translation). I use a custom BoTW theme and this does not happen to me. It must be something with your specific theme. Can you post a link to it?
