### ISSUE TITLE
Wiki unclear on payload naming.

### ISSUE THREAD

**Issue by Hellrespawn** [LumaTeam/Luma3DS#43]
On the [Installation and Upgrade page](https://github.com/AuroraWright/AuReiNand/wiki/Installation-and-Upgrade#upgrading-to-511-from-43-or-older) there is a stern warning not to let payload file names exceed 13 characters. On the [Other Features page](https://github.com/AuroraWright/AuReiNand/wiki/Other-features-and-notes#payload-chainloading) there is no such warning.

**Comment by RShadowhand** [comment]
Fixed. Thanks.
