### ISSUE TITLE
Changing reigon fails to change country and subreigon

### ISSUE THREAD

**Issue by LordZane** [LumaTeam/Luma3DS#430]
This is very important for things such as pokemon

**Comment by Margen67** [comment]
#417

**Comment by LordZane** [comment]
#417 dosen't fix this, I already had it setup as the wiki says now before I opened this issue. The problem is the region is correct, but country and sub country aren't. I can provide a screenshot of my normal us game, and a new save of pokemon when emulating in japanese as comparison if you need

**Comment by Margen67** [comment]
#298 ?

**Comment by LordZane** [comment]
Oh, didnt realize it was already brought up. Can I ask why its impossible as of now? Whats different about changing region from country

**Comment by Liger0** [comment]
As anyone does, your only possibility is to make an Emunand and regionchange it. I did it too.
