### ISSUE TITLE
Ips Patching Stuck on Splash Screen

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#431]
After trying to run a game with an .ips the game stuck at nintendo 3ds splash screen

**Comment by tiduscrying** [comment]
Using .ips patches seems to work for me on 7.0.2... It just hangs a bit at the splash screen, but the game I am using does indeed load.

**Comment by AuroraWright** [comment]
IPS patches work just fine, your patch is likely corrupted or it's not an IPS patch at all (this would cause the infinite loading)
