### ISSUE TITLE
Luma 7.0.4 Breaks this mod

### ISSUE THREAD

**Issue by Piefactor** [LumaTeam/Luma3DS#435]
https://gbatemp.net/threads/release-animal-crossing-new-leaf-gcn-music-pack.468982/page-2#post-7277133

This mod replaces bcstm sound files of Animal Crossing New Leaf using LayeredFS.  For some reason it does not work and crashes the game on launch with 7.0.4, but does work with 7.0.3.

**Comment by KunoichiZ** [comment]
I also posted this in the GBAtemp thread for Luma as well and can confirm this as well.

**Comment by AuroraWright** [comment]
Is the game updated or not? If you enable exceptions is it loader the process that crashes or the game itself?

**Comment by KunoichiZ** [comment]
The game is updated, for me at least, to v1.5. The game gets past the Nintendo 3DS loading screen then immediately crashes. I uploaded my crash dump in the Luma thread. @AuroraWright

**Comment by AuroraWright** [comment]
https://github.com/AuroraWright/Luma3DS/commit/1887c6fae3539200854b8c615932a1916d8fb591 should fix it, please confirm

**Comment by KunoichiZ** [comment]
@AuroraWright Yep, that fixed it. Thanks.
