### ISSUE TITLE
[Suggestion] Patch11.3 OOT3D slowdown issue

### ISSUE THREAD

**Issue by mariomadproductions** [LumaTeam/Luma3DS#436]
The 11.3 system update introduced an [problem](https://www.3dbrew.org/wiki/11.3.0-36#New_issue) where using the Shekiah Stone menu in OOT3D causes video and audio stuttering. It isn't confirmed if any other slowdown exists in this or any other software. Could this be patched with Luma3DS? Or is there no reason to stay on 11.3 if I have CFW?

**Comment by AuroraWright** [comment]
Update to 11.4
