### ISSUE TITLE
Language Patching not working

### ISSUE THREAD

**Issue by Legarad** [LumaTeam/Luma3DS#440]
Luma3DS v7.0.4-b1c07c62 Configuration

(x) Autoboot SysNand
(x) Enable game patching

In the case of Rilu Rilu Fairilu Kirakira * Hajimete no Fairilu Magic the patch does not apply
In the case of PriPara Mezase! Idol Grand Prix No.1! the patch is applied but is stuck in the Nintendo 3DS logo

SD/Luma/Titles/GameID/locale.txt JPN JP

In these two games it is necessary that the name of the game is in Japanese, both games are using 3DS Keyboard

**Comment by TuxSH** [comment]
(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ
