### ISSUE TITLE
No Chainloader 9.2.0-20U O3ds luma 7.0.4 A9LH

### ISSUE THREAD

**Issue by killertaz17** [LumaTeam/Luma3DS#442]
when booting i cant get the chainloader to open i hold start and boot but just loads the sysnad but when i hold select it loads the configuration just fine. i tried older versions but nothing.

**Comment by killertaz17** [comment]
also i had hacked it with browser hax and updated to 9/2/0-20U with sysupdater from 4.0.

**Comment by MelonGx** [comment]
Chainloader is A9LH ONLY

**Comment by MelonGx** [comment]
1. You should confirm your console is real A9LH. Early Chinese sellers always deceived their customers with Menuhax consoles.
2. You should have at least one payload inside /luma/payloads/.

**Comment by Margen67** [comment]
@killertaz17

**Comment by TuxSH** [comment]
Now irrelevant since 7.1
