### ISSUE TITLE
Home button unlock

### ISSUE THREAD

**Issue by henke37** [LumaTeam/Luma3DS#445]
Games sometimes lock the home button for little to no reason. Block the game from locking the button.

**Comment by piratesephiroth** [comment]
No reason? They usually block it when we play online or if the game is loading.

**Comment by AuroraWright** [comment]
Might cause savedata corruption, online cheating and other stuff, so I'm not sure it's a good idea

**Comment by TuxSH** [comment]
The game itself is responsible for yielding control to APT to return to Home Menu, so that's not possible anyways.
