### ISSUE TITLE
Puzzle and Dragons - Super Mario Bros. Edition JAP doesen't work on Luma

### ISSUE THREAD

**Issue by rayman955** [LumaTeam/Luma3DS#446]
Game doesn't work, error on startup

**Comment by MelonGx** [comment]
Read The Fucking Wiki before posting this.
The Fucking Wiki did teach you how to make a foreign game work.

**Comment by GabrielRRussell** [comment]
This is not an issue that should be here. This has zero info. It is most likely already been solved, and is probably an issue with your device / the way you've set up Luma.

This should not have been made in the first place.

If you want help, that is not directly related to Luma or an issue with luma, go to the Q&A thread in the 3DSHacks subreddit.
