### ISSUE TITLE
Get Black Screen On Boot FAQ and troubleshooting not solving the problem.

### ISSUE THREAD

**Issue by houodrigoly** [LumaTeam/Luma3DS#447]
I follow all the steps and its still get black screen, what to do?

**Comment by Margen67** [comment]
If you're using an emuNAND DSiWare and GBA games must also be installed to sysNAND.

If you're not already using A9LH you should install it using [this guide](https://3ds.guide/).

**Comment by houodrigoly** [comment]
Thanks for the guide, I managed to finish the full guide without errors and now my CFW O3DS is much better, solved all the problems, can install any DSI/GBA and run perfectly :)
