### ISSUE TITLE
X Button Payload not loading in Version 5.1.2

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#45]
For me the X payload won't load up in Version 5.1.2, I get a black screen when I want to boot into it. It works fine in 5.1 though

Thanks for your great work!

**Comment by RShadowhand** [comment]
What is your x payload? Emunand9?

**Comment by ghost** [comment]
it is Uncart. 

My payloads are like this: 
![bildschirmfoto 2016-04-20 um 18 42 42](https://cloud.githubusercontent.com/assets/3320036/14682822/c0875f56-0727-11e6-9dc0-a7ab21ed90a8.png)

**Comment by RShadowhand** [comment]
There was an issue with D9 and E9 that required manual patches on ARN's side, but those were fixed by d0k3. It might be that Uncart also needs to be updated to work.

**Comment by ghost** [comment]
ok thanks!

**Comment by RShadowhand** [comment]
To troubleshoot, you can swap x and y payloads, see if you can boot with x then. If you can, then the problem is uncart itself.

**Comment by ghost** [comment]
I can test it later and will report back.

**Comment by ghost** [comment]
The problem is with Uncart. I swapped Uncart (X) with Emunand (Y) and starting Uncart with Y also doesn't work.
