### ISSUE TITLE
Pokemon Moon crashes and Youtube stucked on loading screen

### ISSUE THREAD

**Issue by kayeaborot** [LumaTeam/Luma3DS#452]
**System model: New 3DS

**SysNAND version (+emu/redNAND version if applicable): 11.4.0-37U

**Entrypoint (How/what you're using to boot Luma3DS): A9LH

**Luma3DS version:  7.0.5 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (off)

PIN lock: (off)

New 3DS CPU: (Clock + L2 )

--

Autoboot SysNAND: (x )

Use SysNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch SVC/service/archive/ARM9 access: ( )

Set developer UNITINFO: ( )

Enable exception handlers: ( )

--

**Explanation of the issue:**
Tried playing Pokemon Moon to check issue with online games, I can join battles but after some time it shows the error that something went wrong and need to restart the console.

Youtube just loads the Nintendo 3ds screen.

CHMM themes (as well as default themes) not loading after restarting the unit.

**Steps to reproduce:**

1. Play Pokemon Moon for some time

2. Try opening Youtube

3. Install custom themes by CHMM and shut down the console. After restarting the theme wasn't applied. For default themes, it worked but when you restart the unit it was gone

**Dump file:**

**Comment by Shadow322** [comment]
This is not tech support post this on gbatemp kthx
