### ISSUE TITLE
What do you mean by Sighax support?

### ISSUE THREAD

**Issue by NintendoHacker44** [LumaTeam/Luma3DS#455]
Sighax was released, and I want to know how to use your Sighax support.

**Comment by ihaveamac** [comment]
https://3ds.guide/updating-to-boot9strap

**Comment by AuroraWright** [comment]
Not a support forum...

**Comment by GabrielRRussell** [comment]
I wish we could prevent users from making issues if they have a history of making improper ones. Or is that already a feature?

**Comment by Margen67** [comment]
@Kaisogen GitHub allows you to block users and ban them from repositories.

**Comment by GabrielRRussell** [comment]
Good to know.

Now only if I had people to block and ban (;
