### ISSUE TITLE
Windows Defender Blocks Download - 

### ISSUE THREAD

**Issue by GriffinG1** [LumaTeam/Luma3DS#456]
All on PC

**Explanation of the issue:**

http://imgur.com/KskVy3n

**Steps to reproduce:**

1. Download Luma3DS.7z

2.

**Dump file:**

**Comment by Rebelgaming12** [comment]
I have the same issue

**Comment by jonirrings** [comment]
I just remove it from blocked list

**Comment by AuroraWright** [comment]
It's obviously a false positive, Luma is open source so you can compile it yourself if you don't trust us.
Complain to microsoft.

**Comment by MasterGamingYT** [comment]
I have a question for you Microsoft........
Which word is more offensive "Luma" or "3DS" because you probably think that luma3ds is a virus, but in reality, it isn't ¯\_(ツ)_/¯
