### ISSUE TITLE
[Suggestion] Animated Splash loading? 

### ISSUE THREAD

**Issue by Ganonmain** [LumaTeam/Luma3DS#459]
Title says it all. Do you think this may be a possibility someday? 

If not, I don't really care, I'm super happy with all the work that is done with this cfw! :D

**Comment by GabrielRRussell** [comment]
I think this should be a native feature. It was nearly impossible to set up with BootAnim9, as it was riddled with errors that were easily caught by the user. I don't know how bootctr9 does it, but I would appreciate a feature like this in Luma.  Of course, I don't think this should detract development from the main project. I would use a fork if necessary.

**Comment by TuxSH** [comment]
Too much work and not really Luma3DS's job.
