### ISSUE TITLE
outdated info/missing parts

### ISSUE THREAD

**Issue by NWPlayer123** [LumaTeam/Luma3DS#463]
I'm sure you're aware, but currently we need to download firmtool separately and get the Makefile to read it, so adding it as a dependency like GodMode9 has already done is ideal, otherwise you no longer need --recursive in the README cause all the other external repos have been ditched for pure boot9strap.
If anyone stumbles upon this, I've been pasting firmtool.py in the root directory here and editing the Makefile (line 68) to add the .py so it finds it

**Comment by urherenow** [comment]
It might help if you actually installed firmtool. It happens to install to python as a module, same as the python crypto.

**Comment by NWPlayer123** [comment]
I'll have to try that, still should work out of the box without doing that tho

**Comment by dragos240** [comment]
Here's another one I found:

**Explanation of the issue:**
The "I get an auto-shutdown with GBA/DS/DSiWare games" in the "FAQ and Troubleshooting" section of the wiki still links to [The A9LH section (which no longer exists) of Plailect's guide](https://plailect.github.io/Guide/installing-arm9loaderhax).

**Steps to reproduce:**

1. Visit the Wiki, then the FAQ and scroll down to "I get an auto-shutdown with GBA/DS/DSiWare games". There's a broken link to the [A9LH section of Plailect's guide](https://plailect.github.io/Guide/installing-arm9loaderhax).

EDIT: This link is included [here too](https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-get-a-black-screen-on-boot).

**Comment by urherenow** [comment]
@NWPlayer123 looks like you are correct. Running the install script for firmwaretool seems to install firmwaretool.py into (on my windows setup with python 2.7.x) 

"c:\Python27\Scripts\"  (the trailing backslash is important in your environment path)

So although you do not need to copy firmwaretool.py anywhere, you DO have to edit the makefile line 68 to add .py to it. I'm guessing that the firmwaretool (without .py) is for *nix setups only or perhaps it will install to python and run correctly as-is if run from msys instead of a regular command prompt (can't be bothered to try).

**Comment by TuxSH** [comment]
It's firmtool.

I've edited the README a bit, tell me what you think of the changes.

**Comment by urherenow** [comment]
@TuxSH still have to use firmtool.py. I updated ctrulib, and I updated and re-ran your firmtool install script from an elevated command prompt. What gets installed to Python is firmtool.py, not firmtool. Simply typing firmtool does nothing on windows (usually. Only .exe, .bat, and .com files can be run without an extension).

If you're on Windows and only need to type "firmtool", can you show me your registry entry for .py files that makes it automatically recognized as an executable?

**Comment by TuxSH** [comment]
Isn't that set by the python installer, at least with recent ones?

Class .py default key is Python.File ...

**Comment by NWPlayer123** [comment]
yeah, uh, installing firmtool only copies firmtool.py to C:\Python**\Scripts (**=ver), I copied both from the repo and now it's happy with just "firmtool" (cause the file exists in my path), that should probably be fixed on that side tho

**Comment by urherenow** [comment]
the above works for me, only in msys. regular command prompt still won't take "firmtool". Either manually copy firmtool and use msys, or change makefile to use firmtool.py. It works, but not as-is.

**Comment by urherenow** [comment]
interesting... running "pip install --upgrade git+https://github.com/TuxSH/firmtool.git" from msys resolves everything and "firmtool" works perfectly. Guess I need to remember to use msys from now on for luma.

**Comment by piratesephiroth** [comment]
"firmtool" never works here either.
I must use "firmtool.py"

**Comment by urherenow** [comment]
Damn, son... my post right above tours tells you what to do. Install firmtool from within msys prompt (not cmd.exe). Then it will run fine from msys. It will NEVER run from CMD.exe because .exe, .bat, and .com are the only extentions you can ignore in windows.

**Comment by piratesephiroth** [comment]
msys? If you mean I should run from sh then nope, it doesn't work either.


![image](https://cloud.githubusercontent.com/assets/10672233/26534175/c5abe016-43f7-11e7-82da-8729f4df73d3.png)


![image](https://cloud.githubusercontent.com/assets/10672233/26534139/6ad9e098-43f7-11e7-8b0a-9490a8551cff.png)

**Comment by Jerry-Shaw** [comment]
@piratesephiroth We are at the same place. The only way to fix this is to place the "firmtool" file right in the Luma folder. I tried to install firmtool and confirmed that "firmtool" command ran, but when building Luma, the command was not found still. Very strange.
I am under Windows 10, using devkitARM, msys is in devkitARM.

**Comment by piratesephiroth** [comment]
I think the easiest fix is to change "firmtool" to "firmtool.py" in the makefile.
Would that break anything in a non-windows OS?

**Comment by urherenow** [comment]
I mean msys. If you installed devkitpro (vice just the devkitarm installer) you have devkitpro/msys/msys.bat

Install and run through that. But SH... are you not not on Windows?

**Comment by Margen67** [comment]
~Issue template is outdated as well.~ https://github.com/AuroraWright/Luma3DS/commit/8308e1a8b84e305f3258fc98b26ab1016fe4f574

**Comment by TuxSH** [comment]
latest firmtool commit should fix the .py issue.
