### ISSUE TITLE
[SUGESTION] System-wide keys modifier / hotkeys

### ISSUE THREAD

**Issue by jokkovitch** [LumaTeam/Luma3DS#464]
A lot of users got their home button damaged / not working.
Would it be possible to create hotkeys, like L+R+UP+X would emulate Home button, system-wide and from boot.
Painfull not being able to enter God9 options just because of a malfunctionning button.
Something like this was created for Jailbroken Iphone and litteraly tons of people were using it.

**Comment by GabrielRRussell** [comment]
I'm pretty sure there was a way to send inputs to a computer through the 3DS. Then send the inputs back to the 3DS as something else.

This could be done with a PC program. I don't know if it would be possible to do this through Luma.

As for changing the button used for the payload, edit the source and compile it yourself until a solution is found. Or change the payload name to [button]_GodMode9.bin

**Comment by Masamune3210** [comment]
This would not work in GodMode9 as far as I know even if it is possible, due to GodMode9 loading before Luma

⁣Sent from BlueMail ​

**Comment by urherenow** [comment]
Umm... It doesn't HAVE to load before luma. GM9 can run from HBC, and some direct entry points as well.

**Comment by dogtopus** [comment]
Yet another reason to have a background thread I guess.

**Comment by TuxSH** [comment]
"Painfull not being able to enter GodMode9 options just because of a malfunctionning button."

GodMode9 is running in baremetal (w/o an OS), what you describe is a GM9 issue more than a Luma3DS one.
