### ISSUE TITLE
Banwave

### ISSUE THREAD

**Issue by mem13** [LumaTeam/Luma3DS#465]
**System model:** [e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applica🅱le):** [e.g. 11.4.0-37U]

**Entrypoint (How/what you're using to 🅱oot Luma3DS):** [e.g. A9LH]

**Luma3DS version:** [e.g. 7.0.5 sta🅱le or if using nightly specify the commit like this https://githu🅱.com/AuroraWright/Luma3DS/commit/5fe83588e🅱4🅱8faafc7773🅱3739a3d3307160🅱04]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen 🅱rightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Auto🅱oot SysNAND: ( )

Use SysNAND FIRM if 🅱ooting with R: ( )

Ena🅱le loading external FIRMs and modules: ( )

Use custom path: ( )

Ena🅱le game patching: ( )

Show NAND or user string in System Settings: ( )

Show G🅱A 🅱oot screen in patched AG🅱_FIRM: ( )

Patch SVC/service/archive/ARM9 access: ( )

Set developer UNITINFO: ( )

Ena🅱le exception handlers: ( )

--

**Explanation of the issue:**

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by TuxSH** [comment]
No info given, closing.

Please stop posting empty issues.
