### ISSUE TITLE
B9S-Next builds?

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#466]
how do u use the B9S-Next builds I have put it in both root of sd card and CTRNAND and all it does is shutdown instantly like it doesn't exist?

**Comment by Zetchzie** [comment]
I dont think those are ready for public use

**Comment by AuroraWright** [comment]
It needs the new boot9strap branch to boot, which isn't finalized yet (it works fine as I'm using the latest commit, but I wouldn't recommend installing as it also breaks payloads other than luma)

**Comment by Shadow322** [comment]
@AuroraWright thanks for a real answer unlike @Zetchzie

**Comment by Zetchzie** [comment]
I wasn't entirely wrong either you prick @Shadow322

**Comment by ihaveamac** [comment]
just calm down, this is not the place to argue

**Comment by Shadow322** [comment]
ikr

**Comment by Zetchzie** [comment]
nvm carry on
