### ISSUE TITLE
Hourly update killed o3ds

### ISSUE THREAD

**Issue by sanjek69** [LumaTeam/Luma3DS#468]
Checking for new Luma3DS Updater releases...
Downloading https://api.github.com/repos/KunoichiZ/lumaupdate/releases/latest...
Download progress: 5544 / 5544
Downloaded 5544 bytes
JSON parsed successfully!
Release found: v2.1
Changelog found.
Current updater is already at latest release.
Trying detection of current payload version...
7.1-c73fec46
Loaded existing payload in memory, searching for version number...
Downloading https://api.github.com/repos/AuroraWright/Luma3DS/releases/latest...
Download progress: 3362 / 3362
Downloaded 3362 bytes
JSON parsed successfully!
Release found: 7.1
Found version: Luma3DSv7.1.7z
Release description found.
Downloading http://astronautlevel2.github.io/Luma3DS/lastCommit...
Download progress: 8 / 8
Downloaded 8 bytes
Copying /boot.firm to /boot.firm.bak...
Downloading http://astronautlevel2.github.io/Luma3DS/latest.zip
Download progress: 51398 / 51398
Download complete! Size: 51398
Skipping integrity check #1 (unknown size)
Skipping integrity check #2 (no ETag found)

Extracting payload [OK]
Considering GodMode9.firm
Considering GodMode9.firm
Saving payload to SD/CTR-NAND (as /boot.firm)...
All done, freeing resources and exiting...

**Comment by Margen67** [comment]
https://3ds.guide/updating-to-boot9strap
