### ISSUE TITLE
Arm9 Payloads not booting after switch to newer version

### ISSUE THREAD

**Issue by Pikm** [LumaTeam/Luma3DS#47]
After I switched from AuReiNand 5.0 to 5.1.2, payloads like Uncart and CtrBootManager9 are not booting when the respective key is held. Is there is a fix for this?

**Comment by cheatfreak47** [comment]
I fixed this by updating my uncart payload to the latest version which seems to work fine, not sure why the previous payload wouldn't run though.

**Comment by AuroraWright** [comment]
Fix: https://github.com/AuroraWright/uncart/releases https://gbatemp.net/threads/release-ctrbootmanager9.417159/page-23#post-6271681
