### ISSUE TITLE
Feature Request: Hide EmuNAND options in config if SD Card isn't formatted for EmuNAND

### ISSUE THREAD

**Issue by sora10pls** [LumaTeam/Luma3DS#470]
If it's possible to tell how the SD Card is formatted, then perhaps Luma's config could hide all EmuNAND-related configuration options if the SD Card isn't formatted for EmuNAND.

Edit: I believe this should be added because of the New 3DS configuration options. If a device is an Old 3DS, having the New 3DS options is pointless. Likewise, if the user has no EmuNAND, having the EmuNAND options is pointless. Less is always better.

**Comment by drdeaton** [comment]
Luma can detect if an emunand is present, so I dont see why this can't be a thing.

**Comment by GabrielRRussell** [comment]
I personally find it fine. Some options are already removed upon SDless boot. This is a QoL change that I find nice, but isn't really necessary.

**Comment by Slashin-it-up** [comment]
If you can build Luma3DS, you can also do what I did. In the Config.c, find every line that says =isSDmode and change it to false.

**Comment by quantumcat1** [comment]
Along the same lines, can there be a notice in the config if it has been booted from CTR-NAND? Lots of people have troubleshooting difficulties when it turns out that Luma was booting from CTR-NAND not SD card like they were expecting.

**Comment by sora10pls** [comment]
I second what @quantumcat1 requested. That would be incredibly helpful.

**Comment by fryfrog** [comment]
@quantumcat1, you should make this into an issue/feature request.
