### ISSUE TITLE
Incorrect game patching information in the wiki

### ISSUE THREAD

**Issue by bakugo** [LumaTeam/Luma3DS#471]
The [wiki](https://github.com/AuroraWright/Luma3DS/wiki/Options-and-usage) says
>Obtain a patched code.bin for the game, and rename it with game's title id as the file name  

In the code.bin and code.ips sections, which is incorrect and contradicted by the very next line.

**Comment by TuxSH** [comment]
Thank you :D.

It should be fixed now.
