### ISSUE TITLE
Outdated wiki

### ISSUE THREAD

**Issue by sora10pls** [LumaTeam/Luma3DS#475]
Referring to the "[Options and usage](https://github.com/AuroraWright/Luma3DS/wiki/Options-and-usage)" page.

- Autoboot SysNAND
- Use SysNAND FIRM if booting with R

These two refer to the options displayed in <= v7.0. These options now relate to EmuNAND as of v7.1.

**Comment by Margen67** [comment]
#463

**Comment by TuxSH** [comment]
Should be fixed now.
