### ISSUE TITLE
Chainloader not working when boots from CTRNAND

### ISSUE THREAD

**Issue by dogtopus** [LumaTeam/Luma3DS#476]
**System model:** New 3DS

**SysNAND version (+emu/redNAND version if applicable):** 11.4.0-37U

**Entrypoint (How/what you're using to boot Luma3DS):** B9S

**Luma3DS version:** v7.1

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (1)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch SVC/service/archive/ARM9 access: ( )

Set developer UNITINFO: ( )

Enable exception handlers: (X)

--

**Explanation of the issue:**

When using payload from CTRNAND and hold START, the chainloader menu did not show up and boots normally (Like START was not pressed). The payloads to be chainloaded are located in both `1:/luma/payloads/` and `0:/luma/payloads/` folders (i.e. CTRNAND and SD card)

**Steps to reproduce:**

1. Copy the payload to both `1:/luma/payloads/` and `0:/luma/payloads/`

2. Copy Luma3DS `boot.firm` to `1:/` (CTRNAND)

3. Delete `0:/boot.firm` (Luma3DS on SD card)

4. Reboot (or shutdown and cold-boot) and hold START

**Dump file:** None

**Comment by TuxSH** [comment]
On NAND the `luma` folder should be located inside the `rw` folder
