### ISSUE TITLE
Current Luma3DS still has a FIRM issue like #385

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#478]
This time Luma3DS 7.1 cannot boot a factory 10.7.0-32J SysNAND.
It says "Failed to apply 1 FIRM patch(es)".
Since B9S never supports Luma3DS 6.3.1 - which is the last version properly supported factory NAND's FIRM, I ask the owner to enable "Use EmuNAND FIRM if booting with R", then the SysNAND can be booted into SysE 10.7.0-32J properly.
(Fortunately the owner has a 11.4.0-37J EmuNAND.)

**Comment by AuroraWright** [comment]
Disable game patching and the permission patch, they don't work between 9.3 and 11.0 for now
