### ISSUE TITLE
[BUG] "Show NAND or user string in System Settings"

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#480]
Does not work from nand aka rw/luma/customversion_sys.txt

**Comment by sora10pls** [comment]
Works fine for me...

**Comment by Margen67** [comment]
@sora10pls With customversion_sys.txt on NAND or SD?

**Comment by sora10pls** [comment]
Works fine with CTRNAND (SD Card not inserted and in the path mentioned by OP), as well as with SD Card inserted.

Edit: @Shadow322 make sure your CTRNAND config actually has the option enabled, I don't see why it'd work for me and not for you.

**Comment by Shadow322** [comment]
customversion_sys.txt with top line being Luma3DS-%d.%d.%d-%d does not work and yes its enabled and only shows Sys 11.4.0-37U on Luma3DS v7.1-8308e1a8 from NAND

**Comment by sora10pls** [comment]
Aren't the latest nightlies supposed to be broken? Last I've heard, they don't even boot properly. Your commit string displays latest commit, I'm running stable v7.1.

**Comment by Shadow322** [comment]
hearing and doing is 2 different things

**Comment by sora10pls** [comment]
ok

**Comment by Shadow322** [comment]
Just tested with v7.1 release does not work either so I was right it should be fixed for the ones that it works for is because u have it in your Luma folder on your sd card

**Comment by Margen67** [comment]
Luma will only read/write where the payload (boot.firm) is.

If the custom version string isn't in the same directory (SD card/CTRNAND) it won't read it.

**Comment by Shadow322** [comment]
so it needs not be in the luma folder and be in root of nand?

**Comment by Shadow322** [comment]
nope still does not work

**Comment by Shadow322** [comment]
because its in rw/luma/ like with godmode9.firm the config.bin as well as the 2 splashscreen bins and all the other stuff works

**Comment by Margen67** [comment]
No. If the luma payload (boot.firm) is on the SD card, the custom version string should be put in SD:/luma

If it's on the CTRNAND it should be in CTRNAND:/rw/luma/

**Comment by sora10pls** [comment]
>because u have it in your Luma folder on your sd card

What part of my
>Works fine with CTRNAND

Didn't you get

**Comment by Shadow322** [comment]
it is in  CTRNAND:/rw/luma/ and does not work there is no boot.firm on sd card

**Comment by sora10pls** [comment]
Tried out setting my `customversion_sys.txt` to be the same as yours (line reads `Luma3DS-%d.%d.%d-%d` as you mentioned), works fine in both SD Card boot as well as CTRNAND boot.

I can't replicate this as hard as I try.

**Comment by sora10pls** [comment]
I want to reassure to you something that your last comment may have mentioned.

If boot.firm is found on CTRNAND, it loads that, even with SD Card inserted (and if it has boot.firm).

If boot.firm is **not** found on CTRNAND, but it is on SD Card, it loads that.

If the SD Card *isnt inserted* and you're running boot.firm from CTRNAND, it reads the "luma" folder from CTRNAND.

Likewise, if the SD Card *is inserted*, regardless of launch method, it reads the "luma" folder from the SD Card, *not* from CTRNAND.

**Comment by sora10pls** [comment]
@Shadow322 any updates?

**Comment by Shadow322** [comment]
still does not work

**Comment by sora10pls** [comment]
Let me make sure. When booting, you:

- Have `boot.firm` on the root of CTRNAND?
- Have the SD Card **not** inserted when booting?
- Have `customversion_sys.txt` in `CTRNAND/rw/luma/`?
- Have "Show NAND or user string in System Settings" enabled on your CTRNAND's Luma config?

If the SD Card isn't inserted, it loads all files from CTRNAND.

If the SD Card is inserted, regardless of boot method (`boot.firm` on CTRNAND only, on SD only, on both), it will load files from SD Card rather than CTRNAND.

**Comment by sora10pls** [comment]
@Shadow322

**Comment by Shadow322** [comment]
Then that needs fixed

**Comment by sora10pls** [comment]
@AuroraWright @TuxSH not sure if it's intentional or not, but refer to the last 2 sections of my above comment.

>If the SD Card isn't inserted, it loads all files from CTRNAND.

>If the SD Card is inserted, regardless of boot method (`boot.firm` on CTRNAND only, on SD only, on both), it will load files from SD Card rather than CTRNAND.

**Comment by Shadow322** [comment]
OK when I put customversion_sys.txt in CTRNAND/rw/luma/ on both my O3DS and O3DS XL it works as expected and its not on the sd card at all but when i do the same on my N3DS XL it does not work as intended so its a N3DS/XL problem
