### ISSUE TITLE
LayeredFS lag in-game

### ISSUE THREAD

**Issue by 8bitwalugi** [LumaTeam/Luma3DS#481]
**System model:**
N3DS

[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
Sys 11.4.0-37E
[e.g. 11.4.0-37U SysNAND, 11.4.0-37J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap
[e.g. Boot9Strap, Sighax, etc.]

**Luma3DS version:**
7.1
[e.g. 7.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (1 )

Splash: ( )

PIN lock: ( )

New 3DS CPU: (Clock+L2 )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch SVC/service/archive/ARM9 access: ( )

Set developer UNITINFO: ( )

Enable exception handlers: ( )

--

**Explanation of the issue:**
When loading audio files off SD card for Dragon Quest 8 (cartridge and digital), the game begins to lag and audio starts ro desync.

**Steps to reproduce:**

1. Put Japanese audio files in luma\titles\000400000018F200\romfs\rom\Sound\stream

2. Start a new file, wait for pre-rendered cutscene to finish

No idea if this may also affect other games similarly.

**Dump file:**

**Comment by AuroraWright** [comment]
Can't be fixed, loading from SD is slower than romfs by its own nature
