### ISSUE TITLE
[FEATURE REQUEST]remove configuration shortcut when payload is on ctrnand

### ISSUE THREAD

**Issue by annson24** [LumaTeam/Luma3DS#482]
As the title says, is it possible to remove the config shortcut when luma3ds payload is in the ctrnand? That could prevent noobs from accidentally tweaking the configuration.

**Comment by gnmmarechal** [comment]
There's not really much noobs can screw up in the config anyway.

I don't think this is a good idea.

**Comment by TuxSH** [comment]
> There's not really much noobs can screw up in the config anyway.

Yep, totally.

If launched from NAND Luma3DS will load/store the config from/to NAND (as opposed to SD card), etc.
