### ISSUE TITLE
Luma does not boot on boot9strap v1.1 because of new agrc handling

### ISSUE THREAD

**Issue by qwertyatom100** [LumaTeam/Luma3DS#483]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

7.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (4 )

Splash: ( Off)

PIN lock: (Off )

New 3DS CPU: (Off )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch SVC/service/archive/ARM9 access: ( )

Set developer UNITINFO: ( )

Enable exception handlers: (x)

--

**Explanation of the issue:**
Upon booting Luma on a 3DS with boot9strap v1.1 installed the following error message will occur:
An error has occurred:

Unsupported launcher (argc = 0).

NOTE: This issue is fixed in branch b9s-next

**Steps to reproduce:**

1. Upgrade your 3DS to boot9strap v1.1.

2. Attempt to boot.

**Dump file:**
N/A

**Comment by sora10pls** [comment]
>NOTE: This issue is fixed in branch b9s-next

...

**Comment by james-d-elliott** [comment]
^ This. They're working on supporting it.

**Comment by qwertyatom100** [comment]
Just putting it out there.

**Comment by sora10pls** [comment]
The issue has a solution though.

If someone doesn't want to encounter it, they should use B9S 1.0 with the latest stable release.
If someone doesn't want to encounter it, but wants B9S 1.1, then use any build from the b9s-next branch.
