### ISSUE TITLE
TWL/AGB dies again from latest nightly (b9s-next branch) & B9S 1.1 (Seems to be astronautlevel2's nightly builder's issue)

### ISSUE THREAD

**Issue by MelonGx** [LumaTeam/Luma3DS#484]
As topic.

**Comment by AuroraWright** [comment]
Can't reproduce.

**Comment by Razorzeto** [comment]
TWL/AGB goes dark after updating to B9S 1.1, I'm using the B9s-next branch too.

**Comment by MelonGx** [comment]
OK, it seems to be Astronautlevel2's issue.
I'll still leave it open but change the title.

**Comment by AuroraWright** [comment]
Well don't report such an issue here, contact him...

**Comment by MelonGx** [comment]
OK.....It's moved here
https://github.com/astronautlevel2/Luma3DS/issues/10
