### ISSUE TITLE
Cannot boot with boot9strap 1.2

### ISSUE THREAD

**Issue by ITJesse** [LumaTeam/Luma3DS#485]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37J SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

7.1 stable and the last commit 4429cb2095c7294a97843433ae0259958b8a419c

**Luma3DS configuration/options:**

Default EmuNAND: (x )

Screen brightness: (4 )

Splash: ( x)

PIN lock: (x )

New 3DS CPU: (x )

--

Autoboot EmuNAND: (x )

Use EmuNAND FIRM if booting with R: (x )

Enable loading external FIRMs and modules: (x )

Use custom path: (x )

Enable game patching: (x )

Show NAND or user string in System Settings: (√ )

Show GBA boot screen in patched AGB_FIRM: (√ )

Patch SVC/service/archive/ARM9 access: (√ )

Set developer UNITINFO: (x )

Enable exception handlers: (x )

--

**Explanation of the issue:**

When I upgrade the boot9strap 1.2, the console cannot boot.
It shows:

> Unsupported launcher (argc = 0)

But I can boot other payloads such as GodMode9.

**Steps to reproduce:**

1. Upgrade to the boot9strap 1.2

2. Power on the console

**Dump file:**

**Screenshot:**
![image](https://cloud.githubusercontent.com/assets/3601376/26765773/4a87f1d2-49be-11e7-9010-a51f538fecd5.png)

**Comment by Margen67** [comment]
#483 https://astronautlevel2.github.io/Luma3DS/ use the builds from the "b9s-next" branch

**Comment by ITJesse** [comment]
Thanks, seems the last commit works.

**Comment by ITJesse** [comment]
But the chainloader dosen't work anymore.
Version: 4429cb2095c7294a97843433ae0259958b8a419c

When I boot GodMode9:
![img_1480](https://cloud.githubusercontent.com/assets/3601376/26765852/98eeeb04-49bf-11e7-8ed1-6ea1265152e8.JPG)

[crash_dump_00000001.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/1050762/crash_dump_00000001.dmp.zip)

But I can boot GodMode9 as boot.firm without luma chainloader.

**Comment by ITJesse** [comment]
I opened another issue.
#486

**Comment by MelonGx** [comment]
Use GM9 20170531 nightly.
