### ISSUE TITLE
The chainloader broken in the last commit.

### ISSUE THREAD

**Issue by ITJesse** [LumaTeam/Luma3DS#486]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37J SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

The last commit 4429cb2095c7294a97843433ae0259958b8a419c

**Luma3DS configuration/options:**

Default EmuNAND: (x )

Screen brightness: (4 )

Splash: ( x)

PIN lock: (x )

New 3DS CPU: (x )

--

Autoboot EmuNAND: (x )

Use EmuNAND FIRM if booting with R: (x )

Enable loading external FIRMs and modules: (x )

Use custom path: (x )

Enable game patching: (x )

Show NAND or user string in System Settings: (√ )

Show GBA boot screen in patched AGB_FIRM: (√ )

Patch SVC/service/archive/ARM9 access: (√ )

Set developer UNITINFO: (x )

Enable exception handlers: (x )

--

**Explanation of the issue:**

 The chainloader doesn't work.
When I boot GodMode9:
![img_1480](https://cloud.githubusercontent.com/assets/3601376/26765852/98eeeb04-49bf-11e7-8ed1-6ea1265152e8.JPG)
But I can boot GodMode9 as boot.firm without luma chainloader.

**Steps to reproduce:**

1. Boot any payload in Luma chainloader

**Dump file:**

[crash_dump_00000001.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/1050762/crash_dump_00000001.dmp.zip)

**Comment by MelonGx** [comment]
Use GM9 20170531 nightly.
