### ISSUE TITLE
[Suggestion] Allow N3DS Buttons for Rosalina Menu Combo

### ISSUE THREAD

**Issue by Carbuino** [LumaTeam/Luma3DS#487]
Pretty much what the title says.

**Comment by TuxSH** [comment]
Not possible. 

The Rosalina menu reads buttons _itself_ in the most basic way possible (through reading the [HID_PAD](https://www.3dbrew.org/wiki/HID_Registers#HID_PAD) hardware register). For the same reason InputRedirection won't work for it either.

On the other hand ZL/ZR and the c-stick are in an external device (even on N3DS), managed by the `ir` submodule.
