### ISSUE TITLE
[Question] Possible to store Rosalina menu combo in a config file?

### ISSUE THREAD

**Issue by sora10pls** [LumaTeam/Luma3DS#489]
As the title says. Currently, it's only possible to change the combo during runtime, and gets reset to default (default being `(L) + (Down) + (Select)`) every time the device restarts.

**Comment by blackwing182** [comment]
Plus to this.

I was going to report this minor issue right now.

**Comment by Steveice10** [comment]
This would be especially useful to me as my D-Pad down button is broken. Having the homebrew-launching title saved to a configuration file as well would be helpful as well.

**Comment by HolidayOugi** [comment]
I support this since my L button is almost broken

**Comment by TuxSH** [comment]
In my todo list 😛

**Comment by ghost** [comment]
Glad to know its being worked on! Thanks so much.

**Comment by Hikari-chin** [comment]
The combination can be changed by editing the config.bin now; no too currently exists to modify

**Comment by deltaFigure** [comment]
Is this still being worked on, or is this finished?
