### ISSUE TITLE
Rename the v8.0 release

### ISSUE THREAD

**Issue by BigBrainAFK** [LumaTeam/Luma3DS#492]
The current v8.0 release name "Luma3DS v8.0" somewhat "breaks" the Luma Updater.

I guess a rename to just "v8.0" would fix the more or less "visual" bug.

**Comment by james-d-elliott** [comment]
I have a feeling this might of been a deliberate change since updating requires additional steps. Using the updater would have no benefit since you have to remove the SD card anyway.

https://3ds.guide/updating-b9s

**Comment by BigBrainAFK** [comment]
well looking into the updater after the update still says that you arent on the latest version.

EDIT: people dont seem to care and update from 7.1 to 8.0 despite not updating b9s first anyways so ya

**Comment by KunoichiZ** [comment]
I second this.

**Comment by KunoichiZ** [comment]
This will be fixed in a re-uploaded version of Luma Updater, as mentioned in KunoichiZ/lumaupdate#13.

**Comment by BigBrainAFK** [comment]
Then i guess this isnt really needed here anymore
