### ISSUE TITLE
"An Exception Occurred" error when loading Smash for 3DS

### ISSUE THREAD

**Issue by DewGaming** [LumaTeam/Luma3DS#493]
[New 3DS XL]

11.4.0-37U SysNAND,

Boot9Strap 1.2

[Luma 8.0]

Luma3DS configuration/options:

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Clock+L2)

Autoboot EmuNAND: (No)

Use EmuNAND FIRM if booting with R: (No)

Enable loading external FIRMs and modules: (No)

Enable game patching: (Yes)

Show NAND or user string in System Settings: (Yes)

Show GBA boot screen in patched AGB_FIRM: (Yes)

Patch ARM9 access: (No)

Set developer UNITINFO: (No)

Smash-Selector Settings:

SaltySD: Enabled

Region: USA

Game Type: Cartridge

Explanation of the issue:

With the code.bin file inside of the folder with the USA Smash 4 Title ID in the titles folder for game patching.  When using the cartridge version of Smash 4, the game crashes

Steps to reproduce:

1. Using Smash-Selector, download the code.bin
2. Launch Smash 4 Cartridge through Smash-Selector or by itself

[Dump files (opened through Smash-Selector (0) and my itself (1))](https://github.com/AuroraWright/Luma3DS/files/1062935/dumps.zip)

![Error Message](https://user-images.githubusercontent.com/24654288/26959617-83b520e4-4c96-11e7-81dc-87ec6322494d.jpg)

**Comment by AnalogMan151** [comment]
Smash opens fine for me. More details?

New or old 3DS. Any romfs mods like music or stages? Any locale setting changes?

**Comment by DewGaming** [comment]
Moving the code.bin file seemed to fix the issue.

This is weird, as the pirated, digital version that the physical cart (which was the one having problems) replaced worked fine with the code.bin.

It seems like having a code.bin in the luma/titles/[USA Smash Title ID] folder is what's causing the crash to occur.  I can try with an ips file quick.

**Comment by ntojr123** [comment]
yeah me too im having the same problem opening things like crt quake and stuff like tthat but i dont know where to move code.bin or what it even is sorry im new to this please help im on luma cfw 8.0 right now and b9s 1.2

**Comment by wkocbz** [comment]
Hi , i had the same problem, but i resolved it.
you open the luma menu ( start the console with power+select) and disable  gaming pathing.

**Comment by ntojr123** [comment]
So I did that and it did not do anything now it says undefined instruction and then says you can find a dump in the following file dumps/arm11/crash_dump_00000042.dmp. right now I do not think luma 8.0 is stable so just try to wait for next update but any help would be appreciated.

**Comment by TuxSH** [comment]
Try this build of the latest commit:
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1062691/boot.zip)

**Comment by ntojr123** [comment]
How do I load that boot?

**Comment by TuxSH** [comment]
you replace the current boot.firm at the root of your sd card?

**Comment by DewGaming** [comment]
I tried using the provided boot.firm file in the zip file, but that file only leads to an infinite black screen.  I have the boot.firm on the sd card and have tried it was the boot.firm on the root, as well as a payload using Luma's chainloader.

**Comment by ntojr123** [comment]
Ok so don't use that boot?

**Comment by DewGaming** [comment]
I updated the original comment with more info, including where I got the code.bin as well as the settings I have for Luma and Smash-Selector (if it makes a difference)

**Comment by ntojr123** [comment]
But where do I download the code.bin to fix it but anyways I'm about the Same settings two but with game patching​ disabled

**Comment by DewGaming** [comment]
Read the "Steps to reproduce" section

**Comment by ntojr123** [comment]
I did smash works fine for me but I'm talking about other applications but do I move the dump files or something

**Comment by WilliamImm** [comment]
Appear to be getting this very same error. Using Smash Selector 2.2. Tried using Luma 8.0 and nightlies, used code.bin from Smash Selector 2.2, nothing seems to be working for me.

![img_20170618_210831](https://user-images.githubusercontent.com/1304819/27267609-46f669fc-546f-11e7-8e33-67fe60e5551e.jpg)
[Crash dump file](https://www.dropbox.com/s/rjrfvvoxt8y2rpb/crash_dump_00000016.dmp?dl=0)

**Comment by ghost** [comment]
Could anyone with this issue try a later commit like [this one](https://astronautlevel2.github.io/Luma3DS/builds/Luma3DS-1782827.zip)? Thanks.

**Comment by DewGaming** [comment]
Still crashed the game, even on the latest nightly 0fbdeee3 that I got from https://jenkins.hakujou.fr/job/3DS/job/Luma3DS/

**Comment by WilliamImm** [comment]
@Hikari-chin I've tried a Luma nightly at the time to see if it would avert the crash, it still doesn't. In fact, I think it's the exact same one that you've linked here.

**Comment by ghost** [comment]
Just to clarify, @DewGaming, the Smash mod you're trying to use is compatible with whatever update of Smash you have installed (or the original if none installed, etc.), right?

**Comment by DewGaming** [comment]
Even without a saltysd folder on my sd card root, the game still crashes

**Comment by WilliamImm** [comment]
I've tried with the latest version of Smash Selector, using IPS patches. System still crashes, this time with a data abort.

**Comment by thunderkai** [comment]
I have this issue too

**Comment by angelmarlboro** [comment]
luma 8.1 dosnt correct this bug? you must selec in te luma boot menu Disable ARM11 exeption handlers

https://gbatemp.net/threads/2-issues-and-2-doubts-and-arm11-exception.475467/page-2

**Comment by WilliamImm** [comment]
Tried, the game just crashes directly to the 3ds home menu instead.

**Comment by ghost** [comment]
@angelmarlboro @William-Imm Note that you forfeit your right to make or comment on GitHub issues if you choose to enable this option, as specified in the config option description. Disabling this option prevents us from getting valuable crash information when issues happen.

**Comment by ntojr123** [comment]
I'm quite confused about that because how in the hell are we supposed to tell them what's wrong

**Comment by ntojr123** [comment]
For most of the apps it just brings me to the home menu and says needs to restart system

**Comment by ghost** [comment]
Exactly, @ntojr123.  Keeping that option enabled allows us to get a  general idea of what went wrong. With that option disabled, there's no feasible way to trace where the crash came from. It's best to keep it enabled; the only situations I can see where it's viable to disable them (enable that option) is if you have a child or similar that is scared by all the numbers and letters they cannot understand, or if you're using an improperly made (buggy) homebrew or hack that causes crashes.

**Comment by ntojr123** [comment]
I think that it should be different so that you can tell them what is wrong to try to fix them but yeah I understand you

**Comment by WilliamImm** [comment]
Understood, the option to disable the exception handler is disabled and will remain disabled. Only tried it out to see if it would work at all, and the answer is no.

[Attached relevant crash dump I've prepared earlier (data abort, using SaltySD IDS patches)](https://www.dropbox.com/s/60708pnldmm8msb/crash_dump_00000027.dmp?dl=0)

**Comment by ntojr123** [comment]
So what do we do now?

**Comment by ghost** [comment]
It's being looked into; that's why this issue is still open. Rest assured, I'll post a status update when something relating to it is found.

**Comment by yamato05** [comment]
I also have the same problem with Hyrule Warrior Legends.
Adventure mode causes the exception but the Legend mode is fine.

https://www.dropbox.com/s/nox864gc5pphn52/crash_dump_00000016.dmp?dl=0

**Comment by heyrict** [comment]
I had the same error after updating from luma6.6 to luma8.1 when starting sysnand, while emunand works fine for me. Should I open a new issue?

**Comment by astronautlevel2** [comment]
Can we get a summary of the thread up until now to make testing easier? This thread is a mess and it's hard to tell what people are doing that's breaking it (it sounds like you're using SaltySD _and_ luma patching?)

**Comment by ha1vorsen** [comment]
SaltySD through Smash Selector requires Luma patching to run. It utilizes the LayeredFS/IPS patching abilities of the CFW.

If OP hasn't, they should try updating to Smash Selector 2.3, which uses IPS patches instead of code.bins. Then confirm that there is nothing other than the patch in luma/titles/(folder name with EDF at the and)/code.ips) Make sure absolutely nothing else is there as it may conflict.

**Comment by ghost** [comment]
@LinkSoraZelda The IPS patches cause even more issues, the older code.bin files work more often...

**Comment by ewormPL** [comment]
Trying to run a Pokémon Y hack (code.bin), same issue.

**Comment by ghost** [comment]
Going to go ahead and close this, given the recent Smash Selector release and mention of various issues on their side.

**Comment by ha1vorsen** [comment]
Not quite. Smash Selector and SaltySD will only fail to load and close with an exception if the user is running a non-American copy of Smash 4 on patch 1.1.7.

This user seems to be running the American copy, and this issue was opened befote 1.1.7 released.

**Comment by cetertel** [comment]
American copies of the game should be running perfectly fine, as nothing is needed after the 1.1.7 patch, like LinkSoraZelda said.

I am getting this same crash log and would be happy to give more crash dumps and pictures if you would like.

**Comment by EnderWeeb132** [comment]
Currently having the same problem, and have had for a while. I have Smash 4 on cart, updated to 1.1.7. Gives the same crash. Seriously we need a solution for this

**Comment by wazupttp90** [comment]
Have you guys tried taking the cia from the cart and installing as a eshop download

**Comment by shinra358** [comment]
SAME WITH LUMA 9.1
