### ISSUE TITLE
Input redirection C-Stick not working in games

### ISSUE THREAD

**Issue by justinappave** [LumaTeam/Luma3DS#494]
So input redirection is working perfectly on the home menu, C-Stick, ZL and ZR. But when entering a game like Monster Hunter Generations or Fire Emblem Echoes it stops working. All other controls still register. This is on a N3DS and using an Xbox One controller.

**Comment by sora10pls** [comment]
#487 

>The Rosalina menu reads buttons itself in the most basic way possible (through reading the HID_PAD hardware register). For the same reason InputRedirection won't work for it either.

**Comment by justinappave** [comment]
Oh didn't see that. Thank you!
