### ISSUE TITLE
[Suggestion] option to disable rosalina menu in luma config

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#496]
please give us the option to disable Rosalina menu.

I don't want to open it by accident, while in a game. or have my kids open it and mess around in it by accident. maybe add an option to disable it from the config screen. 

Thank you for your time.

**Comment by sora10pls** [comment]
While the odds of you pressing (L) + (Down) + (Select) all at the same time seem extremely slim, this would be a nice option.

**Comment by TuxSH** [comment]
Not possible, sorry.

**Comment by Gudf** [comment]
@bladesdnm Well, you can still change the combo by something like A+B+X+Y+Up+Right+L/R, or something using Select/Start+A/B/Y/X+R, which would really be nearly impossible to do unless you know how (and want) to do this.

**Comment by TuxSH** [comment]
Oh, yeah, you can change the combo.

**Comment by Valeri0p** [comment]
Why you can't? 
Rosalinda is so interconnected with Luma?

**Comment by ghost** [comment]
the combo don't save/resets. why even have the option to change it if it don't work? 
why even suggest that as a solution u know damn well it don't work

**Comment by Gudf** [comment]
#542  
Wait for next release.
