### ISSUE TITLE
(REPRODUCABLE) An exception occurred - Data abort

### ISSUE THREAD

**Issue by PolarisBeaver** [LumaTeam/Luma3DS#501]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.4.0-37U SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[8.0]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Before)

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**
An exception occurred screen pops up when closing System Settings to return to the Home Menu after entering and exiting Nintendo DS Connections.

**Steps to reproduce:**

1. Launch System Settings

2. Press Internet Settings (and enter PIN if applicable)

3. Press Nintendo DS Connections, then OK to confirm launching

4. After the Nintendo DS Connections interface loads, press B or click the Back button to go back to System Settings

5. Press Back, and finally Close to close System Settings and return to the Home Menu.

6. Luma will pop up with the exception screen.

**Dump file:**

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1051237/crash_dump_00000000.zip)

**Comment by holly-hacker** [comment]
Can reproduce on o3DS, 11.4.0-37E.
[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1051750/crash_dump_00000000.zip)

**Comment by sora10pls** [comment]
#453

**Comment by TheMCNerd2017** [comment]
Was able to reproduce this glitch successfully on a N3DSXL running firmware 11.3.0-36U. 
![img_1120](https://cloud.githubusercontent.com/assets/25375242/26785891/90f5a358-49d2-11e7-9c02-681399376141.JPG)
Here is the dump file that was created.
[crash_dump_00000020.zip](https://github.com/AuroraWright/Luma3DS/files/1052119/crash_dump_00000020.zip)

EDIT: Forgot to include the details below.

Version: Luma 8.0
Entrypoint: B9S 1.2

**Comment by sora10pls** [comment]
Reminder that my comment references an issue with this same problem, and that it happens with stock devices too...

**Comment by shinji257** [comment]
I've also been able to reproduce this using the steps in the OP.  Personally, I would have never spotted this... I never go into that screen. >.<

Firmware: 11.4.0-37U
Device: New 3DS
Boot Method: B9S 1.2
Luma 3DS Release: v8.0

Dump: [crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1052292/crash_dump_00000000.zip)

Screenshot:
![unf6jmo](https://cloud.githubusercontent.com/assets/261005/26788670/01f5d9b6-49dc-11e7-973a-658c64b22e21.jpg)

Copy/pasteable version (yes I typed all of this)
```
An exception occurred

Processor:       ARM11 (core 0)
Exception type:  data abort
Current process: menu (0004003000008F02)

R0     00003FFF       R1     0032E950
R2     00000000       R3     00344FA0
R4     00000000       R5     00000002
R6     08000080       R7     00000001
R8     0032D5F8       R9     0032D680
R10    00000000       R11    00343650
R12    00065FF0       SP     0FFFFF58
LR     002330CC       PC     00117D9C
CPSR   20000010       FPEXC  00000005

You cna find a dump in the following file:
dumps/arm11/crash_dump_00000000.dmp

Press any button to shutdown

Stack dump:

0FFFFF58: 00 00 00 00 02 00 00 00
0FFFFF60: 80 00 00 08 CC 30 23 00
0FFFFF68: 00 00 00 00 03 D5 09 51
0FFFFF70: FF FF FF FF FF FF FF FF
0FFFFF78: 00 03 00 00 00 00 00 00
0FFFFF80: 01 00 00 00 38 38 02 00
0FFFFF88: 00 00 00 00 00 00 00 00
0FFFFF90: 00 00 00 00 00 00 00 00
0FFFFF98: 00 00 00 00 00 00 00 00
0FFFFFA0: 00 00 00 00 00 00 00 00
0FFFFFA8: 01 01 00 00 00 00 00 00
0FFFFFB0: F8 D5 32 00 78 02 34 00
0FFFFFB8: 01 01 00 00 01 00 00 00
0FFFFFC0: 00 00 00 00 00 00 00 00
0FFFFFC8: 00 00 00 00 54 50 10 00
0FFFFFD0: 00 00 00 00 00 00 00 00
0FFFFFD8: 00 00 00 00 00 00 00 00
0FFFFFE0: 00 00 00 00 3C 23 10 00
0FFFFFE8: 00 00 00 00 00 00 00 00
```

**Comment by holly-hacker** [comment]
As @sora10pls mentioned, this is a known issue. See the issue he linked for an explanation. I think this issue can be closed.

**Comment by sora10pls** [comment]
Is nobody gonna read my comment

**Comment by TuxSH** [comment]
This is actually a bug in Nintendo's code, and want unoticed because HM was siletenly terminated.

Worked around (fixed) in latest commit anyways.

**Comment by Masterpokeagsg** [comment]
Currently updated to B9s 1.2 and luma 8.0 I appeared the error that many happened to them, like the one that creates a file called Crashdump in old 3ds Luma / dumps / arm11 / crash_dump_00000000.dmp
I can not take a photo I'm sorry :(. Forget to put
- Old 3DS
- B9s 1.2 w/ Luma 8.1
- Firmware: 11.4.0-37U

**Comment by Margen67** [comment]
@Masterpokeagsg You need to use this build. https://github.com/AuroraWright/Luma3DS/files/1056537/boot.zip

**Comment by Masterpokeagsg** [comment]
Thanks bro


2017-06-06 4:40 GMT-04:30 Margen67 <notifications@github.com>:

**Comment by jnozsc** [comment]
thanks everyone who worked on this issue.
It seems I met the similar issue when I try to setup luma by following this doc 
```
3ds.guide/installing-boot9strap-(browser)
```

I am not sure whether I should create a new issue or reply here.

here is the screenshot and dump file

![img_6192](https://user-images.githubusercontent.com/470215/27256985-d7ce9ac0-537b-11e7-86c9-4dba63f017b9.JPG)


[crash_dump_00000008.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/1082820/crash_dump_00000008.dmp.zip)

thanks!

**Comment by jnozsc** [comment]
some addition info.

old 3ds ll, US region.
version 4.5 (If I don't misremember it)

**Comment by jnozsc** [comment]
I have tried the latest public release version and nightly version, neither works

**Comment by jnozsc** [comment]
sorry for previous post in this ticket, notice it is my side's issue. thanks

**Comment by XiNaru** [comment]
That unfortunately did not help me .... I have the firmware 11.4.0-37E Luma 3DS 8 and boot9strap. Yesterday updated and came with me just in a game, after the use of an ntr cheats, and now the savegame is not right anymore.

Translated with google translator from the german

**Comment by PolarisBeaver** [comment]
Ihre Spiel speichern Datei ist zerstört? Ruiniert? Das ist ein anderes problem. Es ist nicht mit Luma3DS verwandt. Es ist ein Problem mit NTR.
Übersetzt mit Google

Your game save file has become destroyed? Ruined? That is a different problem. It is not related to Luma3DS. It is a problem with NTR.
Translated with Google

**Comment by XiNaru** [comment]
But is the same error. Arm11: an exception occured. So I thought there was a connection between ntr and arm11, since I had before the update on boot9strap 1.2 and on luma 8 no problems with ntr had had.

Translated with google translator from the german

**Comment by atom505** [comment]
can you help me also? 

I am have a problem with 

"you can find  a dump in the following file:
dumps/arm11/crash_dump_000000010.dmp

**Comment by LiberoPat** [comment]
Has the issue pulled up by OP been fixed? I'm switching from Reinand to B9S & Luma and this same exact problem is occurring right now when I boot up my N3DS which has 9.2.0 sysnand.

-update: now trying to save the microsd where the error occurs in, since I have several games in it. Tried deleting files and folders created when following 3ds.guide but error still occurs when this memory card is inserted. Trying to figure out why. 
I think the error may have occurred when I tried to installing b9s with instructions on how to with a stock N3ds, forgetting I had arm9hax installed already. Not sure, but it's my only fault.
Will try to reinstall luna and b9s with a new memory card and hopefully fixes this bug.

-ok I solved my issue, by pressing select and checking "auto-boot emunand" along with show in system settings, and now I'm good~

-update 2: I don't think I've successfully installed B9S due to this issue :/
-final: solved all issues by updating sysnand to latest firmware..

**Comment by Fuantei2** [comment]
> -ok I solved my issue, by pressing select and checking "auto-boot emunand" along with show in system settings, and now I'm good~
>-update 2: I don't think I've successfully installed B9S due to this issue :/
-final: solved all issues by updating sysnand to latest firmware..

Same as you, except for the final solution, i cant update my SysNAND because i cant access it, when i try with no select "auto-boot emunand" it pop up me the error or if i try turning on the 3DS without SD card it shutdown inmediatly, i only can access the EmuNAND (thanks to you), what did you do to update your SysNAND¿, from the EmuNAND or you could access your SysNAND without problems¿

Sorry about my english

**Comment by cactuar** [comment]
I have the same problem, I can only access my emunand. How did you update your sysnand? Thank you!

**Comment by cactuar** [comment]
You can try to update your sysnad booting in recovery mode
https://3dbrew.org/wiki/Recovery_Mode
Use it at your own risk!

**Comment by jeffdoho** [comment]
HI I have an issue with my new 3ds, it has a black icon, when I open it, it loads and says ( an exception occurred  arm11 (1) pre-fetch abort svc-break) any help please
