### ISSUE TITLE
[Bug] Error on starting Xenoblade Chronicles 3D (Digital version)

### ISSUE THREAD

**Issue by albluu** [LumaTeam/Luma3DS#502]
**System model:**

N3DSXL

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.0

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

On starting Xenoblade Chronicles 3D (digital), this error occurs:

An error occurred (ErrDisp)
Error type: generic
Process ID: 42
Process name: smallfol
Process title ID: 0x000400000f700100
Address: 0x003be900
Error code: 0xd900458b
Press any button to reboot

It crashes a few seconds after a save is loaded/new game is started. It also sometimes crashes on the loading screen, before the main menu.

**Steps to reproduce:**

1. Start Xenoblade Chronicles 3D

2. If it hasn't crashed already, start a new game or load a save file

**Dump file:**

Does not appear to have a crash dump location.

**Comment by ghost** [comment]
The EU version works fine, just updated to B9S 1.2 and Luma 8.0 and my game loads fine, and savegames too.
