### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by holly-hacker** [LumaTeam/Luma3DS#509]
Line 10 of README.md reads:
>Since Luma3DS v8.0, Luma3DS has its own in-game menu, triggerable by `L+Start+Select` (see the release notes).

`L+Start+Select` is not the default combination, it is `L+Down+Select`. Please fix, Luma is unusable without this patch.

**Comment by BigBrainAFK** [comment]
You could have put that into a pull request yourself and I don't think it makes Luma unusable.

**Comment by holly-hacker** [comment]
It was sarcasm, and I haven't used Git before to collaborate so I am not familiar with making pull requests on projects I don't own. Feel free to do it yourself, though.

**Comment by T3CHNOLOG1C** [comment]
Made a PR to fix, #510

**Comment by TuxSH** [comment]
Merged
