### ISSUE TITLE
Ds mode not working in emunand

### ISSUE THREAD

**Issue by topkeksphagetti** [LumaTeam/Luma3DS#51]

**Comment by topkeksphagetti** [comment]
This is from 5.1.2

**Comment by weegee721** [comment]
Same with GBA mode

**Comment by weegee721** [comment]
I tried repatching twl and agb firms with no luck

**Comment by RShadowhand** [comment]
Do [this](https://github.com/AuroraWright/AuReiNand/wiki/Installation-and-Upgrade#fixing-gbadsiwareextended-memory-games-issues)
