### ISSUE TITLE
Luma 8.0 makes 2DS stop booting

### ISSUE THREAD

**Issue by phtom** [LumaTeam/Luma3DS#513]
The new Luma 8.0 makes your 2DS stop working, thank god i had firm backup to make it work again! After the update it turned on and imediatly off.
After the update you cant even boot GodMod9.

**Comment by ADADEAF** [comment]
Same Problem, How do you resolve it? please

**Comment by ghost** [comment]
you likely didn't update B9S via SafeBoot9StrapInstaller, as 8.0 will not work with 1.0/1.1 B9S
