### ISSUE TITLE
Input redirector disabling 3ds joystick

### ISSUE THREAD

**Issue by Jan200101** [LumaTeam/Luma3DS#515]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E Sysnand

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.2

**Luma3DS version:**

8.0-21db0d4

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: (Before)

PIN lock: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

 3ds Joystick stops responding when Input redirector is active and ingame (tested with Pokemon Omega Ruby, Smash Brothers and the Home Menu)

NOTE: I do not mean the C-Stick 

**Steps to reproduce:**

1. Start Input Redirector from Rosalina

2. Start a game

3. Try using the 3ds joystick ingame

**Comment by sora10pls** [comment]
#487 

>The Rosalina menu reads buttons itself in the most basic way possible (through reading the HID_PAD hardware register). For the same reason InputRedirection won't work for it either.

**Comment by Jan200101** [comment]
Im talking about the normal joystick not the c-stick
I also added that to OP to make sure no one else thinks that

**Comment by TuxSH** [comment]
Make sure that your remote joystick is correctly calibrated, also start inputredir outside of the game.

For ΩRαS, while it'll prevent the game from disconnecting from the Internet, it will unfortunately prevent the game from using Internet features itself.

**Comment by Jan200101** [comment]
I am using a keyboard and the remote Joystick is fine.

Its the 3ds joystick that is causing the issue... You know
this thing.
![image](https://cloud.githubusercontent.com/assets/15076013/26819035/5c7a9ca2-4a9d-11e7-9b5e-ba50eb4b731d.png)

After more trying I cant get it to work after I connect my Input Redirection client to it, not even on the home menu
