### ISSUE TITLE
Opening the Rosalina while playing Pokemon Sun crashes both displays

### ISSUE THREAD

**Issue by TheMCNerd2017** [LumaTeam/Luma3DS#516]
Pretty self-explanatory issue, opening up the Rosalina Menu while playing Pokemon Sun(in the overworld, battles, cutscenes, etc) causes both screens to crash with corrupted graphics. The system itself does not crash, merely the screens since everything else is still functional. This issue persists until I power-off the console.

Here is a link to the image I took of the screen crash: http://www.imgur.com/a/YJ8Fx

EDIT: This issue does not happen while I am in the main menu or title screen.

**Comment by Gudf** [comment]
Have you tried it several times ? It crashed the first time for me, but everything is working just fine now, I can open and close the Rosalina Menu, nothing crashes.

**Comment by TheMCNerd2017** [comment]
Yes, I tried it several times. Every single time the displays would crash, but the game and all other things would still be fully functional.

**Comment by sora10pls** [comment]
From release notes:

>Minor issues: the menu can sometime freeze in some games (that will be attempted to be fixed before next release)

**Comment by TheMCNerd2017** [comment]
I read the release notes, so I know that. Just thought that I would report the issue as well as the game that causes the issue.

And by the way, this doesn't happen when I'm on the main menu or title screen.

**Comment by ghost** [comment]
can we have an option to disable the button combo from opening Rosaline menu please.

**Comment by Gudf** [comment]
I may have found a fix, but I'm not sure. Try checking or unchecking "Enable Game patching", launch the game, launch Rosalina Menu, close it and it should work (you can check or uncheck again "Enable game patching" after this).

**Comment by Margen67** [comment]
@bladesdnm #496

**Comment by TuxSH** [comment]
This happens somtimes. I'll attempt to fix that later (if possible) after fixing other issues.

> can we have an option to disable the button combo from opening Rosaline menu please.

Set it to an impossible combo.

**Comment by ghost** [comment]
why even have the option to set combo if it don't save
