### ISSUE TITLE
SD card removal shows "The Game card has been removed"

### ISSUE THREAD

**Issue by gingerbeardman** [LumaTeam/Luma3DS#521]
SD card removal shows "The Game card has been removed"
I do not have any Game Card in my N3DS.

I am removing SD card on Homebrew Launcher to hot swap some files.

Regardless of whether or not the error should appear, it should mention SD card rather than Game card

**Comment by fincs** [comment]
From the hbmenu readme:

> You should not hotswap the SD card while hbmenu is running since it compromises the 3DS OS's stability amongst other things. It is recommended that you instead use a file transfer homebrew application such as ftpd to transfer files without rebooting.

**Comment by gingerbeardman** [comment]
Thanks @fincs it seems to be a bad habit I've gotten into (SD hot swapping is advice given in the latest 3ds.guide for example)
