### ISSUE TITLE
Changing the Rosalina menu button combo only allows one button AND doesn't persist after reboot

### ISSUE THREAD

**Issue by Aluminite** [LumaTeam/Luma3DS#529]
**Explanation of the issue:**

Changing the Rosalina menu button combo only allows one button

**Steps to reproduce:**

1. Enter Rosalina menu

2. Change button combination under misc, attempt to use multiple buttons

As soon as you press the first button, it says `Successfully changed the menu combo.` without letting you press more than one.

For the second issue, just restart your system.

**Comment by acelerador25** [comment]
In this case it's necessary to press all the buttons at the same time, then, after the reboot, is true that the code is not permanent, and is necessary for the future

**Comment by sora10pls** [comment]
That's... not a bug?

Refer to #489 and #491.

**Comment by pillows2** [comment]
You can use multiple buttons but you have to press them all at once.

**Comment by TuxSH** [comment]
"only allows one button". This was fixed in the latest commits, see here: 
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1056541/boot.zip)

I'll do the other part.

**Comment by JerryWester** [comment]
I'm not fantastic at understanding the processes behind Luma, but I suggest you write the combination to a .bin in the /luma folder and read from it at boot and after it's written to.

**Comment by ghost** [comment]
@TuxSH Is saving the hb. app application being worked on as well?

**Comment by Shadow322** [comment]
What? "Saving the homebrew application application being worked on as well?"

**Comment by ghost** [comment]
@Shadow322 Saving the app that hb. app was injected into to a file on the SD card, that way we can have a designated, quick loading homebrew launcher

**Comment by acelerador25** [comment]
Ok, I try the new code sistem of Rosalina and is ok for me (press the buttons 1 by 1), but any please can make this code wearable after the reboot?

**Comment by acelerador25** [comment]
@Margen67 I say this: When you enter Rosalina for the first time (in this case after power-up) you put the oficial code, then you change the code, after the game play, you shut down the console, but if you power-up again, the code you put before it doesn't work and again need to change the code. In this case I ask that they can change the code permanently if I do a reboot in the 3ds

**Comment by Auscobe** [comment]
from the looks of some recent happenings, i'm starting to wonder whether or not Luma3DS is slowly losing some of its "noob-friendlyness"

Example: Rosalina. 'nuff said.

**Comment by mysterypaint** [comment]
What if Rosalina shortcut keys were configurable from somewhere within the /luma/ folder as a .txt? It could solve this issue, as well as the issue for people with broken buttons.

**Comment by Auscobe** [comment]
good idea, i feel that should be implemented

also, Rosalina was a kind of feature i had imagined being in Luma, but at the time i didn't have a Github account.

**Comment by ghost** [comment]
I referenced these enhancements [here](https://github.com/AuroraWright/Luma3DS/issues/619). Going to close this now. Thank you.
