### ISSUE TITLE
[BUG] Luma config changes don't stay if you boot into a payload/shut down right after

### ISSUE THREAD

**Issue by Aluminite** [LumaTeam/Luma3DS#531]
**System model:**

Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

Doesn't apply

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.0

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Doesn't apply)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: (X)

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

Luma config changes don't stay if you boot into a payload/shut down right after.

**Steps to reproduce:**

1. Boot into Luma settings

2. Make any change, press start, let go and start holding start immediately after

3. Once in chainloader menu, press power

4. Config should go back to how it was before you changed anything

**Dump file:**

Doesn't apply

**Comment by TuxSH** [comment]
Latest commit fixes this.
