### ISSUE TITLE
Extended Memory games don't load after updating B9S & Luma (SSB, MH4, Pokemon Sun, MHGen)

### ISSUE THREAD

**Issue by baabon** [LumaTeam/Luma3DS#532]
<b>System Model:</b> Old3DSXL

<b>SysNAND version:</b> 11.4.0-37U SysNAND

<b>Entrypoint:</b> Boot9strap 1.2

<b>Luma3DS version:</b> 8.0 (latest release)<hr>

<b>Luma3DS configuration/options:</b>

Default EmuNAND: ( 1 )
Screen brightness: ( 4 )
Splash: ( Off )
PIN lock: ( Off )

Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Use custom path: ( )
Enable game patching: ( <b>X</b> )
Show NAND or user string in System Settings: ( )
Show GBA boot screen in patched AGB_FIRM: ( )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )<hr>

<b>Explanation of the issue:</b>

After updating B9S 1.2 + Luma3DS 8.0 <i>(from B9S 1.0 & Luma3DS 7.1)</i> games that require to work on <i>Larger RAM Mode</i> like Monster Hunter or Super Smash Bros. haven't loaded anymore.
After shows 3ds logo the screen stays black and I must to hard reset the system.

I tried to get back B9S 1.0 + Luma3DS 7.1 <i>(when all my games worked fine)</i>, but the issue still persists.

<b>Note:</b> After I updated B9S and Luma3DS, I ran homebrew launcher <i>(with the new option of Luma)</i> and I executed tikSweep <i>(to clean all unused tickets)</i> and next cthulhu <i>(to clear my play time, step and software history)</i>.<hr>

<b>Steps to reproduce:</b>

1. Open a <i>Larger RAM</i> game (Super Smash Bros.)
2. System shows a black screen and I can't go to Home Menu pressing Home Button.
3. Try to Hard Reset or Power Off.
<br>

**Comment by TuxSH** [comment]
Can't reproduce.

**Comment by digidude512** [comment]
[crash_dump_00000008.zip](https://github.com/AuroraWright/Luma3DS/files/1053594/crash_dump_00000008.zip)
**System Model:** N3DSXL

**SysNAND version:** 11.2.0-35E SysNAND

**Entrypoint:** Boot9strap 1.2

**Luma3DS version: 8.0** (latest release)

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 )
Screen brightness: ( 4 )
Splash: ( Before )
PIN lock: ( Off )
New 3DS CPU: ( Clock+L2 ) (Also applies to off)

Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Enable game patching: ( X )
Show NAND or user string in System Settings: ( X )
Show GBA boot screen in patched AGB_FIRM: ( X )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )

**Explanation of the issue:**

After updating B9S 1.2 + Luma3DS 8.0 (from B9S 1.0 & Luma3DS 7.1) much like @baabon  games that require to work on Larger RAM Mode like Pokémon Sun and Moon After shows 3DS logo I get
**An exception occurred**
Processor: ARM11 (core 0)
Exception type: data abort
Current process: niji_loc (0004000000164800)

Dump Attached.
[crash_dump_00000008.zip](https://github.com/AuroraWright/Luma3DS/files/1053593/crash_dump_00000008.zip)

Edit: Disabled Game Patching and Sun now boots, Unsure if No Line Patch is not working with Luma 8.0 or is a bug with Luma.

**Comment by xelrix** [comment]
I cant reproduce these either.
Similar setup albeit on an o3ds.
Playing MHXX just fine. With and without translation patch (patched through ntr). With and without ntr.
No luma patching though.

**Comment by digidude512** [comment]
@xelrix Do you have Pokémon Sun or Moon? I can ZIP my No Line and see if that has the same problem?

**Comment by xelrix** [comment]
No I dont. You could try disable game patching in luma menu and try reloading the game.

**Comment by baabon** [comment]
In my Old3DS I tried disabling the game patching from Luma Menu, but the issue still persists. I uninstalled Smash Bros and installed again (different backup) and it's the same.

**Comment by gnkz** [comment]
I don't know if this is related but

**System Model:** N3DSXL

**SysNAND version:** 11.4.0-35E SysNAND

**Entrypoint:** Boot9strap 1.2

**Luma3DS version:** 8.0 (latest release)

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 )
Screen brightness: ( 4 )
Splash: ( Off )
PIN lock: ( Off )
New 3DS CPU: ( Off )

Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Enable game patching: ( )
Show NAND or user string in System Settings: ( X )
Show GBA boot screen in patched AGB_FIRM: ( )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )

**Explanation of the issue:**

Pokemon moon backup crash after nintendo 3ds logo. I don't have any other game to test at the moment.

[crash_dump_00000002.zip](https://github.com/AuroraWright/Luma3DS/files/1055665/crash_dump_00000002.zip)
![img_06062017_115332](https://user-images.githubusercontent.com/6633835/26838906-8bf100f4-4aaf-11e7-9293-1d926304257a.jpg)
![img_06062017_115336](https://user-images.githubusercontent.com/6633835/26838905-8befdb0c-4aaf-11e7-9849-fe9bcd6ad9da.jpg)

**Comment by TLNiles** [comment]
2DS, Game patching on, MHXX(with LayeredFS patch) and Pokemon Moon runs normally. Also running latest b9s and Luma 8.0 stable.
Might be some sort of console issue, just no idea what kind of it.

**Comment by srwgin** [comment]
do you change region？if changed you should system format or you can not play larger ram game

**Comment by acelerador25** [comment]
I try to play the Smash cartidge in my old and I don't have any problems. In this moment I try to play my Revelations and Sun cartridge, my Moon and Meta Gear cias and then post the results (I have active the patching active but only for a dlc of fates)

Edit: I don't have problems in the games I say before

**Comment by baabon** [comment]
I never did a <i>region change</i> with my O3DSXL. Yesterday, I did a <b>9.2.0 CTRTransfer</b> <i>(always of my region USA)</i>, never happened. Reinstalling the game don't work. Import the seed neither.

**Comment by james-d-elliott** [comment]
Did you use a clean CTR Transfer bin from the guide?

**Comment by baabon** [comment]
@james-d-elliott Yes

**Comment by JackAttack2** [comment]
i have this problem too, SuMo get stuck on black screen, no game patches.

**Comment by JackAttack2** [comment]
i get this dump file
[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1059562/crash_dump_00000000.zip)

**Comment by srwgin** [comment]
backup nand and nintendo3DS folder first
then try system format after that see what happen

**Comment by baabon** [comment]
An user in another forum tried a System Format but it doesn't work. There is a similar issue when you do a Region Change.

I'll try using a friend's Pokemon Moon cartridge tomorrow, so I'll tell you about what happened.

**Comment by srwgin** [comment]
I have 2 region change emunand after system format Pokémon moon worked

**Comment by baabon** [comment]
Finally, I did a System Format and the issue has been solved.

**Comment by andamirorulez** [comment]
Hello, i cant boot smash 4
New 3ds, luma 8 + b9s 1.2 , 11.4.0-37U SysNAND
It stuck in 3ds boot logo, any fix for this or how to solve it?

**Comment by andamirorulez** [comment]
The only option i have selected, is show "sys" in configuration
