### ISSUE TITLE
Power off fails to shut down properly sometimes

### ISSUE THREAD

**Issue by LioMajor** [LumaTeam/Luma3DS#533]
**System model:** new3DS (EUR)
**SysNAND version (+emu/redNAND version if applicable):** 9.2 sysNAND / 11.2 emuNAND
**Entrypoint (How/what you're using to boot Luma3DS):** boot9strap 1.2
**Luma3DS version:** 8.0 Release

**Luma3DS configuration/options:** 

Default EmuNAND: (1)
Screen brightness: (4)
Splash: (none)
PIN lock: (no)
New 3DS CPU: (default)

--

Autoboot EmuNAND: (1)
Use EmuNAND FIRM if booting with R: (no)
Enable loading external FIRMs and modules: (no)
Use custom path: (no)
Enable game patching: (no)
Show NAND or user string in System Settings: (Yes)
Show GBA boot screen in patched AGB_FIRM: (no)
Patch ARM9 access: (no)
Set developer UNITINFO: (no)

--

**Explanation of the issue:**

Sometimes powering off fails until forcing power off.
(Both screens are off, power is still lit)
Problem did start after using boot9strap 1.0 > Luma3DS .firm.
Never had this problem on A9LH.
Booting flashcard instead of Luma3DS > power off works flawless.
Using GodMode9 (chainloaded) > power off works flawless.

**Steps to reproduce:**

Boot 3ds, use it a while, turn power off, either it powers off properly or it doesn't.

**Comment by TuxSH** [comment]
Can't reproduce
