### ISSUE TITLE
[Reproducable] System crash when closing homebrew from home menu

### ISSUE THREAD

**Issue by martinnnnnnnnnnnnnnnnnnn** [LumaTeam/Luma3DS#534]
**System Model:** New 3DS

**System Version:** 11.3.0-36U SysNAND

**Entrypoint:** Boot9Strap

**Luma Version:** 8.0 stable

**Luma3DS configuration/options:**
Default EmuNAND: (1)
Screen brightness: (4)
Splash: (Off)
PIN lock: (4)
New 3DS CPU: (Clock+L2)
Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Use custom path: ( )
Enable game patching: ( )
Show NAND or user string in System Settings: (x)
Show GBA boot screen in patched AGB_FIRM: (x)
Patch ARM9 access: ( )
Set developer UNITINFO: ( )

--

**Explanation:**
After launching homebrew with Luma 8.0's new homebrew compatibility, if you go back to the home menu and close the current app (homebrew), the system crashes.
**Steps to reproduce:**
1. Open the homebrew launcher through the application of your choice
2. Exit back to the home menu by pressing the home button
3. Press close on the current application
**Dump file:** 
[crash_dump_00000007.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/1053509/crash_dump_00000007.dmp.zip)

**Comment by TuxSH** [comment]
Probably APT shit, rebuild the homebrew with ctrulib updated to the latest commit (clone ctrulib, then `cd libctru && make install`).
