### ISSUE TITLE
Console freeze on 3dsx homebrew menu selection after changing Rosalina homebrew app

### ISSUE THREAD

**Issue by Flat** [LumaTeam/Luma3DS#536]
**System model:** New 3DS - USA
**SysNAND version (+emu/redNAND version if applicable):** 11.4.0-37U

**Entrypoint (How/what you're using to boot Luma3DS):** Sighax/Boot9Strap

**Luma3DS version:** Commit https://github.com/AuroraWright/Luma3DS/commit/4d219813fe9204ef814f18ff1bf675ae300262e1

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 ) (N/A)

Screen brightness: ( 2 )

Splash: ( Before )

PIN lock: ( Off )

New 3DS CPU: ( Clock+L2 )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( X )

Show NAND or user string in System Settings: ( X )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

If using a non-default app for Homebrew through Rosalina only the initial 3dsx will boot (boot.3dsx) attempts to launch any other 3dsx file through the homebrew menu freeze the console. If using homebrew_launcher_loader all 3dsx's will launch without freezing.

**Steps to reproduce:**

1. Set home & safety as the Rosalina homebrew app

2. Close home & safety

3. Launch home & safety

4. try to launch a 3dsx from homebrew menu

5. ???

**Dump file:**

**Comment by TuxSH** [comment]
For _some_ reason it doesn't work with H&S (due to APT maybe)? homebrew_launcher_loader works, Download Play too.
