### ISSUE TITLE
Potential for patch to block decrementing demo plays?

### ISSUE THREAD

**Issue by vaguerant** [LumaTeam/Luma3DS#54]
Is there any chance we could get a patch to launch demo titles without decrementing the number of plays remaining or otherwise bypassing the limited-play system? Some demos would particularly benefit from this, e.g. Bravely Default's demo features content that is unique to the demo, not a subset of the retail game. Being able to play this indefinitely (which is, admittedly, already possible via HANS), would improve it greatly, in addition to being more convenient and, probably, stable than using HANS to do the same. There are many titles that currently don't cooperate with HANS, including a large proportion of demos.

According to @yifanlu: "I think it should be easy. likely a home menu patch somewhere"

**Comment by TuxSH** [comment]
Atm I've no idea about which service commands are used to store the updated count, something I'd like to know.

**Comment by poutros** [comment]
I think lauching through homebrew doesn't decrement the demo plays.

**Comment by vaguerant** [comment]
**EDIT** _This was in response to a since-removed comment._ **/EDIT**
I think that depends on how they're launched. As far as I know, launching titles via RegionFour does, but via HANS doesn't. Obviously they operate in pretty significantly different ways, but I'm not sure how much help that is for someone looking to do it directly in CFW.

**Comment by TuxSH** [comment]
Yes of course, it's HomeMenu who decreases the counter. But how exactly?

poutros: read the first post please ;)

**Comment by RShadowhand** [comment]
The demo counter is held in the header. It's decreased by HomeMenu each
time it's launched through HomeMenu.

**Comment by TuxSH** [comment]
Of course I knew that (3dbrew), but how precisely is it done... ?

**Comment by RShadowhand** [comment]
That is up for research. I just know that it's counted in the header, and HomeMenu decreases it each time you run it. Which is why HANS can launch it without decreasing the numbers.

**Comment by TuxSH** [comment]
Yes of course ...
But I'll be busy the next two weeks...

**Comment by rboninsegna** [comment]
FWIW, I can delete the AM driver's save without ill effects.

I don't have an unpatched demo I could try it on right now, though!

**Comment by llakssz** [comment]
I played with demo counts last year I think, patching the ticket and deleting the correct system save both work.
Although in a weird case I found (and another user too) - when the ticket was patched, sometimes (rarely) the correct demo count would return...

But yes this would be useful and nice to have in cfw!
If we have this, permanent 300 coins would be nice too.

**Comment by Hartie95** [comment]
@llakssz The eshop resets the tickets you own on start, so the counter will return.

**Comment by Slashin-it-up** [comment]
Use homebrew, also there is a tool for resetting play count
