### ISSUE TITLE
[BUG] Luma 8.0 "Region Settings" emulation function is broken

### ISSUE THREAD

**Issue by CaiMiao** [LumaTeam/Luma3DS#541]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37J SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.2

**Luma3DS version:**

8.0 pre-release

**Luma3DS configuration/options:**

New 3DS CPU: ( x )

Enable game patching: ( x )

**Explanation of the issue:**

I created the locale.txt for title 000400000008B500 (Mario Kart 7 - iQue official Simplified Chinese) as
`CHN ZH CN 01`
and after starting the game, both screen turned pure red and freezed. Long press shutdown is needed.
I think this problem will also reproduce on other region version of MK7.

Also I heard my friend's Rhythm Heaven Megamix (US) can't run anymore on his Japan console as region emulation is broken.

One more thing, the Luma wiki should update region emulation section, to give more detailed option for region emulation. (e.g. state/province code)

One more thing again, a suggestion, to edit locale emulation settings directly via Rosalia?

**Comment by CaiMiao** [comment]
![tim 20170606134316](https://cloud.githubusercontent.com/assets/4640483/26815300/25ade938-4abe-11e7-950a-b41ee75035ee.jpg)

**Comment by Jan200101** [comment]
Able to reproduce with my EU copy.

**Comment by TuxSH** [comment]
Possibly missing chinese font, maybe potentially missing chinese data with MK7?

What if you try with EUR FR (for example)?

> One more thing, the Luma wiki should update region emulation section, to give more detailed option for region emulation. (e.g. state/province code)

Sure, later.

**Comment by retrofank** [comment]
Yes, a better detailed explantion on the Wiki would help on this please.  See this thread here:

http://gbatemp.net/threads/updating-to-b9s-2-0-luma-8-0-has-broken-language-region-on-some-games.473258/#post-7371356

**Comment by Red1812** [comment]
From my testing I found out that if you have a locale.txt for a game it will not be able to access the SD card to read the DLCs. RomFS and language emulation still work but games can't access the SD card for the DLCs. If you remove the locale.txt, RomFS still works and DLCs are available again.
Hope that helps.

**Comment by CaiMiao** [comment]
No, the game will load font from game itself, that's not the problem.
MK7 added corresponding region data of CN / HK / TW at 1.1 update for all region, and the patch content is embedded on MK7's Chinese release (iQue console preinstalled / TWHK cardrige).

I also afarid this would have a potential chance to break your SD card's FS,
as my SD card got some weird problem after it happened.
According to @Red1812 's information, forced access attempt is weird.

The only reason I would try out the new region emulation is, I can change the country information to China which is really shiny as I didn't got an iQue console.

**Comment by TuxSH** [comment]
All titles are given SD access now.

**Comment by Red1812** [comment]
I tried EUR EN, EUR EN EN 01, EUR EN UK 01 and EUR EN UK in the locale.txt. The games does start in English but when I try to access DLCs it says it can't find the SD Card.
If I remove locale.txt, the game stats in my console language and the DLCs work normally. If you want me to test something else I'll be happy to help.

**Comment by TuxSH** [comment]
Please try the latest commit which you can find below.
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1055982/boot.zip)

**Comment by Red1812** [comment]
Yes that works. I tried with EUR EN in locale.txt. The game launches in English, it has access to the DLCs and the shop and RomFS works too.
Do you want me to try something else?

**Comment by TuxSH** [comment]
Hmm idk. Probably other regressions if you see them.

**Comment by CaiMiao** [comment]
Sorry but,
**Country / state emulate** introduced in Luma 8.0 (a.k.a **Better language emulation**) still freezes (but no more red screens) the MK7, as i tried `CHN ZH CN 01` and `CHN ZH CN`.
Only language emulation `CHN ZH` is ok but lack of new **region emulation**.

**Comment by CaiMiao** [comment]
**(Please reopen this issue as it's not solved yet)**

I also tried Pokemon Moon (title `0004000000175E00`), with `CHN ZH CN 01` also freezes at loading.

MK7 freezes on logo and Pokemon Moon freezes on black screen.

![tim 20170607030248](https://user-images.githubusercontent.com/4640483/26846928-d895365e-4b2d-11e7-9411-5fe3ec3bf18d.png)

**Comment by Red1812** [comment]
I tried EUR EN EN 01, no freeze, DLCs are working. 
I tried EUR EN UK 01, same which is strange because UK is not in the list of countries if I read correctly patcher.c
@CaiMiao Have you tried CHN ZH ZH 01?

**Comment by CaiMiao** [comment]
@Red1812 tried just now, freezes.

**Comment by Red1812** [comment]
Do you have another Chinese game you could try this on?
@TuxSH Are the country and state ID optionals in locale.txt? I assumed they are since it's working for me without them but that might not be the intended behaviour.

**Comment by CaiMiao** [comment]
@Red1812 Yes the country and state ID optional, I tested.
But I'm preferring country & state/province emulation working then I can have my country flag showing.

Pokemon Sun & Moon are global titles which includes Chinese language & **country/region information**, so they should be good sample to inspect problems.

**Comment by CaiMiao** [comment]
http://gbatemp.net/threads/updating-to-b9s-2-0-luma-8-0-has-broken-language-region-on-some-games.473258/#post-7373732
This guy's Rhythm Heaven is still not working.

And I tested `EUR EN UK 01` or `EUR EN EN 01` on Pokemon Moon still freezes.

**Comment by TuxSH** [comment]
try `EUR EN GB 01`

**Comment by CaiMiao** [comment]
@TuxSH still freezes Moon.

**Comment by Red1812** [comment]
I tried EUR EN GB and EUR EN GB 01 on Mario Kart 7 (eshop EUR) and it freezes with red screens.
It tried EUR EN GB on FE Fates and it worked normally. I guess the game doesn't have anything linked to the country.
So it seems the country part of locale.txt is not working properly.

**Comment by AuroraWright** [comment]
For people having issues with the latest commit @TuxSH posted, are you trying to use a Japanese/American/European game on a different region (Chinese, Taiwanese, Korean) console or vice-versa? If so, note that Chinese/Korean/Taiwanese consoles have each a different font (the font is the same in European/Japanese/American ones) so that could cause the crashes.

**Comment by TuxSH** [comment]
@CaiMiao I can reproduce but it shouldn't happen... weird.

What if you test w/o any save file? (ie new game prompt) ?

**Comment by CaiMiao** [comment]
@TuxSH I wiped my MK7 save with JKSM and starting the game also freezes at logo.

**Comment by CaiMiao** [comment]
There should have nothing to do with the system font, as PKMN Moon and MK7 loads custom font from the game itself.

**Comment by Red1812** [comment]
@AuroraWright It freezes only when you try to use a different country than the one the console is setup and if the game uses that parameter. 
I tried to launch MK7 bought on EUR eShop on my EUR console. The game only freezes when I use EUR EN GB or EUR EN GB 01. It works with EUR EN.
With FE Fates it works with all combinaisons.

**Comment by CaiMiao** [comment]
@Red1812 No, there's nothing to do with console region.
I tried `CHN ZH JP 01` and `JPN JP JP 01` also freezes logo.

EDIT: `JPN JP JP 01` freezes Pokemon Moon, so definitely this is a bug.

**Comment by Red1812** [comment]
Yeah... The region setting on my console is FR. I just tried EUR EN FR 01 and EUR EN FR and it freezes.
With EUR EN it works but that kinda defeat the purpose.

**Comment by TuxSH** [comment]
Try the latest commit please:
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1056537/boot.zip)

**Comment by CaiMiao** [comment]
@TuxSH It works!!!
Finally the last piece.
Thank you for the work!!!

Another reminder, a suggestion, any possibility to edit locale emulation settings directly via Rosalia?
![tim 20170607072333](https://user-images.githubusercontent.com/4640483/26856176-b822d012-4b54-11e7-9158-d5269fc23aea.png)

**Comment by TuxSH** [comment]
Dunno, seems like a chore :P

**Comment by Red1812** [comment]
Sorry I'm late to the party but I confirm the latest commit worked for me too.

**Comment by Jimmy-Z** [comment]
Is there a list of country and state code?
