### ISSUE TITLE
Key Combo Resets Every Time Console Is Powered Off

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#542]
May be an issue with the actual code, but is the key combo saved anywhere? Whats the point of having a custom one if you have to use the default one to access the menu every time you reboot anyways? Thanks for all your hard work! Really appreciate the software.

**Comment by Gudf** [comment]
#489

**Comment by User13181408200115** [comment]
So does the 3dsx loader app if not using defult (homebrew launcher loader)

**Comment by Thelostrune** [comment]
This was already fixed in the commits, apparently.

**Comment by TuxSH** [comment]
Saving the combo on storage will be implemented later this day.

**Comment by ghost** [comment]
@TuxSH Is the injected hb app also going to be saved to storage? Would be very handy, thanks again for all the hard work!
