### ISSUE TITLE
[Suggestion] Cheat Searcher/NTR Plugin Loader

### ISSUE THREAD

**Issue by Monotek18** [LumaTeam/Luma3DS#543]
Since a lot of time, GW have an advanced cheat searcher in his in-game menu.

So I am wondering if Luma would have that one day in his ingame menu.

Also the menu take most of NTR feature, but there is no way to use NTR Plugin... yet 
That would be nice to see that.

**Comment by Margen67** [comment]
Cheat search seems possible but probably won't be added to Luma anytime soon.

Loading NTR plugins would be difficult if not impossible without the source code.

**Comment by Monotek18** [comment]
Well even if that take many time it does not matter, as long as Luma will have a searcher one day. (as long as it's nice and work)
Abiout the plugin loading, you can RE NTR to look how it load plugin.

**Comment by Margen67** [comment]
>RE NTR

That's easier said than done.

**Comment by TuxSH** [comment]
Duplicate of #512 (I'm leaving the latter open)
