### ISSUE TITLE
[Enhancement] Nintendo Server Calling Patch

### ISSUE THREAD

**Issue by Trojaner1982** [LumaTeam/Luma3DS#544]
We all know how unsecure it is with modded consoles when they call always home.

Any Chance for Pachting the Home Calling or redirect to ex. Google (Internet Settings Setup Call Nine Server) ... try around few things with server blocking, if i block conntest.nintendowifi.net, the connection test fail. but with this setting i can still use the Webbrowser ... Homescreen it self disconnect always from internet and do checks (even TitleDB from FBI doesn´t work) ... i would prefer a Non Home calling console ... Option for this Patch could be in Rosalina Menu, so we can simply change this if we dislike the Nine Server crap... Homebrew does´t need Nine Servers (more secure for us)

**Comment by Margen67** [comment]
LumaTeam/studious-barnacle#6
