### ISSUE TITLE
Game Patching Not Working on Fire Emblem Echoes DLC

### ISSUE THREAD

**Issue by ITZYOBOYkoko** [LumaTeam/Luma3DS#548]
I'm on latest luma and boot9strap. I'm playing USA Fire Emblem Echoes DLC and it's not working. I enable game patching in luma config and sdcard>titles>game id>locale.txt>USA EN and the DLC is not working.

Did I do something wrong or is it a bug or idk lol?

EDIT:
Tried the language patching and stuff in bootNTR and now everything is working just fine. 
But still the luma game patching is not working. I hope you can fix this. 

EDIT2:
Turning off game patching in luma config fixes my problem..lol

**Comment by jonirrings** [comment]
try `USA EN EN 01`?

**Comment by ITZYOBOYkoko** [comment]
@jonirrings Nope, it's not working either

**Comment by simonrule** [comment]
hope we can get a fix soon

**Comment by TuxSH** [comment]
Langemu issue? Fixed by the latest commit which you can find below.
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1055982/boot.zip)
