### ISSUE TITLE
[Feature request] Reboot and shutdown shortcuts in Rosalina menu

### ISSUE THREAD

**Issue by gtm87x** [LumaTeam/Luma3DS#549]
Hi all,
I have an old O3DS XL with a hard to press power button, so I generally prefer to use software solution to turn it off or restart it, like two standalone homebrew which serve that purpose alone.
Now that Luma 8.0 introduced the always accessible rosalina menu though, it would be great if two option for shutting down and restarting the console could be added to it.

**Comment by TuxSH** [comment]
Duplicate issue, but sure.

**Comment by trbocode** [comment]
Check out my fork of Luma. Power off is currently bugged- it will not take effect until you exit rosalina. Shutdown works fine.
