### ISSUE TITLE
Patch DS/DSi games on the fly to use the alternative wfc

### ISSUE THREAD

**Issue by droped** [LumaTeam/Luma3DS#55]
This is the alternative wfc: https://github.com/polaris-/dwc_network_server_emulator
And this is what you currently do to get access to it: https://github.com/polaris-/dwc_network_server_emulator/wiki

You need an action replay code or you can use a rom patcher.
I don't know if it is possible but an auto patcher with an auto code generator(or a code list for each game similar to how region change is done) to patch the game could be implemented.

**Comment by AuroraWright** [comment]
Not possible as far as I know. Loader doesn't load TWL titles
