### ISSUE TITLE
Unrespoonsive Luma3ds Configuration and Rosalina Menu

### ISSUE THREAD

**Issue by MDornH03** [LumaTeam/Luma3DS#550]
Whenever i do L+Down+Select, the rosalina pops up but I can't move up, down, or press A. The only button that works is B to get out of the menu. Same thing with Luma3ds Config, except I have to shut down my 3ds to exit it. No one else has been able to help, thanks 👍.

11.4.0 37U 03ds
I followed the guide on 3ds.guide.

**Comment by TuxSH** [comment]
Are you sure your buttons even work to begin with?

**Comment by MDornH03** [comment]
yes

**Comment by TuxSH** [comment]
There's no reason other than a hardware issue (buttons not properly "connected"?) for it not to work.

**Comment by Margen67** [comment]
Try this: https://github.com/AuroraWright/Luma3DS/files/1055982/boot.zip

**Comment by MDornH03** [comment]
thanks so much dude, it works now

**Comment by MDornH03** [comment]
nevermind, worked for a second. stopped again
