### ISSUE TITLE
I can't load a code.bin which is edited because of a new file in romfs

### ISSUE THREAD

**Issue by FlameBeam** [LumaTeam/Luma3DS#551]
Sorry for my bad English.
I am a Chinses player. As you know, a number of player in China play 3DS games that is translated by some translate group like ACG.
But many times, we must edit the code.bin because we need add some files in the romfs,like font(you know the Chinese font file is different from English and Japanese).
If I use a code.bin that is edited because of some new files in the romfs, the game will be not work.
Is there any way to use this code.bin?

**Comment by ghost** [comment]
I don't believe this is an error with Luma. In the code.bin, you likely need to edit it to make use of the new files. However, I may have misunderstood. Can you explain what you did to the romfs and code.bin in detail?

**Comment by FlameBeam** [comment]
https://mega.nz/#!dcYjnYaA!_ToNltgAMqMtkP2IjNCFnfbDKZebD00sGda17gu7bA0
Here is the patch of the Zero Escape: Zero Time Dilemma in Chinese. Because we need a Chinese input in the game, we add the "hanhua" and "system/desision/input" folders in romfs and edited the code.bin. As a cia, it works. But as a luma game patch, it dead. 
If I delete the code.bin, it works.
It's only one game in many code edited Chinese games.

**Comment by FlameBeam** [comment]
I think maybe it because of the edited exh.bin?

**Comment by ericjwg** [comment]
did you used a decompressed version code.bin?

**Comment by FlameBeam** [comment]
I tested.
the original code.bin can work but the edited code.bin can't. 
I asked the author who edited the code, he told me because the exh.bin was edited.

**Comment by ericjwg** [comment]
@FlameBeam weird. are u using the latest commit or stable release version?

**Comment by FlameBeam** [comment]
@ericjwg Of course, I use the Luma 8.0.

**Comment by ghost** [comment]
@FlameBeam, could you try this with OnionFS or another LayeredFS implementation and let us know if it works or has the same issue?

**Comment by ghost** [comment]
Closing this, original issuer has not responded to requests for further testing. Will reopen if that occurs and this ends up being an issue specific to Luma.

**Comment by FlameBeam** [comment]
I'm sorry I have test OnionFS until today. I have final exam these days.
I test the OnionFS today, it can not work.
I find the reason is that we have a costum exheader.bin, so can Luma patch a costum exheader.bin for games?

**Comment by ghost** [comment]
No worries. Thank you for testing. I'll look into this further and let you know.

**Comment by FlameBeam** [comment]
I tested another game(HyruleWarriors)，it's also a game with a custom code.bin and custom exheader.bin.
But it works!!! Then I try  Zero Escape again, it also works. Maybe something wrong when the first test.

**Comment by FlameBeam** [comment]
↑↑↑
 I mean test in OnionFS, they're working but dead in Luma.

**Comment by FlameBeam** [comment]
OnionFS:
custom code.bin + custom romfs = work!
(exh.bin not changed)custom code.bin + custom romfs + new files in romfs = work!
(exh.bin changed)custom code.bin + custom romfs + new files in romfs = work!

Luma:
custom code.bin + custom romfs = work!
(exh.bin not changed)custom code.bin + custom romfs + new files in romfs = work!
(exh.bin changed)custom code.bin + custom romfs + new files in romfs = bomb!

**Comment by FlameBeam** [comment]
I tested the custom code.bin with custom exheader.bin in last version(8.1.1). 
It still can't be run. 
Here are the dump files.
[dumps.zip](https://github.com/AuroraWright/Luma3DS/files/1207500/dumps.zip)
I tested third times.

**Comment by Shadow322** [comment]
Um v8.1.1.7 does not exist

**Comment by FlameBeam** [comment]
Oh well, it '8.1.1.7z' ,lol

**Comment by TuxSH** [comment]
Closing, tracker cleanup
