### ISSUE TITLE
error code with luma game patching on monster hunter generations (8.0)

### ISSUE THREAD

**Issue by slowbeatle** [LumaTeam/Luma3DS#552]
trying on some textures and got error code: 0xd860466c when i press home

**Comment by AuroraWright** [comment]
Please disable any custom home menu themes you have enabled, this is the third time you report this issue for different games.

**Comment by TuxSH** [comment]
0xd860466c : Module: FS (17) | Description: 620 | Summary: Out of resource (3) | Level: Permanent (27)
