### ISSUE TITLE
Luma3DS-84d736c ???

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#560]
all newer builds compiled on *nix black screen and blue led causes u to force shutdown on N3DS/XL but work fine on O3DS/XL

**Comment by dogtopus** [comment]
That commit got reverted. It's probably broken.
Did you try the latest commit?

**Comment by Auscobe** [comment]
i recommend just using the stable build.

**Comment by TuxSH** [comment]
Or one I've posted in the region emulation issues.

**Comment by MelonGx** [comment]
Ask Linux builders to build it for you.
Current codes cannot be properly built by Windows environment.
Also do not use astro's nightly until he fix his environment.

**Comment by jonirrings** [comment]
@MelonGx can it be built under *nix, like mac os?

**Comment by MelonGx** [comment]
@jonirrings Dunno about Mac. We only have Windows and Linux.

**Comment by jonirrings** [comment]
@MelonGx got it, thank you

**Comment by Auscobe** [comment]
oh how i wish i could go back to Windows.

**Comment by ericjwg** [comment]
@WubTheGame windows build doesn't work either.
only nix-ish

**Comment by Auscobe** [comment]
regardless, i don't really like mac.

**Comment by ihaveamac** [comment]
@WubTheGame please don't comment just because, only if you have something to add to the conversation.

**Comment by Auscobe** [comment]
okay..

i'm just enjoying having a github account is all.

**Comment by TuxSH** [comment]
Fixed.
