### ISSUE TITLE
Add gateway-ish like byte search

### ISSUE THREAD

**Issue by ThatFluffyFox** [LumaTeam/Luma3DS#562]
Add any sort of cheat search for the new rosalina menu very like the one gateway has or like what windows has "cheat engine."

**Comment by Auscobe** [comment]
i forget which post it is, but this has already been asked.

**Comment by jonirrings** [comment]
I think the devs should use the github `Project` feature to track the issues and `todo`s and feature request and so on.:joy:

**Comment by ThatFluffyFox** [comment]
Sorry as Wub said this was my mistake of not reading other post and making a duplicate of another post

**Comment by fincs** [comment]
Duplicate of #512.

**Comment by Auscobe** [comment]
fincs he already knows that. i told him.

**Comment by fincs** [comment]
I was just linking to the relevant issue, just to make it even clearer.

**Comment by Auscobe** [comment]
oh, right, well thanks.
