### ISSUE TITLE
Latest commit 427a059 ???

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#565]
can anyone be kind and compile a copy plez

**Comment by james-d-elliott** [comment]
https://astronautlevel2.github.io/Luma3DS/

Get the second last one: a16d1eb

427a059 just reverts a commit.

**Comment by Shadow322** [comment]
if it was there sure

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus

**Comment by DeathAngel74** [comment]
I hope this helps @Shadow322 and @james-d-elliott! I did not compile it myself, a friend did it for me. 2DS and N3DSXL are fully functional and booting normally.

[Luma3DSv8.0-a16d1eb.zip](https://github.com/AuroraWright/Luma3DS/files/1060102/Luma3DSv8.0-a16d1eb.zip)

**Comment by james-d-elliott** [comment]
https://transfer.sh/3tvxY/boot.firm here. Just built it.

Edit: Oh, someone else linked to another from the repo.

**Comment by DeathAngel74** [comment]
doh! ninja'd

**Comment by Shadow322** [comment]
@james-d-elliott THANKS!!!

**Comment by ghost** [comment]
This is not the proper place to ask for this. Please do not do this again.
