### ISSUE TITLE
Taiko 3 romfs not working

### ISSUE THREAD

**Issue by GoldNoway** [LumaTeam/Luma3DS#566]
Hi,
I already stated that on GBAtemp, but I figured it'd be worth it to mention it here too.

When using the romfs translation patch for Taiko no Tatsujin : Dokodon - Mystery Adventure, as a "romfs" in the correct folder, to load the game in english, it just doesn't work : Taiko is still in Japanese.
That's the case ever since romfs feature was implemented on Luma. I didn't care previously because it was bootable with Hans, but Hans doesn't show up in the new Homebrew Menu, so Taiko 3 romfs is basically not working.

All DLC work correctly though.

Titleid for this game is 0004000000190E00.

**Comment by Shadow322** [comment]
U need to extract the romfs into a folder u can't use a single .romfs file

**Comment by ghost** [comment]
Could you link to the GBAtemp thread in question? As @Shadow322 said, if the romfs hasn't been extracted into a folder (rather than a .romfs, romfs.bin, etc.) it will not work.

**Comment by GoldNoway** [comment]
Well I just mentioned that in the Luma general thread, and that was not as well explained as here. I think I made a thread a while ago too but I'm not so sure about that one :')

In any case, the romfs, named "romfs" without any extension, is located on luma/titles/0004000000190E00/. I don't think there's an error here, and as stated earlier that file worked previously with Hans.

**Comment by ghost** [comment]
HANS uses a raw file named "romfs", so you'll have to clarify. Did you extract this file into a directory called "romfs" with ctrtool or similar? Luma does not support the way HANS handles romfs. The romfs must be extracted into a directory called "romfs".

**Comment by GoldNoway** [comment]
EDIT : I finally found out why I couldn't load Taiko 3 romfs. Sorry about that, it was a mistake in my files.
