### ISSUE TITLE
Crashes running pcsx_rearmed libretro/retroarch

### ISSUE THREAD

**Issue by gingerbeardman** [LumaTeam/Luma3DS#568]
Luma 8.0
Boot9strap 1.2

https://github.com/libretro/pcsx_rearmed/issues/125

https://github.com/libretro/pcsx_rearmed/files/1052379/crash_dump_00000003.dmp.zip

**Comment by ghost** [comment]
Looks like this is a [known issue](https://gbatemp.net/threads/retroarch-emulation-thread-nightly-builds-included.400913/page-300#post-7397579) with PCSX reARMed itself. You can use an older version linked in that thread to fix it.

**Comment by gingerbeardman** [comment]
Great, thanks! I wasn't sure where the problem was as the error was presented by LUMA
