### ISSUE TITLE
[Rosalina] N3DS Clock settings not sticking after reboot

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#569]
Reporting what i think is a bug - Rosalina seems to automatically apply the L2/Max clock speed patch at each boot. Considering the Luma settings give the option to simply disable this patch, i guess the Rosalina menu shouldn't reapply it at each boot regardless?

**Comment by TuxSH** [comment]
No it doesn't.

It's just that Home Menu runs with those settings by default, then it changes at each game launch.

Maybe there's a bug in reporting the L2 and clock status but that's separate.
