### ISSUE TITLE
armips on linux builds

### ISSUE THREAD

**Issue by shinji257** [LumaTeam/Luma3DS#57]
I built ~~static~~ dynamic binaries that should be usable on most linux installations.  Don't know if they will be usable for anyone here but it might save some from having to compile it themselves.  Details are in the readme.  I don't actually claim any credit for this.  32-bit and 64-bit binaries are included.

Static binaries don't work with pthread so I had to do dynamic ones anyways.  Good news is that they still worked out for me.

https://mega.nz/#!uQ1T1IAD!Q91O0e12LXKiaXh_YjXD3D5m8_W3FuMI-hEa6KVMRDQ

**Comment by AuroraWright** [comment]
Added to the readme, thank you!
