### ISSUE TITLE
sdcard (rare) random unmounts

### ISSUE THREAD

**Issue by pcs3rd** [LumaTeam/Luma3DS#570]
idk if my sdcard is the problem. Every once in a while, right off the bat, when opening the lid, the sdcard does not remount and theme and everything else disappears until I reboot.

**Comment by ghost** [comment]
Could not reproduce, attempted ~100 times. Likely a hardware failure, test your SD card with [H2testw](https://3ds.guide/h2testw-(windows).html) or another tool. If the SD card comes back fine, it may the SD card slot itself; the 3DS SD card slot cannot handle many cycles.

**Comment by ZenIsBestWolf** [comment]
This is likely a poor SD card.

**Comment by pcs3rd** [comment]
ok. thanks. every once in a while, it does similar while exiting rosalina

**Comment by pcs3rd** [comment]
It's actually stabalized over the last 2 hours

**Comment by ghost** [comment]
Closing. If this turns out to be an actual issue, I'll reopen it at a later date.
