### ISSUE TITLE
[Feature Request] Add Sound Adjustment Option into Rosalina Menu

### ISSUE THREAD

**Issue by greenDarkness** [LumaTeam/Luma3DS#576]
Hello, 
I was wondering if you would consider adding a sound adjustment feature to Luma for 3ds users that have broken sound sliders?
Thank you for reading this, and for all your work!

**Comment by ghost** [comment]
This is being considered. If it's feasible, it may be implemented in the future.

**Comment by greenDarkness** [comment]
Thank you so much for considering!

**Comment by ghost** [comment]
Since my volume slider is misbeahvering this will help me alot

**Comment by ghost** [comment]
See the reference. Closing this now. Thank you.
