### ISSUE TITLE
Broken again 427a0599 ???

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#577]
anything newer then 427a0599 just boots to a eternal black screen and blue led to a forced shut down by holding power button

**Comment by TLNiles** [comment]
Just stop downloading hourly updates if you're not a dev. Download latest stable release and put it in the root of your SD.

**Comment by MelonGx** [comment]
Repeat again.
This is a building environment issue.
1. Do not use hourlies who haven't upgraded devkitARM + ctrulib + firmtool to the latest.
2. If you build Luma yourself, update your devkitARM + ctrulib + firmtool to the latest.
3. If everything don't work, ask a Linux builder to build it for you. Windows has bad compatibility on this wave of building unusable Luma.

**Comment by MelonGx** [comment]
Update:
The eternal black screen DOES happen on N3DS + In-NAND 949d219 built from Linux & devkitARM + ctrulib + firmtool latest.
O3DS hasn't got this issue.

**Comment by trbocode** [comment]
Can confirm blackscreen

**Comment by DeathAngel74** [comment]
They fixed building in *nix environments @Shadow322 in commit 4bc9597.
Also, 
https://astronautlevel2.github.io/Luma3DS/ 
is back up and running.

**Comment by trbocode** [comment]
@DeathAngel74 Still blackscreens for me.

**Comment by nl255** [comment]
All recent builds from the nightly site do that for me on my n3DS (haven't tested them on an o3ds), and so does the build tuxsh provides at https://github.com/AuroraWright/Luma3DS/issues/493 (which is 84d736c).  Fortunately the chainloader still works so I can use gm9 to revert to 8.0.

**Comment by MelonGx** [comment]
52a1883 properly booted N3DS SysNAND & N3DS EmuNAND.
