### ISSUE TITLE
Powers on and then instantly powers off after updating

### ISSUE THREAD

**Issue by NoobForeverANDever** [LumaTeam/Luma3DS#579]
after i updated it it powered off so i tried to power it on again and then it just powers on and powers off pls HELP!

**Comment by ghost** [comment]
Did you update boot9strap to 1.2? luma3DS 8.0 requires it.

**Comment by Margen67** [comment]
Nobody can help you if you don't even provide any details.

**Comment by ghost** [comment]
@Margen67, he probably has a old boot9strap, same thing happens to me, I updating everything through 3DS.guide. Now I have luma 8 working.

**Comment by NoobForeverANDever** [comment]
ill see when i get home

**Comment by NoobForeverANDever** [comment]
all right Im back and I checked and turns out I didnt update boot9strap

**Comment by ghost** [comment]
Working now?
