### ISSUE TITLE
An Exception Occurred

### ISSUE THREAD

**Issue by Bonesaww** [LumaTeam/Luma3DS#583]
**System model:** Old 3DS
**SysNAND version:** 11.3.0-36U SysNAND
**Entrypoint:** Boot9Strap
**Luma3DS version:** 8.0
**Luma3DS configuration/options:** Show NAND or user string in System Settings: (x)

Updated B9S and Luma last night with the most recent stable versions and am greeted with [this](https://i.imgur.com/w0Tb8Ng.jpg) error upon booting to SysNAND.

Chainloader/EmuNAND booting still seem to work just fine.

[crash_dump_00000001.zip](https://github.com/AuroraWright/Luma3DS/files/1065476/crash_dump_00000001.zip)

**Comment by ZenIsBestWolf** [comment]
Make sure everything is in the right place, and I reccomend updating to 11.4.

**Comment by GabrielRRussell** [comment]
> updating to 11.4

Can't do that if SysNand isn't booting.

Reinstall BootStrap 1.0, and then go back to Luma 7.1.

Update to 11.4, and make sure everything is functional.

If you don't see anything out of place, reinstall 1.2

**Comment by Bonesaww** [comment]
Tried it. Boots to black screen and none of the usual fixes work (No SD/Cart/Safe Mode). Chainloader/EmuNAND still work fine. Guess I'll try a 9.2 CTR transfer.

**Comment by GabrielRRussell** [comment]
Uhh

Replace Luma with 7.1 then downgrade to Bootstrap 1.0? You don't have to CTRTransfer.

You don't have to upgrade to Luma 8.0, you know.

**Comment by Bonesaww** [comment]
I've already tried reinstalling b9s 1.0 and going back to Luma 7.1. It's there that I run into the black screen at boot.

**Comment by Bonesaww** [comment]
Well the 9.2 CTR transfer seems to have fixed it, so I'm gonna just go ahead and close this. Still confused as to what went wrong in the first place though.

**Comment by david-zzj** [comment]
hi, can you tell me how to reinstalling b9s 1.0 ？
now i am b9s 1.2
