### ISSUE TITLE
Crash when installed boot9strap 1.2 and copy luma 8.0.7 to SD and open 3ds.

### ISSUE THREAD

**Issue by wang80919** [LumaTeam/Luma3DS#586]
**System model:**
New3ds
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
V9.1.0-20J
[e.g. 11.4.0-37U SysNAND, 11.4.0-37J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
boot9Strap
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
8.0.7
[e.g. 7.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ()
1
Screen brightness: ( )
4
Splash: ( )
off
PIN lock: ( )
off
New 3DS CPU: ( )

--
off
Autoboot EmuNAND: ( )
off
Use EmuNAND FIRM if booting with R: ( )
on
Enable loading external FIRMs and modules: ( off)

Use custom path: ( )
off
Enable game patching: ( )
off
Show NAND or user string in System Settings: ( )
on
Show GBA boot screen in patched AGB_FIRM: ( )
off
Patch ARM9 access: ( )
off
Set developer UNITINFO: ( )
off
--

**Explanation of the issue:**

**Steps to reproduce:**

1.
use  Homebrew Launcher ot install boot9starp ok
2.
copy lunm 8.0.7 to sd
3.
open 3ds
4.
sysNAND loading crashed.
enuNAND 11.4.0.37J loaded ok.

**Dump file:**

**Comment by ghost** [comment]
Can't reproduce this; also 8.0.7 doesn't exist, or if it does exist as a commit you did not specify it correctly.

**Comment by jonirrings** [comment]
Luma3DSv8.0.7z -> 8.0.7……:joy:

**Comment by wang80919** [comment]
ok it is 8.0

**Comment by Clement95** [comment]
Do you have updated to boot9strap 1.2 ?
