### ISSUE TITLE
[Bug Report] Crash when using or launching youtube

### ISSUE THREAD

**Issue by Auscobe** [LumaTeam/Luma3DS#587]
So, my lil bro was using my 3DS, and i don't know what really happened, but he came across a crash and it filled the screens with code and stuff. here's the Crash Dumps: 
[Crash Dumps.zip](https://github.com/AuroraWright/Luma3DS/files/1069862/Crash.Dumps.zip)

EDIT: this morning i got the same thing so i have updated the zip

**Comment by ghost** [comment]
Can't reproduce this no matter what I do in the YouTube app.

**Comment by Clement95** [comment]
The problem is on Youtube app, the software bug and crash also with a 3DS who don't have CFW
