### ISSUE TITLE
Console won't boot if the Rosalina Menu Combo is spammed

### ISSUE THREAD

**Issue by Clement95** [LumaTeam/Luma3DS#589]
When I press POWER button and spam the Rosalina Menu Combo, my console stay with a black screen. It's not important but a small bug to fix

**Comment by Jan200101** [comment]
Thats a known issue.
Rosalina hasnt initiated properly at that time and will softlock the console

**Comment by TuxSH** [comment]
It doesn't softlock, it just doesn't display anything.

**Comment by fyw321** [comment]
same problem here
