### ISSUE TITLE
The arm11 error for homebrew

### ISSUE THREAD

**Issue by HRudyPlayZ** [LumaTeam/Luma3DS#592]
**System model:**

Old Nintendo 3DS

**SysNAND version:**

11.2.0-35E (SYSNAND)

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap (previously A9LH)

**Luma3DS version:**

8.0 Stable build.

**Luma3DS configuration/options:**

Default EmuNAND: ( 1)

Screen brightness: ( 4)

Splash: (Before payloads )

PIN lock: ( Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: (X)

Enable loading external FIRMs and modules: (X)

Use custom path: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**
I wanted to use the homebrew launcher (i have a ctrbootmanager programmed for selecting between
GridLauncher, HBLauncher & HBLauncher 2.0), the bootmanager booted very well but none of my launchers works... It gives me a "data dump error", but when i only uses the new HBLauncher 2.0 it does
boot but i can't play homebrews well or cannot launch them at all. (I precise i use the hblauncher_loader)

EDIT: also when i try to use soundhax, it's crash instantly with the arm11 error.

**Steps to reproduce:**

1. Launch the hblauncher_loader

2. Select your launcher or Select an homebrew

**Dump file:**

I don't know if the upload does works, because github don't want to upload my ZIP.

**Comment by fincs** [comment]
hax 2.x payloads aren't supported anymore with Rosalina, due to fundamental changes and patches done to the 3DS operating system. It is also required to use the latest version of hbmenu (2.0 at the moment) to be able to launch 3dsx applications with Rosalina. Anything else doesn't work since they try to use the 3dsx booting protocol designed for hax 2.x payloads.
