### ISSUE TITLE
fpexc register showing dfsr content on exception screen

### ISSUE THREAD

**Issue by LiquidFenrir** [LumaTeam/Luma3DS#596]
**System model:**

Old 3DS EUR

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.2

**Luma3DS version:**

Luma3DS v8.0-901d4992 (astro's nightlies go up to that)

**Luma3DS configuration/options:**

Default EmuNAND: ( 1 )

Screen brightness: (  2 )

Splash: ( Off )

PIN lock: ( Off )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( X )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

When a crash happens and the "An exception occured" screen comes up, the bottom right register (labelled FPEXC) shows the contents of the register labelled dfsr when using exception_dump_parser.py

**Steps to reproduce:**

1. Crash the system (for example, with https://github.com/LiquidFenrir/MultiUpdater/issues/20)

2. Look at the screen

3. Parse the crash dump using the python script

4. Notice the difference

**Dump file:**

Images: [On 3DS](http://i.imgur.com/AHEc40y.jpg) vs [after parsing](http://i.imgur.com/GhngTi1.png)
[crash_dump_00000028.zip](https://github.com/AuroraWright/Luma3DS/files/1068199/crash_dump_00000028.zip)

**Comment by TuxSH** [comment]
Thanks for reporting, it's fixed now.
