### ISSUE TITLE
[Feature Request] Volume and 3D adjuster in Rosalina Menu

### ISSUE THREAD

**Issue by DewGaming** [LumaTeam/Luma3DS#597]
I have an old 3ds that I don't use to play on anymore, but use for testing purposes.  The reason is that liqquid was spilt on it and no some things don't work right, like the volume slider.  When I'm using the test 3ds, I don't always want the volume to be on, especially if someone is sleeping next to me.  Is it possible to add in a function to manually override the slider and change the volume using the Rosalina menu?

**Comment by sora10pls** [comment]
#576

**Comment by alwe2710** [comment]
I'd like this feature as well, my 3d slider is broken. would be great
