### ISSUE TITLE
Crash with Stack Dump when launching games with NTR Mode3

### ISSUE THREAD

**Issue by InkDragon** [LumaTeam/Luma3DS#598]
**System model:** o3ds
**SysNAND version:** sys 11.4.0-37u
**Entrypoint:** B9S 1.2
**Luma3DS version:** 8.0
**Luma3DS configuration/options:**

Default EmuNAND: (1)
Screen brightness: (4)
Splash: (off)
PIN lock: (off)

--

Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Use custom path: ( )
Enable game patching: (X)
Show NAND or user string in System Settings: (X)
Show GBA boot screen in patched AGB_FIRM: ( )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )

--

**Explanation of the issue:**
System crashes with a stack dump error when booting MHG via mode 3 NTR boot Selector

**Steps to reproduce:**

1. load bootNTR selector mode 3, lode NTR more 3 version 3.4
2.  press home and load Monster Hunter Generations
3. Game will play as normal first run, but many codes will not work.
4. Save & quit game, reboot system
5. Repeat steps 1 & 2
6. Game will immediately crash and produce an arm 11 error

**Dump file:**
I was unable to get the file to upload via github as a zip, so this is the link to the upload from [my posts in the MHG cheat file thread](https://gbatemp.net/threads/monster-hunter-generation-cheats-plugin.434897/page-17#post-7386886).
https://gbatemp.net/attachments/crash_dump_00000000-rar.89868/

**Comment by TuxSH** [comment]
Not sure if it's a Luma3DS 8.0 issue or a Luma3DS issue at all.

**Comment by InkDragon** [comment]
I attempted to use the luma 8 legacy build which just resulted in the game not loading so likely a luma issue

**Comment by T3CHNOLOG1C** [comment]
Attempting to launch BootNTRSelector Mode 3 on my 11.4.0-37U O3DS with latest commit (self built) just softlocks the system.

**Comment by TuxSH** [comment]
Should be fixed by the latest commits.
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1073197/boot.zip)

**Comment by InkDragon** [comment]
Nope still borked, here's the dump for it.
https://www.dropbox.com/s/5lotkhkq1xsi020/crash_dump_00000001.zip?dl=0

**Comment by InkDragon** [comment]
can someone please reopen this as its not fixed

**Comment by Skullfun** [comment]
Hi, did you solve your problem?

**Comment by InkDragon** [comment]
yes, was fixed. switched to a nightly build and deleted and redownloaded the cheat file.

**Comment by Skullfun** [comment]
Where do you download the nightly build? O what is that?

**Comment by Skullfun** [comment]
I have the problem with mhxx, I patched language with Luma: Enable game patching: (X)
