### ISSUE TITLE
[Bug Report] Screen capture broken

### ISSUE THREAD

**Issue by RS55** [LumaTeam/Luma3DS#599]
**System model:**

[Old 3DS]

**SysNAND version:**
11.4.0-37U SysNAND

**Entrypoint:**
Boot9Strap/Sighax

**Luma3DS version:**
Luma 3DS v8.0-901d499

**Luma3DS configuration/options:**

Default EmuNAND: ( )
Screen brightness: ( 4 )
Splash: ( )
PIN lock: ( )

--

Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Use custom path: ( )
Enable game patching: ( )
Show NAND or user string in System Settings: ( X )
Show GBA boot screen in patched AGB_FIRM: ( X )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )

--

I have been using the screenshot function and after taking an X quantity, this occurs... Or sometimes the first with several games.

PD: This happened to me with the stable Luma3DS v8.0 and now with Luma 3DS v8.0-901d499 (And other nightlies I've used)

![img_20170610_172312](https://user-images.githubusercontent.com/29388266/27058791-4de5148e-4fa1-11e7-82a0-134290f29be7.jpg)

**Comment by TuxSH** [comment]
Happens occasionnaly, will fix later.

**Comment by ghost** [comment]
This should be fixed in commit 2363817.
