### ISSUE TITLE
Old Luma updating to new Luma without chainloader

### ISSUE THREAD

**Issue by Japoelho** [LumaTeam/Luma3DS#600]
**System model:** Old 3DS
**SysNAND version (+emu/redNAND version if applicable):** 11.2.0-35U SysNAND
**Entrypoint (How/what you're using to boot Luma3DS):** arm9loaderhax
**Luma3DS version:** 6.6-b16d887 (dev)
**Luma3DS configuration/options:**
Default EmuNAND: ( )
Screen brightness: ( )
Splash: ( )
PIN lock: ( )
New 3DS CPU: ( )
Autoboot EmuNAND: ( )
Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Use custom path: ( )
Enable game patching: ( )
Show NAND or user string in System Settings: ( x )
Show GBA boot screen in patched AGB_FIRM: ( )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )

**Explanation of the issue:**
I have an old Luma version, 6.6, and I tried updating to B9S. This version doesn't have the chainloader menu to install the B9S and I can't update to the latest Luma using the Updater because of the B9S requirement.
How can I update the Luma manually on the NAND or how can I make the Luma Updater update to a newer but still A9LH compatible first and then to B9S?

**Steps to reproduce:**
1. Luma 6.6 installed
2. Try to update it.

**Dump file:**

**Comment by ghost** [comment]
[This is the last version of Luma compatible with A9LH](https://github.com/AuroraWright/Luma3DS/releases/download/v7.0.5/Luma3DSv7.0.5.7z); update to it manually then follow https://3ds.guide/a9lh-to-b9s.

**Comment by Japoelho** [comment]
I'm searching for the how-to do the manual update but I can't find it, do you know where can I find it or explain it if possible?

**Comment by ghost** [comment]
Extract the arm9loaderhax.bin from the linked .7z file and replace the arm9loaderhax.bin on your SD card with it.

**Comment by Japoelho** [comment]
Thank you very much.
