### ISSUE TITLE
"An Exception Occurred" error when loading "Shaun the Sheep 1-15 EUR" on US o3DSxl

### ISSUE THREAD

**Issue by rynho** [LumaTeam/Luma3DS#603]
**System model:**
Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**
11.4.0-37U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap 1.2

**Luma3DS version:**
8.0 stable

**Luma3DS configuration/options:**
Default EmuNAND: ( 1)
Screen brightness: ( 1)
Splash: ( off)
PIN lock: ( off)
New 3DS CPU: ( )

Autoboot EmuNAND: ( no )
Use EmuNAND FIRM if booting with R: ( no )
Enable loading external FIRMs and modules: ( no )
Enable game patching: ( no )
Show NAND or user string in System Settings: ( yes )
Show GBA boot screen in patched AGB_FIRM: ( no )
Patch ARM9 access: ( no )
Set developer UNITINFO: ( no )

**Explanation of the issue:**
downloaded "shaun the sheep (episode 1-15 + Making of)" using CIAngel, "CTR-N-MBMP", EUR, 00040000000f2a00, and install using FBI.  after successful installation, launch the title, and get an ARM11 exception error.  I attached the dump file below.

**Steps to reproduce:**
1. Launch latest CIAngel, choose "Create CIA", region "off", search for "shaun", and select "Shaun the sheep (episode 1-15 (EUR) CTR-N-MBMP"

2. After download, exit CIAngel, launch latest FBI and install title from "SD\CIAngel" folder.

3. exit FBI, launch the new installed app, and get the error and found dump in "SD\luma\dumps\arm11"

**Dump file:**

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1073549/crash_dump_00000000.zip)

**Comment by MelonGx** [comment]
Why don't you write Luma Region Patches for them before asking this question?
CIA region free is a pretty old stuff that is only compatible with old-era systems like rxTools, GW, etc. and conflict with current era CFWs.
So don't think CIA region free can take Luma region patch's place.

**Comment by rynho** [comment]
I tried, it didn't work.

**Comment by rynho** [comment]
I used latest nightly build 8.0-901d499 last night, the title running well with enabling the region simulation.  Therefore, I confirm this is a bug regarding region patch in 8.0 stable build, and was fixed in nightly build.  @Hikari-chin could you please close this post, thanks.
