### ISSUE TITLE
NSMB2 Luma patching seems to only work on USA versions

### ISSUE THREAD

**Issue by Gimzie** [LumaTeam/Luma3DS#604]
A while ago I reported an issue where NSMB2 Luma patching did not work, and then it was fixed. Only, it seems like it was fixed for US versions only. (And possibly only n3DS/Special Edition) There have been many who have tried it with a European version, only for it to not work. I myself was able to test this with a European copy, and it indeed didn't work.

In any case, there's a group of people with a specific copy of NSMB2 that can't run the Luma patches, and have to use OnionFS instead.

**Comment by Jan200101** [comment]
I've tested a mod called New Super Mario Classic on my EU device with a EU Version of the game.
It seems to work fine for me

**Comment by ghost** [comment]
Is this thing working?

**Comment by Gimzie** [comment]
Is it the Special Edition?

**Comment by Jan200101** [comment]
No

**Comment by GRAnimated** [comment]
Just tested myself, on the EU version it does work but the special edition does not, but the US regular and special works.

**Comment by Gimzie** [comment]
Maybe it's just Special Edition?

**Comment by ghost** [comment]
Are the mods you're testing stated to be compatible with the Special Edition? It's likely there are some small differences that may break certain mods/patches. Additionally, a mod meant for the EU version may not work on the US version and vice versa, depending on what the differences are.

**Comment by Jan200101** [comment]
@Gimzie Can you try the mod NSMB Classic ?
According to the Devs it should work with the Special Edition for EU

**Comment by Jan200101** [comment]
After some searching I noticed
There is no "gold edition" of the EU version instead the normal EU version is the gold edition

**Comment by ghost** [comment]
Closing this; original reporter has not responded and based on @Jan200101's comments it is likely user error.

**Comment by AuroraWright** [comment]
Can't reproduce with both the special edition and a cart, so I confirm this to be user error (or the game files aren't universal)
