### ISSUE TITLE
Request: IP address display. 

### ISSUE THREAD

**Issue by ForcedToRock** [LumaTeam/Luma3DS#605]
A wee bit of a drag to have to open up FTPD, FBI, or even my router configuration page to find the IP address of a console, I can see it between the version of Luma3DS and the battery percentage number.

**Comment by Jan200101** [comment]
Most Routers allow you to set a static local IP for devices but its a valid Suggestion.
:+1:

**Comment by LiquidFenrir** [comment]
enable debugger, then go into the process list. it will be in the top right. you can just disable debugger after

**Comment by TuxSH** [comment]
^

Was just about to post that.

**Comment by ForcedToRock** [comment]
More button presses rather than just opening Rosalina, but alright.

**Comment by TuxSH** [comment]
See 9ccfacd06d34e9482ad06d7ed75cbdee0097e2af
