### ISSUE TITLE
[Request] LayeredFS for System Applet?

### ISSUE THREAD

**Issue by CaiMiao** [LumaTeam/Luma3DS#606]
If LayeredFS can implement on System Titles, maybe we can edit some cool stuff, e.g. to use UI translation for **other languages** (preview attached below).

For current version, I just tested on Mii Plaza, Home Menu and Internet Browser, only Mii Plaza is properly worked and others remain un-layered.

Edit: Home Menu and Internet Browser are applets.

![20170614140650](https://user-images.githubusercontent.com/4640483/27117796-d083774a-510a-11e7-8be0-a4109fab6c86.jpg)

**Comment by AuroraWright** [comment]
It won't work, it bases itself on functions that are missing on applets

**Comment by Margen67** [comment]
#410
