### ISSUE TITLE
On New3DS, nightly version of Luma auto-shutdown when launching GBA VC game or DSiWare

### ISSUE THREAD

**Issue by TheNain38** [LumaTeam/Luma3DS#608]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

nightly https://github.com/AuroraWright/Luma3DS/commit/24de7c527287ad6bd1b76b9962ef0f4330382acb

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (1)

Splash: (Before)

PIN lock: (0)

New 3DS CPU: (L2 Cache + Clock)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

When trying to launch a GBA VC game, or a DSiWare title, the console auto-shutdown, also I don't have this bug on Luma v8.0, and just in case, I even reinstalled a clean TWL_FIRM and AGB_FIRM, by using the instructions on the [wiki](https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-get-an-auto-shutdown-with-gbadsdsiware-games)

Maybe it's a problem with Luma failing to patch the firms?

**Steps to reproduce:**

1. Try to start a GBA VC game, or a DSiWare title

2. See that the console auto-shutdown

**Comment by DeathAngel74** [comment]
Try 005684

**Comment by DeathAngel74** [comment]
d8

**Comment by TuxSH** [comment]
[boot.zip](https://github.com/AuroraWright/Luma3DS/files/1075441/boot.zip)
Latest commit.

**Comment by TheNain38** [comment]
It still doesn't work with the latest commit that you provided

**Comment by TuxSH** [comment]
I can't reproduce...

**Comment by TheNain38** [comment]
The weird thing, is that I don't have this bug on Luma v8.0, and that in between, it looks like you didn't change anything related to TWL_FIRM or AGB_FIRM, or maybe I'm wrong? Because it does as if Luma would fail to apply the patches... hmm...

**Update**:
Would it be possible for you to compile a version of Luma that adds logging if Luma fails to apply the patches to TWL_FIRM and/or AGB_FIRM? So that we could verify if it's not that issue?

**Comment by DeathAngel74** [comment]
Just tested this commit works. 12b561a2.

**Comment by DeathAngel74** [comment]
https://drive.google.com/file/d/0B007JgCLgXQLX0d4UHNKZHdhZm8/view?usp=drivesdk

**Comment by DeathAngel74** [comment]
Just rename to boot.firm

**Comment by MelonGx** [comment]
Haven't got your issue on da30c0b.

**Comment by DeathAngel74** [comment]
005684d8 is when the prob started

**Comment by MelonGx** [comment]
@DeathAngel74 Then why I have no error on launching DSiWare with da30c0b?
Also tested no error on a1b2ea2.
I think either it's started on 24de7c5, or it's just an error from a bad compile.

**Comment by DeathAngel74** [comment]
Could be any number of variables. I broke 2x 2ds's on 005684d. Pokemon Sun stopped working. 12b561a2 fixed the issue on both 2ds's. 2x n3dsxl's weren't effected though.

**Comment by MelonGx** [comment]
@DeathAngel74 Re-testing since the O3DS with DSiWare unable to boot has a CTRTransferred DSi error. 
Fixing it with installing those 5 TWL CIAs.....Fixed.

12b561a has no this issue from the retest.
a1b2ea2 has no this issue either.

**Comment by TheNain38** [comment]
@TuxSH Does something in one of these [commits](https://github.com/AuroraWright/Luma3DS/commits/master/patches) between v8.0 and master, that could have caused this? Or maybe it's a change with ctrulib or something... I'll try to recompile Luma v8.0 with the latest ctrulib, it's maybe what is causing the problem...

@DeathAngel74 It still does not work with your boot.firm

@MelonGx Maybe it does only affect the New3DS? And not so many people could of test it recently as it was broken and wouldn't even boot on New3DS
And I already tried to reinstall the 5 TWL CIAs, I'll redo it again just in case it doesn't work because of that (btw I also have the problem with GBA VC games... which means that it also has problems with the AGB_FIRM)

**Comment by MelonGx** [comment]
@TheNain38 My first test was on the New3DS JPN and no issue on both 12b561a and a1b2ea2.
Is it an EUR hardware issue?

**Comment by TheNain38** [comment]
Well, it works fine with Luma v8.0, so I'll try to do regression testing and see at which commit it fails... also, I remebered that some commits had the New3DS unable to even boot, I'll report all of that when I'm done

**Comment by TuxSH** [comment]
Fixed.

**Comment by TheNain38** [comment]
Thanks, it works now, could I know what was the problem or you don't really have the time to explain it?
