### ISSUE TITLE
Satsuki - Data Abort?

### ISSUE THREAD

**Issue by Z6n4** [LumaTeam/Luma3DS#609]
**System model:**
Old 3DS

**SysNAND version:**
11.3.0-36U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**
B9S 1.2

**Luma3DS version:**
8.0

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (OFF)

PIN lock: (OFF)

New 3DS CPU: ()

--
Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )
Enable loading external FIRMs and modules: ( )
Use custom path: ( )
Enable game patching: (X)
Show NAND or user string in System Settings: (X)
Show GBA boot screen in patched AGB_FIRM: ( )
Patch ARM9 access: ( )
Set developer UNITINFO: ( )

**Explanation of the issue:**
Modifying a game.  It could just be an issue with the modified files, I've just never seen this
process listed. it's all in the screen shot below.  I was just looking for some clarity on what this means.  I saw many other "data abort" issues listed here, but none related to this specific process.  This is a specific title, as indicated by the screen shot.  

**Dump file:**
![image](https://user-images.githubusercontent.com/13697975/27144712-f6d7b01e-5100-11e7-8c70-15ef96170181.jpg)

**Comment by MelonGx** [comment]
Customed game should have issue from modification.
Why do you think it's caused by Luma?
