### ISSUE TITLE
Fatal error luma updater-2.1.2

### ISSUE THREAD

**Issue by nicollezr** [LumaTeam/Luma3DS#612]
![img_20170614_141423720](https://user-images.githubusercontent.com/29440321/27150738-c2c3e2a2-511e-11e7-80c1-72b848235dc8.jpg)
Could someone help? 

luma updater-2.1.2

I am using boot9strap 1.2 and luma 8.0. But this error appears in the luma updater:

Checking for new Luma3DS Updater releases...
Downloading https://api.github.com/repos/KunoichiZ/lumaupdate/releases/latest...
Got error: Could not get status code
Ret code: -660561850
Skipping self-update...
Trying detection of current payload version...
8.0-21db0d4
Loaded existing payload in memory, searching for version number...
Downloading https://api.github.com/repos/AuroraWright/Luma3DS/releases/latest...
Could not get status code
Ret code: -660561850

FATAL ERROR
Failed to obtain required data.

Press START to exit.

**Comment by TuxSH** [comment]
Not a Luma3DS issue, go bug the right repository. May be a Github change, idk.
