### ISSUE TITLE
Display IP address on Rosalina menu when InputRedirection is on

### ISSUE THREAD

**Issue by dogtopus** [LumaTeam/Luma3DS#613]
Currently Rosalina only displays IP address when gdbstub is enabled. It will be nice to expand it to InputRedirection.

**Comment by james-d-elliott** [comment]
https://github.com/AuroraWright/Luma3DS/issues/605

**Comment by dogtopus** [comment]
I saw that issue too, but still decided to open a new one since it is relatively easy to check whether InputRedirection is enabled (InputRedirection uses the same wifi lock as gdbstub so the 3ds is guaranteed online when it is enabled) than check whether 3ds is connected to a wifi. (latter involves accessing extra system services)

**Comment by TuxSH** [comment]
9ccfacd06d34e9482ad06d7ed75cbdee0097e2af
