### ISSUE TITLE
Problem while entering to the System Settings app (An exception occurred blackscreen)

### ISSUE THREAD

**Issue by Constoush** [LumaTeam/Luma3DS#614]
**System model:**

[2DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.4.0-37EUR SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[8.0]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)
--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**
After Updating boot9strap to 1.2 and luma to 8.0 with the guide on 3ds.guide on my first SD card, I can't enter into the system settings anymore, this black screen pop up
![20170615_113358](https://user-images.githubusercontent.com/29452712/27176580-6628f5f0-51c3-11e7-9586-21708f8e3864.jpg)
![20170615_113356](https://user-images.githubusercontent.com/29452712/27176579-66254252-51c3-11e7-9535-605b4b44099d.jpg)
I have the files updated on another SD card and this black screen doesn't pop up, such as without SD card it doesn't pop up too.
I tried to move the exact same files from the working SD card to the non-working SD card and it doesn't work.
I don't know why this happens and why one one SD card and not on the other, it doesn't make sense.
I don't know if somebody else has the same issue, I saw something like that on another thread but the solution of this problem doesn't work for me.. I don't know if there's something else to do..
On the SD card that doesn't work I installed fake badges, maybe that's why it doesn't work anymore, but I don't know which folder to delete to let my 2DS create new Home Menu Files, and entering into System Settings through the regular Ninento App or the Badge seems to do the same.

**Steps to reproduce:**

1. Just enter into the system settings

2. There's the error.

**Dump file:**
I can't upload my crash dump, even in ZIP format for some reason

[EDIT] [https://drive.google.com/open?id=0BwNj-VtfRxIOaUx5dzI1alA1azg](url) here's the link to the dump file, I can't upload it directly on the website for some reason

[EDIT 2] With some tests I found that entering into the system settings through the Home Menu options works, it's definitely a problem with the disposition of the home menu, it might be an incompatibility with the MrCheeze's app GYTB if it could help someone who's encountering the same issue

[EDIT 3] After deleting the Home Menu ExtData (00000082 folder for Japanese consoles, 0000008f for USA consoles and 00000098 for EUR consoles) I don't have issues to go into the system setting anymore, I let this subjet here in case of there's people who's having the same issue.

[EDIT 4] I can't access to Decrypt9 and Hourglass9 anymore, it gives me the same type of error that I had with my system settings. I just had to update them manually but it will be good to have a disclaimer somewhere saying to do this.

**Comment by Constoush** [comment]
[https://drive.google.com/open?id=0BwNj-VtfRxIOaUx5dzI1alA1azg](url) here's the link to the dump file, I can't upload it directly on the website for some reason

**Comment by Constoush** [comment]
With some tests I found that entering into the system settings through the Home Menu options works, it's definitely a problem with the disposition of the home menu, it might be an incompatibility with the MrCheeze's app GYTB if it could help someone who's encountering the same issue

**Comment by ZenIsBestWolf** [comment]
While I do not possess a EUR 2ds, on my o3ds xl USA I cannot reproduce. Works fine for me.

_Sent from my BLU Life One X2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Constoush** [comment]
I think it was a problem with my Home Menu data, so it can't be reproduced on a console that works fine
