### ISSUE TITLE
Crash wne exiting from system settings

### ISSUE THREAD

**Issue by the4anoni** [LumaTeam/Luma3DS#616]
**System model:** New 3DS

[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
11.4.0-37E
[e.g. 11.4.0-37U SysNAND, 11.4.0-37J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
8.0 Stable
[e.g. 7.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (None )

PIN lock: ( None)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (*)

Show GBA boot screen in patched AGB_FIRM: (*)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**
When i exit from Nintendo DS network settings ,and then exit from system settings console crashes

**Steps to reproduce:**

1.Go to System Setting
2.Go to network settings
3.Go to Nintendo DS connections
4.Click OK
5.Press B
5.Press Back
6.Exit from system settings

**Dump file:**

Cant upload zip file so get it from there
http://www59.zippyshare.com/v/wNAikXqf/file.html

**Comment by AuroraWright** [comment]
Fixed (or rather hidden since the bug is Nintendo's) in nightlies already
