### ISSUE TITLE
5.3.1

### ISSUE THREAD

**Issue by dragonkni** [LumaTeam/Luma3DS#62]
Newest luma fail to boot on old 3ds xl. Dude you have to see me and my friend faces we unboxed old 3ds xl ( new get from store today ) and after hours of tutorial black screen. We was thinking its brick... Older version of luma work good but this not working.

**Comment by michierusama** [comment]
Redownload again, it was a mistake, now it's fixed.

**Comment by dragonkni** [comment]
Thx guys and keep up good work , your the best !
