### ISSUE TITLE
Screen glitches while using Rosalina

### ISSUE THREAD

**Issue by Lv44EnderShaman** [LumaTeam/Luma3DS#620]
System Model: O3DS
System Version: 11.4.0-37U SysNAND
Entrypoint: Boot9Strap
Luma3DS Version: 8.0 Stable
Configuration Options: Show NAND in User Settings, Show GBA Boot Screen in AGB_Firm

Issue: Sometimes, rarely, when exiting the Rosalina menu on 8.0 Stable branch, the screen will glitch out and show only grey lines on both the top and bottom screen. Music and gameplay in games and the Home Menu will continue as if nothing's wrong. Attempting to close the system and put it in sleep mode does nothing; attempting to re-enter Rosalina freezes the system. Happens rarely in normal games, but more frequently in games running in the extended RAM mode, e.g., Pokemon Sun

Steps to reproduce:
1. Enter Rosalina menu
2. Use an option like taking screenshots
3. Exit Rosalina menu
4. If screen does not glitch, repeat steps 1-3 until the glitch occurs

Unfortunately, I am currently unable to provide a dump file, as the glitch does not display any exception handlers; can provide photo of glitch instead:
![20170615_213349](https://user-images.githubusercontent.com/23041167/27208276-cdc097be-5212-11e7-8edd-250ccbb7641f.jpg)

**Comment by TuxSH** [comment]
I know. Everything I attempted so far to fix it failed.
