### ISSUE TITLE
[Feature Request] Screen capture

### ISSUE THREAD

**Issue by bigretromike** [LumaTeam/Luma3DS#623]
Would it be possible to include screen/video-capture like NTR have. 
It would be a great thing that its missing from Luma, also this would lead to improvement of current stream solutions (software-based)

I know about screenshot option inside Luma, so capturing video should be possible.

**Comment by PolarisBeaver** [comment]
There is one already in Luma 8.0

Access the menu by pressing L+Down+Select together. You will see the screenshot option there.

**Comment by Jimmy-Z** [comment]
I guess he meant screen streaming like NTR, he mentioned screenshot only to prove it should be possible.

That's the most f*cked up English I've ever read.

**Comment by PolarisBeaver** [comment]
Oops I misread it seems. But yes, capture would be great. I'm guessing O3DS can't have this option anytime?

**Comment by bigretromike** [comment]
@Jimmy-Z yeah, a lot of typos; I fixed it (i think). and yes, I'm talking about video capture like the one in NTR.

@PolarisBeaver who knows. Maybe Luma would be able to achieve partial support (with less cpu demanding games)

**Comment by ghost** [comment]
Closed. Feature requests for Rosalina go in #619 only.
