### ISSUE TITLE
Error in Wiki page about options regarding the custom version string

### ISSUE THREAD

**Issue by maki-chan** [LumaTeam/Luma3DS#628]
The [wiki](https://github.com/AuroraWright/Luma3DS/wiki/Options-and-usage) says

> The version strings can't exceed **39 characters**.

Though in the code and as far as my tests on my N3DS worked out, it should say **19 characters**. I don't think Luma3DS can handle files with this much characters and just doesn't use any character beyond the 19th byte in a customversion txt file.

**Comment by ghost** [comment]
I think it refers to custom default payload file path (as of AuReiNand 5.0). So you're right.

**Comment by ghost** [comment]
Thanks, fixed.
