### ISSUE TITLE
Mario kart 7 patching broken

### ISSUE THREAD

**Issue by M-1-RLG** [LumaTeam/Luma3DS#635]
**System model:**

[New3dsXL]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.3U]

**Entrypoint (How/what you're using to boot Luma3DS):**

[B9.]

**Luma3DS version:**

[e.g. 7.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ()

Screen brightness: (max)

Splash: (off)

PIN lock: (none )

New 3DS CPU: (off )

--

Autoboot EmuNAND: (off )

Use EmuNAND FIRM if booting with R: ( off)

Enable loading external FIRMs and modules: ( )

Use custom path: (off )

Enable game patching: (on )

Show NAND or user string in System Settings: (on )

Show GBA boot screen in patched AGB_FIRM: (off )

Patch ARM9 access: (off )

Set developer UNITINFO: (off)

--

**Explanation of the issue:**
Yes, I know what I am doing I've done it tons of times, it doesn't work anymore like it did before luma 7.X, I have everything in the right place and I check everything a bunch of times. On latest luma version

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by TuxSH** [comment]
Could you try the latest commit [here](https://u.nya.is/mxgcqp.firm) please? Just replace the boot.firm on your SD card with this one (and reboot, if you did the former through something like FTPd).

**Comment by Jan200101** [comment]
There seems to be a lack of Reproduction steps.
I'm gonna go ahead and say this is  user error

**Comment by ghost** [comment]
In addition to what @TuxSH said, have you changed anything about your modifications recently? Updates to MK7, updates to the patches, whatever? Or is updating Luma from 7.1 to 8.0 the only factor that's changed?

**Comment by M-1-RLG** [comment]
@Hikari-chin Luma update that is it

**Comment by M-1-RLG** [comment]
@TuxSH Yeah I know where it goes. :P

**Comment by M-1-RLG** [comment]
Okay for some reason this newer build works, even though I was on latest. I guess you built this from source

**Comment by ghost** [comment]
@Dark124 Yes, it was built from source. The "hourlies" site used by Hamcha/Kunoichi's LumaUpdate is actually four commits out of date as of now. Also, if you're using the latest version of LumaUpdate, it no longer allows you to download "hourlies" period, so you'd only be able to update to the current stable release, 8.0.
