### ISSUE TITLE
Homebrew Launcher shutdown

### ISSUE THREAD

**Issue by Tanobully** [LumaTeam/Luma3DS#637]
System model:

[Old 3DS]

SysNAND version (+emu/redNAND version if applicable):

[11.4.0-37E SysNAND]

Entrypoint (How/what you're using to boot Luma3DS):

[Boot9Strap]

Luma3DS version:

[8.0]

Luma3DS configuration/options:

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Before)

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

![67450067-4af8-4ad2-a333-96cb578a4fd9](https://user-images.githubusercontent.com/29551178/27298820-6f326eaa-552a-11e7-8c82-34ce7d6047a5.jpg)

How do I fix it?

**Comment by Slashin-it-up** [comment]
What did you do to get it to crash?

**Comment by ghost** [comment]
Are you using the [latest version of the Homebrew Menu](https://github.com/fincs/new-hbmenu/releases)?

**Comment by Tanobully** [comment]
I'm using version 1.1.1 of hbl and every time I open a tool or any other
application for hbl give me this screen

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-06-19 20:16 GMT+02:00 Yuuki Hikari <notifications@github.com>:

**Comment by ghost** [comment]
Use the [latest version of the Homebrew Menu](https://github.com/fincs/new-hbmenu/releases). Closed.
