### ISSUE TITLE
[Suggestion] Feature to change a console's DeviceID

### ISSUE THREAD

**Issue by Garro** [LumaTeam/Luma3DS#639]
A feature to change the deviceID of a console would be extremely useful for those with the bypassing of the NNID service ban (known also as 022-2812).

This was researched back then with the Sun/Moon ban, there's a dump of different posts related to the ban here: https://gbatemp.net/threads/heres-what-we-know-about-002-0102-and-022-2812.449218/#post-6850004 (Including the trick related to messing up the RAM and the test related to the deviceID)

**Comment by Monotek18** [comment]
It does not work anymore (the "ram" trick)
Anyway that a good way to be flagged.

**Comment by Garro** [comment]
Any source on that?

**Comment by ghost** [comment]
See #286. This particular method doesn't work anymore anyway, but I'll state this clearly: **Methods to bypass bans from Nintendo's online services will not be implemented in Luma3DS, period.**
