### ISSUE TITLE
expanded-memory issues

### ISSUE THREAD

**Issue by pcs3rd** [LumaTeam/Luma3DS#640]
expanded-memory games reboot to nothingness

**Comment by pcs3rd** [comment]
@Hikari-chin may I ask what the fix is? And if it is "reformat system memory", will it effect boot9strap at ALL?

**Comment by ghost** [comment]
Try a later commit like [this one](https://u.nya.is/mxgcqp.firm).

**Comment by pcs3rd** [comment]
Is that a nightly?

**Comment by ghost** [comment]
Actually, I was mistaken. This wasn't a bug on Luma's side at all, actually. See #532. 

And, to respond to your edit, no, a System Format won't remove B9S.

**Comment by pcs3rd** [comment]
thank you. ill try it after making backups.
