### ISSUE TITLE
freeshoop CRASH

### ISSUE THREAD

**Issue by angelmarlboro** [LumaTeam/Luma3DS#641]
in some way random i have this error with free shoop 

http://i67.tinypic.com/65tsth.jpg

luma v8 
and wait i have another problem... if i hold start botton and press power nothing happens, of course my games downloaded in the free shoop works fine for now.

i meen i can´t do this

Instructions

    Boot your device while holding (Start) to launch the Luma3DS chainloader menu

https://3ds.guide/godmode9-usage.html

thanks and sorry for my english

i dont know how to reed the dump file is in binary

**Comment by TuxSH** [comment]
We're not offering help for piracy tools such as freeshop.
