### ISSUE TITLE
A dsp dump feature

### ISSUE THREAD

**Issue by ThatFluffyFox** [LumaTeam/Luma3DS#645]
Since Luma 8.0 came out the .3dsx files that dump the dspfirm.cdc can't work becuase 8.0 broke ninjhax 2.0+ (needed to dump), so maybe you can add a feature that dumps it remade in Luma. or find a fix/patch that makes ninjhax work again?

**Comment by fincs** [comment]
Use [DSP1](https://github.com/zoogie/DSP1/releases) (as per the Guide)
