### ISSUE TITLE
DS / Dsi software not working on O3DS

### ISSUE THREAD

**Issue by piratesephiroth** [LumaTeam/Luma3DS#65]
I'm not sure when this started happening but it was probably around v5.

Any DS software, cart or eshop, always get stuck on a black screen.
A problem with the TWL_FIRM patches perhaps? Because they work fine on the N3DS.
(A9LH, 10.7 sysnand)

**Comment by Shadow322** [comment]
Work's fine on O3DS fix your path with the path changer

**Comment by tobeannouncd** [comment]
You may want to use FBI to reinstall the latest TWL_FIRM title.

I had the same problem and https://github.com/AuroraWright/Luma3DS/issues/61#issuecomment-215471267 fixed it.
