### ISSUE TITLE
Exception error on 8.0(+ntr cfw)

### ISSUE THREAD

**Issue by mb1zz** [LumaTeam/Luma3DS#656]
**Luma3DS configuration/options:**

Default EmuNAND: (x - sysnand only)

Screen brightness: ( 4)

Splash: ( x)

PIN lock: (x )

New 3DS CPU: ( x)

--

Autoboot EmuNAND: ( x)

Use EmuNAND FIRM if booting with R: ( x)

Enable loading external FIRMs and modules: ( x)

Use custom path: ( x)

Enable game patching: ( x)

Show NAND or user string in System Settings: ( x)

Show GBA boot screen in patched AGB_FIRM: ( x)

Patch ARM9 access: ( x)

Set developer UNITINFO: ( x)

--

**Explanation of the issue:**

**Steps to reproduce:**

1. active ntr cfw 

2. launch SuMo->open save

3. back to home menu and open internet browser -> exception error

**Dump file:**

text on display when occured exception error 
--
(red font color)An exception occurred

Processor : ARM11 (core 0)
Exception type : prefetch abort (svcBreak)
Current process : SKATER (000400300000AE02)

R0 00000000 R1 00000000
R2 00000000 R3 002582FF
R4 031B8000 R5 003773C8
R6 003773C0 R7 04E00000
R7 00000000 R9 00000000
R10 00000000 R11 00000000
R12 00000000 SP 0FFFFFD8
LR 00258303 PC 0031DC28
CPSR 60000010 FPEXC 000000F8

You can find a dump in the following file:
(dump file address)

**Comment by TuxSH** [comment]
NTR CFW doesn't support launching applets iirc.
