### ISSUE TITLE
Pokemon Red/Yellow/(Blue?) cause Prefetch Abort crash

### ISSUE THREAD

**Issue by N-G-Neer** [LumaTeam/Luma3DS#659]
System model : Old 3DS

SysNAND version : 11.4.0-37E SysNAND

Entrypoint : Boot9Strap

Luma3DS version : 8.0 stable

Luma3DS configuration/options: Default EmuNAND 1, Screen Brightness 4, Splash Before, PIN off, Show NAND or user string.

Explanation of the issue : 

Downloaded and installed Pokemon Red and Yellow (GBA) -snip-.
Both initially crashed at the Nintendo 3DS logo with the following error : 
An exception occurred.
Processor: ARM11 (core1)
Exception type: prefetch abort (svcBreak)
Current process: loader
(dump file included)

After deleting and reinstalling them a few times, I got Yellow to work while Red still crashes.

Steps to reproduce : 
1. Download Pokemon Red or Yellow on Freeshop (French Versions at least)

2. Launch the titles once installed.

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1100719/crash_dump_00000000.zip)

**Comment by j0zu3** [comment]
This happen to me with my own dump of mhgen, same exception type and same current process error, I had to do a new dump and reinstall a few times until it worked

Edit: dump file

[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1100756/crash_dump_00000000.zip)

**Comment by ghost** [comment]
Can't reproduce this, but also: We don't and won't provide support for issues pertaining to piracy tools here.
