### ISSUE TITLE
O3DS Regression (GW Downgrade) 5.3.1

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#66]
As you stated in the release 

"Please note I need testing with this change, as it might cause issues for Old 3DSes which used the Gateway launcher to downgrade the console in the past. I have verified this is probably not an issue as all the leftovers seem to be deleted after an update, but I'm still not 100% sure. If you notice a regression (Luma failing to boot) I'd like to know."

The old 3DS I have was originally downgraded from 7.1->4.2 using the GW downgrader. Then manually updated to 9.2 later on. However, after installing 5.3.1, both emuNAND and sysNAND fail to boot, hanging on a black screen.

Reverting to 5.3 allows the system to operate normally again. If you need any more information, let me know.

**Comment by AuroraWright** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-get-a-black-screen-on-boot-with-an-old3ds-which-was-downgraded-from-the-gateway-menu-in-the-past :) (just done)
