### ISSUE TITLE
An exception occurred Stack Dump

### ISSUE THREAD

**Issue by MrFrawgg** [LumaTeam/Luma3DS#664]
![img_20170626_211951](https://user-images.githubusercontent.com/29719721/27567036-3fc3d676-5ab7-11e7-8048-60a9d0987bc8.jpg)
I followed this guide https://3ds.guide/installing-boot9strap-(browser) exactly!

On an Nintendo 3DS XL firmware 8.1.

I get to Section IV - Configuring Luma3DS and select "Show NAND or user string in System Settings" and then press START to save. After that I get the crash dump in the picture.

I can get back into Luma by holding Select at boot or by deleting config.bin.

Other than that I'm stuck. Never had this issue before.

Crash Dump:
https://3.sharebylink.com/1/?YR0eDvrSSv8k

EDIT:
Figured it out!

Anyone in the future be sure to use Legacy version of boot.firm when your on firmware version 8.1 otherwise you'll get this crash dump error.

**Comment by ghost** [comment]
Could you try a newer build, like [this one](https://astronautlevel2.github.io/Luma3DS/builds/Luma3DS-e67c6ed.zip)?

**Comment by Margen67** [comment]
Do astronautlevel2's builds work properly?

**Comment by MrFrawgg** [comment]
I figured it out. I needed to use a Legacy version of boot.firm because I was on 8.1 firmware.

The guide didn't state that until the next page a couple paragraphs down. After that I was golden.

Hopefully this will help anyone in the future.

**Comment by TheNain38** [comment]
@MrFrawgg Well, you can close this issue then

**Comment by rj197** [comment]
how to fix the stack dump because i need help please

**Comment by rj197** [comment]
on my 3ds
