### ISSUE TITLE
[Feature Request] Add xdelta patching

### ISSUE THREAD

**Issue by TheNain38** [LumaTeam/Luma3DS#667]
Would it be possible to add xdelta patching, the same way as IPS patching is done?

**Comment by Derek1199** [comment]
@TheNain38  do feature requests in #619

**Comment by dogtopus** [comment]
vcdiff or xdelta1?

**Comment by TheNain38** [comment]
xdelta1 is old, so maybe supporting vcdiff would be better

**Comment by AuroraWright** [comment]
Too much code is needed for that patch format, can't afford it with O3DS being on the verge of running out of usable memory.
