### ISSUE TITLE
ACNL crashes while using NTR in a friends town.

### ISSUE THREAD

**Issue by Derek1199** [LumaTeam/Luma3DS#668]
**System model:**
N3DS
**SysNAND version (+emu/redNAND version if applicable)
11.4.0-37U 
**Entrypoint (How/what you're using to boot Luma3DS):**
Latest commit of b9s.
**Luma3DS version:**
https://github.com/AuroraWright/Luma3DS/commit/e67c6ed3ee6804d29aca5d5e4b09493de514ceba

*Luma3DS configuration/options:**

Default EmuNAND: (*)

Screen brightness: (1)

Splash: ( )

PIN lock: ( )

New 3DS CPU: (*)

--

Autoboot EmuNAND: (*)

Use EmuNAND FIRM if booting with R: (*)

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: (*)

Show NAND or user string in System Settings: (*)

Show GBA boot screen in patched AGB_FIRM: (*)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**
While using rydog's acnl NTR cheats, going to a friend's town and then pressing the "a" button causes an exception to occur. This has been happening since around latest commit or a few before. (I didn't play yesterday) I'm also using latest commit of the plugin but yeah this is an issue that needs fixed now.

**Steps to reproduce:**

1. Use latest commit of luma and the latest commut of the Acnl NTR plugin cheat by Rydog.
2. Go to a friend's town and press the a button. You will be greeted with an arm 11 exception.

**Dump file:**

**Comment by DeathAngel74** [comment]
I'm running the latest commit of Luma3DS (e67c6ed) and B9S (574b387), with game patching turned on in Luma config. No crashes on 2x 2DS's, nor 2x N3DSXL's. Maybe NTR cheat plugin is the problem, not Luma3DS?

**Comment by Derek1199** [comment]
Did you go to a friend's town and press "a"?

**Comment by DeathAngel74** [comment]
This sounds more like a NTR problem than a Luma3DS problem though.

**Comment by Derek1199** [comment]
I see. Hmm. Try using latest commit of the NTR cheats by rydog. It's an NTR
problem, but didn't occur until using latest commit of luma. So idk.

**Comment by Derek1199** [comment]
I did compile luma myself though.

**Comment by DeathAngel74** [comment]
One way to check....try friend's town, pressing "a", without NTR and with plugins disabled. Then you'll know for sure if its NTR or Luma.

**Comment by Derek1199** [comment]
It's NTR though. But it didn't occur until using latest luma commit. Weird.

**Comment by DeathAngel74** [comment]
You may have to revert a few commits of NTR to find one that doesn't crash. Did you report this on the NTR github as an issue?

**Comment by Derek1199** [comment]
It's the plugin itself probably though. Also sometimes , this is extremely
rare, but svc_controlmemory when running bootNTR also fails. After running
it a popup in home menu will say svc_controlmemory failed. This has only
happened twice though. So I should put it as a issue On the plugin page as
well.

On Jun 27, 2017 8:22 PM, "DeathAngel74" <notifications@github.com> wrote:

You may have to revert a few commits of NTR to find one that doesn't crash.
Did you report this on the NTR github as an issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AuroraWright/Luma3DS/issues/668#issuecomment-311546064>,
or mute the thread

**Comment by Margen67** [comment]
@DeathAngel74 The issues tab was removed from the repo

**Comment by T3CHNOLOG1C** [comment]
@Derek1199 try reverting to stable build and see if that fixes it, if not, it's probably a plugin / ntr problem

**Comment by ghost** [comment]
This is an issue with NTR, not Luma.

**Comment by Derek1199** [comment]
OK.

**Comment by Derek1199** [comment]
Apparently it was luma conflicting with NTR or the plugin. It's fixed now, no longer getting the error. Not sure what caused it oh well. Thanks
