### ISSUE TITLE
Exception ocurred using homebrew cthultu

### ISSUE THREAD

**Issue by alnoses** [LumaTeam/Luma3DS#670]
**System model:**

New 3ds xl

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap/Sighax 1.2

**Luma3DS version:**

Luma 8.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (4 )

Splash: ( off)

PIN lock: (off )

New 3DS CPU: ( off)

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

Enter the cthulhu man to delete the activity log I gave the option to edit by accident I gave the button b to go back I gave him cancel changes and I skip the screen

**Steps to reproduce:**

1.Enter the homebrew from the rosalina menu

2.Enter the homebrew Cthultu

3.Activity log magnament

4.Edit software library

5.Press the key b

6.Confirm or cancel save changes

PD: fail is reproduce

**Dump file:**
[crash homebrew cthultu.zip](https://github.com/AuroraWright/Luma3DS/files/1108052/crash.homebrew.cthultu.zip)

**Comment by ghost** [comment]
Has Cthulhu been updated for the 2.0 version of the Homebrew Menu? I doubt this is a Luma issue.
