### ISSUE TITLE
Latest Release (v8.0) with Rosalina Support causes framedrops.

### ISSUE THREAD

**Issue by Bolt23** [LumaTeam/Luma3DS#673]
I don't know if others have experienced this or not but Rosalina is causing frame drops in games specific ally Sun/Moon Single Battles (Normal Trainer Battles) which were not caused before! EMM games have frame drops which are easily visible! @AuroraWright and @TuxSH you can check them yourself! I played with the last 7.1 hourly which supported B9S 1.2 and then the frame rate came back to normal! I know that Rosalina is a handy menu but the amount of 3DS' computer resources it uses is high I suppose? Maybe you could lower the RAM usage.

**Comment by ghost** [comment]
Can't reproduce. There's likely some other confounding factor, or you've just got the nocebo effect. Additionally, were this a Luma 8.0 issue, it would affect a ton of people given the popularity of those games, especially Pokemon, and thus would've very likely been reported as an issue almost instantly.
