### ISSUE TITLE
A few Wiki changes

### ISSUE THREAD

**Issue by NightScript370** [LumaTeam/Luma3DS#676]
https://github.com/AuroraWright/Luma3DS/wiki/Installation-and-upgrade#optional-making-luma3ds-work-with-an-external-boot-manager  -  https://gbatemp.net/threads/release-the-bootctr9-release-thread.435347/ This has a Boot9Strap 1.2 build.

https://github.com/AuroraWright/Luma3DS/wiki/Options-and-usage#options-changed-in-last-major-release  -  Outdated with 8.1

**Comment by ghost** [comment]
Fixed, thanks.
