### ISSUE TITLE
Luma3ds load failed !!! Arm 11 (Core 1) / Exception Type: prefetch abort (svcBreak) Help !!!

### ISSUE THREAD

**Issue by Kforforce** [LumaTeam/Luma3DS#677]
Hi Guy. 

I hope somebody can fix this problem. I have a NEW 3DS XL (US), the Arm9 was setuped on this system, i'm use luma 5.5, it still work, after that i update via Arm9loader.bin form luma 6.6, the screen is black and stuck  at this step to boot. 

So i update Arm9 to B9strap, my system in arm9 is 11.0 when i update the B9strap with B9strap 1.2 - Luma boot.firm 8.0 and then the screen show the crashed code like that. 

An Exception occurred 

Processor:  ARM11 (Core 1)
Exception type: prefetch abort (svcBreak) 
Current process: loader (0000000000000000)

i hope somebody help me .... I'm can't fix it :( by 100 ways trying ........

![19553510_1816065425086882_1497195073_n](https://user-images.githubusercontent.com/29763843/27664460-d680dec0-5c91-11e7-8150-03b1ad1c0298.jpg)

**Comment by Hikari-chin** [comment]
Could you try [Luma3DS 8.1](https://github.com/AuroraWright/Luma3DS/releases/latest), please?

**Comment by ghost** [comment]
Could you try [Luma3DS 8.1](https://github.com/AuroraWright/Luma3DS/releases/latest), please? If that does not solve the issue, it's likely you installed a modified system title at some point; Luma does not support these as they can cause patches to fail as well as other strange issues. You'll need to figure out which System Title you've modified and install a clean .CIA of it with FBI or similar.

**Comment by AuroraWright** [comment]
Most likely Home Menu or NS, those were floating around patched for region free a while ago, with their version spoofed to max so they wouldn't get updated

**Comment by david-zzj** [comment]
i have the same crash，is it solved？

**Comment by Hercules187** [comment]
I have this on a 2ds which previously had CFW rxtools on it select and start work taking into config modes but console doesn't boot....

**Comment by david-zzj** [comment]
now i cannot enter the  system, so how can i install a clean .CIA with FBI...
please give me some suggestsuggestion, THX...

**Comment by RatManz34PLUS2** [comment]
I am getting this error I hope I can fix this.

![3ds error question](https://user-images.githubusercontent.com/37990439/41508467-3bedc2fc-723d-11e8-8a23-24c20a51b2ed.jpg)

**Comment by Meltandu27** [comment]
I found a solution to delete all the files found in d:(you SD cards)\luma\titles
it worked for me 
try to see me it works directly

**Comment by plop8989** [comment]
> I found a solution to delete all the files found in d:(you SD cards)\luma\titles it worked for me try to see me it works directly

Im having the same issue but i dont have any titles installed and im getting this error after a fresh install on a clean system. Is there any fix?
