### ISSUE TITLE
Homebrew Launcher doesn't work anymore after saving settings for switching .hb title to current app

### ISSUE THREAD

**Issue by IngeniousDefault** [LumaTeam/Luma3DS#679]
[New 3DS]

**11.4E**

**boot9strap version 1.2**

**Luma3DS version: 8.1**

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**

Hi there,

I want to use the Health & Safety app to launch the Homebrew Launcher. If I just switch the. hb app to H&S I can launch all .3dsx app. However as soon as I save the change and restart the Homebrew Launcher no app launches anymore.

**Steps to reproduce:**

1. Switch .hb title to Health & Safety
2. Save settings
3. Exit HBL
4. Launch HBL
5. Select one .3dsx file

**Dump file:**
Because the system does not crash I can not provide any dump file.

**Comment by ghost** [comment]
This is a known issue with H&S. It's being looked into.
