### ISSUE TITLE
Patch out requirement to access conntest.nintendowifi.net

### ISSUE THREAD

**Issue by tranaconda** [LumaTeam/Luma3DS#68]
I have blocked one of my 3DS from WAN for testing reasons and noticed that all apps that use WiFi are stuck "Waiting for wifi..." (FTPd) or something unless they are allowed to connect to conntest.nintendowifi.net. This means you can't use network apps in closed networks or when your internet is out.

I did get arround this by poisoning my local DNS to point to my computer and serving the webpage there, but it'd be nice to patch this out somehow (optionally, as I realize it could break other things).

Browsing 3dbrew.org, I guess it must be somewhere in ac:u, probably GetWifiStatus or IsConnected.

**Comment by ghost** [comment]
From my knowledge, it's part of the WiFi code itself, as it is on Nintendo DS, DSi, Wii, WiiU, etc..

**Comment by tranaconda** [comment]
Please be more specific, what exactly do you mean by "WiFi code". Is my assumption of it being in ac:u wrong?

**Comment by d0k3** [comment]
This is correct - this is part of the Wifi code. I don't know if Aurora can fix this in Luma3DS, and also, if it is a good idea to do this, cause apparently the console needs some way to check if Wifi is working.

**Comment by RShadowhand** [comment]
Your best bet would be to redirect conntest.nintendowifi.net to a local address within the network using your router, or simply using a DNS server that does that.

**Comment by tranaconda** [comment]
If you read the OP, you can see thats what I'm doing right now. But this is annoying and people who don't know about DNS poisoning can't use FTPd or other WiFi enabled apps when their internet is down. It could be an optional patch, as I suggested.

**Comment by piratesephiroth** [comment]
MicroSD Management doesn't require the connection test to be successful (it can be used in a local network without internet access) so it's definitely possible.

**Comment by TuxSH** [comment]
The thing is that conntest.nintendowifi.net is used to automatically select which access point to use.

It doesn't apply to MicroSD Management since the latter forces you to select a precise access point.
