### ISSUE TITLE
Crashes.

### ISSUE THREAD

**Issue by poudink** [LumaTeam/Luma3DS#685]
**System model:**

Old 3DS

**SysNAND version:**

11.4.0-37U

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (4 )

Splash: ( off)

PIN lock: ( off)

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Use custom path: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

--

**Explanation of the issue:**
TWLoader crashes my 3DS. - occasionnaly crashes too. I would have asked on the discord but the link didn't work.

**Steps to reproduce:**

1.Boot TWLoader.

2.Crash.

**Dump files:**

https://www.dropbox.com/s/wnbk5qoa82orddm/arm11.zip?dl=0

**Comment by ghost** [comment]
Can't reproduce. Try updating those programs.
