### ISSUE TITLE
[Feature Request] FTP server function through Rosalina

### ISSUE THREAD

**Issue by SerraraFluttershy** [LumaTeam/Luma3DS#687]
Given that Rosalina is now a system module, and that FTP has a working implementation though apps and homebrew such as FTBrony, FTPDS, and most knowingly FTPDB....is it possible for Rosalina to open up the console for FTP functions in the background (barring certain directories, obviously) for multitasking?

This would be a great addition as this would eliminate the need for a separate app, but still keep the 3DS's SD Card Management feature intact.

**Comment by fox8091** [comment]
See issue #619 and close.

**Comment by ghost** [comment]
Rosalina feature requests go in #619. This has already been requested there by @Plailect, though.
