### ISSUE TITLE
Things Drawn on the Bottom softlock Rosalina

### ISSUE THREAD

**Issue by Jan200101** [LumaTeam/Luma3DS#689]
**System model:**

Old 3ds XL

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

https://github.com/AuroraWright/Luma3DS/commit/31e2243c5cb7736ff30be3781dfd2c854c2f61aa

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: (After)

PIN lock: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

If another app is drawing a object onto the bottom screen (like NTR or similar, this does not limit itself to NTR) Rosalina softlocks the console on access

**Steps to reproduce:**

1. Start anything that draws on the bottom screen ([Ntr Overlay Sample](https://github.com/44670/ntr_overlay_samples/releases) for example) 

2. Open Rosalina

Note:
 I have taken NTR Overlay Sample as a example for convenience as most people already have NTR installed

**Comment by Sonlen1414** [comment]
Can confirm, all settings match above aside from Clock+L2 on a New 3DS XL, opening Rosalina while using a NTR Plugin that draws to the bottom screen locks the conole and forces a shutoff holding the power button.

**Comment by ghost** [comment]
That happens to me everytime, activating Rosalina and NTR CFW at the same time will collide each other and causes to freeze the game completely.

**Comment by fox8091** [comment]
Is it only with NTR? If so, that's likely because two different apps are trying to stall the system, resulting in the entire console softlocking.

**Comment by Jan200101** [comment]
Its been confirmed to happen with NTR but we cant say for sure that normal applications arent affected because of the lack of Applications that draw a permanent object on screen

**Comment by TuxSH** [comment]
With the lack of other examples than NTR I'll assume it's a NTR issue.

**Comment by ghost** [comment]
I think this is an issue with certain plugins you're using. I can't reproduce this with NTR CFW 3.5, I can trigger both the Rosalina and NTR menu without locking the system, likewise with the Gateshark2NTR menu in certain applications.

I attempted: 
* Open NTR, then Rosalina
* Open Rosalina, then NTR
* Open Gateshark2NTR, then Rosalina
* Open Rosalina, then Gateshark2NTR

None of these caused any freezes or crashes, nor did opening all three menus at once. I'm going to close this for now; if it becomes evident that this *is* actually a Rosalina issue, I'll reopen it.

**Comment by Hikari-chin** [comment]
Ro

**Comment by Jan200101** [comment]
@Hikari-chin Not the NTR menu.
If something draws on the normal screen like the example plugin mentioned in OP it freezes

**Comment by ghost** [comment]
Yes, I'm saying that, NTR and Gateshark2NTR both draw on the screen, and don't freeze, so it's probably an issue with that specific plugin.
