### ISSUE TITLE
SSB,MH4,MHX Blank Screen on Changed Region

### ISSUE THREAD

**Issue by stayfr0sty141** [LumaTeam/Luma3DS#69]
Please Fix this broo 

i have an REG japan to USA region 
and want to play SSB,MH4,MHX its Blank Screen just that.. 

PS : i'm not using BOOT Manager such BootCTR or anything..

its fine on REAL USA Console..
buat for changed region.. stuck on blank screen...

**Comment by AuroraWright** [comment]
Region has **nothing** to do at all with the reboot patch, so this is 100% a mistake on your part in the region changing process (removed NATIVE_FIRM probably)

**Comment by stayfr0sty141** [comment]
removed native firm ?
