### ISSUE TITLE
[Feature Request] Simulated home button press option in misc. Luma menu

### ISSUE THREAD

**Issue by benduckwdesign** [LumaTeam/Luma3DS#691]
**Explanation of the issue:**

It would be great to have the option to simulate a home button press through Luma, as sometimes the home button can be a pain... Especially if 3DS hard-mods are performed by inexperienced hackers.

**Steps to reproduce (ideally):**

1. Hold down combo for Luma menu.

2. Go into misc. options

3. Select home button press

4. Exit Luma menu

5. Home button press is executed.

**Comment by ghost** [comment]
Rosalina feature requests go in #619.
