### ISSUE TITLE
Pokemon Art Academy can not be patched.

### ISSUE THREAD

**Issue by FlameBeam** [LumaTeam/Luma3DS#699]
System model: new3DS

SysNAND version: 11.4.0-37J

Entrypoint: Boot9Strap

Luma3DS version: 8.1 (game patch enabled)

Explanation of the issue:
I tried to make a game patch for Pokemon Art Academy, but it can't work.
I tested with JPN(00040000000CF900) and USA(00040000000D0A00) version gamecart, but they all can not be patched.

**Comment by AuroraWright** [comment]
Are you referring to LayeredFS? What happens?

**Comment by FlameBeam** [comment]
Yep, I referring to LayeredFS. 
If I put a romfs folder as a LayeredFS patch, nothing happens in game.
But exefs.bin can be patched. 
I also try the OnionFS, same thing like LayeredFS.

**Comment by AuroraWright** [comment]
This should be fixed in the latest commit: https://transfer.sh/MgSht/boot.firm, please test and report back

**Comment by FlameBeam** [comment]
I tested, the LayeredFS patch can be work for this game now! Thanks!
