### ISSUE TITLE
Please help 3ds firmware problem

### ISSUE THREAD

**Issue by FeelinLucky12** [LumaTeam/Luma3DS#701]
Hi im lucky and i have a 3ds that runs 11.3 homebrewed but theres one problem my 3ds wont turn on without the sd card im using cfw and a9lh. But here is the problem i accidental deleted my data on the sd card and didnt back up. When i turn on my 3ds the blue ld light turns on and fades away anyone please help.

**Comment by FeelinLucky12** [comment]
Plus i lost the original sd card so any suggests

**Comment by ghost** [comment]
Luma's GitHub issues aren't for tech support. Try the [Nintendo Homebrew Discord](https://discord.gg/MWxPgEp).
