### ISSUE TITLE
[3DS Game Crash]Heroes of Ruin "RiftWalk" error.

### ISSUE THREAD

**Issue by ScytheIronclaw** [LumaTeam/Luma3DS#707]
**System model:**

new3DS

**SysNAND version (+emu/redNAND version if applicable):**

Sys 11.2.0-35U

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.1-557F205
https://github.com/AuroraWright/Luma3DS/commit/557f2057f772298f4c4b85cdea9a6985b115443d

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (1 )

Splash: (Off )

PIN lock: (Off )

New 3DS CPU: (Off )

--

Autoboot EmuNAND: (Off)

Use EmuNAND FIRM if booting with R: ( Off)

Enable loading external FIRMs and modules: ( Off)

Enable game patching: (On )

Show NAND or user string in System Settings: (On )

Show GBA boot screen in patched AGB_FIRM: (Off )

Patch ARM9 access: (Off )

Set developer UNITINFO: (Off )

Disable ARM11 exception handlers: (Off )

--

**Explanation of the issue:**

After launching Heroes of Ruin and setting the following initial settings:
Enable Spotpass? NO > Enable User Generated Content? NO > Receive Notifications from Square Enix? NO

After selecting these options the following error is displayed on the bottom screen:

Error type: logged
Process ID: 41
Process name: RiftWalk
Process title ID 0x0004000000075100

Address: 0x003ec3dc

**Steps to reproduce:**

1. Launch Heroes of Ruin

2. Select NO on all three options.

**Dump file:**
Like @Hikari-chin mentioned in her most recent comment, this is an internal error thrown by the game itself and not Luma. Bad dump. Time to hunt down a physical copy, dump it, and test it.

**Comment by ghost** [comment]
Sounds like bad dumps, but we don't support piracy tools or websites.

**Comment by Margen67** [comment]
>11.2

**Comment by ScytheIronclaw** [comment]
I just figured out why this is invalid. Nevermind. I'm updating the OP now with the proper required information. Sorry for the trouble!

**Comment by ghost** [comment]
I actually misread this a bit, my apologies. I'll look into this.

**Comment by ghost** [comment]
I confirmed this as an actual issue with Luma. While it's possibly due to laziness on Square Enix London's part, it will be looked into and fixed. Thank you.
