### ISSUE TITLE
Input Redirection is disabled after waking up from sleep

### ISSUE THREAD

**Issue by rereprep** [LumaTeam/Luma3DS#715]
System model:
New 3DS XL

SysNAND version (+emu/redNAND version if applicable):

[11.4.0-37E SysNAND]

Entrypoint:

B9S

Luma3DS version:

8.1 stable

Luma3DS configuration/options:

Default EmuNAND: ( )

Screen brightness: (4 )

Splash: (Off)

PIN lock: ( Off)

New 3DS CPU: (Off )

Autoboot EmuNAND: (Off )

Use EmuNAND FIRM if booting with R: (Off )

Enable loading external FIRMs and modules: (Off )

Enable game patching: (Off )

Show NAND or user string in System Settings: (On )

Show GBA boot screen in patched AGB_FIRM: (On )

Patch ARM9 access: ( Off)

Set developer UNITINFO: (Off )

**Explanation of the issue:**
Input Redirection is disabled after waking up from sleep. Turning the input redirection off and on from the Rosalina menu works.

**Steps to reproduce:**

1. Setup the Input Redirection and make sure it works (wifi is on, pc client is working).

2. Close the lid to make the 3ds go to sleep mode, open the lip back and Input Redirection will not work unless you turn it off and on again from Rosalina menu.

**Comment by TuxSH** [comment]
It seems I have the same issue with debugger... I guess it's due to some vodoo the AC modules does, and it looks like an enormous PITA to attempt to fix for only little gain :/
