### ISSUE TITLE
Crash HomeMenu; Friends ands Notifications

### ISSUE THREAD

**Issue by kaitomugui** [LumaTeam/Luma3DS#718]
System model: New 3ds XL
11.4.0-37U SysNAND
Boot9Strap 1.2
Luma3DS version: 8.1-557f205

Dump File;
[arm11.zip](https://github.com/AuroraWright/Luma3DS/files/1136619/arm11.zip)

**Comment by ghost** [comment]
Can't reproduce, exact same sysNAND version, b9s version, etc.
