### ISSUE TITLE
Chainloader not working with Luma 8.1

### ISSUE THREAD

**Issue by PhoenixGamer** [LumaTeam/Luma3DS#723]
![2017-07-12](https://user-images.githubusercontent.com/29511598/28120340-0a63d4b4-6718-11e7-9a76-2fb96d9cf9b6.png)
**System model:**

[Old 3ds]

**SysNAND version (+emu/redNAND version if applicable):**

[11.4.0-37E Sysnand]

**Entrypoint:**

[Bs9]

**Luma3DS version:**

(8.1 Stable)

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (off)

PIN lock: (off)

--

Autoboot EmuNAND: (No Emunand)

Enable loading external FIRMs and modules: (yes)

Enable game patching: (yes)

Show NAND or user string in System Settings: (yes)

Show GBA boot screen in patched AGB_FIRM: (no)

Patch ARM9 access: (no)

Set developer UNITINFO: (no)

Disable ARM11 exception handlers: (no)

--

**Explanation of the issue:**
Luma won't start chainloader by presin start at boot

**Steps to reproduce:**

1.Put any chainload payload in plugin folder

2.start 3ds while holding start

**Dump file:**

No dump file

**Comment by astronautlevel2** [comment]
Hello,

Can you send a screenshot of the payloads folder?

**Comment by Shadow322** [comment]
its because u have a code.bin in rw/luma on nand as well as sd:/luma

**Comment by ihaveamac** [comment]
@Shadow322 umm what? how is this related?

**Comment by PhoenixGamer** [comment]
theres no code.bin in on my sd

**Comment by astronautlevel2** [comment]
@PhoenixGamer 

A couple things to try:

1. Delete the Y_GodMode9 folder
2. Update the X_GodMode9.firm to the latest version on the GM9 repo
3. Rename it to just GodMode9.firm and hold start on boot

**Comment by PhoenixGamer** [comment]
doesn`t work

**Comment by ghost** [comment]
Can't reproduce. Additionally, if you've only got one payload in /luma/payloads holding Start with launch it, instead of the chainloader menu. Furthermore, delete the "Y_GodMode" folder if you haven't already, it serves no purpose.

**Comment by Slashin-it-up** [comment]
@Hikari-chin You should remove the "Can't Reproduce" label since there is only one payload on in there.

**Comment by ghost** [comment]
@HugaShire I tested with both multiple payloads and a single payload in the /luma/payloads folder, and the chainloader functioned as expected in both scenarios, so indeed, I couldn't reproduce it.
