### ISSUE TITLE
[Bug] Force quitting A .cia Application to The Homemenu Causes Homemenu Game Titles To Disapear

### ISSUE THREAD

**Issue by clasher58** [LumaTeam/Luma3DS#734]
**System model:**
Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**
11.5.0-38U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**
Sighax

**Luma3DS version:**
8.1 stable 

**Luma3DS configuration/options:**
Default EmuNAND: (1)

Screen brightness: (4)

Splash: (off)

PIN lock: (6)

Autoboot EmuNAND: (no)

Use EmuNAND FIRM if booting with R: (no)

Enable loading external FIRMs and modules: (no)

Enable game patching: (no)

Show NAND or user string in System Settings: (yes)

Show GBA boot screen in patched AGB_FIRM: (no)

Patch ARM9 access: (no)

Set developer UNITINFO: (no)

Disable ARM11 exception handlers: (no)

**Explanation of the issue:**
When I open and use a .cia application (not all of them), and it force quits to the home menu, all of the upper logos/banner for each application/game disappears. It might because of the .cia its self but I am just reporting just incase.

 ##

**Steps to reproduce:**
Some applications that force quit may not work, but some will
1.Open a .cia application that can force quit (I recommend luma updater 2.1.2) 
Others 
-CiaAngel Pressing the quit button
-FBI .cia Pressing start button
2.Do what it takes to force quit into the home menu (On luma updater, you press the start button).

**Comment by Slashin-it-up** [comment]
This is because the homemenu pretty much is ran differently. This is due to the cia itself not Luma3DS.
