### ISSUE TITLE
[Feature Request] Plugin Support

### ISSUE THREAD

**Issue by DevShadd** [LumaTeam/Luma3DS#735]
Plugins are also needed more and more for the 3DS mod scene. Having plugins built into Luma would allow simpler ways to setup and use plugins. Plugin support would also allow further improvements to overall system stability and other minor adjustments to enhance the user experience. ( ͡° ͜ʖ ͡° )

Plugins should have the following support:
►Plugins can be enabled/disabled via Rosalina menu
►Plugins should be able to not run until under certain circumstances when a plugin is enabled (when an app or game loads, certain system settings are enabled, etc.)
►Allow plugins to force disable manual enabling/disabling to the plugin and other certain plugins (to prevent any issues)

**Comment by Margen67** [comment]
#619

**Comment by Slashin-it-up** [comment]
Close this issue this is:

1. A duplicate 

2. Should belong in #619
