### ISSUE TITLE
HB launcher exception occurred

### ISSUE THREAD

**Issue by jryn** [LumaTeam/Luma3DS#739]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.5.0-38E SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[8.1]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
An Exception occurred while trying to launch hblauncher via download play after using Rosalina menu to swap

**Steps to reproduce:**

1. Use Rosalina to switch Download play to hb launcher as suggested by [3ds.guide](https://3ds.guide/finalizing-setup)

2. Relaunch into this screen 
![20170721_155026](https://user-images.githubusercontent.com/30337494/28454484-0c9cffe0-6e2e-11e7-87cb-04137dc09d2e.jpg)

**Dump file:**

[crash_dump.zip](https://github.com/AuroraWright/Luma3DS/files/1164864/crash_dump.zip)

**Comment by ghost** [comment]
Can't reproduce. I use Download Play as my takeover app without issue. You likely need to [update your boot.3dsx](https://github.com/fincs/new-hbmenu/releases).
