### ISSUE TITLE
Can't load firmware.bin when quit from TWL mode or GBA mode

### ISSUE THREAD

**Issue by ITJesse** [LumaTeam/Luma3DS#74]
When I quit from GBA VC games or quit from a DS flashcard, the BootNTR can't load. I think the cfw have load the wrong firmware from CTR Nand but not fireware.bin file.

Sorry for my poor English.

**Comment by RShadowhand** [comment]
Can't reproduce. Used my DS Flashcart, quit, went to NTR, worked fine.

**Comment by cheatfreak47** [comment]
Can't reproduce either, though I have noticed that NTR does fail to boot properly occasionally, usually rebooting fixes it though. 

I don't believe this is a Luma3DS issue.

**Comment by ITJesse** [comment]
Maybe fixed in the newest release.
