### ISSUE TITLE
I cant access my home menu on my O3DS XL

### ISSUE THREAD

**Issue by jjja909** [LumaTeam/Luma3DS#740]
**System model:**

Old 3ds XL

**SysNAND version (+emu/redNAND version if applicable):**

11.3.0-37U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.2

**Luma3DS version:**

8.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Whenever I turn on my 3DS, an error screen popped up, saying (in red text) 
(White text) Error type: logged
Process ID : 15
Process title ID: 0x0004003000008f02

Address: 0x00164654
Error code: 0xd900458b

Press any button to reboot"

It happened when I was playing pokemon sun, I went to the home screen with the app still open, I closed my 3DS and put it in my pocket, I took it out of my pocket and it was off! I turned it on and, error screen. Pokemon sun was downloaded on my 3ds and the thing that all the people with the problem had in common, was that we all had a ds game in the slot... Im not sure how to fix this please help.

**Steps to reproduce:**

1. Turn on the 3ds

**Comment by ghost** [comment]
The behavior you describe sounds like a bad NAND or SD card rather than an issue with Luma; try restoring your NAND and/or checking your SD card with something like h2testw. 

If you continue to experience issues, try the [Nintendo Homebrew Discord](https://discord.gg/C29hYvh) for further support; the Luma issue tracker isn't the proper place for it.

**Comment by 200zero** [comment]
we been trying Discord and no luck at all

**Comment by Slashin-it-up** [comment]
Try booting without a Game.

**Comment by Slashin-it-up** [comment]
Try booting with your SD card out, and then reinserting it after booting
Power off your device
Remove your SD card from your device
Power on your device
When the home menu appears, reinsert your SD card into your device
If this worked, you should clear Home Menu’s extdata by navigating to the following folder on your SD card: /Nintendo 3DS/(32 Character ID)/(32 Character ID)/extdata/00000000/
EUR Region: Delete 00000098
JPN Region: Delete 00000082
USA Region: Delete 0000008f
CHN Region: Delete 000000A1
KOR Region: Delete 000000A9
TWN Region: Delete 000000B1
Try booting without any cartridges inserted (including flashcarts)
If you have a hardmod and a NAND backup, flash the backup back to SysNAND
Try booting into recovery mode and updating your system
Power off your device
Hold (L) + (R) + (A) + (Up)
Power on your device
If you enter safe mode, update your device
Your device may be bricked. For support, ask for help at Nintendo Homebrew on Discord

**Comment by ValShaped** [comment]
Also, if you have a DS card with an invalid header or poor contacts, the HOME Menu will sometimes fail to load with no fatal errors reported. Remove the cartridge from the cartridge slot.
