### ISSUE TITLE
Softlock upon starting Rosalina's network features immediately upon boot

### ISSUE THREAD

**Issue by ha1vorsen** [LumaTeam/Luma3DS#743]
**System model:** New Nintendo 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** 11.4.0-37J SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):** boot9strap 1.2

**Luma3DS version:** 8.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (4)

Splash: (Before)

PIN lock: (4)

New 3DS CPU: (Clock)

--

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

--

**Explanation of the issue:**
In short,  opening the Rosalina menu seconds into booting the home menu, then proceeding to open Input Redirection, will cause the console to softlock upon exit, requiring a reboot. Of course, this could always be remedied by just waiting, but it's still an issue you should probably know about. In addition the scope of time the lock will occur after loading the home menu is pretty wide (around 10 seconds).

If there were a way to detect a fresh boot of the home menu, Rosalina menu requests should be ignored for a few seconds. 

The error by Rosalina is 0x09401bfe, a standard timeout error. So, isn't just input redirection, but any network related elements of Rosalina will softlock the console immediately after a fresh boot (like the debugger).

**Steps to reproduce:**

1. Boot up the system and open Rosalina within 10 to 15 seconds of the HOME Menu appearing.

2. Start Input Redirection, and exit

**Comment by ghost** [comment]
Confirmed this is an issue, at least partially. I didn't lock up, but doing this caused most apps/folders and the battery/wifi/etc. bar to never appear. Does not occur with the debugger, interestingly.

**Comment by fox8091** [comment]
Also reproduced (with debugger as well), and when in the state you were in @Hikari-chin, opening and closing Rosalina again softlocked the system as well. Once in this state, any attempts to open InputRedirection result in error code 0xFFFFFFFF, though debugger still returns 0x09401BFE.

**Comment by TuxSH** [comment]
Old issue and I don't know how to fix.

**Comment by O-J1** [comment]
Same issue and I was able to get it to crash, just thought I should upload the dump just in case.

[crash_dump_00000007.zip](https://github.com/AuroraWright/Luma3DS/files/1182901/crash_dump_00000007.zip)
