### ISSUE TITLE
Pokémon moon randomized crashes cfw

### ISSUE THREAD

**Issue by andy5861** [LumaTeam/Luma3DS#746]
Every time I try to launch Pokémon moon randomized CIA file I installed it crashes my cow im running the latest luma and boot 9 strap but it keeps crashing the CIA was made with my Pokémon moon cartridge

**Comment by jupitteer** [comment]
Github is not for technical support. I recommend going to the nintendo homebrew discord.
edit: also, never report an issue on github and say that 'it crashed'. We need detailed crash info.

**Comment by andy5861** [comment]
I could leave the dmp file it leaves on my sd card

**Comment by Slashin-it-up** [comment]
@Andy5861 Show a pic of the 3DS and upload the dump file. Also you should fill out the github issue template

**Comment by andy5861** [comment]
![image](https://user-images.githubusercontent.com/30444474/28598295-b1c00982-7170-11e7-8aea-9f7a8f03a40d.png)

**Comment by andy5861** [comment]
https://www.dropbox.com/sh/ayiyepqrhw478rn/AAAuIEuYUQFQc5fvlrKrAt6Ma?dl=0 my error dumps are in there 
 also trired on my other 3ds does the same thing

**Comment by jupitteer** [comment]
Invalid CIA, possibly?

**Comment by andy5861** [comment]
i made the cia from my cart

**Comment by Slashin-it-up** [comment]
Redump it. The error looks like a corrupted file (.app)

**Comment by andy5861** [comment]
alright could it be pk3ds corrupting it?

**Comment by andy5861** [comment]
i fixed it

**Comment by jupitteer** [comment]
close the issue than
