### ISSUE TITLE
ARM 11 exception error core 1 (SWAP DOODLE BOOT)

### ISSUE THREAD

**Issue by User13181408200115** [LumaTeam/Luma3DS#747]
NEW 3DS
SysNAND 11.5.0-38E
Sighax 1.2
Luma 3ds 8.1 stable release

Default EmuNAND: (-)

Screen brightness: (4)

Splash: (After)

PIN lock: (-)

New 3DS CPU: (-)

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

When I boot up swap doodle I get a ARM 11 exception error
prefetch abort (svcBreak)
Current Process: loader (0000000000000000000)
[crash_dump_00000000.dmp.zip](https://github.com/AuroraWright/Luma3DS/files/1174533/crash_dump_00000000.dmp.zip)

Steps to Reproduce:
I literally just boot it up

**Comment by jupitteer** [comment]
Do you have doodlebomb? If so, it is not compatible with rosalina. Rosalina does not support *hax payloads.

**Comment by fincs** [comment]
Use Rosalina's native 3dsx loading feature instead of trying to launch *hax through an entrypoint.

**Comment by User13181408200115** [comment]
I had Doodle Bomb but i am not using it I just boot up the software and it crashes imidiately

**Comment by User13181408200115** [comment]
I deleted the software and made a data backup, dowloaded it again form the e-shop, and now it works! Sorry to bother you, but thanks for the help annyways
