### ISSUE TITLE
ARM11 exception error on Toki Tori 3D game

### ISSUE THREAD

**Issue by wekii** [LumaTeam/Luma3DS#750]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4 )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X )

Show NAND or user string in System Settings: (X )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When I start Toki Tori 3D (EUR) game I get ARM11 exception error:

![15012783831380](https://user-images.githubusercontent.com/8656086/28737515-1e974720-73ef-11e7-89c2-0e3cc89818a7.jpg)

If I try to run manual I get following screen:

![15012779408580](https://user-images.githubusercontent.com/8656086/28737431-c20bf17c-73ee-11e7-996c-5d69c8e2d0b9.jpg)

**Steps to reproduce:**

1. Install Toki Tori 3D game

2. Run Toki Tori 3D game

**Dump file:**

[crash_dump_00000001.zip](https://github.com/AuroraWright/Luma3DS/files/1184348/crash_dump_00000001.zip)

**Comment by TuxSH** [comment]
The title you installed is corrupt (error code 0xd9004587), not a luma issue.
