### ISSUE TITLE
"generic" error when trying to system update from 11.4.0-37u

### ISSUE THREAD

**Issue by DeityofSwA** [LumaTeam/Luma3DS#751]
Error type: generic

Process ID: 19
Process name: am
Process title ID: 0x0004013000001502

Address: 0x001092d2
Error code: 0xc86044d2

I don't know if you need all of this information, but am I missing a step to updating properly?

**Comment by ghost** [comment]
Can't reproduce. Updated from 11.4 three times, twice on N3DS and once on N2DS.
