### ISSUE TITLE
Swapdoodle doesn't connect to store with l2 cache off while eshop doesnt connect unless l2 cache is on

### ISSUE THREAD

**Issue by MarioMasta64** [LumaTeam/Luma3DS#754]
**System model:**

[New 3DS XL (RED-001)]

**SysNAND version (+emu/redNAND version if applicable):**

[11.5.0-38u SysNand]

**Entrypoint (How/what you're using to boot Luma3DS):**

**Boot9strap: Luma3DS v8.1-3907c469:**

**Luma3DS configuration/options:**

--

Autoboot EmuNAND: (off )

Use EmuNAND FIRM if booting with R: (off )

Enable loading external FIRMs and modules: (off )

Enable game patching: (on )

Show NAND or user string in System Settings: (on )

Show GBA boot screen in patched AGB_FIRM: (off )

Patch ARM9 access: (off )

Set developer UNITINFO: (off )

Disable ARM11 exception handlers: (off)

--

**Steps to reproduce:**

1. turn l2 cache off and try to access store in swapdoodle

2. turn l2 cache on and try to access eshop

**Comment by ghost** [comment]
Can't reproduce.
