### ISSUE TITLE
A facelift for the menus?

### ISSUE THREAD

**Issue by lavendertheghost** [LumaTeam/Luma3DS#757]
Would a facelift ever be possible for the boot menu and Rosalina? I like the CFW but the command line look really is off putting. This could be counted as something of a side goal for a later date.

**Comment by ghost** [comment]
Stuff (aside from bug reports) pertaining to Rosalina goes in #752.

**Comment by ghost** [comment]
Is use of the touch screen even possible considering how early the boot menu is displayed?
