### ISSUE TITLE
Region Patch not working; Causing prefetch abort

### ISSUE THREAD

**Issue by icefire82G** [LumaTeam/Luma3DS#759]
**System model:**

New3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.4.0-37U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.2

**Luma3DS version:**

Luma 8.1-a4629e4

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: (before)

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (*)

Show NAND or user string in System Settings: (*)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When booting a European copy of Miitopia (00040000001b4f00) using Luma Region patching, it causes a prefetch abort, no matter what combination of Region strings I've tried (EUR EN, EUR EN EN 01, EUR EN EN, EUR EN UK, EUR EN GB).

The file is /luma/titles/00040000001b4f00/locale.txt like it's supposed to be, and none of the above strings that I've tested seem to prevent the crash.

**Steps to reproduce:**

1. Create proper directories for region patch (titles directory, then titleid directory)

2. Create locale.txt with only contents being "EUR EN"

3. Launch game

4. Crash

**Dump file:**

[crash_dump_00000041.zip](https://github.com/AuroraWright/Luma3DS/files/1202270/crash_dump_00000041.zip)

**Comment by jupitteer** [comment]
You disabled arm11 exception handlers. That disqualifies you.

**Comment by TuxSH** [comment]
Does it happen w/o region patch?

**Comment by astronautlevel2** [comment]
@jupitteer I don't see where they disabled exception vectors. Also, they explain the exact issue they experience (prefetch abort) which you can only see with the exception vectors...

**Comment by icefire82G** [comment]
@TuxSH Yep, still crashes without the region patch.

Crash dump here: 
[crash_dump_00000045.zip](https://github.com/AuroraWright/Luma3DS/files/1202727/crash_dump_00000045.zip)

**Comment by AuroraWright** [comment]
This is loader crashing and not the game itself... Does it crash with "game patching" disabled? If so, the game is probably corrupted (seed wasn't installed properly or something).

**Comment by icefire82G** [comment]
Yep, it crashed when I turned off game patching.

Reinstalled the game and it worked fine after reenabling game patching and adding the proper patch.

Thanks guys!
