### ISSUE TITLE
Seriously... SSB, MH Series can't RUN! in O3DS after change region from JAP to USA

### ISSUE THREAD

**Issue by stayfr0sty141** [LumaTeam/Luma3DS#76]
Seriously dude... everything is checked.. 
and i follow tutorial as well..
no missing title or anything..
but why ??
can't run those game... ??

**Comment by cheatfreak47** [comment]
This isn't a personal help/troubleshooting forum.

if you believe there is a problem with Luma3DS, provide as much detail as possible about why this is a problem with Luma3DS, and not just a user specific issue.

Going in here saying "Wah it doesn't work" isn't going to accomplish anything.

As for your actual issue, I'd be inclined to say your problem has something to do with your entrypoint and setup, as Luma3DS requires you to use a program that changes it's internal boot path if you're not using the default "arm9loaderhax.bin" payload. But you've given no details about that, so there's no actual help I can provide.

**Comment by RShadowhand** [comment]
Not Luma's fault. Closing.
