### ISSUE TITLE
[Suggestion] Change in New3ds menu in Rosalina

### ISSUE THREAD

**Issue by Darkshadow3582** [LumaTeam/Luma3DS#761]
Could you implement in the menu of new3ds in rosalina that shows the current state of the CPU?
How often is the CPU and what cache level is selected

And the style menu of new3ds in "Overclock" style NTR?

And I'm sorry, my English is bad

**Comment by ghost** [comment]
This has already been asked for, and Rosalina feature requests go in #752.
