### ISSUE TITLE
ARM11/ARM9 Crashes

### ISSUE THREAD

**Issue by AlienatedMerc** [LumaTeam/Luma3DS#767]
[Downloads.zip](https://github.com/AuroraWright/Luma3DS/files/1210328/Downloads.zip

**System model:**

New 3DS

11.5.0-38U

Boot9Strap

8.1.1

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Clock+L2)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

I'm currently receiving ARM9/11 crashes when powering off the system, opening certain apps, and closing them as well.

**Steps to reproduce:**

1. Open App
2. Close It Normally then power off system

1. Open an app and it might just crash (e.g. eu MiiTopia on a usa console, and randomly enough, nintendo ds wifi settings)

1. open -snip-
2. close it with start and enjoy the crash

**Comment by ghost** [comment]
Cannot reproduce. Exact same setup, USA region N3DS (also tested on N2DS) on 11.5.0 and the exact same applications. Are you using NTR? It tends to cause instability like this.
