### ISSUE TITLE
(Future Feature Request) Shuffle Splash Screen Support

### ISSUE THREAD

**Issue by redalpha666** [LumaTeam/Luma3DS#768]
We already have shuffle theme support for the home screen, but would shuffle splash screens be possible? If so, that's awesome and thanks for all your amazing work.

**Comment by astronautlevel2** [comment]
This shouldn't be particularly difficult to do; I don't mind implementing it but it's up to Aurora and Tux if it's merged.

**Comment by redalpha666** [comment]
Awesome,  I hope they do decide to merge it lol.  I think it'd be an awesome feature to have

**Comment by 1mcuadros** [comment]
Please add it x2

**Comment by TuxSH** [comment]
Closing, tracker cleanup

**Comment by kiuhbit** [comment]
I take it there hasn't been any progress on this? I might try implementing it
