### ISSUE TITLE
Crash when launching VoxelMaker

### ISSUE THREAD

**Issue by Committee** [LumaTeam/Luma3DS#770]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.5.0-38U

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9strap

**Luma3DS version:**

8.1.1

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: ( 4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Clock+L2)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: (X)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

3DS crashes when starting the game VoxelMaker

**Steps to reproduce:**

1. Install CIA of Voxelmaker (NA Version)

2. Crash

**Dump file:**

[crash_dump_00000017.zip](https://github.com/AuroraWright/Luma3DS/files/1215157/crash_dump_00000017.zip)

**Comment by TuxSH** [comment]
Error is 0xd9004587.

You have a corrupted game (or missing seed).
