### ISSUE TITLE
Potentially Luma 8.1.1 bug?

### ISSUE THREAD

**Issue by FusselTeddy** [LumaTeam/Luma3DS#784]
Hey :)

I don't know if this is a Luma bug or whatsoever, but I encountered an an error on two of my Luma CFW Old 3DS Systems after updating to version 8.1.1 with lumaupdater (the newer one with disabled hourly versions)

**System model:**
Old 3DS XL (both)

**SysNAND version**
11.5.0.38E (both), no emuNAND or such things

**Entrypoint**
boot9strap 1.2 (both)

**Luma3DS version:**
stable 8.1.1 (both)

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (1)

Splash: (Off)

PIN lock: (Off)

Enable game patching: (X)

Show NAND or user string in System Settings: (X)

(I removed everything that isn't marked)

**Explanation of the issue:**

So I wanted to power on my device but the blue LED turned on shortly and turned off again. I tried to power it on severel times, but no success.
Old 3DS XL 1: 
After I removed the SD and turned the system on without my SD the Luma configuration menu popped up and "Show NAND or user string in System Settings: ( )" wasn't enabled. I enabled it, put in my SD and from there on everything was OK.
Old 3DS XL 2:
After I removed the SD and turned the system on without my SD the Home Menu started and everything was fine. I powered it off, inserted my SD back into the SD slot and rebooted the System without any issues.  
I only encounterd this on 2 of my Old 3DS XL Systems, not on my New 3DS XL System (which has the same firmwre, settings and everything). I updated all Systems with Luma Updater to the same Luma version (stable 8.1.1).

**Steps to reproduce:**

1. Update Old 3DS XL System to Luma 8.1.1 
2. Power the System off (maybe wait about a day or two, that's what happend to me)
3. Power it on, the issue described above happend to me

I got no crash reports whatsoever

Everything is OK now on both Old 3DS XL Systems, but this may help

**Comment by ghost** [comment]
This isn't a Luma issue; that behavior displays when boot.firm doesn't exist or is invalid. Could be a myriad of things, bad download, SD card issues (damage, contact, many things), etc. In the case of the former, it'd be either an issue with your network or an issue with KunoichiZ's Luma Update.
