### ISSUE TITLE
System doesn't shut down after exiting VC GBC game

### ISSUE THREAD

**Issue by BernardoGiordano** [LumaTeam/Luma3DS#79]
After playing a custom GB/GBC game (haven't tried GBA yet), 95% of the times system fails to shut down after going to shut down menu. Screens shuts down but blue led is always on, then i'll have to shut down in a forced way. 
I'm running A9LH on a 2DS, Luma3DS 5.4 running on EmuNAND.

**Comment by TuxSH** [comment]
Could you try with an official GB/GBC game? Most likely the custom GB/GBC is the issue, being incorrectly packed.

**Comment by TuxSH** [comment]
No answer, closing.
