### ISSUE TITLE
"Process patches menu" title appears when saving settings in Misc options

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#791]
So, I went to Misc options, I selected 'Save settings', that title appears. It is supposed to be related to patching SM/FS in process patches menu. "Miscellaneous options menu" title stayed when selecting either the first three misc options.

**Comment by urherenow** [comment]
Verified with nightly build as of around 24 hours ago...
Sorry, I'm out to sea and can't really do a pull request (although if I'm lucky with bandwidth, I suppose I could do it from here via fork). Besides, I don't know if the devs would want uniformity by changing it to "Miscellaneous options menu" or if it should really just say "Saving..."

Anyway, it's a simple fix here: https://github.com/AuroraWright/Luma3DS/blob/6bcb1f8679ad6b3d25df510837c5a60dc4509f7e/sysmodules/rosalina/source/menus/miscellaneous.c#L227

**Comment by ghost** [comment]
Fixed, thanks.
