### ISSUE TITLE
mods not working

### ISSUE THREAD

**Issue by tommaniacal** [LumaTeam/Luma3DS#794]
I have a new 3ds xl with sysnand 11.5, and luma3ds version 8.1. Neither SaltySD or the Luma Folder in my sd card methods have worked so far. I've tried luma/titles/(Pokemon Sun's ID number) and putting the txt files, code.bin, and romfs folder in here, but when I open sun it's instant and the mods don't install. Am I doing this wrong? I have modding enabled in the luma config settings so I don't know what else I could have missed
![screenshot 2](https://user-images.githubusercontent.com/31083594/29390458-2036a032-82b6-11e7-8170-03fa99462449.png)

**Comment by Sonlen1414** [comment]
First off, this isn't a support forum, for future issues, I would advise going to the [Nintendo Homebrew Discord](https://discord.gg/C29hYvh)
Secondly, your TitleID is wrong, it should be "0004000000164800", if you have any further issues, please direct them to the above Discord Server.
