### ISSUE TITLE
Cro edits and code.bin files crash the game

### ISSUE THREAD

**Issue by Amphar0s** [LumaTeam/Luma3DS#796]
Hello, first off I know this isn't a support thread, but I asked this question before on the discord server and did not get a reply.
I edited the code.bin of pokemon sun,  (randomizing the tms) but puting the code.bin in luma/titles/gameid/ causes the game to crash. Puting cro edits does the same thing.  I dumped the files directly from my gamecart,  (I have sun and updated to 1.2) but only romfs changes are working

**Comment by AuroraWright** [comment]
"I dumped the files directly from my gamecart, (I have sun and updated to 1.2)" you need to dump the 1.2 code.bin from the update, not 1.0 from the cart...
