### ISSUE TITLE
micrSD Management Crash when exiting

### ISSUE THREAD

**Issue by pokeimon** [LumaTeam/Luma3DS#797]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.5.0-38u

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

v8.1.1-d5d56e76

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (4 )

Splash: (After )

PIN lock: ( Off)

New 3DS CPU: ( Off)

--

Autoboot EmuNAND: (Off )

Use EmuNAND FIRM if booting with R: (Off  )

Enable loading external FIRMs and modules: (Off  )

Enable game patching: ( Off )

Show NAND or user string in System Settings: (On)

Show GBA boot screen in patched AGB_FIRM: (Off  )

Patch ARM9 access: (Off  )

Set developer UNITINFO: (Off  )

Disable ARM11 exception handlers: (Off  )

--

**Explanation of the issue:**

When leaving the micrSD Management I get an arm11 exception

**Dump file:**

[crash_dump_00000014.zip](https://github.com/AuroraWright/Luma3DS/files/1232909/crash_dump_00000014.zip)

**Comment by urherenow** [comment]
Launching from system settings, or did you install the .cia to launch from the home menu?
