### ISSUE TITLE
emuNAND transfers data from sysNAND during System Transfer instead of data from emuNAND

### ISSUE THREAD

**Issue by PlatinumLucario** [LumaTeam/Luma3DS#799]
**System model:**
White New Nintendo 3DS

**SysNAND version (+emu/redNAND version if applicable):**
SysNAND: 9.2.0-20E
EmuNAND: 11.5.0-38E

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap 1.2

**Luma3DS version:**
8.1.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Attempting to do a System Transfer in EmuNAND from New 3DS to New 3DS will result in the data from the SysNAND being transferred, rather than the data in EmuNAND.

Normally the data from EmuNAND should be transferred while in EmuNAND mode, rather than the data from SysNAND.

However, any Nintendo Network IDs linked to the system (even on the EmuNAND) will still be transferred over though. Additionally, the EmuNAND data will be formatted, rather than the SysNAND data, even though the data was transferred from the SysNAND.

**Steps to reproduce:**

1. Run the system in EmuNAND mode in Luma3DS using a NAND that is not tied to the SysNAND

2. Open System Settings, then attempt to do a System Transfer as usual. (And login to the NNID linked while doing the System Transfer)

3. During the transfer process, the data from the SysNAND will be transferred over, rather than the data from the EmuNAND. The NNID will be transferred to the target system.

4. After the transfer is complete, Error Code 028-3136 will display. It will indicate that there was a problem with the transfer process.

(Note: This System Transfer that caused the issue was done using a source New 3DS with a 64GB microSD card and with Luma3DS CFW and the target New 3DS having a 4GB microSD card and no CFW or mods)

**Dump file:**
No crash dump is generated from this issue.

**Comment by Masamune3210** [comment]
As long as it takes to launch into the System Transfer app from the Settings app, I wouldn't be surprised if the 3DS was soft-rebooting in the process, sort of how the O3DS does for memmode changes required for games like Smash. If i'm not mistaken, doesn't rebooting mess with EmuNAND in some way, its been a while since I ran one and do not remember
