### ISSUE TITLE
Newest Ctrulib breaks Luma3DS

### ISSUE THREAD

**Issue by astronautlevel2** [LumaTeam/Luma3DS#80]
This pull request has broken compiling Luma3DS: https://github.com/smealum/ctrulib/pull/282

Error: http://hastebin.com/kofalaqofa.lua

It seems like an update to the FSLDR_OpenFileDirectly function is required. Specifically, see: https://github.com/smealum/ctrulib/blob/cf91be5041cc7f9f816021d5ca5af5b7338fd89a/libctru/source/services/fs.c#L186-210

I'll take a look at this later today assuming no one else does.

**Comment by AuroraWright** [comment]
Fixed with the latest commits
