### ISSUE TITLE
[SUGGESTION] Launch a title on boot

### ISSUE THREAD

**Issue by manu-03** [LumaTeam/Luma3DS#801]
It would be great to be able to boot directly to a certain title such as a NTR flashcard or the Homebrew Launcher. This, in addition to some other new features, would allow the development of custom *Home Menus* which did things like
* Avoid the banwave by setting the current title to something present in a vanilla 3DS. (Activity log would still be useful since there can be a non-official one in such launcher)
* Show installed titles (`CTR`, `NTR`, `TWL` or `AGB`) `.cia`, homebrew `.3dsx` and shortcuts to NDS ROMs installed on flashcards `.nds` in the same menu
* Allow custom icon/name/top screen per item
* Better folder management

Of course, aside from the pain produced by developing such a complicated menu, it would involve many Luma improvements such as
* This suggestion
* Giving that menu a way to boot a title spoofing it with another in the friends list
* Being able to boot said menu after a MCU reboot

The idea I had about how to set the title you want to use for this was from the Rosalina Menu, in a similar way to how we can currently switch the current homebrew app. I would not count it as a suggestion for Rosalina, though. Hence why I didn't post it inside #752.

**Comment by ghost** [comment]
Duplicate, closed.
