### ISSUE TITLE
3ds_injector issues - updates on HOME menu

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#81]
Due to the 3ds_injector code used, the "Complete Download Now" option causes a check and the 3DS thinks it needs to be updated. This is moreso a bug with 3ds_injector itself.

**Comment by TuxSH** [comment]
I've already tried many things to no avail :/

https://github.com/yifanlu/3ds_injector/issues/5

**Comment by ghost** [comment]
What's used in 3ds_injector on Luma?

**Comment by AuroraWright** [comment]
The patch has been limited to the not updated NAND, not much more I can do about it
