### ISSUE TITLE
Out-of-region doesn't work with Pokemon Shuffle

### ISSUE THREAD

**Issue by Clement95** [LumaTeam/Luma3DS#811]
**System model:**

[New 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.5.0-38E SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap/Sighax 1.2]

**Luma3DS version:**

[Luma3DS 8.1,1 stable]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (1)

Splash: (Before)

PIN lock: (Off)

New 3DS CPU: (Clock+L2)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: (x)

--

**Explanation of the issue:**

I'm trying to launch Pokemon Shuffle in japanese language, I used Luma Locale Switcher to set region and language of the game to japanese, but when I launch Pokemon Shuffle, it still stays on the language of my System Settings (french)

**Steps to reproduce:**

1. Enable game patching in Luma config

2. Set Pokemon Shuffle to japanese region with Luma Locale Switcher

3. Launch Pokemon Shuffle

**Dump file:**

**Comment by ghost** [comment]
You have disabled your ARM11 Exception Handlers, please read the config option description. Your right to submit issues is forfeit.

**Comment by Clement95** [comment]
I didn't disabled it, sorry I was wrong when I wrote this issue, but nothing errors is appeared

**Comment by urherenow** [comment]
tried to comment earlier, but couldn't. If your game doesn't have Japanese built-in already, the region patch will do nothing for you. It doesn't magically add a new language to your game. It's meant for you to download the Japanese version then apply the settings to it.

**Comment by Clement95** [comment]
It works now, I just changed the destination to luma/titles/folder
title id/locale.txt
