### ISSUE TITLE
"An Exception Occurred" error when loading RetroArch for 3DS 

### ISSUE THREAD

**Issue by ZeroNinx** [LumaTeam/Luma3DS#814]
System model: New3ds

SysNAND version: 11.5.0-38J

Entrypoint: Boot9Strap/Sighax

Luma3DS version: 8.1.1

Luma3DS configuration/options:

Default EmuNAND: ( 1 )

Screen brightness: ( 3 )

Splash: ( Before )

PIN lock: ( off )

New 3DS CPU: ( Clock+L2 )

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( X )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

Explanation of the issue:

    When I used RetroArch_FBA2012 to load a large rom (such as kof2002.zip , svc.zip and so on , larger than about 50MB), it crashed. When I tried to load a small file , it worked properly. Someone told me that it always works properly in A9LH.

Steps to reproduce:

1.load the RetroArch_FBA2012

2.use "Load Connect" to load a large rom

[crash_dump_00000073.zip](https://github.com/AuroraWright/Luma3DS/files/1244310/crash_dump_00000073.zip)

**Comment by ghost** [comment]
This is a known issue with RetroArch, not a Luma issue.
