### ISSUE TITLE
An exceptation occured error ARM9 while booting on O3ds (prefetch abort) (svcBreak)

### ISSUE THREAD

**Issue by PaperApple** [LumaTeam/Luma3DS#816]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.2.0.35U]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap/Sighax]

**Luma3DS version:**

[ 8.1.1 stable]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (off)

PIN lock: (off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
This 3ds was bricked not to long ago and I unbricked it with NTRboot Hax. I followed all the steps properly, but everytime I reboot it goes to a screen with a bunch of codes I wana know if there is anyway to fix this issue. If so please tell me I been trying for hours and found no solution. 

**Steps to reproduce:**

1.System Boot

2.An expectation occurred error Arm9

**Dump file:**

![1503531911986](https://user-images.githubusercontent.com/25622546/29647853-1f0c99b6-8840-11e7-97cb-5e4323741cc9.jpg)

[dumps.zip](https://github.com/AuroraWright/Luma3DS/files/1247630/dumps.zip)

**Comment by ghost** [comment]
Not a Luma issue; likely something wrong with your "unbricked" NAND.

**Comment by PaperApple** [comment]
Is there a fix?

**Comment by Derek1199** [comment]
Try doing a CTRNAND transfer of a clean Nand image. That should fix it.

**Comment by PaperApple** [comment]
How do I do that?

**Comment by Slashin-it-up** [comment]
Not a support form. Look at 3DS.guide/9.2.0-ctrtransfer
