### ISSUE TITLE
Luma config menu doesnt show when booting 3DS and holding the select button

### ISSUE THREAD

**Issue by chuchucha** [LumaTeam/Luma3DS#817]
**System model:**
New 3DS
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.4.0-37U SysNAND, 11.4.0-37J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
version 8.1
[e.g. 8.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--
Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (X )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
When booting up (turning on) my 3DS, it takes longer time, and when I am holding the SELECT button, config menu doesnt show. Also, I experienced several freezes when starting a game after I ran NTRCFW plugin, usually, the screen stuck on 3DS logo when starting a game. I am sorry if this is not the place to post this kind of thread, I dont know where should I post besides here. Also, please be patience with me, because I am totally new to this 3ds hack.

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by ghost** [comment]
Can't reproduce. Also, use 8.1.1, 8.1 is outdated now. The latter thing is an NTR issue, not a problem with Luma.
