### ISSUE TITLE
[Request] Rosalina Menu - IP Address

### ISSUE THREAD

**Issue by CodyZeppelinR** [LumaTeam/Luma3DS#823]
It would be helpful to know the current IP address on the connected network without needing to switch applications, if at all possible. Perhaps just an additional line of text in the Rosalina Menu?

**Comment by jupitteer** [comment]
It already shows that when you activate input redirection.

**Comment by fox8091** [comment]
First, it already does this, look in the bottom right. Second, things like this belong in issue #752.
