### ISSUE TITLE
An exception has occurred ARM11 (core 0)

### ISSUE THREAD

**Issue by foontitz** [LumaTeam/Luma3DS#825]
**System model:**
New 3ds

**SysNAND version (+emu/redNAND version if applicable):**
 11.5.0-38U SysNAND, 11.5.0-38U EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

Luma 3ds 8.1.1

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: (3 )

Splash: (off )

PIN lock: ( off)

New 3DS CPU: (Clock+L2 )

--

Autoboot EmuNAND: (x)

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Whenever I enter system settings and go to 3ds game management I get " An exception has occured ARM11 (core 0) prefetch abort (svcBreak)" and yes I have tried reinstalling luma and disabling Arm11 exception handlers ( as so guides said to do), and all the latter does is cause the 3ds to crash without a dump or error screen. The error does not occur when in SysNAND.

**Steps to reproduce:**

1.enter system settings while in EmuNAND

2.enter 3ds title management

**Dump file:**

[crash_dump_00000016.zip](https://github.com/AuroraWright/Luma3DS/files/1254151/crash_dump_00000016.zip)

**Comment by mzino** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-get-a-black-screen-on-boot

"If you see a "svcBreak" in the "loader" process, go ahead with the steps", so it should help you.
