### ISSUE TITLE
RomFS patching via "romfs" file

### ISSUE THREAD

**Issue by mariomadproductions** [LumaTeam/Luma3DS#827]
**Suggestion**
Add RomFS patching via "romfs" file like in old versions and HANS.

**Reason**
Because the game loads faster when using RomFS patching via "romfs" file compared to RomFS patching via "romfs" folder.

**Comment by ghost** [comment]
That's...not true and is based upon a misunderstanding of how LayeredFS works. Rejected.

**Comment by mariomadproductions** [comment]
That's what you get for believing things you read in the internet.

**Comment by mariomadproductions** [comment]
Are you saying the "folder" speed is the same/faster? Or that the feature is still present?
It certainly _was_ slower on _some_ games.

**Comment by mariomadproductions** [comment]
https://www.reddit.com/r/3dshacks/comments/8tfuvr/romfs_files_and_lumas_game_patching/
