### ISSUE TITLE
Bug Pokemon Lune for old 3ds

### ISSUE THREAD

**Issue by polopoi** [LumaTeam/Luma3DS#828]
I play Pokemon Moon and it bug in the volcanic park when I try to face other similar trainers for the test of Kiwae here is the message that I receive:

An error occurred (ErrDisp)

Error type: generic
Process ID: 38
Process name: niji_loo
Process title ID: 0x0004000000175e00

Adress: 0x002b37401
Error code: 0xo96045b 

Press any button to reboot

help me 
i use sysnand no emunad my system is 11.5.0-38E ,my luma 3ds 8.1,FBI is 2.4.11

**Comment by AuroraWright** [comment]
The error code is missing two digits, please fix it

**Comment by polopoi** [comment]
Repair an Error Code? How do we do ? I'm new to the crack of the 3ds
It would be good if you showed me the trick how to repair this erratic ca will be able to serve me for the other games that I have on my console.
What more do you mean by the error code missing two digits? I would like to have more details on this error.

Thanks you for your comprehension

**Comment by Committee** [comment]
What she means is the error code that you gave is missing two characters:

Error code: 0xo96045b??

What are the missing characters?

**Comment by polopoi** [comment]
ok i see , this is the true error code : 0xo960454b

**Comment by Committee** [comment]
You posted the same thing.

**Comment by Slashin-it-up** [comment]
This could be an issue with many things. However you error code you keep telling us is missing a digit

**Comment by polopoi** [comment]
look the picture 

-
![wp_20170829_03_34_46_pro](https://user-images.githubusercontent.com/31406482/29803577-69fa71ac-8c6c-11e7-8b71-f590edc3de7c.jpg)

**Comment by fincs** [comment]
Turns out it was a "C", not an "O".
```
<fincs> !err 0xc960454b
<plutobot> Module: FS (17) | Description: 331 | Summary: Internal (11) | Level: Status (25)
```

**Comment by polopoi** [comment]
that's it sorry for the bad writing error , i need a solution for resolve this error

**Comment by ghost** [comment]
Can't reproduce this; this is probably save, game, or update data corruption.

**Comment by polopoi** [comment]
how to repair this error ?

**Comment by polopoi** [comment]
how to repair this error ?

**Comment by james-d-elliott** [comment]
You can get support for issues not related to Luma on the discord server.  https://discord.gg/C29hYvh

**Comment by polopoi** [comment]
In which part of the site I have to go to see how to solve this problem that prevents me in my adventure in pokemon moon, I invite you to see a little higher I posted the image of the error
