### ISSUE TITLE
Why not load FIRM directly in place?

### ISSUE THREAD

**Issue by yifanlu** [LumaTeam/Luma3DS#83]
Just wondering if there's a reason why FIRM has to be loaded first into FCRAM and then memcpy'd into the right location. I modified it to load the FIRM header and lseek to the right place and load the section directly in place. Then the patches are also done in place and arm9 is decrypted in place too. So am I missing something here/will something break? Since it seems like every CFW loads to FCRAM, does patches there, and finally memcpy to the right location. 

Here's how I did it: https://github.com/yifanlu/Cosmo3DS/commit/a04a80342b25bff250576186a4d7a4af361c5f77

Also for people with updated sysNAND, is it possible to, instead of FIRM blocking, update FIRM1 instead? That way you can just load from FIRM1 and not have to do a directory read each time.

**Comment by TuxSH** [comment]
Loading FIRM sections in place would be a little be bothersome because we need to decrypt them. Furthermore, copying section0 takes only 11ms and 0.5ms for the others.

Moreover writing to FIRM1 is dangerous since it needs to decrypt into specific garbage.
