### ISSUE TITLE
Applications that uses Internet just Freezes and Give an ErrDisp

### ISSUE THREAD

**Issue by pedrohos** [LumaTeam/Luma3DS#830]
**System model:**

[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.4.0-37U SysNAND, 11.4.0-37J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**

[e.g. 8.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When I download on any app (Ex: System Update, Eshop, Freshop etc.) the app just freezes.
And then if I hold power Button it will turn off and when I power on it still stays with the same problem.
But if I turn off the Wireless switch it gives an error - ErrDisp [0xF9606C05].

Copied from error Description (from Kurisu bot (at Nintendo Homebrew Discord Group):
[0xF9606C05]
-Module
    NWM (27)
-Description
    Invalid string length. This error is returned when service name length is greater than 8 or zero. (srv) (5)
-Summary
    Internal (11)
-Level
    Fatal (31)

Obs.: I'm using luma 8.1.1 (latest version) and b9s 1.2, currently at 11.5.0 sysNAND. I tried to find some answers but I didn't find any. I don't remember when this started to happen (I stoped using it for a long time ago).
**Steps to reproduce:**

1. Open eshop and download something.

2. In the middle of the process it (should) freeze.

3. Optional: Turn off wifi switch, then it gives the [0xF9606C05] error.

**Dump file:**

**Comment by ghost** [comment]
Can't reproduce. This sounds like hardware damage.
