### ISSUE TITLE
[Feature Request] Custom LED colors

### ISSUE THREAD

**Issue by BlazeUchiha420** [LumaTeam/Luma3DS#832]
Is it possible to have an option in Rosalina to customize the color of your LED lights on your console similar to what is shown in this video here: https://www.youtube.com/watch?v=i9ILMxlcUik without the possibility of an unrecoverable MCU brick? If so, then it would be awesome to have an option for every LED on the console. This would allow for more customization for the end user's preference(even the potential to have have them continuously change like in the video.

**Comment by Derek1199** [comment]
#752 go here.

**Comment by BlazeUchiha420** [comment]
sorry for posting in the wrong area. Thanks for rectifying this for me!

**Comment by BlazeUchiha420** [comment]
Not to sound entitled or anything, may I ask why this is invalid and closed? Is it not possible?

**Comment by ihaveamac** [comment]
it's closed since these kinds of things go to the feature-request issue.

**Comment by BlazeUchiha420** [comment]
So would it be ok if I re-posted it there or would it just get closed again? Afaik it was moved there.

**Comment by ghost** [comment]
It would just be deleted for being a duplicate; this feature was already requested.

**Comment by BlazeUchiha420** [comment]
alright thank you
