### ISSUE TITLE
[request]Add load romfs.bin from TF card

### ISSUE THREAD

**Issue by FlameBeam** [LumaTeam/Luma3DS#836]
As we all know, LayeredFS need to judge if files in romfs is in folder. It has too many I/O so that some game will be very slow (such as kriby, if I use a LayeredFS patch, it will load about 5 minutes before I enter the game.)
Another hand, HBL can't use HANS by smea now.
So can Luma add a function to load romfs.bin?

BTW, I hope we can load exefsheader.bin, because if we change the code.bin, we also need to change the exefsheader.bin. My friend told me that some of the code are in the exefsheader.bin.

**Comment by ghost** [comment]
The files must be mounted and expanded regardless of whether romfs is a single file or not... 

Additionally, this is a duplicate.
