### ISSUE TITLE
feature request: title region emulation automatically based on title serial

### ISSUE THREAD

**Issue by Jimmy-Z** [LumaTeam/Luma3DS#838]
I requested this in an "all feature requests goes here" thingy, ~but I can't find it now, so posting it again.~ found it: https://github.com/AuroraWright/Luma3DS/issues/619#issuecomment-308950488 and I suppose the new "compilation" issue doesn't include non-rosalina feature requests.

Currently users need to create a text config file to engage title region emulation, but since region of commercial games can be determined based on the last letter of the serial, we can set title region emulation to that if it doesn't match system region, eliminating the requirements of such text config files.

**Comment by ghost** [comment]
#619 was also only for Rosalina feature requests, as the title said. Unfortunately, this feature, while possible, will not be implemented, for the following reasons: 

* The SMDH region is not easily accessible by something like Loader; to check it every launch would incur a performance penalty.
* The standard is not necessarily followed by unofficial applications. 
* General buggy behavior this could cause.

The best option is to have a homebrew program to write the folders and .txts for you automatically, and this already exists: [LumaLocaleSwitcher](https://github.com/Possum/LumaLocaleSwitcher/releases).

**Comment by Jimmy-Z** [comment]
performance penalty like several milliseconds?

give me one example of unofficial application that will fail with title region emulation on.

how exactly?

that locale switcher is a joke.

**Comment by piratesephiroth** [comment]
well it could skip the check for system titles. I don't really see a strong impact in performance if you do that
