### ISSUE TITLE
Cannot load arm9loaderhax after reboot

### ISSUE THREAD

**Issue by jcashma2** [LumaTeam/Luma3DS#84]
Hello and thank you for your help.

I am unable to boot into arm9loaderhax after reboot.  I have followed all directions and encountered no issues from this guide.

https://github.com/Plailect/Guide/wiki/Part-5-(arm9loaderhax)

I am on Section IV of Part 5. Telling you this for context.  I hold start while powering on but boot to the home menu rather than arm9loaderhax.  Thank you again, happy to supply any other details you need.

**Comment by RShadowhand** [comment]
arm9loaderhax loads Luma and that loads home menu.
Holding start should run another payload. Read the wiki.
Closing as this isn't an issue, but feel free to comment again.
