### ISSUE TITLE
i can not access the homebrew after i installed luma 8.1.1

### ISSUE THREAD

**Issue by biggiedaman** [LumaTeam/Luma3DS#840]
**System model:**
New 3DS
[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**
11.2.0-35U
[e.g. 11.4.0-37U SysNAND, 11.4.0-37J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9strap
[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**
8.1
[e.g. 8.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: ( 4)

Splash: (off )

PIN lock: (off )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

i just installed luma v8.1.1 and i tryed to go back to the homebrew channel and all i get is a error message . 
![20170903_230335](https://user-images.githubusercontent.com/31605334/30010409-8ea86dfc-90fd-11e7-867d-5c8bba1f4533.jpg)
![20170903_230335](https://user-images.githubusercontent.com/31605334/30010421-9bc1d85c-90fd-11e7-9ba2-7d88252ea6dc.jpg)

**Steps to reproduce:**

1.I  power on the 3ds  and i go to nintendo 3ds sound and click on it and go to sd card and then i click on the ned file and get this error message.

2.

**Dump file:**

**Comment by biggiedaman** [comment]
[crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1273542/crash_dump_00000000.zip)

**Comment by Shadow322** [comment]
Should fill out the spreadsheet properly if u want any help

**Comment by biggiedaman** [comment]
i am trying. i am new at this. i will post a pic of what i get when i try to load homebrew from soundhax

**Comment by 46620** [comment]
Luma breaks some homebrew entry points. That might be the issue.

**Comment by biggiedaman** [comment]
i solved it thank you for your time and help every one. i just had to inject the fbi into the health and safety by using godmode9.

**Comment by fincs** [comment]
*hax 2.x is not supported by Luma due to differences in RAM offsets. Please note that Luma has a built-in way to run 3dsx homebrew applications.

**Comment by Jenarou** [comment]
can you please explain how did you fix it?
I am having the same issue and I have no idea how to fix it using godmode9, I have godmode9 installed already.

**Comment by biggiedaman** [comment]
Just google godemode9 usage
