### ISSUE TITLE
-: either crash->Home Menu or Error Screen (see image below)

### ISSUE THREAD

**Issue by c12345678901** [LumaTeam/Luma3DS#842]
[New 3DS (XL)]

**SysNAND version (+emu/redNAND version if applicable):**

[11.4.0-37E SysNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap/Sighax.]

**Luma3DS version:**

[8.1.1 Luma]

**Luma3DS configuration/options:**

Default EmuNAND: 1(x)

Screen brightness: 3(x)

Splash: Off(x)

PIN lock: Off(x)

New 3DS CPU: Clock(x)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Hey there, about two weeks ago I wanted to open - and it either crashed right away or it loaded a few things and then it showed me an error screen "An exception occurred"
I also tried to reinstall the app or deleting the - folder but that was useless.

 

**Steps to reproduce:**

1. opening -
[crash_dump_00000010.zip](https://github.com/AuroraWright/Luma3DS/files/1282040/crash_dump_00000010.zip)

2.

**Dump file:**

**Comment by c12345678901** [comment]
[11.5.0-38E SysNAND]* sorry

**Comment by AuroraWright** [comment]
1) not Luma's issue
2) we don't support piracy

**Comment by pbanj** [comment]
simple fix....... buy your games
