### ISSUE TITLE
{Feature Request} Screenshot placement

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#843]
When Luma is in ctrNAND taking screenshots with Rosalina it places all screenshots in "RW/Luma/Screenshots" have it save screenshots in "SD:/Luma/Screenshots"

**Comment by Derek1199** [comment]
It's supposed to save them in Sysnand CTRNAND/rw/luma/screenshots when you are booting without an SD card. This isn't a luma issue at all. It can't save to an SD card when no SD is present. If booting with an SD card it will save To SD/luma/screenshots

**Comment by Shadow322** [comment]
Well your wrong as the SD card is present and still saves to "CTRNAND/rw/luma/screenshots" so it is a luma issue

**Comment by jupitteer** [comment]
@Shadow322 Just put boot.firm on your sd card.

**Comment by Shadow322** [comment]
@jupitteer just put your brain in a jar of fermadahide as its doing u no good
