### ISSUE TITLE
An exception occurred

### ISSUE THREAD

**Issue by SF1997** [LumaTeam/Luma3DS#846]
**System model:**

Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.5.0-38E SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

8.1.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: (x)

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Every time I try to launch Monster hunter Stories Eur, a crash error appeared, even I installed another cia. 

**Steps to reproduce:**

1. Launching Monster Hunter Stories 

2. Crashed error show up

**Dump file:**

[crash_dump_00000031.zip](https://github.com/AuroraWright/Luma3DS/files/1293363/crash_dump_00000031.zip)
![dsc_0441](https://user-images.githubusercontent.com/21049124/30287238-4596cc74-971c-11e7-9508-816423a68a8b.JPG)

**Comment by ghost** [comment]
Can't reproduce, likely you failed to use region emulation.
