### ISSUE TITLE
Payloads not loading

### ISSUE THREAD

**Issue by anypirate** [LumaTeam/Luma3DS#85]
I am following the Plailect guide to install A9LH and at section 5 step 5, the payload for Emunand9 doesn't not load when i held Y on boot. Payloads dont work for start_decrypt9 too.

The 3ds directly boots to the RedNAND home screen interface.

Please advise

Thank you

**Comment by urherenow** [comment]
You need to hold the button BEFORE turning on your console, and keep holding it until it loads what you want. Github is to present bugs and fixes, not to be a support forum. Ask for help on gbatemp. I can assure you that payloads are working just fine when named correctly and in the correct directory, with the correct button being pushed. There is no bug here.
