### ISSUE TITLE
Feature request: On the fly file format conversion for screenshots

### ISSUE THREAD

**Issue by Osha31** [LumaTeam/Luma3DS#853]
Rosalina allows us to take screenshots in-game, which is fine, although still a bit slow, but eh, I'll live with that. What would be nice is if it could actually convert the screenshots from bmp to png automatically, allowing us to skip having to convert them to png, since most image hosts (yes I know about Imgur, I do not like it) don't support that file format. And maybe even having Rosalina save the screenshots in the DCIM folder directly, so we could upload the screenshots directly from the internet browser ?

**Comment by ghost** [comment]
Rosalina feature requests go in #752, but this particular request is a duplicate and has already been rejected.
