### ISSUE TITLE
Wrong color format in VC screenshot

### ISSUE THREAD

**Issue by Flaviculpus** [LumaTeam/Luma3DS#854]
**System model:**
Old 3DS

**SysNAND version (+emu/redNAND version if applicable):**
11.5.0 SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap 1.2

**Luma3DS version:**
8.1.1 stable 

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (2)

Splash: (on)

PIN lock: (off)

New 3DS CPU: (off)

--

Autoboot EmuNAND: (off)

Use EmuNAND FIRM if booting with R: (off)

Enable loading external FIRMs and modules: (off)

Enable game patching: (on)

Show NAND or user string in System Settings: (on)

Show GBA boot screen in patched AGB_FIRM: (on)

Patch ARM9 access: (off)

Set developer UNITINFO: (off)

Disable ARM11 exception handlers: (off)

--

**Explanation of the issue:**

Taking a screenshot in a VC game result in an incorrect color reproduction.
Color format detection works fine with 3DS games but it seems to be broken when it comes to VC.
See an example here: https://imgur.com/a/Ezeck.

**Steps to reproduce:**

1. Start a VC game.

2. Open the rosalina menu and take a screenshot.

**Dump file:**

**Comment by jupitteer** [comment]
I can't seem to reproduce that, and I take a lot of screenshots.

**Comment by Flaviculpus** [comment]
Added more examples. It looks like ntr doesn't have this issue. Also, why does it take so much time to take a screenshot using rosalina? Looking at how ntr does screenshots, it should be slower considering it works on a higher lever and uses nested loops, shoudn't it? 

Edit: no idea if it's actually why, but the issue might come from the fact GBC and NES use 15-bit RGB instead of truecolor like the 3DS does...

**Comment by profi200** [comment]
Can reproduce this with the only GBC VC i have.
![alt text](https://dl.dropboxusercontent.com/s/fiqwfw5gedxyigo/top_0001.png)

**Comment by AuroraWright** [comment]
Fixed on https://github.com/AuroraWright/Luma3DS/commit/a39adc8ac13480077bb4d190e3325aefdb5f1204
