### ISSUE TITLE
[REQUEST] Rosalina menu on Top/Botton screen

### ISSUE THREAD

**Issue by MaiconErick** [LumaTeam/Luma3DS#858]
So, Rosalina is really handy when you want to freeze the screen.
Unfortunately, Rosalina menu is displayed only on bottom screen.
By making an option to change the screen in which Rosalina will be displayed would be a nice feature.

I believe BootNTR had this feature.
A transparency setting of Rosalina menu would work too.

(My personal reason for this feature is that I study Japanese, and the texts shown on cutscenes are too fast for me to read yet, so I keep taking screenshots with Rosalina, because that is a way to make the bottom screen freeze for a while.) 
[I don't really want to keep doing this because I got an error when taking a lot of screenshots in succession, when I find some kind of pattern I'll post more info here, along with the error code.]

**Comment by ghost** [comment]
Rosalina feature requests go in #752.
