### ISSUE TITLE
Feature Request - Rosalina HB redirection: boot.3dsx alternative location

### ISSUE THREAD

**Issue by annson24** [LumaTeam/Luma3DS#861]
Hey there, may I request to add the ctrnand's root as alternative location for rosalina's redirection of the boot.3dsx? So that we can redirect to the boot.3dsx even without an sd card. Thanks.

**Comment by ihaveamac** [comment]
homebrew is stored on the SD and expects to be on the SD, so this won't work.

**Comment by fincs** [comment]
Also: argv, devoptab & 3dsx-romfs requires it being on SD as well.

**Comment by ghost** [comment]
Wrong place for this anyway.
