### ISSUE TITLE
Arm 11 An exception occurred

### ISSUE THREAD

**Issue by Piruy** [LumaTeam/Luma3DS#862]
**System model:**
New 3DS

**SysNAND version (+emu/redNAND version if applicable):**
11.6.0-39U

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9Strap/Sighax

**Luma3DS version:**
8.1.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

New 3DS CPU: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
When booting up Metroid: Samus Returns, a exception error screen pops up

Game error:
Processor: ARM11 (core 0)
Exception type: data abort
Current process: MATADORA (00040000001BB200)

**Steps to reproduce:**

1. Boot up Metroid

**Dump File:**
[Dump.zip](https://github.com/AuroraWright/Luma3DS/files/1318002/Dump.zip)

**Comment by Sonlen1414** [comment]
Seems to be a common issue with people who pirated the game. Buy it, it is worth the money.

**Comment by hsuanpai** [comment]
Change the Region of Game to USA , Language of Game to EN. And Problem will be solved. Thanks.
