### ISSUE TITLE
[Request] Change screenshot naming scheme order

### ISSUE THREAD

**Issue by alvgalrus** [LumaTeam/Luma3DS#863]
Hi!

Currently the naming scheme of screenshots is `<screen>_<number>.bmp`. This makes the files listed with all bottom images first, then all top/right ones.

I suggest inverting the order to `<number>_<screen>.bmp`, this way the screenshot files will be listed next to each other.

Regards.

**Comment by CodyMKW** [comment]
I think [screenshot merge](https://github.com/ihaveamac/screenshot-merge) would also need to be updated if they did this

**Comment by ghost** [comment]
#752
