### ISSUE TITLE
Exception when launching homebrew launcher 2.0 with RPwnG or Notehax

### ISSUE THREAD

**Issue by garoxas** [LumaTeam/Luma3DS#864]
**System model:**

Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.5.0-38U SysNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap 1.3

**Luma3DS version:**

8.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Running homebrew launcher 2.0 (https://github.com/fincs/new-hbmenu) with RPwnG or Notehax crashes when top screen shows ***hax 2.9 alpha**

Revert to the legacy build (Luma3DS v7.1-fc7d554a) fixes this issue

**Steps to reproduce:**

1. Open RPG Maker FES or Flipnote Studio 3D
2. Run payload
3. Crash

**Dump file:**

[crash_dump.zip](https://github.com/AuroraWright/Luma3DS/files/1320108/crash_dump.zip)

**Comment by Shadow322** [comment]
Close this plez and use Rosalina kthx

**Comment by ihaveamac** [comment]
*hax does not work with luma 8.0+ due to rosalina.
