### ISSUE TITLE
[Request] Soft-Reset in games using Luma3DS Rosalina Menu.

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#865]
So, I know Luma already has the reboot & power off functions in the menu, but some games can't be soft-resetted using normal means, like some Mario & Luigi games, & a bunch of other things.

My question is: is there a way to bake a soft-reset option straight into Luma since some games don't really support it?

**Comment by Margen67** [comment]
https://github.com/AuroraWright/Luma3DS/issues/752
