### ISSUE TITLE
Wierd bug in reigon emulation (Province names should not be latin?)

### ISSUE THREAD

**Issue by trbocode** [LumaTeam/Luma3DS#867]
**System model:**

New 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39U

**Entrypoint (How/what you're using to boot Luma3DS):**

B9S 1.2

**Luma3DS version:**

My own fork with different fonts- DEFENITLY NOT THE CAUSE.

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4?)

Splash: (none )

PIN lock: ( none)

New 3DS CPU: (Yes, L2 and MHZ )

--

Autoboot EmuNAND: ( X)

Use EmuNAND FIRM if booting with R: ( X)

Enable loading external FIRMs and modules: (X )

Enable game patching: (V )

Show NAND or user string in System Settings: (V )

Show GBA boot screen in patched AGB_FIRM: (V )

Patch ARM9 access: ( X)

Set developer UNITINFO: (X )

Disable ARM11 exception handlers: (X )

--

**Explanation of the issue:**

![top_00000002](https://user-images.githubusercontent.com/20900544/30756846-f12c39e6-9fd4-11e7-8745-3d4d3faa477c.png)
![top_0000](https://user-images.githubusercontent.com/20900544/30756847-f14af94e-9fd4-11e7-9432-077b9726645c.png)

The first one is an American 3DS running an American MK7 copy. Reigon emulation is set to Jiangsu, China, and all the matching stuff.
The second one is an iQue running an American MK7 copy.
As you can see, both have bugs, but different kinds of bugs.

**Steps to reproduce:**

1.Set reigon emulation to Jiangsu (and the matching stuff)

2. Go to the MK7 channel

**Comment by AuroraWright** [comment]
Region emulation doesn't change the game's code, so this is not Luma's fault.

**Comment by trbocode** [comment]
But both games are the same... This IS Luma's fault. The only thing different here is that one is running nativly and the other runs via reigon emulation

**Comment by ValShaped** [comment]
The iQue 3DS doesn't have the english language fonts. It's not a surprise things are broken; Luma doesn't try to fix font issues.

**Comment by trbocode** [comment]
The font is clearly provided by the game.
The location on the american 3DS (First one) is wrong. That's the problem.
THINGS should look like the second picture, but they don't. Only the fisrt pic uses reigon emulation
