### ISSUE TITLE
Homebrew Crash Error

### ISSUE THREAD

**Issue by Sil3ntfury** [LumaTeam/Luma3DS#873]
**System model:**

[New 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.6.0-39J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[8.1.1]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: (Clock+L2)

--

Autoboot EmuNAND: (X)

Use EmuNAND FIRM if booting with R: (X)

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
So when ever I try to load up homebrew this error keeps poping up.

![image](https://user-images.githubusercontent.com/32247742/30786494-6302eaf4-a112-11e7-84fe-f8f6b9106855.jpg)

**Steps to reproduce:**

1. ?

2. ?

**Dump file:**
(https://github.com/AuroraWright/Luma3DS/files/1327709/crash_dump_00000003.zip)

**Comment by fincs** [comment]
Are you actually using Rosalina's 3dsx loading stuff? Keep in mind that hax 2.x is not supported.

**Comment by Sil3ntfury** [comment]
Not sure. I did everything on the guide and then once it re-boots and I try to go to homebrew it does this.

**Comment by fincs** [comment]
How are you actually launching a 3dsx?

**Comment by Sil3ntfury** [comment]
Soundhax

**Comment by Shadow322** [comment]
Use Rosalina to boot homebrew

**Comment by fincs** [comment]
As I suspected.
