### ISSUE TITLE
multiple photos in one shot in Rosalina

### ISSUE THREAD

**Issue by acelerador25** [LumaTeam/Luma3DS#874]
I have seen in the menu after making the shot that you see several photos of the same section of the photo: several of the upper and lower. Can the number of them be reduced?

**Comment by ghost** [comment]
If I'm understanding this correctly, are you saying that taking a single screenshot is making multiple duplicate files? If so, cannot reproduce.

**Comment by acelerador25** [comment]
Is correct. In this case I see in the screenshot folder: **Top-right** and **Top** for the same image, but, after I delete the folder and put the last verson of lumad (63fc2b) the problem don't occur in the new folder
