### ISSUE TITLE
Boot splash disappears during bootup

### ISSUE THREAD

**Issue by pcs3rd** [LumaTeam/Luma3DS#875]
during bootup, the splash screens disappear while loading the home-menu, making it feel quite lonely
during boot up:{ especially on a 128gb card

**Comment by ValShaped** [comment]
This is normal; the splash screen delays startup for a few seconds to be shown, and then the screen is deinitialized so the 3DS's operating system can take over.

**Comment by ghost** [comment]
This is intended behavior.
