### ISSUE TITLE
Smash 3DS

### ISSUE THREAD

**Issue by EnderWeeb132** [LumaTeam/Luma3DS#879]
It involves Luma so thats why I'm posting here. So, I got CFW, yatta yatta, and got Smash 3ds mods. It was rolling well, I was getting new mods every now and then, but eventually something happened. After a Luma update, only certain types of Mods started to work. Once I updated to Luma v7 however, the mods would crash the game. ANY type of mod. I think Luma 7 has something to do with it since it stopped AFTER the update.

**Comment by dogtopus** [comment]
Luma v7 is an ancient version. Please update to v8 and see if the problem still persists.

**Comment by pbanj** [comment]
reading the wiki also helps
