### ISSUE TITLE
Efecto congelado al actualizar un juego

### ISSUE THREAD

**Issue by GabrielCatDev** [LumaTeam/Luma3DS#883]
[spanish]
Cuando actualizo un juego parece que se queda congelado y no me gusta...además si no hay espacio disponible para la actualización lo intenta igualmente...creo que no cuesta nada mirar cuanto ocupa y mirar si cabe...me gustaría que hubiera una forma de ver el estado actual de la actualización así puedo estar tranquilo.

**Comment by Shadow322** [comment]
ENGLISH PLEASE

**Comment by GabrielCatDev** [comment]
When update some game, cant see any progress and feels like frozen the system,please can add any progress bar or something...

Other problem when update without MB available...dosent stop just try a until update...becouse never will can finish...


Sorry my bad English...
