### ISSUE TITLE
Update game, efect Froze

### ISSUE THREAD

**Issue by GabrielCatDev** [LumaTeam/Luma3DS#884]
When update some game, cant see any progress and feels like frozen the system,please can add any progress bar or something...

Other problem when update without MB available...dosent stop just try a until update...becouse never will can finish...

Sorry my bad English...

**Comment by Tyulis** [comment]
Where do you update games?

**Comment by GabrielCatDev** [comment]
When i want to play, the system say update...(clic into icon game)

**Comment by ghost** [comment]
This isn't a Luma problem, and this is infeasible to "add" to Nintendo's software.

**Comment by GabrielCatDev** [comment]
It's doesnt true because when i update this program call freeshop...i know this because I power off while updating and free ship say me this incident while updating...

**Comment by AuroraWright** [comment]
We don't support piracy, and a freeze in a program is not Luma's fault (in this case it's most likely a GPU freeze if you don't see exceptions).

**Comment by tetradog** [comment]
Not freeze literally is an effect when update some game...
