### ISSUE TITLE
arm11 core0 iron15 error

### ISSUE THREAD

**Issue by ishtiaq1234** [LumaTeam/Luma3DS#886]
**System model:**

N3DS

11.6.0-39E sysnand

B9S

**Luma3DS version:**

8.1.1 stable

**Luma3DS configuration/options:**

Default EmuNAND: 1(x)

Screen brightness:4(x)

Splash: Before( x)

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

used FEFEditor to edit some files in the games rom, put it in the correct directories its ment to be in to run but when i get to the first chapter the game always crashes at the exact point each time (see image below)

![b1bf86a4-a62b-47ab-877b-163560b3406c](https://user-images.githubusercontent.com/29050335/31293697-ff82b654-aacf-11e7-9eae-7e9e665957c5.jpeg)

**Comment by ValShaped** [comment]
It sounds like something went wrong with the files you've edited (And not something wrong with Luma3DS)

**Comment by ishtiaq1234** [comment]
oh alright ill re edit my files see it that helps

**Comment by piratesephiroth** [comment]
maybe you should try it on Citra first (if it can run that game)

**Comment by ghost** [comment]
>used FEFEditor to edit some files in the games rom

Definitely not a Luma issue.
