### ISSUE TITLE
Luma 3DS 8.1.1 crash at loading

### ISSUE THREAD

**Issue by fraf** [LumaTeam/Luma3DS#888]
I explain the process I did before show you the crash that permanently occurs now.

I had an old version of luma 3ds (arm9 bin loader + menu hax).
I have sysnand 9.2 (downgrade)
I had emunand 11.5 (OK)

All was working and decided to install bootstrap9 now following YouTube tutorial : https://www.youtube.com/watch?v=Hgg2kuibs7g

So I formatted my SDCARD content *EXCEPT* "Nintendo 3DS" folder.
Then I took files from the link in the tutorial (which was updated because the options selector menu mentionned Luma3DS 8.1.1 instead of 7.1 in the video)
and extract all in SDCard exactly like in the tutorial.
I reached 3:30 minutes all was OK and when luma3ds seems to boot, a crash occurs.

A screen of the crash here  .. :

https://www.hostingpics.net/viewer.php?id=164260IMG20171007135804133.jpg

At 3:10 minutes, safehax made a backup firm0firm1.bak in boot9strap folder. Do I have to restore Something ? Can I fix luma start ?
I'am blocked now.
I can only start bootstrap9 menu (holding start button) ... to do what with ?
I can erase luma config .. to do what with ?
Otherwise, I boot with the exception screenshot.

Starting without sdcard causes black screen then 3DS switch off automatically.

Thanks for your help (I don't know how to continue with this luma crash).

**Comment by fraf** [comment]
I think my mistake is that I kept "Nintendo 3DS" folder from my old installation (ARM9 + menu hax).
I will attach a crash dump soon.

**Comment by Tyulis** [comment]
Read the official guide on [3ds.guide](http://3ds.guide), there is a full, precise and up to date tutorial and troubleshooting

**Comment by fraf** [comment]
here the dump :

https://nofile.io/f/3OG8jUqswpZ/crash_dump_00000000.dmp

I followed the part "Black screen on SysNAND boot after Installing boot9strap" because I have bootstrap install (holding start works and menu appears).
But Nothing works. I should go for CTRTransfert so ? But I have firmware 9.2, is it ok to restore NAND ? Links in the guide are for 11.5 doesn't it ?

Can I follow the guide ?

Thanks.

EDIT : I found a ctr transfert image in 9.2 n3DS, I can follow the guide then. Thanks.

**Comment by fraf** [comment]
Problem solved with troubleshooting guide as mentioned.
The problem was me !
I deleted the wrong folder into "Nintendo 3DS" folder. It was the one in emunand (32 number/letters name), not in sysnand (also 32 number/letters) I deleted.
My fault !

Thanks you very much, you can close !
