### ISSUE TITLE
Will not compile...

### ISSUE THREAD

**Issue by Sterillo** [LumaTeam/Luma3DS#89]
Hello, I am trying to compile this CFW and whenever I try (using all the steps correctly) it spits out this message:

`make: armips: Command not found;
make: *** [build/patches.h] Error 127`

**Comment by urherenow** [comment]
1) No you aren't doing all the steps correctly. If you were, you wouldn't get any errors.

2) Install armips and everything else the main page tells you to. Links are provided even! Add it to devkitPro\devkitARM\bin

3) Go to gbatemp next time. This is not a forum.

**Comment by Sterillo** [comment]
Jeez. Sorry for posting in the wrong place... But thanks anyways. I just figured a single answer question is better here than there...

**Comment by RShadowhand** [comment]
Read the README.md, it's explained there. Closing.
