### ISSUE TITLE
Instant Invite on this not working

### ISSUE THREAD

**Issue by lunathir** [LumaTeam/Luma3DS#894]
Sorry to bother you guys, but I have an issue with my 3DS and I was going to the Nintendo Hacking server but the instant invite link doesn't work. It gives me "(The instant invite is invalid or has expired.)"

**Comment by ihaveamac** [comment]
it seems there's a typo in it. https://discord.gg/MjzatM8

**Comment by lunathir** [comment]
Thanks, I'd suggest updating the comment in the issue tracker to be sure though.
