### ISSUE TITLE
[Feature request] EmuNAND manager

### ISSUE THREAD

**Issue by thenets** [LumaTeam/Luma3DS#899]
It's too complicate manage EmuNAND with Luma3DS + GodMode9.
I don't know if is better add an EmuNAND manager to Luma or create a new payload just for it.
I was thinking about creating a "SafeMode9" for features like manage EmuNAND that will not brick the console.

EmuNAND manager features:
- Format SD for EmuNAND support
- Add / remove EmuNAND 1, 2, 3 and 4
- Clear EmuNAND
- Tiny format for EmuNAND
- Install FBI on EmuNAND

**Comment by Nemris** [comment]
Are you certain that this issue belongs to Luma?

**Comment by thenets** [comment]
@DMSalesman I don't know. I was thinking that EmuNAND must be compatible with Luma, so the manager must be related to Luma or GodMod9 project.
Sorry if I posted in the wrong place.

**Comment by ghost** [comment]
This is out of scope for Luma, belongs as its own payload.

**Comment by thenets** [comment]
@Hikari-chin @DMSalesman can you give me a way to follow? An example payload project will help a lot. And is possible run/test/debug payload with Citra?

**Comment by Nemris** [comment]
@thenets 3DS development is out of my scope, I'm afraid.
