### ISSUE TITLE
Patch to prevent certain games from disconnecting the internet

### ISSUE THREAD

**Issue by cheatfreak47** [LumaTeam/Luma3DS#90]
Something I've noticed is that a handful of games force the Wifi off while they are running.

One such example of this is The Legend of Zelda: Ocarina of Time 3D

Was wondering if that could be patched out.
A practical use for a patch like this would be that it would negate the need for people using NTR for video streaming to run this via the debugger: write(0x0105AE4, (0x70, 0x47), pid=0x1a)

It would also allow the friends list application to display these games that for whatever reason force Wifi off.

**Comment by TuxSH** [comment]
I'll take a look when I have time ;)

**Comment by jaxrogers2** [comment]
This is a "feature" added in 11.0 to hinder downloading Homebrew Launcher payloads from the Internet with OoT3D and Cubic Ninja. Only these two games are affected, so if you need a temporary fix you can just restore a 10.7 backup or use emuNAND on <=10.7 to play the game with NTR streaming.

**Comment by fincs** [comment]
No it isn't. OoT has blocked internet access since 3DS system version 1.0. 11.0 only revoked CN's permissions to use SOC:u and http:u (it does not disconnect the 3DS from the Internet).

**Comment by TuxSH** [comment]
I assume it uses SOCU_CloseSockets, although I'm not so sure about that...

**Comment by TuxSH** [comment]
@cheatfreak47 do you have another example of a game turning off Wifi?

**Comment by cheatfreak47** [comment]
@TuxSH Sure do, Star Fox 64 3D and I've also heard Monster Hunter 3 Ultimate does as well, but I don't have that last game to check it personally.

**Comment by usagirei** [comment]
Monster Hunter 3 Ultimate has never turned my wifi off as far as i can tell, it has multiplayer, so i don't think it'd do it.
Just popped my cart in for good measure and the Internet is still connected (Blue Indicator on homemenu, wifi indicator on unit lit)

**Comment by Cu3PO42** [comment]
Pokemon X/Y/OR/AS disconnect from WiFi unless you explicitly connect to the internet in game as well.

**Comment by GabrielRRussell** [comment]
Is this a precautionary measure by games? I think it might be part of the system, as it happens with certain system apps too. System Settings, in particular, does this. I wonder what causes this across many apps.

**Comment by Bappsack** [comment]
all NFC Games still disable the wifi, if wifi turned on, then NFC will be disabled

**Comment by Shadow322** [comment]
Wrong NFC is enabled when WiFi is on and off when WiFi is off

**Comment by TuxSH** [comment]
The culprits are NDM:U EnterExclusiveState and NDM:U SuspendScheduler.

Now, for an efficient implementation => soon.

**Comment by TuxSH** [comment]
(∩ ͡° ͜ʖ ͡°)⊃━☆ﾟ

**Comment by LordShaid** [comment]
So how would I find and edit NDM:U EnterExclusiveState and NDM:U SuspendScheduler? I'm looking into this to try to prevent Pokemon Moon from auto-disconnecting from the wifi for NTR 3.6 streaming. Sorry if this has been solved, I'm very new to homebrew 3ds stuff and don't see a solution (at least one that I understand). The write command performed in the debugger does not do anything to help me. I am running 11.5 by the way
