### ISSUE TITLE
Luma3DS no longer reflects patches

### ISSUE THREAD

**Issue by Kingsbury8** [LumaTeam/Luma3DS#901]
I was working on some texture edits for Fire Emblem Fates, and tested one out. It worked fine, but when I added more textures, and edited the first, Luma3DS doesn't reflect the new textures/changes, but still shows the first edited texture, despite that file no longer being on my sd card. I have never had this issue before, and I did nothing different between the first test and the following ones. Update: Changes to patches for other game still are reflected, only FE Fates will not change.

**Comment by ghost** [comment]
Can't reproduce, likely user error. LayeredFS just redirects romfs to the SD card, if the files don't exist anymore it isn't possible that they would be shown.
