### ISSUE TITLE
Games Crash

### ISSUE THREAD

**Issue by narukan** [LumaTeam/Luma3DS#902]
**System model:**  Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):** 11.6.0.39E

**Entrypoint (How/what you're using to boot Luma3DS):** Boot9Strap

**Luma3DS version:** 8.1.1

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (4)

Splash: (Off)

PIN lock: (Off)

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
Sometime my game crash.
There is a black screen with red title and white text :
 
> An error occurred (ErrDisp)
>Error type:          generic
>Process ID:        53
>Process name:   niji_loc
>Process title ID: 0x0004000000175e00
>
>Adress:             0x0033e6c8
>Error code:       0xc88044ab
>
>Press any button to reboot.

---

> An error occurred (ErrDisp)
>Error type:          generic
>Process ID:        56
>Process name:   niji_loc
>Process title ID: 0x0004000000175e00
>
>Adress:             0x006b39d8
>Error code:       0xc960454b
>
>Press any button to reboot.

**Steps to reproduce:**
It's random. (When I play or after 3ds sleep)
When it happened, I was in the game since some days.
It happened on two download games ("Team Kirby Clash Deluxe" from eshop and "Pokemon Moon" from *.cia)

**Dump file:**

**Comment by ghost** [comment]
Can't reproduce, but this error is an FS problem; it's possible your SD card is partially corrupted or is damaged.
