### ISSUE TITLE
Errdisp NFC

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#903]
**System model:**
New 3DS
**SysNAND version (+emu/redNAND version if applicable):**
11.6.0-39U Sysnand

**Entrypoint (How/what you're using to boot Luma3DS):**
Boot9strap
**Luma3DS version:**
8.1.1 Stable

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When i use any app its shows ERRDISP Generic NFC, the only app i can use is system config

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by ValShaped** [comment]
Could you attach a crash dump?

**Comment by ghost** [comment]
No because the 3ds doesnt dump, it shows this
![img-20171019-wa0002](https://user-images.githubusercontent.com/25125986/31754628-3f4c5eae-b46f-11e7-9c53-d7ccfd19874c.jpg)

**Comment by ValShaped** [comment]
Huh, that is an issue

**Comment by ghost** [comment]
I formatted and now i can't complete the config
![img-20171019-wa0011](https://user-images.githubusercontent.com/25125986/31754847-cbfcaa88-b470-11e7-87ca-c4565aea92f4.jpg)

**Comment by Tyulis** [comment]
When did this issue happen the first time? Randomly, after Luma installation? And do you have access to GodMode9?

**Comment by ghost** [comment]
After Luma instalation and yes, i have access

**Comment by jcmejia** [comment]
Ok thanks

**Comment by Tyulis** [comment]
Ok, so check if the issue is still here if you restore your NAND backup. It's possible that something was wrong in your installation.

**Comment by ghost** [comment]
Can't reproduce; this seems like hardware damage; qtm (head-tracking) and other hardware parts also cause crashing if they're damaged.

**Comment by ghost** [comment]
but i changed the nfc antenna and i keep getting that error.

**Comment by Tyulis** [comment]
Do you tried to restore your NAND backup?

**Comment by ghost** [comment]
Finally i gived up and i bought another motherboard
