### ISSUE TITLE
VARIOUS CRASHES AT BOOT/INGAMES

### ISSUE THREAD

**Issue by AurelienMB** [LumaTeam/Luma3DS#906]
**System model:**

New 3DS XL, EUR

**SysNAND version**

11.6.0-39E SysNAND, 11.6.0-39E EmuNAND]

**Entrypoint :**

Boot9Strap

**Luma3DS version:**

8.1.1 stable 

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: ( 4)

Splash: ( Off)

PIN lock: ( Off)

New 3DS CPU: (Off )

Autoboot EmuNAND: (No )

Use EmuNAND FIRM if booting with R: (No )

Enable loading external FIRMs and modules: (No )

Enable game patching: ( No)

Show NAND or user string in System Settings: ( No)

Show GBA boot screen in patched AGB_FIRM: (No )

Patch ARM9 access: (No )

Set developer UNITINFO: (No )

Disable ARM11 exception handlers: (No )

**Explanation of the issue:**

Various crashes at boot/in game : 

At Zelda Majora's Mask (random crashes but the game boots most of the time) 

![1](https://user-images.githubusercontent.com/33004351/31863868-16ac3fea-b754-11e7-8e29-1254765ce07c.jpg)

Zelda Majora's Mask , when i try to enter the first door on the left, inside the Zora Hall.
This crash happens systematically.

![3](https://user-images.githubusercontent.com/33004351/31863892-7e6088bc-b754-11e7-9990-10d10baf98f0.jpg)

And Animal Crossing : New Leaf, each time i try to take the train.
This crash happens systematically.

![2](https://user-images.githubusercontent.com/33004351/31863915-d8e651a4-b754-11e7-853b-befa3e605bad.jpg)

I don't know if this concerns the 8.1.1 version of Luma but it happens since i did the A9LH to B9S
tutorial. Am i alone with this? Thank you.

**Comment by Sonlen1414** [comment]
That error code is a File System error code, your SD card is corrupted. Backup all the data off it that you can, try and use Checkpoint or sometbing for saves just in case, reformat it, and reinstall everything that couldn't be saved. Also this is not a Luma issue.
