### ISSUE TITLE
Can't access on Rosalina Menu

### ISSUE THREAD

**Issue by Clement95** [LumaTeam/Luma3DS#909]
**System model:**

[3DS XL]

**SysNAND version (+emu/redNAND version if applicable):**

[10.3.0-28E]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap/Sighax]

**Luma3DS version:**

[8.1.1 stable]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: (1)

Splash: (Off)

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

I can't access on Rosalina Menu because my L button is broken, can I change the combo to access on it ?

**Steps to reproduce:**

1. Press L+Down+SELECT but it doesn't work because my L button is broken

2.

**Dump file:**

**Comment by urherenow** [comment]
Github isn't a support forum. You should ask on gbatemp or discord. I'm not holding my 3ds in my hand, but I'm pretty sure you have to access Rosalina to change the combo, so your choices are have someone change it and send you their config file, or modify the source and build your own default.

**Comment by ghost** [comment]
From the Discord server, this should help you:

"This is the Rosalina config.bin to use if you can't open the Rosalina menu due to broken buttons. It changes the Rosalina menu combo to the "A" button. It's recommended that you change the Rosalina combo to something more convenient by opening the Rosalina menu, going to "Misc. Settings", and "Change menu combo"." 

https://cdn.discordapp.com/attachments/196635695958196224/369124653618298880/config.bin

**Comment by Clement95** [comment]
Thank you very much !

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-24 2:23 GMT+02:00 Yuuki Hikari <notifications@github.com>:

**Comment by Clement95** [comment]
Thank you, but it doesn't work, when I turn on my 3DS XL it shows the Luma config and to access on my Home Menu I need to save a new config, then A button doesn't work..

**Comment by Clement95** [comment]
...

**Comment by ghost** [comment]
Try this one. 

https://cdn.discordapp.com/attachments/287345711492628490/372887450101612555/config.bin

**Comment by Clement95** [comment]
I tried, I didn't find what is the Menu Combo, I tried "A" but it doesn't work

**Comment by Clement95** [comment]
It's okay now, thank you !

**Comment by FlamingNova** [comment]
I'm having a similar issue but neither config posted in this thread works when I copy it into the luma folder. It launches the config screen instead upon boot.
