### ISSUE TITLE
Some games yield System Update message

### ISSUE THREAD

**Issue by ccfman2004** [LumaTeam/Luma3DS#91]
When trying to redeem the Darkrai Pokémon code in Pokémon X, I get the "A system update is required" error even though my emuNand is up to date.  I even re-ran the update system option and it says I'm up to date so there may be something else that Nintendo is using for system version detection that isn't patched or something.

I'm on emuNand 11.0.0-33 using A9LH with Luma 5.4.

This happens with all 4 Pokémon games X, Y, Ruby and Sapphire on both 3DS XL and N3DS XL.

This error does not happen when checking in with Pokémon Shuffle which also requires an up to date system to check in.

Both of my emuNands use stock Nintendo 11.0.0-33 files with no patched system titles.

**Comment by TuxSH** [comment]
Are you using the latest commit?
http://astronautlevel2.github.io/Luma3DS

**Comment by ccfman2004** [comment]
I thought that 5.4 was the latest and wasn't aware that there was something newer or that site since I can't compile this stuff myself.

It does work now with the afc6f51 commit.

**Comment by TuxSH** [comment]
It's indeed the latest _release_

**Comment by reeved** [comment]
I tried to use the latest commit and I still can't connect to the internet using the Player Search System on either Pokemon X or Omega Ruby. I moved the /3ds/ files where they should be and also put the .dat file in the root folder. Was there a step to updating that I missed?

**Comment by TuxSH** [comment]
What about the friend list?

What entrypoint are you using? AL9H, AL9H with a boot manager or menuhax?

**Comment by reeved** [comment]
okay, I updated Luma using Star Updater and everything is fine now. on a sidenote, what did star updater do that I didnt when I manually tried to update Luma? I'm using A9LH.

edit: didn't realise i needed to replace A9LH.bin

**Comment by urherenow** [comment]
How exactly did you try "to use the latest commit"? Look for my sig on gbatemp. The rxtools compiling guide applies (_for the most part_) to everything. Don't know how long ago you first cloned the repo, but perhaps you needed to update your submodules and/or libraries such as ctrulib.
