### ISSUE TITLE
Console crashes whenever I launch VC games, after exiting FBI.

### ISSUE THREAD

**Issue by Cyrean** [LumaTeam/Luma3DS#910]
System model:

New 3DS

SysNAND version (+emu/redNAND version if applicable):

11.6.0-39E SysNAND

Entrypoint (How/what you're using to boot Luma3DS):

boot9strap

Luma3DS version:

8.1.1 Stable

Luma3DS configuration/options:

Default EmuNAND: 1

Screen brightness: 4

Splash: Off

PIN lock: Off

New 3DS CPU: Clock+L2

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ()

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: (x)

--

Explanation of the issue:

Launching VC games after exiting FBI (injected into Face Raiders) causes my console to crash.
I have to reboot everytime I want to play VC games. Might be just me though.

--

Steps to reproduce:
1. Boot the console and launch FBI.
2. Press the Home Button and close FBI
3. Launch any VC Game

![exception](https://user-images.githubusercontent.com/33072917/31968942-0fc7b338-b913-11e7-86ca-021752b52104.jpeg)

**Comment by ghost** [comment]
>Disable ARM11 exception handlers: (x)

Your right to submit issues is forfeit. This is stated on the config option description. 

Also, injection is a terrible hack and no one should be using it any longer. Not a Luma issue, most likely.
