### ISSUE TITLE
 edits to MCU Sysmodule memory in code/.text mode should be read-only

### ISSUE THREAD

**Issue by Derek1199** [LumaTeam/Luma3DS#917]
I believe the MCU sysmodule's memory should be ready only in code/.text mode using rosalina's ram editor should be read only. While normally the worst that could happen Is just needing to take the battery out of the console to shut off, it is possible to rewrite the code in it in code/.text mode. In doing this if we were to change the flashing code in it, we could end up flashing random garbage to the MCU, ending up in bricking it. And considering the fact MCU handles a lot of service, from Backlight, to volume slider, to LCD's; this could potentially brick users. MCU bricks are also almost completely unrecoverable. The only way to unbrick one is soldering to the MCU and reflashing firmware to it. I feel very strongly about this. In any case it should at least give the user a warning when going to code/.text mode for the MCU sysmodule's memory.

**Comment by ghost** [comment]
Non-issue, the best you'll accomplish unless you're deliberately trying is crashing the MCU sysmodule. Additionally, flash is only done once on power on, anyway.
