### ISSUE TITLE
Instant Arm11 crash

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#918]
System model:

New 3DS

SysNAND version (+emu/redNAND version if applicable):

11.6.0U SysNAND

Entrypoint (How/what you're using to boot Luma3DS):

boot9strap

Luma3DS version:

8.1.1 22a8661fe1840057d3a6a720b79659a85b50d633

Luma3DS configuration/options:

Default EmuNAND: 1

Screen brightness: 4

Splash: Off

PIN lock: Off

New 3DS CPU: Off

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

Explanation of the issue:

Instant Arm11 crash

[arm11.zip](https://github.com/AuroraWright/Luma3DS/files/1439803/arm11.zip)

**Comment by ghost** [comment]
Compiled this myself, cannot reproduce. Exact same hardware (New 2DS XL), firmware version and region, config settings, etc.

**Comment by Shadow322** [comment]
Then can u upload your Luma3DS .firm file plez

**Comment by ghost** [comment]
https://a.uguu.se/so3Cq1mImXVw_boot.firm

**Comment by Shadow322** [comment]
thanks works

**Comment by TuxSH** [comment]
@Shadow322 by any chance, did you build it with an outdated dkA (run `arm-none-eabi-gcc -v` & paste the output to check)

**Comment by Jerry-Shaw** [comment]
Same here but under windows
Could this help?

Using built-in specs.
COLLECT_GCC=arm-none-eabi-gcc
COLLECT_LTO_WRAPPER=d:/programs/devkitpro/devkitarm/bin/../libexec/gcc/arm-none-eabi/6.3.0/lto-wrapper.exe
Target: arm-none-eabi
Configured with: ../../gcc-6.3.0/configure --enable-languages=c,c++,objc,obj-c++ --with-gnu-as --with-gnu-ld --with-gcc --with-march=armv4t --enable-cxx-flags=-ffunction-sections --disable-libstdcxx-verbose --enable-poison-system-directories --enable-interwork --enable-multilib --enable-threads --disable-win32-registry --disable-nls --disable-debug --disable-libmudflap --disable-libssp --disable-libgomp --disable-libstdcxx-pch --target=arm-none-eabi --with-newlib --with-headers=../../newlib-2.5.0/newlib/libc/include --prefix=/opt/devkitpro/i686-w64-mingw32/devkitARM --enable-lto --with-system-zlib --with-bugurl=http://wiki.devkitpro.org/index.php/Bug_Reports --with-pkgversion='devkitARM release 46' --build=x86_64-unknown-linux-gnu --host=i686-w64-mingw32
Thread model: single
gcc version 6.3.0 (devkitARM release 46)

**Comment by fincs** [comment]
Outdated devkitARM. Please run the devkitPro Updater to get the latest version of devkitARM (r47).

**Comment by Jerry-Shaw** [comment]
Wow, never update devkitPro before, thanks.

**Comment by fincs** [comment]
devkit*Pro* is the organization that *pro*vides the devkits. You can't really install it. What you actually do is install devkitPro products such as devkitARM using the devkitPro Updater program.

**Comment by Shadow322** [comment]
@Jerry-Shaw can u contact me on gbatemp nick Shadow#1 I need some help since your on windows compiling.

Thanks

**Comment by Jerry-Shaw** [comment]
@Shadow322 Yeah, posted to you, see ya on GBATemp.

**Comment by Repflez** [comment]
I managed to replicate this consistently by using Boot NTR Selector 2.9 installed as CIA.

1. Open Boot NTR Selector 2.9.
2. Select any version or let it select 3.6 automatically.
3. Instead of returning to the HOME menu, it crashes.

On commit 8258a98, it gives an ARM11 crash, making a dump, of course, while on commit 22a8661 or newer it instead shows an ErrDisp message with the `0xd92103fb` error code. Commit 76dde0e is the last working commit.

Here's the dump given by these steps:
[crash_dump.zip](https://github.com/AuroraWright/Luma3DS/files/1442955/crash_dump.zip)

**Comment by Jerry-Shaw** [comment]
Yep, updating devkitPro works. Thanks guys.
