### ISSUE TITLE
Holding L or R during the Luma Chainloader locks it up

### ISSUE THREAD

**Issue by Sonlen1414** [LumaTeam/Luma3DS#921]
Luma Version 8.1.1

During the Chainloader, if you hold L or R, the console is unresponsive until you release the button.

**Comment by ghost** [comment]
Confirmed, it will not respond to any key, not even the power button, if L/R are held.

**Comment by Derek1199** [comment]
The same thing also happens in luma config too.

**Comment by roggentrolla** [comment]
Can confirm, my 3DS L button is stuck down and config menu is unresponsive. My 3DS is currently unusable because of this.
