### ISSUE TITLE
Broken Debugger(Rosalina)

### ISSUE THREAD

**Issue by Bappsack** [LumaTeam/Luma3DS#923]
**System model:**

[e.g. 2DS, New 3DS, Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.6.0-39U SysNAND, 11.6.0-39J EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[e.g. Boot9Strap/Sighax, etc.]

**Luma3DS version:**

[e.g. 8.1.1 stable or if using nightly/hourly specify the commit like this https://github.com/AuroraWright/Luma3DS/commit/9570e6cbeca53128433abbf5e3473cb8a07fe69e]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( 4)

Splash: ( )

PIN lock: ( )

New 3DS CPU: (x )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x )

Show NAND or user string in System Settings: (x )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( x)

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

If the 3ds Connection lost, the debugger will freeze with some game steps(Enter house or something)
Its only Fixable when u disable the debugger, disable wifi, reenable wifi, reenable Debugger.

**Steps to reproduce:**

1. Turn the router off

**Dump file:**

**Comment by ghost** [comment]
Can't reproduce, the only "freeze" I've seen with the debugger are when a process is attached, which is expected.
