### ISSUE TITLE
How does a "svcBreak" in the "loader" process look like on 3DS screen?

### ISSUE THREAD

**Issue by RoestVrijStaal** [LumaTeam/Luma3DS#924]
That question crossed my mind when reading https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-troubleshooting#i-get-a-black-screen-on-boot for troubleshooting. 

I want to be sure the problem which the tutorial solves is the same one as I have. It would be a pity when I do more harm while thinking I'm fixing my problem.

**Comment by ghost** [comment]
Improper use of the issue tracker.

**Comment by RoestVrijStaal** [comment]
Ok fair enough, what's the correct place to ask for clarification of what's written on the wiki of _this_ repo?
