### ISSUE TITLE
Newly installed Luma 8.1

### ISSUE THREAD

**Issue by cyberexodus** [LumaTeam/Luma3DS#930]
![1510629174813969856003](https://user-images.githubusercontent.com/33645756/32761175-bc9c5e04-c8a6-11e7-97cf-0f824377774b.jpg)
So I have a O3DS with 9.5.0.22U update and I was follwing this tutorial on to installing cfw to my 3ds but I keep getting this screen after running soundhax.
This is the tutorial I used

https://3ds.guide/installing-boot9strap-(homebrew-launcher)

**Comment by Shadow322** [comment]
what screen?

**Comment by cyberexodus** [comment]
Sorry I'm new I was using mobile earlier. There's an update to my original.

**Comment by Shadow322** [comment]
Did u update to 11.6?

**Comment by cyberexodus** [comment]
No

**Comment by Shadow322** [comment]
B9s installed?

**Comment by cyberexodus** [comment]
Yes

**Comment by Shadow322** [comment]
Then just update the 3ds

**Comment by cyberexodus** [comment]
Can't start up soundhax,but luma is still active.

**Comment by Shadow322** [comment]
U don't need soundhax anymore

**Comment by cyberexodus** [comment]
Okay, but lets say I want to install cias what do I do?

**Comment by urherenow** [comment]
use the rosalina menu to launch the homebrew browser. Run FBI.3dsx from that. You can install the .cia version of FBI onto your home menu from there. Also the hblauncher_loader if it meets your fancy.

**Comment by cyberexodus** [comment]
From the rosalina menu what command do I set to enter the homebrew browser.

**Comment by Shadow322** [comment]
https://github.com/AuroraWright/Luma3DS/wiki

**Comment by cyberexodus** [comment]
Lol just got it thanks for all the help guys 😆

**Comment by Derek1199** [comment]
https://3ds.guide ...follow this.
