### ISSUE TITLE
payloads can not load...

### ISSUE THREAD

**Issue by GabrielCatDev** [LumaTeam/Luma3DS#931]
i press start when i power on and not load payloads menu...something wrong?

**Comment by urherenow** [comment]
This isn't a support forum. Ask on GBAtemp or something, and when you do, post your ENTIRE situation, including 3ds model, luma version, b9s version, folder setup (what's in sd:/luma/payloads/ ?)

**Comment by TheRasPiGuy** [comment]
tetradog, if you are still here, you need to hold down the start button and then press power until a menu shows up.
