### ISSUE TITLE
Won't boot with boot.firm

### ISSUE THREAD

**Issue by TheRasPiGuy** [LumaTeam/Luma3DS#932]
Ok, so I followed [this](https://3ds.guide/a9lh-to-b9s) tutorial to upgrade from A9LH to B9S, but after I finished everything, it worked for a while, and then suddenly, it wouldn't turn on. I took out the SD card to see if it would work, and it booted, so then I put my SD card back in, and it still worked, but when I tried to boot with the SD card back in, the blue power led turned on, and then a second later, it turned off. So I tried experimenting on my computer to see what file(s) were causing this, but when I moved the boot.firm onto my computer it booted normally... So, my question is, why does my O3DS on 11.6.0-39U hate the boot.firm file?
Also, I tried using the released boot.firm, and also tried modifying the source code and building it, but it still wouldn't boot.

**Comment by Derek1199** [comment]
Install b9s 1.3, simple as that. And use the latest luma release.

**Comment by TheRasPiGuy** [comment]
The thing is, I did, but I will try updating...
after I finish dumping Cubic Ninja to my 3ds (from gamecart)...

**Comment by TheRasPiGuy** [comment]
I can't even update it because I can't get to the chainloader menu. It goes straight to GodMode9.
i hate my 3ds...

**Comment by TheRasPiGuy** [comment]
wow, now it boots with sd card...
that was strange...
