### ISSUE TITLE
Splash Screens don't work?

### ISSUE THREAD

**Issue by TheRasPiGuy** [LumaTeam/Luma3DS#933]
So, I downloaded 2 different splash screens from [here](https://splash.3dsthem.es/), but when I copy both bin files to the luma folder, it will boot, but the splash screen is white. This happens with all the splash screens I use, but it started doing this after I upgraded from a9lh to b9s, so I don't know if this is a bug or something, but this is really strange...

**Comment by ghost** [comment]
They work for me, as splash.bin and splashbottom.bin in /Luma.
