### ISSUE TITLE
System crashes when clicking SD on FBI

### ISSUE THREAD

**Issue by Gupple** [LumaTeam/Luma3DS#938]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[11.6.0-39U SysNAND]

**Entrypoint:**

[Boot9Strap]

**Luma3DS version:**

[8.1.1 stable]

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (off)

PIN lock: (off)

New 3DS CPU: ( )

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: (x)

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
System shows an ARM9 exception when clicking SD on the FBI menu. Updated luma to 8.1.1 and system crashes, showing an ARM9 data abort.

**Comment by Tyulis** [comment]
"Data abort" shows a problem in the program's data, so it is more likely a problem in FBI rather than in Luma

**Comment by Gupple** [comment]
So should I try to reinstall FBI?

**Comment by urherenow** [comment]
Couldn't hurt. iirc FBI had updates related to b9s, and you didn't mention which version of FBI was installed.

**Comment by Gupple** [comment]
It was the latest version of FBI.

**Comment by urherenow** [comment]
So now it's time to run tests on the SD card. I have no such issue on O3DS or N3DS. If it passes all tests, you might try formatting the card and then copy everything back to it.

**Comment by ghost** [comment]
Can't reproduce. FBI works fine for me as both a CIA and 3DSX.
