### ISSUE TITLE
Cant play gba.cia and dsiware game when up latest release from v5.2 luma3ds 

### ISSUE THREAD

**Issue by minhhot** [LumaTeam/Luma3DS#94]
I have my O3dsXL a9LH with Luma3ds updated latest release, sthg are fine accept my gba and dsi game not run. In v5.2 it works normally. Did you know that and you have any idea about this. Please help me, thank bro. I boot Luma3ds with exactly arm9loaderhax.bin in root of my SDcard.

**Comment by AuroraWright** [comment]
https://github.com/AuroraWright/Luma3DS/wiki/FAQ-and-Troubleshooting#i-get-a-black-screen-on-boot-with-an-old-3ds-which-has-been-downgraded-from-the-gateway-menu-in-the-past

**Comment by minhhot** [comment]
My games work normally like before. Thank you very much

2016-05-25 4:19 GMT+07:00 Aurora notifications@github.com:
