### ISSUE TITLE
Problem Rosalina New 3DS Menu clock + L2

### ISSUE THREAD

**Issue by Juanito9001** [LumaTeam/Luma3DS#944]
Always in the home menu i have enabled the "L2 cache" and the "clock rate", and always i want to disable, but when i return to the home menu, both options re enable automatically.
I erased the luma config.bin three times and this doesnt fix the problem

**Comment by ghost** [comment]
The Home Menu runs at 804MHz+L2 on the New 3DS/2DS even on stock consoles, this is expected behavior.
