### ISSUE TITLE
Luma cannot patch romfs in applets or cfas

### ISSUE THREAD

**Issue by dd01da0465b4542f8f8af4ecedc149ed** [LumaTeam/Luma3DS#949]
(Hello there, I'm the creator of Foxverse) While patching Miiverse, I noticed that Luma cannot patch romfs inside applets this is a big issue for us since in order to get our HTTPS certs inside Miiverse we used LayeredFS for this, since this doesn't seem to work we have to use 2 CIAs to patch this and 3DS system updates no longer work because of this, I consider this being a (needed) enhancement to LayeredFS. Thank you. -ninjafox

**Comment by ihaveamac** [comment]
as far as I know this won't happen due to code differences in applets, compared to normal applications. someone else can provide a better explanation.

**Comment by urherenow** [comment]
What exactly is miiverse being patched to do? Use a different server? Because... isn't miiverse supposed to be discontinued?

**Comment by holly-hacker** [comment]
@urherenow yes, it's common for custom servers to patch https URLs in the client so the requests can be redirected to a new one without having to fuck with host redirection and installing custom certificates.

**Comment by profi200** [comment]
You will need custom certs anyway if you want to keep security. Patching https completely out is just dumb.

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
@urherenow Yes, It's getting patched to use a different server.

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
@profi200 Originally we wanted to use HTTPS but it didn't work because of this issue we had. So to fix this we have to install 2-3 CIAs that contain our certs and stuff.

**Comment by khang06** [comment]
looks like trying to use game patching on home menu is also affected by this

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
Updating the title as it seems that not even system data archives work with LayeredFS.

**Comment by frozenLake** [comment]
Oh, this is why my RootCA edits were not doing anything? Okay, this is something I have a decent need for.

**Comment by frozenLake** [comment]
You know, I'm curious: Has any research been done regarding this? Is there anything of note that is making this more difficult on the devs?

**Comment by Brawl345** [comment]
Any news for this? Would like to add Let's Encrypt to the 3DS browser by editing the rootca.pem, but LayeredFS doesn't work with applets.

**Comment by ParzivalWolfram** [comment]
Would be handy for patching several features, more support and new certs into the Browser.

**Comment by billyohgren** [comment]
I would love to patch the home menu, and if this is affected by this, could someone give me pointers on where this (layeredFS) is being used in the source code?

**Comment by AuroraWright** [comment]
As @ihaveamac said sadly the SDK code patched by layeredfs isn't there on these titles, so the current approach won't work
