### ISSUE TITLE
mask of majora 3ds An  exception occurred

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#950]

**Comment by Sonlen1414** [comment]
Buy the game, it works 100% of the time.

**Comment by Navioli** [comment]
1: Enable Enable loading external FIRMs and modules: ( )
2: mask of majora 10/10

**Comment by mariyo8** [comment]
@Navioli 

How do I do this?

**Comment by Navioli** [comment]
1. Make sure the console is off.
2. Hold select while turning on the console.
3. You should be on the Luma3DS configuration screen.
4. Go down to Show NAND or user string in System Settings and select it.
5. Go to Enable loading external FIRMs and modules and select it.
6. Go ahead and press start to leave. It should work, its what worked for me.

**Comment by mariyo8** [comment]
@Navioli 
Did what you said. The screen error pops up...

**Comment by Sonlen1414** [comment]
Of course the error still pops up, what he suggested you do does literally nothing for corrupted titles, Luma does not support Piracy and you won't be getting help with it here. Buy the game as I said, it is guarenteed to work. ¯\\\_(ツ)_/¯

**Comment by Navioli** [comment]
Oh, he pirated his games? It started doing that when I hacked eShop titles with NTR.
