### ISSUE TITLE
Feature Request: Default Chainloader Boot / key-pad SysNAND boot option.

### ISSUE THREAD

**Issue by Spork-Schivago** [LumaTeam/Luma3DS#953]
**System model:**

[Old 3DS]

**SysNAND version (+emu/redNAND version if applicable):**

[10.3.0-28U SysNAND, GW3D 10.2.0-28U EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

[Boot9Strap]

**Luma3DS version:**

[8.1.1-f6483ec]

**Luma3DS configuration/options:**

Default EmuNAND: (1 )

Screen brightness: ( )

Splash: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: (yes)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**
This isn't a bug, I'm trying to submit a feature request but I'm having trouble figuring out how to add the label.   I've filled out the requested information to the best of my ability.

I have a Gateway 3DS and currently am using the Chainloader feature of Luma3DS.   I have it configured where if I hold down the "down" key on the d-pad during bootup of the 3DS, it'll boot into the Gateway mode and show the dragon, along with the EmuNAND that I have installed.

If I don't hit the "down" key on the d-pad during bootup, it boots to normal SysNAND.    I'd like to submit a feature request where I can switch it around.    For example, I would like to have it only boot to the SysNAND if I hold down the "down" button on the d-pad, otherwise, have it boot directly into the Gateway mode (or whatever file we're chainloading).

Thanks!

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by GabrielRRussell** [comment]
What do you mean by Gateway 3DS? Is it a 3DS previously hacked with Gateway, or was a 3DS released by Gateway?

**Comment by ihaveamac** [comment]
"Gateway 3DS" usually refers to the red card, so...

**Comment by Margen67** [comment]
1. Stop using Gateway
2. ???
3. Profit

**Comment by mzino** [comment]
Since the global consensus in the community seems to be that GW is "objectively worse" (even if it does different things so it's not really comparable...) you probably won't get an option to override the default no-button action for the chainloader.

You should use BootCTR9 instead. The latest commits have .firm compatibility and there's a GW .firm around, so you can set a default option to load GW and another button for Luma or other homebrews.

PS. how did you get the Luma chainloader to load GW? Last time I checked it was incompatible and BootCTR9 was kinda the only option.

**Comment by urherenow** [comment]
Yay. So for that, I'll need to rebuild boot9strap again so bootctr9 will be the default, but named ctr9.firm or something, to ensure I don't break Luma by not having it as sd:/boot.firm (or does luma autodetect its own name for reboot cases (exit system settings, or MH on O3DS)?

**Comment by mzino** [comment]
I don't think rebuilding B9S would solve anything. AFAIK, you would still reboot to the BootCTR9 firm when exiting system settings, just named differently.

But you could press the corresponding button at each reboot, not so hard.

**Comment by ghost** [comment]
There are no plans for this at this time.
