### ISSUE TITLE
Using latest commit, over latest release breaks mario kart 7 mod; ctgp-7

### ISSUE THREAD

**Issue by greensad** [LumaTeam/Luma3DS#956]
I'm not exactly sure why this happens but I can confirm that installing the latest release fixes the problem. The mod author said it had something to do with a bug caused by the custom sm module.

**Comment by ghost** [comment]
As per the [CTGP-7 changelog](https://gbatemp.net/threads/mario-kart-7-custom-track-grand-prix-7-ctgp-7.396936/), this has been fixed on their side as of 0.15.1.
