### ISSUE TITLE
Arm11 Crashed while I was playing Fire Emblem Fates: Conquest. I was playing in My Castle.

### ISSUE THREAD

**Issue by NaturalHarmonia** [LumaTeam/Luma3DS#958]
Here's the dump.

[crash_dump_00000008.zip](https://github.com/AuroraWright/Luma3DS/files/1543717/crash_dump_00000008.zip)

I've had this happen multiple times a few days ago as well and thought it had stopped.

**Comment by ghost** [comment]
Can't reproduce, but all the people that have complained of Fates crashes in the past have had damaged save data from improper editing.

**Comment by NaturalHarmonia** [comment]
I also just had a crash with Pokemon Ultra Moon. Will upload dump later.

**Comment by Sonlen1414** [comment]
The issue is most likely you didnt remove the no outlines patch as it isn't compatible with the game update yet. Not a Luma issue.

**Comment by ghost** [comment]
Played both of these games through to completion on the latest few commits without issue; the issue is likely that or improper save editing. Not Luma's problem, as Sonlen said.
