### ISSUE TITLE
Splash screen too fast

### ISSUE THREAD

**Issue by dbenfouzari** [LumaTeam/Luma3DS#96]
Hi there,

I followed Plailect's tutorial and I now have Updated SysNand working with a9lh + Luma3DS.
I would like to customize my boot with a custom splash image. 
I successfully get my image showing, but that's way too fast ! I nearly can't see it.

Of course, I put my splash.bin in /luma/ folder, that's why i'm able to say it works, but that's really too fast (like 100ms showing).

Any way to make it way longer ?

Thanks in advance ! :)

**Comment by Hartie95** [comment]
It's not possible with luma, at least not without modifying the source code, but you could use a configurable boot loader like bootctr9.

**Comment by RShadowhand** [comment]
Use the latest hourly, that added some splash delay I believe.

**Comment by TuxSH** [comment]
It's consistenly 3 seconds with the latest commit.
