### ISSUE TITLE
no boot, ARM11 (core 1) exception prefetch abort (kernel panic)

### ISSUE THREAD

**Issue by jherome28** [LumaTeam/Luma3DS#960]
Device is an old 3DS CTRtransfer 2.1.0 to 11.5.0 due to following an old guide with missing files. stuck at 2.1.0 updated the device using pokemon Y game cart. causes an arm9 prefetch abort, CTRtransfer to 11.5.0 followed by using ntrboothax installing boot9strap and luma then had ARM11 (core 1) prefectch abort (kernel panic) current proces : ptm (0004013000002202)
![20171211_191149](https://user-images.githubusercontent.com/34464593/33865595-46101e44-dea7-11e7-8ee6-2450abd753a7.jpg)

**Comment by ghost** [comment]
The issue tracker isn't for technical support; try the [Nintendo Homebrew Discord](https://discord.gg/MWxPgEp).
