### ISSUE TITLE
Request: Streetpass Extension

### ISSUE THREAD

**Issue by piepie62** [LumaTeam/Luma3DS#961]
Right now, the Streetpass data is limited to twelve games. Is it even feasible to extend this? If so, then can you that or is it out of the scope of this project? I understand if the answer to either of these is no, given that I have not seen anything about this anywhere. Thanks for any answers, though

**Comment by TuxSH** [comment]
I don't know how/where/how many times the limit is implemented (knowing would take time) and I believe than even if I knew it wouldn't be feasible _a priori_.

Interesting proposition but I don't think it's feasable reasonably.

**Comment by piepie62** [comment]
Alright, that's fair. Just was wondering if you had any clue. Thanks for the reply!
