### ISSUE TITLE
Online connectivity in certain titles error.

### ISSUE THREAD

**Issue by rhg** [LumaTeam/Luma3DS#97]
I haven't tested this much, but on Pokemon Alpha Sapphire booted from an emunand on the latest firmware version and latest luma3ds trying to go online gives an error stating that 'a system update is required'. @dark-samus told me on IRC that this is due to the loader and that there is a patch for this but the update broke it. I was able to get online via https://github.com/yellows8/ctr-httpwn but a fix would be nice (and necessary for games such as smash).

**Comment by piratesephiroth** [comment]
just switch to a more recent build

**Comment by rhg** [comment]
I'm running the latest release as of today, but glad to know it's fixed
already.

**Comment by piratesephiroth** [comment]
It's broken on the latest official release.
You need to use a more recent nightly build.

http://astronautlevel2.github.io/Luma3DS/

**Comment by Dimensional** [comment]
I've attempted that, but the most recent build prevents me from loading any cia files nor booting into emunand. I have to revert back to 5.4 for things to work again.

**Comment by rhg** [comment]
I'm half-tempted not to close this issue until a new release is cut with this fix, but on the other hand, I'm about to go build-hunting and if I find a working one then I might say which and close.

## 

8544dc works for me, but I do think that this should be in the wiki; and that is a seperate issue so I'm closing this one.
