### ISSUE TITLE
Luma 8.1.1 Game Patching not working N3ds Xl

### ISSUE THREAD

**Issue by VanquishSTG** [LumaTeam/Luma3DS#976]
Version: Luma 8.1.1
Installed via ntrboot on 11.4.37 eu,
Afterwards updated to 11.6.39 eu
Fbi etc works just fine but game patching eoesnt work. Already ntrbooted 3 nds xl successfull with game patching working, but the 4th just doesnt want to.

**Comment by ghost** [comment]
You've probably messed up your SD card directory structure or are using invalid files. Can't reproduce.
