### ISSUE TITLE
Crash with Luma3DS v9.0?ls this a bug?

### ISSUE THREAD

**Issue by JKC-A9LH** [LumaTeam/Luma3DS#979]
When l close bigbluemenu or devmenu to open other app or game，it will be crash？B9 v1.3 Luma3DS v9.0. FBI doesn't has this problem.

**Comment by urherenow** [comment]
Neither devmenu nor bigbluemenu are updated and they probably never will be. Why don't you just use FBI?

**Comment by fincs** [comment]
Moreover, they are illegal leaked tools from the official SDK. Do not use them, use FBI instead.
