### ISSUE TITLE
Incorrect entrypoint in config

### ISSUE THREAD

**Issue by Moire9** [LumaTeam/Luma3DS#980]
**System model:**
o3DSXL

**SysNAND version (+emu/redNAND version if applicable):**

SysNand 9.2.0-19U (I know, I downgraded to use EmuNand9, only to realize it doesn't work with SigHax, forgot to update it again) RedNand type EmuNand (so, it's EmuNand, but RedNand type, not GW type) 11.6.0-36E

**Entrypoint (How/what you're using to boot Luma3DS):**

SaltMode9 Bootloader commit f157dcd542f75287bb080fe77642b8fbdc4fdd4a

**Luma3DS version:**

9.0 Stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (4)

Splash: (After)

PIN lock: (None)
--

Autoboot EmuNAND: (x)

Use EmuNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: ( )

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: (x)

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

When booting into Luma Config, it shows at the bottom, "Loaded by B9S on SD." However, this is not true. I don't use B9S anymore-I switched to the GM9 bootloader some time ago. It should say, "Loaded via SigHax on SD," or "Loaded by GM9 on SD."

**Steps to reproduce:**

1. Use GM9 bootloader.

2. Boot Luma config.

**Dump file:**
no crash

**Comment by ghost** [comment]
This is likely a result of GodMode9's bootloader pretending to be boot9strap for compatibility with FIRMs that check their entrypoint; not a Luma issue and the only entrypoint we officially recommend is B9S.
