### ISSUE TITLE
Unexcepted issue on my 3DS, black screen

### ISSUE THREAD

**Issue by govelosu** [LumaTeam/Luma3DS#983]
Hello.
When i'm lauching the Homebrew launcher, a black screen appears and i only can exit.
Here is the dump file.
If someone can help me, it would be very appreciated.

(https://github.com/AuroraWright/Luma3DS/files/1585025/crash_dump_00000000.zip)

**Comment by ghost** [comment]
You're either using an old version of the Homebrew Menu, an incompatible takeover app like H&S, or an otherwise incompatible boot.3dsx.
