### ISSUE TITLE
SD titles not working from Test Menu

### ISSUE THREAD

**Issue by ghost** [LumaTeam/Luma3DS#984]
**System model:**

Old 3DS XL

**SysNAND version (+emu/redNAND version if applicable):**

9.2.0-20U SysNAND, 11.6.0-39U/11.5.0-38J EmuNAND

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap, probably 1.2?

**Luma3DS version:**

9.0

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (1)

Splash: (Off)

PIN lock: (Off)

--

Autoboot EmuNAND: (x)

Use EmuNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: (x)

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

Using Test Menu, SD titles black screen on load and require a forced power-off.
NAND titles work fine (DevMenu, SaveDataFiler, Config), and physical cartridges work fine. Haven't tried DSiWare.

(Before someone suggests unitinfo breaking retail apps, the games run fine from default home menu.)

Worked fine in [8.1.1-6b9b047](https://github.com/AuroraWright/Luma3DS/commit/6b9b0472bccf32275123741aae22ef6a369647e2), and for that matter, continues working fine if I just revert from 9.0 to that.
I wouldn't be able to tell which commit broke it unless I tested every commit since then, and there's a lot of them. :s

**Steps to reproduce:**

1. Have Test Menu installed along with DevMenu to NAND (needed to launch other apps through Test Menu), with Test Menu set in Config app, and dev unitinfo in Luma settings so it will load.

2. Run DevMenu on Test Menu, pick any of your installed SD titles.

3. Black screen, ???, no profit

**Dump file:**

It silently fails without producing a dump, so there isn't any, sorry.

**Comment by redunka-zver** [comment]
Can confirm this.
O3DS, SysNAND 11.6.0-39E, B9S 1.3, no settings ticked in Luma, aside from UNITINFO. 
Both TestMenu and DevMenu are ver. 0.24.67 (r61713), if that matters.
This started to happen after this commit: [8258a98](https://github.com/AuroraWright/Luma3DS/commit/8258a986472baa94188de2890735b4f065e5f34e), reverting to any previous one fixes this issue.
DSiWares do work, as well as everything else installed to NAND + cartridges.
Also, some SD apps still work, like Flipnote Studio 3D, CTRXplorer and GBA titles.
FBI actually crashes, here's a crashdump, maybe it'll help: [crash_dump_00000000.zip](https://github.com/AuroraWright/Luma3DS/files/1585976/crash_dump_00000000.zip)
