### ISSUE TITLE
[Question] Sysmodules

### ISSUE THREAD

**Issue by chaoticryptidz** [LumaTeam/Luma3DS#985]
Will there in the future be more sysmodules to replace the default nintendo ones?
If you can, please message me on discord at NamedKitten#8468
\- NamedKitten :3

**Comment by chaoticryptidz** [comment]
Why close the question instead of answer it?

**Comment by ghost** [comment]
Because it's a misuse of the issue tracker.

**Comment by chaoticryptidz** [comment]
I didn't know where else to place it.

**Comment by Margen67** [comment]
Try contacting TuxSH or Aurora on Discord.

**Comment by chaoticryptidz** [comment]
Thanks.

**Comment by chaoticryptidz** [comment]
Aurora doesn't have dm's open, i'll try TuxSH now.
