### ISSUE TITLE
Feature Request: Increased/configurable delay time for splash screens

### ISSUE THREAD

**Issue by Lv44EnderShaman** [LumaTeam/Luma3DS#989]
Was wondering if it might be possible to increase the current delay time for splash screens, or perhaps make it configurable in the setup menus. Some options would be 3 seconds, 5 seconds, or 7 seconds depending on what's possible. This would benefit users who have CTRNAND splash screens with details like their contact information in case the system is lost or stolen.

**Comment by Qyriad** [comment]
If this is approved I can implement it.
