### ISSUE TITLE
"An exception occurred" every time I boot up  3ds

### ISSUE THREAD

**Issue by johnwayneh** [LumaTeam/Luma3DS#993]
System model:

[Old3DS]

SysNAND version (+emu/redNAND version if applicable):

 [11.6.0-39E SysNAND]

Entrypoint (How/what you're using to boot Luma3DS):

[Boot9Strap 1.3]

Luma3DS version:

9.0

Luma3DS configuration/options:

Default EmuNAND: (1)

Screen brightness: (4 )

Splash: (Off )

PIN lock: (Off )

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

Explanation of the issue:
This happened  when I updated Luma for version 9.0 , I rebooted the console and there was a black screen with a lot of numbers.
Now every time I boot the console it happens. 
It says: 
Processor: ARM11 (core 1)
Exception type: prefetch abort (svcBreak)
Fault Status: Debug event 
Current process: pm (000000000000000) 
Note: I can open the luma config menu and the chainloader.

Steps to reproduce:

1. Turn on the console 

2. Wait 3 seconds 

Dump file:
[crash_dump_00000057.zip](https://github.com/AuroraWright/Luma3DS/files/1594156/crash_dump_00000057.zip)

**Comment by ghost** [comment]
Can't reproduce; try the [Nintendo Homebrew](https://discord.gg/C29hYvh) Discord for tech support debugging problems.
