### ISSUE TITLE
How do I debug the .dmp crash files

### ISSUE THREAD

**Issue by meepingsnesroms** [LumaTeam/Luma3DS#994]
I just get this error with gdb:
Reading symbols from C:\Users\Emily\Desktop\RetroArchDev\PullRequestForks\RetroArch\retroarch_3ds.elf...done.
"C:\Users\Emily\Desktop\Debug\Xmb3DS\dumps\arm11\crash_dump_00000012.dmp" is not a core dump: File format not recognized

I was using arm-none-eabi-gdb.exe from devkitPRO, not windows or linux gdb.

Visual Studio says "Debugging older format crashdumps not supported.".

They are not readable in a text editor.

There is no guide anywhere on these files.

So what should I use to read them?

**Comment by ghost** [comment]
You use the Exception Dump Parser included in the releases or in the source code under `exceptions`. It requires Python and is installed via `setup.py` like any other standard Python package.
