### ISSUE TITLE
compiling error???

### ISSUE THREAD

**Issue by Shadow322** [LumaTeam/Luma3DS#997]
What do i update?

c:\Build_Luma3DS\Luma3DS\sysmodules\rosalina/source/menu.c:199: undefined reference to `MCUHWC_GetBatteryLevel'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [build/rosalina.elf] Error 1
make[1]: Leaving directory `/c/Build_Luma3DS/Luma3DS/sysmodules/rosalina'
make: *** [build/rosalina.cxi] Error 2

**Comment by ghost** [comment]
See 522f105, you need (at least) [ctrulib commit 3bbd2dc](https://github.com/smealum/ctrulib/commit/3bbd2dca163042de947e3c823db227f1d79906d2).

**Comment by Shadow322** [comment]
@Hikari-chin um im lost now do i compile it or what and where do i add it to my environment?

**Comment by ghost** [comment]
Clone the latest ctrulib, `cd ctrulib/libctru`, `make`, then `make install` (`sudo make install` may be necessary if your environment is located in a privileged area).

**Comment by Shadow322** [comment]
thanks just a little nudge in the right direction is all i needed
