### ISSUE TITLE
Shutting down 3ds wile memory card managment is active crash 3ds Luma

### ISSUE THREAD

**Issue by Nogardrevlis** [LumaTeam/Luma3DS#998]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

11.6.0-39E 

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap/Sighax

**Luma3DS version:**

9.0.0 stable

**Luma3DS configuration/options:**

Default EmuNAND: (1)

Screen brightness: (3)

Splash: (x)

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: (x)

Use EmuNAND FIRM if booting with R: (x)

Enable loading external FIRMs and modules: (x)

Enable game patching: (x)

Show NAND or user string in System Settings: (x)

Show GBA boot screen in patched AGB_FIRM: ( )

Patch ARM9 access: ( )

Set developer UNITINFO: ( )

Disable ARM11 exception handlers: ( )

--

**Explanation of the issue:**

I accidentally pushed power button wile i was in microSD card management mode , the 3ds went black and Luma error handler showed arm11 error screen , i tried this a second time just for curiosity it crashes every time i guess normally the power button should be disabled but isn't in sd card management so the system doesn't know what to do and crashes

**Steps to reproduce:**

1. Open microSD card management 

2. Press power button

**Dump file:**

[crash_dump_00000004.zip](https://github.com/AuroraWright/Luma3DS/files/1602106/crash_dump_00000004.zip)

**Comment by Margen67** [comment]
Duplicate issue. https://github.com/AuroraWright/Luma3DS/issues?utf8=%E2%9C%93&q=is%3Aissue+microsd+error
